### ISSUE TITLE
TB - Infrastructure

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1000]
## Issue
For TB encounter, there will be different entries. Through case management: TB suspect is created in AI or ANC module and through individual encounter there will be TB Management module.

TB Management encounter can be reached as follows:
`Clinical` --> `Individual Encounter` --> `TB Management` 

Selection of Individual Encounters | TB Management Activity Screen 
--|--
![Screenshot from 2024-01-24 15-41-10](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/4b17ceef-3329-4843-a427-8421a271facb) | ![Screenshot from 2024-01-24 15-42-24](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/65ed1172-11e8-41dd-854c-91ef80d91d83)

## Logic
1. Respiratory - Cough, conditional question to ask if the cough has been present for 2 weeks or more
2. Diagnosis - two-week cough = TB Suspect, overrides other potential diagnosis

## Todo

- Set up infrastructure
-  Add screen for TB Management as per the usual setup
- Add activity icons
- Implement the Logic

**Comment by balagan73** [comment]
## QA Review

### Checked and approved:

1. The details of this issue were confirmed in other issues, for example:
https://github.com/TIP-Global-Health/eheza-app/issues/1017
https://github.com/TIP-Global-Health/eheza-app/issues/1001#issuecomment-1985536200
https://github.com/TIP-Global-Health/eheza-app/issues/1002#issuecomment-1985571284
