### ISSUE TITLE
TB - Diagnosis

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1001]
## Issue
There are 2 question for diagnosis activity:

Was this person diagnosed with TB? 
2. Where is the TB located?

When the user entered from case management , they will start with  question 1. If it is a new diagnosis/new encounter they start with question 2.

This activity only appears on the first TB Management encounter

![Screenshot from 2024-01-24 16-14-47](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/509150ab-cd0c-4366-a130-1fe62289c8d5)

## Todo

- Implement as per design
- implement the Logic

**Comment by adamhstewart** [comment]
@anvmn Note: this subactivity appears only in the first TB Management encounter (edited description)

**Comment by balagan73** [comment]
## QA Review

### Checked and approved

1. The 2 questions display under diagnostic. Second question only displays if person was diagnosed with TBC

No TBC|TBC
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e662df9d-5bec-4869-8f10-3644faf4ff2f)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/ef9a674a-6a8a-4f0b-8077-0908cc722b23)

2. Diagnosis doesn't display at subsequent encounter
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/87042167-4112-468b-a87a-c8d293f9ac0a)
