### ISSUE TITLE
TB - Medications

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1002]
## Issue
Medication will have 3 sub activities.

Note: Prescribed medications only appears in the first TB Management encountert

Prescribed Medication | DOT | Treatment  Review
--|--|--
![Screenshot from 2024-01-24 16-24-40](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/af3d75b8-f3ea-4b89-8dbb-55d8cbbd20ec) | ![Screenshot from 2024-01-24 16-39-15](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/7db53b90-9d01-47a4-94c1-c4f5706541b8) | ![Screenshot from 2024-01-24 16-39-55](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/d8f6a2d6-aca7-40d5-86f6-d77e97b0413c)

For the DOT activity if the answer is No this will be a sub question for both the :
Why not:
- meds already taken today
- [not indicated] only for "Will you provide DOT/TDO today?"
- med unavailable
- advised to hold b/c of side effects
- patient refused

## Todo

- Create the activities per design

**Comment by anvmn** [comment]
@adamhstewart 

**Prescribed Medication**:
 - Should we allow multiple selection?
 - Third option looks strange to me. Can you confirm the wording please?
 - Shouldn't we add another option for 'no medication prescribed'? If we do, how would this affect the DOT activity?	

**DOT/DTO**:
- Issue description says something about additional question if No answer is given. It's not clear for which question is it (description says both but it does not make sense to me).



Also, I'll need the **icons for the tasks**.

**Comment by Diama1** [comment]
@anvmn 
> **DOT/DTO**:
> 
> * Issue description says something about additional question if No answer is given. It's not clear for which question is it (description says both but it does not make sense to me).

The additional question will come when we say No to both of the questions. But the difference will be only for "Will you provide DOT/TDO today?" we will add [not indicated] .
For example: for the first question 
Why not?
- meds already taken today
- not indicated
- med unavailable
- advised to hold b/c of side effects
- patient refused

for the second we remove  [not indicated] option

**Comment by adamhstewart** [comment]
> Should we allow multiple selection?

Yes

> Third option looks strange to me. Can you confirm the wording please?

Wording is correct

> Shouldn't we add another option for 'no medication prescribed'? If we do, how would this affect the DOT activity?

Medication is always prescribed for TB. The "exit ramp" here is "other"

> Issue description says something about additional question if No answer is given. It's not clear for which question is it (description says both but it does not make sense to me).

"No" to either question on the DOT subactivity reveals the conditional question: "Why not?"

With the possible responses (multiple selections possible):
- meds already taken today
- not indicated (only an option for the first question, not the second)
- med unavailable
- advised to hold b/c of side effects
- patient refused

> Also, I'll need the icons for the tasks.

Prescribed medication: use the medications icon from the main activity
DOT: I will ask from Nora
Treatment review: we have this subactivity in other places in Acute Illness (use same icon).

**Comment by anvmn** [comment]
@adamhstewart 

Where should we pull this info from?
Should it come from prescribed medication sub activity? If so, should we present DOT only after  prescribed medication is completed?

![Selection_184](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/6c1b7217-b2c7-4033-8891-1030f078905c)

**Comment by adamhstewart** [comment]
@anvmn yes it’s pulled from the prescribed medications subactivity which only appears in the first encounter.

**Comment by anvmn** [comment]
@adamhstewart 

> @anvmn yes it’s pulled from the prescribed medications subactivity which only appears in the first encounter.

Does this mean that DOT activity appears only at subsequent encounters?
What about Treatment  Review?

**Comment by adamhstewart** [comment]
@anvmn I suppose at the first encounter we should present the prescribed medications first, and then only after it’s answered the other two sub activities.

**Comment by adamhstewart** [comment]
@anvmn 

> DOT: I will ask from Nora

Instead, make a circle version of the treatment review icon:
<img width="208" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/aa175165-cd6a-4456-8bb6-69b3ba988130">

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Checked and approved

1. After filling out the Prescribed medication form, the DOT and Treatment review subactivities display beside it.

Prescribed medication|All 3 sub-activities
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/9999727f-5bf5-4de2-932c-835c611ce20a)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/555b352f-0476-4031-87bd-6a26bc071f87)

2. DOT/DTO subactivity displays according to requirements.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/5bcfe938-c0e3-48c0-9d2d-d82255f33ddb)

3. Treatment review subactivity displays according to requirements

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/739da612-e02f-48ab-88a6-af303e443862)

4. Prescribed medication subactivity only displays at first encounter. 
Subsequent encounter:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/bd1641b0-a5c7-4777-83c4-f0b60c08c6ff)
