### ISSUE TITLE
TB - Symptom review 

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1003]
## issue
In order to enhance for accurate assessment, we have added the symptom review activity. This activity appears only in subsequent TB encounters.

![Screenshot from 2024-01-24 17-26-04](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/477d8c49-7146-42ae-90e5-6f8210068f6c)

## Todo

- Create the questionnaire of symptoms

**Comment by adamhstewart** [comment]
~@Diama1 Please add detail to this original issue to clarify:~
~- This extra symptom review subactivity is for the acute illness module when a patient reports a cough > 2 weeks (and is therefore a TB suspect). It will sit under "Symtom Review" and can be titled TB Suspect~
~- Cough greater than 2 weeks is an automatic TB Suspect diagnosis and overrides any other diagnosis~
~- The popup before next steps should read "TB Suspect with XXXX" (with XXXX being the chosen symptom in this new sub activity.~

~cc // @anvmn~

My confusion, this is for subsequent tb management encounters only.

**Comment by balagan73** [comment]
## QA Review

### Checked and approved:

1. Symptom review icon displays only at subsequent encounters
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/094ff7b3-ccf5-424d-a6d1-74c48379b2ce)

2. Questions are according to requirements.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/1ca2fca2-6d02-46e5-a926-d38c601043cc)
