### ISSUE TITLE
TB - Next steps 

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1004]
## Issue
If the patient has Adverse Reaction to the medication, exhibits positive symptoms during symptoms review, then they should be referred to the Health Center.   There will also be health Education to be give to the patient and Follow up screen. Screens are  as it is depicted below:

Referral | Health Education | Follow-up 
--|--|-- 
![Screenshot from 2024-01-24 17-38-54](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/beb121f1-b328-45f4-b555-197814604e30) | ![Screenshot from 2024-01-24 17-48-15](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/3914eae6-f98c-4344-b996-ad6f1e926f9e) | ![Screenshot from 2024-01-24 17-48-54](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/d4a06266-d40d-4674-8d32-89538dcaf575)

## Todo

- Style next steps screen per design

**Comment by anvmn** [comment]
@adamhstewart 

If I understand the requirements correctly, Next Steps activity, with ~~all 3 tasks~~ send to HC task appears if any of these 2 situations occur:

1. Adverse Reaction to the medication reported - Medication activity, treatment review task.
2. Any positive symptom reported - Symptom review activity.

_Edited_: Other 2 are displayed always.

Is this correct?

**Comment by adamhstewart** [comment]
@anvmn ^^ correct

**Comment by adamhstewart** [comment]
@anvmn this is the table for the Health Education.

Month | Test | Actions
----- | ----- | -----
Month 1 | xPert, Culture, and DST | Reassess treatment according to results, continue first-line treatment if drug susceptible.
Month 2|  xPert, Culture, and DST | Reassess treatment according to results, continue first-line treatment if drug susceptible.
End Month 2| Smear microposy at the end of the intensive phase | If positive, Culture and DST - Continuation phase.
End Month 5| Smear microposy  | If positive, Culture and DST, and retest after 15 days
End Month 6| Smear microposy  | If positive, Culture and DST, and retest after 15 days, if negative - cured.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Checked and approved

1. Follow up form looks correct
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/9644ffbe-bb37-4cda-bed2-695fad0a8e07)

2. Health Education form looks correct
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/8a5dfb37-18eb-471d-a195-7599f58f02bd)

3. Send to Health Center form looks correct.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/6a8fe81a-7041-40d4-9124-5e7888c09ca5)
