### ISSUE TITLE
Changes to Lab Results workflow - diagnostics and next steps

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1005]
Since it's now possible to perform all tests either right away or at lab, we can have labs dependent diagnoses now at both phases of encounter:

**Tasks** :

- Identify required changes
- Apply new diagnostics for both phases of encounter
- Adjust expected next steps at both phases of encounter

[Master logic sheet](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

**Comment by anvmn** [comment]
**Labs which results could only be filled at initial phase:** 
 - Malaria
 - HIV
 - Partner HIV

**Labs which results could only be filled at recurrent phase:** 
- Blood group and rhesus
- Hemoglobin
- Hepatitis B
- HIV PCR
- Syphilis
- Urine Dipstick
- Random Blood Sugar

**Comment by anvmn** [comment]
**Diagnoses derived from labs:**

- Malaria: 
  -  DiagnosisMalaria
  -  DiagnosisMalariaMedicatedContinued
  -  DiagnosisMalariaWithAnemia
  -  DiagnosisMalariaWithAnemiaMedicatedContinued
  -  DiagnosisMalariaWithSevereAnemia

- HIV:
  - DiagnosisHIV
  - DiagnosisDiscordantPartnership

- Partner HIV    -    none

- Blood group and rhesus:
  - DiagnosisRhesusNegative

- Hemoglobin:
  -  DiagnosisMalariaWithAnemia
  -  DiagnosisMalariaWithAnemiaMedicatedContinued
  -  DiagnosisMalariaWithSevereAnemia
  -  DiagnosisModerateAnemia
  -  DiagnosisSevereAnemia
  -  DiagnosisSevereAnemiaWithComplications

- Hepatitis B:
  - DiagnosisHepatitisB

- HIV PCR:
  - DiagnosisHIVDetectableViralLoad

- Syphilis:
  - DiagnosisSyphilis
  - DiagnosisSyphilisWithComplications
  - DiagnosisNeurosyphilis
  - 
- Urine Dipstick:
  - DiagnosisDiabetes
  - DiagnosisGestationalDiabetes
  -  DiagnosisModeratePreeclampsiaInitialPhase
  - DiagnosisModeratePreeclampsiaRecurrentPhase
  - DiagnosisSeverePreeclampsiaInitialPhase
  - DiagnosisSeverePreeclampsiaRecurrentPhase
  - DiagnosisModeratePreeclampsiaInitialPhaseEGA37Plus
  - DiagnosisModeratePreeclampsiaRecurrentPhaseEGA37Plus
  - DiagnosisSeverePreeclampsiaInitialPhaseEGA37Plus
  - DiagnosisSeverePreeclampsiaRecurrentPhaseEGA37Plus

**Comment by balagan73** [comment]
## QA Review

### Found issues:
1. Syphilis with rash on body should have resulted in syphilis with complications. Also neurosyphilis displays only as positive syphilis. Is this OK?

With complications|Neurosyphilis
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/83d6fbbc-e7b6-4975-ae77-4273762c2d84)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/9850aa62-7265-45b9-a86f-2dc2cf15e080)

2. Not related to this issue, but after filling out the Malaria prevention subactivity the subactivity is not complete, until lab subactivity is completed. Actually I have changed some data in Core examination, and now Malaria prevention shows completed. Image 2 shows next patient, now Malaria prevention displays even after Lab is filled out. Now checking back on the page after I filled out the report, the Malaria prevention is not displayed anymore. It needs to sync data?

1|2
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e6f55eef-252b-480a-b550-df4aae03293f)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/5cc7aaaa-7ab9-445c-9689-b14d51eeaa97)

3. When entering data for sever preeclampsia (110/160, crackles, +1 protein, EGA>37), warning and diagnosis differs. Is this OK? At recurrent encounter only warning displays, no hospital referral takes place. Is this OK?

Warning|Diagnosis
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/d5b58a84-8be4-4f4f-b0b1-f8481add8e32)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/67f2d88f-07f1-476f-a572-8d622a67c777)

4. Pamela was diagnosed with recurrent mild to moderate preeclampsia (Patient is referred to hospital in next steps (EGA < 37)). Her data stays Reviewed under case management, and I can only Leave encounter, but cannot end it. Adeline had severe preeclampsia, situation is the same.

Pamela|Adeline
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/6777b5b8-010f-4c6c-96ca-f04984b70540)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/63d7ba4f-18da-4a47-b9e4-36e64fa7c21f)

5. Sometimes cannot save data. Clicking the button did not change anything on UI, have to refresh the page.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/4f2b76a9-4425-4db2-98b9-f51b849a0f13)

6. When user has HIV PCR in subsequent encounter, regardless of the count nothing changes.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/67ee49f4-b2a0-4588-acd1-c36a12860d7e)


### Checked and approved:
1. After Lab Technician enters lab results and Nurse reviews them, patient is diagnosed with
- HIV
- Syphilis
- Hepatitis B
- Malaria with Anemia
- Gestational Diabetes
- Mild to Moderate Preeclampsia
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/b894bf51-9c89-4cbb-b1f0-9a6198380613)

- Rhesus negative
- Discordant partner
- Malaria with severe anemia
- Severe preeclampsia
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/584dadfc-7e93-4a5b-b956-f2f48917fec8)

- Severe anemia
- Diabetes
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e156a095-b387-4587-83ce-4ce5ff884bcf)

- Mild to moderate anemia
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/a0f7bc49-ba00-4a78-a8b6-9436dd448ce0)

- Mild to moderate preeclampsia, recurrent. Patient is referred to hospital in next steps (EGA < 37)
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/4bfa42a1-ec63-42aa-b337-234c4d5bd002)

- Patient with severe anemia and complications (RR > 30) is referred to hospital.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/3892b414-33a3-43b1-830e-f7a8adbeb21a)

**Comment by adamhstewart** [comment]
Issues here are either OK or addressed as followup in #1031
