### ISSUE TITLE
TB Management - Entry 

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1017]
## Issue

TB Management will sit alongside other individual encounters:

<img width="219" alt="Cursor_and_Acute_Illness___CHW_–_Figma" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/625129e3-d5a3-4486-b22a-55d04678d3e8">

After the encounter is selected, the CHW will choose a patients, as usual

<img width="660" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/b87f611c-8228-4a74-9604-dc231dbf4852">

There is no need to select "First" or "Subsequent" encounters, as a patient without an open TB case will have a "first encounter" and a patient with an active TB case will have a subsequent encounter

## Tasks
- Create the button and add to the individual encounter screen
- choose patient screen
- Add logic to determine encounter type

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Checked and approved:

1. TB Management option is available for CHW workers
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/97b1c57e-bcaf-42a9-878e-51bf5c7ed604)

2. After selecting TB Management, a participant can be selected:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/dd6ec76f-4313-4b8a-8197-4448f465f616)

3. After selecting the patient, Tuberculosis encounter type can be selected
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e93df304-701d-4e29-9a73-e1f02c00842a)
