### ISSUE TITLE
TB Management - initial & subsequent encounters

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1019]
- Diagnosis activity appears only at initial.
- Medication activity:
  - Prescribed medications task only appears in initial.
  - At initial encounter at first only Prescribed medications task appears. When completed, other 2 tasks should appear
-  Symptom review activity appears only at subsequent encounters.

**Comment by balagan73** [comment]
## QA Review

### Checked and approved:

1. Medication activity logic was confirmed in report here:
https://github.com/TIP-Global-Health/eheza-app/issues/1002#issuecomment-1985571284

2. Prescribed medication doesn't display at subsequent encounters.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e1b57df5-a61f-4fda-89db-bc03f7d4ed17) 

3. Symtptom review icon displays only at subsequent encounter.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/7292c464-bd03-4c28-8127-0c28ee5c7109)
