### ISSUE TITLE
TB Management - Translations

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1022]
## Issue
Translation for Kinyarwanda and Kirubndi for TB Management module - most strings should be available now for translation

## Tasks
- Translation in Kinyarwandsa
- Translation in Kirundi

**Comment by adamhstewart** [comment]
@Diama1 Kinyarwanda handled in #1053 - leaving this open for Kirundi.

**Comment by anvmn** [comment]
Deployed to live
