### ISSUE TITLE
Group Education - Entry - Health Education

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1034]
## Issue 

As there are two different encounters for this group encounter, we will have child nutrition and Health education.
![Screenshot from 2024-02-28 13-34-15](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/b7b16285-f7a5-4dd9-ba7a-0b75bbef96a1)

## Tasks

- Add Entry for Health Educations per designs

**Comment by Diama1** [comment]
@adamhstewart while creating this issue I got to wonder, will there be a group assigned to each topic or it will be for everyone in the system?

**Comment by anvmn** [comment]
@adamhstewart Deployed to Nutrition env

**Comment by LudmilaGoichman** [comment]
@anvmn 

- https://nutrition-ihangane.pantheonsite.io/
- Android tablet/Chrome

### Checked and Approved:
1. two different encounters have been added for the group encounter for CHW

<img width="382" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1d00ffb0-2165-4597-b45c-5f135fd8f56d">

2. Health Educations entry has been added: 
<img width="1228" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a1add329-c5c9-48a1-99c6-29f3564f6dcf">
