### ISSUE TITLE
Group Education - Infrastructure [6h]

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1043]
## Issue 

For storing the info from these sessions, we will need to create an Education Session content type that will hold the 
- session topics
- participants that attended
- time and date of the session
- Village for which this session was done
- performing nurse/chw

## Tasks
- Create the content type
- Create the infrastructure to sync content from the frontend to back end.

**Comment by anvmn** [comment]
@adamhstewart Deployed to Nutrition env

**Comment by LudmilaGoichman** [comment]
@anvmn 

- https://nutrition-ihangane.pantheonsite.io/
- Android tablet/Chrome

### Checked and Approved:
1. Education Session CT is created:
<img width="1080" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/89c9d243-74b4-4a56-a311-90b9f1e030da">

2. A node is created when performing a health education encounter. All fields mentioned in the description exist in the CT: 
<img width="759" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c7e89292-f44a-4128-9a3c-6a5b5554ebba">
