### ISSUE TITLE
Group Education - Health Education Topics

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1044]
## Issue

As for Health education, we have a list of health education topics that will be given.
The list of all the Education topics:

- Tuberculosis
- STDs & Prevention of HIV
- Mental Health Diseases & Epilepsy
- Malarial diseases and the use of mosquito nets
- Childhood illnesses( Prevention, danger signs & emergency case management)
- Malnutrition (The prevention and fight against diseases caused by malnutrition)
- Antenatal Care, Postnatal Care & Danger Signs in Pregnancy
- Family Planning & Sexual and reproductive health
- Gender equality, Gender-Based Violence (GBV) & Behavior change
- Non-Communicable Diseases(Diabetes , Hypertension & Asthma)

![Screenshot from 2024-02-28 16-39-24](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/ea1a08fc-84ff-4655-9754-aa474fda1163)

## Task
- Create the screen as per design
- Create the logic for the selection of the topics

**Comment by anvmn** [comment]
@adamhstewart Deployed to Nutrition env

**Comment by LudmilaGoichman** [comment]
@anvmn

- https://nutrition-ihangane.pantheonsite.io/
- Android tablet/Chrome

### Question:
I think this space should be removed: 
<img width="386" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2480c760-5af7-45a5-8bc8-9e246825ad13">

### Checked and Approved:
1. The list has been created:

<img width="386" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5292534f-2672-451e-ad17-8594fb8e3afa">

2. Education topics are selected in Education Session CT node

<img width="1094" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4623e7cf-ad1a-4165-b031-10f430d8e579">
