### ISSUE TITLE
Group Education - Attendance Record

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1045]
![Selection_326](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/417120be-ad67-4a78-9745-de988a29ae16)

**Comment by anvmn** [comment]
@adamhstewart Deployed to Nutrition env

**Comment by adamhstewart** [comment]
@anvmn we need the option to be able to display all as we have in other group encounters:
<img width="761" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/a112f3f4-e1c2-487b-bcd5-6120a86f3f18">

In this case it should read: "Display all people"

**Comment by adamhstewart** [comment]
@anvmn  also note that the submit button should read "Record Group Education"

**Comment by anvmn** [comment]
@adamhstewart 

Required changes implemented. Deployed to Nutrition env.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app/

## QA Review

### Found issues and questions:

1. Link says Display/Hide all participants, not Display all people per https://github.com/TIP-Global-Health/eheza-app/issues/1045#issuecomment-2013196992. 
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e54c2109-ee86-4244-b324-fb64ffdc6909)

2. Not related to this issue, but a space is missing before the parentheses on the Health topics and other pages, where topics are listed.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/da4306a6-7165-4378-856a-1ce2fe4ab405)


### Checked and approved:

1. There is an option to display all participants, button label reads Record group education
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/4eca23a5-40b1-4570-bba5-35f99fb15fb1)
