### ISSUE TITLE
TB Management - Update cough duration [6h]

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1051]
## Issue

As for TB management, an individual becomes a TB suspect if, through acute illness, cough persists as a symptom for a period of 2 weeks or more. 

As such we need to change the cough duration field to reflect a diagnosis for TB:
~~Less than 2 weeks~~
~~2 Weeks or more~~
- 2 Weeks or less
- More than 2 weeks

## Task
- Add the new field and deprecate the old field
- Create infrastructure to handle the new field
- Update the UI on the forntend

**Comment by anvmn** [comment]
@adamhstewart what do we do about progress report then?

**Comment by anvmn** [comment]
@adamhstewart 

> @adamhstewart what do we do about progress report then?

This is what I've implemented, so we can make use existing if fields and get all needed info:


![Peek 2024-03-11 11-57](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/57e39caa-4b10-498d-b99e-062bde383069)

Will this do?

**Comment by adamhstewart** [comment]
@anvmn ^^ Unfortunately, no - we need to convert to the two options as described, I assume this means a new field and infrastructure.

For the purposes of the progress report, we can assume less than 2 weeks to be 7 days and  more than 2 weeks to be 15 days.

**Comment by anvmn** [comment]
@adamhstewart 

> For the purposes of the progress report, we can assume less than 2 weeks to be 7 days and more than 2 weeks to be 15 days.

It's 2 weeks or more, so I'll make it 14. This way we maintain consistency with max duration of other signs.

**Comment by anvmn** [comment]
As discussed at catch up meeting:

Periods are:

- 2 Weeks or less
- More than 2 weeks

**Comment by anvmn** [comment]
@adamhstewart deployed to Nutrition env

**Comment by balagan73** [comment]
### QA Review

## Found issues and questions

- None

## Checked and approved

1. Options on UI are updated
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/4b731b76-0edf-4149-972c-96346b638454)
