### ISSUE TITLE
TB Management - Case management for TB Suspect [4h]

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1052]
## Issue

After the individual has been found as a TB Suspect through Acute illness, a case management followup should be created in TB Management rather than in Acute Illness.

![Screenshot from 2024-03-04 22-43-52](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/5e5696d1-fe7f-4b8d-84d0-f803e5c634a9)

## Task
- Create the Case management followup

**Comment by anvmn** [comment]
@adamhstewart deployed to Nutrition env

**Comment by balagan73** [comment]
### QA Review

## Found issues and questions

- None

## Checked and approved

1. Case management follow up is properly created under Tuberculosis
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/4f897362-4c04-4a97-bf23-64881a8ae533)
