### ISSUE TITLE
TB Management - Add AI Diagnoses TB Suspect [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1055]
## Issue
A cough of two weeks or longer is considered a TB Suspect, and it overrides any diagnosis.

The popup for diagnosis should read Tuberculosis Suspect:
<img width="844" alt="Cursor_and_E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/275c8346-77cb-4a50-94d3-81430eb025e2">

Next steps items are:
- Refer to health center
- Followup

**Comment by anvmn** [comment]
@adamhstewart 

If I remember this right, COVID was most urgent diagnosis, where we would show next steps right after diagnosis was made.
Other diagnoses required 3 or 4 activities to be completed, to resolve the diagnosis.

How should we treat DB? Given more than 2 weeks cough, make the diagnosis right away + show next steps?

**Comment by adamhstewart** [comment]
> How should we treat DB? Given more than 2 weeks cough, make the diagnosis right away + show next steps?

We should complete the full activities - For COVID it was a matter of isolation. Here it's not a concern.

**Comment by anvmn** [comment]
@adamhstewart 

> > How should we treat DB? Given more than 2 weeks cough, make the diagnosis right away + show next steps?
> 
> We should complete the full activities - For COVID it was a matter of isolation. Here it's not a concern.

In this case, it can override all diagnoses except for COVID.

**Comment by anvmn** [comment]
@adamhstewart 

> Next steps items are:
> - Refer to health center
> - Followup 

We have AI both for nurse and CHW.
If it's CHW that's running the encounter, it makes sense to refer to HC.
What do we do for nurse? Refer to hospital?
Or maybe, TB suspect should be determined only by CHW?

**Comment by anvmn** [comment]
@adamhstewart 

> Next steps items are:
> - Refer to health center
> - Followup 

For the context, at AI first encounter we determine (possible) diagnose.
Subsequent encounter will be available (in other words illness will remain open) is diagnose was made.
Subsequent encounter is used to track illness progress and reaction for treatment.
As a result, next steps at these encounters are different.
For example, at subsequent encounter, we send to HC if there was no improvement.

So the question is what should be next steps at subsequent encounter?

**Comment by adamhstewart** [comment]
> What do we do for nurse? Refer to hospital?

I believe in this case, we should do nothing (don't provide the refer to HC subactivity) - in real life, they would be referred for TB testing, but we don't have that concept yet.

> Subsequent encounter will be available (in other words illness will remain open) is diagnose was made.

My recommendation is that until we handle TB at the HC, we close the illness in favor of it being handled as DOT at the CHW (which is designed to track illness progress and reaction to treatment).

> In this case, it can override all diagnoses except for COVID.

not necessarily - if the cough question comes before a COVID diagnosis, it should take priority.

**Comment by anvmn** [comment]
As discussed at catch up meeting:

- If cough more than 2 weeks - cancel COVID path, so that we get TB suspect as diagnosis.
- For nurse, only task at next steps is follow up.
- When encounter completed and TB suspect identified, close the illness (no subsequent encounter at this stage).

**Comment by anvmn** [comment]
@adamhstewart deployed to Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Found issues and questions

- None

### Checked and approved

1. User is diagnosed correctly

Coughs more than 2 weeks|2 weeks or less
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/1289a8b3-22e8-4083-a19e-3fd8ed993289)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/254ed3c3-d5e8-4aaf-9ccf-d870ef3d3a56)

2. Next steps items are correct

Referral|Follow up
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/aa1840c3-76b6-4fd4-99d4-a47ae4cfa5a9)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/05360181-f981-45cc-9c56-dbf1888bb835)
