### ISSUE TITLE
Change logic for Insecticide treated bed net

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1057]
## Issue
The logic in the aggregated scorecard is different than the logic in the individual card. In the individual card, the patient gets a check for every time the question is asked (and it is asked on every visit)

<img width="762" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/45b89974-1377-48c2-a175-3f217be2894c">

In the aggregated scorecard, a single yes answer in any month applies to all months for the child

The logic should change  to match the individual scorecard (as is the case for all of the other items in this panel)

**Comment by anvmn** [comment]
@adamhstewart 

This change implies changing structure of NCDA data stored at patient node.
This mean we'll have to regenerate data for all patients (~85K).
On Pantheon, script processes ~10K and hour, so we'll  need to run it overnight.
