### ISSUE TITLE
Group Education - list all possible patients when search is empty

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1077]
Per https://github.com/TIP-Global-Health/eheza-app/issues/1045#issuecomment-2013196992

<img width="761" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/a112f3f4-e1c2-487b-bcd5-6120a86f3f18">

**Comment by LudmilaGoichman** [comment]
@anvmn

- https://nutrition-ihangane.pantheonsite.io/
- Android tablet/Chrome


### Questions:
1. Why do participants from other villages appear on the list? marked with a pink marker

<img width="1029" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/375434e7-da2d-4a6f-808c-b080f692375a">|<img width="1067" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ae20935b-567b-4b3d-8acf-492b83698525">
---|---

2.  When clicking on the "Hide all participants" link, the list becomes empty, but selected participants are kept, and the Record Group Education button is enabled and can be clicked. Is it okay?
### Checked and Approved:
1. "Display all participants" link appears: 
<img width="390" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0e979b48-76da-4b6d-9fc1-69f6ea938a99">

2. When clicking on this link, participants from the selected village appear in the list (but additional participants also appear - see question above): 
<img width="390" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c84d50ec-0d96-4370-9fdf-687f4b8439d7">

3. When clicking on "Hide all participants" link, the list becomes empty

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1. Why do participants from other villages appear on the list? marked with a pink marker

Well, I don't think that what you say is correct.
Patient is resident of the village, if it's 5 geofields match those of the village.
If we take Test 2534 for example, we have a match.

![Selection_334](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/d91ca569-9d6e-4d33-9ff4-9a5cdcaa134b)
![Selection_335](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/c4ead597-b05e-4ed8-8efc-ebd9445c27ec)

Now there may be some confusion at issue definitions that link between participants and village chw group, which is correct. CHW group participants are mother+child pairs, and they're mainly about child nutrition, while
at group education we allow all adults among village residents to participate.


2.  When clicking on the "Hide all participants" link, the list becomes empty, but selected participants are kept, and the Record Group Education button is enabled and can be clicked. Is it okay?

Yes, similar to nutrition group sessions.
