### ISSUE TITLE
Whats App - support multiple languages [6h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1081]
Message should be sent in language that is currently selected.
If no translation available, default to English.

**Comment by anvmn** [comment]
@Diama1 

Please provide translations for:
`Hi from Tip Global Health. The @report-type progress report for @patient-name from @date. Thank you.`

The ones start with `@` are params, so leave them as is.

Thanks,

**Comment by Diama1** [comment]
> @Diama1
> 
> Please provide translations for: `Hi from Tip Global Health. The @report-type progress report for @patient-name from @date. Thank you.`
> 
> The ones start with `@` are params, so leave them as is.
> 
> Thanks,

@anvmn  ` Muraho.  TIP Global Health yifuje kubasangiza raporo y’ibyakozwe muri serivise y' @report-type ya @patient-name yo ku itariki @date. Murakoze.`

**Comment by anvmn** [comment]
@Diama1 

Thanks. Can we get a Kirundi translation as well?

**Comment by Diama1** [comment]
> @Diama1
> 
> Thanks. Can we get a Kirundi translation as well?

let me ask for it

**Comment by anvmn** [comment]
Delivered to live
