### ISSUE TITLE
Feature: HIV Management

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1083]
## Feature Description
In my capacity as a Community Health Worker (CHW) in Burundi, I play a crucial role in following up with HIV patients  within my community. When community members has been tested HIV positive from the community, I prescribe the medication and provide health Education and other medical support they might need.

Additionally, I provide ongoing support to community members who have been diagnosed with HIV at the health center. Upon learning that an individual is HIV Positive, I undertake the following activities:

- **Diagnosis Activity:** This involves confirming that the person is HIV Positive and the time they were diagnosed
- **Medication Activity:** I actively engage in prescribing the medication and  follow-up activities to ensure patients are consistently consuming their prescribed medication.
- **Health Education:** I provide Health education about the diet, family planning, safer sex practice,...
- **Symptom review:** I conduct reviews to identify any symptoms that could exacerbate the virus and make appropriate referrals when necessary.

## Logic Document 
Can be found  [here.](https://docs.google.com/document/d/1YgzVvIgXOPRbmtOOBUVUxIbliWxmKew5PaNglFrn8_s/edit)

## Acceptance Testing
COMING SOON.

## Tracked Issues - HIV Management
COMING SOON.
## Flowchart: 
https://www.figma.com/file/bxkN6TXMRFcoWP29b1qfD4/Acute-Illness-%40-CHW?type=design&node-id=2-3&mode=design&t=U6pMSHwmMbmJb0QY-0

**Comment by anvmn** [comment]
@Diama1 I suppose we need to add descriptions similar to #999. Please do.

**Comment by Diama1** [comment]
> @Diama1 I suppose we need to add descriptions similar to #999. Please do.

done

**Comment by balagan73** [comment]
## QA Review

### Checked and approved

As all individual features were tested separately, I think this can be accepted as well.

#1093 #1094 #1112 #1086 #1085 #1084
