### ISSUE TITLE
HIV Management - Entry

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1084]
## Issue

HIV Management will sit alongside other individual encounters:
![Screenshot from 2024-03-27 12-14-22](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/2a467926-e560-47f3-86ef-eb5056f70941)

After the encounter is selected, the CHW will choose a patients, as usual

<img width="660" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/b87f611c-8228-4a74-9604-dc231dbf4852">

There is no need to select "First" or "Subsequent" encounters, as a patient without an open HIV case will have a "first encounter" and an HIV positive patient case will have a subsequent encounter.

## Tasks
- Create the button and add to the individual encounter screen
- choose patient screen
- Add logic to determine encounter type

**Comment by anvmn** [comment]
@adamhstewart

Deployed to Nutrition env. Ready for QA.

**Comment by balagan73** [comment]
## QA Review

### Checked and approved:

1. HIV management activity displays among the other activities.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/3fd1a333-61ab-42e4-bd44-cfca138671e2)
