### ISSUE TITLE
HIV Management - Diagnosis

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1085]
## Issue

When a patient comes for the first time for HIV management, the positive test date should be obtained (or estimated). Once the positive test date for this HIV management participation has been established, it does not need to be asked in subsequent visits.

### If the patient has a positive HIV lab test in E-Heza** 

- Show: The patient tested positive for HIV on [date]
- Ask: Is this correct (Yes/No)
- If yes, record the date of HIV management as the "positive test date"
- If no, Ask "Date of positive test:" while providing an "Estimated" check box (as in birthdate for patient registration)

<img width="810" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/96bc2e83-fbc2-4cca-856b-8c0fbf5c8758">

| Yes(Date is Correct) | No, Date is not correct | 
| ---------------------------- | --------------------------------- |
| ![Screenshot from 2024-04-01 16-46-19](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/cca76032-9e53-49c6-972b-1caed9412f27) | ![Screenshot from 2024-04-01 16-46-29](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/c6ad6132-6535-4780-818e-e5cc0c4332ca) |

** Note: there are quite a few ways in E-Heza where we record a patient's HIV status (registration, ANC Partner information, etc.). In this module, we are only concerned with a positive HIV Lab test, HIV status is otherwise ignored for the purpose of this module.

### If the patient does not have a positive HIV lab test in E-Heza
- Ask: "as this person diagnosed with HIV? "
- If no, exit activity.
- If yes,  Ask "Date of positive test:" while providing an "Estimated" check box (as in birthdate for patient registration)

![Screenshot from 2024-04-01 16-52-08](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/79ecad0f-ec4d-4f2b-9d0d-e5a411718d0d)

## Todo

- Implement as per design
- implement the Logic

**Comment by anvmn** [comment]
@adamhstewart 

> and if only they have not been previously diagnosed

How do we define this?

**Comment by adamhstewart** [comment]
@anvmn I re-wrote the issue to answer the question and provide some more scope for this activity.

@Diama1 we need some designs to reflect these changes that were discussed.

**Comment by Diama1** [comment]
> @Diama1 we need some designs to reflect these changes that were discussed.

@adamhstewart Done

**Comment by anvmn** [comment]
@adamhstewart

Deployed to Nutrition env. Ready for QA.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Found issues and questions


### Checked and approved:

1. If patient was not diagnosed with HIV, encounter is ended

2. If patient was diagnosed with HIV, question about test date appears.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/df27940f-2112-45ea-a2b6-a3144af0c7a0)

3.If the patient tested positive for HIV, lab test date appears in question:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/9429de64-3c7d-412a-8f45-dea0f2fb15ef)

**Comment by adamhstewart** [comment]
@anvmn Change "What was the positive test date?" to "When was the positive test date?"
