### ISSUE TITLE
HIV Management - Symptom Review

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1086]
## issue
In order to enhance for accurate assessment, we have added the symptom review activity. This activity appears only in subsequent HIV Management encounters.

![Screenshot from 2024-03-27 12-56-19](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/fa899ed5-9053-4969-9897-4fe57dd89a08)

## Todo

- Create the activity of symptom review

**Comment by anvmn** [comment]
@adamhstewart

Deployed to Nutrition env. Ready for QA.

**Comment by balagan73** [comment]
## QA Review

### Checked and approved:

1. Symptom review activity displays in subsequent HIV management encounters
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/bc5624d1-b8f2-44fa-b929-fff7d2569575)
