### ISSUE TITLE
HIV Management - Encounter Infrastructure [6h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1089]
Tasks:
- Create infrastructure for Participant and Encounter pages
- Start encounter logic

**Comment by anvmn** [comment]
@adamhstewart

Deployed to Nutrition env. Ready for QA.

**Comment by balagan73** [comment]
## QA Review

### Found issues and questions:


### Checked and approved:

1. HIV encounter is implemented
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e55530c8-ee6d-42f7-b401-43a8b1892b3d)

**Comment by balagan73** [comment]
@anvmn What are the Participant pages? I have checked the participant directory, but did not see any HIV related data.

**Comment by anvmn** [comment]
@balagan73 

> @anvmn What are the Participant pages? I have checked the participant directory, but did not see any HIV related data.

Participant page is the one you added at screenshot.
That's the page where we have decision logic of to start encounter and create new participant, or subsequent encounter for existing participant.
