### ISSUE TITLE
HIV Management - Next Steps

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1094]
![Selection_354](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/c58629aa-0487-4533-8f46-9f7ba82d13dc)
![Selection_355](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/d04b856a-1e17-4c0b-bcde-b1f8c54b6938)
![Selection_356](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/5ecf5232-4259-4b30-b138-a329cb1229ad)

**Comment by anvmn** [comment]
@adamhstewart

Deployed to Nutrition env. Ready for QA.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Found issues and questions:

- None

 ### Checked and approved:

1. Send to Health center screen looks and works correctly.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/ba70cc4f-2cd5-4166-8e58-2349900527bf)

2. Health education tab looks good.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e7b0eb41-585c-49d7-92bd-fdc690604e14)
 
 3. Follow up tab looks good.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/b7f480a8-9e23-4804-b66e-2d4eaa81f895)
