### ISSUE TITLE
Group Education - Dashboard

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1096]
## Issue

**Section 1**
Once there have been a group education session it will be recorded on the dashboard as follows:
Number of Group session | number of group encounters on health education in this specified month.
Total attendees | total number of all the participants in those Group session that took place in that specific month
Unique Patients |  the number of patients in the month that showed up for any group education.

**Section 2**
The Group Education | topics that were covered in the group education this  specified month.
Attendance | Number of people who attended the session on that topic

On the topics table, once the user click on the blue arrow, they will see the list of participants on that specific education topic session. The list will appear only at Community level. At health center level on the list of topics we will not have the arrows. 

| Landing page | Group education |Once you click on a topic arrow |
| -------------------- | ------------------------- | -------------------------------------------- |
| ![Screenshot from 2024-04-02 14-57-08](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/706b1cca-2eec-453c-8e75-0cc1451b0ea4) | ![Screenshot from 2024-04-02 14-58-05](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/c6e30e4e-34d7-409c-b6bd-4cf07474ca9b) | ![Screenshot from 2024-04-03 16-27-54](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/228c3da0-e349-4313-bc6f-2f9103bd73c1) |

## Todo
- Create the screen per design
- Implement the Logic

**Comment by anvmn** [comment]
@adamhstewart

Deployed to Nutrition env. Ready for QA.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app/#dashboard/group-education

## QA Review

### Found issues and questions

1. The list on the group education page contains the different educations, not the topics as shown in the issue description.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/f84769d8-8b3c-4b5a-8fd2-69a14f7a9ea4)

2. The consequence of point #1 is that when clicking on the arrow, the participants of the specific session are listed, not the participants in a specific topic.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/12cb4d5e-2872-4271-ae4c-95fc5e21c00d)

### Checked and approved:

1. The Dashboard page contains a Group education tab.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/18402783-c130-49b0-82d6-f39cb1b9d3c2)

**Comment by anvmn** [comment]
@balagan73 

I believe that current behaviour is correct. Each entry presents a session with all it's topics.
Had it been the way you describe it, there would be no meaning to the date.
