### ISSUE TITLE
RM - Guide Message

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1102]
Issue

Create a screen that will give the guide message to the users.
The message will appear when the user enters in the program. It will be added to the other tabs.
![Screenshot from 2024-04-05 13-11-40](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/723e3465-88e9-4c5e-855f-e1ab07536e8d)

## Todo
- Create the screen as per design

**Comment by anvmn** [comment]
@adamhstewart 

Deployed to RM env (https://rm-ihangane.pantheonsite.io/)

**Comment by anvmn** [comment]
Deployed to live
