### ISSUE TITLE
Make HIV status non-required on Patient Registration [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1104]
## Issus

On the patient registration screen, we ask a patient's HIV status: 

![image](https://github.com/TIP-Global-Health/eheza-app/assets/688507/e4522d15-406d-4550-be1a-56958ca92da8)

For privacy reasons (in some cases where registration is done in context where HIV status is confidential), the question needs to be non-required.

## Tasks
- Make the question non-required

**Comment by anvmn** [comment]
Deployed to live
