### ISSUE TITLE
HIV Managment - Can't register a new patient [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1123]
## Issue

In the HIV Management workflow, a new patient can't be registered

https://www.loom.com/share/0dab0f984ba1469db7d6d52c3501a8ee?sid=33742470-26b2-4024-902b-726ac99d9f84

## Task
- Allow registration of new patients

**Comment by anvmn** [comment]
Fixed and deployed to live
