### ISSUE TITLE
Support latest DDEV [3h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1125]
DDEV 1.23.0 drops support for Python2.
We need to adapt infrastructure to overcome this.

**Comment by amitaibu** [comment]
@AronNovak maybe part of this issue is also to fix the issue I have on installation

![image](https://github.com/TIP-Global-Health/eheza-app/assets/125707/2c7cef76-d58b-4de5-8265-c87a8bbd4643)
