### ISSUE TITLE
If a nurse chooses a Malaria test in the laboratory, the test does not show up.

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1127]
1. Nutrition env

patient: Akuzwe Nadege

If a nurse chooses a Malaria test in the laboratory, the test does not show up. //and there is no enabled "Pause encounter" button

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b724d6f2-d09b-4e63-88fa-6e9dfad7759a">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e4d3ea15-cb02-47e7-acb4-5666e9470e62">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/74b824c1-d9e9-43ac-a3f6-f704df45e8e8">
---|---|---

2. Nutrition env. Patient Cyiza Maria

When the nurse selects "Point of care" for the Hemoglobin test and "Lab" for the Malaria test 

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7bc46eec-f46b-4e9b-9329-7d4586ca2bbd">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b952a0b2-7126-41ea-8923-a867bec324de">
---|---

The "Severe Anemia" diagnosis appears, and there is no enabled "Pause encounter" button

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/768e9c85-5f80-4714-9341-25a3916572f5">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/fab8268c-360f-480d-a6be-5c5390e2b665">| <img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d2196cb2-8a88-4ae9-b1aa-98f15adc8381">
---|---|---

And no test for Malaria in the Lab:

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bb631378-422f-437b-9c38-cabe2f9e42fc">

**Comment by anvmn** [comment]
> If a nurse chooses a Malaria test in the laboratory, the test does not show up. //and there is no enabled "Pause encounter" button

Fixed at #1139

> When the nurse selects "Point of care" for the Hemoglobin test and "Lab" for the Malaria test, The "Severe Anemia" diagnosis appears

In this scenario, we Severe Anemia, and don't wait for Malaria test.
Logically, this makes sense, as next step for Severe Anemia is hospital referral.
Once at hospital, if diagnosed, Malaria will be treated as well.

**Comment by anvmn** [comment]
Deployed to live
