### ISSUE TITLE
When a nurse selects “Lab” for Hepatitis B test, the diagnosis for Hepatitis B and Referral activity don't appear. (and other scenarios)

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1128]
Nutrition env

1. When a nurse selects “Point of Care” and the tests are positive for Hepatitis B and Malaria, two activities appear: Medical Distribution and Referral. I think only Referral should appear

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4316066c-ebe6-49f0-bec9-ffb1d345d0d1">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/64e323f0-7ac5-491a-b4b2-29de03128447">
---|---

2. When a nurse selects “Point of Care” and the tests are positive for Hepatitis B and Malaria, the diagnosis appears twice. And when Malaria is negative

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4316066c-ebe6-49f0-bec9-ffb1d345d0d1">| <img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/68d65c99-6140-42b5-be00-e90371be4c9e">
---|---

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4593bb4b-e54d-4881-aae6-33cea2e6deb6">

3. Patient Akuzwe Gossy

When a nurse selects “Lab” for Hepatitis B test and the test is positive (and Malaria is negative - “Point of Care”), the diagnosis for Hepatitis B and Referral activity don't appear. 

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/503f666f-dea2-4a37-b27c-9c104be6b39a">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4626ed4a-4866-484b-8a33-ad8de57fadc0">
---|---

4. Patient Akuzwe Ketsia

When a nurse selects “Lab” for Hepatitis B and the test is positive (and Malaria is positive - “Point of Care”), the diagnosis for Hepatitis B and Referral activity don't appear. The Malaria diagnosis and Medical Distribution action are displayed before the lab test, and after the Medical Distribution action is completed, a Pause Encounter button appears.

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2b5e589d-3568-46fd-9aaf-586dafc5b28c">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c381f112-e120-4724-8857-9cffc97bc84a">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ba528a51-6486-4b3e-9fd9-a11327ef8ac1">
---|---|---

**Comment by anvmn** [comment]
There's no relation between Malarial and HepB. The confusion is from Logics Master file - seems someone has changed by mistake:

![Selection_458](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/e1e4cabd-c33a-4e2e-8b54-7a5ec30217aa)

While it should be:

![Selection_457](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/7fce85bb-0df9-4246-9614-79117a5e0c6d)

**Comment by anvmn** [comment]
> When a nurse selects “Point of Care” and the tests are positive for Hepatitis B and Malaria, two activities appear: Medical Distribution and Referral. I think only Referral should appear

No, both should appear.

Points 2, 3 and for are fixed at #1140.
