### ISSUE TITLE
ANC @ Health Centers - Medication - Mebendazole [3h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#113]
## Issue

We are updating ANC @ Health Center - Subsequent Visit - Medication Activity to fit clinical protocols. 

While pregnant, a patient should receive one dose of Mebendazole (500mg). She must be over 24 weeks EGA. She must NOT have received this medication in the last 6 months. 

Here is the updated design: 
<img width="340" alt="Screen Shot 2022-01-26 at 3 37 53 PM" src="https://user-images.githubusercontent.com/77505464/151243138-f32baddb-89ef-44ea-8871-ee762e621bb6.png">

If the answer = yes, then this question should reappear at every subsequent visit.

If the answer = no, we will prescribe the medication in the next steps and the question will not reappear. If no, these are the next steps that should populate: 
<img width="232" alt="Screen Shot 2022-01-31 at 2 45 52 PM" src="https://user-images.githubusercontent.com/77505464/151861922-bb34b13c-a337-4441-9daa-1649f722a425.png">

## To Do: 

- Update ANC @ Health Center - Subsequent Visit - Medication Activity to fit styling 
- Update next steps per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Just found out that Mebendazole is actually a deworming medecine.
FYI, we already have a deworming pill question at Medication form.
It's current logic - displayed untill answer is YES, starting EGA week 20.
Seem to me this is a duplication. How would you like to treat this.

//cc @adamhstewart

**Comment by jeanette-pelizzon** [comment]
This should replace that existing screen and logic.

**Comment by adamhstewart** [comment]
## QA Analysis

### Works as designed
- Question appears after 28 weeks (and not before) 
- Question reappears if answered "Yes"

### Needs followup
- If answered "No" There is no instruction to distribute the medication in next steps.

**Comment by anvmn** [comment]
@adamhstewart 

> If answered "No" There is no instruction to distribute the medication in next steps.

Note that Next steps activity will appear only after we have Danger Signs activity completed.

**Comment by adamhstewart** [comment]
@anvmn For a given patient, I completed all activities (including danger signs) and I did not get the medications sub activity

![Selection_999(199)](https://user-images.githubusercontent.com/688507/160739458-279bc417-8810-49b9-9917-05ca245bad2b.png)

All activities complete:

![image](https://user-images.githubusercontent.com/688507/160739542-646aa4ce-be82-4738-992e-78fa9fcfdb6b.png)

**Comment by anvmn** [comment]
@adamhstewart
When diagnosis results in emergency referral to hospital, there are no other next steps.

**Comment by jeanette-pelizzon** [comment]
That is true, when a flow is interrupted and a patient is referred to a hospital we prioritize them being sent to get care immediately. However, if they are referred to the hospital at the end of an encounter  (aka not an emergency refferal) then they should also get mebendezole.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. When patient answers No to the question "Has the mother received Mebendazole in the last 6 months?", then Medication distribution subactivity displays under Next steps.

Medication|Next steps
-|-
![1-not-received](https://user-images.githubusercontent.com/3536805/177931500-ec56b4e4-0410-4f0c-be6e-45c60a31b049.png)|![2-meds-distribution](https://user-images.githubusercontent.com/3536805/177931508-01acb1ed-c3fd-4290-9147-084d8505c188.png)
