### ISSUE TITLE
RM - Enable the system to incorporate phase 2 messages

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1136]
##Issue

Currently, we have resilience messages available for 68 days, which will be utilized for the pilot phase. Additional messages up to 6 months of the program will be incorporated into the system for phase 2 before the pilot concludes.

##Todo
- Redesign the backend to incorporate phase 2

**Comment by anvmn** [comment]
@Diama1 

Configuration for this is pretty simple. What we need are the definitions for messages added:
- What is the text
- What is the category
- What is the display day (or week)
