### ISSUE TITLE
When a patient has Chronic Hypertension/ Gestational Hypertension/ Mild to Moderate Preeclampsia, a Lab Technician has entry in the Case Management, but doesn't have an activity

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1150]
Nutrition env, patient Cyiza Gossy

Chronic Hypertension or Gestational Hypertension (all cases)

a Lab Technician in the Case Management:

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/419f7d13-e455-4112-bc33-8939f6e700c5">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7ec47bc5-9780-4360-b924-b5dfcd909912">
---|---

Questions:
1. When a nurse measures blood pressure in Case Management, the report is opened after saving the activity. Is it okay?

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b5fdc5a4-ecd3-4c5a-a314-bec25f628a01">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/523e1fb5-3cde-478f-b9a5-315e5656b11b">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2395e22e-ca9d-4884-a5b9-55a220eaf3c1">
---|---|---

2. The medical distribution activity contains the third option for all cases (the second case contains only two options):

<img width="1083" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/990272bf-2f25-40fd-a7c2-0ce4e09c02db">

(1) EGA < 20 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours) | (3) EGA <20 weeks + systolic >=140mmHg to <160 x 2 (separated by >2 hours)
---|---
<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7596cec0-e924-4d65-9564-af5073af18cf">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0ae322e7-fe91-4fb0-9df7-f73574e35646">

**Comment by anvmn** [comment]
@LudmilaGoichman 

> a Lab Technician in the Case Management:

Fixed at #1164 

> When a nurse measures blood pressure in Case Management, the report is opened after saving the activity. Is it okay?

Report should show up when all activities are completed. One of previous issues delivers a fix for this.
So, will need to retest after new version is deployed.

> The medical distribution activity contains the third option for all cases (the second case contains only two options):

Not sure what option you're talking about, but if I understand properly, what is written at Excel file is not what is shown. In this case, the APP is the source of truth. So, if both VHW and Nutrition envs show the same options, it's ok.

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Found Issues:
1. Mild to Moderate Preeclampsia. (1) EGA >=20 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours) + >= +1 urine protein (point of care). Patient: Akuzwe Julia. 
a Lab Technician has entry in Case Management but doesn't have an activity

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2b456e38-a4a9-452a-b132-85c0e7099b36">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/79ec6121-3e06-4b61-ae4d-3bf4ef83b8d9">
---|---

2. Mild to Moderate Preeclampsia.  (3) EGA >=20 weeks + systolic >=140mmHg to <160 x 2 (separated by >2 hours) +  >= +1 urine protein (point of care). Patient: Akuzwe Orietta. 
a Lab Technician has entry in Case Management but doesn't have an activity

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b4326698-f7da-4f4a-b20e-f289b8180d4a">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cf1f66b7-0ad6-4c6f-a309-ec3e572df9fd">
---|---

### Checked and Approved:
1. All cases (except in "Found Issues") are fixed
2. I also performed negative tests (where blood pressure in the second test is normal)
3. I also performed tests with combined symptoms

**Comment by anvmn** [comment]
@LudmilaGoichman

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn

- Nutrition env
- Android tablet

### Checked and Approved
1. Mild to Moderate Preeclampsia. (1) EGA >=20 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours) + >= +1 urine protein (point of care). 
a Lab Technician hasn't entry in Case Management 

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f473b81c-87e3-4cc9-a358-a65c6fbfcfb3">

2. Mild to Moderate Preeclampsia. (3) EGA >=20 weeks + systolic >=140mmHg to <160 x 2 (separated by >2 hours) + >= +1 urine protein (point of care). 
a Lab Technician hasn't entry in Case Management 

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8caf74f5-3a44-48f4-8974-d01ba1fc9ede">

**Comment by anvmn** [comment]
Deployed to live
