### ISSUE TITLE
Severe Anemia with Complications

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1151]
Hemoglobin < 7g/dL + RR > 30  - Severe Anemia with Complications

1. Env VHW, patient Benimana Florence
 
Diagnosis is shown on a referral activity, but does not appear as a pop-up:

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/805307d6-697f-4e0f-9bc7-6842700b2240">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2870b28d-e5e7-4810-9f21-36765a2d4c9f">
---|---

2. Nutrition env, patient Tuyishime Annet

There are no diagnosis and a "Next Step" activity

- when the Hemoglobin test is "Point of Care"

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c0b5f03b-8946-4fff-b57c-26064de9ca67">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/951ca18b-d7cb-40c7-af8d-9359e8f3f532">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b7db9152-7189-45e4-8e2f-efaf8275c202">
--|--|---

- when the Hemoglobin test is "Lab"

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d74160be-9ea2-4eef-b853-c5dacc04b19a">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b7ece0fb-0066-4675-8842-5d4ceedf8162">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a32e2c36-e502-4345-a51b-e665d8634b02">
--|--|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> Env VHW, patient Benimana Florence
> Diagnosis is shown on a referral activity, but does not appear as a pop-up

What image shows is not a popup, but alerts indicator. It does not include diagnoses.
Diagnostics popup shows up after result is set for urgent diagnoses, and navigation to next steps for regular diagnoses.

> There are no diagnosis and a "Next Step" activity

Fixed at #1165

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
### Question and Found Issue:
1. Question: When a hemoglobin test is performed at the point of care, the diagnosis appears when the test is saved. In the VHW environment, the diagnosis appears after all tests are completed and the Next Steps activity opens. This is right?

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7a4a570a-4e44-4206-9c19-2a11f9e8b44c">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ac6e5473-7d8c-4540-b7d9-38867c628ac7">| <img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f94b6290-42e8-4303-80a1-1cde7517c827">
---|---|---

2. Patient: Akuzwe Queen. When a hemoglobin test is performed at the lab, diagnosis doesn't appear

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ddeb7c1f-c5ae-4bdc-9197-37319bd1b7d7">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f700f9e6-0c6a-429e-a61d-8ca6a932029c">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/79ebba54-2a2f-404c-97ca-91ed6034f755">
---|---|---

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7c0519fd-f199-4886-afa7-a996f251ec12">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/528c6394-d231-4dc4-bae0-70c1ee2eaf1c">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/50c695c5-4f21-46a7-8583-876574de3204">
---|---|---


<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d6b011c8-1382-449e-9752-77b40952ac11">

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1. Question: When a hemoglobin test is performed at the point of care, the diagnosis appears when the test is saved. In the VHW environment, the diagnosis appears after all tests are completed and the Next Steps activity opens. This is right?

Current behaviour is correct. We're dealing with emergency diagnosis, and therefore, need to refer to hospital right away.

![Selection_533](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/84565bea-d561-4581-9761-2ce75f96bbf7)

VHW env is from 8 month ago, and possibly, there was a change request. Another option is that we had a bug there.

>2. Patient: Akuzwe Queen. When a hemoglobin test is performed at the lab, diagnosis doesn't appear

Fixed at #1171

**Comment by anvmn** [comment]
@LudmilaGoichman

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Question:
When a hemoglobin test is performed at the lab, the diagnosis and next steps appear for the Lab Technician when he/she saves a hemoglobin test. Can the lab technician refer the patient to the hospital?

Patient Cyiza Aurore

Nurse:

<img width="260" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/77a03951-1e45-4ae3-bd70-41dfb45e2649">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/79c1793f-661d-4343-bb36-5656d1fea9a1">
---|---

Lab Technician

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c4c5d329-1a4d-4fb0-a511-5dfddc101b6d">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/77bd4667-c943-4096-8b56-904ecf387176">
---|---

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/158bab87-21c7-4760-b473-b57ac0d359e1">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/41db03f3-8e45-4569-a4ae-78a89c1b4023">
---|---

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9caaf125-23d0-4b64-91a1-90dc50ceef50">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c5f04230-01b7-4420-acf8-99d07284ac33">| <img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/55dde214-701b-4620-b70f-bef56535e03b">
---|---|---



Nurse:

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a9e3be5b-e7c0-41a6-98fa-8247dd87074c">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ac30f223-6e25-48d3-abcf-63c20eafc015">
---|---

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/96a7f915-462e-48b1-b002-471e280adc63">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bc5698f8-e827-437a-85d9-bdc4499e97b2">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9e647813-b1ad-445d-8332-2e0f4097c2de">
---|---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> When a hemoglobin test is performed at the lab, the diagnosis and next steps appear for the Lab Technician when he/she saves a hemoglobin test. Can the lab technician refer the patient to the hospital?

No, lab tech can not refer patient anywhere, since patient is not present. Current behaviour happens because lab result cases diagnostics of urgent diagnosis, and urgent diagnoses are treated right away.
We should make following change in this case:
- For lab tech - no reaction 
- When nurse enters from case management - navigate to Next Steps activity and view Warning popup with info about urgent diagnosis / diagnoses.

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Checked and Approved:
The nurse referred the patient to the hospital.

nurse

<img width="265" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e7ebdf9e-988f-4422-b30b-f78935a08f69">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d85ccecd-d42f-4298-8e75-e4e835e882e1">
---|---

lab technician

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b9f7ebf1-50c8-4a61-850f-bce4ec9e4b9d">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a49aaa43-6e19-4401-ad6f-098949877111">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5fff610d-8b44-4c58-a6c6-453e56516720">
---|---|---

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f6231b4b-0e39-474e-9350-bd0f753db594">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3a77507e-810c-4419-9fb7-936cbe96d7e9">
---|---

nurse

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ad586c8a-ced3-4d4d-8bc8-a8187fed9940">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3fd5e77a-e6a2-4b83-8218-ebd0356de889">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0f7d3a9d-f729-4065-86f9-747923a44a76">
---|---|---

**Comment by anvmn** [comment]
Deployed to live
