### ISSUE TITLE
Questions about diagnoses

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1152]
Nutrition env

1. Why is this diagnosis “Malaria with severe anemia”? And why is the test for hepatitis B only in the lab? Should it be another diagnosis?

<img width="628" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4227402c-21e3-4b17-90ef-bc54ce95ffa2">

2. Why do diagnosis (and maybe treatment) not appear if the answer is "yes" to the following questions? Is it okay?

<img width="402" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7ea8d020-bcb5-48a0-9cf5-3667650674e8">| <img width="404" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/06e9c823-ba91-4790-bcdf-eb325b410c44">
---|---

3. Why doesn't "Counsel on safer sex practices" appear when the test can't be made? // in vhw env, "Counsel on safer sex practices" appears with this option

<img width="429" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/68dae58b-bfaf-4b6b-8bc9-d8f1c10e938b">

4. Why doesn't "Counsel on safer sex practices" appear in the next steps if the answer to the following question is "yes"? (it appears when the test is positive) Is it okay? 

<img width="379" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7f85e56a-9889-4a0e-bb9d-eb540e097ae8">

5. Why is the diagnosis from the Logic Master file (Gestational Hypertension) different in environments (Nutrition and VHW)?

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8487cc2c-022a-4a73-8ca8-38366e0f2070">

6. Why does an alert not appear when EGA >=20 weeks + diastolic >=90 to <110 mmHg  (Gestational Hypertension)? In both env: Nutrition and VHW

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cf0a668b-324e-47e9-971d-03113072a69d">

When EGA < 20 weeks + diastolic >110 (Chronic Hypertension), the alert appears 

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6963ae61-4eeb-4976-955d-b0e54c7e6ac4">

And when Systolic is high (when EGA > or <20 weeks), the alert also doesn't appear.

7. Mild to Moderate Preeclampsia. Why is the "Leave encounter" button enabled when the diagnosis is ready and the "Next Steps" include a "Referral" activity? (in both env - nutrition and VHW)
 
<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/63ec0652-808c-441b-a0c5-88b74f839c68">

8. “depression not likely” - this is not depression, right? Why does this sentence appear as a warning? And other diagnoses are not shown. And this sentence appears in diagnoses in the report

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/360a2591-fb50-49f5-83e3-1be8cdd6ac32">
<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a7bf9ce7-7176-468a-bd90-c1d93543c9b2">

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1. Why is this diagnosis “Malaria with severe anemia”? And why is the test for hepatitis B only in the lab? Should it be another diagnosis?

There was a mistake in Excel file. Someone made a change by mistake. This is how it's supposed to be:
![Selection_523](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/fdb6c979-b3e4-4dc8-8783-e50b1668ea58)

> 2. Why do diagnosis (and maybe treatment) not appear if the answer is "yes" to the following questions? Is it okay?

This is the requirement. If known as positive, no next steps.


>3. Why doesn't "Counsel on safer sex practices" appear when the test can't be made? // in vhw env, "Counsel on safer sex practices" appears with this option
4. Why doesn't "Counsel on safer sex practices" appear in the next steps if the answer to the following question is "yes"? (it appears when the test is positive) Is it okay? 

Fixed at #1168


> 5. Why is the diagnosis from the Logic Master file (Gestational Hypertension) different in environments (Nutrition and VHW)?

Per customer request. Gestational and Pregnancy induced is same thing.


>6. Why does an alert not appear when EGA >=20 weeks + diastolic >=90 to <110 mmHg  (Gestational Hypertension)? In both env: Nutrition and VHW

Fixed at #1168


> 7. Mild to Moderate Preeclampsia. Why is the "Leave encounter" button enabled when the diagnosis is ready and the "Next Steps" include a "Referral" activity? (in both env - nutrition and VHW)

At recurrent phase, there may be multiple entries, to update partial labs results for example.
Therefore, we always allow to leave the encounter. 

>8. “depression not likely” - this is not depression, right? Why does this sentence appear as a warning? And other diagnoses are not shown. And this sentence appears in diagnoses in the report

This was already answered (and fixed) in another issue.
Warning because customer asked for indication in any case.
Diagnosis did not appear, because it's an urgent one, and there's dedicated flow for it.
