### ISSUE TITLE
Add icon for case management that was created today [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1154]
## Issue

When a followup that was created today appears in case management, it appears without an arrow (since and encounter can't be created in the same day):

<img width="879" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/8d5ea836-fd52-4a46-a180-9b4d511f13eb">

Rather we should use a grayed out arrow

## Task
- substitute blank space with a greyed out arrow.

**Comment by anvmn** [comment]
Deployed to live
