### ISSUE TITLE
Changes to Treatment Review questions [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1155]
## Issues

Two changes
1. Re-order as indicated below
2.  swap locations to the ye/no answers so that the "good" result is always on the left

![E-Heza_System](https://github.com/TIP-Global-Health/eheza-app/assets/688507/8d72a8b2-bf5f-4410-a986-e9e1dfe20ae5)

**Comment by anvmn** [comment]
@LudmilaGoichman please test on Nutrition env

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Checked and Approved:

Changes have been made to the Treatment Review questions.

<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6188ded9-a064-4831-9b5c-323353984341">

**Comment by anvmn** [comment]
Deployed to live
