### ISSUE TITLE
ANC @ Health Center - Labs - HIV Update

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#116]
## Issue

Based on feedback from the team, we are making changes to the HIV lab flow in ANC. We are adding in an additional question "Is this patient known to be HIV positive?" If yes, then the user will click save and it will update the progress report accordingly in the backend and they will move to the next test. If no, then the questions that we already have programmed will appear. I have updated the design in Figma [here. ](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=6668%3A47492) Quick clickthrough can be found [here](https://www.figma.com/proto/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=6272%3A42250&scaling=scale-down&page-id=5862%3A38746&starting-point-node-id=6668%3A47492&show-proto-sidebar=1).

Quick explainer video [here. ](https://www.loom.com/share/631854e111854ea2b246caf452b2084d)

// @anvmn @adamhstewart

**Comment by anvmn** [comment]
@jeanette-pelizzon 

1. Don't understand this part: `If yes, then the user will click save and it will update the progress report accordingly in the backend`. Please elaborate how progress report needs to be updated.
2. HIV test is done at first encounter, and then at 38 weeks. If the answer is positive and we know patient got HIV, should we be showing HIV test activity again at 38 weeks?

**Comment by jeanette-pelizzon** [comment]
1) the HIV status will need to be shown on the progress report. the logic for this should already exist as it happens at the CHW level as well.  

2) Spoke with Wendy, if positive at first encounter then we do not need to show again at 38 weeks. 

// @anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> the HIV status will need to be shown on the progress report. the logic for this should already exist as it happens at the CHW level as well.

From what I found, at Medical Diagnosis pane, we show the info we got from Medical History activity (taken at first encounter). If HIV question is answered Yes, we'll reflect it at the pane:

![Peek 2022-02-01 10-19](https://user-images.githubusercontent.com/17882245/151934341-5f11fa5e-b028-4b2c-a1a8-e384ed6b2e9a.gif)

It's not clear what change is required.
If it's only the 'Yes' answer to added question, I don't understand why we don't do it if test is ran, and result is positive. Also, there're other tests we run, and they probably also need to be reflected.
I suggest summing up the requirements, and making it a separate issue.

//cc @adamhstewart

**Comment by jeanette-pelizzon** [comment]
I will make the progress report changes a separate issue. I was just trying to explain the whole flow. Sorry for the confusion. 

I don't understand this part of your question "If it's only the 'Yes' answer to added question, I don't understand why we don't do it if test is ran, and result is positive. "
