### ISSUE TITLE
Mild to Moderate Preeclampsia when EGA >= 37 weeks

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1160]
Nutrition env.
Patient: Akuzwe Claudine

(2) If >=37 weeks EGA, refer to hospital for **immediate delivery**

in VHW env, the "Refer patient to hospital immediately" warning appears (patient AKIMANIZANYE Claudine)

<img width="340" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b7cc4c40-2ca9-41ef-9638-9fab8c2d346f">

but in Nutrition env., this warning doesn't appear

// question: Why is diagnosis doesn't appear in the warning?

**Comment by anvmn** [comment]
@LudmilaGoichman 

> (2) If >=37 weeks EGA, refer to hospital for immediate delivery - in Nutrition env., this warning doesn't appear

FIxed at #1162 

>  Why is diagnosis doesn't appear in the warning?

Once urgent diagnoses is set, app opens next steps page and shows warning popup with urgent diagnosis.
The expectation then is for encounter to end, and patient to be sent to hospital right away.
Therefore, standard warning does not include urgent diagnoses.

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Questions/Found Issues:
1. Maternal Mental Health activity. Why is "tasks completed" written when the question remains unanswered? And why isn't the number of questions displayed?

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/96d3abae-ca55-48d7-be77-658fa3b6521b">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d6dce5a3-ee40-4381-9617-b028893f0808">
---|---


2. Why is the diagnosis displayed in the pop-up in 2 cases (and not displayed in other cases)?

EGA >=37 weeks + diastolic >110/systolic  >=160 mmHg +  edema/urine protein | EGA >=37 weeks + diastolic >=90 to <110 mmHg/systolic >=140mmHg to <160 **x 2 (separated by >2 hours)** + edema/urine protein
---|---
<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/02fbcec3-dc86-4ec6-aa44-577f0e297d80">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2315e179-e72a-4342-8a77-2b6983802d21">

3. Why does the pop-up appear after completing these tasks? Maybe the popup should appear after saving edema (Core Physical Exam task) because referral to the hospital is immediate? EGA  >=37 weeks + diastolic >110 +  edema 

pop-up | completed tasks (**marked tasks are not important, right?**) | "symptom" isn't completed| 
---|---|---
<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2d3ef19a-9d18-4a0f-a054-a12769e7ba9d">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1ce8b192-202f-4673-a0a1-5c233f98e1c1">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/25375505-1d5f-4806-8e60-b78cd10b8cfb">


4. EGA  >=37 weeks + diastolic >110/systolic  >=160 mmHg + >= +1 urine protein (lab technician). The diagnosis and next steps appear for the Lab Technician

 Lab Technician:

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/dace71a4-e6a9-4487-a8b2-c45e53bf79db">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/596de3fc-4d03-49fb-8e26-d3718a824a4f">
---|---

Nurse:

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d011b7fb-bd52-476d-b2ef-0c5d03dda087">

5. EGA  >=37 weeks + systolic  >=160 mmHg + >= +1 urine protein (long, labs). After the task with high blood pressure (all activities in the “Examination” task were completed), I gave the lab technician a urine test (without performing other tasks). And I leave the encounter, perform the test with a lab technician, and the pop-up does not appear. When I rechecked this case with all the tasks completed, a pop-up appeared (for a lab technician). This is okay?


### Checked and Approved:
1. the "Refer patient to hospital immediately" warning appears

EGA >=37 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours) + edema in hands | EGA >=37 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours) + >= +1 urine protein (short, point of care) | EGA >=37 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours) + >= +1 urine protein (long, labs)
---|---|---
<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2315e179-e72a-4342-8a77-2b6983802d21">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3cceeb1b-fcdc-4348-9266-27c3c7648abc">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/15c489df-77aa-433c-b25b-e7a103cf29d8">


EGA >=37 weeks + systolic >=140mmHg to <160 x 2 (separated by >2 hours) + edema in feet | EGA >=37 weeks + systolic >=140mmHg to <160 x 2 (separated by >2 hours) +  >= +1 urine protein (long, point of care) | EGA >=37 weeks + systolic >=140mmHg to <160 x 2 (separated by >2 hours) +  >= +1 urine protein (short, labs)
---|---|---
<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/16eee3bd-f302-45e0-9ec3-4ffa8b529a17">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5aaf313f-18e1-4a1d-b363-8f2182299aad">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c5356e96-abe3-44be-983f-40f4ac1ad26e">



EGA  >=37 weeks + diastolic >110 +  edema in feet | EGA  >=37 weeks + diastolic >110 + >= +1 urine protein (long, point of care) 
|---|---
<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5ded67f8-363f-4899-9457-b7f6724ac1fb">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3d70a053-54e6-4718-b55b-c4a7fb37ac1c">



EGA  >=37 weeks + systolic  >=160 mmHg + edema in hands | EGA  >=37 weeks + systolic  >=160 mmHg + >= +1 urine protein (short, point of care)
---|---|
<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cb843930-6c33-476b-a462-2ad6e66736d5">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6f3b819f-1a88-490f-81f2-d90155da2cc9">

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1. Maternal Mental Health activity. Why is "tasks completed" written when the question remains unanswered? And why isn't the number of questions displayed?

There's single task on each form.
Design did not include question number.

> 2. Why is the diagnosis displayed in the pop-up in 2 cases (and not displayed in other cases)?

I suppose you ask why different messages in popup. This should be fixed at #1173.


> 3. Why does the pop-up appear after completing these tasks? Maybe the popup should appear after saving edema (Core Physical Exam task) because referral to the hospital is immediate? EGA  >=37 weeks + diastolic >110 +  edema 

These activities are defined as mandatory. Only when all mandatory activities are completed, diagnosis is determined.

> 4. EGA  >=37 weeks + diastolic >110/systolic  >=160 mmHg + >= +1 urine protein (lab technician). The diagnosis and next steps appear for the Lab Technician

Same issue as at https://github.com/TIP-Global-Health/eheza-app/issues/1151#issuecomment-2120161656.
Fixed at #1173.

> 5. EGA  >=37 weeks + systolic  >=160 mmHg + >= +1 urine protein (long, labs). After the task with high blood pressure (all activities in the “Examination” task were completed), I gave the lab technician a urine test (without performing other tasks). And I leave the encounter, perform the test with a lab technician, and the pop-up does not appear. When I rechecked this case with all the tasks completed, a pop-up appeared (for a lab technician). This is okay?

I think it's same issue as at https://github.com/TIP-Global-Health/eheza-app/issues/1151#issuecomment-2120161656. Fixed at #1173.

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixes deployed to Nutrition env. Please retest points 2 - 5.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Found Issues:
2. The warning is different:

EGA >= 37 weeks + diastolic >110 + >= +1 urine protein (point of care); EGA >=37 weeks + diastolic >110 + edema; EGA >=37 weeks + systolic >=160 mmHg + >= +1 urine protein (point of care); EGA >=37 weeks + systolic >=160 mmHg + edema | other cases
---|---
<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/12007234-3acd-45dd-aeb4-afc26cebedd9">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f3f3805b-0239-47e7-b5dd-1c6eea5e8a16">

3. >Why does the pop-up appear after completing these tasks? Maybe the popup should appear after saving edema (Core Physical Exam task) because referral to the hospital is immediate? 


case |pop-up | completed tasks (marked tasks are not important, right?) | "symptom" isn't completed
-- | -- | -- |--
EGA >=37 weeks + diastolic >110 + edema; Patient Cyiza Stecy|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/295a1bb9-21da-4973-95cf-3ae6ec609c97">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/eecaeb64-61e0-48e3-8315-34b9a808ff3d">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/fe985fc8-1a5d-46b7-b40d-edd434a1b4fd">
EGA >=37 weeks + systolic >=160 + edema; Patient Gatera Adela|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/facf5587-5156-40dd-afbe-2229e5208b6f">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/20baaa4e-0c73-4df6-9660-2c13a8e01070">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f585502e-e751-4ee0-9757-4f0aea887638">

5. >EGA >=37 weeks + systolic >=160 mmHg + >= +1 urine protein (long, labs). After the task with high blood pressure (all activities in the “Examination” task were completed), I gave the lab technician a urine test (without performing other tasks). And I leave the encounter, perform the test with a lab technician, and the pop-up does not appear. When I rechecked this case with all the tasks completed, a pop-up appeared (for a lab technician). This is okay?

Patient Gatera Alphonsine
After urine test by lab technician

Nurse, Case Management:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/de2dd936-5963-4a87-b1fb-2b9e3480bbdc">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b245ed3f-fd9e-4e0a-8aa3-c0a0e07d7015">
---|---

Nurse, Encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/79266a6f-2438-464b-8fb0-bcf728af1280">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9bca59a7-ac7d-48e1-b2e1-9bc43920770e">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b4e4fe30-ec13-4998-8793-ad3de5f43798">
---|---|---

Nurse, Case Management again:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2e61241d-1e93-45b7-8ccf-c6cd5d37420e">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cc3a081f-e62d-46be-b264-3f859e460e46">
---|---



### Checked and Approved:
4.  The diagnosis and next steps appear for the nurse. Cases:
- EGA >=37 weeks + diastolic >110 +1 urine protein (lab technician)
- EGA >=37 weeks + systolic >=160 mmHg + >= +1 urine protein (lab technician)

**Comment by LudmilaGoichman** [comment]
@anvmn 

3. I think that the diagnosis should appear (and referral to the hospital) after saving blood pressure and edema, because it must be immediately. The diagnosis appears after completing other tasks (not all): activities in the Examination task and after Family planning, Medication, Malaria prevention tasks (these tasks are not urgent) + the Danger signs task. 

5. If patient feels bad, and the nurse saves blood pressure and urine protein test for lab technician and doesn't perform other tasks, I think that after results of the urine protein test, the diagnosis and referral to the hospital immediately should appear in the Case management, not after completing other tasks

**Comment by anvmn** [comment]
@LudmilaGoichman fixes deployed to Nutrition env.

Please test:
- Popup message:

![Selection_580](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/72ad61d6-0fc5-4f1c-b1bb-b5ad4c3386f8)

- > f patient feels bad, and the nurse saves blood pressure and urine protein test for lab technician and doesn't perform other tasks, I think that after results of the urine protein test, the diagnosis and referral to the hospital immediately should appear in the Case management, not after completing other tasks.

In words - if results entered by Lab Tech cause diagnostics of Urgent diagnosis, when nurse enters the encounter from Case Management, warning popup should appear, and Next Steps activity should be presented.

> I think that the diagnosis should appear (and referral to the hospital) after saving blood pressure and edema, because it must be immediately. The diagnosis appears after completing other tasks (not all): activities in the Examination task and after Family planning, Medication, Malaria prevention tasks (these tasks are not urgent) + the Danger signs task.

As we discussed, Danger signs is a mandatory activity. Only after it's completion, diagnostics is performed.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Checked and Approved:
Warnings are correct:

EGA >=37 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours)  + edema; |EGA >=37 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours)  + >=+1 urine protein (point of care); |EGA >=37 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours)  + >=+1 urine protein (lab); 
---|---|---
<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d82221aa-6c17-49f0-9e51-6438fcffd453">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a61aaebd-a8a1-45bb-a387-53593f37d00a">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ebf3d01e-a5d4-4dcd-b0e3-b5af9d10534e">



EGA >=37 weeks + systolic >=140mmHg to <160 x 2 (separated by >2 hours) + edem;|EGA >=37 weeks + systolic >=140mmHg to <160 x 2 (separated by >2 hours) + >=+1 urine protein (point of care); |EGA >=37 weeks + systolic >=140mmHg to <160 x 2 (separated by >2 hours) + >=+1 urine protein (lab); 
---|---|---
<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2753cab7-1642-4c84-a60b-fbaf3dfb9a36">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0e3fc22a-f70f-4f3a-bcaf-7d2874180f7d">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b5d5764f-416e-4342-a855-316acce16789">


EGA >= 37 weeks + diastolic >110 + >= +1 urine protein (lab); |EGA >=37 weeks + systolic >=160 mmHg + >= +1 urine protein (lab); 
---|---
<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9710d457-13bd-424e-8050-8eb095d91492">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/91e3eff7-7516-4dc4-8108-3cf2a88097d0">
