### ISSUE TITLE
Mild to Moderate Preeclampsia. (2) EGA  >=20 weeks + diastolic >110 + >= +1 urine protein (labs - urine dipstick)

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1161]
Nutrition env
Patient: Akuzwe Daniella

VHW env
Patient: AYINKAMIYE Jeanne d'Arc

1. Both environments. Before the urine test, the following diagnosis appears. And there is no enabled "pause encounter" button. Maybe the diagnosis should be shown after the urine test?

VHW env:

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/849841dd-5140-4408-bc22-e490ccb979e9">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cf7a6a08-5f24-40db-9d86-f45cba8dd8f4">
---|---

Nutrition env

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/aae91352-de9f-474e-a5cf-c17628530d34">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/24e86069-ee9c-4c30-a278-671bbee94a77">
---|---

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/11cc4741-67bc-4e73-9a2b-f9ee4f2272f3">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/582b06f6-165b-469f-a0f7-af293744f0d0">
---|---

2. After the urine test, in the VHW env, the diagnosis changes. But in Nutrition env, the diagnosis doesn't change (in the Case Management and in the encounter)

VHW env.

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/27a334db-8285-4108-bbb2-b723740e4773">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1bd149ae-68ab-4b39-a251-29e200a5b25a">
---|---

Nutrition env:

Case Management 

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/12edc294-19c9-4139-906b-c4cc581a39e3">

Encounter:

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0e28271b-fbc8-4b92-93cf-ec9513b2f262">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/347b3a3d-2a20-490c-852e-96f6bc7826a0">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> Both environments. Before the urine test, the following diagnosis appears. And there is no enabled "pause encounter" button. Maybe the diagnosis should be shown after the urine test?

First diagnosis show up correctly, as all conditions match:
![Selection_521](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/0e900f18-7206-4516-8c57-c5eec4409f24)

The Wait task shows up only when all other Next Steps tasks are completed:

![Peek 2024-05-15 22-07](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/68bf1b61-9d72-48dc-b50d-55c57d10a14f)


> After the urine test, in the VHW env, the diagnosis changes. But in Nutrition env, the diagnosis doesn't change (in the Case Management and in the encounter)

From my test, it shows up properly. Likely, we have already fixed it when working on previous issues you reported:

![Peek 2024-05-15 22-08](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/fabf37bd-941f-49de-aa88-d4b97ac8e068)

**Comment by anvmn** [comment]
@LudmilaGoichman 

Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Found Issues:
Mild to Moderate Preeclampsia 2 cases - **No diagnosis**
in your video, the urine test is +1, **but I selected +2** (>= +1)

1. EGA  >=20 weeks + diastolic >110 + **>= +1 urine protein (labs** - urine dipstick) Patient Cyiza Adela

<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d8e091e1-ccbb-4132-a60c-f0eab066e30b">|<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/fa394458-83ef-47c7-8511-5d103600cc69">
---|---

<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/65607457-c4e8-4b37-b11a-bf4a893be0a1">|<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1bac37a2-10fc-43ed-9b07-ecca632392c3">
---|---

2. EGA  >=20 weeks + systolic  >=160 mmHg + **>= +1 urine protein (labs** - urine dipstick) Patient Cyiza Adeline

<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/15f2ac13-e604-4c43-97bf-5ad3b8004a9b">|<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9fab8c7d-dca8-49a7-98ef-aea0b993e971">
---|---

<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3bd4874f-f894-4171-8385-550113e1d5ec">|<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6f248a2c-b01a-4a8a-b152-9e8c20b72103">
---|---

### Checked and Approved:
The Wait task shows up only when all other Next Steps tasks are completed:

<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/221738b2-621b-4512-8666-6da3c4bfb2b4">

**Comment by anvmn** [comment]
@LudmilaGoichman 

The problem was that for Lab Tech, assessment message was not sent and diagnosis was not added.
Fixed at #1171.

**Comment by LudmilaGoichman** [comment]
@anvmn

- Nutrition env
- Android tablet

### Checked and Approved
1. Mild to Moderate Preeclampsia 2 cases - the diagnosis and Next step activity appear


EGA >=20 weeks + diastolic >110 + >= +1 urine protein (labs - urine dipstick) 
EGA >=20 weeks + systolic >=160 mmHg + >= +1 urine protein (labs - urine dipstick) 

<img width="357" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d673898c-285f-44be-aeff-fefa43bb1658">

**Comment by anvmn** [comment]
Deployed to live
