### ISSUE TITLE
General - Add No Follow up option on Follow up activity

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1163]
## Issue

Add the "No Follow up " option on the list of the time to follow up options. If no follow up has been selected there will be no follow up displayed in case management.

![Screenshot from 2024-05-14 12-15-38](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/bc82b346-c8d4-469b-beda-e177e9c30f9b)

## Todo

- Add the option  as per design

**Comment by anvmn** [comment]
### Analysis:

**There are 7 types of Follow Ups:**

- Acute Illness
- HIV
- Group Nutrition
- Individual Nutrition
- Prenatal
- Tuberculosis
- Well Child

**There are 4 variations of Follow Up Value:** 
- FollowUpValue
- NutritionFollowUpValue
- PrenatalFollowUpValue
- AcuteIllnessFollowUpValue

**Comment by anvmn** [comment]
@LudmilaGoichman please test on Nutrition env

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition
- Android tablet



### Checked and Approved:

No Follow up option is added on Follow up activity

Nurse

 Individual Nutrition | Group Nutrition PMTCT | Group Nutrition FBF |
|---|---|---
|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8eb2e7c1-849d-47d1-bd56-52214e931341">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f556afa4-f05e-442f-aeac-a43832bbbc2f">| <img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/fade5c76-b192-4fde-be7d-d3dab3526b5d">

Acute Illness | Standard Pediatric visit
---|---
<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d7f8974b-dbae-4d87-9845-eb35cf7331dc">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/188804b5-0721-43aa-9712-b9d91cc61a14">


CHW

Acute Illness | Individual Nutrition | Well Child
---|---|---
<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/27a99d5d-882b-457b-9403-b47cf5be0318">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/83ad19f7-ffd2-4f1c-8e1d-4b86edd0cfdf">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b325c6c3-4d95-4aa4-9ded-84a8ae948092">

Tuberculosis | HIV | Prenatal | Group Nutrition
---|---|---|---
<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bc8f8b5b-cb37-4551-bf55-0d407e2a2047">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6fccb6bd-fd96-4973-981a-ed8ac1f1c2d0">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c5fdd65a-215b-4b2a-8fc2-fa0e60227801">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f8de04be-3da6-437c-8e25-b62adc8f2008">
