### ISSUE TITLE
ANC @ Health Centers - Labs - Hep B Updated

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#117]
## Issue 

Based on feedback from the team, we are making changes to the Hep B lab flow in ANC. We are adding in an additional question "Is this patient known to be Hep B positive?" If yes, then the user will click save and it will update the progress report accordingly in the backend and they will move to the next test. If no, then the questions that we already have programmed will appear. I have updated the design in Figma [here](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=6675%3A47924). Quick clickthrough can be found [here.](https://www.figma.com/proto/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A42717&scaling=scale-down&page-id=5862%3A38746&starting-point-node-id=5862%3A42660&show-proto-sidebar=1)

Quick explainer video [here](https://www.loom.com/share/840e8ae0305e44619e275ecb36794f5e).

// @anvmn @adamhstewart

**Comment by anvmn** [comment]
@jeanette-pelizzon 

1. Description now says HIV. It should be Hepatitic B I assume.
2. Same as for HIV, if we know person is Hepotitis B positive, no need to show the activity at 38 weeks, correct?

**Comment by jeanette-pelizzon** [comment]
1) Oops - I will fix 

2) Yes. Thank you!

**Comment by adamhstewart** [comment]
## QA Analysis

### Works as designed
- Additional question is added along with conditional skip logic

### Needs followup
- The positive status does not show up in the progress report as described in the issues, although I do not see a design for how it is supposed to appear. Should it be with other test results? cc/ @jeanette-pelizzon

**Comment by anvmn** [comment]
@adamhstewart 

> The positive status does not show up in the progress report as described in the issues, although I do not see a design for how it is supposed to appear. 

Progress report status update issue is #154, and will be available for testing after #194 is reviewed and deployed.

**Comment by jeanette-pelizzon** [comment]
@adamhstewart there is a tab on the [Logic Maste](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=2144570215)r with where each diagnosis should fall on the ANC progress report. TB will appear under medical diagnosis.

**Comment by adamhstewart** [comment]
Positive Hepatitis B does not register a medical diagnosis:

![image](https://user-images.githubusercontent.com/688507/160856906-09f21581-058f-46d5-87ef-be5ac10ec50e.png)

**Comment by adamhstewart** [comment]
@anvmn see this is part of #194... moving to ready for review - please move to QA column when it is deployed to environment.

**Comment by anvmn** [comment]
@adamhstewart #194 is now deployed. ^^ can be retested.

**Comment by adamhstewart** [comment]
The scope of this issue is rechecked and approved.

There are two issues that need to be investigated:

1. Progress report does not appear at the end of the vitals recheck/labs entry - this should be addressed in #
2. After the user views the progress report after "next steps" (in the second "part" of the encounter), if the user uses the back arrow, you return to an activity tray for the first party of the activity.

I'll add these to #203
