### ISSUE TITLE
Placenta Previa | Placental Abruption | Uterine Rupture. Wrong diagnosis

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1183]
<img width="1092" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9ddaa0f1-e589-4c3d-933b-53bf15a4a363">

VHW env. Patient AKONIBONEYE Gerardine

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8530471a-879e-46f5-8820-25152bc74f51">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c600fba8-3077-4aff-9cde-7519fde96c89">
---|---

Nutrition env. Patient Gatera Daniella

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cb89a44f-0bd6-456a-ad53-acece8f7eece">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f556a099-e245-487e-921d-44192a1093d9">
---|---

**Comment by LudmilaGoichman** [comment]
@anvmn 

Yes, when EGA > 23 weeks, the diagnosis is correct.

**Comment by anvmn** [comment]
@LudmilaGoichman 

No problem then. Closing.
