### ISSUE TITLE
Premature Rupture of Membranes (PROM). Wrong diagnosis.

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1184]
<img width="1041" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/fa4e2ff0-ce27-49a2-99b0-23bb30e22424">

Wrong diagnosis in both env VHW and Nutrition

VHW env. patient Munganyinka Gerardine

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c940224a-36a9-4420-885c-6e95c475468a">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bc2560c9-ccf3-48ec-9d69-f767b2ef3e33">
---|---

Nutrition env. patient Gatera Huguette

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/594e7c8c-cd0e-4477-8ebe-168652a9b10a">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/53ecc7fb-219f-4146-abfa-05ea2a5da9b4">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

Wrong definitions in Excel file again. 
PPROM is **Preterm** premature rupture of the membranes.
PROM is  premature rupture of the membranes.

In code we have:
![Selection_575](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/bc2317e4-bb16-4b74-9635-6dbb0791c8d3)

So, up to EGA 37 (included) it's PPROM.
EGA 38 and above, PROM.

Updated the Excel:
![Selection_576](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/161086b1-2d67-4d5b-9627-658238b2c20d)

**Comment by LudmilaGoichman** [comment]
@anvmn I rechecked. Everything is correct. Please close this issue.
