### ISSUE TITLE
RM - Fix - the user is prompted to take the survey again after taking it.

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1193]
## Issue
After completing the surveys and refreshing, the user is prompted to take the survey again.

## Todo
- Implement logic to ensure surveys are recognized correctly after refresh.

**Comment by anvmn** [comment]
@Diama1 

I think this problem is solved at #1159. Need to retest.

**Comment by anvmn** [comment]
Deployed to live
