### ISSUE TITLE
Eheza Reports - Prenatal

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1194]
### Tasks:

- Generate data on back-end
- Update recalculation trigger to include new content types used for data generation
- Decode and Store data on client
- Generate and view the report from stored data

![Selection_595](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/12784303-88f5-4664-8747-3b2877d03143)

**Comment by AronNovak** [comment]
@anvmn @adamhstewart I'd have a few questions here.
 - Is it actionable already?
 - "Generate data on back-end" - do we imagine to have an extra table to have this data to fill the table and update it repeatedly from Cron?
 - "include new content types used for data generation" - what are those content-types?
 - "Decode and Store data on client" - @anvmn will you do that part?
 - "Generate and view the report from stored data" - Drush-like report on the backend or inside the Elm app? Based on the previous point, likely it's inside Elm.

**Comment by anvmn** [comment]
@AronNovak
Not sure how urgent this is for @adamhstewart. 

 The idea is to build on top of existing PRs (not merged yet) that have already needed infrastructure in place.
General idea is that every person got a field where json encoded reports data is stored.
There is a mechanism that triggers data recalculation on backend, using AQ.
So when app needs to present a report, backend is queried with needed scope, data for patients in scope is aggregated and passed to app, and the app applies logic to generate report from the data it got.

If you want to add new type of report, it will require extending reports data for patient.
There is also a scrip that regenerated the data for all patients (part of hedley_reports module).

**Comment by anvmn** [comment]
@adamhstewart 

Looked through current implementation. Criteria to determine if pregnancy is active on date X:
 - It's 30 days or more till EDD date - active pregnancy.
 - Less then 30 days till EDD date - completed pregnancy.

Is this what we need?

**Comment by adamhstewart** [comment]
@anvmn  If this is the implementation in the current script, it is incorrect. It should be that Pregnancy is considered active from the date it is registered in Eheza until either 30 days after the EDD OR the pregnancy was marked as concluded.

**Comment by anvmn** [comment]
Deployed to live
