### ISSUE TITLE
Eheza Reports - Acute Illness

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1195]
### Tasks:

- Generate data on back-end
- Update recalculation trigger to include new content types used for data generation
- Decode and Store data on client
- Generate and view the report from stored data

![Selection_594](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/31f6f980-de1f-474e-82ba-bde01319b5f7)

**Comment by anvmn** [comment]
@adamhstewart 

1. We also have TB suspect diagnosis. Should we include it?
2. Do we really need to count None?

**Comment by anvmn** [comment]
@adamhstewart 

When discussing this issue, we said that we'll have 2 date selectors to define a period we want to get report for.

**Total** - the number of diagnoses that were made withing the period.

Other 2 columns are not clear:

**Days from symptoms** - when we run an encounter, we allow recording lots of symptoms. Some diagnoses are determined using a symptom /combinations of symptoms.
Others are determined by lab (Malaria for example). So, we may record many symptoms, and most of them (if not all) will not be relevant for the diagnosis. So, what should be exact logic here.

**# of encounters** - do we have definition for this?

**Comment by adamhstewart** [comment]
> We also have TB suspect diagnosis. Should we include it?

Yes

> Do we really need to count None?

Yes but not include in the count of diagnosis

**Comment by anvmn** [comment]
Deployed to live
