### ISSUE TITLE
Infection. any EGA + fever + RR > 30 OR  extreme weakness (danger signs). There are no diagnosis

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1196]
There are no diagnosis in VHW and Nutrition env. 
for the first case (any EGA + fever + RR > 30) - no diagnosis
for the second case (any EGA + fever + extreme weakness (danger signs)) - Maternal Complications diagnosis (wrong)

1. Nutrition env:
the first case: any EGA + fever + RR > 30. Patient: Gatete Alphonsine

<img width="243" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3d08f164-f6fc-42cf-abcc-71575e4331ef">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6d50aa28-65cd-46ee-8a2f-a0811859109e">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/93edf7aa-0e26-4e3a-b036-f20768b41fe5">
---|---|---

VHW env, patient Adeliphine Niyigena

Question: Should the diagnosis appear when there is a high temperature and no fever in danger signs?

2. Nutrition env:
the second case: any EGA + fever + extreme weakness (danger signs). Patient: Gatete Anaelle

Wrong diagnosis:

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/239e7a18-72ce-428b-be20-56e5ab8ea23c">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/87a7aa21-541f-4fb3-8125-4eddde59977b">
---|---

VHW env, patient Alice NDAGIJIMANA

**Question:** Should the diagnosis appear when there is a high temperature and no fever in danger signs?

**Comment by anvmn** [comment]
@LudmilaGoichman 

Infection diagnosis is not implemented at current phase.

> for the second case (any EGA + fever + extreme weakness (danger signs)) - Maternal Complications diagnosis (wrong)

This is correct. The system acts per:

![Selection_601](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/de5ba7c1-0a0e-427f-afa7-5504e0335e05)

Please close the issue if you agree with my analysis.

**Comment by LudmilaGoichman** [comment]
@anvmn 

You attached the diagnosis “Maternal Complications”, not “Infection”.
Why doesn't the first scenario work in Maternal Complications? (other scenarios work)

- Maternal Complications are implemented except the first case
- Infection isn't implemented

<img width="1075" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/20d8f7b2-fe8b-4730-90f4-2638babaac87">

**Comment by anvmn** [comment]
@LudmilaGoichman 

1. Infection diagnosis is **not implemented** at current phase.
2. Maternal Complications, first case, is **not implemented** at current phase. There's a comment next to it saying "we are holding off an any logic that takes in difficulty breathing alone for the moment, will be addressed in the next sprint"
