### ISSUE TITLE
Diabetes and Gestational Diabetes: <= 20 weeks EGA + fasting blood glucose of >126 mg/dL AND >=200 mg/dL

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1197]
1. Nutrition env. Diagnosis appears twice, when a test is at point of care (both cases 126/200)

Diabetes:

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8db2bc70-f5b4-461b-a0b7-8c58504c0613">

Gestational Diabetes:

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/965b76f7-0807-4fe0-a7e9-04be0a636c4f">

2. Diabetes and Gestational Diabetes: When performing the test after a meal, the diagnosis doesn't appear (in nutrition and VHW env), but this didn't written in the Logic Master. Is it okay? It seems that when the test is done after a meal, the result should be >=200 mg/dL, right?

3. Diabetes and Gestational Diabetes: Referral to the hospital. It is different in nutrition and VHW env. (when a test is at point of care and in lab)  (both cases)

> health education for nutrition and exercise + refer to hospital **for specialty management.**

Nutrition:

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/de3b2589-b064-43b8-b685-843c82fdf9eb">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/03c7ff12-e2a3-4507-839a-dd2ccd25c17d">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0f941e75-23a4-4ec7-8165-537a05b9b9cf">
---|---|---

VHW:

<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a4a6a9ed-1ace-4f03-9480-82eff5bb6d1e">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/72da7507-bcba-4d2b-86df-9346992b1036">
---|---

4. Diabetes and Gestational Diabetes: When the blood glucose should be  >=200 mg/dL and the test is performed in the lab, the result of 200 isn't displayed as not correct. When the test is performed at the point of care, the result is 200 and indicates a diagnosis.

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/39c24652-c55a-4c8f-8d93-b7da836845f6">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1ba7cd63-ee43-4d32-9649-ac0a0da0b5c6">
---|---

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b1d27f09-aa0c-4bc4-adb4-6522a836c2f7">|<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/12e28de8-13b1-4c93-bff3-ad27b31c01c1">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1. Nutrition env. Diagnosis appears twice, when a test is at point of care (both cases 126/200)

Fixed at #1209


> 2. Diabetes and Gestational Diabetes: When performing the test after a meal, the diagnosis doesn't appear (in nutrition and VHW env), but this didn't written in the Logic Master. Is it okay? It seems that when the test is done after a meal, the result should be >=200 mg/dL, right?

Correct, updated the logic file:
![Selection_603](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/25d29e23-a176-4119-84d5-aa987de7b099)


> 3. Diabetes and Gestational Diabetes: Referral to the hospital. It is different in nutrition and VHW env. (when a test is at point of care and in lab)  (both cases)

Per logic file any time Diabetes / Gestational Diabetes is diagnosed, we refer to hospital.
Please retest and make sure this really happens for all cases (glucose of >126 mg/dL, glucose of >= 200 mg/dL, blood sugar test unable to run + glucose at urine dip >=2+ ).


> 4. Diabetes and Gestational Diabetes: When the blood glucose should be  >=200 mg/dL and the test is performed in the lab, the result of 200 isn't displayed as not correct. When the test is performed at the point of care, the result is 200 and indicates a diagnosis.

Fixed at #1209

**Comment by anvmn** [comment]
@LudmilaGoichman 

We should have Health education for all cases. Updated logic file:

![Selection_605](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/9875f79e-9cc6-4d2f-8de0-d4a11fbaeb54)

Please retest after #1209 is deployed.

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn **Scenarios with glucose in urine dip will be reviewed in https://github.com/TIP-Global-Health/eheza-app/issues/1200**

- Nutrition env.
- Android tablet

### Checked and Approved:
1.  Diagnosis doesn't appear twice, when a test is at point of care (both cases 126/200)

Diabetes:

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/20be623f-c09b-4012-8892-fce5a645146e">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2f59bdc4-017a-4914-96c4-75e5867dcd53">
---|---

<img width="288" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f286303d-8083-44d5-839e-eb7f98fa5a59">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/74447f8e-df0d-40d1-a15f-b1ece9a4f95d">
---|---

Gestational Diabetes:

<img width="289" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/17c03c89-e2f9-469f-ac40-cbc8a75b3566">|<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/97b18fb1-e405-4ccb-9bbb-6d884e00bdf2">
---|---

<img width="301" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6c8b06d8-b704-4efb-911e-e8a05dd79246">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ee39f2d0-3f8a-42c8-a7a9-ddd95be8237f">
---|---

3. I tested all scenarios and have now retested each one.

> Please retest and make sure this really happens for all cases (glucose of >126 mg/dL, glucose of >= 200 mg/dL, blood sugar test unable to run + glucose at urine dip >=2+ ).

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b8388e3f-6fa2-48b2-966e-609b328d7f46">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/14068aaf-fa0f-4897-8205-e894a271515f">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d113ca55-0f42-4a4d-89ee-73b256cbe92e">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0ec316c0-be49-4ced-9cb1-a4269acdb82b">
---|---|---|---


<img width="288" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/de8143e3-7ad6-49c1-9502-c40d359226f3">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6a6dc9ce-3fce-4920-afba-2859c0372693">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f8edbd12-5d55-476a-a421-9853bd96c5ee">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/eee4d061-0f15-4242-830c-9b9090539d74">
---|---|---|---


<img width="289" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0448fe75-8ab0-4761-857a-f0c98baf4b61">|<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cc351e44-590b-4ae9-b847-1240ccc744e4">|<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ac9dd04e-fee0-419a-987f-5c5ee6686ca3">|<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9652441f-8c7a-4928-8781-47277ebb5231">
---|---|---|---

<img width="301" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c052af5e-0bba-4d2b-84d1-94179cea7128">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c61df025-cfb1-41c1-82af-e4539bc09cbc">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/59f60fa1-1c9d-4ae2-a06a-004ae4e6a1ef">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5d27bb91-7533-4902-89f9-a2f87441a1b2">
---|---|---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1f5852d4-da3e-4339-9e29-f739c183b568">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c9cd7c4a-302e-482f-80f8-383a981fc49a">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c3215b94-fa8a-40e8-ab94-79aaac428e1e">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/fd8652be-3ea5-4252-a083-f4c814aa7413">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6de940ba-2a07-4339-8d0a-2f4391beba48">
---|---|---|---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2ffa8077-dc84-4e47-aad7-1b5f2de8c468">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6be4dd34-9fc1-40e3-ae41-234c8cef13c6">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/72e00197-4de7-4c0d-81d1-e50b7d90af91">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b79348d9-ec09-4c29-afac-8ae5468778f5">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8e95e3b2-c64b-426b-b845-0f35ed98a159">
---|---|---|---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/25881cd2-1f92-4ae8-92fc-1f1fa1524cd2">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/83d7af22-4975-42e8-a6a2-205aeefea9c6">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e4ef96cb-49b5-4308-9f4e-d911a7ee3552">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d2d7e9a9-1ce4-4f29-821f-0ae8dcfd7464">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5ab2c4d8-edc0-42ab-af5d-8dc9aa205aeb">
---|---|---|---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b1475964-5f11-4023-94cd-396ae4cc8ce6">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ee453712-7f5c-45e7-8603-3df50675da37">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/50ece04a-c443-4fc0-a472-93b663311e7c">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b45546d3-4df4-4acb-abdd-e55ddc9022fe">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a0eff1fe-6496-4cc5-acd6-97b675b70311">
---|---|---|---|---

4. When the blood glucose should be >=200 mg/dL and the test is performed in the lab, the result of 200 is displayed as not correct.

Diabetes:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/63afa99d-7e93-4a81-9508-78fb4694e864">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5c92b698-96d2-4cdc-9109-d2df1de33980">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/58ff8b99-c652-4399-9903-e0b5efdc05ee">
---|---|---|

Gestational Diabetes:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/24a1b098-f3e3-49b5-b5a8-1d5ed60917bf">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d1105b5d-f700-4caf-87b0-0f5edf698c96">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/33924aa8-5605-42ac-9622-3d0ee0a6720b">
---|---|---|

**Comment by anvmn** [comment]
Deployed to live
