### ISSUE TITLE
Diabetes and Gestational Diabetes: <= 20 weeks EGA + urine dip (glucose) >=2+ 

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1200]
1. Nutrition env. Diagnosis appears twice, when a test is at point of care (long and short dipstick)

Diabetes:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/eca3bf13-6a15-4bbc-aafd-c7b8118a20c2">

Gestational Diabetes:

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2b6b2099-5ee1-4c62-b0fa-a373559c9908">

2. Diabetes and Gestational Diabetes: In the Logic Master is written:

> (1) If urine dip (glucose) is >=2+ then random blood sugar test should be run (if not done already). Then follow the other two logic options for diabetes. If test is unable to be run, refer to hospital. 

But in the next steps, only referral to the hospital

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/46dce852-30ca-4944-8901-c72c58320333">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0397d7c1-b492-4ae8-a83b-0360948b591e">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env.
- Android tablet

### Checked and Approved:
1. Diagnosis doesn't appear twice, when a test is at point of care (both cases 126/200)

Diabetes:

<img width="210" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/647953e2-87ec-4d53-b5a5-b5362652beae">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4771d639-0666-49d8-a819-8d0a91801ea6">
---|---

Gestational Diabetes:

<img width="272" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/be611826-b39f-4bac-9177-711dc44a63f5">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2c5dbac5-95e6-4fd0-aa8a-5b7e88fcd20a">
---|---

3. I tested all scenarios and have now retested each one.

> Please retest and make sure this really happens for all cases (glucose of >126 mg/dL, glucose of >= 200 mg/dL, blood sugar test unable to run + glucose at urine dip >=2+ ).



<img width="210" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6aba2091-c256-46a5-ab6e-3ebc9d6aaf2d">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/83c30164-f1ff-481e-8036-10f5324c73d5">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0cfa1582-d859-4f27-8eba-45ac84fb3745">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1f7bc517-1407-42bd-aeed-6745103304f1">
---|---|---|---

<img width="272" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/09d36e69-f051-4f55-8013-0e4481752e76">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cb24e8c4-8b35-4180-b819-bf2f8167f9f8">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/865eab26-8e48-445d-8380-094a1f7e3798">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e86b70cd-ffeb-4cae-bde5-473612a64ca8">
---|---|---|---

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d144e5c1-c17d-4289-bba7-60624feb98ab">|<img width="303" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ba0428b6-cf16-49d9-a734-565f732f1712">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/37dc7d68-ac12-4a83-bd28-77c44acadadb">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/855a4ff7-ccdc-4b59-8c01-a62884c142a3">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/61d9c600-d752-43b3-8195-e5e0e72cb032">
---|---|---|---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4fc665ef-15b9-4a76-97fd-72c7b06c9a4e">|<img width="263" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b241b8e8-1960-428f-99ff-314d1d475967">|<img width="348" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/439a1f29-4bdc-45dc-af7f-f8b39b4fb953">|<img width="348" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6b76f833-cfc4-452c-8b6f-ae53d439d5ab">|<img width="348" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/677d6247-50d8-4239-8017-d9a7e7751d88">
---|---|---|---|---

**Comment by anvmn** [comment]
Deployed to live
