### ISSUE TITLE
When a nurse looks at the test results (from the lab), they are opened again after referral to the hospital (in all scenarios)

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1202]
https://github.com/TIP-Global-Health/eheza-app/assets/35059802/67a97f84-7f4b-4589-aada-647df918f1a7

**Comment by anvmn** [comment]
@LudmilaGoichman fixed at #1209

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixes deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env
- Android tablet

### Checked and Approved:
When a nurse looks at the test results (from the lab), they aren't opened after referral to the hospital

**Comment by anvmn** [comment]
Deployed to live
