### ISSUE TITLE
Syphilis. If before 20 weeks - Negative, repeat at 32-34 weeks EGA. There is no Syphilis test at 32-34 weeks EGA

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1204]
Nutrition env
Patient Gatete Gossy

The first encounter:

<img width="349" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4d96d3b5-43ae-4eaa-8a3d-45a558914326">

The second encounter:

<img width="349" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a720b61e-4f6d-4b95-9829-13cb3298183a">|<img width="349" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3b18e716-f9d6-42de-921d-b26f59cb0234">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

Logic file specification is not accurate (and should not be stated there at all).
Repeated Syphilis test requirements are specified at #55.
In words, we give another Syphilis test at encounter after EGA  week 38, or above.
I've updated the file:

![Selection_606](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/00d87428-f343-49f4-ac05-7f251b995f85)

Please retest and close the issue if you agree with the analysis.

**Comment by LudmilaGoichman** [comment]
@anvmn So this issue can be closed?

**Comment by anvmn** [comment]
@LudmilaGoichman 

![Selection_615](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/765735c6-9816-4f27-8907-9a8c7481d0f8)

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env
- android tablet

### Checked and Approved:
The Syphilis test appears after EGA week 38

first encounter:

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/207bd119-3c3b-41cc-865c-27b1dc0b04a1">

second encounter:

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e997e909-9b5f-4807-938e-ed8bcd447c65">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/590e53b6-5d55-4fd9-9b36-fc0e17df414d">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2d23f1b5-5540-4f92-9f68-0de9d7c39265">
---|---|---

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/71c41fd0-efe1-42e1-b411-ac6717d464ea">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/045ff553-327f-4d68-9e3d-f3d9cd669bff">
---|---
