### ISSUE TITLE
TB Management - Progress report, main page

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1207]
## Issue

The TB Management progress report will include four sections: Summary, Treatment Timeline, Adverse Events, and List of Encounters.

- **Summary**: This section will contain four items: Diagnosis, Initial Date(treatment), Missed Doses, Completion Date, and Current Medication.
- **Treatment Timeline**: This section will expand from one month to six months, reflecting the treatment duration.
- **Adverse Events**: This section will list the adverse events along with the dates they were recorded.
- **List of Encounters**: This section will provide  list of all TB encounters, with one record per month. Users can click on the blue arrow to view more details.

<img src="https://github.com/TIP-Global-Health/eheza-app/assets/32199791/2391e50a-283e-4b8b-b6a4-71ec256ad76d" width="500">

## To Do:
- Implement logic for the progress report
- Apply styling according to the design

**Comment by anvmn** [comment]
@Diama1 

- What should we count for missed doses here:

![Selection_644](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/e3715035-4c4d-43bc-bd19-af89e6781eb6)

Is it the summary of all missed doses reported?

- Treatment timeline - is there a logic for the display (for example, something regarding the dates of the encounters that were performed), or, just according to time that has passed from the beginning of treatment?

**Comment by anvmn** [comment]
@adamhstewart 

1. Regarding Current Medication: as far as I can tell, there's no option to change medication. So we always show the medication that was selected at initial encounter.
2. Should we allow sending the report to WhatsApp? If so, which sections should we allow to select?

**Comment by Diama1** [comment]
> @Diama1
> 
> * What should we count for missed doses here:
> 
> ![Selection_644](https://private-user-images.githubusercontent.com/17882245/343706669-e3715035-4c4d-43bc-bd19-af89e6781eb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDMzOTYsIm5iZiI6MTcxOTkwMzA5NiwicGF0aCI6Ii8xNzg4MjI0NS8zNDM3MDY2NjktZTM3MTUwMzUtNGM0ZC00M2JjLWJkMTktYWY4OWU2NzgxZWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA2NTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NzJlMzA2ZDhmYjhhOTY2NzU3NWU2YTRjMTUzMDJiZDA3NDUzOGMwZGE4NGI1OGIzZWVkZmMyNjUyOGQ4MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gtzf6hrAg6eIiNuBIzo2lXqpDwORfLwMHooUk3f2GEQ)
> 
> Is it the summary of all missed doses reported?
> 
> * Treatment timeline - is there a logic for the display (for example, something regarding the dates of the encounters that were performed), or, just according to time that has passed from the beginning of treatment?

@anvmn we count all the reported missed dose.
On the treatment  timeline, we calculate according to the time passed  from the beginning of treatment. (for example one month from the beginning of the treatment, two and so on)
// @adamhstewart

**Comment by anvmn** [comment]
@LudmilaGoichman 

Please test on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- android tablet

### Checked and Approved:
Four sections: Summary, Treatment Timeline, Adverse Events, and List of Encounters exist. The data is contained in the report


<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/09152874-9bab-4881-bfdd-4d66a3a75413">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4521a2ef-6ba7-4d94-b185-840ad4972d81">
---|---
