### ISSUE TITLE
TB Management - Progress report - Encounter details

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1208]
## Issue

In the List of Encounters, clicking the blue arrow will take the user to the details of that specific encounter. The details will include all the items specified in the designs.

<img src="https://github.com/TIP-Global-Health/eheza-app/assets/32199791/737453a3-e395-4bc5-a781-0eed5393492d" width="600">

## To Do
- Implement as per the design

**Comment by anvmn** [comment]
@LudmilaGoichman 

Please test on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- android tablet

### Checked and Approved:

The progress report looks like this. The data is contained in the report

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8ab58c37-94db-48d6-99ab-45abc633c007">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/269342b0-4e19-48ef-96a0-07bcfa004f3e">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/05d04d4b-cdd6-4540-a188-cdd151537271">
---|---|---
