### ISSUE TITLE
Symptom Review: Burning with Urination

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1216]
1. In all of these cases, the diagnosis is Yeast infection instead of Candidiasis.

<img width="1072" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ef24c92d-1268-4e16-8bb5-86275e6b9efe">

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5928f947-ec89-4783-8e8a-38a3368b43c4">

2. In all of these cases, the diagnosis doesn't include "Possible"

<img width="1073" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/05e081d1-b799-44e1-b830-50c6b1d8b3c0">

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f3220b81-c107-4f9a-a95d-e865a62e2097">

3. In all of these cases, the diagnosis doesn't include "Lower"

<img width="1072" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2fb7e600-8fbb-4082-afd6-6a048cf1d576">

<img width="353" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4ed6bc9c-d5e6-46bf-a42b-cc95c27067f1">

4. In the first case, the Medication distribution task should not appear, right?  

<img width="1075" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/626eedfe-7ece-409c-8e09-880eb1ea2ddc">

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/49e2003f-bc43-49aa-99af-e09923a534b3">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5cddaeb6-85ad-43f9-8375-cd942321c076">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2e839b43-a9f8-4123-be69-dde76e1a624a">
---|---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bfa7e723-c19a-47fe-b532-3a05fa707730">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7be3de15-2178-46ad-836a-797418fa271f">
---|---

5. In the second and third cases, the Health Education task should not appear, right? 

<img width="1075" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/626eedfe-7ece-409c-8e09-880eb1ea2ddc">

second case:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0587db81-7834-47c7-a866-b3d4fab5d9d9">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2a7be91b-09d4-4d11-9369-38ebe03b7a77">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/dfb0a807-61a1-4e04-aace-53ad2b35e066">
---|---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/585b6ec4-623d-41ef-bb62-38568891cf87">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c46dd2db-ed28-4fd5-b5db-65a6a9a6cf3e">
---|---

third case:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/59234781-af64-4cba-839a-c764e35903f3">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ff22851a-aea9-4727-8449-e6be487346a1">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/26f44bce-05e6-4ca9-89ee-3ff4b7070646">
---|---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9853d9df-91aa-4789-985a-9c945162ab8c">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0c42b8f7-8c9d-4b22-bc48-74cd1318fab1">
---|---

6. If you answer “yes” to all questions, two diagnoses appear (instead of three?), and maybe the “Medication Distribution” and “Health Education” tasks should not appear?

<img width="1094" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bdd08dd1-6637-4170-9c53-d838619216fc">

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3e2aa77d-7ca3-4d59-88e6-46b0158571f3">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9bd48e37-cc01-4681-829f-d538f9961c42">
---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f970ec1a-50b8-4dd9-9950-039e01835a52">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/07970b05-f384-4312-877f-8bbf372f828d">
---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9bd495e5-39d0-4c33-968d-9e9c391b714e">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bec5bc11-3380-428a-a42a-0ce85374deb2">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1. In all of these cases, the diagnosis is Yeast infection instead of Candidiasis.

This is per requirements. See original issue: https://github.com/TIP-Global-Health/eheza-app/issues/244

> 2. In all of these cases, the diagnosis doesn't include "Possible"

Per requirements.


> 3. In all of these cases, the diagnosis doesn't include "Lower"

Per requirements. See #242.

> 4. In the first case, the Medication distribution task should not appear, right? 
> 5. In the second and third cases, the Health Education task should not appear, right? 

No. All 3 cases result in same diagnosis, and therefore same treatment (Health Education + Medication). See #244.

6. If you answer “yes” to all questions, two diagnoses appear (instead of three?)

Pretty sure it's what we were asked to implement.
It's live for couple of years, and no complains, so far.
 
> and maybe the “Medication Distribution” and “Health Education” tasks should not appear?

Unless specifically defined, the rule says that we offer complete treatment for each of diagnoses.
