### ISSUE TITLE
Hypertension (Continued Care). In the subsequent encounter, the diagnosis doesn't appear (pop-up), and in the Case Management, there are no tasks. 

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1221]
1. nutrition and VHW env.

patient in the nutrition env: Ishimwe Gossy

<img width="1093" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/676d8ade-2c3f-4fce-a38c-395e6aa9faf9">

In the subsequent encounter, the diagnosis doesn't appear (pop-up), and in the Case Management, there are no tasks. 

first encounter:

| | |
---|---
<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/81405013-ade2-4de0-95b1-ded17e017ac9">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f0ee90ff-3fea-42e5-8320-52bc87062812">
<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/901f0276-f896-454e-91ed-357a88d271d7">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c4c0b355-e46d-4719-8f09-088a56e3df91">
<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e1a39096-1344-4e99-851f-4374b37ccf06">|

subsequent encounter:

| | |
---|---
<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/65b15ca0-b54e-4c54-b34d-208d31583d0e">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8cd3b9a3-dbf1-438e-829e-9011a6f331fd">
<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ea4f0a85-8d2e-463f-a66c-387626806f39">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4e7e661b-0c32-4eb4-b205-e211ece813fc">
<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/204acda4-a9ec-4f36-a1ad-7ec091d9f121">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/49a49a85-4dc2-4d7a-b6b8-96e6d27d5561">
<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/70a7f45e-6494-43bf-ac93-eec266a04787">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5ca5f135-1e5a-45b7-83ab-1c9681ad2fac">
<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e7be7406-1024-476d-9435-0b44eed1eb4e">| |

2. VHW env. patient: Gaudance UFITINEMA There are no diagnosis and recommendations. Is it okay?

<img width="1093" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8df6eafe-ee9a-49ca-abc2-6cfb82856b4c">

first encounter:

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0c0ab9b1-22ca-4aba-a1d8-c329da457cc6">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b7b9bcae-7fea-4c29-8cca-de684cf44675">
---|---

subsequent encounter:

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bf383f78-f172-491e-b7b7-ca3bddb68800">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ade1bc45-bf68-4e9e-b634-7207f18d6792">
---|---

3. nutrition and VHW env.

patient in the nutrition env: Mom group 26 Mom

In the subsequent encounter, the diagnosis doesn't appear (pop-up), and the Next Steps task appears in the completed tab

<img width="1088" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3ff8eacc-bf15-4b6e-abfe-0800d6a2a465">

first encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/008e6244-6a07-4230-af64-9a34f47b6953">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/00029d88-6cd2-49e9-9c76-ff90292c5113">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1b283bad-1425-4b48-a31f-c784cba62fbc">
---|---|---

subsequent encounter:

| | |
---|---
<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/00dceaba-5577-42eb-85e8-357c791a5d60">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3217c7e3-e927-4fd2-b906-eb2b0555489d">
<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/788b1250-0932-4a49-9cb3-27393d053bfa">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/187a303b-e20a-4436-b2ef-77bafe7770a3">
<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0c09d70a-7acf-4e0a-a564-27f3dac2c55d">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/35ef196e-ff0f-44b8-9d41-8e537a49cffd">

4. nutrition and VHW env.

patient in the nutrition env: Mukunde Gossy

In the subsequent encounter, the diagnosis doesn't appear (pop-up)

<img width="1091" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/40d637df-ac08-4443-afbc-ffb8dad9684e">

5. nutrition and VHW env. In the first encounter, the diagnosis is Chronic Hypertension. But in the subsequent encounter, it appears as Hypertension (without Chronic) in all cases

subsequent encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/42eb3f86-9650-48af-92f2-3db107c9ba41">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bd401f1f-e98c-4946-84c3-dd64f70ab7e5">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3941b74c-6c11-460b-83bc-01d43642a36d">
---|---|---

**Comment by LudmilaGoichman** [comment]
@anvmn I added 3-5 points

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1. In the subsequent encounter, the diagnosis doesn't appear (pop-up), and in the Case Management, there are no tasks. 

Per requirements, when we continue treatment of diagnosis, we don't show the pop-up, since 
there was not change. Case management problem fixed at #1223.


> 2. VHW env. patient: Gaudance UFITINEMA There are no diagnosis and recommendations. Is it okay?

Yes, no change in diagnosis and no change is needed in treatment.
Therefore, no action is taken.


> 3. In the subsequent encounter, the diagnosis doesn't appear (pop-up), and the Next Steps task appears in the completed tab

Next steps problem fixed at #1223.


> 4. In the subsequent encounter, the diagnosis doesn't appear (pop-up)

Per requirements.

> 5. In the first encounter, the diagnosis is Chronic Hypertension. But in the subsequent encounter, it appears as Hypertension (without Chronic) in all cases

Per requirements. Logic behind this is that initial diagnosis (Gestational / Chronic) is determined based on pregnancy week. When we treat the diagnosis in subsequent encounters pregnancy progresses.

**Comment by anvmn** [comment]
@LudmilaGoichman 

#1223 deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env
- android tablet

### Found Issue:
3. patient: Mucyo Ketsia

In the **first** encounter, the Next Steps task appears in the completed tab (in the subsequent encounter, the Next Steps task appears in the "To Do" tab).

first encounter:

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/874f253a-3814-4ae9-bd7b-6d0ee7158fac">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f084944b-68d2-4592-aa05-21124b930ca8">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/25b4a8c6-8c10-49c8-9a94-84c65a491987">
---|---|---

subsequent encounter:

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7eb85074-ab97-4589-a76e-e89e9ca23b34">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bd8e62e0-9175-49a5-9777-8ae2bcbb205b">
---|---

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7f85f7a9-749a-4711-8ec7-9d7fdf976d67">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/99cb756b-f38b-4a9b-a280-8060e134245c">
---|---

### Checked and Approved:

1. In the subsequent encounter, the "Wait" activity doesn't appear

first encounter:

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4741ab45-1934-4500-b985-a77e6bfb0226">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4f67fac4-d737-4156-a748-980c8ac68f4e">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c8c685a1-4c12-4ff2-8c27-72194ad5b82f">
---|---|---

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a50ceba7-d23e-4b2c-9cff-23be456c433d">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d20551ec-9748-41b5-8430-31ba9e8495af">
---|---

subsequent encounter:

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b8ab6a06-642a-4007-a35f-05617b9ded1d">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1ab2cafa-15a5-4119-8dd8-80ff80513fe0">
---|---

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/255b287f-b5d6-46cd-9164-a62fe3f15eb2">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/417fd599-be64-4493-9cab-5059f9c73a1a">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixed and deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn

- nutrition env
- android tablet

### Checked and Approved:

In the first and subsequent encounters, the Next Steps task appears in the "To Do" tab

first encounter:

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/34549c07-d0aa-42f8-99c3-a5cf6e98283c">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/fd58d7cb-71be-4dda-b5be-77c739f3275f">
---|---

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d0235c58-dd94-400e-995c-751b2f309cec">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/43276a9a-538f-45e8-bc48-9b181ed9affa">
---|---

subsequent encounter:

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/cfdbbadd-479b-45d2-bc9a-cc135a60c151">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9454dcf8-ebb8-4e0d-8841-0cbc4aaa35db">
---|---

<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9e954467-b950-4ad0-a0d8-8079eaa8ab3d">|<img width="352" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/39586e52-2ab5-459a-a3ed-8642e079564c">
---|---
