### ISSUE TITLE
Postpartum encounter. After the “GU Exam” activity, the screen returns to the previous activity (“Breast Exam”, this is saved).

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1227]
https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c5d8ff61-10a3-44aa-b289-12f9fe03be41

**Comment by anvmn** [comment]
@LudmilaGoichman 

Nice catch!. 

Fixed at #1231 (deployed to Nutrition env). Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env
- android tablet

### Checked and Approved:
the issue is fixed
