### ISSUE TITLE
Postpartum encounter. "Depression Not Likely" doesn't appear if the diagnosis is "Undetermined"

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1229]
- "Depression Not Likely" doesn't appear if the diagnosis is "Undetermined"

<img width="1090" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/dfd6464a-d733-4307-be6e-9556242eb197">

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7275b614-d592-4ab3-885e-9cf06c8e81e0">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/de34d2f4-da28-49d0-8475-7bf2c0ba00fb">
---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/75d686ef-f582-4e0c-8108-b7e436d6e240">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b309938b-c5dd-4e17-8b1b-acb9ba6ab1e9">
---|---

- "Depression Not Likely" appears if the diagnoses are "Urinary Incontinence" and Infection

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/fed3fbd0-02ec-49e4-96a8-8d6a5941dc7f">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a633e891-86d0-4898-87eb-2a8261d6ba5d">
---|---

- "Depression..." and "Suicide Risk" diagnoses appear  if the diagnosis is "Undetermined"

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3299563a-8038-4432-a97d-eef2aeae9f96">

**Comment by anvmn** [comment]
@LudmilaGoichman 

This functionality is due to fact that there're no next steps for 'Depression not likely' and 'Undetermined'.
It's informative only, and if I'm not mistaken, the decision was that it will only be shown if there're next steps for other diagnoses.

**Comment by anvmn** [comment]
@LudmilaGoichman 

If the answer is satisfactory, please close the issue.
