### ISSUE TITLE
ANC Logic - Add Activity - Next Steps [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#123]
## Issue 

Building upon what we have already created for ANC @ Health Centers, we will be adding a "Next Steps" activity to the main activity tray. 

The activity will only appear when all other activities have been completed. 

At the end of the "Next Steps" sub-activities, the user will be taken to the progress report. 

Main Activity Icon: 
<img width="126" alt="Screen Shot 2022-01-31 at 3 30 50 PM" src="https://user-images.githubusercontent.com/77505464/151868294-a1640f48-ef10-49b8-8acd-393f27cbb823.png">

## Design Assets
[Link to Figma file. ](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=1%3A1249) 

## To Do: 

- Add "Next Steps" Activity to main activity tray.

**Comment by adamhstewart** [comment]
## QA Analysis

### Works as designed
- The next step button appears at the appropriate time and the the progress report is displayed at the end (although in some cases twice - see followups in #187 )

## Needs followup
- Not exactly related but no place else to put this: it appears that when there is no diagnosis, we still get the popup with empty text before we go to "next steps"
![image](https://user-images.githubusercontent.com/688507/160678387-2c8bcc4f-0541-40f2-bf86-d81ebee2e153.png)

**Comment by adamhstewart** [comment]
@anvmn I'm having trouble hunting this down - but it happened also with @leowea . It's possibly happening when there is no diagnosis at all, but I thought I had experienced it when I should have seen hypertension, although I couldn't recreate that scenario.

**Comment by anvmn** [comment]
@adamhstewart ^^ fIxed at [0c0ff63](https://github.com/TIP-Global-Health/eheza-app/pull/209/commits/0c0ff63b0079b63b9bb7c38a08860104d89be11e).

This was happening when there was a suspicion for hypertension - a need to get BP retaken at second phase of encounter.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Patient EGA is under 20 weeks. The diastolic measurement of the patient is => 90  and less than 110. No warning displayed, 
but Next steps included a wait icon for follow-up blood pressure measurement in 2 hours. If follow-up diastolic measurements were also between 90 and 110, warning displayed about chronic hypertension. The empty warning screen was not visible during the workflow.

EGA
![1-ega](https://user-images.githubusercontent.com/3536805/176378038-7165e9b0-671c-44bb-ac4b-f1bb9ac7805d.png)

Diastolic >=90
![2-diastolic-90](https://user-images.githubusercontent.com/3536805/176378106-7d538ee1-f369-4b3e-a3ff-cf172dae9eb9.png)

Wait
![3-next-steps](https://user-images.githubusercontent.com/3536805/176378137-6e37790f-4d38-44f9-94b1-3cfaade64d2c.png)

Follow-up measurement
![4-follow-up-bp](https://user-images.githubusercontent.com/3536805/176378183-d16efa9e-f03b-41e2-9e7d-a9207797e125.png)

Warning:
![5-warning](https://user-images.githubusercontent.com/3536805/176378214-710c1f64-1427-43d6-99c4-d1032472db49.png)

**Comment by leowea** [comment]
@balagan73 This is correct. She can be diagnosed with hypertension before 20 weeks. If she is above 20 weeks, then preeclampsia becomes part of the possible diagnoses. Thank you for your great work on the QA!
