### ISSUE TITLE
RM - Tracking User Progress on Adoption survey

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1232]
## Issue

On the adoption survey, there was a request for the user to be able to track their progress on their 3-month survey score compared with the baseline score. Here is the logic:
- If the 3 months survey score is lower than the baseline survey, there will be this message "you have slid back compared to your last performance (an arrow showing a regress-down arrow)" 
- If the 3rd month survey score is greater than the baseline survey score, the message will be "congratulations; you've improved." ( with a green arrow showing improvement)"
- If the score remained the same; the message will be "you remained in the same category."
- On the six month survey, which is the last there will be a summary of the score on each survey that was taken.

| Baseline score > the 3 months  score | Baseline score = the 3 months score | Baseline score < the 3 months score |
| ----------------------------------------------------- | -----------------------------------------------------| ----------------------------------------------------- |
| ![Screenshot from 2024-07-02 12-35-10](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/68bc5abb-45e9-437a-afd7-bcb6cee5c4bb) | ![Screenshot from 2024-07-02 12-35-01](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/c2d6376c-885a-4cfd-ad1e-3d596b6116ea) | ![Screenshot from 2024-07-02 12-34-52](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/62861006-12ad-4616-b6e0-0a0284b1d940) |

## Todo
- Implement per design.
- Implement the logic

**Comment by anvmn** [comment]
Deployed to live
