### ISSUE TITLE
ANC, Postpartum - incorrect referrals per Speciality Care 

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1235]
![Selection_672](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/f9f6a768-cd3b-4824-a02f-f089cce55f29)

Per requirements, in we refer to ARV / NCD program, if Speciality care activity states that patient was not referred there previously.

### Current behaviour for HIV:

**Case 1:**

![image](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/ed5a7ed1-1570-48b7-b16b-46db7e1821b9)
![image (1)](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/f1ff833a-7629-4655-8f32-d86ee26dc352)

**Case 2:**

![image (2)](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/94b867e6-21cc-440c-8ead-6785390111a6)
![image (3)](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/5addb211-1265-402b-9f93-6a6a0ea0b190)

### Current behaviour for Diabetes:

**Case 1:**

![image (4)](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/4dc71419-b694-45f7-ad2a-0d5b700f80b6)

![image (5)](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/6d623173-cd34-436a-8923-e7e593af1604)

**Case 2:**

![image (6)](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/09296b7c-79ba-40b1-b74f-239315e28427)
![image (7)](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/6a07bd1b-a82f-4fb3-89a7-7f7d85240de6)

**Comment by anvmn** [comment]
@LudmilaGoichman 

Fixed and deployed to Nutrition env. Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env
- android tablet

### Questions/Found Issues:
1.  Why is a patient referred to ARV to the postpartum encounter if the answer is `No` to the question `Does the health center have an ARV services program?` at the first appointment?

First encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b184f6c6-ca2a-4a04-98bd-df2beaefb27b">| <img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0f84b2cc-d631-43eb-abc3-6de5d7d85581">
---|---

Postpartum encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a8fc2419-2df0-4072-9cc6-ff39cbfe83d3">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1c9e4de8-410b-4988-8689-c3a194f07687">
---|---

2. Gestational Hypertension.  Two referrals. If "yes," then there is a referral.
First encounter:

<img width="351" alt="image" src="https://github.com/user-attachments/assets/7e774622-6729-4137-ab2c-2ee35772a75a">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/8b1dd46f-907a-43bc-adfa-a8f5e07a8b01">
---|---

Postpartum encounter:

<img width="351" alt="image" src="https://github.com/user-attachments/assets/5538dd41-3aea-4fdd-a6db-5c2e179ca0c0">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/3ce22ddf-e6b0-4b99-bbd6-d8e54dd6f744">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/d9962138-ec69-4a44-ab3f-d24f4cd0051d">
---|---|---

<img width="351" alt="image" src="https://github.com/user-attachments/assets/2de3cb93-0832-4220-9279-5df26c5acb6e">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/c52906a5-dce3-4527-b80b-1f298fbe1006">
---|---

<img width="351" alt="image" src="https://github.com/user-attachments/assets/31869211-41a1-4fc5-8306-c8fa7672c558">| <img width="350" alt="image" src="https://github.com/user-attachments/assets/ea39f0dc-c6b9-4413-9c6e-4894a96da960">
---|---

3. Severe Preeclampsia. The pop-up doesn't appear in the Postpartum encounter. And the diagnosis is wrong

First encounter:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/7463050f-ced7-434c-a21a-87ba8c97ec13">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/616f464d-e89a-402a-bfe1-facff860f555">
---|---

Postpartum encounter:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/3e8c6f07-efd6-480e-908a-893e43e1590d">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/f9b7ddb3-5b54-4896-843a-2ea8244557ea">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/c870c147-12f6-4859-9277-ab11313f7d8c">
---|---|---

<img width="350" alt="image" src="https://github.com/user-attachments/assets/a4c204e9-7aaf-4af2-ba93-10961aa2eb33">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/c9d343b1-ff07-4680-a2b9-f7411acb3467">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/024585dd-9365-4599-9b1a-8526b3779df3">
---|---|---


### Checked and Approved:
1. HIV. Referral to ARV

First encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9bc63a67-77a8-400a-a8ec-4ba2e0c1d9e8">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e29cf91f-c452-4ebf-b488-f8e3d5d7013e">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ea0789cf-7517-4ca6-89d7-75ca4887aec3">
---|---|---

Postpartum encounter:

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/60411741-98a7-4610-b7b0-28fb544afab2">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5a08a9b0-d8d1-4a88-a1a2-a6eb5a954e54">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9808bbff-113a-49e3-ae3f-b0c0504ec9c8">
---|---|---

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/36059d2f-1a1f-41b0-ae10-eee1c1a47686">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/37412c76-d95f-4e8e-87c4-a15523411e64">
---|---

First encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/dc01b1a8-24d5-4a0e-b31d-49d707893370">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e97f7db3-8836-40da-b97b-29596dc39899">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/96f48172-e97b-4d42-822f-8177db4daf0b">
---|---|---

Postpartum encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/fcf1b5dd-3328-480b-ac40-ed8f51fdefb8">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/bc0fcada-ab6c-4c19-8e14-0a7a40b8ae91">
---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a4511600-95c4-4fb9-b7ca-d21403a014fe">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/21bc721b-4c33-41aa-b3d1-3162df1e9909">
---|---


First encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f2e4de41-0470-48a6-9487-a54af3ff0858">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1c858d9b-2a0e-41d1-a8ed-fa45282d1bb9">
---|---

Postpartum encounter:

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c7f9bd95-d235-4314-beb6-ffaaa24ede70">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6ed7a2d6-15ac-4e85-b48f-86ec40fd4335">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/75e6d958-8196-4bff-a4c1-8484ca042421">
---|---|---

<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/2d952e77-8117-4386-96f2-ec42d4244967">|<img width="350" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4c974547-7999-44b1-a133-0299c47a1c2a">
---|---

2. Diabetes. Referral to NCD

First encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ebba9356-f080-4ce5-aae8-2439af130a39">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/6902c078-a031-49f5-9958-852b90be0d34">
---|---

Postpartum encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3711a0fa-c7bb-477c-8e7b-8645c7e742fe">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/184b9404-7a61-4099-bf33-244a34a6e2a0">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7c520dca-1cce-4e2e-a81c-e067d9335cba">
---|---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/227796c1-2aff-433f-bd1e-6fb84feb0c36">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1c1bdc2a-793a-4283-a382-54c5bdee6258">
---|---

5. Gestational Diabetes. Referral to NCD

First encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/228f493b-8db6-4c8a-813b-fc34c97616b2">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4e899328-c191-4762-9972-bd236ee6bfae">
---|---

Postpartum encounter:

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d6aacb20-9651-4247-9b10-e3d685ca0ebe">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/21f0487e-e0be-4ca4-9b35-19aab141f7fb">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/18ba5c0a-6c30-4fdf-9d79-75d48febb329">
---|---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5f6caf11-7471-4066-86f3-05021a6b7474">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a9dff319-ee11-49ee-9537-a4d9ec7cecc1">
---|---

6. Chronic Hypertension. Referral to NCD

First encounter:

<img width="351" alt="image" src="https://github.com/user-attachments/assets/9690c56d-34eb-44f6-b25e-3e41279dcd92">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/b804a040-b17d-48ab-84ae-5cd0339cc3a7">
---|---

Postpartum encounter:

<img width="351" alt="image" src="https://github.com/user-attachments/assets/ab325100-f493-4184-a586-b0a72f1f8f9f">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/dff75f89-9496-4ed5-a359-50160082fd28">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/c7427236-4c5e-4322-b993-63cfa81ec009">
---|---|---

<img width="351" alt="image" src="https://github.com/user-attachments/assets/e7e265ee-9320-4085-bd45-73e4e5cd9bbc">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/35f6492b-e736-4bf1-8460-4a6d77af4d26">
---|---

7. Mild to Moderate Preeclampsia. Referral to NCD

First encounter:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/27429e29-e649-4ed3-ab64-7027f78f50ca">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/03c556df-1cc6-4bff-b11a-d51b51c37b21">
---|---

Postpartum encounter:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/10d636f5-62ef-47b8-9da2-bf5307446455">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/ada21a80-dbd8-409a-bf8a-f154604f7894">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/129cbbc6-3e52-4db5-8140-abc4c63cfa21">
---|---|---

<img width="350" alt="image" src="https://github.com/user-attachments/assets/856d95df-b70a-44c9-8691-39baf577ada1">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/508ba49b-5bcb-42c2-ad4f-62c2cb5b1644">
---|---

7. Eclampsia. Referral to NCD

First encounter:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/ea840574-75ce-4bd6-9930-bbaf2302323d">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/d3167608-27ea-40a6-afb0-ac55e7939782">
---|---

Postpartum encounter:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/484e3c4a-ea61-447f-8c52-1f5a13f94229">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/eb52fe03-ef26-400e-b1f3-4ec78dba9a7c">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/3c6a5255-14e1-4949-affc-f0f2cce63245">
---|---|---

<img width="350" alt="image" src="https://github.com/user-attachments/assets/b2668c7a-e7b4-4d92-b8c9-02045996853b">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/699b6eed-8960-484f-b776-79dd358c5c62">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> Why is a patient referred to ARV to the postpartum encounter if the answer is No to the question Does the health center have an ARV services program? at the first appointment?

Patient can be sent to ARV services at hospital, or some other location.
Logic is only at postpartum: in to enrolled to ARV already, refer to ARV.

**Comment by LudmilaGoichman** [comment]
@anvmn I added 2 issues

**Comment by anvmn** [comment]
@LudmilaGoichman 

> @anvmn I added 2 issues

Fixed and deployed to Nutrition env.

**Comment by LudmilaGoichman** [comment]
@anvmn

- nutrition env
- android tablet

### Question:
4. When blood pressure is normal in a postpartum encounter, should the patient be referred to the NCD?

### Checked and Approved:
2. Gestational Hypertension. One referral. If "yes," then there isn't a referral.
First encounter:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/f7db5cec-0d8c-493c-84db-b86bdd5c7050">|<img width="350" alt="image" src="https://github.com/user-attachments/assets/2d1d6949-0439-42e4-aed5-9ae2d6570f59">
---|---

Postpartum encounter:

<img width="350" alt="image" src="https://github.com/user-attachments/assets/d1c5568c-cc0c-43a2-87fc-dbb3eb48cf82">|<img width="352" alt="image" src="https://github.com/user-attachments/assets/8223a3e7-c3b1-45ff-b88b-2ee511470914">|<img width="352" alt="image" src="https://github.com/user-attachments/assets/308cdb31-6fe5-43df-a8c2-2882fa98bb89">
---|---|---

<img width="352" alt="image" src="https://github.com/user-attachments/assets/facedfbf-6105-4c64-a279-fcec98ec1df2">|<img width="352" alt="image" src="https://github.com/user-attachments/assets/ba9228a1-cb89-4f0e-b41d-de2db31ba3a7">
---|---

3. Severe Preeclampsia. There is no pop-up with the wrong diagnosis in the Postpartum encounter. 
First encounter:

<img width="352" alt="image" src="https://github.com/user-attachments/assets/ec83cf09-ad80-4d00-bdbb-ce1a8c30915c">|<img width="352" alt="image" src="https://github.com/user-attachments/assets/07ccce03-1d2e-434e-b96d-6f69c77949c1">
---|---

Postpartum encounter:

<img width="352" alt="image" src="https://github.com/user-attachments/assets/1e68514e-262b-43ff-80a3-dbd6794ed3c3">|<img width="352" alt="image" src="https://github.com/user-attachments/assets/2b8f1dee-dd1f-4958-8dda-09a437c2108b">|<img width="352" alt="image" src="https://github.com/user-attachments/assets/aa67e6e5-3697-45ae-b117-fc92daea1f13">
---|---|---

<img width="352" alt="image" src="https://github.com/user-attachments/assets/b6663ad2-1160-4540-9b81-cf4078001727">|<img width="352" alt="image" src="https://github.com/user-attachments/assets/465f3f54-87cf-4d6d-acf2-4e5e685f4d59">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> When blood pressure is normal in a postpartum encounter, should the patient be referred to the NCD?

NCD referral is based on diagnses made during pregnancy only. BP in postpartum encounter is not taken into account.
