### ISSUE TITLE
RM - Change the position of  on Guide message

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1243]
## Issue

The guide message needs to be positioned for better guidance to the user. Here is the wireframe for the rephrased guide message:
![Screenshot from 2024-07-09 17-10-51](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/e80a9a73-4f41-4b9f-9bd3-af6969499fd5)
![Screenshot from 2024-07-09 17-23-33](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/d91ba8d5-a756-45a6-942d-4501779d052f)

## Todo
- Implement per design

**Comment by anvmn** [comment]
Deployed to live
