### ISSUE TITLE
TB Management - allow changing medication

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1253]
## Issue

Prescribed medication task should appear at subsequent encounter:

![Selection_742](https://github.com/user-attachments/assets/d418e4cb-8aaf-4638-be49-fd6a78f39cca)

If no, is selected, medication lost should appear to allow changing medication:

![Selection_743](https://github.com/user-attachments/assets/3455bb28-c963-48c9-b441-7dae3a69387e)

**Comment by anvmn** [comment]
@adamhstewart

Deployed to Nutrition env.

**Comment by anvmn** [comment]
@adamhstewart 

Seems that I closed this issue by mistake. Don't have the Reopen option.
Can you reopen it please?

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Questions:
1. The ~Treatment review~ Prescribed medication activity looks different:

first encounter | second encounter |
---|---
<img width="351" alt="image" src="https://github.com/user-attachments/assets/e4d0cd30-866a-411d-8641-b07bf0126ade">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/46c18119-c847-498d-bb79-8a9147926f0d">


2. The Prescribed medication activity looks different in the first encounter, when opening this activity again:

https://github.com/user-attachments/assets/ec845c31-a1e5-4308-a8a5-07ef4c1d579b

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1. Prescribed medication activity looks different

It's ok. Descriptions got screenshots from another module. We used different medications for TB.

> 2. The Prescribed medication activity looks different in the first encounter, when opening this activity again.

Fixed and deployed to Nutrition env for retest.

**Comment by LudmilaGoichman** [comment]
@anvmn

- Nutrition env
- Android tablet

### Checked and Approved:

2. The Prescribed medication activity looks the same in the first encounter when opening this activity again.

first encounter:

<img width="354" alt="image" src="https://github.com/user-attachments/assets/4914243c-40d1-4ed7-9b29-57fdfc38f5de">|<img width="354" alt="image" src="https://github.com/user-attachments/assets/c5f4e600-e5a0-4caa-8fa8-5c4745fd11d6">
---|---


second encounter:

<img width="354" alt="image" src="https://github.com/user-attachments/assets/a0a82f2d-f117-4c0c-ae82-29f71817e11e">|<img width="354" alt="image" src="https://github.com/user-attachments/assets/a768809c-e3fc-4c09-a1a7-fc28ac8bf717">
---|---
