### ISSUE TITLE
TB Management - Progress report - add the previously completed medication

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1254]
## Issue

~~When a patient finishes the initial phase medication, the display will show the previously completed medication.
This will come immediately after 2 months (which is end of initial phase).~~

Report will show current medication, and previous medication, if there was one.

![Screenshot from 2024-07-18 16-18-25](https://github.com/user-attachments/assets/744d6b44-7447-4792-aa2a-2521fcb018a1)

## To-Do
- Update the logic.
- Implement according to the design.

**Comment by anvmn** [comment]
@adamhstewart

Deployed to Nutrition env.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- Nutrition env
- Android tablet

### Question:
1. In the third encounter, the medication given in the first encounter doesn't appear. Is it okay? 

first encounter | second encounter | third encounter
---|---|---
<img width="351" alt="image" src="https://github.com/user-attachments/assets/63650e5a-c5ba-485a-b5fb-a601f567bb7f">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/c75450f3-09fd-426d-9f9b-a533b85e3c5e">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/82f01db7-21ac-494f-9ed1-0ebc0164b886">


### Checked and Approved:
1. Report will show current medication, and previous medication

first encounter | second encounter | third encounter
---|---|---
<img width="351" alt="image" src="https://github.com/user-attachments/assets/72077495-e150-4fb2-bc30-794de9327a5a">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/cc5bfed9-4d96-46c9-b2bc-2eb52632d269">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/90cdd58c-1de6-4a3b-996f-ad63a6593855">

**Comment by anvmn** [comment]
@LudmilaGoichman 

> In the third encounter, the medication given in the first encounter doesn't appear. Is it okay?

Yes. We show only 2 last medications - current and previous.
