### ISSUE TITLE
TB management - display the progress report after the save of the last to do activity

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1255]
## Issue

When the user completes the final activity, they need to be taken directly to the progress report, rather than seeing an empty page and having to click on the progress report tab. This should be consistent with the behavior of other modules.

## Todo
- Implement as for the other modules

**Comment by anvmn** [comment]
@LudmilaGoichman 

Deployed to Nutrition env.
Please test for first and subsequent encounters.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env
- android tablet

### Questions:
1. Should I check all modules? 

>Implement as for the other modules

2. patient Ntwari Claude. I had a few (first and subsequent) encounters, but the diagnosis didn't appear in the report

subsequent encounter:

https://github.com/user-attachments/assets/d6bc847b-1293-4397-98ea-4c9ab7a7b827

### Checked and Approved:
The progress report is displayed after the save of the last activity 

https://github.com/user-attachments/assets/68b74e3c-fe50-4908-a97d-a16f61099641

**Comment by anvmn** [comment]
@LudmilaGoichman 

> patient Ntwari Claude. I had a few (first and subsequent) encounters, but the diagnosis didn't appear in the report

What you show is first encounter. I know this, because only first encounter got diagnostics activity. For subsequent encounter to be possible, at first encounter, Tuberculosis must be diagnosed.

**Comment by LudmilaGoichman** [comment]
@anvmn no, it's the third encounter:

<img width="720" alt="image" src="https://github.com/user-attachments/assets/f6cf0aa5-1ea9-4416-9c8b-b7e537d704a2">

<img width="720" alt="image" src="https://github.com/user-attachments/assets/71593458-2ae7-4b36-bcbb-7e7c82c6320a">

<img width="718" alt="image" src="https://github.com/user-attachments/assets/2325500f-8f7d-489d-8df1-27fd2161a69a">

**Comment by anvmn** [comment]
@LudmilaGoichman 

Are those all share same participant?

**Comment by LudmilaGoichman** [comment]
@anvmn 
yes 

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/52d18e42-d168-4a10-a47b-19c5e7aa651f">

**Comment by anvmn** [comment]
@LudmilaGoichman 

Actually, each encounter got it's own participant:

![Peek 2024-07-25 09-43](https://github.com/user-attachments/assets/e206f263-ad5c-451b-84f3-351560338f37)


Only first encounter got diagnostics activity. For subsequent encounter to be possible, at first encounter, Tuberculosis must be diagnosed. 

Not sure what was the problem, but it should not act like it has with Ntwari Claude.
Tested this locally, and it worked well.
Please retest.

**Comment by LudmilaGoichman** [comment]
@anvmn

- nutrition env
- android tablet


### Found Issues:
1. I create a new patient, 9 years old. But there are fields for adults:

<img width="345" alt="image" src="https://github.com/user-attachments/assets/10eb359a-5e58-4642-ae0d-c58f1c05bb65">

2. patient: Patient TB. The diagnosis didn't appear in the report in the subsequent encounter

first encounter:


https://github.com/user-attachments/assets/39788531-c79b-4288-b5ae-3e6ba0e3a012



<img width="1039" alt="image" src="https://github.com/user-attachments/assets/7d3ef355-37f2-4c3b-94bb-7d338844ddc8">|<img width="1060" alt="image" src="https://github.com/user-attachments/assets/486f1816-0776-4881-a012-c5d0d1bf721d">
---|---

subsequent encounter:

https://github.com/user-attachments/assets/75d7f4d0-f38d-4735-9f79-286f6af1350a

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1. I create a new patient, 9 years old. But there are fields for adults:

~~Please open new issue for this. I will fix is separate PR.~~
Fixed at #1260 


> 2. patient: Patient TB. The diagnosis didn't appear in the report in the subsequent encounter

Problem here is that you update date on the participant.
When you do this, both start and end date are set.
When end date is set, participant is considered to be completed.
Therefore, when you start new encounter, it's not associated to that participant.
Instead, new participant is created (and the encounter is considered initial).

Please retest - note that date change should be  done on encounter node only.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env
- android tablet

### Question:
1. Should the "Mode of delivery" field be for children?

<img width="351" alt="image" src="https://github.com/user-attachments/assets/9d438d88-b5ea-4b67-bd0c-67cccc7506e2">


### Checked and Approved:
1. I create a new patient, 9 years old. There are fields for children:

<img width="351" alt="image" src="https://github.com/user-attachments/assets/50c0c072-2d26-46ea-8c96-2fc2e8037b53">

2. I changed the date in the encounter node only. And the diagnosis appears in the report in the subsequent encounter

<img width="1042" alt="image" src="https://github.com/user-attachments/assets/df0a6373-17e2-4956-99ef-473fa8a84420">|<img width="351" alt="image" src="https://github.com/user-attachments/assets/2d2128af-cc25-4d29-b8b1-657f0782248a">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> Should the "Mode of delivery" field be for children?

 Yes, it's a child field.
