### ISSUE TITLE
E-Heza Reports: allow start end date filters for each report [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1259]
## Issue 

Instead of a single limit date, ~~each report~~ ANC and Demographics reports should be filtered by a "start date" and "end date" (similar to Aculte Illness report).

## Task
- change the filters and name appropriately

**Comment by anvmn** [comment]
@adamhstewart 

We have it for Acute Illness report. Suppose we could add it for Demographics.
For other types of reports, this requirement does not make much sense to me.
If we take ANC, setting start date would cut pregnancies in the middle.
If we take Nutrition, we have predefined output (last 12 months, 4 quarters, 2 years). Setting start date there also seems weird. Setting end date would break https://github.com/TIP-Global-Health/eheza-app/issues/1257.

**Comment by anvmn** [comment]
Deployed to live
