### ISSUE TITLE
TB Management: Add "Prescribed Medications" sub activity under the medications activity [5h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#1264]
## Issue

In order to allow changing medications during the course of treatment, we will add the prescribed medications subactivity as it appears in HIV management (substituting the prescription options available for TB).

<img width="1035" alt="E-Heza_System" src="https://github.com/user-attachments/assets/3e7534bb-2688-47f4-8364-af22be22abb0">

Add in the first position

<img width="1056" alt="E-Heza_System" src="https://github.com/user-attachments/assets/a397e768-8fa0-4b9f-8c38-e520bc56f8f9">

## Tasks
- add the subactivity

**Comment by anvmn** [comment]
Duplicate to #1253
