### ISSUE TITLE
Redesign Calendar Widget [8h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#13]
### Issue

On click, popup should appear:

![image](https://user-images.githubusercontent.com/34378755/145789719-c7cdf01b-7d71-4098-9f32-68dd408f8823.png)

**Comment by adamhstewart** [comment]
From https://github.com/TIP-Global-Health/eheza-app/issues/82#issuecomment-1005028464

> There is an additional feature requirement for the following instances of the calendar - we want a "default position" for the calendar widget (different than a default date, because we don;t want to prefill a date for entry)
> 
> In ANC - pregnancy dating, the default position should be the first date of the time period suggested by the previous question.
> In ANC labs - the default position should be the current date (as it's likely that the lab was run in the few days previous)
> In SPV Immunization - the default position should be the next prescribed dose for the given vaccination.

@anvmn This is indeed a regression as we have a default position on the exiting calendar for these things.

**Comment by adamhstewart** [comment]
@anvmn bump 2h or ping me if there are complexities.

**Comment by anvmn** [comment]
@adamhstewart 

> In ANC labs - the default position should be the current date (as it's likely that the lab was run in the few days previous)

Setting current date is not possible, because this would mean that test was run today, and in this case, we don't need to enter date at all. I'll update last date that is allowed, which is yesterday.

**Comment by adamhstewart** [comment]
## QA Analysis

### Works as designed
- All widgets default to the correct position.
