### ISSUE TITLE
Remove Partner Information from History section

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#1320]
## Issue

We should remove the partner information activity with all the questions under this activity. 
![Screenshot from 2024-09-17 15-52-41](https://github.com/user-attachments/assets/b3922771-7f39-4d06-80f0-f864d1477a11)

## Todo

- Remove the partner information activity

**Comment by anvmn** [comment]
Duplicate to #1323. Closing.
