### ISSUE TITLE
Slow loading of '/admin/content' view [8h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#133]
On live, it takes ~60 seconds to load the view, making it difficult to administer content.

**Comment by anvmn** [comment]
New Relic analysis: 53.5 seconds transaction.
2 problematic queries - one runs for 30 seconds, and the other ~10 seconds, twice:


![Selection_478](https://user-images.githubusercontent.com/17882245/152685719-3cc1fa3e-b6ce-4750-92df-c7a76ffb679c.png)

**Comment by anvmn** [comment]
First query:

```
SELECT COUNT(*) AS expressionFROM (SELECT DISTINCT node.nid AS nid, node.title AS node_title, history.timestamp AS history_timestamp, node.created AS node_created, node.changed AS node_changed, node.type AS node_type, users_node.name AS users_node_name, users_node.uid AS users_node_uid, node.status AS node_status, ? AS expressionFROM `node` nodeLEFT JOIN `users` users_node ON node.uid = users_node.uidLEFT JOIN `taxonomy_index` taxonomy_index ON node.nid = taxonomy_index.nidLEFT JOIN `taxonomy_term_data` taxonomy_term_data_node ON taxonomy_index.tid = taxonomy_term_data_node.tidLEFT JOIN `history` history ON node.nid = history.nid AND (history.uid = :views_join_condition_?)) subquery
```




![image](https://user-images.githubusercontent.com/17882245/152685774-b11da41b-eb34-4d47-98d6-e335d722aaf9.png)

**Comment by anvmn** [comment]
Second query:

```
SELECT DISTINCT node.nid AS nid, node.title AS node_title, history.timestamp AS history_timestamp, node.created AS node_created, node.changed AS node_changed, node.type AS node_type, users_node.name AS users_node_name, users_node.uid AS users_node_uid, node.status AS node_statusFROM `node` nodeLEFT JOIN `users` users_node ON node.uid = users_node.uidLEFT JOIN `taxonomy_index` taxonomy_index ON node.nid = taxonomy_index.nidLEFT JOIN `taxonomy_term_data` taxonomy_term_data_node ON taxonomy_index.tid = taxonomy_term_data_node.tidLEFT JOIN `history` history ON node.nid = history.nid AND (history.uid = :views_join_condition_)ORDER BY node_changed DESCLIMIT ? OFFSET ?
```

![Selection_480](https://user-images.githubusercontent.com/17882245/152685869-bb238705-a1e6-4e3c-97dd-cc7f7e62e670.png)

**Comment by anvmn** [comment]
After some digging, per https://www.drupal.org/project/views/issues/1540908, seems that the cause of slowness is `select count(*)` query that is generated by pager.
It's needed to know total number of results view produces. The suggestion is to replace pager with `views_litepager`. It will be showing only next/previous options, and avoid problematic count query.

**Comment by adamhstewart** [comment]
@anvmn Wendy (and others) have experienced timeouts on other admin queries - specifically `/admin/content/mothers` - is it the same issue can we apply there as well?

**Comment by anvmn** [comment]
@adamhstewart 

Yes, that one uses Full pager as well:

![Selection_545](https://user-images.githubusercontent.com/17882245/156379597-43482b5c-3c8f-4900-873f-9093a2f52875.png)

**Comment by adamhstewart** [comment]
@anvmn great - then probably easier to update this issue to add the new pager on those views as well. I can't see the hours used, but let's bump accordingly?

**Comment by anvmn** [comment]
@adamhstewart 
Actually, it's already implemented.
All views under `admin/content` that used to have full pager get lite pager.

**Comment by anvmn** [comment]
This has been deployed for some time now. Closing.

**Comment by adamhstewart** [comment]
@anvmn reopeing as there's still the same issues.

**Comment by anvmn** [comment]
@adamhstewart This can be closed.

**Comment by anvmn** [comment]
Closing...
