### ISSUE TITLE
Circle CI tasks timeout after 1h execution [3h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#1335]
All failing tasks state 1h execution time. For example:

https://app.circleci.com/pipelines/github/TIP-Global-Health/eheza-app/4742/workflows/022cde6a-0985-44b5-9143-90f92554c68b/jobs/16322

![Selection_875](https://github.com/user-attachments/assets/47a43281-378b-4441-ac77-f29141e65fa8)

**Comment by AronNovak** [comment]
@anvmn With #1342 , do you consider the tests are stable enough according to the past two weeks?

**Comment by anvmn** [comment]
@AronNovak Seem that tests now run under 40 minutes, so it's fine.
