### ISSUE TITLE
ANC Logic - Diagnosis and Next Steps: Malaria [12h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#136]
## Issue 
 
If the patient's lab result for Malaria comes back POSITIVE there will be next steps. The next steps vary based on EGA as shown below (and outlined in the logic document). Note: the nurse will choose ONE course of action to move forward with. 
**<= 14 Weeks EGA**
PopUp | Selection | Referral (if the referral option is selected) 
--|--|--
<img width="262" alt="Screen Shot 2022-02-23 at 11 46 10 AM" src="https://user-images.githubusercontent.com/77505464/155366234-6afe0ca8-e934-422f-afb2-86e9d8fab961.png"> | <img width="262" alt="Screen Shot 2022-02-23 at 11 46 16 AM" src="https://user-images.githubusercontent.com/77505464/155366236-fbe5c2cd-809a-4f8b-a87c-cbce772a8ea1.png"> | <img width="258" alt="Screen Shot 2022-02-23 at 11 46 23 AM" src="https://user-images.githubusercontent.com/77505464/155366237-28360ea4-94fd-488a-8595-e9b731ee49bd.png">

**> 14 Weeks EGA**
PopUp | Selection | Referral (if the referral option is selected) 
--|--|--
<img width="261" alt="Screen Shot 2022-02-23 at 11 46 33 AM" src="https://user-images.githubusercontent.com/77505464/155366539-09e02622-e976-4dab-9026-cab4c6f5058f.png"> | <img width="258" alt="Screen Shot 2022-02-23 at 11 46 39 AM" src="https://user-images.githubusercontent.com/77505464/155366541-43c62bf1-0209-404e-8c9f-f14dce522d84.png"> | <img width="255" alt="Screen Shot 2022-02-23 at 11 46 46 AM" src="https://user-images.githubusercontent.com/77505464/155366542-4efa8012-73f9-4d15-ac1f-4a11e6082215.png">

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma under [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) under the purple logic heading. 

## Note: 
- The next steps should appear after the initial encounter with the patient, not after they return for lab results. 
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
 
## To Do: 

- Create next steps activities 
- Diagnosis Logic 
- Create necessary pop-ups and the logic to display them 
- Style per Design

**Comment by anvmn** [comment]
@jeanette-pelizzon 



![Selection_513](https://user-images.githubusercontent.com/17882245/154862119-d863d468-5836-4175-9fe9-62ec011df0cb.png)

> Any EGA with GI complications: See Written Protocols

Please define what GI complications are.

> Any EGA with Malaria with Complications: Stabilize and Refer to Hospital

Please define what complications are.

**Comment by jeanette-pelizzon** [comment]
@leowea - This is meant to be based on the same logic as we have in the AI module, however we do not collect the information needed to determine any malaria complications in this module (no symptom review). Should we then have follow up questions if a Malaria RDT comes back positive? Or change next step instructions to have nurse determine on their own? 

// @anvmn @adamhstewart

**Comment by leowea** [comment]
@jeanette-pelizzon For now, let's use the following options that the nurse can choose from. She can check one, two or three options.
Options if <=14weeks EGA:
Give quinine sulphate per os 10 mg/kg/dose, 3 times a day for 7 days
GI complications, Followed Written Protocols
Severe Malaria- Stabilize and Refer to Hospital

Options >14 wks EGA: 
Coartem 4 tablets by mouth twice per day x 3 days
GI complications: Followed Written Protocols
Severe Malaria: Stabilize and Refer to Hospital

This may shift with the next sprint when we add a symptom review. Please let me know if you have other questions on this!
// @adamhstewart @anvmn

**Comment by jeanette-pelizzon** [comment]
@anvmn I updated the designs, the logic document and the main issue to reflect changes made to this flow.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

1. As a rule, requirements are supposed to appear at issue description.
If requirements are updated, issue description needs to be updated as well.
Please update issue description.

2. Should the selection be single or multiple? Please clarify.

3. Please clarify is after the popup, we need to navigate to next steps activity or not.

**Comment by jeanette-pelizzon** [comment]
@anvm: 

(1) Updated the issue description. Thanks for the feedback. 
(2) Single. 
(3) The pop-up will appear in the next step section. A positive malaria test shouldn't interrupt the encounter flow.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Please consider following scenario:

**HIV:**
  Test posiitve + HIV/PMTCT program exists at health center  => requires refferal to program.

**Malaria:**
  Test posiitve + Severe Malaria: Stabilize and Refer to Hospital at Dignosis + Medication activity => requires refferal to hospital.

So, here we have 2 referrals, which is impossible as we have single Referral activity.
I'm setting priority to 'Refer to Hospital', which means that patient may not get the ARVs.
Tell me if this needs to work in a different manner.

//cc @adamhstewart

**Comment by leowea** [comment]
@anvmn It makes sense to prioritize the hospital referral. We would want to be sure that the progress report identifies new diagnoses though. In our next sprint, we will be working on how to follow up with new diagnoses. We can have a way to identify women diagnosed with HIV and whether or not they have received ARVs.
// @jeanette-pelizzon @adamhstewart

**Comment by adamhstewart** [comment]
## QA Analysis

### Works as expected

- When malaria is indicated, next steps includes the popup and the referral sub activity 

### Needs followup

- There is not the required medication disbursement sub activity after a positive malaria test
- as a result, cannot test the EGA factor which determines dosage.

![image](https://user-images.githubusercontent.com/688507/160701275-db286bd6-8e88-455e-afff-21c44b082e64.png)

**Comment by anvmn** [comment]
@adamhstewart

EGA determines if first option will be Coartem or Quinitine Sulphate.
It's not about dosages.

Only time we will display additional sub activity, is when selected treatment is 'refer to hospital'.

**Comment by jeanette-pelizzon** [comment]
Less than or equal to 14 weeks = Quinine 

Greater than 14 weeks = Coartem
