### ISSUE TITLE
ANC Logic - Diagnosis and Next Steps: Hep B [12h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#137]
## Issue 

If the patient's lab results have come back positive of Hepatitis B: 

Diagnosis | Referral 
--|-- 
<img width="248" alt="Screen Shot 2022-02-07 at 12 26 23 PM" src="https://user-images.githubusercontent.com/77505464/152840022-99c89fba-ccaa-45e7-b650-276acbaf4195.png"> | <img width="247" alt="Screen Shot 2022-02-07 at 12 27 08 PM" src="https://user-images.githubusercontent.com/77505464/152840144-39d8ab1e-41ec-4b4b-859f-1e640531c6dc.png">

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma under [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) under the purple logic heading. 

## Note: 
- The next steps should appear after the lab results have been returned when the patient returns to the point of care. 
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
 
## To Do: 

- Create next steps activities 
- Diagnosis Logic 
- Create necessary pop-ups and the logic to display them 
- Style per Design

**Comment by adamhstewart** [comment]
## QA Analysis
## Works as designed
- Diagnosis is shown in next steps after positive test result and is referred to the hospital.
