### ISSUE TITLE
ANC Logic - Diagnosis and Next Steps: Anemia [12h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#138]
## Logic 

During the encounter, the patient has their hemoglobin levels tested. If the hemoglobin levels are under a specific g/DL then it shows the patient has Anemia in general (severity is dependent on exact g/DL levels per logic doc). Anemia is also a side effect of having Malaria so we need to rule out a malaria diagnosis before treating for Anemia. If Negative for malaria and with low hemoglobin levels the patient is Anemic and we then decide how anemic to determine next steps. If positive for Malaria, follow malaria diagnosis logic #136. 

**Mild to Moderate Anemia** | **Severe Anemia** | **Severe Anemia with Complications** 
--|--|--
<img width="316" alt="Screen Shot 2022-02-07 at 12 32 51 PM" src="https://user-images.githubusercontent.com/77505464/152841298-b06ccd36-1134-4a13-9c5d-29103b30f043.png"> | <img width="272" alt="Screen Shot 2022-02-07 at 12 33 09 PM" src="https://user-images.githubusercontent.com/77505464/152841415-2400f68c-0d14-4743-84b8-b3f3ee655959.png"> | <img width="299" alt="Screen Shot 2022-02-07 at 12 40 21 PM" src="https://user-images.githubusercontent.com/77505464/152842295-a36137a8-4f8f-4b9f-8f4d-f6a5448c4020.png">
<img width="245" alt="Screen Shot 2022-02-07 at 12 33 50 PM" src="https://user-images.githubusercontent.com/77505464/152841322-9ce70731-a2a7-4a06-87d3-d04a847d7f4b.png"> | <img width="199" alt="Screen Shot 2022-02-07 at 12 39 08 PM" src="https://user-images.githubusercontent.com/77505464/152842121-b6f917ae-07f4-482d-85a7-cec1e56a7c57.png"> | <img width="301" alt="Screen Shot 2022-02-07 at 12 40 26 PM" src="https://user-images.githubusercontent.com/77505464/152842318-c29ddb11-8bd6-4582-af45-9113ceafd661.png">

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma under [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) under the purple logic heading. 

## Note: 
- The next steps should appear after the lab results have been returned when the patient returns to the point of care.
- Exception: **For Severe with complications, will pop up immediately once the logic is met - will not wait until the end of the encounter**
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
 
## To Do: 

- Create next steps activities 
- Diagnosis Logic 
- Create necessary pop-ups and the logic to display them 
- Style per Design

**Comment by adamhstewart** [comment]
## QA Analysis
- Pathways for mild to moderate, severe, and severe with complications appear as expected with the correct lab results.

### Needs followup
- Looks like for anemia we have even a third medical distribution sub activity (see #172 )
 
![image](https://user-images.githubusercontent.com/688507/160720119-bf98ea08-3e0c-4abb-8b5d-81db06e5759f.png)

**Comment by adamhstewart** [comment]
@anvmn @jeanette-pelizzon moving this over in favor of #203

**Comment by jeanette-pelizzon** [comment]
Anemia should only have medication distro OR hospital referral.
