### ISSUE TITLE
ANC Logic - Diagnosis and Next Steps: Hypertension [12h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#140]
## Issue

Hypertension is a disease that is diagnosed through monitoring blood pressure. There are two types of hypertension: 

- Gestational = under 20 weeks EGA
- Chronic = over 20 weeks EGA 

The EGA is the only thing that affects whether it is gestational or chronic.

In this flow, the nurse will be able to check **one** of three options for treatment. 

There are two flows for hypertension. 

**Return for Vital Check Flow**
Initial Diagnosis | Next Steps | Case Mgmt   
--|--|--
<img width="272" alt="Screen Shot 2022-02-07 at 4 13 01 PM" src="https://user-images.githubusercontent.com/77505464/152872947-ae6bac77-595d-4e35-8414-6a031722fc85.png"> | <img width="268" alt="Screen Shot 2022-02-07 at 4 13 15 PM" src="https://user-images.githubusercontent.com/77505464/152872971-899496c3-021a-4c2d-9bfa-d2a4dd458a39.png"> | <img width="377" alt="Screen Shot 2022-02-07 at 4 14 55 PM" src="https://user-images.githubusercontent.com/77505464/152873062-34b779f4-93b0-44ba-a697-cab69a39b2de.png">  

Vitals Recheck | Final Diagnosis | Next Steps
--|--|--
<img width="269" alt="Screen Shot 2022-02-07 at 4 13 09 PM" src="https://user-images.githubusercontent.com/77505464/152873283-e9f8cea2-c1fc-4c51-8caa-6ac8709583a7.png"> | <img width="268" alt="Screen Shot 2022-02-07 at 4 13 23 PM" src="https://user-images.githubusercontent.com/77505464/152873141-c5499204-28e3-436a-b4bb-78ed798456e3.png"> |<img width="282" alt="Screen Shot 2022-03-01 at 5 12 33 PM" src="https://user-images.githubusercontent.com/77505464/156257830-a71221bf-94ad-47cd-a80a-2d7e9cfbab92.png">

**No Vital Check Needed**
Diagnosis | Next Steps
--|-- 
<img width="285" alt="Screen Shot 2022-02-07 at 4 26 19 PM" src="https://user-images.githubusercontent.com/77505464/152874934-0c6ada62-9577-4746-a7c7-367944a2b0f8.png"> | <img width="282" alt="Screen Shot 2022-03-01 at 5 12 33 PM" src="https://user-images.githubusercontent.com/77505464/156257869-b0c31d5a-eada-4ed8-82fb-0a81484a4258.png">

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma under [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) under the purple logic heading. 

## Note: 
- The next steps can appear after the initial touch point with the nurse if able to diagnose without a vital recheck. Otherwise, they will appear after the vitals are rechecked.
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
- You may notice that in some cases we can diagnose hypertension right away but then the diagnosis would change to pre-clampsia based on lab results. We should still diagnose and prescribe the hypertension medication if they qualify. Then we will add on the preeclampsia diagnosis and send them to the hospital to get taken care of.
 
## To Do: 

- Create next steps activities 
- Diagnosis Logic 
- Create necessary pop-ups and the logic to display them 
- Style per Design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

1.
> (2) If the follow up is still within these ranges, perscribe:
>  1. Methyldopa 250mg 1 tablet by mouth three times a day.
>  2. Methyldopa 250mg 1 tablet by mouth four times a day.

This looks strange to me. Based on what nurse needs to decide if to perscribe 3 or 4?
If this is really what is required, I'd expect to see some kind of instructions on form.

2. 
![Selection_512](https://user-images.githubusercontent.com/17882245/154861131-61e947b6-a23a-47fa-9444-c8e90c1fab82.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn 

Chronic Hypertension: I believe the nurse gets to decide to do 3x or 4x a day based on some clinical factors. I will let @leowea chime in here. 

Gestational Hypertension: It is my understanding that the nurses have a medication table that they refer to. I believe we don't give specific dosages here because it may depend on weight or another factor that we don't ask for. 

// @adamhstewart

**Comment by leowea** [comment]
@jeanette-pelizzon @anvmn @adamhstewart 
Thanks for tagging me on this. I should have removed the 'see medication table'. All pregnant women who are going to be treated with medication for any form of high blood pressure will receive methyldopa 250mg at varying doses. The nurse should give methyldopa 250mg by mouth twice a day when first diagnosed with hypertension. If still high the next visit, the dose should go up by 250mg, and this continues with each visit to a maximum of 500mg twice a day. My preference would be to give the nurse options so that she can increase the dose on her own if she wants to.
Here would be the ideal- the below options are always provided. The recommended dose would appear in parentheses next to the dose, but the nurse could choose any option. For example- no medication previously prescribed, then (recommended) would be next to the first option. If 2 times a day was prescribed last visit and the blood pressure remains high this time, then (recommended) would be next to the second option, etc.
Methyldopa 250mg by mouth two times a day 
Methyldopa 250mg by mouth three times a day
Methyldopa 250mg by mouth four times a day

@jeanette-pelizzon sorry this has shifted. The NCD protocol had information that wasn't in the ANC protocol. Please let me know if this doesn't make sense. Also- if the (recommended) part is too complicated, we can just have the 3 options and let the nurses decide what to give.

**Comment by jeanette-pelizzon** [comment]
@anvmn I updated the logic in the document and the design. What are your thoughts on the technical difficulty of the (recommended) appearing next to the appropriate dose based on past prescriptions? I kept that out of the design for now so it doesn't hold anything up immediately. 

<img width="258" alt="Screen Shot 2022-02-23 at 12 34 38 PM" src="https://user-images.githubusercontent.com/77505464/155374913-b8c0a74c-096c-419a-b055-eb35b904343f.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> What are your thoughts on the technical difficulty of the (recommended) appearing next to the appropriate dose based on past prescriptions

This will require 2-3h to implement.

**Comment by jeanette-pelizzon** [comment]
@anvmn I spoke with Adam and we are going to move forward with implementing the recommended call out. Here is an example of what that should look like: 
<img width="282" alt="Screen Shot 2022-03-01 at 5 12 33 PM" src="https://user-images.githubusercontent.com/77505464/156257702-36a1a6e7-ff79-4c7e-8789-5643f127a4a1.png">

Do I need to make this a separate issue?

**Comment by anvmn** [comment]
@jeanette-pelizzon

No, we can have this issue updated with requirements and estimation.

**Comment by adamhstewart** [comment]
@anvmn I can't select the recommended checkbox:

![image](https://user-images.githubusercontent.com/688507/160654116-58397a1d-1086-43bd-b53e-3fb0a59ba62e.png)

The HTML looks like maybe it's out of order with the prechecked input falling outside the div.

**Comment by anvmn** [comment]
@adamhstewart  ^^ is fixed at #194

**Comment by anvmn** [comment]
@adamhstewart #194 is deployed, so ^^ can be retested

**Comment by adamhstewart** [comment]
Rechecked and approved
