### ISSUE TITLE
ANC Logic - Diagnosis and Next Steps: Syphilis [12h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#141]
## Issue 

Syphilis is diagnosed via a lab test. 

If negative, repeat the test at 32 - 34 weeks EGA. 

If positive, the patient will then go through a syphilis specific symptom review. That will determine if the medication they need and/or if they are to be sent to the hospital for further evaluation. This flow is different as we are allowing the nurse to select which medication and dosage they will be prescribing. An alert will pop up if Azithromycin or Ezthromycin is chosen (as seen in the screen below) 

**Normal Syphilis** 
If no symptoms or any symptoms except headaches or vision changes are selected in the symptom review.
Initial Diagnosis | Symptom Review | Medication | Medication Alert
--|--|--|-- 
<img width="226" alt="Screen Shot 2022-02-07 at 5 42 03 PM" src="https://user-images.githubusercontent.com/77505464/152884551-ddbcdbdf-5a14-4e87-9580-e57be223d810.png"> | <img width="255" alt="Screen Shot 2022-02-07 at 5 38 57 PM" src="https://user-images.githubusercontent.com/77505464/152884397-7758f444-dcaa-49f3-9613-7a197a248362.png"> | <img width="256" alt="Screen Shot 2022-02-07 at 5 39 03 PM" src="https://user-images.githubusercontent.com/77505464/152884425-ab92686d-b535-407b-a018-4114c76737f8.png"> | <img width="257" alt="Screen Shot 2022-02-07 at 5 39 10 PM" src="https://user-images.githubusercontent.com/77505464/152884464-575fb83d-99c8-47f7-8aee-9f4d011f1bb9.png">

**Potentially Nuerosyphilis** 
 If headaches or vision changes are selected in the syphilis symptom review
 
Initial Diagnosis | Symptom Review | Diagnosis | Referral 
--|--|--|--
<img width="283" alt="Screen Shot 2022-02-07 at 5 59 31 PM" src="https://user-images.githubusercontent.com/77505464/152887719-cc9bfff3-9c9a-4f2b-b52d-89c3f111539a.png"> | <img width="360" alt="Screen Shot 2022-02-07 at 6 08 21 PM" src="https://user-images.githubusercontent.com/77505464/152887734-5863f001-58e3-48ba-ae81-9617b2a59773.png"> | <img width="282" alt="Screen Shot 2022-02-07 at 5 59 55 PM" src="https://user-images.githubusercontent.com/77505464/152887758-a31c056f-33ba-430a-a892-aeee4be546da.png"> | <img width="278" alt="Screen Shot 2022-02-07 at 6 00 04 PM" src="https://user-images.githubusercontent.com/77505464/152887781-e2a39fa2-e9fc-41c1-8de0-0f5bd5a5c441.png">

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma under [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) under the purple logic heading. 

## Note: 
- The next steps should appear after the patient has received their lab results. 
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
 
## To Do: 

- Create next steps activities 
- Diagnosis Logic 
- Create necessary pop-ups and the logic to display them 
- Style per Design

**Comment by anvmn** [comment]
@jeanette-pelizzon 
The way I see it, if syphilis lab result is positive, we should ask about symptoms right away.
No need to wait till we get to Next Steps.
So, there will be another dynamic task on the form that is presented if test result is positive:

![Selection_571](https://user-images.githubusercontent.com/17882245/157443551-98e2458a-409c-4a86-aec1-82abef257a95.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn good catch! I updated Figma. The follow-up questions should appear right after the positive test but the diagnosis and next steps should appear in the next steps section.

**Comment by adamhstewart** [comment]
## QA analysis

### Works as designed
- Syphilis positive, popup and medications as expected
- Syphilis positive + headaches/vision popup and referral as expected
