### ISSUE TITLE
ANC Logic - Diagnosis and Next Steps: Placenta Previa - Placental Abruption - Uterine Rupture [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#143]
## Issue

When a patient meets the criteria for Placenta Previa, Placental Abruption, Uterine Rupture it will trigger the pop-up and immediately go to referral. The patient will not finish the encounter as this is an emergency situation.

Pop-Up | Referral 
--|--
<img width="255" alt="Screen Shot 2022-02-07 at 6 38 36 PM" src="https://user-images.githubusercontent.com/77505464/152890417-a43a22b0-47ba-4402-a17d-6e2267d079b7.png"> | <img width="263" alt="Screen Shot 2022-02-07 at 6 29 29 PM" src="https://user-images.githubusercontent.com/77505464/152890431-a9c19827-bc1b-4a65-ab61-bb222ec7a948.png">

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma under [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) under the purple logic heading. 

## Note: 
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
 
## To Do: 

- Create next steps activities 
- Diagnosis Logic 
- Create necessary pop-ups and the logic to display them 
- Style per Design

**Comment by adamhstewart** [comment]
## QA Analysis

### Works as designed
- Warning shows in a pregnancy after 28 weeks with vaginal bleeding.
