### ISSUE TITLE
ANC Logic - Diagnosis and Next Steps: Post Abortion Sepsis [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#145]
## Issue

When a patient meets the criteria for Post-Abortion Sepsis it will trigger the pop-up and immediately go to referral. The patient will not finish the encounter as this is an emergency situation.

Pop-Up | Referral 
--|--
<img width="316" alt="Screen Shot 2022-02-07 at 6 44 39 PM" src="https://user-images.githubusercontent.com/77505464/152890939-4eb5e1da-f259-4602-a9ea-b38dea441443.png"> | <img width="263" alt="Screen Shot 2022-02-07 at 6 29 29 PM" src="https://user-images.githubusercontent.com/77505464/152890431-a9c19827-bc1b-4a65-ab61-bb222ec7a948.png">

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma under [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) under the purple logic heading. 

## Note: 
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
 
## To Do: 

- Create next steps activities 
- Diagnosis Logic 
- Create necessary pop-ups and the logic to display them 
- Style per Design

**Comment by anvmn** [comment]
@jeanette-pelizzon 
We have got at least 2 more options that match the criteria:

![Selection_493](https://user-images.githubusercontent.com/17882245/153435286-d4e6362e-85be-4441-bfa6-188fa57ac36a.png)

How do we decide what diagnosis to show?

**Comment by jeanette-pelizzon** [comment]
It's dependent on the EGA: 

- Uterine Rupture | Obstructed Labor | Placental Abruptions = greater than or equal to 22 weeks EGA + severe abdominal pain 

- Ectopic Pregnancy = less than 22 weeks EGA + severe abdominal pain

**Comment by anvmn** [comment]
@jeanette-pelizzon I am asking about Post Abortion Sepsis

**Comment by jeanette-pelizzon** [comment]
Oh sorry, I just looked at the red things. I will have to ask Wendy and report back as that's the only information I have.

**Comment by jeanette-pelizzon** [comment]
@anvmn we are taking this away as an individual diagnosis. It will be combined with #144 and #146 as a potential diagnosis. Closing this issue and updating the others.
