### ISSUE TITLE
ANC Logic - Infection (NOT DONE YET - NEEDS MORE INFO)

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#147]
## Issue

When a patient meets the criteria for Infection it will trigger the pop-up and immediately go to referral. The patient will not finish the encounter as this is an emergency situation.

Pop-Up | Referral  
any EGA + fever + RR > 30 OR  extreme weakness (danger signs)
--|--
<img width="319" alt="Screen Shot 2022-02-07 at 7 42 29 PM" src="https://user-images.githubusercontent.com/77505464/152896351-bfe67779-2d37-42fd-9613-df3696e63e7e.png"> | <img width="263" alt="Screen Shot 2022-02-07 at 6 29 29 PM" src="https://user-images.githubusercontent.com/77505464/152890431-a9c19827-bc1b-4a65-ab61-bb222ec7a948.png">

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma under [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) under the purple logic heading. 

## Note: 
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
 
## To Do: 

- Style next step screens per design 
- Adjust logic per document

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Still not ready?

**Comment by jeanette-pelizzon** [comment]
We are holding off this diagnosis for now. Will revisit in a later sprint. Closing this issue now.

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Saw that one path was held of, but there was another one:

![Selection_501](https://user-images.githubusercontent.com/17882245/154312943-b5761e24-8692-4eee-b782-685cb1f4c1e9.png)

To summarise, we should not have Infection diagnosis at all?
