### ISSUE TITLE
ANC Logic - Next Steps Sub-Acitivities 

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#152]
## Issue: 
In the next steps activity for ANC @ Health Centers, there are four different sub-activities that could be triggered by a diagnosis. 

Health Education | Medication Distribution | Referral | Wait 
--|--|--|--
![Property 1=Done (2)](https://user-images.githubusercontent.com/77505464/153045223-72287be6-c74f-40ec-9bf3-edbfbaa23af6.jpg) | ![this](https://user-images.githubusercontent.com/77505464/153045488-b177778b-7da6-48e7-98ed-25cef4c63f57.jpg) | ![Property 1=Done](https://user-images.githubusercontent.com/77505464/153045286-5578a4bb-1215-46de-8eb3-ed9212ca6549.jpg) | ![Property 1=Done (3)](https://user-images.githubusercontent.com/77505464/153045304-b3408197-ca10-4ad6-9a8d-6baa0a40bd73.jpg)

You can find which sub-activities are triggered for each diagnosis by looking at that specific issue.  

After the subactivities are completed then the progress report should be shown and the nurse can close out of the encounter from there. 

## Note: 

Please read over the meta issue, specifically, the overview of the next steps flow as it is different than what we have created before. 

## Design:
SVG files can be downloaded from Figma [here.](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=4126%3A13171) 

## To Do: 

- create each subactivity

**Comment by anvmn** [comment]
@jeanette-pelizzon 

For context, these are activities that generates entities stored on backend.
Development of such activity is done both for front end and back end.
Simple activities require 4h. More complex (with many inputs, or non trivial logic for example), require more.

At Prenatal module, we already have Health education and Send to HC activities.
Most likely we can make some additions to use them for ANC Logic (Send to HC will become Referral).
As for other 2, we'll need to create them as an infrastrucutre issues (as they're used at different scenarios).
I'll create and issue for Medication distribution, as it's needed for #113.

//cc @isapisa

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Went over the designes, and did not find the Wait activity anywhere. Did we give up on it?

**Comment by adamhstewart** [comment]
@anvmn @jeanette-pelizzon it seems this issue has been covered as part of other issues, but I think highlights the issue I raised in https://github.com/TIP-Global-Health/eheza-app/issues/124#issuecomment-1082437031

Let's then make this the controlling issue for that fix: 

There should be only one sub activity (and associated icon) which holds "Medication disbursement" - multiple diagnosis with medical disbursement should be contained under one sub activity.

**Comment by jeanette-pelizzon** [comment]
In next steps, the medication acitvites - whether it is a multiple choice or a directive - need to be under the sub-activity "Medication Distribution"

**Comment by anvmn** [comment]
@jeanette-pelizzon 

This is a complex requirement,  and I'd say it will require minimum of 10 hours. Probably more.

It may have been a little easier if we had it in 2 steps, so, at first step recomended treatment option would be selected (as it's done now), and at second, we'd ask standard set of questions that are asked for any medication. Here I could say it's 5-6 hours.

Please open a new issue for this.
If you prefer the 'hard' way, please update designs for those diagnosis that require it.
I think it's syphilis and hypertension. Also, do we leave the 'No treatment administered' option, or make it something else?


//cc @adamhstewart

**Comment by anvmn** [comment]
@adamhstewart 
I believe we do not need this issue for tracking anymore, as we have #255.
Can it be closed?
