### ISSUE TITLE
ANC Logic - Danger Signs Addition [1h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#153]
## Issue 

In order to diagnose some issues in ANC @ Health Centers, we need to add some symptoms to the Danger Signs activity. 

Here is the complete list of danger signs with the new additions highlighted in blue: 
<img width="492" alt="Screen Shot 2022-02-08 at 1 08 08 PM" src="https://user-images.githubusercontent.com/77505464/153049166-d4827bdd-9e3f-4d97-800a-3a0bfa3399f8.png">

The design already exists, we are just adding more options. Here is the design with the new options for reference:  
<img width="321" alt="Screen Shot 2022-02-08 at 1 15 53 PM" src="https://user-images.githubusercontent.com/77505464/153050494-42a242c7-12b5-4e8b-b977-3a4abea41279.png">

## To Do: 

- Add new options 
- Style per design

**Comment by adamhstewart** [comment]
## QA Analysis

##W Works as designed
- New options added:

![image](https://user-images.githubusercontent.com/688507/160696359-224e497d-d7ad-448d-975e-2046875371d7.png)
