### ISSUE TITLE
ANC Logic - ANC Progress Report Update [12h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#154]
## Issue 
The issues that the app diagnosis need to populate on the progress report in the appropriate section. The different diagnoses, the wording that should appear on the progress report, and the section that it should appear on can be found on [Logic Master](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=2144570215) on the ANC Progress Report tab. The wording follows a template of Diagnosis + Complications (if any) + Action Taken + Date. 

E-Heza will have to populate the medication prescribed, the complications (for Hep B and Syhilis), and the date the action was taken. 

Here is an example of the progress report with sample diagnoses filled in: 

![__Anetnatal Progress Report](https://user-images.githubusercontent.com/77505464/153917114-a87a88b5-ef46-4ab0-992b-545147bd9d0d.jpg)

## To Do: 
- Logic for Diagnosis to populate
- Style per Design

**Comment by jeanette-pelizzon** [comment]
@leowea only Syphilis diagnosis go in Medical History. Can we move this to the Medical Diagnosis section to consolidate the report?

**Comment by leowea** [comment]
Sure!


Wendy Leonard, MD, AAHIVS

Executive Director

TIP Global Health (formerly The Ihangane Project)

***@***.*** | +1 831 234 6053
www.tipglobalhealth.or <http://www.tipglobalhealth.org/>g



*Hope lies in dreams, in imagination, & in the courage of those who dare to
make dreams into reality. **- Jonas Salk*

**Comment by jeanette-pelizzon** [comment]
Dating - should go newest to oldest

**Comment by anvmn** [comment]
@jeanette-pelizzon 

After reviewing the requirements, here's a summary:

We have ~ 30 different diagnoses.
Some are straightforward - have single option for treatement.
Others are more complex - different sympoms trigger different treatment. When it comes to progeress report, we need to present both the symptoms and the treatment (Anemia with severe complications, Syphilis), so it's more time consuming.
If we stick to implementing the requirements exactly as stated at Logic Master, I'd say it's 8 - 10 hours task.

However, there are questions that may make things more complex, and time consuming:

1. `[diagnosis] referred to hospital on XX/XX/XXXX`: 

When we send to hospital, nurse may select 'No' answer, and then a reason why referral was not done:

![Selection_599](https://user-images.githubusercontent.com/17882245/159490635-31b2e19d-30b4-417a-8381-5111d6ff60a1.png)

There're no requirements for this case. Does it mean that we do not present anything?
Alternatively, what should be presented?

2. `Hypertension treated with Methyldopa on XX /XX/XXXX`,
    `Syphilis with X complication treated with X medication on XX/XX/XXXX`

Though there's no option to say that treatment was not prescribed, nurse can leave 
Diagnosis + Medicine activity incompleted.
What do we do in this case?

3.  `[diagnosis] treat with medicine(s) on XX /XX/XXXX`:
When we prescribe medication, nurse can select 'No' answer, and then select a reason why medication was not prescribed:

![Selection_600](https://user-images.githubusercontent.com/17882245/159505278-da1797e4-e0ff-4a0e-b10d-6c738024f420.png)

What do we do in this case?

4. `Malaria treated with Coartem on XX/XX/XXXX OR Malaria treated with Quinine Sulphate on XX/XX/XX`:

There're other 2 possibilities for treatment:

![Selection_601](https://user-images.githubusercontent.com/17882245/159505893-bec198b2-2b81-4894-a1cf-fe2fb10ca22d.png)

I suppose that if reffered to hopital, we do same as other diagnoses that refer to hospital,
but what do we do for the 'written protocols' option?

**Comment by jeanette-pelizzon** [comment]
1) We should still present something as the patient has been diagnosed with something and they will need to see that in future visits. I suggest this format: 
- [diagnosis] referred to hospital on XX/XX/XXXX - [reason why patient didn't go to hospital]

2) I feel like in those cases maybe we should make a check box or something that says the medicine was not given. Either way the progress report should then read:  
- Hypertension diagnosed on XX/XX/XXXX - medication was not prescribed due to [reason]
- Syphilis with X complication diagnoses on XX/XX/XXXX - medication was not prescribed due to [reason]

3) In this case I suggest: 
- [diagnosis] was diagnoses on XX/XX/XXX  - medication was not prescribed due to [reason]

4) Agree on the hospital situation. I would say for the GI one:  
- Malaria with GI complications diagnoses on XX/XX/XXX - written protocols followed 

@anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> I feel like in those cases maybe we should make a check box or something that says the medicine was not given.

Well, this does not solve it, because nurse can leave Diagnosis + Medicine activity incomplete anyway.
I suggest something more general, like 'No treatement recorded' message.

**Comment by anvmn** [comment]
@jeanette-pelizzon given these additional requirements, please set time estimation to 12h.

**Comment by jeanette-pelizzon** [comment]
> @jeanette-pelizzon
> 
> > I feel like in those cases maybe we should make a check box or something that says the medicine was not given.
> 
> Well, this does not solve it, because nurse can leave Diagnosis + Medicine activity incomplete anyway. I suggest something more general, like 'No treatement recorded' message.

It should follow the other medications format though. So adding in a question about "did the you prescribe the medication to the patient?" yes/no -- no with the options? 

![Next Steps Template](https://user-images.githubusercontent.com/77505464/159719327-2ec64339-d274-4989-8dc2-a3658703c66b.jpg)

**Comment by anvmn** [comment]
@jeanette-pelizzon 
This is not going to work. It's not standard medication.
Malaria for example have 2 options which are not medication at all.

This is complex enough by itself, so If not treatement option is needed, we can add it as another checkbox.
This is not simple development, but possible.

Adding a reason will break the design completly, and will require several days to redesign and redevelop.

**Comment by jeanette-pelizzon** [comment]
Ah okay, I didn't realize the complexity.  I will defer to you on what you think is best here then.

**Comment by adamhstewart** [comment]
@anvmn @jeanette-pelizzon I'm not certain of the status here.

**Comment by anvmn** [comment]
@adamhstewart deployed to Nutritition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. When setting Abnormal Vaginal discharge with Yes to vaginal itching and urethral discharge (candidiasis+gonorrhea), medical distribution cannot be completed.
Selecting yes for either Ceftriaxone or Azithromycin and clicking save on Medical distribution doesn't add the checkmark icon, and doesn't move this item to the Completed tab. Clkicking Save on the already completed Health education doesn't move focus to the next icon (Medical distribution).

![2-save-not-working](https://user-images.githubusercontent.com/3536805/177169326-64be62cc-7943-4808-92ae-c6e07f624a92.png)
![4-next-steps](https://user-images.githubusercontent.com/3536805/177169344-9a73e6a1-070b-446b-9df5-f40939b0cb71.png)

2. CHW Activity section is missing from Progress report. Is there a way to display it?

### Checked and approved:

1. Syphilis treatment is moved under Medical diagnosis.
![8-syphilis](https://user-images.githubusercontent.com/3536805/177178302-36c5bfc8-a2be-4e38-b711-ed0ac012cbb5.png)

2. Risk factors.
![5-risk-factors](https://user-images.githubusercontent.com/3536805/177178369-0df9cbb4-0a62-4262-92c2-bf32b26a0f3d.png)

3. Medical, Obbstretrical diagnosis, Patient progress.
![6-medical-obstretrical-patient-progress](https://user-images.githubusercontent.com/3536805/177178443-324acf38-eac3-4dd3-a54a-9c202a3d4fa6.png)

4. Lab results:
![4-lab-results](https://user-images.githubusercontent.com/3536805/177178506-3b43debc-33ac-4b31-89c1-57f5ed0949de.png)

5. Photos display.
![7-photos](https://user-images.githubusercontent.com/3536805/177178336-57e06522-b9b1-44f5-8f61-4957caeabdea.png)

**Comment by anvmn** [comment]
@balagan73 

> CHW Activity section is missing from Progress report. Is there a way to display it?

There's a dedicated issue for this, and it's still being developend (by @Diama1).
See https://github.com/TIP-Global-Health/eheza-app/pull/119.

**Comment by anvmn** [comment]
@balagan73 

Please retest point 1

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. I have reproduced the same situation: Candidiasis + Gonorrhea. Now after filling both forms and then clicking save in either subactivity under Next steps opens the Progress report (all other activities are finished), but cannot end encounter. Medical distribution still has no checkmark.

Medication:
![15-medication](https://user-images.githubusercontent.com/3536805/178761705-5ab11255-b110-4abc-963b-d8c1e5aa5eb8.png)
Progress report:
![16-cannot-end-encounter](https://user-images.githubusercontent.com/3536805/178762163-43b05522-8493-417e-ba2b-f03b4100d072.png)

**Comment by jeanette-pelizzon** [comment]
Interesting. Passing back to @anvmn to take a look at.

**Comment by anvmn** [comment]
@balagan73 

> I have reproduced the same situation: Candidiasis + Gonorrhea. Now after filling both forms and then clicking save in either subactivity under Next steps opens the Progress report (all other activities are finished), but cannot end encounter. 

By definition, if all sub activites at Next steps are completed, we present progress report.
This however does not mean that encounter can be ended. For that, we have 2 usecases: 
1. Emergency referral diagnosis was identified - all that is needed is to complete Next steps.
2. Emergency referral diagnosis was NOT identified - all activies need to be completed, besides Photos.


> Medical distribution still has no checkmark.

Fixed at [5d9c8e9](https://github.com/TIP-Global-Health/eheza-app/commit/5d9c8e9a4783179a805107042e1946a4719e1a9d)

**Comment by anvmn** [comment]
@balagan73 please test the fix on nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

As far as I remember, Fundal height was validated before. Now I can enter any value. The patient where this is happening, had several encounters.
![image](https://user-images.githubusercontent.com/3536805/180039638-65411bfb-a6bb-4015-be42-7a1c4d9252bd.png)

### Checked and approved:

1. Encounter can be ended when Candidiasis + Gonorrhea is diagnosed.
![1-can-end-now](https://user-images.githubusercontent.com/3536805/180040601-8a37d309-618c-4787-beeb-4e100b27db6b.png)

**Comment by anvmn** [comment]
@balagan73 

> As far as I remember, Fundal height was validated before. Now I can enter any value. The patient where this is happening, had several encounters.

There never was validation there. Almost all inputs do not get validated.
Rare exception is few fields on Create / Edit patient form.

//cc @jeanette-pelizzon

**Comment by balagan73** [comment]
@anvmn @jeanette-pelizzon This is what I meant by validation. I remember many times I had to try and guess the acceptable fundal height for a given EGA. I also recall there was some validation working for Fetal heart rate, when @adamhstewart first showed me how this app works, he forgot that a fetus's heart rate should be around double, and he had to changed that data.
![image](https://user-images.githubusercontent.com/3536805/180141491-ac39a900-640d-4e76-8a51-10327c1a7fbc.png)

**Comment by anvmn** [comment]
@balagan73 
Fundal height depends on EGA.
If EGA is set properly, APP calculates the ranges, and views the alert.
I tested this on nutrition env and it works well:


![Peek 2022-07-21 09-15](https://user-images.githubusercontent.com/17882245/180142977-0c23464b-450a-4352-abfd-65db6eb73e53.gif)

If you can reproduce, please mention patient name so I can take a look at it (and of course, make no other changes to that patient).

**Comment by jeanette-pelizzon** [comment]
Moved to acceptance but @balagan73 please see Anatoly's comment above. If there is still an issue please assign to the correct person and update project board.
