### ISSUE TITLE
ANC Logic - Diagnosis + Next Steps: Imminent Delivery [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#156]
## Issue 

When a patient meets the criteria for Imminent Delivery it will trigger the pop-up and immediately go to referral. The patient will not finish the encounter as this is an emergency situation.

Pop-Up | Referral 
--|--
<img width="312" alt="Screen Shot 2022-02-08 at 4 29 08 PM" src="https://user-images.githubusercontent.com/77505464/153079268-c960174b-4ae6-4e4a-8c9e-b8b5de5f2cd5.png"> | <img width="263" alt="Screen Shot 2022-02-07 at 6 29 29 PM" src="https://user-images.githubusercontent.com/77505464/152890431-a9c19827-bc1b-4a65-ab61-bb222ec7a948.png">

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma under [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) under the purple logic heading. 

## Note: 
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
 
## To Do: 

- Style next step screens per design 
- Adjust logic per document

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Question about the icon: so far, when referring to HC / Hospital / Program we were using this icon:

![Selection_496](https://user-images.githubusercontent.com/17882245/153841114-372b3bb2-29b3-48c4-a272-936fb2a0d951.png)

Here we get another one. Is this model speciall so that we get new icon?
Alternatively, maybe we should be showing this icon at other models?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> The patient will not finish the encounter as this is an emergency situation.

What should happen when nurse clicks on 'Save' button?

**Comment by jeanette-pelizzon** [comment]
(1) Great, we can continue using that icon here. I can update the designs this week to reflect that. 

(2) We need to figure this out. Ideally, if an emergency pops up and we refer a patient to the hospital without finishing the encounter, then E-heza would save where the patient left off in that encounters flow and pick back up at the next visit. We could have a pop-up at the beginning informing the user that it is the continuation of a visit. Unsure how tricky that would get clinically if the next they come to the HC requires different labs or if the EGA then changes a diagnosis... @adamhstewart  can probably help suss this out more.

**Comment by jeanette-pelizzon** [comment]
(2) updated: nurse refers patient to hospital, sees progress report, hits save --- this closes the encounter. If the patient returns we will do a new encounter for them

**Comment by adamhstewart** [comment]
## QA Analysis

## Works as designed

-  When "imminent delivery" is indicated, shows popup warning an diverts the flow to next steps.
