### ISSUE TITLE
ANC Logic - Case Management [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#159]
## Issue 

In our previous ANC sprint, we built out a Lab Results section in Case Management for nurses. This sprint we are adding in another level to the lab results so that nurses will also be able to see which patients need to come back to have their vitals rechecked to make a proper diagnosis.  These patients will still appear under the Lab Results tab in Case Management but their label will read "Vitals Recheck."

Along with that we are introducing an activities tray as the next screen that appears when a user clicks on a patient. This way they can put in both lab results and vitals without having duplicate case management entries. 

This is what the flow will look like: 
case management --> activities tray --> individual activity --> back to activities tray (if another activity exists) --> individual activity (if required) ---> next steps --> end encounter 

Case Management | Activities Tray
 --|--
<img width="314" alt="Screen Shot 2022-02-10 at 1 43 10 PM" src="https://user-images.githubusercontent.com/77505464/153475191-aea0ff26-236c-45ea-8875-0b714f62ae2b.png"> | <img width="314" alt="Screen Shot 2022-02-10 at 1 43 15 PM" src="https://user-images.githubusercontent.com/77505464/153475229-ef708fb2-bc0a-4c15-82c1-8c7d2f4f75ed.png">

## Note: 

- Design files can be found on [figma ](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=6960%3A59483) under the HC- ANC Labs page under Case Management heading.
- See issue #168 for more information re: infrastructure

## To Do: 
- Update label options to include "Vitals Recheck" 
- Style per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 
> Along with that we are introducing an activities tray as the next screen that appears when a user clicks on a patient. This way they can put in both lab results and vitals without having duplicate case management entries.

This is separate topic, which requires developing new page + logic to decide it activity was completed or not, and placing them them at correct tab. In short, very similart to page of an encounter. Estimation there is 6h.
Also, we will need to redesign current Lab results page - diferent routing to new page, based on available activities. That's another 2h. 
Please open a separate issue (one, with 2 sections).

**Comment by adamhstewart** [comment]
## QA Assessment

### Works as designed
- Updated label and style of vitals recheck
- Path to patient and workflow for vitals recheck

### Needs followup
- When completing the vitals recheck and the following next steps, the patient record is not displayed nor is there a button to close the encounter.

![image](https://user-images.githubusercontent.com/688507/160656614-5333c782-936b-4f32-b65b-70fb13eeeba1.png)

Design (after next steps):

![image](https://user-images.githubusercontent.com/688507/160656834-3680cc66-3d9e-4931-b305-9c6bb7e31921.png)

**Comment by adamhstewart** [comment]
@anvmn moving this over in favor of the workflow redesign in #203
