### ISSUE TITLE
ANC Logic - Medication Distribution activity infrastructure [4h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#160]
At different scenarios at ANC Logic nuse perscribes mediacation.
Medication Distribution activity will present prescription and store nurse inputs on backend.

**Comment by adamhstewart** [comment]
## QA Analysis

- medication distribution content set on the backend after activity:
![image](https://user-images.githubusercontent.com/688507/160679963-b8552dfe-3a6c-406d-8865-75289ab190df.png)
