### ISSUE TITLE
ANC Logic - record and store Prenatal Diagnosis [6h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#161]
Similar to Acute Illness and Nutrition, it's not only required to come up with diagnosis / assessment, and apply appropriate logic, but also to record and store the diagnosis, for presentation, and logical decisions at subsequent encounters.

//cc @jeanette-pelizzon @adamhstewart @isapisa

**Comment by adamhstewart** [comment]
## QA Analysis

### Works as designed
- Diagnosis are recorded on the prenatal encounter
![image](https://user-images.githubusercontent.com/688507/160666321-ef49c04e-1eb6-4473-8d11-ede932c9c3e1.png)
