### ISSUE TITLE
ANC Labs - HIV Updated [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#165]
## Issue 

As we went through ANC Logic for HIV ( #124 ) we discovered that we needed to make some significant updates to the HIV lab flow to gather further information to be able to properly treat the patient in the next steps. 

We have added questions to determine if the health center has a PMTCT/HIV program, if the patients partner is positive, if the partner is on ARV's, and if the partner has a suppressed viral load. 

Here is a quick [video overview](https://www.loom.com/share/ff555070cee840d68fbe182af7ae04d2) of the updated flow. 

## Note

- We now ask in several places if the patient's partner is HIV positive. There is a clinical reason for that and we need to keep all of those questions in the flow. 

## Supporting Documents 

You can find the updated HIV flow in Figma [here. ](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021)

## To Do: 

- Update the HIV Labs flow 
- Style screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

:+1: :+1: for video overview.
One question - what should be the flow if test result is Indeterminate?

**Comment by jeanette-pelizzon** [comment]
@anvmn those thumbs up really made my day.

Answer: if the HIV test comes back indeterminate, there will be no next steps and the HIV test should reappear at the next visit.

**Comment by anvmn** [comment]
@jeanette-pelizzon This does not makes sense to me.
Why would patient with negative result and negative partner get health education, and patient with indeterminate result not?
Also, what about patinet that is know as positive? We don't run a test for this case:

![Selection_543](https://user-images.githubusercontent.com/17882245/156148757-e90c676d-37ed-457e-9b0e-4f82f7722f8f.png)

Should we view health education, and what questions should be there?

**Comment by jeanette-pelizzon** [comment]
Good point. I would suggest we do the health education for indeterminate as well. I would assume the patients who are known to be HIV positive already know but health education probably would be good to have there as well. Let's add it for those options and see what the team thinks in testing. 

// @anvmn

**Comment by adamhstewart** [comment]
## QA Analysis
I'm assuming that this issue is just for the labs section and not for the next step logic (if so I'll revert)


### Works as designed
- Added "known to be positive" and skip logic.
- Added paternal questions (+ ARVs + viral load) and skip logic.

**Comment by jeanette-pelizzon** [comment]
@adamhstewart this issue is just labs related. It was created before the introduction of the more intense logic.
