### ISSUE TITLE
ANC Labs - Urine Dipstick - Protein Results Update [1h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#182]
## Issue

In the lab results portion for the Urine Dipstick test, the result options need to be changed per feedback from Wendy. 

Potential results should be: 

- 0
- +1 
- +2 
- +3 
- +4

## Notes: 
I have updated the [ANC Source of Truth](https://docs.google.com/spreadsheets/d/1kRfEJIF9nuRVbgicrB3R39LUNGiiGRw5v86FDQlrAjY/edit#gid=0) document to reflect this change.

**Comment by anvmn** [comment]
Need this for #139. Can't wait anymore with this.
Self assigning...

**Comment by adamhstewart** [comment]
## QA - Analysis
 - Change as requested
