### ISSUE TITLE
Deploy new version to production on Mar 27, 2022 [2h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#198]
Include:

#135 
#192
#197

**Comment by anvmn** [comment]
@adamhstewart ^^

**Comment by anvmn** [comment]
### Deployment instructions:

- Reinstall project locally, to get new contrib module.
- `drush updb`

**Comment by anvmn** [comment]
@adamhstewart 

Deployed to live. Let me know if we want to run the scripty that fixed the EDD (#192).

**Comment by adamhstewart** [comment]
@anvmn let's please do.

**Comment by adamhstewart** [comment]
@anvmn this doesn't cover #133 ?

**Comment by anvmn** [comment]
@adamhstewart 

Yes,  #135 is PR for #133.

Script executed:
![Selection_602](https://user-images.githubusercontent.com/17882245/160450020-97f23908-23e7-4df5-98b0-135da8fbd20d.png)

**Comment by anvmn** [comment]
@adamhstewart This issue is done. Closing.
