### ISSUE TITLE
Assemble the Activities of a Subsequent Visit [12h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#201]
## Issue 

Subsequent visits which were seen previously at the health center have the following activities:
- Danger Signs
- Physical Exam
- Treatment Review

![image](https://user-images.githubusercontent.com/688507/160502848-f4497e80-7f2b-48b3-86a1-a5450ec43c45.png)

- The sub activities for "prior treatment history" and "physical exam" and workflows are the same as they are for an initial visit
- The sub activities for "danger signs" are the same as they are for a CHW.

## Tasks
- Create each of the activities and the workflows.

**Comment by anvmn** [comment]
@adamhstewart 

So, we just fill the activities and end encounter?
No Next steps?

**Comment by adamhstewart** [comment]
No we should already have next step logic from anc health center functionality.

**Comment by anvmn** [comment]
@adamhstewart 
Next steps derrive from activites completed at current encounter.
So, it's not clear to me what should this be.

**Comment by anvmn** [comment]
@adamhstewart 
Do you mean that it should be same Next steps as we have at subsequent encounter for CHW?

**Comment by anvmn** [comment]
If ^^ is correct, I think we said that instead of sending to Health Center, we'll be sending to Hospital.
However, we also have 'Contact HC' subactivity for patients with Covid diagnosis, that are not improving.
Also, should nurse be scheduling follow up and providing health education?

**Comment by anvmn** [comment]
@adamhstewart 

We have Treatment Review and Prior treatment history mentioned at requirements:

![Selection_646](https://user-images.githubusercontent.com/17882245/162638233-42889142-70fc-4a71-acb6-3561885c7fc3.png)

Prior treatment history is an activity that appears on first encounter both for Nurse and CHW.
Treatment Review is an activity that is viewed on subsequent encounter (CHW only), in case medication was prescribed during illness.

Which one do we need here?

**Comment by anvmn** [comment]
@adamhstewart 

> we also have 'Contact HC' subactivity for patients with Covid diagnosis, that are not improving.

As we discussed at ctach up meeting, I made a check if there's an option to get to this path at nurse subsequent encounter.

If we have a COVID suspect, and nurse indicates that test was not performed, (and Malaria test that we give after is negative) we consider this case as Covid positive.
Also, encounter is not closed automatically, meaning that answers to questions will need to be provided.

Therefore, I don't see a way to get to subsequent encounter for nurse with 'Covid suspect' diagnosis.

**Comment by anvmn** [comment]
@adamhstewart deployed to Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Not sure how to proceed. As far as I can see, Danger signs and Physical exam is working correctly for a nurse.
![2-review-danger-signs](https://user-images.githubusercontent.com/3536805/169539902-801d5acb-5cd7-4f6d-a8e0-a0a563251318.png)
![3-physical-exam](https://user-images.githubusercontent.com/3536805/169539922-f527e6d4-1847-4a17-9195-1c3728132263.png)


### Checked and approved:

1. The Treatment review doesn't appear for user with Nurse role, but the Danger signs and Physical exam options do display.
![1-treatment-review](https://user-images.githubusercontent.com/3536805/169537819-fc85f631-5705-4e1e-9e7f-0818a4cb88e6.png)
