### ISSUE TITLE
ANC Logic - HIV Next Steps Update - Discordant Partners [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#206]
## Issue 

The wording on one of the next steps screen in the HIV flow needs to be updated. The screen is the medication screen for a discordant partnership where the partner is not on ARVs. 

**This is the situation:** 
Patient HIV = Negative 
Partner = Positive 
Partner ARVs = No 

**This is the new screen:** 
<img width="337" alt="Screen Shot 2022-04-05 at 12 49 31 PM" src="https://user-images.githubusercontent.com/77505464/161817446-f802c287-a908-4ee6-b92b-97099b89790b.png">

## To Do: 
- Update the wording on the medication distribution screen to match the screenshot above.

**Comment by jeanette-pelizzon** [comment]
Assigned to @Diama1 but tagged @anvmn so you are in the loop.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

This requirement is somewhat problematic, because medication disatribution is a combined form, that presents all medications that should to be perscribed. For example - HIV ARVs + Mebendazole:

![Selection_635](https://user-images.githubusercontent.com/17882245/161975469-3e01cd8c-bee6-4b7d-9e56-f8e101787e99.png)

So, it's not really clear what should the wording be.
Right now there's none. We do show diagnoses in popup, when Next steps activity is opened.
If this is not enough, we need to define the wording when there're medications for several diagnoses.


//cc @adamhstewart

**Comment by jeanette-pelizzon** [comment]
Ah, okay. When I designed it I thought it would stack like this: 
<img width="272" alt="Screen Shot 2022-04-06 at 2 25 44 PM" src="https://user-images.githubusercontent.com/77505464/162043157-2ab4f1db-cd65-4697-93f0-0b3b42984a6b.png">

Then a nurse could run through the medication and have a conversation such as " Since you are in a discordant partnership and your partner is not on ARVs, I am prescribing you XXXXX and this is when and how you should take it. Since you have not had a dewormer in the last 6 months, I am prescribing you XXXXXX and this is when and how you should take it." 

Would it be possible to do it like this ^ 

// @anvmn @adamhstewart

**Comment by anvmn** [comment]
@jeanette-pelizzon 

It is not a trivial change, but it is possible.

**Comment by anvmn** [comment]
@jeanette-pelizzon 
However, for every diagnosis treated with medicine, we need to have that text defined.

**Comment by jeanette-pelizzon** [comment]
Can we discuss in our Monday meeting? We can figure out what option would be best.

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Well, I think what you suggest at the design is great.
Other option as I see it not to give any wording for any medicine, which I would not vote for.
Do you have in mind another option?

**Comment by jeanette-pelizzon** [comment]
No, that's my only idea there. So let's keep the wording. I will go through and make sure they all have correct wording. (they should already but let me double check) @anvmn

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Wording on the Medication distribution panel matches the one specified in issue description.

Precondition|Medication distribution
-|-
![1-partner-no-arv](https://user-images.githubusercontent.com/3536805/175482821-14554873-985f-4baf-9326-e6e8a60e9e4e.png)|![2-updated-meds](https://user-images.githubusercontent.com/3536805/175482840-5676d942-dd30-44ea-86c4-ad15d5d4a2aa.png)
