### ISSUE TITLE
ANC Logic - HIV Next Steps - HIV Positive Medication Update [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#210]
## Issue 

We received feedback that the medication we are currently prescribing for HIV positive pregnant women is incorrect. The correct prescription is: 

<img width="253" alt="Screen Shot 2022-04-06 at 4 38 20 PM" src="https://user-images.githubusercontent.com/77505464/162066653-6f2d0b61-efe9-4060-9c13-500917fb8c8c.png">
 
## To Do: 

- update the medication distribution 
- update the follow up questions

**Comment by anvmn** [comment]
@jeanette-pelizzon 
So, Tenofovir and Lamivudine are not required anymore?

**Comment by jeanette-pelizzon** [comment]
Correct, Just the combination pill and the dolutegravir. 

// @anvmn

**Comment by anvmn** [comment]
@adamhstewart Implemeted at #209

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. HIV medications and followup questions match those in issue description.
![1-meds](https://user-images.githubusercontent.com/3536805/175482015-91ae0442-d018-4817-9505-429a86d0f3b1.png)
