### ISSUE TITLE
Wording Fix: Hemoglobin Spelling [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#221]
## Issue
There are two places in the app where the spelling of Hemoglobin is different. Apparently, there are two ways to spell it but for consistency the team would like it to be "Hemoglobin" throughout the app. 

## To Do
"Haemoglobin" needs to be changed to "Hemoglobin" on the Progress Report in the Labs Section and in the Long Urine Dipstick Results Input section.

**Comment by Diama1** [comment]
@jeanette-pelizzon Since I am working on Translations can I combine this issue with the translations issue #196

**Comment by anvmn** [comment]
@Diama1 

No you can not. This fix should come on top on ANC Logic branch.
By the way, there should be an issue for translation of ANC Logic feature as well.

**Comment by Diama1** [comment]
> @Diama1
> 
> No you can not. This fix should come on top on ANC Logic branch. By the way, there should be an issue for translation of ANC Logic feature as well.

oh Thank you let me do it like that
