### ISSUE TITLE
ANC Logic - Hep B + HIV - Known Positive [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#222]
## Issue 

In the ANC labs section, we ask if the patient is known positive under the HIV RDT activity + the Hep B activity. If a patient is known positive, it currently leaves the lab results section blank and isn't updating anywhere else on the progress report. Both CHW's and Nurses, need to see on the progress report if a patient is known positive for either of these. 

If a patient is known positive for HIV or Hep B, the progress report should update with a label that says "Known Positive" next to the appropriate test. Here is an example: 

<img width="671" alt="Screen Shot 2022-04-25 at 12 12 50 PM" src="https://user-images.githubusercontent.com/77505464/165136724-be35f8c1-fbcc-477b-8b2f-0faa03ab26f9.png">

If a patient is known positive for HIV or Hep B, the progress report should also update with this information in the Medical Diagnosis section. Here is an example: 

<img width="419" alt="Screen Shot 2022-04-25 at 1 03 17 PM" src="https://user-images.githubusercontent.com/77505464/165138092-97cfa0d9-494a-4cb6-a761-da18bab594ff.png">

## To Do: 
- Create "Known Positive" label
- Update logic for Hep B Known Positive to populate the "Known Positive" label in the progress report. 
- Update logic for HIV Known Positive to populate the "Known Positive" label in the progress report. 
- Update logic for Hep B Known Positive to populate under the Medical Diagnosis 
- Update logic for HIV Known Positive to populate under the Medical Diagnosis

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Both HIV and Hepatitis B known positive displays on the Progress report Medical diagnosis and Lab results sections.

HIV|Hepa B
-|-
![1-hiv-rdt](https://user-images.githubusercontent.com/3536805/177162990-96951323-a828-4a6e-b776-51018248750b.png)|![2-hepab](https://user-images.githubusercontent.com/3536805/177162992-1515bf62-8173-4b01-b30a-19034f5f43d5.png)


Medical diagnosis|Lab results
-|-
![3-medical-diagnosis](https://user-images.githubusercontent.com/3536805/177162926-ea248ff2-cbee-4208-8005-a174bbf4946f.png)|![4-lab-results](https://user-images.githubusercontent.com/3536805/177162934-2b6c8671-7212-415c-9f3c-c7ba2dcc0f3d.png)
