### ISSUE TITLE
ANC Logic - Translations for Anc Logic

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#224]
## Issue
Adding translations for ANC Logic feature

## Tasks
- List texts that need translations
- Add translations in the app

**Comment by anvmn** [comment]
@Diama1 

After merging #225, I still see several places where translation is missing at `Translate.elm` of #157.
For example:
![Selection_750](https://user-images.githubusercontent.com/17882245/168763043-5eb07dbd-95d8-4b8d-9db5-0f8323d6354d.png)

Please complete all translations, or comment, if translation is not needed (medication name, for example).

**Comment by Diama1** [comment]
> @Diama1
> 
> After merging #225, I still see several places where translation is missing at `Translate.elm` of #157. For example: ![Selection_750](https://user-images.githubusercontent.com/17882245/168763043-5eb07dbd-95d8-4b8d-9db5-0f8323d6354d.png)
> 
> Please complete all translations, or comment, if translation is not needed (medication name, for example).

I might have missed it but I am going to put it.

**Comment by adamhstewart** [comment]
@Diama1 are these translations complete?

**Comment by Diama1** [comment]
> @Diama1 are these translations complete?

This one is done
