### ISSUE TITLE
ANC Subs Visit - Add Activity - Symptom Review [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#227]
## Issue

Building upon the existing subsequent encounter activities for ANC @ Health Centers, we will be adding a Symptom Review Activity. 

The Symptom Review activity should appear 2nd in the tray, after Danger Signs. 

Individual Icon: 
![Symptom Review](https://user-images.githubusercontent.com/77505464/165367671-1da4dfba-f0ba-44a0-a8c0-a48ac382c358.jpg)

Tray View: 
<img width="301" alt="Screen Shot 2022-04-26 at 2 26 21 PM" src="https://user-images.githubusercontent.com/77505464/165367700-53dd3767-f5bc-4130-9498-c46001fd1b8b.png">

## Design Files: 
You can access the icon SVG [here. ](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=207%3A442)

## Related Issues: 
- #228 
- #229 

## To Do: 
- Build out architecture for the Symptom Review Activity.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Coming after Danger signs the Symptom review icon is the second.
![1-symptom-review](https://user-images.githubusercontent.com/3536805/177146224-176184db-6fba-4a30-9dd7-9f6ab151edd7.png)
