### ISSUE TITLE
ANC Subs Visit - Symptom Review - Add Symptoms [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#228]
## Issue 

In order to diagnose and address some common issues in pregnancy, we have added the new symptom review activity.

Here is the complete list of symptoms that should appear in a checklist: 

- Burning with Urination 
- Abnormal Vaginal Discharge
- Nausea + Vomiting
- Heartburn 
- Leg Cramps 
- Low Back Pain 
- Cough for > 3 weeks
- Pelvic Pain 
- Constipation
- Varicose Veins 
- Leg Pain (One Leg)
- Leg Redness (One Leg)
- None of these 

Here is a view of the screen: 
<img width="429" alt="Screen Shot 2022-04-26 at 2 58 24 PM" src="https://user-images.githubusercontent.com/77505464/165372610-7f20bf45-fb7f-4609-a70e-f835d3309bc9.png">

##Design Files: 
Can be found in figma in the ANC Health Center file under the Subsequent Visit flow [here. ](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021)

## Related Issues: 
#227 
#229 
#230

## Notes: 
- There will be follow up questions that will be added in if specific symptoms are selected (See related issues). 
- There will also be specific next steps related to certain symptoms and follow up questions. You can view the logic[ here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493). 
- In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 

## To Do: 
- Create checklist of symptoms

**Comment by jeanette-pelizzon** [comment]
We have updated Leg Pain and Leg Redness into one option now. 

Here is the new screen. I have highlighted the change with a red box. The red box is NOT part of the design. 

<img width="410" alt="Screen Shot 2022-05-03 at 11 34 54 AM" src="https://user-images.githubusercontent.com/77505464/166486094-3c7991f0-28ce-4cd5-b2ee-327e4f40392a.png">


// @anvmn

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. I have noted it here https://github.com/TIP-Global-Health/eheza-app/issues/234 but it belongs here:
We are talking about Lower back pain, but symptom says 'Low back pain'. Is that OK?

### Checked and approved:

1. Symptom review page contains all the checkboxes mentioned in the issue description.
![1-symptoms](https://user-images.githubusercontent.com/3536805/177145262-03625942-303e-401b-8f11-56309ca2c6d0.png)

**Comment by anvmn** [comment]
@jeanette-pelizzon @balagan73 

> We are talking about Lower back pain, but symptom says 'Low back pain'. Is that OK?

No, not ok. Will be fixed.

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Low back pain is changed to Lower back pain.
![2-lower-back-pain](https://user-images.githubusercontent.com/3536805/178764944-a0b5332c-d27e-4e1a-8987-28018bf95859.png)
