### ISSUE TITLE
ANC Subs Visit - Symptom Review Follow Up Questions [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#229]
## Issue 

Certain symptoms in the symptom review will require follow-up questions which will later determine the diagnosis. If these symptoms are selected in the first screen, the appropriate follow-up questions will appear. 

First, a user will select the symptoms the patient is experiencing. Then they will press save. Next, a screen populates with the follow-up questions for the selected symptoms. If more than one symptom requiring a follow-up question is selected, then the corresponding questions will all populate on one screen. The answers to these questions will then inform diagnoses in the next steps section. 

Note: Not all symptoms have follow-up questions. 

Here are the symptoms with follow-up questions and their corresponding questions.
 
Nausea + Vomiting | Pelvic Pain (added onto N+V as an example of stacking | Leg Pain 
--|--|-- 
<img width="429" alt="Screen Shot 2022-04-26 at 2 58 24 PM" src="https://user-images.githubusercontent.com/77505464/165378147-5175323e-3657-4744-b988-657ae1b50af9.png"> | <img width="257" alt="Screen Shot 2022-04-26 at 3 34 05 PM" src="https://user-images.githubusercontent.com/77505464/165378167-56524f6f-240f-44cc-9bea-479b176616b5.png"> | <img width="258" alt="Screen Shot 2022-04-26 at 3 34 10 PM" src="https://user-images.githubusercontent.com/77505464/165378201-8a83ba0c-7a84-4e92-a186-221f04fd0a25.png">

Leg Redness | >3 Week Cough  
--|--
<img width="336" alt="Screen Shot 2022-05-02 at 1 15 23 PM" src="https://user-images.githubusercontent.com/77505464/166293676-48d747d1-6310-4bdc-9894-b98f1ce1c1e7.png"> |<img width="307" alt="Screen Shot 2022-04-26 at 3 36 17 PM" src="https://user-images.githubusercontent.com/77505464/165378644-c3b081c8-dbe0-44a7-a62f-fe7fd92b69ba.png">

Burning on Urination | Vaginal Discharge 
--|--
 <img width="307" alt="Screen Shot 2022-04-26 at 3 36 23 PM" src="https://user-images.githubusercontent.com/77505464/165378671-e8ea8f8f-ea08-49f8-805b-b032fd05a9f7.png"> | <img width="332" alt="Screen Shot 2022-05-02 at 1 14 32 PM" src="https://user-images.githubusercontent.com/77505464/166293517-5d3cb9b5-25d7-425c-a0a0-a0a975f38c3e.png">

## Design Files: 

You can see the full flow in the Subsequent Visit section in the ANC Health Center file on figma [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021) 

## To Do: 
- Create logic for follow-up questions to populate 
- Ensure follow-up questions stack

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> First, a user will select the symptoms the patient is experiencing. Then they will press save. Next, a screen populates with the follow-up questions for the selected symptoms.

This division to 2 screens is technically complex, and may not be necessary.
If we insist on it, there should be an option of going back to first screen to edit the symptoms.
I suggets to make follow up questions dynamic, so, when symptom is selected,
it's questions appear on the bottom.

//cc @adamhstewart

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Leg pain and leg redness, got similar questions (at discription it's same screenshot which is a mistake, but even at Figma we have similar ones).
Can you please make a design when these 2 are stacked together?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

![image](https://user-images.githubusercontent.com/17882245/166199952-704e0c40-8f89-408b-8e3b-2747ec91fd7e.png)

Making this dynamic is overcomplicating things. We can have 4 checkboxes with options: No, left, right, both.
Similar to:
![Selection_714](https://user-images.githubusercontent.com/17882245/166200327-316eca44-64e6-44ae-b297-db9ddc4bf60e.png)

**Comment by jeanette-pelizzon** [comment]
> @jeanette-pelizzon Leg pain and leg redness, got similar questions (at discription it's same screenshot which is a mistake, but even at Figma we have similar ones). Can you please make a design when these 2 are stacked together?

They are the same questions. A patient may not have both leg redness and leg pain. They are asked the follow-up questions to determine if they have a more severe issue. If they have both leg pain and leg redness can we create some logic that they only get asked the follow-up questions once?

**Comment by jeanette-pelizzon** [comment]
> ![image](https://user-images.githubusercontent.com/17882245/166199952-704e0c40-8f89-408b-8e3b-2747ec91fd7e.png)
> 
> Making this dynamic is overcomplicating things. We can have 4 checkboxes with options: No, left, right, both. Similar to: ![Selection_714](https://user-images.githubusercontent.com/17882245/166200327-316eca44-64e6-44ae-b297-db9ddc4bf60e.png)

Okay, updated the design: 
<img width="259" alt="Screen Shot 2022-05-02 at 1 17 29 PM" src="https://user-images.githubusercontent.com/77505464/166293948-bbc62f38-0c54-4f35-ab45-f978c6ea38c9.png">

**Comment by jeanette-pelizzon** [comment]
We have combined leg pain and leg redness into one symptom called "Leg pain or redness." Here is the new combined follow up screen/questions.

<img width="382" alt="Screen Shot 2022-05-03 at 11 37 19 AM" src="https://user-images.githubusercontent.com/77505464/166486721-7e394d6d-99ac-408d-bc9e-48df9ce299d4.png">
 for this symptom

// @anvmn

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Follow-up questions are correct.

Nausea + Vomiting | Pelvic Pain | Leg Pain 
-|-|-
![1-nausea](https://user-images.githubusercontent.com/3536805/177148329-0a1d5cd1-e259-4736-878c-844e48eb3dbd.png)|![2-pelvic-pain](https://user-images.githubusercontent.com/3536805/177148341-d4c64cab-1b51-4957-91f9-bfe64a1a9eb7.png)|![3-leg-pain](https://user-images.githubusercontent.com/3536805/177148343-20a92703-4cb8-4691-8be5-65534ec6a0eb.png)


 more than 3 weeks Cough |Burning on Urination | Vaginal Discharge 
-|-|-
![4-cough](https://user-images.githubusercontent.com/3536805/177148552-964b9c22-7ca8-4036-bab6-6dfc0bf55255.png)|![5-burning-urination](https://user-images.githubusercontent.com/3536805/177148556-c5986613-8c12-4555-b447-187a55819e8d.png)|![6-vaginal-discharge](https://user-images.githubusercontent.com/3536805/177148559-d9bbbacf-4a9a-4d54-be6c-fbb46057a4d5.png)
