### ISSUE TITLE
ANC Subs Visit - Next Steps - Nausea + Vomiting [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#230]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 

When a patient identifies that they have nausea + vomiting as a symptom for the FIRST TIME  and answer no to all the follow-up questions, they will not see a diagnosis pop-up but they will receive health education to reduce the symptoms.  

**Yes to Nausea/Vomiting + NO to Follow-Up Questions = health education + NO pop-up diagnosis** 

You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

<img width="250" alt="Screen Shot 2022-05-03 at 1 25 35 PM" src="https://user-images.githubusercontent.com/77505464/166506453-b9b6cc7f-0c98-4766-80b8-57a362b87f5b.png">

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity. 

## To Do:  
- Style next steps screen per design 
- Adjust logic per document

**Comment by jeanette-pelizzon** [comment]
updated the health education screen to include the question and fit the style of other health education screens for stacking: 
<img width="250" alt="Screen Shot 2022-05-03 at 1 25 35 PM" src="https://user-images.githubusercontent.com/77505464/166506453-b9b6cc7f-0c98-4766-80b8-57a362b87f5b.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Please update screenshot at issue description.
We need to see complete requirements there.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. There is a typo in the title of the Health education panel. It should be Nausea
![3-typo](https://user-images.githubusercontent.com/3536805/177120010-07c87ceb-18b4-40a8-adcb-1c57a299de37.png)

### Checked and approved:

1. When the symptoms are Nausea and vomiting, and all answers to follow-up questions are no, there is no warning and only health education is offered.

Nausea and vomiting|Follow up questions|Health education
-|-|-
![1-nausea](https://user-images.githubusercontent.com/3536805/177120158-c2068158-e0f5-4b91-986c-7d4b9b63dfb4.png)|![4-follow-up](https://user-images.githubusercontent.com/3536805/177120505-93189e4e-3560-4c7d-a585-cf666ae0e4cb.png)|![2-health-edu](https://user-images.githubusercontent.com/3536805/177120164-07482dab-55ef-4302-9802-34eead4f597a.png)

2. In subsequent visits when Nausea and Vomiting is given as symptom, and no is given as an answer to all follow-up questions, then no health education is offered these symptoms.

Symptoms|No next steps
-|-
![5-symptoms-subsequent](https://user-images.githubusercontent.com/3536805/177124769-61565b9f-1826-47ea-ac3b-e2ca5021991d.png)|![6-no-next-steps](https://user-images.githubusercontent.com/3536805/177124776-6421d603-3475-4fcd-8b66-df44487dd9f1.png)

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Typo is fixed.
![image](https://user-images.githubusercontent.com/3536805/180732755-0aac0044-3f3f-454e-b498-259c8d2d59d4.png)
