### ISSUE TITLE
ANC Subs Visit - Next Steps - Hyperemesis Gravidum (Dehydration) [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#231]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. In the case of Hyperemesis Gravidum, we also diagnose it from a danger sign. 

Here are the three different ways Hyperemesis Gravidum can be diagnosed.

(1) Any Encounter -> Danger Sign = Severe Vomiting --> _INTERRUPT FLOW_ Assume Hyperemesis Gravidum and send to hospital

(2) Any Encounter -> Symptom Review = Nausea + Vomiting PLUS a yes to any follow up question --> In next steps, assume Hyperemesis Gravidum and send to hospital

(3) Any Encounter -> Symptom Review = Nausea + Vomiting PLUS they have already had this symptom in a previous encounter --> in next steps, assume hyperemesis Gravidum and send to hospital.

You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

This is in addition to the already existing logic for Hypermesis Gravidum. The pop-up screen and next steps will be the same as in the initial encounter. 

## To Do:  
- Adjust logic per document

**Comment by anvmn** [comment]
@jeanette-pelizzon 

We already have this diagnosis for initial encounter. Triggered by `Severe Vomiting` at danger signs.
It's an emergency referral diagnosis, and I believe that here it is as well.

The popup we show is:
![Selection_725](https://user-images.githubusercontent.com/17882245/167293694-bafd630c-4f2d-48c9-ba16-dbb0877eec3f.png)

Do we need to show popup with different instructions for subsequent encounter?

**Comment by jeanette-pelizzon** [comment]
> @jeanette-pelizzon
> 
> We already have this diagnosis for initial encounter. Triggered by `Severe Vomiting` at danger signs. It's an emergency referral diagnosis, and I believe that here it is as well.
>
> 
> Do we need to show popup with different instructions for subsequent encounter?

Good catch, the pop-up/flow can be the same as it was initially. We just need to add in the logic for the new trigger. But next steps and everything else can be the same. Ill update the main issue here.

**Comment by jeanette-pelizzon** [comment]
@anvmn spoke to Wendy about this since there are now several ways to trigger this diagnosis. 

(1) Any Encounter ->   Danger Sign = Severe Vomiting --> INTERRUPT FLOW Assume Hyperemesis Gravidum and send to hospital 

(2) Any Encounter -> Symptom Review = Nausea + Vomiting PLUS a yes to any follow up question --> In next steps, assume Hyperemesis Gravidum and send to hospital 

(3) Any Encounter ->  Symptom Review = Nausea + Vomiting PLUS they have already had this symptom in a previous encounter --> in next steps, assume hyperemesis Gravidum and send to hospital. 

I will update the logic document to reflect these changes and the primary issue here. 

// @adamhstewart

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. When in Symptom Review Nausea and Vomiting + yes is given to any follow-up questions, no Next steps display.

Follow-up questions|Result
-|-
![2-follow-up-yes](https://user-images.githubusercontent.com/3536805/177181747-d7ffeb62-1b8a-406d-bd72-00866e437714.png)|![3-no-next-steps](https://user-images.githubusercontent.com/3536805/177181823-9a19f304-966c-4be8-824b-a499dc356d60.png)

2. When I enter Nausea and vomiting the second time under Symptom review (with No to follow up questions), no Next steps display.

### Checked and approved:

1. When Severe vomiting is selected under Danger signs, the warning displays and patient is referred to hospital.
![1-vomiting](https://user-images.githubusercontent.com/3536805/177183002-8b70dc04-15cd-4bfe-9722-2f4272a715e4.png)
![4-hospital](https://user-images.githubusercontent.com/3536805/177183076-bb1cd19f-a640-4162-a4e9-f05d96acc264.png)

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Still no Next steps icon displays for both entering Nausea and vomiting twice with 'No' answers to follow-up questions, or once with 'Yes' answer. 

![image](https://user-images.githubusercontent.com/3536805/180734873-c92ba0e8-c595-4a4e-8bbc-a3cf4f4953ad.png)
