### ISSUE TITLE
ANC Subs Visit - Next Steps - Heartburn [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#232]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 

**First Time**
When a patient identifies that they have heartburn a symptom for the FIRST TIME, we provide health education and medication 
Pop-Up | Health Education | Medication
--|--|-- 
<img width="301" alt="Screen Shot 2022-04-26 at 4 20 44 PM" src="https://user-images.githubusercontent.com/77505464/165385373-a974179e-f532-48d5-a0d4-b0777cd509ab.png"> | <img width="299" alt="Screen Shot 2022-04-26 at 4 20 52 PM" src="https://user-images.githubusercontent.com/77505464/165385375-33654e0a-78fe-46c2-888e-34ff8e0de645.png"> | <img width="301" alt="Screen Shot 2022-04-26 at 4 20 58 PM" src="https://user-images.githubusercontent.com/77505464/165385376-5901905a-f166-49cd-a13a-1e600ecf7406.png">

**Second Time** 
When a patient identifies that they have heartburn a symptom in a second visit, we refer to the hospital. 

Pop-Up | Referral 
--|-- 
<img width="330" alt="Screen Shot 2022-04-26 at 4 21 49 PM" src="https://user-images.githubusercontent.com/77505464/165385529-350dc232-540d-407b-a364-9a5e22941083.png"> | <img width="333" alt="Screen Shot 2022-04-26 at 4 21 58 PM" src="https://user-images.githubusercontent.com/77505464/165385530-edb43de1-ed8d-445c-89ce-ce399cf34557.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity. If they are being referred to the hospital for multiple things, there is only one referral screen. 

## To Do:  
- Style next steps screens per design 
- Adjust logic per document 
- Develop logic to decide which flow to follow
- Create popup for both flows
- Add new medication option + style form
- Add new health education option + style form

**Comment by jeanette-pelizzon** [comment]
updated the health education screen so that it includes the question: 

<img width="296" alt="Screen Shot 2022-05-03 at 12 28 07 PM" src="https://user-images.githubusercontent.com/77505464/166496975-dc66bc70-c62f-4a6f-83cb-537e7e90e873.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

This issue is underestimated.
We need to:
 - Develop logic to decide which flow to follow
 - Create popup for both flows 
 - Add new medication option + style form
 - Add new health education option + style form

Please bump to 4h in total.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

About the popups, and navigation after diagnosis is made.
We need to remeber that we have logic and styling developend for initial encounter, and it has to be same at subsequent encounter.
For example, if we do not diagnose Malaria on initial encounter, and we do on subsequent, we view notifications on this exactly as we would on initial encounter.

Flow 1, where we provide health edication and medication will be treated similar to 'non urgent' cases, where we show all diagnoses stacked when navigating to Next Steps. It will not have following instructions:
![Selection_726](https://user-images.githubusercontent.com/17882245/167356053-4dcb3cc2-fc9c-46d5-91c7-eff774476474.png)

Flow 2, where we refer to hospital, will be treated as an urgent case.
Meaning that it wil break the flow, and after Referral activity is completed encounter will end.

**Comment by jeanette-pelizzon** [comment]
> @jeanette-pelizzon
> 
> This issue is underestimated. We need to:
> 
> * Develop logic to decide which flow to follow
> * Create popup for both flows
> * Add new medication option + style form
> * Add new health education option + style form
> 
> Please bump to 4h in total.

Updated the to-do section in the main issue and bumped the time up

**Comment by jeanette-pelizzon** [comment]
> r example, if we do not diagnose Malaria on initial encounter, and we do on subsequent, we view notifications on this exactly as we would on initial encounter.

Alright. Just keep the first part with the diagnosis then and we can remove the second bit.

**Comment by anvmn** [comment]
@jeanette-pelizzon

Something I saw at logic that is not part of description:

![Selection_727](https://user-images.githubusercontent.com/17882245/167478133-9d991631-db9d-4c18-9ba9-6224a5af7291.png)

Do we need to have this implemented?

**Comment by jeanette-pelizzon** [comment]
@anvmn ah yes this was added in after some conversation. If a patient goes on medicine and 8 days later still has symptoms then we refer to hospital.

**Comment by anvmn** [comment]
@jeanette-pelizzon 
What if patient does not take medication, or takes it, but 8 days have not passed yet?

**Comment by jeanette-pelizzon** [comment]
@anvmn alright so I asked today to Wendy and Valens and this has switched. We are taking out the 8 days of medicine stipulation. To track this the way we would need to we would then have to create an entire new encounter type so we are tabling that for now. I have updated the logic document.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Question mark on the symptom review page is not needed.
![1-question-mark](https://user-images.githubusercontent.com/3536805/176385054-8fb8f9de-07f6-4e8b-b6eb-584e930b09ae.png)

2. At second encounter (that's the first time when Symptom review page displays) when I mark Heartburn as a symptom, no Medication distribution displays under Next steps, and Health education doesn't include heartburn. (I filled out already existing next steps before filling out the symptom review page.)

3. Typos on the Medication distribution page.
![6-typos](https://user-images.githubusercontent.com/3536805/176389002-14380c2a-f35e-472f-989b-ed3e875ed221.png)

4. Dosage (500mg) is missing on the Medication distribution page.
![7-dosage](https://user-images.githubusercontent.com/3536805/176389170-ba347135-4db0-4172-b333-1339836a52ce.png)

5. Symptom review page states: 'The patient has noted symptoms that require follow up questions:'. This displays even when everything was fine with patient at first encounter. I think this was meant to be displayed only on the second page of Treatment review:
![10-follow-up](https://user-images.githubusercontent.com/3536805/176398296-26008a9d-95b7-40cc-bafd-920506d052e9.png)

6. Displaying the Treatment review page only at the second encounter makes some diseases not possible to be diagnosed at first encounter (like candidiasis, heartburn). Can't we just show a Symptoms page at each encounter? I think this would increase usability of the app a great deal.

### Checked and approved:

1. In the third encounter (when Symptom review displayed 2nd time), the Warning displayed, even when I filled out the next steps page before filling out symptom review, so probably that was not the cause of the warning not displaying previously.
![5-medical-distribution](https://user-images.githubusercontent.com/3536805/176389414-7ee83f29-59af-4c65-9a50-6164a5051076.png)

2. At fourth encounter (third display of Symptom review page) the patient is referred to the hospital in Next steps, if they still have heartburn.

Warning|Hospital referral
-|-
![8-not-responding-warning](https://user-images.githubusercontent.com/3536805/176392152-69cd3e1a-9b07-4699-8b02-4f2bda9d8cf0.png)|![9-hospital-referral](https://user-images.githubusercontent.com/3536805/176392247-cfe7db8c-1826-46eb-93fa-9cc6e64d981a.png)

**Comment by anvmn** [comment]
@balagan73 

> At second encounter (that's the first time when Symptom review page displays) when I mark Heartburn as a symptom, no Medication distribution displays under Next steps, and Health education doesn't include heartburn. (I filled out already existing next steps before filling out the symptom review page.)

This may be cause by a bug we fixed already. Please retest this after new version is deployed.

> Symptom review page states: 'The patient has noted symptoms that require follow up questions:'. This displays even when everything was fine with patient at first encounter. I think this was meant to be displayed only on the second page of Treatment review:

This is second step, after you select symptoms on first step. It's not related to previous encounter.
If you think this is a problem, please decribe steps to reproduce.

> Displaying the Symptoms review page only at the second encounter makes some diseases not possible to be diagnosed at first encounter (like candidiasis, heartburn). Can't we just show a Symptoms page at each encounter? I think this would increase usability of the app a great deal.

This is what customer has requested. There may be good clinical reason to check for symptoms only at second encounter. @jeanette-pelizzon can you confirm please?

**Comment by jeanette-pelizzon** [comment]
1. We can remove the question mark

2. Heartburn this is what should be happening: 
<img width="1235" alt="Screen Shot 2022-07-06 at 8 36 00 AM" src="https://user-images.githubusercontent.com/77505464/177562963-99a7c380-5fe6-45fa-99fa-ab1eb2df5bc1.png">

3 + 4. Typos are an easy fix. This is what that screen should look like: 
<img width="292" alt="Screen Shot 2022-07-06 at 8 37 44 AM" src="https://user-images.githubusercontent.com/77505464/177564340-4d846d66-1789-448b-8693-ed1a0debe4a6.png">

5. Agree with Anatoly, it's directly related to the page before not a previous encounter. If they have a symptom in the symptom review activity on this specific encounter then the follow-up questions will populate. 

6. I honestly cannot remember why we have the symptom review only in subsequent encounters. I will check today during my call and get back to you both as soon as I have an answer. 


// @anvmn @balagan73

**Comment by anvmn** [comment]
@jeanette-pelizzon do we have an answer for point 6?

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
### Checked and approved:

1. Question mark is replaced by colon:
![image](https://user-images.githubusercontent.com/3536805/180725001-251243be-955f-4b61-a5be-a58e3d2ca138.png)

2.  Medication distribution displays properly, typos are fixed, and dosage appears on medical distribution page.
![image](https://user-images.githubusercontent.com/3536805/180725549-3141441c-776d-4216-9c28-982f9372057e.png)
