### ISSUE TITLE
ANC Subs Visit - Next Steps - Leg Cramps [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#233]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 
 
When a patient identifies that they have leg cramps as a symptom at any visit, we provide health education (even if it is the 2nd or 3rd time they have had this symptom)

<img width="325" alt="Screen Shot 2022-05-03 at 1 03 26 PM" src="https://user-images.githubusercontent.com/77505464/166503278-2ac3fb3b-3a10-4560-bc2a-f19ff528c3d3.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity.

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by jeanette-pelizzon** [comment]
updated the health education screen to include the question: 

<img width="325" alt="Screen Shot 2022-05-03 at 1 03 26 PM" src="https://user-images.githubusercontent.com/77505464/166503278-2ac3fb3b-3a10-4560-bc2a-f19ff528c3d3.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Please update screenshot at issue description.
We need to see complete requirements there.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Empty warning displays when symptoms are repeated.

### Checked and approved:

1. When symptom is Leg cramps the first time, its corresponding health education displays under Next steps.

Symptoms|Next steps
-|-
![1-cramps](https://user-images.githubusercontent.com/3536805/177129318-e657d6e0-c4d9-45bc-80c2-445fc54422c7.png)|![2-health-edu](https://user-images.githubusercontent.com/3536805/177129329-0df842ba-1321-4f62-beea-278b9a8edc0c.png)

2. When symptom exists repeatedly, its health education displays under Next steps.

Repeated symptoms|Next steps
-|-
![3-repeated-symptoms](https://user-images.githubusercontent.com/3536805/177129477-3bb1c505-c607-495d-aeef-2f27516c06b9.png)|![4-health-edu](https://user-images.githubusercontent.com/3536805/177129481-c6b29920-3c4d-4a4f-97cb-495430de791a.png)

**Comment by anvmn** [comment]
@balagan73 

> Empty warning displays when symptoms are repeated.

This problem is already fixed. Please retest after new version is deployed.

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. No warning displays when symptom occurs repeatedly.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app/

### QA Review

### Checked and approved:

1. No Empty warning displays.
