### ISSUE TITLE
ANC Subs Visit - Next Steps - Lower Back Pain [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#234]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 

When a patient identifies that they have lower back pain as a symptom at any visit, we provide health education (even if it is the 2nd or 3rd time they have had this symptom)

<img width="269" alt="Screen Shot 2022-04-26 at 4 26 42 PM" src="https://user-images.githubusercontent.com/77505464/165386308-1c04b262-52c1-4fd5-9402-3aa71a39e296.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity.

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by jeanette-pelizzon** [comment]
updated the health education screen to include the question: 

<img width="339" alt="Screen Shot 2022-05-03 at 12 56 01 PM" src="https://user-images.githubusercontent.com/77505464/166502149-39c3b839-8d40-40df-8ec5-d201bd3f1568.png">

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Empty warning displays when symptom exists repeatedly.

2. Symptom and health education mentions "Low back pain". Is that OK?

Symptom|Health education
-|-
![3-lower](https://user-images.githubusercontent.com/3536805/177128515-5efea3aa-5265-449f-ab10-9421369a2ee3.png)|![4-lower](https://user-images.githubusercontent.com/3536805/177128530-44380d4f-bc01-4929-bcc2-17cc15a62b21.png)


### Checked and approved:

1. When Lower back pain is given as a symptom, its corresponding health education displays under Next steps.

Symptom|Next steps
-|-
![1-lower-back-pain](https://user-images.githubusercontent.com/3536805/177128716-84d11e15-8d59-46f6-aa61-c6e668a89e30.png)|![2-health-edu](https://user-images.githubusercontent.com/3536805/177128722-539cfa5c-2a9f-4a90-a4db-7670e9081cc8.png)

2. When symptom exists repeatedly, health education displays under next steps.

Repeated symptoms|Next steps
-|-
![5-repeated-symptom](https://user-images.githubusercontent.com/3536805/177128846-a05d4ab1-c786-4d2f-a3b4-34214fc3e887.png)|![6-health-edu](https://user-images.githubusercontent.com/3536805/177128855-3015cb9c-e687-482a-bfcf-a4f90bc4b4c6.png)

**Comment by anvmn** [comment]
@balagan73 

> Empty warning displays when symptom exists repeatedly.

This problem is already fixed. Please retest after new version is deployed.

> Symptom and health education mentions "Low back pain". Is that OK?

Already reported (and handled) at another PR.

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. No warning displays when symptom is repeated.

2. Low back pain is changed to Lower back pain.
![7-lower-back-pain](https://user-images.githubusercontent.com/3536805/179522906-e172f881-10c2-435e-9fb8-bb5b6faec4b5.png)
![9-second-visit](https://user-images.githubusercontent.com/3536805/179522967-3b9c0f7f-3fa6-4b12-a85a-b07af009584e.png)
