### ISSUE TITLE
ANC Subs Visit - Next Steps - Constipation [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#235]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 
 
When a patient identifies that they have constipation as a symptom at any visit, we provide health education (even if it is the 2nd or 3rd time they have had this symptom)

<img width="333" alt="Screen Shot 2022-04-26 at 4 29 48 PM" src="https://user-images.githubusercontent.com/77505464/165386805-f0ce1a18-debd-4f3a-94fc-ad10de6061ac.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity.

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by jeanette-pelizzon** [comment]
updated the health education screen to include the questions: 

<img width="315" alt="Screen Shot 2022-05-03 at 12 59 09 PM" src="https://user-images.githubusercontent.com/77505464/166502665-81656995-ae65-4bc2-82bd-92a8a4cf1884.png">

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Empty warning displays when symptom exists repeatedly.
![4-warning-empty](https://user-images.githubusercontent.com/3536805/177126765-7f81f08c-6ed2-465d-941d-b71c8c9f80e2.png)

### Checked and approved:

1. When constipation is given as a symptom, health education is given for it under next steps.

Symptom|Next step
-|-
![1-constipation](https://user-images.githubusercontent.com/3536805/177126965-a25ab9c7-b8b9-41fc-9961-a219263b4678.png)|![2-health-edu](https://user-images.githubusercontent.com/3536805/177126975-2dc628eb-f0e6-49f7-ad04-fcf3e754d97a.png)

2. When symptom exists repeatedly, health education is given for it under next steps.

Repeated symptom|Next steps
-|-
![3-subsequent-visit](https://user-images.githubusercontent.com/3536805/177127559-895e61b4-f7e4-4d66-9cfa-ea0bbac2d5f0.png)|![6-health-edu](https://user-images.githubusercontent.com/3536805/177127240-6b59d288-5783-40c0-b95a-ee1aee2ff584.png)

**Comment by anvmn** [comment]
@balagan73 

> Empty warning displays when symptoms are repeated.

This problem is already fixed. Please retest after new version is deployed.

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. No warning displays when there is repeated constipation diagnosed.
