### ISSUE TITLE
ANC Subs Visit - Next Steps - Varicose Veins [2hr]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#236]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 
 
When a patient identifies that they have varicose veins as a symptom at any visit, we provide health education (even if it is the 2nd or 3rd time they have had this symptom)

<img width="334" alt="Screen Shot 2022-04-26 at 4 32 03 PM" src="https://user-images.githubusercontent.com/77505464/165387236-d5f30764-41a5-4495-98af-3920940346de.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity.

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by jeanette-pelizzon** [comment]
Updated the screen to include the question and match other Health Education sections in the app: 
<img width="237" alt="Screen Shot 2022-05-03 at 1 21 47 PM" src="https://user-images.githubusercontent.com/77505464/166505834-3288539d-e1aa-4720-b064-c99f25ddacf3.png">

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

 ### QA Review

### Found issues and questions:

1. Empty Warning displays when patient has this symptom the second time.
![4-warning-empty](https://user-images.githubusercontent.com/3536805/177125610-203e4f0f-ef57-4da6-9474-70634229735c.png)

### Checked and approved:

1. When patient marks varicose veins as symptom for the first time, the health education displays under Next steps.

Symptom|Next steps
-|-
![1-varicose](https://user-images.githubusercontent.com/3536805/177126181-355aec74-dd4f-4fa7-a845-8dd7a9eff679.png)|![2-health-edu](https://user-images.githubusercontent.com/3536805/177126186-8512122e-fd3f-47f8-b415-09abb0af96dd.png)


2. When patient marks varicose veins as symptom for the second time, the health education displays.

Repeated symptom|Health education
-|-
![3-subsequent-symptom](https://user-images.githubusercontent.com/3536805/177125887-b1c749af-9cd1-4233-b841-e628afd0bef9.png)|![4-health-edu](https://user-images.githubusercontent.com/3536805/177125892-e32e523c-89ae-447a-bd66-81ad34c87479.png)

**Comment by anvmn** [comment]
@balagan73 

> Empty warning displays when symptoms are repeated.

This problem is already fixed. Please retest after new version is deployed.

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. No warning displays for first or repeated Varicose veins symptoms.
