### ISSUE TITLE
ANC Subs Visit - Next Steps - Leg Pain or Redness [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#237]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 
 
When a patient identifies that they have leg pains as a symptom at any visit and answer NO to all follow-up questions, we provide health education (even if it is the 2nd or 3rd time they have had this symptom)

<img width="325" alt="Screen Shot 2022-04-26 at 4 35 27 PM" src="https://user-images.githubusercontent.com/77505464/165387798-89cd6e36-822f-4077-aff0-7d30ca0f2150.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity.

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by jeanette-pelizzon** [comment]
Updated this screen to: 

(1) include leg redness as well 
(2) added in the follow-up question so it is in the same format as other health education screens in the app 

<img width="346" alt="Screen Shot 2022-05-03 at 11 43 08 AM" src="https://user-images.githubusercontent.com/77505464/166487738-73825fca-c934-4f02-b3f6-f9e2a70b0eb8.png">


// @anvmn

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. The word "or" is missing.
![4-typo](https://user-images.githubusercontent.com/3536805/177110447-fd78361c-dd3d-44bb-bd2a-daac4c2be608.png)


### Checked and approved:

1. When the patient has leg pain or redness, as far as follow-up questions are no, they are offered health education.

Symptoms|Follow-up|Health education
-|-|-
![1-redness](https://user-images.githubusercontent.com/3536805/177110660-c676b79b-ceb0-4ac1-be96-0a2ff88db9bb.png)|![2-follow-up-no](https://user-images.githubusercontent.com/3536805/177110664-df96ab34-0371-454e-9c76-a130e10afbe9.png)|![3-health-edu](https://user-images.githubusercontent.com/3536805/177110665-56a29555-225f-4ae9-8c78-a094a044f8e3.png)

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Panel title is now 'Leg pain or redness'
![image](https://user-images.githubusercontent.com/3536805/180719408-e95da06b-b2b8-4c47-995c-a3a823ac8988.png)
