### ISSUE TITLE
ANC Subs Visit - Next Steps - Deep Vein Thrombosis (DVT) [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#239]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 
 
When a patient identifies that they have: 

(1) (ANY VISIT) Symptom Review: Leg Redness + at least one yes to the follow-up questions
(2) (ANY VISIT) Symptom Review: Leg Pain + at least one yes to the follow-up questions

Pop-Up | Referral Screen 
--|--
<img width="302" alt="Screen Shot 2022-04-26 at 4 39 48 PM" src="https://user-images.githubusercontent.com/77505464/165388510-c3d6e0d3-0a57-443b-a433-351e26e1a0d2.png"> | <img width="302" alt="Screen Shot 2022-04-26 at 4 39 53 PM" src="https://user-images.githubusercontent.com/77505464/165388513-b38b8f10-1284-4ad3-8fe5-f6f32b8a0d30.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity.

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. When patients have leg pain or radness, and they answer at least one yes to any follow-up questions, they are diagnosed with DVT, and are referred to hospital.

Symptoms|Follow-up questions|Warning|Hospital referral
-|-|-|-
![1-leg-pain](https://user-images.githubusercontent.com/3536805/177113438-546a8f3e-10bb-4a58-8659-0d7b89512917.png)|![2-follow-up-yes](https://user-images.githubusercontent.com/3536805/177113453-2cdb9031-cd22-4961-9ee2-8bd063db2dbc.png)|![3-warning](https://user-images.githubusercontent.com/3536805/177113456-c259407c-e3ee-499c-81b3-640b2bb35b33.png)|![4-hospital](https://user-images.githubusercontent.com/3536805/177113458-c298d5de-e0b8-4279-b9bb-cc8e5b457ba9.png)
