### ISSUE TITLE
ANC Subs Visit - Next Steps - Tuberculosis [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#240]
## Issue 
 
When a patient identifies that they have had a cough for more than 2 weeks, we direct the user to follow TB protocols via a pop-up. There is no normal screen as the TB protocols can vary. 

<img width="280" alt="Screen Shot 2022-04-26 at 5 07 53 PM" src="https://user-images.githubusercontent.com/77505464/165392626-8529ad55-dccd-4429-a99a-35ce1412429b.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity.

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by anvmn** [comment]
@jeanette-pelizzon 

1. Why do we have 4 follow up questions for this symptom, if we do not look at them?
2. I believe that similart any treatment, this should be recorded at Medication distribution activity (similar for what we have for Malaria). Here we'll have 2 options - protocols and no treatment administered.

**Comment by jeanette-pelizzon** [comment]
> 1. Why do we have 4 follow up questions for this symptom, if we do not look at them?

It's my understanding that there will eventually be TB protocols built into E-Heza. It was more complicated than initially expected so that's why we have the "follow TB protocols" pop-up as a holdover for now. 

> 2. I believe that similart any treatment, this should be recorded at Medication distribution activity (similar for what we have for Malaria). Here we'll have 2 options - protocols and no treatment administered.

I would need to double check on this but I believe it should pop-up mid-flow so they can take precautionary measures during the exam. @leowea can confirm

**Comment by jeanette-pelizzon** [comment]
@anvmn spoke with Wendy on this - with TB we should keep the pop-up where it is. There are no next steps for this but the nurse/patient make need to put on a mask or order some tests (outside of e-heza) during this encounter.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Issue description and Logic master google doc mentions > 2 weeks cough. We have 3 weeks in symptom review.
![1-3-weeks](https://user-images.githubusercontent.com/3536805/176436184-c8b0e68f-a42a-47b3-b358-85f9ec14e78b.png)

2. I haven't yet ended the encounter where I have marked pelvic pain as a symptom. Even though I have deleted it from the symptoms, and marked only coughing, pelvic pain is still diagnosed.

Symptoms|Diagnoses
-|-
![4-symptoms](https://user-images.githubusercontent.com/3536805/176436561-d18df02d-7ea3-446d-8f10-2ce3745cd028.png)|![3-pelvic-pain](https://user-images.githubusercontent.com/3536805/176436423-ba173369-eaab-48b8-92a4-1f7ab801f4e7.png)

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Issue description and Logic master google doc mentions > 2 weeks cough. We have 3 weeks in symptom review.

Should it be 2 or 3 weeks?

**Comment by leowea** [comment]
>2 weeks!


Wendy Leonard, MD, AAHIVS

Executive Director

TIP Global Health (formerly The Ihangane Project)

***@***.*** | +1 831 234 6053
www.tipglobalhealth.or <http://www.tipglobalhealth.org/>g



*Hope lies in dreams, in imagination, & in the courage of those who dare to
make dreams into reality. **- Jonas Salk*

**Comment by jeanette-pelizzon** [comment]
1. 2 weeks per wendy's comment. Sorry, it was missed on this screen when we updated logic. 

2. Seems like there is a bug there. @anvmn can you investigate? I believe it should only appear in the next steps if you checked it as a symptom and then hit save.

**Comment by jeanette-pelizzon** [comment]
@anvmn do we need to move this to QA? It wasn't assigned to a project so I put it back on the e-heza development board.

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Yes, it's fixed already. Lets move to QA.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Cough duration is 2 weeks now.
![image](https://user-images.githubusercontent.com/3536805/180742046-c2f42549-1cd6-4bc5-977b-c334bf7f6aa2.png)


2. When I uncheck Pelvic pain, and then check cough for 2 weeks, warning displays stating only Risk of TBC.
![image](https://user-images.githubusercontent.com/3536805/180741474-8340018e-a111-482f-a0f0-8753a60c62a2.png)
