### ISSUE TITLE
ANC Subs Visit - Next Steps - Pelvic Pain [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#241]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 

**First Time**
When a patient identifies that they have pelvic pain as a symptom for the first time and answer no to all follow-up questions, we provide health education.  

<img width="290" alt="Screen Shot 2022-04-26 at 5 10 38 PM" src="https://user-images.githubusercontent.com/77505464/165393019-d658d09e-2187-49de-bf96-c2dd4dbec9b1.png">

**Second Time** 
When a patient identifies: 

(1) (ANY VISIT) Symptom Review: Pelvic Pain + Yes to follow up question = Refer to Hospital
(2) (SECOND VISIT) Symptom Review: Pelvic Pain + No to follow up question = Refer to Hospital

Pop-Up | Referral 
--|--
<img width="324" alt="Screen Shot 2022-04-26 at 5 23 59 PM" src="https://user-images.githubusercontent.com/77505464/165394979-757943fb-a486-47e3-a27c-c23266a08484.png"> | <img width="325" alt="Screen Shot 2022-04-26 at 5 24 05 PM" src="https://user-images.githubusercontent.com/77505464/165394983-04fe2da1-9df0-4ae7-87c8-b20f4b146793.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity. If they are being referred to the hospital for multiple things, there is only one referral screen. 

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by jeanette-pelizzon** [comment]
updated the Health Education screen to include the question: 

<img width="204" alt="Screen Shot 2022-05-03 at 12 58 10 PM" src="https://user-images.githubusercontent.com/77505464/166502468-f25f3595-c6d1-44c7-bcae-474878a244e0.png">

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. When at subsequent visit the patient has Pelvic pain and No severe pain, they are not referred to hospital. 
![6-second-visit](https://user-images.githubusercontent.com/3536805/176406091-8e2ac625-b671-4010-9698-2fc9310d3414.png)

2. Wording of the displayed warning is different from issue description. See image down below. Is this a problem?

### Checked and approved:

1. First visit, Pelvic pain and No severe pain, health education displays.

Pelvic pain|No severe pain|Health education
-|-|-
![1-symptom](https://user-images.githubusercontent.com/3536805/176406284-273701e4-cca7-47b3-874f-24c1eb40232e.png)|![2-follow-up](https://user-images.githubusercontent.com/3536805/176406292-63fdd3aa-4e0e-43af-91f6-d49109d55c63.png)|![3-health-edu](https://user-images.githubusercontent.com/3536805/176406297-ef0559b6-8d39-43b1-9201-7f151be30724.png)

2. When there is Severe pain, warning displays and patient is referred to hospital.

Warning|Referral to hospital
-|-
![4-warning](https://user-images.githubusercontent.com/3536805/176406452-45a0193b-eea8-4d71-9689-7698fe278813.png)|![5-hospital-referral](https://user-images.githubusercontent.com/3536805/176406458-f2d067d0-1f19-4adc-8905-5358979f82c6.png)

**Comment by anvmn** [comment]
@balagan73 

> When at subsequent visit the patient has Pelvic pain and No severe pain, they are not referred to hospital.

Just ran this scenario locally, and it worked well. 
Please retest and see if issue is reproduced.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### Retesting point 1.

I confirm the issue exists. Steps of the workflow I have taken:

Pelvic pain first symptom|No severe pain|Health education
-|-|-
![10-pelvic-pain](https://user-images.githubusercontent.com/3536805/177290558-ba9b5137-4949-4aad-9596-092550f3bde9.png)|![11-no-pain](https://user-images.githubusercontent.com/3536805/177290575-5a411fe1-5066-4127-ae46-669d2a967fab.png)|![12-health-edu](https://user-images.githubusercontent.com/3536805/177290587-9beea5c3-474d-4244-a229-eb01715872a4.png)

Pelvic pain second time|No severe pain|No next steps
-|-|-
![13-pelvic-pain2](https://user-images.githubusercontent.com/3536805/177290602-4abafb59-49c5-4dfc-a306-12fc828f5aa1.png)|![14-no-pain2](https://user-images.githubusercontent.com/3536805/177290626-9b406d59-915d-435c-bf7f-c67350b01cde.png)|![15-no-next-steps](https://user-images.githubusercontent.com/3536805/177290646-b707eb68-b718-4a4f-971b-5837b440fdf8.png)

**Comment by anvmn** [comment]
@balagan73 

This was fixed at most recent deploy. I verified it works well on Nutrition env.

Please retest.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Patient is referred to hospital at second encounter, when there is pelvic pain with No severe pain in followup question.
![17-referral](https://user-images.githubusercontent.com/3536805/180143501-6938af25-2e25-4d81-8e42-683a186fff7b.png)
