### ISSUE TITLE
ANC Subs Visit - Next Steps - Lower Urinary Tract Infection [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#242]
## Issue 
In subsequent encounters, a patient may identify a symptom for the first time which will result in a specific diagnosis. If they return and identify the same symptom again then the diagnosis may change. 
 
When a patient identifies that they have the following, we prescribe medication.
(1) Symptom Review: Burning with Urination + no to all FU's 
(2) Symptom Review: Burning with Urination + urinary frequency

Pop-Up | Medication 
--|-- 
<img width="305" alt="Screen Shot 2022-04-26 at 5 29 45 PM" src="https://user-images.githubusercontent.com/77505464/165395743-ff79fd77-30fb-4229-b7c8-ce2d52d26939.png"> | <img width="303" alt="Screen Shot 2022-04-26 at 5 29 51 PM" src="https://user-images.githubusercontent.com/77505464/165395744-c189a250-ba61-4ee0-b9ae-69ea40bcd7d8.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Typo in medication names.
![1-typo](https://user-images.githubusercontent.com/3536805/176450186-122cb067-c975-41ba-88de-2e428c193dae.png)

It should be Nitrofurantoin and Amoxicillin (double l)

### Checked and approved:

1. When Symptom Review: Burning with Urination + no to all FU's or
Symptom Review: Burning with Urination + urinary frequency, the diagnosis is Urinary tract infection.

![2-warning](https://user-images.githubusercontent.com/3536805/176450822-5af56421-143a-4759-91c5-4fc8ce3fe738.png)

Next steps contain correct medication, although with typos.

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Looking at the hypertension medical distribution page I noticed another typo. Cronic should be Chronic
![4-hypertension-typo](https://user-images.githubusercontent.com/3536805/180180649-d2b6adb5-bc44-4fb4-b9a0-51734913da28.png)


### Checked and approved:

1. The typo in the medication names are fixed.
![3-typo-fixed](https://user-images.githubusercontent.com/3536805/180180897-bf2ad273-6527-4834-96a3-eaba27ed74ed.png)

**Comment by jeanette-pelizzon** [comment]
@Diama1 can you please fix the typo that Zolt has outlined above. Thank you!

**Comment by anvmn** [comment]
@balagan73 please check that typos were fixed on Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

###  QA Review

### Checked and approved:

1. Typos in medication names are fixed.
![image](https://user-images.githubusercontent.com/3536805/183839552-9644f890-008c-4e60-901b-d7dd92fb75f1.png)
