### ISSUE TITLE
ANC Subs Visit - Next Steps - Possible Trichomonas or Bacterial Vaginosis [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#246]
## Issue 

When a patient identifies that they have the following symptoms, we provide health education and medication: 
(1)Symptom Review: Abnormal Vaginal Discharge + NO to all follow-up questions 

Pop-Up | Health Education | Medication
--|--|-- 
<img width="323" alt="Screen Shot 2022-04-26 at 5 42 14 PM" src="https://user-images.githubusercontent.com/77505464/165397335-be9842c1-ab88-4b4c-bb2c-e457acecb394.png"> | <img width="320" alt="Screen Shot 2022-04-26 at 5 42 20 PM" src="https://user-images.githubusercontent.com/77505464/165397337-544393f3-03d1-49a6-82cf-d4bdde2b13b4.png"> | <img width="302" alt="Screen Shot 2022-05-11 at 11 20 34 AM" src="https://user-images.githubusercontent.com/77505464/167886837-aa223f0e-a910-4360-80eb-a6cd10d641b9.png">

## Supporting Documents: 
You can see the logic for next steps[ here. ](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)

## Notes: 
Similar to the first ANC encounter, if a patient is receiving health education for multiple things they will stack in one health education sub-activity. If they are being referred to the hospital for multiple things, there is only one referral screen. 

## To Do:  
- Style next steps screens per design 
- Adjust logic per document

**Comment by jeanette-pelizzon** [comment]
updated health education screen to include question: 

<img width="326" alt="Screen Shot 2022-05-03 at 1 04 52 PM" src="https://user-images.githubusercontent.com/77505464/166503616-b0dd2441-d29e-43f9-a3bb-1292ee44bbe2.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Regarding medication distribution - since we have single option here, I believe we should follow standard flow of prescriving medication, as we do for HIV, for example:
![Selection_730](https://user-images.githubusercontent.com/17882245/167709257-2104768e-fbf5-4680-99a5-60d0f158c51d.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn sorry I somehow skipped the question. updated the main issue image to be correct

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Wording of warning message is different then in issue description. Is that a problem?
![3-warning](https://user-images.githubusercontent.com/3536805/176400209-9c486a3e-64e3-4eb4-8c35-0c7aedf828a1.png)

### Checked and approved:

1. If proper preconditions exist, the corresponding Health education and Medication distribution screens display.

Preconditions|Health Education|Medication
-|-|-
![1-avd](https://user-images.githubusercontent.com/3536805/176400497-be02b6b3-3c9a-427e-93f3-bed66585add3.png)![2-follow-up-questions](https://user-images.githubusercontent.com/3536805/176400505-7dc5a16b-dfdf-41fb-ba1c-ba484d26d2bb.png)|![5-health-edu](https://user-images.githubusercontent.com/3536805/176400544-b047b6ab-7e85-4689-8aec-9ef4c0120abd.png)|![4-medication](https://user-images.githubusercontent.com/3536805/176400573-ab35780f-cb8e-4b41-a6e3-4f94ccc62611.png)

**Comment by anvmn** [comment]
@balagan73 

> Wording of warning message is different then in issue description. Is that a problem?

This was updated. Please retest after new version is deployed.

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. There is a space missing on the warning panel:

![image](https://user-images.githubusercontent.com/3536805/180738124-b931c5e7-1e22-448d-8cc7-2467d6b1fa44.png)
