### ISSUE TITLE
ANC Subs Visit - Add Activity - Treatment Review [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#247]
## Issue

Building upon the existing subsequent encounter activities for ANC @ Health Centers, we will be adding a Treatment Review Activity to REPLACE the current medication activity

The Treatment Review activity should appear 6thin the tray, after Family Planning. 

Individual Icon: 
![Treatment History](https://user-images.githubusercontent.com/77505464/165400648-516cf34d-bd45-453c-a5ed-d255869d072c.jpg)

Tray View: 
<img width="301" alt="Screen Shot 2022-04-26 at 2 26 21 PM" src="https://user-images.githubusercontent.com/77505464/165367700-53dd3767-f5bc-4130-9498-c46001fd1b8b.png">

The activity will have sub-activities based on a patient's previous diagnosis. Potential subactivities could be: 
- Prenatal Medication ( #248) 
- HIV Medication (#249)
- Hypertension (#250)
- Malaria (#251)
- Anemia (#252)
- Syphilis (#253)
- ** There could be more added at a later date** 

## Design Files: 
You can access the icon SVG [here. ](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=207%3A442)

## To Do: 
- Build out architecture for the Treatment Review Activity.

**Comment by jeanette-pelizzon** [comment]
Updated main issue with related issues and more information about sub-activities.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Treatment review displays as 6th icon, after Family planning.
![1-treatment-review](https://user-images.githubusercontent.com/3536805/175491270-3719d4fd-cbcc-4955-b30d-ed6200bc07a8.png)
