### ISSUE TITLE
ANC Subs Visit - Treatment History - Prenatal Medication [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#248]
## Issue

We are moving the previous "Medication" activity to a subactivity under "Treatment Review." We are changing the name to "Prenatal Medication." This is because, during subsequent encounters, the healthcare worker will need to follow up with the patient on the treatment protocol that they were prescribed during their previous visit. It makes the most sense, clinically, to have the prenatal medication questions as a subactivity under treatment review. 

The sub-activity icon is the pill (it will be the same for all sub-activities in this section): 

![Medication](https://user-images.githubusercontent.com/77505464/165583910-c2d40ce1-800e-4599-b6db-a333adc408a0.jpg)

The screen for this sub-activity will look like: 
<img width="343" alt="Screen Shot 2022-04-27 at 1 14 45 PM" src="https://user-images.githubusercontent.com/77505464/165583988-56b0eaf1-f7d5-49bd-a81b-1babf9f517d6.png">

## Design Files: 
You can find the Treatment Review flow in Figma [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021)

## Notes: 

The logic for both folic acid and mebendazole questions and next steps remains the same. 

## To Do: 
- Create Prenatal Medication Subactivity 
- Style screen per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. At first encounter the Medication activity displays.
![3-first-encounter](https://user-images.githubusercontent.com/3536805/177933459-504b4ded-8efc-4f61-ae28-61e316bf6baf.png)

2. At subsequent encounters the medication activity doesn't display, but there is a prenatal medication subactivity under Treatment review.

![1-no-medication](https://user-images.githubusercontent.com/3536805/177933549-b894d52e-a14a-4f10-b55f-217e2571c820.png)
![2-subsequent-encounter](https://user-images.githubusercontent.com/3536805/177933558-41f13a12-dd35-4dd5-b77a-3fb949bcc89a.png)
