### ISSUE TITLE
ANC Subs Visit - Treatment History - Hypertension [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#250]
## Issue 

Under the "Treatment Review" activity, a Hypertension medication sub-activity will populate if the patient was diagnosed with hypertension in a previous encounter. This is necessary for the healthcare worker to follow up with the patient and ensure they are correctly taking their medications and that their symptoms are improving. This activity will only populate for patients who were diagnosed with hypertension previously in this pregnancy.

The top of the screen should populate with the treatment they were prescribed previously. This way the healthcare worker can verify that is what they have been taking and adhering to the correct dosage.

<img width="318" alt="Screen Shot 2022-04-27 at 3 09 38 PM" src="https://user-images.githubusercontent.com/77505464/165601676-714b0080-0140-4783-9aa7-9ac248c3ec38.png">

The answers to these questions will affect the next steps for this diagnosis. 

## Design Files:
You can see the Figma file [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=424%3A24920)

You can access the medication icon[ here.](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=201%3A28) 

Here is the icon that should be used: 
![Medication](https://user-images.githubusercontent.com/77505464/165603581-f3ccec29-c281-48d3-be18-c41b8aa4c484.jpg)

## To Do:
- Create hypertension medication sub-activity
- Create logic for the two different pathways
- Style screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Here I did a more thorough testing of Treatment review - Hypertension:
https://github.com/TIP-Global-Health/eheza-app/issues/256#issuecomment-1165332275

The top of the screen contains the currently prescribed medication of the patient.
