### ISSUE TITLE
ANC Subs Visit - Treatment History - Malaria [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#251]
## Issue
Under the "Treatment Review" activity, a Malaria medication sub-activity will populate if the patient was diagnosed with Malaria in a previous encounter. This is necessary for the healthcare worker to follow up with the patient and ensure they are correctly taking their medications and that their symptoms are improving. This activity will only populate for patients who were diagnosed previously in this pregnancy.

The top of the screen should populate with the treatment they were prescribed previously. This way the healthcare worker can verify that is what they have been taking and adhering to the correct dosage.

Example Coartem | Example Quinine
--|--
<img width="272" alt="Screen Shot 2022-04-27 at 3 21 00 PM" src="https://user-images.githubusercontent.com/77505464/165603699-01851d64-2112-413f-8d0a-ae1ce660551f.png"> | <img width="271" alt="Screen Shot 2022-04-27 at 3 20 56 PM" src="https://user-images.githubusercontent.com/77505464/165603701-84aef9a8-4942-42bc-b1cd-555977d61d8e.png">

The answers to these questions will affect the next steps for this diagnosis.

## Design Files:
You can see the Figma file [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=424%3A24920)

You can access the medication icon[ here.](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=201%3A28) 

Here is the icon that should be used: 
![Medication](https://user-images.githubusercontent.com/77505464/165603581-f3ccec29-c281-48d3-be18-c41b8aa4c484.jpg)

## To Do:
- Create malaria medication sub-activity
- Create logic for the two different pathways
- Style screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Under Treatment review the Malaria medication panel is populated according to what was prescribed in previous encounter.

Medicine|Prescription|Review
-|-|-
Quinine|![1-quinine](https://user-images.githubusercontent.com/3536805/175489983-b41de8e6-83bd-4307-8594-b61313704646.png)|![2-quinine](https://user-images.githubusercontent.com/3536805/175490000-79e9c31a-3f21-4931-b6c4-f28de60f7292.png)
Coartem|![3-coartem](https://user-images.githubusercontent.com/3536805/175490076-a5aae0db-5014-450c-82eb-384c981e7d26.png)|![4-coartem](https://user-images.githubusercontent.com/3536805/175490085-f50f7c29-d845-4ca2-a6b8-0e96b1b84790.png)
