### ISSUE TITLE
ANC Subs Visit - Treatment History - Anemia [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#252]
## Issue
Under the "Treatment Review" activity, an anemia medication sub-activity will populate if the patient was diagnosed with Anemia in a previous encounter. This is necessary for the healthcare worker to follow up with the patient and ensure they are correctly taking their medications and that their symptoms are improving. This activity will only populate for patients who were diagnosed previously in this pregnancy.

The top of the screen should populate with the treatment they were prescribed previously. This way the healthcare worker can verify that is what they have been taking and adhering to the correct dosage.

<img width="294" alt="Screen Shot 2022-04-27 at 3 23 29 PM" src="https://user-images.githubusercontent.com/77505464/165604090-6dbada47-0a08-4ecb-a206-ab3e69ccacbf.png">

The answers to these questions will affect the next steps for this diagnosis.

## Design Files:
You can see the Figma file [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=424%3A24920)

You can access the medication icon[ here.](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=201%3A28) 

Here is the icon that should be used: 
![Medication](https://user-images.githubusercontent.com/77505464/165603581-f3ccec29-c281-48d3-be18-c41b8aa4c484.jpg)

## To Do:
- Create anemia medication sub-activity
- Create logic for the two different pathways
- Style screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. These occur before getting to the Treatment review panel:
I have entered 7 g/dL for hemoglobin test result. Then Encounter was paused. Under case management there were 2 entries:
![3-case-management](https://user-images.githubusercontent.com/3536805/175531849-7dafc8a6-4a9a-4680-b188-fe12b9049bb4.png)

Clicking on the Vitals recheck and updating the hemoglobin data doesn't make this pending entry disappear. Clicking it the hemoglobin lab panel displays. 
![4-7g-hemoglobin](https://user-images.githubusercontent.com/3536805/175532665-c343e3ab-01cc-4596-b913-963f86a5a142.png)

After finishing the ANC Lab results pending entry, which opened the same panel but without data, the vitals recheck pending entry still remains, but clicking it displays the popup to end encounter. The pending entry still remains.
After refreshing the page it is possible to open the lab results panel, and then end the encounter, but pending entry remains.

2. The recommended iron dosage for anemia is wrong.

Actual dosage|Dosage in google sheet
-|-
![1-iron-dosage](https://user-images.githubusercontent.com/3536805/175532848-6b2f9346-9354-4656-9fee-65d475672edd.png)|![2-dosage](https://user-images.githubusercontent.com/3536805/175532870-c044509a-f9be-4c9d-ae17-d02840a11475.png)

3. The grammar of the prescribed medication is incorrect. There are 2 verbs in the sentence.
![6-grammar](https://user-images.githubusercontent.com/3536805/175535496-642cf6b2-5b01-49da-b8fb-a4d74e2ac126.png)

Maybe putting a colon after the total dosage would make reading the text easier elsewhere too.  
![7-grammar](https://user-images.githubusercontent.com/3536805/175537034-9fc2c476-180f-49de-be07-a93db23d98db.png)


### Checked and approved:

1. Under Treatment review the previously prescribed medication matches the panel in the issue description. However, this is grammatically incorrect, and actually double dose is prescribed.
![5-treatment-review](https://user-images.githubusercontent.com/3536805/175536654-7a5dfb09-7fec-4628-842e-fb0e26e395b5.png)

**Comment by adamhstewart** [comment]
@anvmn can you please check:

1.  the logic on the case management screen identified in point 1. 
2. The dosage in point 2
3. Make the grammar suggestions in the other points

**Comment by anvmn** [comment]
@adamhstewart 

> 1. the logic on the case management screen identified in point 1.

I don't really understand what the problem is.
There're 2 entries - each represent separate encounter.
Logic says that if there's a need for vital recheck, this is what the label will be saying,
even if there're labs to be filled in.
The requirements are specified at https://github.com/TIP-Global-Health/eheza-app/issues/159, and seems that it has passed QA.

To be able to analyse a problem, I need to know what steps were performed, what was the expected result and was was the actual result.

> 2. The dosage in point 2

Fixed at [4c3485a](https://github.com/TIP-Global-Health/eheza-app/pull/303/commits/4c3485a513e4c2531b56bb095670ccf5b872ecec)

> 3. Make the grammar suggestions in the other points

Fixed at [f490d1a](https://github.com/TIP-Global-Health/eheza-app/pull/303/commits/f490d1a13bdfdf0443555b5c88402d63fd830559)

**Comment by anvmn** [comment]
@balagan73 

Please retest

**Comment by balagan73** [comment]
### QA Review

### Found issues and question. 

1. There is another verb in the sentence. "take" should be dropped, or changed to "to be taken"
![10-grammar](https://user-images.githubusercontent.com/3536805/180151664-e0fe24be-5e6c-449b-9926-959246a70462.png)

Although the comma is inserted, and the Coartem, 4 treatment looks good here, it occurs in other places too. If Medical distribution text is reused on the report, maybe these should be rephrased and the beginning verb should be dropped to result in:
"4 Coartem tablets by mouth twice per day x3 days".
and accordingly: "treated with 4 Coartem tablets by mouth twice per day x3 days"

Treatment|Report
-|-
![13-give-coartem](https://user-images.githubusercontent.com/3536805/180156061-f4eae22f-3812-43cf-8523-456314833819.png)|![14-report](https://user-images.githubusercontent.com/3536805/180156070-e3de9425-1c26-4df1-bc6d-a36e485aa510.png)

2. Not sure about what should I see under case management after encounter is paused. Trying to reproduce previous problem I have entered EGA >=20 weeks + diastolic >=90 to <110 mmHg x 2 (separated by >2 hours) data and pending Hemoglobin test.

 Case management|To Do
-|-
![15-case-management](https://user-images.githubusercontent.com/3536805/180159005-29252e15-8b71-49c0-a5fa-a9bd51f9706f.png)|![16-pending](https://user-images.githubusercontent.com/3536805/180159034-f8119b80-56b9-4ac6-aa77-6bb33d02ac58.png)

 
### Checked and approved:

1. Dosage is fixed.
![9-dosage-fixed](https://user-images.githubusercontent.com/3536805/180151714-695363ad-5168-4844-aab5-c61f3519c609.png)

**Comment by jeanette-pelizzon** [comment]
1. @Diama1 can you update this text please. There is a part above the image and then the coartem point below the image. 

2. I believe it is set up at the moment to show the person twice in the list - 1x for the vitals recheck and 1x for the lab follow up. This seems like it is not happening @balagan73?

**Comment by jeanette-pelizzon** [comment]
Checking in on this issue @balagan73 @Diama1

**Comment by balagan73** [comment]
@jeanette-pelizzon 

When I have a pending lab results, and vitals recheck, I only see Vitals recheck under case management.

Next steps|Case management
-|-
![image](https://user-images.githubusercontent.com/3536805/181179302-6d660b90-07a3-4c4b-b2df-8a3b17f9ed6d.png)|![image](https://user-images.githubusercontent.com/3536805/181179354-9576ba37-91fa-4337-ac83-07cedfb0d35c.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn it should show both correct?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

No, see point 1 at https://github.com/TIP-Global-Health/eheza-app/issues/252#issuecomment-1167062913

**Comment by adamhstewart** [comment]
@anvmn please check found issues above (except the case management screen).

**Comment by anvmn** [comment]
@adamhstewart 

> 1. There is another verb in the sentence. "take" should be dropped, or changed to "to be taken"

Fixed at #475 - added 'to be taken' at appropriate places for all treatments we display.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Wording on the Anemia medication is grammatically correct.
![image](https://user-images.githubusercontent.com/3536805/192326610-03fe3198-a469-4ba0-9cd1-1dbd96ffdb5b.png)
