### ISSUE TITLE
ANC Subs Visit - Treatment History - Syphilis [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#253]
## Issue
Under the "Treatment Review" activity, a Syphilis medication sub-activity will populate if the patient was diagnosed with Syphilis in a previous encounter. This is necessary for the healthcare worker to follow up with the patient and ensure they are correctly taking their medications and that their symptoms are improving. This activity will only populate for patients who were diagnosed previously in this pregnancy.

The top of the screen should populate with the treatment they were prescribed previously. This way the healthcare worker can verify that is what they have been taking and adhering to the correct dosage.

<img width="318" alt="Screen Shot 2022-04-27 at 3 26 01 PM" src="https://user-images.githubusercontent.com/77505464/165604476-d2688990-16c6-4310-9a44-ca262371a473.png">

The answers to these questions will affect the next steps for this diagnosis.

## Design Files:
You can see the Figma file [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=424%3A24920)

You can access the medication icon[ here.](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=201%3A28) 

Here is the icon that should be used: 
![Medication](https://user-images.githubusercontent.com/77505464/165603581-f3ccec29-c281-48d3-be18-c41b8aa4c484.jpg)

## To Do:
- Create Syphilis medication sub-activity
- Create logic for the two different pathways
- Style screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. During subsequent encounter under treatment review no Syphilis medication icon displays. @anvmn Did I miss something?
![5-no-syphilis-med](https://user-images.githubusercontent.com/3536805/175263522-4be6d690-7168-4f13-964f-3f6007f1c0c8.png)

Previous steps taken:

1|2|3
-|-|-
![1-new-diagnosis](https://user-images.githubusercontent.com/3536805/175263721-2b1b3c7b-e1c4-4615-874e-f92f411a8904.png)|![2-outside-care-medication](https://user-images.githubusercontent.com/3536805/175263730-7e77d83a-ecd1-440a-9885-754ce1b25fb0.png)|![3-syphilis-lab](https://user-images.githubusercontent.com/3536805/175263735-6b6e19aa-7179-4936-8ae5-0d470c9df659.png)

**Comment by anvmn** [comment]
@balagan73 

Outside care is not in scope of this issue.
Correct flow is to make syphilis test, and then prescribe medication at Medication distribution task of Next steps activity. Please retest.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. I found another way not to display the Syphilis medication icon under Treatment review. No medication is available under Next steps:

Steps taken:

Lab|Lab results|Next steps
-|-|-
![6-lab-syphilis](https://user-images.githubusercontent.com/3536805/175299563-039d3215-b9d5-43fb-8ec8-95a2d521a18e.png)|![7-lab-results](https://user-images.githubusercontent.com/3536805/175299574-5fea2fca-8ee2-4ecd-bf72-c5a3402dda16.png)|![9-next-steps](https://user-images.githubusercontent.com/3536805/175299596-a3c348a9-54f8-409f-9dfd-a64c9aac599f.png)

![11-no-syphilis-medication](https://user-images.githubusercontent.com/3536805/175299739-eee87eef-0845-4cca-a6c2-088f43f7f259.png)

**Comment by anvmn** [comment]
@balagan73 

> I found another way not to display the Syphilis medication icon under Treatment review. No medication is available under Next steps:

Diagnosis in your flow is Neurosyphilis. Next steps for it is sending to hospital.

See Logics file:
![Selection_871](https://user-images.githubusercontent.com/17882245/175304891-89cca1ef-3ccb-4026-b3e2-1c1c9f758948.png)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Indeed, when selecting 'None of these' as the experienced symptoms by the patient, it is possible to prescribe medication.
![12-medication](https://user-images.githubusercontent.com/3536805/175308286-5924e46b-b9d3-4c4d-90c1-b26b30fb6fa0.png)

Then during subsequent encounter the Syphilis medication is available under Treatment review.
![13-treatment-review](https://user-images.githubusercontent.com/3536805/175308964-76c78eb0-b72c-49cf-98de-674b73c451aa.png)
