### ISSUE TITLE
"Stack" medication disbursements in the case of multiple diagnoses [12h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#255]
## Issue 

Identified in https://github.com/TIP-Global-Health/eheza-app/issues/152#issuecomment-1083191434 and https://github.com/TIP-Global-Health/eheza-app/issues/124#issuecomment-1082437031 in some cases a patient may have multiple diagnoses and as a result different sets of instructions for the different conditions. These instructions and dosing should all appear on the same screen separated by a horizontal rule as such:

<img width="209" alt="Screen Shot 2022-04-27 at 3 35 19 PM" src="https://user-images.githubusercontent.com/688507/165611153-1e4769fd-450f-419b-bd27-f061c17a8f70.png">

## Tasks
- create the underlying architecture to display multiple types of disbursements in the same page
- render the page according to design.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. The medications for different diagnoses show up separated by a horizontal ruler under the Medication distribution activity.

![3-medication](https://user-images.githubusercontent.com/3536805/178423132-c9cdeb78-7c97-4658-8b36-1892b89c6c70.png)
