### ISSUE TITLE
ANC Subs Visit - Next Steps - Updated Hypertension Meds [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#256]
## Issue

When a patient returns to the health center for a subsequent visit, the healthcare worker goes through a treatment review with them to ensure they are taking their medicine appropriately. This happens in the treatment review activity. (#249)

In the case of hypertension, the nurse takes information told to them in the treatment review PLUS the numbers during the exam to make a decision on what course of treatment will determine what the continued treatment plan for the patient is. 

The logic for what we recommend is outlined in[ this document](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) in the subsequent encounter section under "Hypertension (Continued Care)." 

The screen shows: 
- the diagnosis 
- key data on the current state of the patient relevant to the diagnosis (BP, positive test result, etc) 
- current medication regimen
- recommended medication regimen 
- checkbox list of possible treatment options - this could be medication, could be a hospital referral, could to follow a protocol. 

The screen gives the health care worker all the different treatment levels to choose from. We are empowering them to choose which option based on the conversation with the patient regarding medication adherence (this is what we are doing in treatment review) and their blood pressure ranges.

We then ask them to confirm if they gave the recommended treatment. This is so we can collect data on why they aren't prescribing it. 

As in the first encounter, this falls under the medication distribution sub-activity because that is where it makes the most sense clinically. 

REMINDER: this is only populating for patients who have been previously diagnosed with chronic or gestation diabetes. 

Here is the screen for hypertension: 

<img width="248" alt="Screen Shot 2022-04-27 at 4 12 35 PM" src="https://user-images.githubusercontent.com/77505464/165623235-0d141518-db4a-45ca-aeca-b6edca96e42a.png">

## Design Files: 
- You can see the design file for ANC @ Health Centers in Figma [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=351%3A26645) 

## To Do: 

- Create the logic for continued hypertension 
- Style screen per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

1. At #226, we have this under Treatment Review section, but I don't see any relation to it. Why is it there?
2. At first encounter we had 3 treatment options (only Methyldopa). Here we have additional 2. Why do we have them only at subsequent encounter?
3. Hypertension can be diagnoses straight away, or after BP recheck. The design is only for first option. What about the second? What values should we display?
4. Please define `recommended medication regimen`. I know that is we used to give 2 times a day, we suggest 3. If were giving 3 times a day, we suggest 4. What about all other options? Maybe we just do not recomment anything. If we do what should the text say?
5. Question `Is this the recommended dose` is not needed. It derives from the selection above it.

**Comment by jeanette-pelizzon** [comment]
1. This issue is for the next steps that are derived from the questions we ask in #266. The adherence to the medication will affect how a health care worker moves forward in prescribing things. 
2. It's a clinical thing. They give methyldopa and if the condition doesn't respond then they move up certain levels or switch to the other medicine. 
3. If they are being diagnosed for the first time with something it should follow the same flow as the first encounter. The only thing that is different in the subsequent encounter is that we are checking adherence to medication and then adjusting if they are still hitting any of the markers for hypertension - whether that be that we can diagnose immediately or have to wait for labs to return. 
4. + 5.  We will need to consult @leowea on this. I believe there was a clinical reason for the recommendation and the follow-up question but am unsure as to why. 

// @anvmn @adamhstewart

**Comment by jeanette-pelizzon** [comment]
@anvmn reviewed notes and updated the main issue for clarity.

**Comment by leowea** [comment]
@jeanette-pelizzon Hi! Just checking- do you need anything from me on this?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

This is what I see at logics file:
![Selection_752](https://user-images.githubusercontent.com/17882245/168972088-9f0b3d2c-8500-4f6a-a8ad-5e2a38d51146.png)
![Selection_753](https://user-images.githubusercontent.com/17882245/168972104-2cd4c7a9-2b0f-45e1-83a4-a893d27c0539.png)

1. > previously diagnoses with Hypertension + Diagnosed again with hypertension + **Treatment review: No adverse effects** 

What do we do if there were adverse effects?

2. It is not clear to me what go up by one / two dosed mean.
Please fill following table:

| Current Medication        | Medication after +1 dose           | Medication after +2 doses  |
| ------------- |:-------------:| -----:|
| Methyldopa (250mg): by mouth 2x a day     |  |  |
| Methyldopa (250mg): by mouth 3x a day     |  |  |
| Methyldopa (250mg): by mouth 4x a day     |  |  |
| Carvedilol (6.25mg): by mouth 2x a day     |  |  |
| Amlodipine (5pmg): by mouth 1x a day    |  |  |

**Comment by jeanette-pelizzon** [comment]
2. Here is the table I have from Wendy. (A titration is a dosage level)

<img width="866" alt="Screen Shot 2022-05-18 at 10 46 53 AM" src="https://user-images.githubusercontent.com/77505464/169070403-908e54bb-76b1-4e79-8802-d47059faa571.png">

1. I will have to ask today.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

So, if I fill that table, I still got blanks:

| Current Medication        | Medication after +1 dose           | Medication after +2 doses  |
| ------------- |:-------------:| -----:|
| Methyldopa (250mg): by mouth 2x a day     | Methyldopa (250mg): by mouth 3x a day | Methyldopa (250mg): by mouth 4x a day |
| Methyldopa (250mg): by mouth 3x a day     | Methyldopa (250mg): by mouth 4x a day | Carvedilol (6.25mg): by mouth 2x a day  |
| Methyldopa (250mg): by mouth 4x a day     | Carvedilol (6.25mg): by mouth 2x a day  | Amlodipine (5pmg): by mouth 1x a day |
| Carvedilol (6.25mg): by mouth 2x a day     | Amlodipine (5pmg): by mouth 1x a day | ??? |
| Amlodipine (5pmg): by mouth 1x a day    | ??? | ??? |

What do we do with ???

**Comment by jeanette-pelizzon** [comment]
@anvmn 

So you will never stop taking Methyldopa, you add on the others. I made this table that outlines how the medication should work. If they are taking the maximum dose and are still having blood pressure that is telling us to up the dose then they should be sent to the hospital because this means they are very, very, very ill. It seems from conversation with Wendy and Valens that this is rare but technically could happen. 


<img width="993" alt="Screen Shot 2022-05-19 at 10 34 34 AM" src="https://user-images.githubusercontent.com/77505464/169322698-931f4560-1d8b-44e1-b73b-c930a4ed7a1e.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

OK, That is clear.

Now, getting back to `previously diagnoses with Hypertension + Diagnosed again with hypertension + Treatment review: No adverse effects`, were there any clarifications on what heppens when ther was an adverse event?

Also, I see a contradiction in `Diagnosed again with hypertension` part and the requirements:
![Selection_755](https://user-images.githubusercontent.com/17882245/169386663-61d37355-22a3-429e-8047-6888d6cfdf01.png)

`If blood pressure is < 140 systolic and < 90 diastolic (independent #s)` would not trigger even a suspect for Hyhpertension.
`If blood pressure is >=140 to <=159 (systolic) and >=90 to <=99 (diastolic) (independent #s)` would require taking another measurement after 2 hours, and so would diastolic part at `If blood pressure  is >=160 to <= 179 (systolic) and >=100 to <=109 (diastolic)`.

So maybe it should be just  `previously diagnoses with Hypertension + Treatment review: No adverse effects`?

**Comment by jeanette-pelizzon** [comment]
(1) adverse effects - can we talk about on Monday with Adam. There was feedback about this but I am unsure what makes sense to do technically. 

(2) if the numbers are <90 and <140 -- that's good! That means the medicine is working and that's why they will continue on their current dosage level if their numbers are below 90 and 140. 

I need to follow up with Wendy to see if we need to still do the 2- hour wait if someone has already been diagnosed. I will send an email and try and get you an answer ASAP. 

We do need to know the numbers and have that in the logic to determine if thier dosage level is staying the same, going up +1, or going up +2. 

// @anvmn

**Comment by leowea** [comment]
@jeanette-pelizzon No need to do the 2-hour wait once hypertension has been diagnosed!

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. According to the logic at 160/100 blood pressure the dosage level should be raised by two dosage levels.

Blood pressure|Next steps|Logic
-|-|-
![1-blood-pressure-160-100](https://user-images.githubusercontent.com/3536805/175495690-f4f70eae-a9f6-4ac0-a2aa-eee8ce9d772f.png)|![2-high-risk](https://user-images.githubusercontent.com/3536805/175495698-275ca91f-44a0-4b55-9f91-70785ebb691c.png)|![3-logic](https://user-images.githubusercontent.com/3536805/175496329-1466b7c7-fd3e-43c3-aa74-993975592d7b.png)

2. A space is missing when dosage level should be raised.
![8-missing-space](https://user-images.githubusercontent.com/3536805/175497869-73840a4b-6c2c-47f9-81e6-c0ff5e03611e.png)

3. Logic per google sheets describes 'and' conditions for blood pressure measurements. What should happen when systolic and diastolic measurements fall into different categories?

For example if blood pressure is 135/99, according to systolic logic, current medication should be continued.
According to diastolic logic, medication should be raised by 1 dosage level.
![13-contradiction](https://user-images.githubusercontent.com/3536805/175500428-2aa7746c-779b-4416-968f-2d1f217aa245.png)
With 141/89 blood pressure the displayed text recommended to raise medications by 1 dosage level.
In both cases systolic conditions took precedence over diastolic conditions. Is that ok?

Blood pressure|Next steps
-|-
![16-bp-135-99](https://user-images.githubusercontent.com/3536805/175501392-21e8cab0-2477-4d76-82d6-144ed78f89db.png)|![17-meds](https://user-images.githubusercontent.com/3536805/175501398-09fe0d45-485a-49f8-a086-5d9bfdd89055.png)
![14-bp-141-89](https://user-images.githubusercontent.com/3536805/175501439-64546f9e-fc46-4290-a6a7-5561651ae2d6.png)|![15-meds](https://user-images.githubusercontent.com/3536805/175501446-4acf2260-3c34-4f51-b34c-455f1a883077.png)

4. When patient should be referred to hospital, text doesn't mention stabilization, while it is included in the logic. See last image below. Is that ok?


### Checked and approved:

1.

Blood pressure|Next steps
-|-
![4-blood-pressure-139-89](https://user-images.githubusercontent.com/3536805/175497211-c5d0dcbc-7a40-49eb-9270-56288cf9c250.png)|![5-meds](https://user-images.githubusercontent.com/3536805/175497218-451270d0-fd41-44aa-b5a1-dbd99cb090c6.png)
![6-blood-pressure-140-90](https://user-images.githubusercontent.com/3536805/175497711-b3caf020-b6e6-4718-920b-fcedd0c94c72.png)|![7-meds](https://user-images.githubusercontent.com/3536805/175497717-0109b2de-fca1-4b61-aeeb-e66810b376ee.png)
![9-bp-159-99](https://user-images.githubusercontent.com/3536805/175498269-4c706364-ff27-49bc-a83e-1b23f0f6e694.png)|![10-meds](https://user-images.githubusercontent.com/3536805/175498282-c190dc47-4a31-4926-a12b-6bf272538b7c.png)
![11-bp-180-99](https://user-images.githubusercontent.com/3536805/175498759-0f07b0e2-2ae3-4aef-8b70-bb18f382bf52.png)|![12-hospital](https://user-images.githubusercontent.com/3536805/175498762-6828b654-307d-4f34-aee2-cfab72984cc3.png)

**Comment by adamhstewart** [comment]
@anvmn please check dosage level on point 1 and fix the grammar in point 2.

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. When patient had hypertension, and in spite of the recommended medication No treatment is administered, the text displayed later on the Medical distribution tab is contradictory. Should we deal with the use case when nurse describes something else than what is recommended? Maybe we can just change wording of 'It is recommended that the medication remain unchanged' to
'Recommended medication:' or similar more general expression.
![18-contradiction](https://user-images.githubusercontent.com/3536805/177176272-af6b6370-f297-4f85-aca4-39e8451e1b47.png)

@anvmn @jeanette-pelizzon Just ran into this related issue.

2. And another typo here:
Recomendatoins should be Recommendations.

![19-typo](https://user-images.githubusercontent.com/3536805/177177105-c1cffb4e-e0ee-445b-a83d-44cb32ddbcd1.png)

**Comment by anvmn** [comment]
@balagan73 

Both points fixed. Please test on nutrition env.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. There are still some typos and grammatical errors.
An apostrophe is missing from the second line:
"The patient's current BP is ..."

4th sentence should be: "It is recommended that the medication is increased one dosage level to ..."

And down should be"recommendations"
![20-typo](https://user-images.githubusercontent.com/3536805/180051781-c3d1c5fc-6aed-4b38-b904-ddfae53be7b8.png)

### Checked and approved:

1. The displayed text now is not contradicting.
![21-medication](https://user-images.githubusercontent.com/3536805/180052065-9c3dbc3b-91da-491c-a07f-ec15245fb535.png)

**Comment by jeanette-pelizzon** [comment]
@Diama1 can you please fix the typos that Zolt has found above. Thanks!

**Comment by anvmn** [comment]
@balagan73 please check that typos were fixed on Nutrition env

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. We are getting there, but the second part of the sentence should be also changed to "...the medication is increased..."

![image](https://user-images.githubusercontent.com/3536805/183843040-91cd88f9-a9f3-41e0-a8a2-596646a45444.png)

**Comment by adamhstewart** [comment]
@Diama1 see points above ^^
