### ISSUE TITLE
ANC Subs Visit - History - Outside Care [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#257]
## Issue 
It is possible that a patient will have gone to another health center and/or received care outside of E-Heza during their pregnancy. They could have been diagnosed with a condition and received medication. We need to document this in E-Heza. To do this, we have added a sub-activity called "Outside Care" under the "History" activity. This sub-activity will follow the "Partner Information" sub-activity. 

The first screen will determine if a patient sought outside care. If so, a series of questions will populate. It is followed by a screen to validate the medication that was prescribed.  This information should then populate in the correct section on the progress report. 
 
One | Two | Three | Four
--|--|--|--
<img width="230" alt="Screen Shot 2022-04-27 at 4 40 24 PM" src="https://user-images.githubusercontent.com/77505464/165627569-7bb97db2-1ef4-449d-8ba7-daa03d446469.png"> | <img width="228" alt="Screen Shot 2022-04-27 at 4 40 31 PM" src="https://user-images.githubusercontent.com/77505464/165627570-af3818f8-1538-4d9a-9316-274c2961623e.png"> | <img width="253" alt="Screen Shot 2022-05-17 at 12 47 31 PM" src="https://user-images.githubusercontent.com/77505464/168866117-46ddb266-e01f-4c93-9683-254445f9d926.png"> | <img width="264" alt="Screen Shot 2022-05-19 at 7 44 11 PM" src="https://user-images.githubusercontent.com/77505464/169421815-e569f5f6-fdfa-48e9-a7d0-d4f528291537.png">

## Design Files: 
- You can see the Figma file for ANC @ Health Centers [here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021). 

## Supporting Documents
- You can view progress report placement for various conditions via the Logic Master [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493). 

## To Do: 
- Create Outside Care subactivity 
- Style screens per design 
- Update logic for to update the progress report

**Comment by anvmn** [comment]
@jeanette-pelizzon 

1. Subsequent encounter introduces new set of diagnoses. Shouldn't they appear as well?
2. There can be multiple diagnoses selected, therefore, the medication form needs to reflect this.
3. Will be there a separate issue for presentation at Progress report?
4. Effort estimation for this is 12h. If you dont plan separate issue for Progress report, add another 4.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Subsequent encounter introduces new set of diagnoses. Shouldn't they appear as well?

Per our meeting yesterday, we present only the set of diagnoses that appear at design.

> There can be multiple diagnoses selected, therefore, the medication form needs to reflect this.

I'll make this similar to Medication distribution activity, where we stack medications for multiple diagnoses.
When there's only one option for medication (like HIV for example, will make it Yes/No question).

> Will be there a separate issue for presentation at Progress report?

Please open separate issue with detailed requirments for presentation.

**Comment by jeanette-pelizzon** [comment]
@anvmn after talking with wendy there have been changes made to this. 

1. Screen 3 has been updated 
2. Stacking sounds like a good idea. 
3. #268 is the exsisting progress report issue

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Screen 3 has been updated

'None of these' also needs to be removed (because partient decalred there was new diagnsis).

> Stacking sounds like a good idea.

Please provide one example of how stacking should look.
Also, from my analysis, there are 5 diagnoses we can get medications for:

- Hypertension
- Malaria
- Syphilis
- HIV
- Anemia

We have design for Hypertension - seems to me that Carvedilol and Amlodipine should also appear there.
It's pretty clear to me what Malaria and Syphilis should look like.
For HIV and Anemia however, there's no selection. Would it be enough to ask if HIV / Anemia medications were perscribed (Yes / No question), or should it be something else?

> https://github.com/TIP-Global-Health/eheza-app/issues/268 is the exsisting progress report issue

I don't see any requirements for Outside care there.

**Comment by jeanette-pelizzon** [comment]
(1) None of these means that they were diagnosed with something not on this list. Since we are trying not to have health care workers type in we are just having the "none of these" check box there for data keeping purposes. 

(2) I will have to work on these screens today and get back to you

(3) outside care is giving a new diagnosis from that list. we already have progress report instructions for all those diagnoses. I'm confused what else you need here?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> (1) None of these means that they were diagnosed with something not on this list. Since we are trying not to have health care workers type in we are just having the "none of these" check box there for data keeping purposes.

In this case, I suggest we use `Other`.

> (3) outside care is giving a new diagnosis from that list. we already have progress report instructions for all those diagnoses. I'm confused what else you need here?

From #268 description - `The wording follows a template of Diagnosis + Complications (if any) + Action Taken + Date.`

We have diagnosis, don't have complications, have action only for the ones that were possibly treated with medicine, and don't have date. So, what do we do about missing data?

**Comment by jeanette-pelizzon** [comment]
(1) Other works for me. 

(2) I would say in this case we tweak it a bit to be 

_diagnosis + diagnosed by outside care + medication given (if any) + added to patient record on XX/XX/XXX_ 

Example: Malaria diagnosed by outside care and treated with Coartem added to patient record on 10/07/2021

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Other works for me.

I'm now thinking, maybe we need to make it Others, as there may be more than one.

>  I would say in this case we tweak it a bit to be ...

Looks good to me. Lets add these requirements to #268.
What would you like to present if Other(s) was selected?

So far, #268 was about 11 new diagnoses that were intruduced by subsequent visit.
Now we want it to support another 18 diagnoses from outside care.
We need to develop the logic to pull data from Outside Care activity, and present it.
Please add 4h to #268 estimation.

**Comment by jeanette-pelizzon** [comment]
> @jeanette-pelizzon
> 
> > Other works for me.
> 
> I'm now thinking, maybe we need to make it Others, as there may be more than one. 

**It makes more sense to just be other in English because that can mean 1 other or multiple**
> 
> > I would say in this case we tweak it a bit to be ...
> 
> Looks good to me. Lets add these requirements to #268. What would you like to present if Other(s) was selected?

 **if other was selected I think we can just say in medical diagnosis** 

**Received a diagnosis from a different health care facility  - please follow up with patient** 

> 
> So far, #268 was about 11 new diagnoses that were intruduced by subsequent visit. Now we want it to support another 18 diagnoses from outside care. We need to develop the logic to pull data from Outside Care activity, and present it. Please add 4h to #268 estimation. 

**DONE**

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Are these only options for Hypertension, or they could get Methyldopa 4x + other medicine(s), as per 
https://github.com/TIP-Global-Health/eheza-app/issues/256#issuecomment-1131799771?
![Selection_756](https://user-images.githubusercontent.com/17882245/169392143-5b054a5b-2f1f-4266-aabb-a83851b0ca30.png)

**Comment by jeanette-pelizzon** [comment]
I don't know how common it would be that they get the higher doses elsewhere but perhaps so let's include them for continuity at the very least. 

<img width="264" alt="Screen Shot 2022-05-19 at 7 44 11 PM" src="https://user-images.githubusercontent.com/77505464/169421724-c835af8d-2af6-4f01-bc2b-bc24df355782.png">

I will update the image in the main screen. 

Do you need screens for the other diagnosis with meds or can this be a template? Let me know.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Do you need screens for the other diagnosis with meds or can this be a template?

I need the ones of HIV and Anemia.

**Comment by jeanette-pelizzon** [comment]
@anvmn 

Screens below. The checkboxes should be able to have multiple selected so that the health care worker can choose the right combination of medication that the patient is receiving. 

Hypertension (updated) | Anemia | HIV
--|--|--
<img width="297" alt="Screen Shot 2022-05-23 at 5 33 27 PM" src="https://user-images.githubusercontent.com/77505464/169909469-5d504316-4ce0-462e-aa37-3780281b2546.png"> | <img width="297" alt="Screen Shot 2022-05-23 at 5 33 31 PM" src="https://user-images.githubusercontent.com/77505464/169909471-e859acad-3b27-4b38-830d-33f3bd114f71.png"> | <img width="293" alt="Screen Shot 2022-05-23 at 5 33 36 PM" src="https://user-images.githubusercontent.com/77505464/169909472-7caee0d2-da56-45e1-a650-77e9b64ac1cb.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Well, this will require a considerable rework. So far we had single selection everywhere. Supporting multiple selection alone will require additional 4h.
Also, we have some new options that are not perscribed at our APP - additioanl variant of Iron, Lamivudine and Tenofovir.
After seeing these changes, I'll have to ask you for designs for Malaria and Syphilis, and please mention if there should be single or multiple selection on these forms.

**Comment by jeanette-pelizzon** [comment]
New screens per our call today. Please note HIV has been updated. All should be multiple choice. 

Malaria | Syphilis | Hypertension (Updated) | Anemia | HIV (Updated)
--|--|--|--|--
<img width="226" alt="Screen Shot 2022-05-24 at 2 34 55 PM" src="https://user-images.githubusercontent.com/77505464/170107916-3937b552-997d-4134-9171-074ca367f68a.png"> | <img width="226" alt="Screen Shot 2022-05-24 at 2 34 52 PM" src="https://user-images.githubusercontent.com/77505464/170107922-83f6c3b8-c7c8-4279-964d-2866bb2ae7b4.png"> | <img width="228" alt="Screen Shot 2022-05-24 at 2 33 14 PM" src="https://user-images.githubusercontent.com/77505464/170107925-d19f64b0-dd9f-4463-be8a-49f50a63206e.png"> | <img width="227" alt="Screen Shot 2022-05-24 at 2 33 19 PM" src="https://user-images.githubusercontent.com/77505464/170107929-aa966b20-1f66-47bc-8cde-40f35dd95397.png"> |<img width="228" alt="Screen Shot 2022-05-24 at 2 34 44 PM" src="https://user-images.githubusercontent.com/77505464/170107933-763bf144-cd68-4aa1-a709-a7a6980481d4.png">



// @anvmn  @adamhstewart

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Questions:

1. Wording for some diagnoses is a bit different from design. Is this OK?
![1-diagnoses](https://user-images.githubusercontent.com/3536805/175312681-037962ee-ad98-47a5-a96a-47a7325f0231.png)

2. Moderate is misspelled as mederate:

Typo1|Typo2
-|-
![8-typo](https://user-images.githubusercontent.com/3536805/175315771-8745aa0a-285d-4e94-a31e-4263d6642ad3.png)|![10-typo](https://user-images.githubusercontent.com/3536805/175315809-cf9f59d2-ae9a-4b90-8e4c-4df08523b661.png)

3. While both chronic and gestational hypertensions display medications, only the mild to moderate anemia displays them. Severe anemia doesn't display the Were you given medicine question. Is that OK?
![11-severe-anemia](https://user-images.githubusercontent.com/3536805/175316259-f58b2f62-10f1-4c56-a04a-abfcd10225df.png)

### Checked and approved:

1. Outside care displays under History.  When the option of new diagnosis is selected, HIV, Syphilis, Malaria, Mild to Moderate Anemia, Chronic Hypertension, Gestational Hypertension trigger display of Were you given medicine? question.

Malaria|Syphilis|Hypertension|Anemia|HIV
-|-|-|-|-
![3-hypertension-medication](https://user-images.githubusercontent.com/3536805/175315141-36d42fb0-02cb-499a-9b39-e9c2b778e098.png)|![5-malaria](https://user-images.githubusercontent.com/3536805/175315174-0bd579ec-3f9b-449a-86d7-bd0d5dee7f67.png)|![6-syphilis](https://user-images.githubusercontent.com/3536805/175315182-9f892318-d669-43dd-b0dc-18a24f69adab.png)|![7-mild-anemia](https://user-images.githubusercontent.com/3536805/175315187-e4216b28-bcf2-46b3-8c26-cd5ceae4a51f.png)|![9-HIV](https://user-images.githubusercontent.com/3536805/175315198-055b4f71-0231-4f0d-87fa-74f0c0275407.png)

**Comment by adamhstewart** [comment]
> Severe anemia doesn't display the Were you given medicine question. Is that OK?

My understanding is that this is incorrect

@anvmn can you please check?

also can you fix the spelling and the rephrasing from design?

**Comment by anvmn** [comment]
@adamhstewart 

> can you please check? 

There's no medication treatment for severe Anemina.
![Selection_872](https://user-images.githubusercontent.com/17882245/175467887-510dd9ad-156a-4e4c-82a0-1bd326d2fa12.png)



> can you fix the spelling and the rephrasing from design?

These diagnoses are displayed throughiut the APP, and it seems to me that we better have common label.
@jeanette-pelizzon can we remain with what we have right now, or we need to have special name for some of diagnoses on Outrside care activity?

**Comment by jeanette-pelizzon** [comment]
as we discussed, it should be whatever is a possible diagnosis in the app. Thanks!

**Comment by anvmn** [comment]
@balagan73 

Please retest point 2 from you QA review

**Comment by balagan73** [comment]
@jeanette-pelizzon FYI I have updated #268 issue requirements with outside care info.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. There was a problem with HIV medication in the report. I have noted it here https://github.com/TIP-Global-Health/eheza-app/issues/268#issuecomment-1179134557 but that issue will take some time to QA, so I also make a note here.

### Checked and approved:

1. Typo was fixed, now it is Mild to moderate anemia.
![12-moderate-fixed](https://user-images.githubusercontent.com/3536805/178918329-8ddc179c-7a48-4736-8fbe-653dfbf8eeb7.png)

**Comment by jeanette-pelizzon** [comment]
Thanks @balagan73 we can tackle that problem in the issue you linked. I'll move this to client acceptance.
