### ISSUE TITLE
ANC Subs Visit - Case Management - ANC Labs [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#259]
## Issue 

We now have lab results that are typically not returned during the 14-day window that we have set up for case management. We need to change this cut-off point to 35 days as it often takes a month to have some test results returned to the health center. 

## To Do: 
- Change the logic from 15 days to 35 days

**Comment by anvmn** [comment]
@balagan73 

Deployed to Nutrition env. Please test.

**Comment by jeanette-pelizzon** [comment]
@balagan73 has this been QA'd?

**Comment by balagan73** [comment]
@jeanette-pelizzon Yes, sorry, somehow I have lost my comment. Will enter it again.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Not sure what is meant by cut-off point. If I change back the date on the Prenatal encounter to 128 days before today, the Case management still enables me to enter Lab results. 
![2-100-days](https://user-images.githubusercontent.com/3536805/178024309-655a5375-1ca5-4787-a67e-ff04f940c4ab.png)

Or when I am entering the lab results and I specify that the test date was not today (8th of July), I am able to select the date 30 days before today, not 35. @anvm @jeanette-pelizzon Please let me know if I misunderstood the task.
![30-days](https://user-images.githubusercontent.com/3536805/178024205-e0d34941-fd75-40b0-a23a-722527d073ae.png)

**Comment by jeanette-pelizzon** [comment]
@balagan73 when a user goes through an ANC visit and says they ran a lab test they should have 30 days from that day to input the results. If they do not, we close it out automatically. Based on your comment, it seems that's not happening. Tagging @anvmn to take a look.

**Comment by anvmn** [comment]
@balagan73 

> Not sure what is meant by cut-off point. If I change back the date on the Prenatal encounter to 128 days before today, the Case management still enables me to enter Lab results

What controlls this is not the date of encounter, butfield of Prenatal Labs Results content type.
It's created when laboratory test is executed and pending results. 'Date concluded' is an 'expiration' field, after which, it's entry at case management is hidden.
No matter what previous date for test is set, we count 35 days since Prenatal Labs Results entry was created.

> , I am able to select the date 30 days before today, not 35

Changed this to 35 at [e3e50fa](https://github.com/TIP-Global-Health/eheza-app/pull/329/commits/e3e50fa4a123fd97478acf362fc9c98f70745cf1), though per answer above, this will not affect the logic.

**Comment by anvmn** [comment]
@balagan73 please test on nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. When Date concluded field of Prenatal labs results content type is changed back to the day before today, the Pending tests disappear from case management.
![image](https://user-images.githubusercontent.com/3536805/180043968-f6c40f68-30f6-4f39-b08a-2388a4b37d2d.png)
