### ISSUE TITLE
ANC Subs Visit - Immunization Activity [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#261]
## Issue 

We are adding in an immunization activity into the ANC subsequent encounter. It will come before the Lab activity. It will have the same structure as the immunization activity in SPV. However, the only immunization is tetanus. I will make a separate activity for the Tetanus immunization sub-activity. 

## To Do :
- Create architecture for Immunization Activity

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Why is it added to subsequent encounter only?
Shouldn't we do it at first nurse encounter?

**Comment by jeanette-pelizzon** [comment]
We can check with @leowea but, so far, it has only been talked about in the context of the subsequent visits.

**Comment by leowea** [comment]
@jeanette-pelizzon Sorry about this- we noted it later, but it should be a part of the ANC process beginning with the first encounter. // @anvmn thanks for catching this!

**Comment by anvmn** [comment]
@balagan73 

Deployed to Nutrition env. Please test.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. The immunizations activity only displays when patient is pregnant. It sounds logical, but I couldn't find any info about it in the Logic Master google sheet. Is this OK?

![3-immunizations](https://user-images.githubusercontent.com/3536805/177927555-170b3852-6e5a-4b8f-9298-e881297a9b5d.png)

### Checked and approved:

1. Immunizations displays before the Laboratory activity. Currently it only holds the Tetanus subactivity.
![4-tetanus](https://user-images.githubusercontent.com/3536805/177927698-10e7a824-4cbb-45fe-9f57-9dbc1304f8b1.png)

**Comment by jeanette-pelizzon** [comment]
@balagan73 yes it should only appear if a patient is pregnant. Moving this to acceptance testing. Thanks!
