### ISSUE TITLE
ANC Subs Visit - Next Steps - HIV [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#264]
## Issue 
If we diagnosed a patient with HIV in a previous ANC visit, we will run an HIV PCR test on them at each subsequent ANC visit. The goal is to track their HIV viral load throughout their pregnancy to ensure that it is undetectable by the time they are 36 weeks so that they do not pass on HIV to their baby during delivery. 

It takes a month for the result to return from the lab in Kigali. Once a healthcare worker inputs the results into E-Heza, the next steps will populate (as is normal for ANC).  

If the patient has a viral load under 20, they are considered undetectable and there are no next steps. 

If a patient has a **viral load OVER 20**, these next steps will populate: 

Screen One | Screen Two 
--|-- 
<img width="273" alt="Screen Shot 2022-05-03 at 5 10 11 PM" src="https://user-images.githubusercontent.com/77505464/166567099-dca882b7-22cd-480b-8c43-cd8a04cfc413.png"> | <img width="272" alt="Screen Shot 2022-05-03 at 5 10 19 PM" src="https://user-images.githubusercontent.com/77505464/166567114-5e04421e-acac-42ee-9d2e-325985b1cd14.png">

## Design Files: 
- You can find the design files in Figma [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021) 

## To Do: 
- Create the logic for next steps for HIV PCR results 
- Style screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Since we show a combo for all diagnoses when entering next steps, only first part of popup can be presented.
Maybe we should view that message for second part on the form itself?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

This issue is very much underestimated, because it got extra layers of complexity.
1. Health education is to appear as next step on 'Lab Results' phase of encounter, and right now we don't have it. So, it's not only to expand the form, but add infrastructure to view the task.
2. Health education appears on regular encounter as well, so, similar to medication distribution, this needs to be 2 phase activity, where at each phase we need to take into account what was the state at other phase.

Please update estimation to 6h.

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Should this somehow be reflected on progress report?

**Comment by jeanette-pelizzon** [comment]
@anvmn Yes HIV PCR results should go on the progress report in the same form as the other results so it should be 

HIV PCR -- DATE -- RESULT -- NORMAL RANGE 

Normal Range for HIV PCR = less than 20

**Comment by anvmn** [comment]
@jeanette-pelizzon 

I mean do we need to present detectable viral load / suppressed viral load diagnosis on medical / obstetrical panes?

**Comment by jeanette-pelizzon** [comment]
Yes. They need to see the numbers is my understanding. The goal is to prevent transmission to the baby and the numbers matter for that is my understanding.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. The virus load information is not reflected on the Progress report.
![4-progress-report](https://user-images.githubusercontent.com/3536805/175031456-3b7e248a-f873-4acd-83e7-dd04c8e609b1.png)

### Checked and approved:

1. On subsequent antenatal encounter when the entered virus load is above 20ppm, the expected panels display.

Viral load|Warning|Health education
-|-|-
![1-viral-load](https://user-images.githubusercontent.com/3536805/175031777-844e1b2f-ddec-490b-ab92-bb8baa821983.png)|![2-warning](https://user-images.githubusercontent.com/3536805/175031779-84cfc0a1-6f91-4d0e-8a34-a1ae4af4037f.png)|![3-health-edu](https://user-images.githubusercontent.com/3536805/175031781-99d516cd-c16d-41f2-b282-b074fb124251.png)

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Yes. They need to see the numbers is my understanding. The goal is to prevent transmission to the baby and the numbers matter for that is my understanding.

This is what it looks like right now. Can we keep as is, or need to change to something?

![Selection_865](https://user-images.githubusercontent.com/17882245/175041508-8412e713-1983-4a52-a24c-4f946685efa9.png)

**Comment by adamhstewart** [comment]
@anvmn moving this along because the progress report is in a separate issue

**Comment by jeanette-pelizzon** [comment]
@anvmn yes I think that is fine - if we get feedback from the field that it is confusing we can change it
