### ISSUE TITLE
ANC Sub Visit - Next Steps - Anemia Contd' [1h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#265]
## Issue 

If a patient was diagnosed with Anemia previously in this pregnancy, and they are continuing to meet the logic for Anemia, we continue on with the next steps as outlined in the original logic. There are no changes to the logic - they will not be referred to the hospital or have a dosage changed. 

## To Do
- Ensure the logic is correct for a patient continuing to present as anemic

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> and they are continuing to meet the logic for Anemia

As far as I can tell, this is not possible.
To diagnise Anemia we need Hemoglobin values, but that lab test is done only once.

**Comment by anvmn** [comment]
@adamhstewart This required no special development (as the behavior was to remain as is), so I'm moving this straight to QA column.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Typo on warning popup:

![6-typo](https://user-images.githubusercontent.com/3536805/178027122-dfd6cd4b-cad2-4480-8457-5ce6a7ae39ae.png)


### Checked and approved:

1. When patient fulfills the conditions for mild to moderate anemia repeatedly, they are prescribed the same medicine and not referred to hospital. 

![4-warning](https://user-images.githubusercontent.com/3536805/178026628-f994d813-6bdb-48d8-9a95-0d1514f75fea.png)
![5-next-steps](https://user-images.githubusercontent.com/3536805/178026666-f1cf430c-2ebe-4746-b246-4265e7a8f827.png)

**Comment by jeanette-pelizzon** [comment]
@Diama1 can you please fix the typo in the pop-up? Thank you!

**Comment by anvmn** [comment]
@balagan73 

Please verify that type at popup is fixed.

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. Typo is fixed.
![image](https://user-images.githubusercontent.com/3536805/183280197-4ac6c344-811e-4ddf-bc98-5a8544d403eb.png)
