### ISSUE TITLE
ANC Subs Visit - Next Steps - Syphilis [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#266]
## Issue 

Once a patient tests positive for Syphilis they will always test positive for Syphilis. So if a patient tested positive for Syph earlier in this pregnancy, and we re-test them, they will continue to show as positive. 

We pull the next steps for Syphilis in a subsequent visit from the questions asked during the treatment review section. 

If a patient answers YES to the question "Have you missed any doses?" then this screen will pop up, interrupting the flow. There are no next steps. 

<img width="309" alt="Screen Shot 2022-05-03 at 5 28 49 PM" src="https://user-images.githubusercontent.com/77505464/166569558-d7e4a5ef-7b65-4470-9765-65fa21b50f9e.png">

## Design Files: 
- You can find the design files in Figma [here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021). 

## To Do: 
- Create logic for pop up 
- Style screen per design

**Comment by balagan73** [comment]
As stated here https://github.com/TIP-Global-Health/eheza-app/issues/253#issuecomment-1164160402 the Syphilis medication icon doesn't display under Treatment review. It seems this issue is blocked.

**Comment by anvmn** [comment]
@balagan73 

Please see https://github.com/TIP-Global-Health/eheza-app/issues/253#issuecomment-1164188835

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Next steps option only displays if patient experiences adverse events and they are referred to hospital. See: https://github.com/TIP-Global-Health/eheza-app/issues/284#issuecomment-1165256397

2. Popup displays if Yes is selected for the Have you missed any doses question.

Missed doses|Popup
-|-
![1-missed-doses](https://user-images.githubusercontent.com/3536805/175479928-d67275cd-08e7-4ff6-b407-bb5a23137fdc.png)|![2-popup](https://user-images.githubusercontent.com/3536805/175479937-46d6bfb9-5eff-4b28-84b2-025626f14c72.png)
