### ISSUE TITLE
ANC Progress Report - Labs Section [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#267]
## Issue 

After feedback from the team and users in Rwanda, there are some changes that need to be made to the labs section on the ANC Progress report to make it more user-friendly. 

I have made [this short video ](https://www.loom.com/share/c42ef98c615e45c3a5a2ba8b3ea26711)explaining the changes. 

## Design Files 
- You can access the design files in Figma [here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=468%3A25592). 

- You can click through the prototype [here.](https://www.figma.com/proto/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=468%3A25592&scaling=scale-down&page-id=127%3A13021&starting-point-node-id=463%3A25002&show-proto-sidebar=1)

## To Do: 
- Update the main lab report page to view the high level results 
- Update the main lab report page to show test - date - result - normal range - arrow 
- Update the logic to show an abnormal result in red 
- Update the sub results pages - remember that the urine dipstick page is different

**Comment by anvmn** [comment]
@jeanette-pelizzon 

I need definitions of Normal ranges for some of parameters were present:

1. These 2:
![Selection_843](https://user-images.githubusercontent.com/17882245/174496054-be95013f-5cf0-4768-bb4b-984a9b04958b.png)

2. All of these:
![Selection_842](https://user-images.githubusercontent.com/17882245/174496063-6e5a332c-62c5-4587-8040-794a32e34238.png)

Couldn't find it on logics file.

**Comment by jeanette-pelizzon** [comment]
@anvmn 

The lab info was in a separate document but I just pulled it over to the logic file [here] (https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1285901434) so that we can have everything in one place. There are some that I did some investigating on that I still have questions about and probably fell through the cracks before. They are highlighted in red on the document. Everything is else is good.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Thanks. Follow up quesrtions:

1. I don't understand this range:
![Selection_849](https://user-images.githubusercontent.com/17882245/174656310-a61dbe84-f52d-4b58-a534-80b271a1518c.png)

Is it between 11 and 16.5?

2. This looks strange:
![Selection_851](https://user-images.githubusercontent.com/17882245/174656532-c47cf837-4c54-48ef-a022-ca99f0349ac3.png)

We don't have 4.5 as an option, so only abnormal value is 8.5. Can you confirm please?

**Comment by jeanette-pelizzon** [comment]
Yep, those ones I have asked about so I will hopefully have answers for you soon

**Comment by jeanette-pelizzon** [comment]
I got answers to the questions and have updated the [spreadsheet](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1285901434).

**Comment by anvmn** [comment]
@jeanette-pelizzon 

I still don't see an update for:

![Selection_867](https://user-images.githubusercontent.com/17882245/175091060-bb3dd8e5-a4e8-435a-9077-194c33819e8b.png)

Also, these changes require 2 new issues.
1. Adding new options for PH.
2. Removing special gravity from everywhere it appears.

![Selection_866](https://user-images.githubusercontent.com/17882245/175091567-4a3bbd5c-a261-48e4-92ba-06a942b87a0a.png)

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Also, Protein values are:

0
+1
+2
+3
+4

See https://github.com/TIP-Global-Health/eheza-app/issues/182.

**Comment by jeanette-pelizzon** [comment]
Hemoglobin - normal range is between 11 and 16.5 
Protein - I need to check with wendy what the normal ranges are

ill create those new issues for Ph and removing specific gravity.

**Comment by jeanette-pelizzon** [comment]
confirmed: Protein should be zero as the normal range - unsure if we still have that as an option

**Comment by anvmn** [comment]
>  unsure if we still have that as an option

@jeanette-pelizzon we do have it

**Comment by anvmn** [comment]
@balagan73 

Deployed to Nutrition env. Please test.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Leukocytes is missing from Long dip test, but instead there is two Glucose items.
![1-leukocytes](https://user-images.githubusercontent.com/3536805/177946257-fca5b5cd-bb8b-4764-ba18-c62085caa35e.png)
 
### Checked and approved:

1. Lab result pages look good and adhere to the design.

Hemoglobin|Malaria
-|-
![2-hemoglobin](https://user-images.githubusercontent.com/3536805/177948669-33b7c3e2-b3a0-4a2f-85fc-82e12520d7e3.png)|![4-malaria](https://user-images.githubusercontent.com/3536805/177948685-8cdd2a3e-bf09-47d3-98de-2dd548f75ef2.png)

Lab results1|Lab results2
-|-
![3-lab-results](https://user-images.githubusercontent.com/3536805/177948775-adae3d91-8f7a-45e4-8837-602a34883496.png)|![5-lab-results-good](https://user-images.githubusercontent.com/3536805/177948784-d332fd5f-465f-4107-9db9-134f82f7f6f2.png)

Dipstick long not done:
![6-dipstick-long](https://user-images.githubusercontent.com/3536805/177950746-17ea9331-56d3-4af5-a0b9-0b6b8146678b.png)

Results pending:
![7-results-pending](https://user-images.githubusercontent.com/3536805/177950884-14e73aa0-3880-4d79-923b-d9f77f733a5d.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn perhaps there is a typo? This is the list from design: 
<img width="161" alt="Screen Shot 2022-07-08 at 10 14 30 AM" src="https://user-images.githubusercontent.com/77505464/178020976-a396becd-c24d-4264-bd0d-43b988f43b1a.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> @anvmn perhaps there is a typo?

Indeed. Fixed at [3b6f703](https://github.com/TIP-Global-Health/eheza-app/pull/329/commits/3b6f703a4dbc7c69b97c42cbc36f1e7096d8ca98).

**Comment by anvmn** [comment]
@balagan73 please test on nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Now there is only one Glucose entry, and Leukocytes display.

![8-leukocytes](https://user-images.githubusercontent.com/3536805/180047732-fba361bd-1d20-429f-9347-574f43ac1620.png)
