### ISSUE TITLE
ANC Subs Activity - Immunization - Tetanus [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#269]
## Issue 
During pregnancy, we need to ensure that a woman is up to date on her Tetanus immunization. Tetanus immunization is a series of 5 shots - see the logic below. 

Following the immunization flow that we set up in SPV, we will ask the healthcare worker to input the dates of past Tetanus immunizations (if any). Then we verify that the patient has received all 5 in the series. If she has not, we will give her one (if it's not too soon in the logic). We will only ask if they received the booster in the last ten years if they have received all 5 shots.

**Logic:** 
<img width="684" alt="Screen Shot 2022-05-04 at 1 41 13 PM" src="https://user-images.githubusercontent.com/77505464/166747644-6064a1cd-0685-445e-bf1a-7b4fc0f17fa6.png">

Screen One | Screen Two | Screen Three | Screen Four 
--|--|--|--
<img width="297" alt="Screen Shot 2022-05-04 at 2 22 58 PM" src="https://user-images.githubusercontent.com/77505464/166800996-9c480902-71d3-4651-b472-e372bfdfd9a5.png"> | <img width="299" alt="Screen Shot 2022-05-04 at 2 23 04 PM" src="https://user-images.githubusercontent.com/77505464/166800999-332f7366-ac07-442c-8fe5-2baec234408e.png"> | <img width="296" alt="Screen Shot 2022-05-04 at 2 23 19 PM" src="https://user-images.githubusercontent.com/77505464/166801001-c6db200e-7a38-41fe-bf69-fb88f5a580fc.png"> |<img width="297" alt="Screen Shot 2022-05-04 at 2 23 26 PM" src="https://user-images.githubusercontent.com/77505464/166801002-49fc515b-5870-42de-b112-94088b6b65a0.png">

## Notes: 
- Patient will never receive more than 5 Tetanus immunizations 
- If the booster is over 10 years, but the patient has received all 5 immunizations, they will NOT get another one. 

## Design Files: 
- You can access the design in Figma [here.](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021) 
- You can find the Tetanus icon [here](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=201%3A28) on the icon page

## To Do: 
- Create logic for Tetanus vaccine 
- Style screen per design (refer to previous immunization activities for more detailed flow information if needed)

**Comment by anvmn** [comment]
@jeanette-pelizzon 

I looked through designes at Figa, and I don't see all possible pathes.
I don't see how previous dates of vaccines are viewed and updated, and how we record that vaccination was given today.
We did have something similar for SPV, however, here we ask some additional question, so it's not clear to me how this all shoul look when combined together (not mention that QA person that may not have an idea at all).

Also, it's not clear to me why we need to show this activity if we have on record that patient already got all 5 doses, and why we need these 2 questions - don't we have the answers already if we see the history of given vaccinations and thier dates?

![Selection_801](https://user-images.githubusercontent.com/17882245/172340872-69222735-e996-454a-b1fa-6c1d39ba8071.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn made changes to flow in Figma. You can see it [here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A13021) and it is labeled example immunization flow. 

I have also made a [quick video](https://www.loom.com/share/e7d69a47ca3e4b6a9f8ef8d98e60b7d9) walking through that is hopefully helpful.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

At well child, we have a helper text on form that provides explanation when vaccination should be administered:

![Selection_836](https://user-images.githubusercontent.com/17882245/173794771-47e82ae1-755f-4d20-8ff2-68d9dc5caa3d.png)

Do we need one for tetanus as well?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

When describing intervals between vaccinations, there's `or during subsequent pregnancy` part.
With current data set we collect, there's no way of knowing this for sure.
I mean we know for sure, if we recorded that shot was given during one of previous encounters at current pregnancy, but if it was not, we still can't be sure it was not given.
How do we handle this?

//cc @adamhstewart

**Comment by jeanette-pelizzon** [comment]
@anvmn no I don't think we need that text here. We put the helper text on SPV because it was a request from the mom's since they are having the nurse explain to the mom/caregiver why they give the vaccine and how often a kid should get it.

**Comment by jeanette-pelizzon** [comment]
@anvmn @adamhstewart we will have to ask Valens/Wendy about the subsequent pregnancy thing. I will get back to you!

**Comment by jeanette-pelizzon** [comment]
I got the answer for this so the tetanus vaccine is given in the prescribed increments so shot number 5 will be a year after shot number 4 UNLESS a patient is pregnant in which case we give them the tetanus vaccine. The patient will only ever receive a course of 5 tetanus shots in their lifetime. So it's either the prescribed time  after their previous shot or during their next pregnancy (whichever comes first) until they hit the 5 shot limit. 

Hope that helps @anvmn

**Comment by anvmn** [comment]
@balagan73 

Deployed to Nutrition env. Please test.

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. Tetanus screens

No-No|Today|Prior
-|-|-
![1-no-no](https://user-images.githubusercontent.com/3536805/177762150-34c6cac8-292f-4e3a-b81c-2298614eef9d.png)|![2-today](https://user-images.githubusercontent.com/3536805/177762166-4aa7573e-cdd2-4e0f-bafa-f03ab831b6b9.png)|![3-prior](https://user-images.githubusercontent.com/3536805/177762169-915cdb6b-032a-4ba8-ba40-f76c971bcb12.png)

History|History2
-|-
![4-history](https://user-images.githubusercontent.com/3536805/177763525-84bd797c-ba11-45c5-a2d6-c8db7ebff2ab.png)|![5-history](https://user-images.githubusercontent.com/3536805/177763462-db77fd09-0042-4578-8c75-9b3b5cd4a2b5.png)
