### ISSUE TITLE
ANC Subs Encounter - Lab Results - HIV PCR [3h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#270]
## Issue 

After we take the HIV PCR lab (#260), we need to enter the results in the next steps. This follows the same flow as the first ANC encounter.  The results are numerical and the user will need to put in the numbers using the native keyboard on the device. The numerical option is then followed up by the question to verify if the result is below 20 copies. That would mean that the virus level is undetectable which comes into play in Next Steps (#264).

Screen One | Screen Two 
--|-- 
<img width="296" alt="Screen Shot 2022-05-04 at 2 57 23 PM" src="https://user-images.githubusercontent.com/77505464/166806593-a747ff62-1542-47a5-822a-4e7eb37ff21a.png"> | <img width="296" alt="Screen Shot 2022-05-04 at 2 57 33 PM" src="https://user-images.githubusercontent.com/77505464/166806594-50fd9ce6-0118-49d9-b99a-6afc5d9b906b.png">

## To Do: 
- Create Lab results activity
- Style screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Why do we have this question?

![Selection_741](https://user-images.githubusercontent.com/17882245/168483501-ad7d1a23-0e5c-44dd-984c-7d12773f5236.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn it's a clinical thing. If it is below <20 copies then the viral load is undetectable and there are no next steps. If it is above the 20, the pop-up for them needing to follow strict PMTCT protocols comes up. This is also setting us up to have more in-depth HIV activity in the future.

**Comment by anvmn** [comment]
@jeanette-pelizzon

We have input where nurse type the exact value.
Why do we need another question?

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Should this somehow be reflected at Labs section of Progress report?

**Comment by jeanette-pelizzon** [comment]
> @jeanette-pelizzon
> 
> We have input where nurse type the exact value. Why do we need another question?

Yes, because the report the nurse gets just says below 20 but not the exact number. So they can put a number in above 20 or they will hit the button that the viral load is under 20.

**Comment by jeanette-pelizzon** [comment]
> Should this somehow be reflected at Labs section of Progress report?

Yes, it should follow the same format of the others. The normal range for HIV PCR is less than 20 copies.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Question: Can we display superscripts where needed?
![3-superscript](https://user-images.githubusercontent.com/3536805/175259284-cfe50e8c-3c2d-4448-8326-2c9f8fd92bbb.png)

### Checked and approved:

1. Result <20 copies/mm3
![1-screen1](https://user-images.githubusercontent.com/3536805/175258741-c743fd4c-a757-4da8-afa0-14a18acb4341.png)

2. Result >20 copies/mm3
![2-screen2](https://user-images.githubusercontent.com/3536805/175258853-3911935a-a81e-438c-b160-c37a0fb0b943.png)

**Comment by adamhstewart** [comment]
> Can we display superscripts where needed?

@balagan73 we can if that's what the design calls for - I don't see that. Am I missing something?

**Comment by adamhstewart** [comment]
seems like this is accepted usage:
![image](https://user-images.githubusercontent.com/688507/175315065-d9cd7caa-000f-4ff2-9692-1f812c78c86a.png)
