### ISSUE TITLE
Patient Record - Family Planning [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#271]
## Issue 

Users requested that we add a Family Planning section to the Patient Record. This page will just show a list of the encounter dates where we asked a patient what method of family planning they are using and then the option they selected. 

Here are the various options that could populate: 
- Auto-observation
- Condoms 
- Cycle Beads
- Cycle Counting
- Hysterectomy
- Implants
- Injectables
- IUD
- Lactation Amenorrhea
- Oral Contraceptives
- Spermicide
- Tubal Ligatures
- Vasectomy
- None of the Above 

Here is what the screen should look like: 
<img width="330" alt="Screen Shot 2022-05-04 at 3 11 51 PM" src="https://user-images.githubusercontent.com/77505464/166809871-a485602f-ef6c-4801-a0f7-9035a8440ca0.png">

## Design Files: 
- You can access the design files in Figma [here. ](https://www.figma.com/file/ar8UMXGjITVnICIAegbtIj/Dashboard-%7C-Progress-Reports-%7C-Etc?node-id=201%3A1089)

## To Do: 
- Create Family Planning section in Patient Record 
- Create logic to pull in answers to populate the family planning screen 
- Style screen per design

**Comment by anvmn** [comment]
@adamhstewart 

I don't think Diane can handle this at current point of time.
It requires loading data from group enconters, which is a complex task, and area Diane never touched before.

**Comment by anvmn** [comment]
@adamhstewart @Diama1 
Taking this over.

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env

Note that family planning activity exists at group encounter (mothers activity) and Antenatal encounter.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Family planning displays under Patient record with previously selected family planning options.

![image](https://user-images.githubusercontent.com/3536805/183422628-e85b06aa-4b52-4b52-ab8b-7032a4132ef5.png)
