### ISSUE TITLE
Patient Record - ANC to Only Appear for Female Patients [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#273]
## Issue 

Currently, in the Patient Record the ANC section is populating for both female and male patients. The team has requested that the ANC section be hidden for male patients. 

## To Do: 
- Update logic for patient record

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Created a new male patient Doe John. When I select him, the Antenatal care is displayed as an encounter type. The Antenatal care is also displayed in the progress reports when selecting the patient.

Male Patient|Patient record|ANC
-|-|-
![1-john-doe](https://user-images.githubusercontent.com/3536805/175304128-0ec3257c-e78f-47c6-a955-0bdc4555ecd5.png)|![2-patient-record](https://user-images.githubusercontent.com/3536805/175304139-dc3586ab-a846-476a-8fc3-48e2ed3e7604.png)|![3-anc](https://user-images.githubusercontent.com/3536805/175304144-0605a4e5-3eda-4191-9c93-95a76f394c4a.png)

**Comment by adamhstewart** [comment]
@anvmn please check. Maybe this isn't on nutrition?

**Comment by anvmn** [comment]
@adamhstewart right, not on Nutrition
It's a Patient Record branch, which is a predecessor on ANC logic, but we did not update it for a while, and therefore, did not pull this change into ANC.

**Comment by adamhstewart** [comment]
@anvmn whats the best place to do QA ?

**Comment by anvmn** [comment]
@adamhstewart Nutrition environment, after we deploy next chunk of code.

**Comment by anvmn** [comment]
@balagan73 

Deployed to Nutrition env. Please test.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Antenatal care still displays for Male patient.
![4-john-doe-male](https://user-images.githubusercontent.com/3536805/177929857-56bbf6db-09bc-4111-a45b-b78761b91697.png)
![5-anc](https://user-images.githubusercontent.com/3536805/177929867-32aeca42-9d76-4698-a297-89cb20fba645.png)

**Comment by jeanette-pelizzon** [comment]
@Diama1 antenatal care should only appear for female patients. 

// @anvmn just FYI

**Comment by anvmn** [comment]
@jeanette-pelizzon @Diama1 

Taking this one over

**Comment by anvmn** [comment]
@balagan73 @jeanette-pelizzon 

> Antenatal care still displays for Male patient.

Fixed at #317

**Comment by anvmn** [comment]
@balagan73 please test on nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. No Antenatal care is available for male patients.
![6-no-anc-for-male](https://user-images.githubusercontent.com/3536805/180137812-0ab17974-ba1b-4fe9-a8a7-f7d55db4de33.png)
