### ISSUE TITLE
ANC Subs Visit - Treatment History - HIV - Logic [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#279]
## Issue 

There are different pathways E-Heza will send a user down based on a patient's answers in the treatment review for HIV medication adherence. 

(1) Patient was referred to a PMTCT program after their initial HIV diagnosis + they did NOT receive medicine from PMTCT = in next steps, we prescribe them medicine as if there was no PMTCT program (the TDF + 3TC and Dolutegravir)

(2) Patient was referred to a PMTCT program after their initial HIV diagnosis + they did receive medicine = continue on with the next screen in this encounter. 

(3) Patient was not sent to a PMTCT program = continue on with the next screen in this encounter. 

(4) Patient is part of a discordant partnership and was prescribed medication previously = continue on with the next screen in this encounter.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> (2) Patient was referred to a PMTCT program after their initial HIV diagnosis + they did receive medicine = continue on with the next screen in this encounter.

I suppose that this is from this green comment:

![Selection_759](https://user-images.githubusercontent.com/17882245/169704033-3595d775-f286-4cf3-9755-ab7e98e122c3.png)

Does this mean that there's nothing we need to do, and just proceed with encounter as ususal?
We do not track medication given by PMTCT program?

Another question:

Consider this flow:

1. Patient was referred to a PMTCT program after their initial HIV diagnosis + they did NOT receive medicine from PMTCT.
2. On subsequent encounter, patien responded that they did NOT receive medicine from PMTCT and was given medicine at HC (per point 1).
3. On next encounter, patient comes in again, asked if they were given medication by PMTCT, answers NO... and is given medicine again??? - **this does not make sence**. Seems to me that decision flow chart above needs updating.

**Comment by jeanette-pelizzon** [comment]
(1) Yes, if they received their meds from PMTCT then, to my understanding, PMTCT is following up with them on all adherence and dosage stuff so we don't need to worry about that.

(2) In this scenario, as I understand it, we would keep giving them medicine because they need to keep refilling their prescription. However, I will need to check with Wendy about how she wants to handle this because if we give them medicine then we should probably pull them out of the PMTCT flow in general so if they ever answer that they did not get meds from PMTCT they come into our care and we are following up with them. I will check with Wendy today and let you know as I am sure this is a complex issue.

**Comment by jeanette-pelizzon** [comment]
@anvmn so if a patient is PMTCT and they come in and have not received medication from PMTCT we will give them medicine and we will make sure they no longer go into any PMTCT flows from then on. Essentially we are moving that patient from PMTCT to our care.

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. During subsequent antenatal encounter, in Examination -> Nutrition assessment the Height field is not displayed, and BMI is not calculated, thus Nutrition assessment cannot be finished, and encounter cannot be ended.
It seems I did not enter data for height at first encounter, but how was I able to end it then?

BMI not calculated|Cannot end encounter
-|-
![6-bmi-empty](https://user-images.githubusercontent.com/3536805/175022474-fe93cea8-a3d3-4d68-9284-7094afb447b8.png)|![7-cannot-end-encounter](https://user-images.githubusercontent.com/3536805/175022480-6b5a44e1-c276-44f0-8526-ac09795761d3.png)


### Checked and approved:

1. 
>_Patient was referred to a PMTCT program after their initial HIV diagnosis + they did NOT receive medicine from PMTCT = in next steps, we prescribe them medicine as if there was no PMTCT program (the TDF + 3TC and Dolutegravir)_

HIV positive+PMTCT|HIV medication|Next steps
-|-|-
![2-hiv-test-positive](https://user-images.githubusercontent.com/3536805/175018159-6c81c998-b887-4c14-8084-3725cba3715b.png)|![1-hiv-medication](https://user-images.githubusercontent.com/3536805/175018174-9619d877-c8ac-4050-8cdd-3119141acb68.png)|![3-next-steps](https://user-images.githubusercontent.com/3536805/175018185-99195309-b23f-4777-9fbe-d8d6f700f1c2.png)

2.
>_Patient was referred to a PMTCT program after their initial HIV diagnosis + they did receive medicine = continue on with the next screen in this encounter.

HIV medication at PMTCT|No next steps
-|-
![4-medication-yes](https://user-images.githubusercontent.com/3536805/175018741-161de950-c904-43db-b0d3-38969c6c2313.png)|![5-no-next-steps](https://user-images.githubusercontent.com/3536805/175018751-8d86ce37-30c7-453a-a18a-f8ef99253075.png)

3.
>_Patient was not sent to a PMTCT program = continue on with the next screen in this encounter.

Not sent to PMTCT program|Next screen
-|-
![10-not-sent-pmtct](https://user-images.githubusercontent.com/3536805/175025391-bdedd707-c606-4c15-acb8-10aba542f12b.png)|![11-next-screen](https://user-images.githubusercontent.com/3536805/175025496-50ee3105-2efa-403b-97cd-1071e740ee0d.png)



4. 
>_ Patient is part of a discordant partnership and was prescribed medication previously = continue on with the next screen in this encounter.

HIV history|Next screen
-|-
![8-hiv-history](https://user-images.githubusercontent.com/3536805/175023718-6491dd3c-6264-4754-a229-977f741341cd.png)|![9-next-screen](https://user-images.githubusercontent.com/3536805/175023725-ecb64d58-e8b6-4396-9a50-865a628508c2.png)

**Comment by adamhstewart** [comment]
> During subsequent antenatal encounter, in Examination -> Nutrition assessment the Height field is not displayed, and BMI is not calculated, thus Nutrition assessment cannot be finished, and encounter cannot be ended.

@anvmn It seems this is related to an issue that @leowea and I encountered while testing yesterday. We thought it might have been related to the photo, but maybe indeed related to a missing height measurement. Can you check to find the root cause that encounters cant be ended?

**Comment by balagan73** [comment]
@anvmn @adamhstewart Not sure, but maybe this whole issue happened because I have suspended encounter to wait for lab results, before correctly filling in the examination forms.

**Comment by anvmn** [comment]
@adamhstewart 

> @anvmn It seems this is related to an issue that @leowea and I encountered while testing yesterday. We thought it might have been related to the photo, but maybe indeed related to a missing height measurement. Can you check to find the root cause that encounters cant be ended?

Logic says that you can complete the econter if all mandatory activities are completed. Photo is only activity that is not mandatory activity.
With new ANC logic, an exception for this was introduced - whenever we have emergency referral, we only need to complete next steps.

Problem with examination nutrition was that in code we were assuming that height measurement was entered on first encountrer. This is no longer valid assumption, therefore, I've modified the logic to explicitly check if heigh was measured already, and if not, present the height input. Fix is at #303.

**Comment by anvmn** [comment]
@balagan73 

Please retest.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. After Pausing encounter, and then updating the lab results via Case management, no height measurement was entered.
At next encounter it is possible to enter height, and then it was possible to end encounter.
![12-height](https://user-images.githubusercontent.com/3536805/178751597-45518f3b-082e-49ba-bf69-a02ba3e01781.png)
![13-ending-encounter](https://user-images.githubusercontent.com/3536805/178754835-54289a1d-d646-4227-9211-76842778daaa.png)
