### ISSUE TITLE
ANC Subs Visit - Treatment Review - Adverse Reaction - Next Steps [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#284]
## Issue: 

If a patient states that they did not take their medicine due to an adverse reaction, we need to have the health care worker decide if they would then like to refer them to the hospital at the end of the encounter. If the adverse reaction is selected as a reason, a boolean question will appear "The patient had an adverse reaction to the medication. Would you like to refer them to the hospital as a next step?" with the possible selection being "Yes" or "No." If they do select "Yes", then we will populate the refer to hospital screen in the next steps. 

<img width="276" alt="Screen Shot 2022-05-24 at 3 34 59 PM" src="https://user-images.githubusercontent.com/77505464/170117874-160748fc-f158-462a-90d5-d42c04051a70.png">

This should be for all applicable diagnoses, including: 
- HIV 
- Anemia 
- Syphilis 
- Hypertension 
- Malaria 
- Anemia 

*We could potentially add in more to this list in the future

## To Do:
 - Add in the conditional question after a yes to adverse events 
 - style screen per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Syphilis:

No adverse effect|Adverse effect
-|-
![1-no-adverse-effect](https://user-images.githubusercontent.com/3536805/175477708-9bcd3e0b-c640-4f03-b0d2-d6389e40e46d.png)|![2-adverse-effect](https://user-images.githubusercontent.com/3536805/175477716-13679f1e-56cf-49a5-b08f-f0fab7ac6237.png)

Refer to hospital Yes| No
-|-
![6-refer-yes](https://user-images.githubusercontent.com/3536805/175478325-4ede6397-0759-436c-8250-ea49fd856ec8.png)|![4-dont-refer](https://user-images.githubusercontent.com/3536805/175478345-6e41a18e-3484-4aeb-a1b3-e4bc2c5054f2.png)
![3-refer-to-hospital](https://user-images.githubusercontent.com/3536805/175478421-6851b162-07ae-4053-9d6b-e89709259f3c.png)|![5-no-next-steps](https://user-images.githubusercontent.com/3536805/175478444-2344001d-a384-4ce4-9374-9876a186dd60.png)

HIV|Malaria|Hypertension|Anemia
-|-|-|-
![7-hiv](https://user-images.githubusercontent.com/3536805/175540933-a48db29e-f499-4455-ac86-ffb3ea90cd41.png)|![8-malaria](https://user-images.githubusercontent.com/3536805/175540939-493efc2c-b0fd-42a2-9ee6-8b2b120db2c7.png)|![9-hypertension](https://user-images.githubusercontent.com/3536805/175540944-e5fdbb4b-3c9e-4a25-9863-9212f51090e1.png)|![anemia](https://user-images.githubusercontent.com/3536805/175540948-44345cd0-c40c-486d-aa5c-6c000a0d12dd.png)
