### ISSUE TITLE
ANC Subs Visit - Maternal Mental Health Activity Infrastructure [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#289]
## Issue 

We are adding a new activity to the ANC Subsequent Visit at the Health Center - Maternal Mental Health. This activity should appear before the Photo activity in the tray. This activity should appear starting at 28 weeks EGA. It only needs to be done once during pregnancy, so once it is completed once it should not appear again. 

Icon SVG can be found in [Figma - Components - Icons](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=201%3A16)
<img width="238" alt="Screen Shot 2022-06-02 at 3 53 45 PM" src="https://user-images.githubusercontent.com/77505464/171726837-db3ba067-1386-42b2-8a5c-36ebfbb8c002.png">

## Related Issues: 
- #290 
- #291 

* Video overview can be found in issue #290

## To Do: 
- Create the infrastructure for the Maternal Mental Health activity

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Maternal mental health icon displays before the Photo icon, if EGA is greater than 28 weeks.

After 28 week EGA|Before 28 week EGA
-|-
![2-maternal-health](https://user-images.githubusercontent.com/3536805/174778167-1114a8ac-c84c-4cf0-a0ca-4fd112539a43.png)|![3-no-maternal-health](https://user-images.githubusercontent.com/3536805/174778190-5bb73cbc-db44-45a4-a97d-8e475a328367.png)

2. The icon doesn't display when the questionnaire was filled out once.
![16-no-icon-when-done](https://user-images.githubusercontent.com/3536805/174787130-2e9f864c-1dbc-469b-945f-6c4db0a37193.png)

**Comment by anvmn** [comment]
@balagan73 

This part needs verification as well: `It only needs to be done once during pregnancy, so once it is completed it should not appear again.`

**Comment by adamhstewart** [comment]
@balagan73 were you able to verify the above ^^

**Comment by balagan73** [comment]
@adamhstewart  Yes, point 2 deals with that part of the issue..
