### ISSUE TITLE
ANC Subs Visit - Maternal Mental Health Logic [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#291]
## Issue: 
Each answer in the Maternal Mental Health Survey has points associated with it. The diagnosis is determined based on the cumulative amount of points a patient has throughout the survey. Essentially, we need to tally up the points. 

All diagnoses will appear in the next steps with the exception of Suicide Risk which should pop up at the final screen of the survey. The pop-up will need to be cleared before the nurse can go on to the next screen. So it doesn't stop the encounter, it just pops up to instruct the nurse to get a mental health professional immediately. Then they should finish the encounter. 

**Depression Not Likely** 
![Depression Not Likely](https://user-images.githubusercontent.com/77505464/171739607-cbd1b545-d36f-418f-91aa-0920e84184f8.jpg)

**Depression Possible**
Screen 1 | Screen 2 | Screen 3
--|--|-- 
![Depression Possible 1](https://user-images.githubusercontent.com/77505464/172690348-a01bf9e6-0f09-4e58-a2e9-ca99952b957c.jpg) | ![Depression Possible 2](https://user-images.githubusercontent.com/77505464/172690349-57e9aac7-b6c2-4db7-a196-e73a72b0bcac.jpg) | ![Depression Possible 3](https://user-images.githubusercontent.com/77505464/172690351-9f9ca36d-9246-4467-8559-4c1e5d7b4f16.jpg)

**Fairly High Possibility of Depression**  
Screen 1 | Screen 2 | Screen 3
--|--|--
![Fairly High Possibility of Depression 1](https://user-images.githubusercontent.com/77505464/172690431-4f83a633-29aa-4e5f-8c53-18e9b0a38490.jpg) | ![Fairly High Possibility of Depression 3](https://user-images.githubusercontent.com/77505464/172690434-0e3db9ff-54e5-4fbe-b193-bce5abbe2336.jpg) | ![Fairly High Possibility of Depression](https://user-images.githubusercontent.com/77505464/172690435-f59d63cb-4a89-401b-82c8-c784e5b7eb37.jpg)

**Probable Depression** 
Screen One | Screen Two | Screen Three
--|--|--
![Probable Depression 1](https://user-images.githubusercontent.com/77505464/172690527-a0b9fb27-e27f-4d9e-bc32-994c3c2849a3.jpg) | ![Probably Depression 3](https://user-images.githubusercontent.com/77505464/172690529-c2d725ee-1afd-425d-8a1d-5e0cb30ff599.jpg) | ![Probably Depression](https://user-images.githubusercontent.com/77505464/172690531-5b8ed946-f9cb-4df1-9709-1eff8e028038.jpg)

 **Suicide Risk** 
Screen One | Screen Two 
--|--
![Suicide Risk 1](https://user-images.githubusercontent.com/77505464/172690616-cb8e72b1-ca79-4620-941b-2eed4bc88a80.jpg) | ![Suicide Risk](https://user-images.githubusercontent.com/77505464/172690619-a5130179-7806-414b-ac32-2579c1169136.jpg) | ![Suicide Risk3](https://user-images.githubusercontent.com/77505464/172690620-859edf12-1f46-44bf-93c0-ceaddf16122e.jpg)

## Logic: 
Logic can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) at the bottom of the ANC tab under Maternal Mental Health heading.

## Related Issues: 
- #289 
- #290 
* Video overview can be found in issue #290

## To Do: 
- Style screens per design (Note: change to wording for mental health referral screen) 
- Logic

**Comment by anvmn** [comment]
@jeanette-pelizzon 

If we have conditional logic at helper text, why do we always refer to hospital?

![Selection_802](https://user-images.githubusercontent.com/17882245/172351415-3a9c9473-c6c8-4afc-b4f8-26daf55b7e2b.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn there is one that does not refer to a hospital and is just health education. The text is different on the mental health referral screens because some health centers may have a mental health specialist on site but if not they will refer to a hospital.

**Comment by anvmn** [comment]
@jeanette-pelizzon
OK, so what should nurse do if there is mental health specialist at health center? Per design she's always shown referral to hospital form.

**Comment by jeanette-pelizzon** [comment]
Updated main issue with new designs for follow ups. 

@anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 

I believe we need to refine these options:

![Selection_825](https://user-images.githubusercontent.com/17882245/173290769-138e2258-a6cd-4522-be9f-a082d8ced9cd.png)

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Should this be reflected at Progress report somehow?
I don't see any definitions for it at logics file.

**Comment by jeanette-pelizzon** [comment]
@anvmn let's just remove the ambulance option and keep the other three.

**Comment by jeanette-pelizzon** [comment]
@anvmn got an answer for this. 

On the progress report, this result should appear under the Obstetrical Diagnosis section. This is what it should say: 

"EPDS performed on XX/XX/XXXX - DIAGNOSIS" 

Possible Diagnoses: 

- Depression Not Likely
- Depression Possible
- Fairly High Possibility of Depression
- Probable Depression
- Suicide Risk

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Typos on the popup:
![22-typo](https://user-images.githubusercontent.com/3536805/174798440-093e087b-23f7-4a9b-812e-2066d94e8146.png)


Should be 'patient shows...'
![24-typo](https://user-images.githubusercontent.com/3536805/174798016-8c4bbb69-6583-4384-8951-2501ca21af27.png)
![25-typo](https://user-images.githubusercontent.com/3536805/174798655-de2f5285-0616-4452-8ee3-cca9d1811dbe.png)
![26-typo](https://user-images.githubusercontent.com/3536805/174798924-5bbf3f57-b261-4eb7-ac96-ee8948a72a57.png)

2. Diagnosis is empty:
![27-diagnosis-empty](https://user-images.githubusercontent.com/3536805/174799743-62431d8d-aa11-4f80-a016-0952a2157ee7.png)

### Checked and approved:

1. Referral: 
Under 9 points there is no referral, just health education form.
![20-health-edu](https://user-images.githubusercontent.com/3536805/174795404-3000f10b-ece1-4cf0-9594-0ef1e9583a2b.png)

2. Popups:

9 points|12 points|14 points|Suicidal
-|-|-|-
![17-9points](https://user-images.githubusercontent.com/3536805/174797236-b349f910-9cda-409e-8dab-ffcb181deb96.png)|![21-12points](https://user-images.githubusercontent.com/3536805/174797255-1f7bf295-3c80-4773-8880-9c8ab9cbd0e5.png)|![23-14points](https://user-images.githubusercontent.com/3536805/174797286-7bc0d700-c6ce-482a-9a90-b6ca2bef74a8.png)|![15-suicide-risk](https://user-images.githubusercontent.com/3536805/174797397-e9af6539-f19f-4243-b2fe-d8ff169ad7f4.png)

**Comment by adamhstewart** [comment]
@Diama1 please correct grammatical mistakes:
- "Patient shows...."
- "high possibility"

**Comment by anvmn** [comment]
@balagan73 

Please verify that typos are fixed.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

Precondition: EGA >= 28 weeks.

### QA Review

### Checked and approved:

1. Typos are fixed.

Possible depression|High possibility|Probable depression|Suicide risk
-|-|-|-
![image](https://user-images.githubusercontent.com/3536805/183284013-68dcaeba-4168-4286-a545-f76a41ac5ce4.png)|![image](https://user-images.githubusercontent.com/3536805/183284045-936b874d-b21d-41db-9f16-25e00609867b.png)|![image](https://user-images.githubusercontent.com/3536805/183284053-b18911e0-8062-4838-84d9-66d771bdccda.png)|![image](https://user-images.githubusercontent.com/3536805/183284060-529d2e35-eba3-4af4-b844-f9d13b112533.png)
