### ISSUE TITLE
Whatsapp Integration [10h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#292]
## Issue 

Nurses and CHWs need a way to share a patient's progress report with them. To do this, we are doing a WhatsApp integration. At the bottom of the progress reports, we are including a new button where they can "send via whatsapp". 

**Flow**: 
Hit "Send Via WhatsApp" Button --> consent Screen --> validate phone number (branches off if new number is needed)--> choose which portions of the report to send --> verify send 

**Video Overview**: 
You can watch a long winded but helpful video [here.](https://www.loom.com/share/abe535011b974ddeaa4c8609e2c1f678)

## Design: 

You can find the design files in Figma [here](https://www.figma.com/file/ar8UMXGjITVnICIAegbtIj/Dashboard-%7C-Progress-Reports-%7C-Etc?node-id=327%3A2239).  This flow is located to the right of the screen under the heading "Whatsapp Send" 

## Report sections for selection:

Source: https://docs.google.com/spreadsheets/d/1gQU_-YdyHKZKDz-3cIpF725aU3QSIxnkw8Hxe7zFx4U/edit#gid=0

![Selection_893](https://user-images.githubusercontent.com/17882245/177209733-c5838565-2ea7-4679-98bd-3c0c886a2389.png)

## To Do: 
- Create backend logic to send to whatapp. 
- Style screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

Can't open Figma link. It says file does not exist.
Points after reviewing the video:

1. As I see it, country code needs to be reconsidered. If we really need it, there are over 200 countries. Does it mean that we need to add all their flag icons.
Also, what about phone validation? Right now we don't validate anything, beside number characters. Do we need to change that? And, if we need country code, do we need to have validation logic for over 200 countries?

2. I don't think these are the right button labels:

![Selection_873](https://user-images.githubusercontent.com/17882245/175831178-7866b0ad-4580-4197-ae07-3efe7390e9f5.png)

3. At entering phone number flow, I don't see an option of canceling the action. What if we want to get back to previous step, or cancel sending message completly?

4. Selection of what part of report to send need to be well defined for all progress reports we need to support.
Technical implementation of this is taking a screenshot of what we want to send, meaning that we will have to view that section on tablet (lots of effort hiding here), so we need clear definition on all variations.
Also, I don't see how this should be supported for for ANC Labs section, for example.

Note: Besides making the screenshot themselves, we'll need to define a way of storing these messages with screenshots, and interaction with WhatsApp API for sending them. I can't estimate before we have API details, but I'd say that roughly this will reqiure at least 40h.

**Comment by anvmn** [comment]
@LudmilaGoichman please test on Dashboards env

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

- https://dashboards-ihangane.pantheonsite.io/
- tablet

### Questions/Found Issues:
1. Should there be spaces between numbers like in Figma?

app | Figma
---|---
<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f848e008-7ff0-4271-a268-014d73487ef4">|<img width="406" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/794fbac7-ba9f-4751-8304-1510436e82f5">
<img width="357" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ef5b30c5-8677-43a1-9813-20f89c896578">|<img width="405" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1036d392-5f20-41ea-9f85-aa8096168790">


2. Typo - `y` is missing in `Immunization History`:

<img width="358" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/ac3e3092-1dbe-410c-aba5-6ff5de3a08e5">

3. Maybe add the word `Charts` like in Figma?

app | Figma
---|---
<img width="358" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a3963746-262e-4915-832d-548e94d7c7bf">|<img width="402" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b56e8a9a-5bfc-4a77-861b-622278535d73">

~4. When the phone number does not exist, there should be 5 delivery attempts. But in all nodes (with existing phone number and non-existing) Delivery attempts = 0:~

existing phone | non-existing phone |
---|---
<img width="1260" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e04d043c-adb2-4880-b307-246008e1c33d">|![image](https://github.com/TIP-Global-Health/eheza-app/assets/35059802/736019dd-fec0-4ae1-be0b-cd7e4072fcbd)

5. Photos are not appear in the whatsapp image (in all reports except progress photos from ANC report //made just before sending the message). Example:

<img width="470" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1ebeb3aa-386b-444f-baa7-f13b53364426">|<img width="468" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/20d1190b-0d4d-4033-800f-981e72507916">
---|---

6. Standard Pediatric report. The section "Acute Illness History" in the list (in the flow), in the report called "Active Diagnosis"
7. NCD Progress Report. The section "Active Diagnosis" in the list (in the flow), in the Excel file called "Acute Illness"
8. ANC report. "Medical History" section is mentioned in the Excel file, but it doesn't exist in the report and in the screen:

<img width="358" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5699250d-2208-48a7-a756-7e05ba521ba1">

9. The word "diagnosis" is used in the Excel file, but in NCD Progress Report list (in app) it's "diagnosis" and in ANC report list it's "diagnoses" it's not consistent.

ANC Report | NCD Progress Report
---|---
<img width="358" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/28187ade-6cd7-4d1d-9304-b76b0be255ef">|<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0ac9821a-8d17-40f0-a208-15872a88167f">


10. Standard Pediatric report, NCD Progress Report, ANC Report. Dots are not displayed in the charts in the whatsapp image. I think it's more critical in the charts from the NCD Progress Report and the ANC Report
Examples:

Standard Pediatric report

<img width="440" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/234b67f0-c801-4603-98fe-1e7b640a085f"><img width="445" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c46b3dae-2080-4232-b569-c8966a673d33">|<img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c5a85d8d-4323-482c-b260-af561bd53bde"><img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5d9f6362-7e85-45df-a546-245fceb5ca9b">
---|---

NCD Progress Report:

<img width="442" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b02bdfda-b8e0-49f6-b9ee-049cd8f0fbb3">|<img width="409" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a28351e3-4631-4015-a504-04e5a1c985eb">
---|---


ANC Report:

<img width="562" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/48e9e7cb-f3df-47f2-bba4-907bf575ce06">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5f968f66-4b5b-419b-9172-d26a7775c42d">
---|---

11. In the group encounters the report cannot be sent, right?
12. The first pop-up doesn't appear for a long time after clicking the "Send via WhatsApp" button. And when clicking the button, it doesn't react for a long time (doesn't change color to a darker). And all buttons in the pop-ups also don't react for a long time
13. AI. The icons from "Action Taken" are not displayed in the message:

report in app | message 
---|---
<img width="260" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8c7069a1-d34e-4453-8339-c51d5ecea523">|<img width="260" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1c4d871c-b519-44c2-a744-cca99ba94f81">

14. When I save nutrition signs, they appear in the report (before sync!), but after sync - they disappear. Watch video:

https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f0f5a0c2-8513-4d0d-b933-4b434dc7ff71


### Checked and Approved:

1. WhatsApp messages are sent from all individual encounters of nurse and CHW.
2. The Flow:

1 |2 |3 (this step doesn't exist  if no phone number for the patient)|4
---|---|---|---
<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/467171e8-c95f-49ba-82a7-e4a313c5632a">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e8edaf5a-9f5f-4494-bcf4-fee897ffd32b">|<img width="354" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f238e45e-f603-4c7a-b305-68b799421f19">|<img width="359" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8272a877-5586-4a34-a274-f170bbddcfec">

5 | 6 (if the answer `yes`) | 7 (this step doesn't exist for AI) | 8 |
---|---|---|---
<img width="358" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/af9c6d8f-af49-4c45-860a-00216391f66a">| <img width="359" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8e43a697-b20d-4fb2-be9e-4a1bcc6f1719">|<img width="358" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/27aecec1-1039-4f92-9aac-520ba4044f9c">|<img width="357" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/61ff7f77-dce3-41da-a58d-e9712fda87ea">

9 | 10 | node created in the backend |
---|---|---
<img width="362" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/4cd67026-0b1e-4d55-a800-a23e2532c7ef">|<img width="462" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e445a757-a3fd-4047-bc25-10c5fcbce02a">|<img width="1197" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/b691b528-a931-4b25-b0f5-c9fba9b4d819">

3. When clicking the "no"/"cancel" button, the flow is canceled (except "no" in steps 3 and 5) 
4. The country code is "+250" by default 
<img width="359" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8d927bac-76d5-4a0f-b2ba-bb732be837e7">

5. The functionality works fine at offline mode (message is sent when internet connection is enabled)
6. The sections in the list correspond to the reports and the list in https://docs.google.com/spreadsheets/d/1gQU_-YdyHKZKDz-3cIpF725aU3QSIxnkw8Hxe7zFx4U/edit#gid=0 //except the questions above

Standard Pediatric report | NCD Progress Report | ANC report | 
---|---|---
<img width="357" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/909002b7-c8a3-4225-a8a9-a92f1f43d8e1">| <img width="356" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0a5bea54-c7e4-4c8b-9ba9-d12adc5b0b23">|<img width="364" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/507c70c7-26d9-43b0-b983-affb78dcb4f4">


7. Standard Pediatric report, NCD Progress Report. The sections in the whatsapp image are the same that were selected in the app. And most of the content is identical (except photos)

Example:

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/3c94f4b8-b877-4a15-b3b2-12292819494a">|<img width="383" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/599322f8-98b1-47e6-9a80-6d7819f42c60">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 4. When the phone number does not exist, there should be 5 delivery attempts. But in all nodes (with existing phone number and non-existing) Delivery attempts = 0:

The thing is that when we deliver message to vendor, we don't know if number is correct or not.
Delivery attempts counter is for retrying message delivery to vendor.
Once vendor got the message, it's their responsibility. We don't get feedback from vendor.
We consider message as delivered.

**Comment by anvmn** [comment]
@LudmilaGoichman  @adamhstewart 

> 1. Should there be spaces between numbers like in Figma?

No, we show numbers as they are. If we get feedback from customer, we may reconsider

>  2. Typo - `y` is missing in `Immunization History`:

Fixed

> 3. Maybe add the word `Charts` like in Figma?

No, we show the name of report pane, and pane is called "Growth'.

> ~4. When the phone number does not exist, there should be 5 delivery attempts. But in all nodes (with existing phone number and non-existing) Delivery attempts = 0:~

Answered at https://github.com/TIP-Global-Health/eheza-app/issues/292#issuecomment-1630626599.

> 5. Photos are not appear in the whatsapp image (in all reports except progress photos from ANC report //made just before sending the message). 

This is limitation. `html2canvas` loads photos, by issuing fetch requests to image urls.
On our APP however, we have SW layer that catched photos fetch requests and maps then to locations at device cache, where real images are stored. `html2canvas` can't use SW, and therefore, it can't get the image.
This affects the image we show at person details, and Photos pane at ANC report.
Seems to me we can not suggest to send the photos pane, and hide person image to avoid issuing invalid requests to backend. @adamhstewart what do you think?

> 6. Standard Pediatric report. The section "Acute Illness History" in the list (in the flow), in the report called "Active Diagnosis"

We show the name of report pane.

> 7. NCD Progress Report. The section "Active Diagnosis" in the list (in the flow), in the Excel file called "Acute Illness"

We show the name of report pane.

> 8. ANC report. "Medical History" section is mentioned in the Excel file, but it doesn't exist in the report and in the screen:

Excel issue - we don't have such pane at report, so obviously, we can't send it. 

> 9. The word "diagnosis" is used in the Excel file, but in NCD Progress Report list (in app) it's "diagnosis" and in ANC report list it's "diagnoses" it's not consistent.

Fixed.


> 10. Standard Pediatric report, NCD Progress Report, ANC Report. Dots are not displayed in the charts in the whatsapp image. I think it's more critical in the charts from the NCD Progress Report and the ANC Report

This happens because `htm2canvas` have trouble rendering certain SVG elements and their associated styles - SVG markers which we use to mark the points.
Solution for this is to replace SVG markers usage with basic SVG `circle` shape.
This is time consuming as we have multiple charts to handle, but since charts are important elements of the report, we'll have to implement the fix. //cc @adamhstewart 

> 11. In the group encounters the report cannot be sent, right?

There are no actions there, but maybe we do need it. @adamhstewart ?
**Update**: thinking about it, this is same Standard Pediatric report, so I'll go ahead and add action to send it by WhatsApp.

> 12. The first pop-up doesn't appear for a long time after clicking the "Send via WhatsApp" button. And when clicking the button, it doesn't react for a long time (doesn't change color to a darker). And all buttons in the pop-ups also don't react for a long time

Taking screenshot can take up to a minute to complete.
The problem here is that this is actual screenshot, so if we put a popup on screen, it will cover area of the report.
We do disable actions and make screen a little darker till actions is completed.

> 13. AI. The icons from "Action Taken" are not displayed in the message:

Fixed


> 14. When I save nutrition signs, they appear in the report (before sync!), but after sync - they disappear. 

Known issue that was handled already.

**Comment by anvmn** [comment]
@adamhstewart Opened a follow up issue - #872
