### ISSUE TITLE
ANC Subsequent - multiple diagnoses in popup should be bulleted list [1h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#306]
## Issue
in cases where there are multiple diagnosis in the popup before "next steps, the listed should be bulleted for easier reading,

## Task
- Re format the list

cc/ @jeanette-pelizzon

**Comment by anvmn** [comment]
@Diama1 what's the status with this?

**Comment by Diama1** [comment]
> @Diama1 what's the status with this?

Trying to finish up with it

**Comment by anvmn** [comment]
This issue requires redesign of architecture we got for data we store for the popup.
This will be implemented as part of Postpartum feature.
Selfassigning.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. The diagnosis on the warning popup display as bulleted list.

![image](https://user-images.githubusercontent.com/3536805/187148704-c22dcac0-6e15-45ae-a972-296b4e8ef073.png)
