### ISSUE TITLE
ANC Labs - Urine Dipstick - Ph - New options

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#308]
## Issue 

We need to add 4.0 and 4.5 as input options to Ph on both dipstick tests. 

## To Do: 

- Add input options

**Comment by jeanette-pelizzon** [comment]
FYI: @adamhstewart @anvmn issue was created and assigned to @Diama1

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. New options display properly.

Long dip|Short dip
-|-
![image](https://user-images.githubusercontent.com/3536805/183281591-e9d2d741-9848-4275-b018-a9945b5ffb4a.png)|![image](https://user-images.githubusercontent.com/3536805/183281790-32014b31-991c-416e-9829-76841c38d847.png)
