### ISSUE TITLE
ANC Labs - Specific Gravity

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#309]
## Issue 

The test for specific gravity is not run in Rwanda. We need to remove it from E-Heza. It occurs in ANC Labs - Urine Dipstick - Long Dip  

## To Do: 

- Remove Specific Gravity from Eheza

**Comment by jeanette-pelizzon** [comment]
FYI @adamhstewart @anvmn issue created and assigned to @Diama1

**Comment by anvmn** [comment]
@balagan73 please test on nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

Specific Gravity is not listed on Dip stick - long page.

![image](https://user-images.githubusercontent.com/3536805/180037066-a0a43855-acfd-4c7b-b972-c28aca30053b.png)
