### ISSUE TITLE
ANC Labs - Urine Dipstick - Urobilinogen- input Update

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#310]
## Issue 

We need to adjust the inputs for Urobilinogen on the Long Urine Dipstick in ANC Labs to mimic what they see on the stick. The results options should be: 

0-0.2 
1
2
4
8

As a reminder, the normal range is anything equal to or less than 1 

## To Do: 
- Adjust the input options for this test

**Comment by jeanette-pelizzon** [comment]
FYI: @anvmn @adamhstewart this change is being made.

**Comment by Diama1** [comment]
> ## Issue
> We need to adjust the inputs for Urobilinogen on the Long Urine Dipstick in ANC Labs to mimic what they see on the stick. The results options should be:
> 
> 0-0.2

@jeanette-pelizzon is this **0-0.2** one value?

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Requested urobilinogen options display: 

![image](https://user-images.githubusercontent.com/3536805/183282111-a5bcb911-80e8-4fdc-82b9-a0f0f322e209.png)
