### ISSUE TITLE
Patient record, adults view - verify age can be calculated before allowing starting Antenatal encounter [2h]

### ISSUE THREAD

**Issue by balagan73** [TIP-Global-Health/eheza-app#317]
## Issue 

I have selected a patient (Gatera Ines) in the participiant directory, and could not save her vitals. It turned out she had no birthday. Patients not yet 13 years old should not be able to start an encounter of type antenatal care.

![1-save-not-available](https://user-images.githubusercontent.com/3536805/177288662-f98c62c9-2079-4eb7-b635-d8634859202f.png)

## To Do
- Ensure antenatal care is not available for patients under 13.

**Comment by anvmn** [comment]
### Analysis:

If we have no knowledge of age we should not allow starting encounters.
This is relevant for adult record, because it's the default view when there's no birth date.

**Comment by anvmn** [comment]
@balagan73 please test on nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. No encounter of type Antenatal care is available for a 12 year old child.
![2-no-anc](https://user-images.githubusercontent.com/3536805/180139228-db693432-b788-4c05-b4df-a87832b280e8.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn If I understood this issue correctly, a user should not be able to start any type of encounter with a patient who has no age save in eheza. Not just ANC as shown in the photo above. Want to make sure the larger issue is okay. 

I've never encountered this but we should prompt the user to input an age for the patient if non exists - does that happen?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Well, at first I thought we should block all types, but currently, we allow starting Acute Illness encounter for patient that got no age set. So, this is what I developed for Patient Record as well.

> I've never encountered this but we should prompt the user to input an age for the patient if non exists - does that happen?

No, this was never required. Birth date is a mandatory field when patient is created, so, not BD seems to me are edge case scenario.

**Comment by jeanette-pelizzon** [comment]
Perfect, so theoretically no patient would be without a birthdate. So we just need to make sure that ANC options only populate for female patients age 13 and up - which seems to be happening. I'll move this to acceptance testing. Thank you!
