### ISSUE TITLE
ANC Labs - Random Blood Sugar - Update [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#322]
## Issue 

We are now going to diagnose diabetes and gestational diabetes in pregnant patients. To do this we need: 

1) Random Blood Sugar run at every visit 
2) Adding a question to the design 

## Design Updates 

We have added in the question "Has the patient fasted for this test" as the second question. This question is required for diagnoses. 

Screen One | Screen Two | Screen Three | Screen Four 
--|--|--|--
![Random Blood Sugar](https://user-images.githubusercontent.com/77505464/177815713-93860849-6e89-4a39-9183-c45f088a465e.jpg) | ![Random Blood Sugar-1](https://user-images.githubusercontent.com/77505464/177815724-984dea05-a938-4545-84a7-8918e1579b02.jpg) | <img width="242" alt="Screen Shot 2022-07-07 at 10 47 10 AM" src="https://user-images.githubusercontent.com/77505464/177816294-a7f2a83e-1540-4142-a41d-4b2cead62245.png"> | <img width="228" alt="Screen Shot 2022-07-07 at 10 47 15 AM" src="https://user-images.githubusercontent.com/77505464/177816322-4d49c623-735d-45be-84cf-04479dcb4191.png">

## To Do: 

- Update frequency of random blood sugar lab so that appears at every visit 
- Style screens per design

**Comment by jeanette-pelizzon** [comment]
Update: new question text should read "has the patient fasted for this test (no food for 12 hours)?"

**Comment by anvmn** [comment]
@balagan73 please test on nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. We have only one screen, and if test was performed,  the test date can be set set. If test was not performed, its reason is asked. I think the design should be updated, what we have is correct.

Test performed|Not performed
-|-
![1-fasting](https://user-images.githubusercontent.com/3536805/179998723-b72e1f5c-0edf-41b2-8c1c-cb79554e9b47.png)![2-questions](https://user-images.githubusercontent.com/3536805/179998769-d60c598e-b90a-4de1-bb8a-ca8b40741b1d.png)|![3-no-test](https://user-images.githubusercontent.com/3536805/179999141-f69c870a-d7b3-4fff-a983-6177952b5759.png)

**Comment by jeanette-pelizzon** [comment]
It is supposed to be one screen but some of the questions are conditional. I just retested. This works appropriately. 

Moving to acceptance.
