### ISSUE TITLE
ANC Subs - Next Steps - Diabetes [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#331]
## Issue 
 
When a patient meets the criteria for diabetes (which can be found on the logic doc [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)) we will provide health education and refer them to the hospital for specialty management. Since we stack diagnoses for hospital referral we can just use the normal referral screen and the nurse will be able to refer them to the correct program on her paper form she hands the patient. 

Note: Patient that was diagnosed previously with Diabetes will be given a test, but no next steps, if tests is positive. Test is given only to record sugar count change.

## Design 

Pop Up | Health Education | Referral 
--|--|-- 
<img width="295" alt="Screen Shot 2022-07-14 at 3 16 30 PM" src="https://user-images.githubusercontent.com/77505464/179075551-cf52c3f4-2d7b-4ff7-aeb9-2945501f3655.png"> | <img width="298" alt="Screen Shot 2022-07-14 at 3 16 35 PM" src="https://user-images.githubusercontent.com/77505464/179075557-32a7c77c-dff1-42d9-9f74-6e9368ef807d.png"> | <img width="292" alt="Screen Shot 2022-07-14 at 3 16 41 PM" src="https://user-images.githubusercontent.com/77505464/179075558-5393a731-d4f8-4f85-afd6-fe3d87bed57e.png">

## To Do 
- create back end logic for diabetes as outlined in the master logic sheet 
- style screens per design 

## Related Issues 
- #322
- #332

**Comment by anvmn** [comment]
@jeanette-pelizzon @balagan73 

Note that this requires extension of #258, per https://github.com/TIP-Global-Health/eheza-app/issues/258#issuecomment-1166608871:

![Selection_919](https://user-images.githubusercontent.com/17882245/179273267-ec4de845-e870-47f8-a32a-85e2a168fac5.png)

**Comment by jeanette-pelizzon** [comment]
Diagnosis should not be hypoclycemia. It should be diabetes per the logic doc. We do not diagnose hypoglycemia. Otherwise the instructions in adams post should be good.

**Comment by anvmn** [comment]
@balagan73 please test on nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. There are typos on the health education screen.
![3-healt-edu-typo](https://user-images.githubusercontent.com/3536805/180004320-a82000a8-4580-4e39-beea-052a9479d3f3.png)

2. After entering results (>20 weeks EGA + fasting blood glucose of >7 mmol/L) under case management, encounter cannot be ended.
![5-next-steps](https://user-images.githubusercontent.com/3536805/180005908-5f7999e2-d9de-4afa-8a6e-38fb2a42aa08.png)
![image](https://user-images.githubusercontent.com/3536805/180006033-69598594-ac2b-4a58-8170-ef95ed95ef66.png)


### Checked and approved:

1. >20 weeks EGA + fasting blood glucose of >7 mmol/L

![1-warning](https://user-images.githubusercontent.com/3536805/180003929-0708398e-9dde-491e-b13e-7fd66b5c1993.png)
![4-referral](https://user-images.githubusercontent.com/3536805/180004527-8f431677-48cc-408b-9b03-3d4d6e879bc1.png)

2. >20 weeks EGA + random blood glucose of >= 11.1 mmol/L

3. > 20 weeks EGA + urine dip (glucose) >=2+

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues:

1. Encounter cannot be ended. Also reported and detailed in #332
2. When <= 20 weeks EGA + urine dip (glucose) >=2+ and encounter was paused before Random blood glucose test. 
Encounter could be ended without any next steps. Nothing displays on progress report.
![image](https://user-images.githubusercontent.com/3536805/180018671-3fc008e9-eb70-4b6f-992d-cbf57cdd8b81.png)

3. Patient is under 20 weeks EGA, and urine dip (glucose) is >=2+ and the patient has fasted-> blood sugar >7mmol/L = **Gestational Diabetes**. If the patient has NOT fasted -> blood sugar >=11= Gestational Diabetes. 

This is not happening, no next steps, nothing on report.

### Checked and approved:

1. Warning displays 
![1-warning](https://user-images.githubusercontent.com/3536805/180015259-c7259119-3678-4abd-a51a-d40dd5510223.png)

2. When <= 20 weeks EGA + urine dip (glucose) >=2+ and Random blood glucose test cannot be run, diabetes is diagnosed and patient is referred to hospital.

Warning|Referral
-|-
![2-no-blood-glucose-run](https://user-images.githubusercontent.com/3536805/180021254-7e289a51-cad8-4fa5-a118-4a65a23a9596.png)|![3-referral-no-bc-run](https://user-images.githubusercontent.com/3536805/180021266-6a214996-27c2-423e-9546-442959abc0d2.png)

**Comment by jeanette-pelizzon** [comment]
1. Let's handle in issue #332
2. We may need to look into this further because the random blood sugar should be run every visit but if they don't run the test and the patient get a urine dip (glucose) above 2 then they should be prompted again to run the random blood sugar as that will finalize diagnosis. @anvmn 

<img width="1119" alt="Screen Shot 2022-07-21 at 8 25 44 AM" src="https://user-images.githubusercontent.com/77505464/180252434-eacf2efe-fff2-4e3f-9694-9a26f8162f8b.png">

3. This should be happening. @anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> 2. We may need to look into this further because the random blood sugar should be run every visit but if they don't run the test and the patient get a urine dip (glucose) above 2 then they should be prompted again to run the random blood sugar as that will finalize diagnosis. @anvmn

With the development of allowing next steps (where encountrer is paused) after all activities are completed (beside Photo), random blood sugar wil be filled by nurse. It may not be run, due to one of the reasons nurse selects. In this case, per logic master, we diagnose by urine glucose.

> 3. Patient is under 20 weeks EGA, and urine dip (glucose) is >=2+ and the patient has fasted-> blood sugar >7mmol/L = Gestational Diabetes. If the patient has NOT fasted -> blood sugar >=11= Gestational Diabetes.

I tested this, and it works fine for me. Hower, note that at  patient has NOT fasted -> blood sugar >=11, 11 is not correct number. It's 11.1:

![Selection_956](https://user-images.githubusercontent.com/17882245/180643775-de33513f-5e58-4fdd-9899-1e7030385c16.png)

**Comment by jeanette-pelizzon** [comment]
verified with wendy-> 11.1 mmol/L  is the correct number.

**Comment by anvmn** [comment]
@balagan73 please retest points 2 and 3. Note that pre https://github.com/TIP-Global-Health/eheza-app/issues/331#issuecomment-1194450250 it's 11.1 and not 11.

Point 1 should also be fixed, as long  as all activities are completed.

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. In the row of Diabetes the Google sheet logic says: Patient is under 20 weeks EGA, and urine dip (glucose) is >=2+ and the patient has fasted-> blood sugar >7mmol/L = Gestational Diabetes. If the patient has NOT fasted -> blood sugar >=11= Gestational Diabetes.
@jeanette-pelizzon Is this supposed to be Diabetes?

![image](https://user-images.githubusercontent.com/3536805/180965089-05b3786f-8c44-47d1-9592-d68562d7401f.png)

2.  In contrast to the above specification the patient is diagnosed with Diabetes, not Gestational diabetes.
![image](https://user-images.githubusercontent.com/3536805/181170313-a36e501b-99eb-4ff4-a198-ea01b6916a36.png)

### Checked and approved:

1. Encounter cannot be paused before all the labs sections are answered.
![image](https://user-images.githubusercontent.com/3536805/180964491-3e4c65fb-0009-49b8-832f-8bc1588264a4.png)

2. Patient is under 20 weeks EGA, and urine dip (glucose) is >=2+ and the patient has fasted-> blood sugar >7mmol/L = Gestational Diabetes. If the patient has NOT fasted -> blood sugar >=11= Gestational Diabetes.

Patient is diagnosed with Diabetes, this is indicated on the progress report.

health education|progress report
-|-
![image](https://user-images.githubusercontent.com/3536805/180965739-a6b16cd1-6f35-4339-be99-d2a91a83d55f.png)|![image](https://user-images.githubusercontent.com/3536805/180965752-56c6d821-62ba-4e31-91f7-5d87843e2bea.png)

3. Encounters can be ended in all cases, there were no problems with workflow.

**Comment by jeanette-pelizzon** [comment]
>In the row of Diabetes the Google sheet logic says: Patient is under 20 weeks EGA, and urine dip (glucose) is >=2+ and the patient has fasted-> blood sugar >7mmol/L = Gestational Diabetes. If the patient has NOT fasted -> blood sugar >=11= Gestational Diabetes.

@balagan the logic document is exactly what the clinical team gave me so we should follow that for logic. Is it populating correctly in the app?

**Comment by balagan73** [comment]
@jeanette-pelizzon No, patient is diagnosed with Diabetes. I have updated my QA Review above. However, without any medicinal knowledge just by looking at the table it looks like Gestational diabetes was not changed after a copy+paste. Can you confirm this diagnoses with the clinical team? Just did a quick search, and according to https://www.nhs.uk/conditions/gestational-diabetes/ this document the screening for Gestational diabetes happens in week 24-28, which strengthens my assumption.

**Comment by jeanette-pelizzon** [comment]
Thanks for catching @balagan73. I followed up and they made two changes:

1) the way we input the medications/diagnose was changed (updated the appropriate issue there and @anvmn knows) 

2) they updated the diagnosis stuff here as well to be diabetes for the diabetes stuff and gestational diabetes for gestaitonal if that makes sense. 

Here are the updates highlighted in yellow on the logic sheet: 
<img width="929" alt="Screen Shot 2022-08-01 at 10 57 19 AM" src="https://user-images.githubusercontent.com/77505464/182224946-3af8bc38-da8a-4f85-8706-e86197c5ee4b.png">

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Currently the patient is diagnosed with Diabetes if urine dip glucose >=2, even if Blood glucose is not higher than 126 mg/dl. Is this OK?

Blood glucose|Warning
-|-
![image](https://user-images.githubusercontent.com/3536805/183279081-652323b4-a3cf-417d-9789-1de8eac2b2a8.png)|![image](https://user-images.githubusercontent.com/3536805/183279095-a60ec16f-b73b-46be-bf48-ad6d66fa387a.png)

### Checked and approved:

1. Diagnoses for Diabetes and Gestational Diabetes is correct.

Diabetes|Gestational Diabetes
-|-
![image](https://user-images.githubusercontent.com/3536805/183279161-a2fa6d89-3925-48f3-a9b1-1788923a4b23.png)|![31-gestational-diabetes](https://user-images.githubusercontent.com/3536805/183279194-8bf78286-4bfa-426f-a38c-83b7623507c0.png)

2. After patient is diagnosed with diabetes, further encounters do not show next steps.
![image](https://user-images.githubusercontent.com/3536805/183279229-94a7cf2b-3a63-4329-810e-e8045842b848.png)

**Comment by anvmn** [comment]
@balagan73 

> Currently the patient is diagnosed with Diabetes if urine dip glucose >=2, even if Blood glucose is not higher than 126 mg/dl. Is this OK?

A change for 126 value is part of #382 which is not deployed yet.
It will be verified when #382 is tested.
