### ISSUE TITLE
ANC Subs - Next Steps - Gestational Diabetes [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#332]
## Issue 
 
When a patient meets the criteria for GESTATIONAL diabetes (which can be found on the logic doc [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493)) we will provide health education and refer them to the hospital for specialty management. Since we stack diagnoses for hospital referral we can just use the normal referral screen and the nurse will be able to refer them to the correct program on the paper form she hands the patient. 

Note: Patient that was diagnosed previously with Diabetes or Gestational Diabetes will be given a test, but no next steps, if tests is positive. Test is given only to record sugar count change.

## Design 

Pop Up | Health Education | Referral 
--|--|-- 
<img width="294" alt="Screen Shot 2022-07-14 at 3 19 27 PM" src="https://user-images.githubusercontent.com/77505464/179076013-ba7d3fae-d1b0-4833-92c9-4081339479ea.png">| <img width="291" alt="Screen Shot 2022-07-14 at 3 19 33 PM" src="https://user-images.githubusercontent.com/77505464/179076019-d995b780-5a8f-47ed-a162-dd63a65548dc.png"> | <img width="292" alt="Screen Shot 2022-07-14 at 3 19 38 PM" src="https://user-images.githubusercontent.com/77505464/179076020-505c170f-42ff-44e9-a203-89a54fe10d17.png">

## To Do 
- create back end logic for gestational diabetes as outlined in the master logic sheet 
- style screens per design 

## Related Issues 
- #322
- #331

**Comment by anvmn** [comment]
@jeanette-pelizzon @balagan73 

Note that this requires extension of #258, per https://github.com/TIP-Global-Health/eheza-app/issues/258#issuecomment-1166608871:

![Selection_919](https://user-images.githubusercontent.com/17882245/179273267-ec4de845-e870-47f8-a32a-85e2a168fac5.png)

**Comment by jeanette-pelizzon** [comment]
Thanks for flagging @anvmn. Just a note: in conversations with the clinical team we've only talked about high blood sugar which is diabetes (hyperglycemia). Hypoglycemia is low blood sugar and not something we address in ANC. We've never referred to diabetes as hyperglycemia in conversation so let's keep it as diabetes. Just so we don't change any wording around since diabetes and hypo glycemia are different diagnosis.

**Comment by anvmn** [comment]
@balagan73 please test on nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. There are typos on the health education screen.
![3-healt-edu-typo](https://user-images.githubusercontent.com/3536805/180004320-a82000a8-4580-4e39-beea-052a9479d3f3.png)

2. After entering results (with all Gestational diabetes conditions) under case management, encounter cannot be ended. To save time I have only entered Random Blood glucose tests, and long/short dip tests where needed. Other activities were paused.

![5-next-steps](https://user-images.githubusercontent.com/3536805/180005908-5f7999e2-d9de-4afa-8a6e-38fb2a42aa08.png)
![image](https://user-images.githubusercontent.com/3536805/180006033-69598594-ac2b-4a58-8170-ef95ed95ef66.png)


### Checked and approved:

1. Patient >20 weeks EGA + fasting blood glucose of >7 mmol/L
 and  > 20 weeks EGA + urine dip (glucose) >=2+ 
also >20 weeks EGA + random blood glucose of >= 11.1 mmol/L

![1-warning](https://user-images.githubusercontent.com/3536805/180003929-0708398e-9dde-491e-b13e-7fd66b5c1993.png)
![4-referral](https://user-images.githubusercontent.com/3536805/180004527-8f431677-48cc-408b-9b03-3d4d6e879bc1.png)

**Comment by jeanette-pelizzon** [comment]
**Point 1**

@Diama1 can you fix the typos in point one, please? 

**Point 2** 
I am not sure I understand what you meant by paused activities. I believe you shouldn't be able to end the encounter until you complete all activities in the first encounter. You don't need to input all results from case mgmt to end an encounter but the activities must be worked through in the first part. 

@anvmn let me know if I am wrong about that.

**Comment by Diama1** [comment]
> ## **Point 1**
> @Diama1 can you fix the typos in point one, please?

@jeanette-pelizzon sure

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> I am not sure I understand what you meant by paused activities. I believe you shouldn't be able to end the encounter until you complete all activities in the first encounter. You don't need to input all results from case mgmt to end an encounter but the activities must be worked through in the first part.

At case management, current logic says that all activites need to be completed for 'end encounter' button to become active.
The problem @balagan73 was experiencing is due to problem with logic that determines if health education sub activity is completed or not. This needs to be fixed. Problem here is that we need to make some infrastructure changes, to support health education at both phases of encounter. I'll open a separate issue.

Regarding `current logic says that all activites need to be completed for 'end encounter' button to become active` we may need to reconsider this, because it is possible that not all lab results will be entered at once.
HIV PCR takes up to 30 days to complete, for example.
So, right now, if partial results are entered, only option to get out of encounter is using the `<-` button.

**Comment by jeanette-pelizzon** [comment]
We should have @adamhstewart give his opnion here. In my opinion it is super confusing for users to have to input partial results and then have to <- back out of the encounter. They should be able to save the encounter and, if all results are not input yet, then it should remain open in case management. That way the user will see that there are still results pending for that patient. 

On the technical side, I am not sure how complicated my idea is to implement but that is what I would suggest as the best experience for the user.

**Comment by anvmn** [comment]
@balagan73 please check that typos were fixed on Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Typos are fixed:
![image](https://user-images.githubusercontent.com/3536805/183838219-ea31c06b-20c8-433b-be00-9656cecb202c.png)
