### ISSUE TITLE
ANC - Eclampsia + Preeclampsia Next Steps [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#337]
## Issue 

There has been a change to when the next steps should appear for eclampsia and preeclampsia. 

Preeclampsia (any level of severity) - in next steps (EXCEPTION if a patient is >=37 weeks EGA then it interrupts)

Eclampsia - interrupts flow 

I have updated this on the [master logic sheet](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) which will be kept the most up to date. 

## To Do: 
- Update next steps

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review


### Found issues and questions:

1. severe right upper quadrant pain (examination - core exam)  is missing.

2. Any EGA + Headaches and blurred vision (with 130/70 BP)
No hospital referral under next steps.
![image](https://user-images.githubusercontent.com/3536805/183296497-8e1dcd21-b04d-4061-919a-b638db644091.png)

3. Logic says Diastolic >= 90 should be diagnosed as some kind of hypertension. This is working, however, validation on the form is only triggered at 91 value.

90|91
-|-
![image](https://user-images.githubusercontent.com/3536805/183356743-5b5ea6bc-3472-49c7-8ef6-6cfdf37218c9.png)|![image](https://user-images.githubusercontent.com/3536805/183356767-f05bc1b2-5115-40e8-b6d8-6bf9fb9fdfb0.png)


### Checked and approved:

1. Any EGA + Headaches and blurred vision
![image](https://user-images.githubusercontent.com/3536805/183296290-8f673c46-8300-4b64-93ec-5acdf21cca5a.png)

2. Convulsions:

Warning|Referral
-|-
![image](https://user-images.githubusercontent.com/3536805/183296567-ac39e294-3fef-4a1e-8076-a2536eae1f83.png)|![image](https://user-images.githubusercontent.com/3536805/183296586-b0eb0f9b-5c71-42d2-8dce-b31efd77fea9.png)

**Comment by adamhstewart** [comment]
@anvmn please check the points above

**Comment by anvmn** [comment]
@adamhstewart 

> 1. severe right upper quadrant pain (examination - core exam) is missing.

It has different wording at the APP:

![Selection_1097](https://user-images.githubusercontent.com/17882245/190896326-2fde04a9-c53a-42c4-b6cb-f6b599b36d56.png)


> 2. Any EGA + Headaches and blurred vision (with 130/70 BP)
No hospital referral under next steps.

Fixed at #475.

> 3. Logic says Diastolic >= 90 should be diagnosed as some kind of hypertension. This is working, however, validation on the form is only triggered at 91 value.

The alerts follow the rules defined at Vitals tab of Logics master file:

![Selection_1098](https://user-images.githubusercontent.com/17882245/190896407-31994ef5-511e-43d9-a6ab-144a7106a109.png)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

### QA Review

### Found issues and questions:

1. Is the different wording in the app is OK?

  severe right upper quadrant pain  <-> Tender to palpation right upper

2. Shouldn't the Blood pressure data on the Vitals tab and on the ANC Nurse tab be in sync? I think if we alert at 91 diastolic BP, we should diagnose at the same bp or vice versa. 

### Checked and approved:

1. Patient is referred to hospital when vision is blurred with headache.
![image](https://user-images.githubusercontent.com/3536805/192314368-4209be63-f469-448e-b6fe-2ed17bbe0dbb.png)
