### ISSUE TITLE
ANC - Hierarchy of Diagnoses [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#340]
## Issue 

As discovered in #139, we currently have a problem where E-Heza doesn't know the diagnosis hierarchy of hypertension, preeclampsia, and eclampsia and is therefore diagnosing patients will all three. Since the logic for these diagnoses is very similar - just stacking on extra symptoms - we need to create a hierarchy so that a patient is not diagnosed with all of these when it should be just one. Essentially these diagnoses build on top of one another so as the severity increases the diagnosis changes. ##

<img width="930" alt="Screen Shot 2022-07-19 at 2 36 36 PM" src="https://user-images.githubusercontent.com/77505464/179852822-cf893c21-e14c-4957-abc2-f782686c0c74.png">

Note 1: the notes section in that image is very general always refer to the master logic document for detailed logic descriptions

Note 2: just a general FYI if someone has eclampsia then they are having seizures and that's the most pressing symptom but they likely have all the other stuff too it's just that as soon as we go over danger signs and see they have seizures we are sending them immediately to the hospital. We won't keep someone to do a full encounter with them if they are having seizures. 

## To Do: 
- update backend to recognize this hierarchy

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Table looks good to me. Only thing tha is inaccurate is that Severe Preeclampsia when there's severe headaches with blurry vision (danger signs) is for ANY EGA. 

Also, please align EGA values at Logics file to match those in table:
![Selection_930](https://user-images.githubusercontent.com/17882245/179953262-43cd2c7e-95a8-4875-acec-88e4720045a4.png)

**Comment by jeanette-pelizzon** [comment]
**NOTE:** once a patient moves up in the hierarchy they will never go back down, even if their symptoms stop. 

- fixed the logic master

- here is the updated screen shot (good catch!) 

<img width="936" alt="Screen Shot 2022-07-20 at 7 49 36 PM" src="https://user-images.githubusercontent.com/77505464/180119496-4ae9d6a2-7b8f-421c-8948-fac2870d066a.png">


// @anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Thanks.

Please note that there're still differences between logic master and the table.
At Severe Preeclapsia, we do not have edema condition.
Also, BP conditions are not the same -  for Hypertension it's enough for one of the measurement to be off, while for Sever Preeclapsia, both dia and sys should be off.
I know that logic master is the source of truth... but it has tendency to change...

Also, I want to reconfirm ANY EGA for Severe Preeclapsia at (1), before I start working on this change (as it'll require quite a considerable effort).
If it's indeed so, please add ANY EGA  to (1) at logics master.

**Comment by jeanette-pelizzon** [comment]
> At Severe Preeclapsia, we do not have edema condition.

Updated. The table is VERY general to understand the hierarchy so always refer to logic master. 

>Also, BP conditions are not the same - for Hypertension it's enough for one of the measurement to be off, while for Sever Preeclapsia, both dia and sys should be off.

Again, all logic should be pulled from logic master. I just included that column to try and help explain why the hierarchy is the way it is. If it confusing just ignore it or I can take it. All we really need to know is the hierarchy. 

>I know that logic master is the source of truth... but it has tendency to change...

I try and keep it as updated as possible as we answer questions or get new information. I update issues with info as well but let me know if I miss any. 

> Also, I want to reconfirm ANY EGA for Severe Preeclapsia at (1), before I start working on this change (as it'll require quite a considerable effort). If it's indeed so, please add ANY EGA to (1) at logics master.

The logic master is correct. You can be diagnosed with Severe Preeclampsia at any EGA. It is dependent on the EGA what the next steps are. In our case, we just refer to hospital for all but technically they are referred for different reasons and the nurse should know this. I don't think we need to outline these in the next steps because we combine all referrals. Keeping the wording in the logic document as we consistently refer back to the logic master in meetings and need to know that we had that outlined. 

[Link to table. ](https://docs.google.com/spreadsheets/d/1wtYQlludCJ310fTztLXiJC-UjX-dX6W8dQsS4IBhRLc/edit#gid=0)

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Patient was diagnosed with Chronic hypertension. Then at next encounter, wheezes and/or crackles was selected at examination core exam, BP was raised to 110/130. Patient was referred to hospital with hypertension before urine dip results. Diagnoses did not show hospital referral.

Blood pressure|Referral|Report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/183373784-0ed80213-7bd3-4457-8db1-2eda001c481b.png)|![image](https://user-images.githubusercontent.com/3536805/183373905-ae133b8c-1ef8-4183-8573-29cbfb3d5a9b.png)|![image](https://user-images.githubusercontent.com/3536805/183373944-9c67c970-a339-4728-932d-55c336910bac.png)

After entering protein for urine dip results, diagnosis did not change.

Urine dip|Diagnosis
-|-
![image](https://user-images.githubusercontent.com/3536805/183374346-835684e1-4157-4b31-8a7f-bce5b97364cb.png)|![image](https://user-images.githubusercontent.com/3536805/183374359-c8f69e72-fdae-4acd-8a74-93c359cdc554.png)

2. For patient diagnosed with Gestational hypertension, Medication distribution states they show signs of Chronic hypertension.
![image](https://user-images.githubusercontent.com/3536805/183357437-a263b0f0-d1cf-4824-85aa-51fb9dd16128.png)

3. The patient was previously diagnosed with Gestational hypertension. Diagnoses did not change after entering Edema or Protein in urine. Maybe second measurement within 2 hours is needed for this, but when I return to case management, I can only end the encounter, no other options are available. After ending encounter, patient is still pending under case management.

Progress report|Case management
-|-
![image](https://user-images.githubusercontent.com/3536805/183359694-7cbef4e2-ce46-4926-b2eb-960191abf5e0.png)|![image](https://user-images.githubusercontent.com/3536805/183359720-bfb45f0e-9a3e-407d-b5a7-6c5271218eb8.png)

After ending encounter|After ending next encounter
-|-
![image](https://user-images.githubusercontent.com/3536805/183359910-b437c356-bcf1-42d0-98ff-1e0b7a364166.png)|![image](https://user-images.githubusercontent.com/3536805/183360756-9b5af40d-e3ea-41dc-b794-675ca1cb4b2f.png)

4. When a patient with Mild to moderate preeclampsia has Blurred vision, warning displays for severe preeclampsia, but progress report is not updated. Maybe this happens after recheck in 2 hours? 

Warning|Progress report
-|-
![image](https://user-images.githubusercontent.com/3536805/183363106-62432fc0-ed4e-4e77-ab70-a55ab8d13dfc.png)|![image](https://user-images.githubusercontent.com/3536805/183363184-3053f8e6-7e33-4347-acb6-29a5bf598e14.png)

5. When patient with Chronic hypertension has Blurred vision they are referred to hospital, progress report is updated for severe preeclampsia, but hospital referral says Hypertension.

Warning|Referral|Report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/183375571-9884030c-d94e-4851-be3e-aa7808cb11c0.png)|![image](https://user-images.githubusercontent.com/3536805/183375621-bc307813-26ee-4bd7-a59e-0937ec4372d0.png)|![image](https://user-images.githubusercontent.com/3536805/183375675-82c6a088-0051-4e48-8c38-4af51318f7f5.png)

### Checked and approved:

1. When patients with Mild to moderate preeclampsia or Severe preeclampsia have convulsions, they are diagnosed with Eclampsia and referred to hospital.

Warning|Progress report
-|-
![image](https://user-images.githubusercontent.com/3536805/183363930-08dc101c-7c81-42eb-8f7d-c933d0a18f77.png)|![image](https://user-images.githubusercontent.com/3536805/183363960-f7fd3c3a-1945-40a9-b6af-27e1a271b0cf.png)

**Comment by adamhstewart** [comment]
@anvmn In addition to checking the points above:  the places where we indicate "Gestational Hypertension", we should instead use "Pregnancy-Induced Hypertension"

The reason is that Gestational hypertension is a "bucket" - which includes pregnancy-induced hypertension, preeclampsia, and eclampsia.

**Comment by anvmn** [comment]
@adamhstewart 

> 1. Patient was diagnosed with Chronic hypertension. Then at next encounter, wheezes and/or crackles was selected at examination core exam, BP was raised to 110/130. Patient was referred to hospital with hypertension before urine dip results. Diagnoses did not show hospital referral.

This is correct behavior, per Hypertension (Continued Care):
![Selection_1106](https://user-images.githubusercontent.com/17882245/190970382-86304cc4-be54-485b-974f-0ca03b02ba4e.png)

Seems to me that sending to hospital is correct decision here, because even if Preeclapsia was diagnosed, patient would have been referred to hospital anyway.
BTW, Nurses now have option to ommit sending patient to hospital, so there's an option to wait for test results, and act according to findings.

> After entering protein for urine dip results, diagnosis did not change.

Tried this, and it worked well. 

Please retest this scenario.

> 2. For patient diagnosed with Gestational hypertension, Medication distribution states they show signs of Chronic hypertension.

Fixed at #475.

> 3. The patient was previously diagnosed with Gestational hypertension. Diagnoses did not change after entering Edema or Protein in urine. Maybe second measurement within 2 hours is needed for this, but when I return to case management, I can only end the encounter, no other options are available. After ending encounter, patient is still pending under case management.

I don't see the bood preasure values that were entered. In any case, I tried this scenarion when checking point 1, and it worked well. Please retest.

> 4. When a patient with Mild to moderate preeclampsia has Blurred vision, warning displays for severe preeclampsia, but progress report is not updated. Maybe this happens after recheck in 2 hours?

Fixed at #475.

> 5. When patient with Chronic hypertension has Blurred vision they are referred to hospital, progress report is updated for severe preeclampsia, but hospital referral says Hypertension.

Tested this, and all seem to work properly. Please retest.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Patient with EGA < 20 weeks is diagnosed with Chronic hypertension (111/130 BP). At next encounter with 110/160 BP and with wheezes the patient is correctly referred to hospital. When urine dipstick results show protein, the diagnosis is correctly Severe preeclampsia. However, pregnancy induced hypertension is also shown.
The question is, where were we supposed to indicate Gestational hypertension before? In the logic master document the Gestartional hypertension refers to only EGA >= 20 weeks. Also, shouldn't we update the logic master document with the Pregnancy induced hypertension?
![image](https://user-images.githubusercontent.com/3536805/191439463-0d65c580-f7ab-4eda-88df-818cbb489074.png)
![image](https://user-images.githubusercontent.com/3536805/191440554-9349d8f4-0789-4246-83d8-fb1c5423ec30.png)

2. I think the induced should start with a lower case i on the Medication distribution page.
![image](https://user-images.githubusercontent.com/3536805/191444679-0d08bab5-08be-420e-9216-32e7cb28dfe6.png)

3. Patient was diagnosed with Pregnancy-induced hypertension (in checked and approved point 2). At next encounter Edema is entered, and diagnosis correctly changes to Mild to moderate preeclampsia, however, on the Referral screen Hypertension is also mentioned. Is that OK?

![image](https://user-images.githubusercontent.com/3536805/191448877-c5fa91fe-226e-4ab0-9d6a-a40650d7c836.png)

### Checked and approved:

1. Patient diagnosed with Pregnancy-induced hypertension, correct diagnosis is shown on the Medication distribution page.

Next steps|Medication distribution
-|-
![image](https://user-images.githubusercontent.com/3536805/191444377-9ede94bb-f339-4491-b913-a41a076bd652.png)|![image](https://user-images.githubusercontent.com/3536805/191444444-988dfaab-0af6-422e-98db-d4b5690f4c1a.png)

2. Mild to moderate preeclampsia diagnosis works fine.

BP|Edema|Diagnosis
-|-|-
![image](https://user-images.githubusercontent.com/3536805/191447359-60720981-1e7c-4106-bb49-c9a5ffbd8e92.png)|![image](https://user-images.githubusercontent.com/3536805/191447581-8a6ca31c-5096-4815-8027-839fc1aaf3f4.png)|![image](https://user-images.githubusercontent.com/3536805/191447627-f842d41e-b99a-40e5-ab85-8fd30ae62d22.png)

3. Patient with normal BP (120/80) and with severe headache and blurred vision is correctly diagnosed with severe preeclampsia and referred to hospital.

BP|Warning
-|-
![image](https://user-images.githubusercontent.com/3536805/191450595-f0860b03-127d-4427-b625-505e85243a97.png)|![image](https://user-images.githubusercontent.com/3536805/191450621-a3986fbc-4949-4669-a828-fed29d675708.png)

Referral|Progress report
-|-
![image](https://user-images.githubusercontent.com/3536805/191450672-d7d27e83-9940-48e8-99e9-6341a6137d1a.png)|![image](https://user-images.githubusercontent.com/3536805/191450731-697197c8-3ed5-4d43-8d15-7168cd3fc7cb.png)

4. Patient with Chronic hypertension and Headache and blurred vision is correctly diagnosed with severe preeclampsia, it is correctly stated on the hospital referral and progress report page too.

BP|Blurred vision
-|-
![image](https://user-images.githubusercontent.com/3536805/191452570-fea08019-29ce-4995-8892-d2531649b4de.png)|![image](https://user-images.githubusercontent.com/3536805/191452686-11df2347-f804-458e-93e8-5e53f24dd77e.png)

Referral|Progress report
-|-
![image](https://user-images.githubusercontent.com/3536805/191452801-6c95608e-ddf0-4327-8ad8-cd5a1d65d922.png)|![image](https://user-images.githubusercontent.com/3536805/191452888-3d9f7d46-f710-469b-b95b-e40f2c1f3142.png)

**Comment by adamhstewart** [comment]
> However, pregnancy induced hypertension is also shown.

Pregnancy induced hypertension which is converted to a more severe condition (preeclampsia, eclampsia) during the course of a single encounter after both phases of work, should be replaced rather than added on. That is only "pre-eclampsia" should appear in this case.

> Also, shouldn't we update the logic master document with the Pregnancy induced hypertension?

Yes, but waiting for @jeanette-pelizzon 's return on that.

> I think the induced should start with a lower case i on the Medication distribution page.

Should follow whatever capitalization convention we use throughout.

> however, on the Referral screen Hypertension is also mentioned. Is that OK?

No, as per above, hypertension should be replaced.

@anvmn @balagan73 ^^
