### ISSUE TITLE
ANC Labs - Rhesus Negative [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#342]
## Issue 

We currently do not have any logic for a negative rhesus in ANC. As background, the patient needs to receive a special sort of medicine that is only available at the hospital to avoid complications after birth. 

If a patient has negative rhesus: 

(1) refer to the hospital 
(2) Add to progress report "Referred to hospital for management of Rh-Negative status on XX/XX/XXXX" under obstetrical diagnosis section

## To Do: 

- create logic

**Comment by anvmn** [comment]
@balagan73 

Please test on nutrition env.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. When patients have negative rhesus result for blood group, they are referred to hospital, and it is indicated on the progress report page.

Hospital referral|Progress report
-|-
![image](https://user-images.githubusercontent.com/3536805/180946273-5c68bd73-198e-486c-9056-806ec1ea7d70.png)|![image](https://user-images.githubusercontent.com/3536805/180946311-6b190c2d-648c-4df0-9dac-86b7768d4d83.png)
