### ISSUE TITLE
ANC Subs - Next Steps - Health education as dynamic sub activity for both phases of encounter [3h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#346]
Follow up for #331 and #332

Health education may need to appear for Diabetes diagnoses.

<img width="291" alt="Screen Shot 2022-07-14 at 3 19 33 PM" src="https://user-images.githubusercontent.com/77505464/179076019-d995b780-5a8f-47ed-a162-dd63a65548dc.png"> 

### Todo:

- Introduce new field store signs of sencond phase, to allow a decision if certain educational task was completed or not.
- Develop logic

**Comment by anvmn** [comment]
@balagan73 

This restructuring was required as a result of analysing point 1 from #331.
Test for this change requires verification that Health Education subactivity can be saved both at initial and 'lab results' phases of encounter.

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. When patient was diagnosed with diabetes with updating historical lab results (https://github.com/TIP-Global-Health/eheza-app/issues/258), no health education displays for diabetes.

![image](https://user-images.githubusercontent.com/3536805/180951836-86f94c9b-93ef-455e-adf8-639269d12bbd.png)

2. Typo still exists on the health education panel.
![1-health-edu-diabetes](https://user-images.githubusercontent.com/3536805/180953059-4e1ba1b5-21b9-42b4-b870-17de7411b73e.png)

### Checked and approved:

1. Health education text displays for Diabetes, and also for Gestational diabetes. Also see image above.

Gestational diabetes:
![image](https://user-images.githubusercontent.com/3536805/180954220-991448b2-afeb-4503-bfca-feebc42712c2.png)

**Comment by anvmn** [comment]
@jeanette-pelizzon @balagan73 

> 1. When patient was diagnosed with diabetes with updating historical lab results no health education displays for diabetes.

Per #258 requirements, if patient was diagnosed with diabetes by updating historical lab results, they should be referred to hospital. Nothing else.


> 2. Typo still exists on the health education panel.

It's a know issue from #332, and will be handled there.

**Comment by jeanette-pelizzon** [comment]
Seems good to go? moving to acceptance testing since point 2 is being handled elsewhere
