### ISSUE TITLE
ANC - PostPartum - Infrastructure [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#352]
## Issue 

Postpartum will replace the pregnancy outcome encounter in ANC. This encounter type will have 9 activities: 

Pregnancy Outcome | Symptom Review | Maternal Mental Health | Breastfeeding
--|--|--|--
<img width="224" alt="Screen Shot 2022-07-25 at 10 19 09 AM" src="https://user-images.githubusercontent.com/77505464/180837164-12dcf20e-1c2b-498e-9afc-f9869dbcbd2f.png"> | <img width="223" alt="Screen Shot 2022-07-25 at 10 19 21 AM" src="https://user-images.githubusercontent.com/77505464/180837200-23ce0de4-0a9c-4723-8dad-257e3ebe535c.png"> | <img width="225" alt="Screen Shot 2022-07-25 at 10 19 27 AM" src="https://user-images.githubusercontent.com/77505464/180837227-a2effd2b-4655-4588-b706-cf5f1b10613c.png"> |<img width="223" alt="Screen Shot 2022-07-25 at 10 19 34 AM" src="https://user-images.githubusercontent.com/77505464/180837248-44ba9391-81aa-448e-9781-ce8e292ad0ed.png">

Examination | Family Planning | Prior Treatment History | Specialty Care | Next Steps
--|--|--|--|-- 
<img width="222" alt="Screen Shot 2022-07-25 at 10 19 41 AM" src="https://user-images.githubusercontent.com/77505464/180837274-1af7484a-1e3c-4e9d-80f0-2212f43ea123.png"> | <img width="222" alt="Screen Shot 2022-07-25 at 10 19 54 AM" src="https://user-images.githubusercontent.com/77505464/180837298-ac7e72ee-f0de-4fb7-95b1-225959c26e7d.png"> | <img width="221" alt="Screen Shot 2022-07-25 at 10 20 03 AM" src="https://user-images.githubusercontent.com/77505464/180837322-cb6eb9bf-5a2f-41c2-9686-0c214167c71a.png">| <img width="226" alt="Screen Shot 2022-07-25 at 10 20 38 AM" src="https://user-images.githubusercontent.com/77505464/180837345-836a6036-04e1-491b-b5db-da7cf417fb1c.png"> | <img width="61" alt="Screen Shot 2022-07-25 at 10 28 01 AM" src="https://user-images.githubusercontent.com/77505464/180838287-aa9cac19-1a5b-4769-a62c-11175b717f0d.png">

**Tray View**
<img width="204" alt="Screen Shot 2022-07-25 at 10 27 42 AM" src="https://user-images.githubusercontent.com/77505464/180838447-135f7c38-7dfa-404b-ae16-f9cd4356a974.png">

## Note: 

- Next steps only appears after all other activities have been completed 

## To Do: 

- Build out infrastructure for Post Partum encounter 
- Remove pregnancy outcome encounter (note: screens from this encounter are being used in the pregnancy outcome activity in the new postpartum encounter see #357)

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Can't find breastfeeding icon on Figma:

![Selection_983](https://user-images.githubusercontent.com/17882245/181067074-5eb86f20-d96b-45c4-ba81-ee3347ecccff.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn emailed it to you. All components are in [this figma file](https://www.figma.com/file/4Rbvi4x1Cxmwzq73Kwsqxk/Components?node-id=207%3A442)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. All the icons specified display during a postpartum encounter.
![image](https://user-images.githubusercontent.com/3536805/186856372-86989278-ce40-4f67-a6ef-96ce36a47b2b.png)
