### ISSUE TITLE
ANC - Update - Preeclampsia (Mild to Moderate) Logic [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#353]
## Issue 

*This issue is only dealing with Mild to Moderate Preeclampsia* 

As we tackled questions around the hierarchy of hypertension/preeclampsia, some other issues with the preeclampsia (mild to moderate) logic came to light. 

Currently, we diagnose preeclampsia and refer to the hospital. If a patient continues to have the same symptoms we would keep referring them. 

Now, when a patient is diagnosed with preeclampsia the first time, we will refer them to the hospital. When the patient returns to the health center for their next ANC visit, we will ask them in the History (Outside Care) activity if they were seen at another facility and diagnosed with anything. They would then say preeclampsia, we would ask what medication they were given. Then we would continue the encounter. (See related issues for updates to this) 

**Logic Change** Based on the patient's BP, we would determine what medication to give them in the next steps. It follows the exact same logic as hypertension. I have updated the logic document under subsequent visits with a preeclampsia continued care section. (see related issues for next steps screen)

Refer to logic document [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493). 

## Note 
- If a patient hits the logic for Severe Preeclampsia, we will bump them up to that as their diagnosis and this logic no longer applies to them. 
- Severe Preeclampsia should be referred every single time 
- Eclampsia should be referred every single time. Technically a patient should only ever be diagnosed once with eclampsia then sent to hospital to deliver baby but, just in case, keep it so it refers every single time. 
- Reminder that once a patient is diagnosed with preeclampsia they will never go back down to hypertension. 

## Related Issues 
- #354
- #355
- #356
- #340

**Comment by jeanette-pelizzon** [comment]
Logic for continued care can currently be found at line 107 in the Logic Master. This will change as we continue to add and move things in that document but just so you can find it easier now. 

// @anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Now, when a patient is diagnosed with preeclampsia the first time, we will refer them to the hospital. When the patient returns to the health center for their next ANC visit, we will ask them in the History (Outside Care) activity if they were seen at another facility and diagnosed with anything. They would then say preeclampsia, we would ask what medication they were given.

This requires a change at Outside Care activity, because right now, we do not offer a choice of medication for Preeclampsia. So, we'll need a new issue to offer these medications (identical to what we have for Hypertension, I suppose).


> **Logic Change** Based on the patient's BP, we would determine what medication to give them in the next steps. It follows the exact same logic as hypertension. I have updated the logic document under subsequent visits with a preeclampsia continued care section. (see related issues for next steps screen)

This will require determining which medication patient takes right now.
If we look at hypertension for example, even if we know from Outside care activity that patient was prescribed medication, we do not take this into account. So, if patient was diagnosed with hypertension, we'd consider only what we have prescribed. Do we do the same for Preeclampsia?


> Severe Preeclampsia should be referred every single time

Does it mean that it needs to be diagnosed every single time, or, if diagnosed once before, it's considered as a chronic diagnosis?

> Eclampsia should be referred every single time. Technically a patient should only ever be diagnosed once with eclampsia then sent to hospital to deliver baby but, just in case, keep it so it refers every single time.

Does it mean that it needs to be diagnosed every single time, or, if diagnosed once before, it's considered as a chronic diagnosis?

> Reminder that once a patient is diagnosed with preeclampsia they will never go back down to hypertension.

If patient is diagnosed with Severe preeclampsia can they go back to Moderate preeclampsia?
If patient is diagnosed with Eclampsia can they go back to Eclampsia?

**Comment by jeanette-pelizzon** [comment]
1. Yes, we made changes to outside care. See linked related issues in the description. 

2.  We should be taking into account the medication that a patient tells us they are getting from outside care. So if they are diagnosed with something outside - like hypertension- and tell us they are getting a medication, we should then provide the next steps recs based on that. Since we pull in the medication in next steps it should be pulling from the most recent one - wether it was their last visit with us or at an outside care facility. 

3. From my conversation with Wendy, she wants them referred to the hospital everytime they hit the qualifications for severe preeclampsia. 

4. Same as point 3. 

5. No, once they are diagnosed with something higher on the hierarchy they will never go back down. 

// @anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> 1. Yes, we made changes to outside care. See linked related issues in the description.

Only issue I see there is #355, and it about additional question on first page.
I'm talking about adding an option to choose mediaction that was given for Preeclapsia, on second page:

![image](https://user-images.githubusercontent.com/17882245/181309759-9ce341f8-99d1-4c37-b95c-e2cd34563d26.png)

> 2. We should be taking into account the medication that a patient tells us they are getting from outside care. So if they are diagnosed with something outside - like hypertension- and tell us they are getting a medication, we should then provide the next steps recs based on that. 

Got it. What do we do in case patient was given Preeclapsia diagnosis, but did not get medicine?

**Comment by jeanette-pelizzon** [comment]
@adamhstewart spoke with Wendy and we may be getting rid of the outside care subactivity so I can follow up on these but we may not need to. I would hold work on this @anvmn until we get the definite yes or no about the activity. 

@adamhstewart we didn't get to speak about in scrum yesterday - do you have any guidance moving forward?

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1.  When patients have >= 110 mmHg diastolic blood pressure OR >= 160 mmHg systolic BP and  edema (mild to moderate preeclampsia), they are diagnosed with preeclampsia, and also marked as high risk at the same time.
 
![image](https://user-images.githubusercontent.com/3536805/183292636-7a230fea-e9f4-438f-988c-9aae9f8fe5e9.png)

### Checked and approved:

1. Mild preeclampsia diastolic >=90 to <110 mmHg x 2 (separated by >2 hours) +

Warning|Edema|Protein in urine
-|-|-
![image](https://user-images.githubusercontent.com/3536805/183291334-a5c34a39-583b-4e06-9ac2-3f0b18b208a1.png)|![image](https://user-images.githubusercontent.com/3536805/183291447-235116cb-5d54-4193-bf34-f86961a790cf.png)|![image](https://user-images.githubusercontent.com/3536805/183291632-da22d219-3ab2-4441-9615-426c70871fa4.png)

2.  diastolic blood pressure >= 110 mmHg

Before urine test results|After urine test results (protein)
-|-
![image](https://user-images.githubusercontent.com/3536805/183292128-2cc36ca9-bdd9-4d55-a5d5-a7b790752f1e.png)|![image](https://user-images.githubusercontent.com/3536805/183292134-1c20fb4d-12c7-4365-af47-4f8a7e3ec9ac.png)

3. 160 mmHg > Systolic BP >=140 mmHg + edema
![image](https://user-images.githubusercontent.com/3536805/183293387-8726971d-4592-483f-9ba6-54869ce721de.png)

4. systolic BP >= 160 mmHg + edema

![image](https://user-images.githubusercontent.com/3536805/183293687-d00a6f56-1cab-4305-9942-459c789017b2.png)

6. EGA > 37 weeks

![image](https://user-images.githubusercontent.com/3536805/183294599-d72c3b4b-38ad-4487-bd85-caab8f94751d.png)

**Comment by adamhstewart** [comment]
@anvmn please check the single point above.

**Comment by anvmn** [comment]
@adamhstewart 

> When patients have >= 110 mmHg diastolic blood pressure OR >= 160 mmHg systolic BP and edema (mild to moderate preeclampsia), they are diagnosed with preeclampsia, and also marked as high risk at the same time. 

Before we had ANC logic, we had requirements for alerts at Medical and Obstetrical panes.
These alerts are for data collected at first encounter only.

Original requirements for the panes were implemented ~ 3 years ago (see, https://github.com/Gizra/ihangane/issues/1182, https://github.com/Gizra/ihangane/issues/1183). Then we were required to add more logic that included the `High Risk for Preeclampsia` (see https://github.com/Gizra/ihangane/issues/1199).

So, maybe we should drop some/all of these now, that we got ANC logic.
Or maybe we shoud have some distinction between Nurse and CHW?

**Comment by anvmn** [comment]
@adamhstewart 


> > When patients have >= 110 mmHg diastolic blood pressure OR >= 160 mmHg systolic BP and edema (mild to moderate preeclampsia), they are diagnosed with preeclampsia, and also marked as high risk at the same time.
> 
> Before we had ANC logic, we had requirements for alerts at Medical and Obstetrical panes. These alerts are for data collected at first encounter only.
> 
> Original requirements for the panes were implemented ~ 3 years ago (see, [Gizra/ihangane#1182](https://github.com/Gizra/ihangane/issues/1182), [Gizra/ihangane#1183](https://github.com/Gizra/ihangane/issues/1183)). Then we were required to add more logic that included the `High Risk for Preeclampsia` (see [Gizra/ihangane#1199](https://github.com/Gizra/ihangane/issues/1199)).
> 
> So, maybe we should drop some/all of these now, that we got ANC logic. Or maybe we shoud have some distinction between Nurse and CHW?

As we discussed, those alerts will be shown only for CHW.
Is this solution sufficient to close this issue?

**Comment by anvmn** [comment]
@adamhstewart ^^

**Comment by isapisa** [comment]
@adamhstewart ^^

**Comment by anvmn** [comment]
This is live for a while now, and no comments on this from field. Closing.
