### ISSUE TITLE
ANC Subs - Preeclampsia (Mild to Moderate) Next Steps [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#354]
## Issue 

*This issue is only dealing with Mild to Moderate Preeclampsia** 

If a patient is diagnosed with preeclampsia for the first time, we refer them to the hospital. 

Once a patient has been seen at the hospital, they will continue to return to the health center for their normal ANC visits. 

We will manage preeclampsia (Mild to Moderate) patients the same way that we manage hypertension patients. They will come for their visit, we work through the encounter, then based off of their vitals we will recommend changes to their medication. These changes are outlined in the [Master Logic](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) document. 

Here is what the next steps screen would like in this scenario: 

<img width="264" alt="Screen Shot 2022-07-25 at 1 28 32 PM" src="https://user-images.githubusercontent.com/77505464/180868427-eb9e6349-aa9b-4489-87ff-7d449aba2dec.png">

## Related Issues: 
- #353 

## To Do: 
- Update the next steps logic for preeclampsia 
- Update the screens per design

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env

**Comment by balagan73** [comment]
@jeanette-pelizzon Maybe this issue should be called ... Continued care instead of ... Next steps. Logic and their respective next steps were checked in https://github.com/TIP-Global-Health/eheza-app/issues/353

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. I think in the Logic sheet on line 110 systolic and diastolic is mixed up.
![image](https://user-images.githubusercontent.com/3536805/183410503-ccc1c0cb-5f0e-4859-87a1-f8c512e89822.png)

2. When patient at first encounter is diagnosed with Moderate preeclampsia, they are referred to hospital, and no medication is prescribed. In subsequent encounter even if patient enters medication given in outside care, it is not taken into account. 
When patient enters 110 diastolic BP, they are not referred to hospital.

**Comment by adamhstewart** [comment]
@anvmn please check

**Comment by anvmn** [comment]
@adamhstewart 

> 1. I think in the Logic sheet on line 110 systolic and diastolic is mixed up.

Correct, logic file is fixed already.

> 2. When patient at first encounter is diagnosed with Moderate preeclampsia, they are referred to hospital, and no medication is prescribed. In subsequent encounter even if patient enters medication given in outside care, it is not taken into account.
When patient enters 110 diastolic BP, they are not referred to hospital.

We don't tale outside care medication into account.
However, we do need to start treatment (as if there was none before) and when BP conditions indicate hospitalization, this should be suggested.

I made a fix for this at #475. It should be thoroughly testsed.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. At second encounter patient is referred to hospital with 110 diastolic bp.
![image](https://user-images.githubusercontent.com/3536805/192325447-b5966862-ff03-41ce-b645-eb64607a4e0d.png)
