### ISSUE TITLE
ANC Subs - Outside Care - Adding a Question [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#355]
## Issue 

The clinical team would like to add an additional question to the subactivity = outside care under the activity = history. 

**New Question**: Do you have follow up care planned with a specialist? 

<img width="249" alt="Screen Shot 2022-07-25 at 1 34 32 PM" src="https://user-images.githubusercontent.com/77505464/180869695-8f5625ed-bd85-4c81-a56f-59941d2a0a4f.png">

## Related Issue 
- #356 

## To Do: 
- Update screen style per design

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. The question displays under Outside care subactivity.

![image](https://user-images.githubusercontent.com/3536805/183390254-98f6e551-3ddf-4b04-84c0-731ddb148b0b.png)
