### ISSUE TITLE
ANC PostPartum - Pregnancy Outcome [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#357]
## Issue 

This activity is bringing all the screens and logic from the old pregnancy outcome encounter into an activity under the new postpartum encounter type. 

There have been no changes to the screens or the existing logic (if any existed at all).  

Tray View | One Screen 
--|--
<img width="242" alt="Screen Shot 2022-07-25 at 3 20 40 PM" src="https://user-images.githubusercontent.com/77505464/180883663-8e8facb6-63b7-4c43-8292-a18abf400d81.png"> |
<img width="239" alt="Screen Shot 2022-07-25 at 3 20 35 PM" src="https://user-images.githubusercontent.com/77505464/180883678-8d105d25-2568-45c6-aebd-fc19e25aae11.png">

## To Do: 
- Create Activity (may have been done in #352) 
- Style Screen per Design 
- Bring logic over from the existing encounter type

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Pregnancy outcome activity is available, screen looks like the design.

Screen|Outcome options
-|-
![image](https://user-images.githubusercontent.com/3536805/186904743-1ce8e8ef-6496-4244-b991-aa7b42088779.png)|![image](https://user-images.githubusercontent.com/3536805/186905028-6ecd82ea-6876-4af2-9bb3-56e3e8cc448a.png)
