### ISSUE TITLE
ANC PostPartum - Symptom Review [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#358]
## Issue 

We are adding a symptom review activity to the postpartum encounter. There are a few new symptoms added from the symptom review activity we have elsewhere in ANC. 

We are adding the symptoms highlighted in red here: 
<img width="188" alt="Screen Shot 2022-07-25 at 3 43 01 PM" src="https://user-images.githubusercontent.com/77505464/180886402-846585a1-4531-45d5-b065-f97b7f0280b9.png">

The symptom review should appear 2nd in the tray after pregnancy outcome. (See #352 for more details.) 

This activity consists of check boxes. Certain check boxes will lead to next steps. (See #359 for more details on logic. 

Tray View | Screen View 
--|--
<img width="375" alt="Screen Shot 2022-07-25 at 3 30 34 PM" src="https://user-images.githubusercontent.com/77505464/180885083-fe533daa-239d-4438-9ba8-ff40ea7d1a4e.png">|  <img width="371" alt="Screen Shot 2022-07-25 at 3 30 25 PM" src="https://user-images.githubusercontent.com/77505464/180885103-d02602f3-6747-4eaf-b7e9-fccc8e6e8c20.png">

## To Do: 

- Style Screen per Design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Here're the symptoms for standard encounter:

![Selection_985](https://user-images.githubusercontent.com/17882245/181223589-20277177-7279-47b8-ba83-6481f0246ec9.png)

I believe following fixes are needed for Postpartum design:

1. We have 'Leg Pain or Redness (One Leg)' so it should not be red.
2. Cough should be `> 2 weeks`.
3. 'Urinary Incontinence' appears twice - remove one.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. The new options display as requested with the modifiocatopms according the comment from @anvmn 
![image](https://user-images.githubusercontent.com/3536805/186905834-d3e44d28-5bb9-4517-9290-b35b085541a1.png)
