### ISSUE TITLE
ANC PostPartum - Symptom Review Logic [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#359]
## Issue 

_Note: in the app all symptoms should appear grey, used two different colors to help explain here._ 

<img width="188" alt="Screen Shot 2022-07-25 at 3 43 01 PM" src="https://user-images.githubusercontent.com/77505464/180887318-6eeb3ff6-2a46-4bf9-a460-c45e3471f94b.png">

**Grey Symptoms** 
These symptoms already have logic built out for them in the ANC module. That logic should stay the same in the post partum encounter. This includes: any conditional screens (follow-up questions) and next steps 

**Red Symptoms**
These symptoms are new and introduce new logic. If selected, any one of these new symptoms will result in a pop-up in next steps telling the user to follow postpartum protocols. 

There are NO follow-up question screens for these symptoms.

Here is an example of the pop up. The symptom should populate where it says headache. 
<img width="261" alt="Screen Shot 2022-07-25 at 3 54 04 PM" src="https://user-images.githubusercontent.com/77505464/180887562-a3ad29f9-9c80-4c8a-9e88-aa0854630e91.png">

## To Do: 
- Create logic for new symptoms 
- Style pop up per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Logics master got duplicate handling for `Urinary Incontinence`:

![Selection_989](https://user-images.githubusercontent.com/17882245/181302855-2acb6462-96e0-4eeb-9098-16db53d9335c.png)

Which one is correct?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> If selected, any one of these new symptoms will result in a pop-up in next steps telling the user to follow postpartum protocols.

We already have one popup when entering Next steps. It lists all diagnoses.
For example:
![Selection_990](https://user-images.githubusercontent.com/17882245/181303257-53ba4b17-563e-4c9e-805e-c87863b2d59f.png)

There will be such diagnoses at Postpartum encounter, and there can not be 2 popups.
So, we'll have to combine the two into one. Can you make a design please?

**Comment by jeanette-pelizzon** [comment]
> Logics master got duplicate handling for `Urinary Incontinence`:
> Which one is correct?

Apologies, we added the urinary incontinence logic later and I didn't catch this duplicate. It should result in the diagnosis urinary incontinence and be referred to hospital. I have updated the logic master to reflect this. @anvmn

**Comment by jeanette-pelizzon** [comment]
@anvmn design here: 

![Uploading Screen Shot 2022-07-28 at 2.13.15 PM.png…]()

**Comment by anvmn** [comment]
@jeanette-pelizzon ^^ did not upload well, but I found it on Figma:

![Selection_1000](https://user-images.githubusercontent.com/17882245/182023637-66b6bca6-7793-4ec0-bb3b-1cdc0b965361.png)

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> If selected, any one of these new symptoms will result in a pop-up in next steps telling the user to follow postpartum protocols.

This definition is problematic, because there may not be any next steps - for example, if only symptom is headache, and no other diagnoses are made. 
Is it acceptable, that popup will not show in such cases?

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Popup displays and shows the diagnoses as agreed.
![image](https://user-images.githubusercontent.com/3536805/186908987-f4ca3aad-9354-4d87-ade9-b7f9bc539241.png)
