### ISSUE TITLE
ANC PostPartum - Maternal Mental Health Logic [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#361]
## Issue 

Logic for Maternal Mental health in postpartum is exactly the same #291. Please see questions/answers in that thread. 

## To Do: 
- Style Screens per Design 
- Logic

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

 ### QA Review

### Checked and approved:

1. I confirm the Maternal mental health questions work as expected.

Depression Not Likely: 0-8 points
Depression Possible: 8-12 points
Fairly High Possibility of Depression: 13-14 points
Probable Depression: 14+ points
Suicide Risk - Any answer to suicidal question except 'Never'
