### ISSUE TITLE
ANC PostPartum - Next Steps -  Early Mastitis or Engorgement [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#363]
## Issue 

If a patient meets the criteria for Early Mastitis or Engorgement, the next steps are to provide health education and distribute medication. 

See [Logic Master](url) for diagnosis criteria.

Pop Up | Health Education | Medication Distribution 
--|--|--
<img width="319" alt="Screen Shot 2022-07-25 at 6 57 15 PM" src="https://user-images.githubusercontent.com/77505464/180905952-f6c014dc-b546-458e-b8aa-5206350a7136.png"> | <img width="311" alt="Screen Shot 2022-07-25 at 6 57 22 PM" src="https://user-images.githubusercontent.com/77505464/180905956-bca03de1-3f7d-4883-ac04-924a8f48056d.png"> | <img width="311" alt="Screen Shot 2022-07-25 at 6 57 32 PM" src="https://user-images.githubusercontent.com/77505464/180905957-0768b9cf-ba4e-4814-8077-1bfe6622175c.png">

## To Do: 
- Style screens per design 
- Create diagnosis logic

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Typo. Even in the Logic sheet Engorgement is misspelled as 'Engorgment'

Warning|Health education|Progress report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/187140351-4024a1cc-e8f8-4695-bc79-e427bee1bcb8.png)|![image](https://user-images.githubusercontent.com/3536805/187140487-caf8809b-6ad9-4f98-86ad-c89cb1e3b1d7.png)|![image](https://user-images.githubusercontent.com/3536805/187141155-47602f41-77be-4cf5-96ed-04ecc36e8eb5.png)

2. When patients are not breastfeeding, but have pain or redness, they are not diagnosed with Mastitis or Engorgement. The checkboxes are indeed radio boxes, and it is only possible to select for example Redness or Pain, but not both.
![image](https://user-images.githubusercontent.com/3536805/187142165-70d339a8-773e-4f88-8efb-62084327442f.png)



### Checked and approved:

1. The Warning, Health education and Medication distribution screens display correctly (except the above mentioned typos), if examination is anything but normal, or when answer to Breastfeeding is yes, and patients are experiencing pain or redness.

Medical distribution
![image](https://user-images.githubusercontent.com/3536805/187140967-6d960a33-cc90-4101-bdb7-a4a4bed9039f.png)

**Comment by adamhstewart** [comment]
@Diama1 assigning to you to correct the spelling mistake of "engorgement" identified above.

@jeanette-pelizzon can you also (a) correct on the logic sheet; (b) confirm we should be able to have multiple options in the second point of @balagan73 's review above?

**Comment by anvmn** [comment]
@adamhstewart @jeanette-pelizzon 
For the context, so far, when asking `why not`, there was only single option allowed.
