### ISSUE TITLE
ANC PostPartum - Next Steps - Mastitis

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#364]
## Issue 
If a patient meets the criteria for Mastitis, the next steps are to provide health education and distribute medication. 

See [Logic Master](url) for diagnosis criteria.

Pop Up | Health Education | Medication Distribution 
--|--|--
<img width="199" alt="Screen Shot 2022-08-10 at 11 24 15 AM" src="https://user-images.githubusercontent.com/77505464/183988566-54da60e3-4502-4e9d-9aab-2b22458718c7.png"> | <img width="197" alt="Screen Shot 2022-08-10 at 11 24 19 AM" src="https://user-images.githubusercontent.com/77505464/183988657-75a3acde-bdd4-4689-ab5a-589bf160d0a9.png"> | <img width="200" alt="Screen Shot 2022-08-10 at 11 24 23 AM" src="https://user-images.githubusercontent.com/77505464/183988707-386bcf85-81d9-4963-91f8-a97b56143ffd.png">

## To Do: 
- Style screens per design 
- Update logc associated with mastitis

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Did we get needed info to complete this issue preparation?

**Comment by jeanette-pelizzon** [comment]
updated @anvmn

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. Typo:
Penicillin is misspelled on the Medication distribution screen.

![image](https://user-images.githubusercontent.com/3536805/187146292-7fc824a9-d304-43cf-b72c-a5b58229b17a.png)

2. Only paracetamol is followed by the word 'or'. See the screenshot above. Do we really need that?

### Checked and approved:

1. If patients have ((Redness or pain) under Breastfeeding OR they have (Warmth or discharge)) under Examination -> Breast exam, AND they have Fever under Symptom review, they are diagnosed with Mastitis, and proper screens display.

Health education|Medication distribution|Progress report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/187147216-85d62a15-78a4-4a62-8c46-6512fb30e285.png)|![image](https://user-images.githubusercontent.com/3536805/187147257-7c3bfc0d-a548-4524-86b4-371873fd3c9e.png)|![image](https://user-images.githubusercontent.com/3536805/187147364-2c2617aa-ef92-41cd-8629-0c071207c91e.png)

**Comment by adamhstewart** [comment]
@Diama1 Please correct the two points (spelling and extraneous "or") identified above.
