### ISSUE TITLE
ANC PostPartum - Physical Exam [10h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#366]
## Issue 

The post-partum encounter will have a physical exam activity. This activity has several sub-activities, below I have listed which ones are staying the same and which are changing: 

- Vitals -> stays the same 
- Nutrition -> stays the same 
- Core -> stays the same 
- Obstetrical Exam -> NOT in this encounter
- Breast Exam -> *add in an option for "warmth"*

We are adding in a new sub-activity called "GU Exam." This sub-activity has conditional questions. 

Initial Screen | Perineal Tear = No  | Perineal Tear = Yes(this has conditional answers)
--|--|--
<img width="283" alt="Screen Shot 2022-07-25 at 7 17 37 PM" src="https://user-images.githubusercontent.com/77505464/180908484-59c14d5f-7da9-4d12-9f47-c3595e0c208e.png"> |<img width="284" alt="Screen Shot 2022-07-25 at 7 18 00 PM" src="https://user-images.githubusercontent.com/77505464/180908558-b294c529-738d-46bf-89a7-90ce0d2f7f3c.png"> |<img width="288" alt="Screen Shot 2022-07-25 at 7 17 52 PM" src="https://user-images.githubusercontent.com/77505464/180908725-b610a4d6-ef9f-4a27-a170-1ccd163c8d81.png">

Perineal Tear = Yes, Healing Normal = Yes | Perineal Tear = Yes, Healing Normal = No 
--|--
<img width="284" alt="Screen Shot 2022-07-25 at 7 18 00 PM" src="https://user-images.githubusercontent.com/77505464/180909053-8bbf03b0-e328-4814-a43e-661ab71e4e8f.png"> | <img width="308" alt="Screen Shot 2022-07-25 at 7 23 55 PM" src="https://user-images.githubusercontent.com/77505464/180909082-9c73dc7e-dd18-4448-9747-07b596549535.png">

## To Do:
- Carry over physical exam subacitvities 
- Get rid of Obstetrical Exam 
- Add in GU Exam 
- Style GU exam screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Breast Exam -> Stays the same

Warmth option does not exist at Breast Exam.

Design at Figma:

![Selection_1021](https://user-images.githubusercontent.com/17882245/183853655-c9b23ac6-335a-4d07-852a-0cc8ca683c54.png)

Actual:

![Selection_1020](https://user-images.githubusercontent.com/17882245/183853705-608465a2-525f-4b09-bdc5-6c6867c96b01.png)

So, should Breast exam stay the same?

**Comment by jeanette-pelizzon** [comment]
Good catch, that must have been a quick change in a meeting. We need to update breast exam. Do you want me to add it and some hours to this issue or create a new one?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

This can be part of current issue.
Question - should this be added only at Postpartum encounter, or for all types of encounters?

**Comment by jeanette-pelizzon** [comment]
Only postpartum. 

updated main issue to reflect adding warmth option to the breast exam

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. On the GU exam screen the Rectal hemorrhoids option is not displayed initially, but only later when any answer is selected for the perineal tear question. Why are we showing it conditionally, when it will always display anyway?
![image](https://user-images.githubusercontent.com/3536805/187144463-908ae1c5-4cfc-4ccd-af8b-2993ea0f84a9.png)

### Checked and approved:

1. Warmth option is included on the Breast exam screen under Examination.
![image](https://user-images.githubusercontent.com/3536805/187143574-d1419cea-8fa7-4673-a25b-612e156faae7.png)

2. Requested sub-activities are available. GU exam sub-activity is available with requested options.

![image](https://user-images.githubusercontent.com/3536805/187144115-9d994ae0-c652-4677-b38c-5da8c949584a.png)

**Comment by adamhstewart** [comment]
@jeanette-pelizzon is there supposed to be conditional logic on the perineal tear question?
