### ISSUE TITLE
ANC Post Partum - Next Steps - Excessive Bleeding [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#367]
## Issue 

If the patient meets the criteria outlined in the[ Master Logic doc](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) for excessive bleeding they should be referred to hospital for further evaluation. Next steps for excessive bleeding happens in the next steps section and does not interrupt the flow of the encounter. 

Pop Up Design: 
<img width="346" alt="Screen Shot 2022-07-25 at 7 28 43 PM" src="https://user-images.githubusercontent.com/77505464/180909690-3ae42a41-cf8f-49c7-a37c-330ae17e1b0b.png">

**Referral Screen** - same as usual 

## To Do: 
- Logic for excessive bleeding 
- Style pop up screen per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

This issue is not assigned for a reason?

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Patients are diagnosed with Infection when under Examination -> GU Exam subactivity Perineal tear is not healing normally.

Warning|Referral|Progress report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/187150653-29795f29-6df1-4de7-90b3-50b0bb32e2d2.png)|![image](https://user-images.githubusercontent.com/3536805/187150720-22c0c490-5fbd-486b-bfce-09fea52e495b.png)|![image](https://user-images.githubusercontent.com/3536805/187150817-05a3efe8-a7ca-494f-ac81-145356eee1c4.png)

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. When Bleeding is selected under Examination -> GU exam, Excessive bleeding is diagnoses, and correct screens display.

Warning popup|Referral|Progress report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/187158833-1d047687-468d-4e57-aa39-dcb1b504a296.png)|![image](https://user-images.githubusercontent.com/3536805/187158889-d160813b-b0c9-4cfb-95b3-f490eda80caa.png)|![image](https://user-images.githubusercontent.com/3536805/187158946-41e95af7-2d52-4625-ae13-51d7b34bb4b5.png)
