### ISSUE TITLE
ANC PostPartum - Next Steps - HIV [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#368]
## Issue 
If a patient was diagnosed with HIV at some point during their pregnancy, and they are not already enrolled in an ARV services program (determined in specialty care review) then we will refer them to ARV services for continuous care post-pregnancy. 

This is the referral screen for ARV services: 

<img width="279" alt="Screen Shot 2022-07-25 at 7 32 37 PM" src="https://user-images.githubusercontent.com/77505464/180910451-7a65a572-1517-4417-b427-b26efd958813.png">

This is the wording/screen that the clinical team decided on. 

## Related Issues: 
- #376 

## To Do
- Create logic 
- Style next steps screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

When patient is diagnosed with HIV, we ask if there's HIV/PMTC program at HC:

![Selection_1045](https://user-images.githubusercontent.com/17882245/185369972-c35439ce-69e7-4917-96f3-1d18054abfff.png)

Then, at Next steps, we refer to Integration HIV/PMTC:

![Selection_1044](https://user-images.githubusercontent.com/17882245/185370171-1e84bf21-de9b-4d4f-b731-89d6975ffbea.png)

In this issue, instead of using Integration HIV/PMTC, we say ARV services.

Are these 2 different programs? If not, shouldn't we have common name for this?

**Comment by jeanette-pelizzon** [comment]
We should have a common name. There was a large discussion around this ages ago and I believe we settled on ARV service as that's what we refer to it as in newer screens. 

Let's go with ARV services.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Patient doesn't have HIV, only the partner has a positive test result, and we are referring the patient to ARV services, saying they have HIV. Is that OK?
![image](https://user-images.githubusercontent.com/3536805/187181619-e5135399-f48e-4956-a145-6e433234795c.png)


For this patient even partner was diagnosed negative.

Next steps|Patient info
-|-
![image](https://user-images.githubusercontent.com/3536805/187184198-2979cfe0-3bb9-4a1d-8cf7-848679cd5db7.png)|![image](https://user-images.githubusercontent.com/3536805/187184270-96a05309-bcd9-493f-ae9c-36541f491d63.png)



### Checked and approved:

1. Patient is referred to ARV services, if they were diagnosed with HIV during pregnancy, and they are still not enrolled in ARV services.
![image](https://user-images.githubusercontent.com/3536805/186858037-0381ec64-a072-416f-b5f7-f392934ffeed.png)

**Comment by adamhstewart** [comment]
@balagan73 I'm guessing here that this is a result of a different HIV diagnoses during teh preganancy.

@anvmn can you confirm?

**Comment by anvmn** [comment]
@adamhstewart 

This needs looking into.

**Comment by anvmn** [comment]
@adamhstewart 

What needs to happen is that if patient is dignosed with Discordant Partnership, the header at next steps should say so. Fixed at #475.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Typo on the HIV laboratory page.
![image](https://user-images.githubusercontent.com/3536805/191433633-899fadad-5a81-42e2-b3ca-ea0105edc38a.png)

2. Discordant partnership is not diagnosed when partner hes suppressed viral load. Diagnosis definition in the logic master document doesn't mention this. Is this OK?
![image](https://user-images.githubusercontent.com/3536805/191433982-b6521620-6607-4e15-be00-595300c0e426.png)

### Checked and approved:

1. Patient is not referred to ARV services, if partner is diagnosed with HIV.

Partner has HIV|No referral
-|-
![image](https://user-images.githubusercontent.com/3536805/191291985-afa2e491-5457-4737-9773-ef3aa64690df.png)|![image](https://user-images.githubusercontent.com/3536805/191292079-d8393f5f-ec00-4b9f-8f31-c1b549caa7da.png)
