### ISSUE TITLE
ANC PostPartum - Next Steps - Diabetes [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#369]
## Issue

If a patient was diagnosed with any type of diabetes (Gestational or Normal Diabetes) during their pregnancy we need to refer them to a NCD services for continued treatment post-pregnancy. 

Here is the NCD services referral screen: 
<img width="291" alt="Screen Shot 2022-07-25 at 7 36 03 PM" src="https://user-images.githubusercontent.com/77505464/180910839-23fa2776-4e26-4f49-8c8c-e0c6488ca163.png">

This is the wording/screen design the clinical team decided on.

## Related Issues: 
- #377 

## To Do: 
- Logic 
- Style NCD service referral screen per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. If patients are diagnosed with Gestational Diabetes or Diabetes, they are referred to NCD services.

Gestational Diabetes|Diabetes
-|-
![image](https://user-images.githubusercontent.com/3536805/186858608-4dff51b6-5f46-4a5a-a333-5b07c102944f.png)|![image](https://user-images.githubusercontent.com/3536805/187134715-4efb36b2-7212-4dd1-a4ae-084fde53e6ad.png)
