### ISSUE TITLE
ANC PostPartum - Next Steps - Hypertension, Preeclampsia, Eclampsia

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#370]
## Issue

If a patient was diagnosed with any type of hypertension, preeclampsia or eclampsia during their pregnancy we need to refer them to NCD services for continued treatment post-pregnancy. 

Here is the NCD services referral screen for hypertension: 
<img width="238" alt="Screen Shot 2022-07-25 at 7 42 58 PM" src="https://user-images.githubusercontent.com/77505464/180911733-b3b66020-022b-4d01-b0d2-63e9b49da1fb.png">

This is the wording/screen design the clinical team decided on.

## Related Issues: 
- #377 

## To Do: 
- Logic 
- Style NCD service referral screen per design

**Comment by jeanette-pelizzon** [comment]
@leowea do we refer people to NCD services only for chronic hypertension? Or do we include gestation hypertension, preeclampsia, and eclampsia as well?

**Comment by leowea** [comment]
@Jeanette Pelizzon ***@***.***> we would refer all of
these situations to NCD services.


Wendy Leonard, MD, AAHIVS

Executive Director

TIP Global Health (formerly The Ihangane Project)

***@***.*** | +1 831 234 6053
www.tipglobalhealth.or <http://www.tipglobalhealth.org/>g



*Hope lies in dreams, in imagination, & in the courage of those who dare to
make dreams into reality. **- Jonas Salk*

**Comment by jeanette-pelizzon** [comment]
Thank you. 

@anvmn I updated the main issue. This should be good to work on now.

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. Gestational hypertension|Chronic hypertension

Gestational|Chronic hypertension|Mild &Moderate preeclampsia|Severe preeclampsia|Eclampsia
-|-|-|-|-
![image](https://user-images.githubusercontent.com/3536805/186664047-d58695d5-1bb8-4a9f-9435-41939fa94f6e.png)|![image](https://user-images.githubusercontent.com/3536805/187176091-0cb4c97e-f171-4e25-9d0b-701beef24321.png)|![image](https://user-images.githubusercontent.com/3536805/187181917-74cb46d3-6f80-4b02-a5d9-d1f8f8f41a2c.png)|![image](https://user-images.githubusercontent.com/3536805/187183924-f70819eb-6527-48a3-b7d5-2fe82cded20a.png)|![image](https://user-images.githubusercontent.com/3536805/187185376-9d8a7b43-b84e-4f5f-878b-c4fac680e489.png)
