### ISSUE TITLE
ANC PostPartum - Next Steps - Urinary Incontinence [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#371]
## Issue 

If the symptom "urinary incontinence" is selected during the symptom review, the patient should be referred to the hospital in the next steps section. Hospital referral screen should be the usual one. Pop-up for this diagnosis is below. 

<img width="320" alt="Screen Shot 2022-07-25 at 7 44 12 PM" src="https://user-images.githubusercontent.com/77505464/180911824-63fd0d2a-2f49-483b-baf8-8d65b3b18f04.png">

Please reference the [Logic Master](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) for more details. 

## To Do: 

- Update logic 
- Style pop up per design

**Comment by adamhstewart** [comment]
@balagan73 I oodn't see a QA report here, was it combined with another issue?

**Comment by balagan73** [comment]
@adamhstewart I might have assigned it to you accidentally. Will QA this.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. When Urinary incontinence is selected under Symptom preview, patient is referred to hospital.

Warning|Hospital referral|Progress report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/187384314-86a2d99e-cc1a-4d22-84fc-acc5c4b3e7c3.png)|![image](https://user-images.githubusercontent.com/3536805/187384719-6e9e0e19-82cd-4430-b47a-c984415916fe.png)|![image](https://user-images.githubusercontent.com/3536805/187384909-b9c0f7a4-b21d-4ff9-b6ae-ceebc0fe81d7.png)
