### ISSUE TITLE
ANC Post Partum - Next Steps - Infection [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#372]
## Issue 

If the patient meets the criteria for infection as outlined in the postpartum section of the [logic master](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493), then they should be referred to the hospital. The hospital referral screen is the usual one. Pop-Up design for this diagnosis is below: 

<img width="320" alt="Screen Shot 2022-07-25 at 7 44 12 PM" src="https://user-images.githubusercontent.com/77505464/180912136-6278d16b-8964-48b7-988e-a6d136b882f4.png">

## To Do 
- Update Logic 
-  Style next steps screen per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Don't understand the `OR yes to preinium question` part:

![Selection_1028](https://user-images.githubusercontent.com/17882245/184080431-a33cb9c1-328e-4d9c-b493-9cce9e7153e9.png)

This is the only question that fits the description:

![Selection_1029](https://user-images.githubusercontent.com/17882245/184080541-365044ad-067e-4f25-8f3f-267f1526ed38.png)

However, I don't see why Yes answere would indicate Infection.
Also, it must be ansered Yes, and `Is healing normally` should be answered No to get to `Episiotomy = Swelling or Discharge` part.

**Comment by jeanette-pelizzon** [comment]
1. updated the logic doc to make more sense since we changed the screen. They need to have tear = yes, healing normally = no --> infection. Any of those checkboxes under there would result in them being referred to hospital. 

<img width="519" alt="Screen Shot 2022-08-15 at 3 52 00 PM" src="https://user-images.githubusercontent.com/77505464/184734120-028c46b4-7363-49fd-9f84-ae6d1440c55a.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

If I undestand ^^ properly, logics doc needs following update:

![Selection_1037](https://user-images.githubusercontent.com/17882245/184939597-09ac2e24-92ad-4402-bddb-f5f806215e1c.png)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Patient is not diagnosed with Infection, if Infection is selected under Examination -> Breast exam.
@jeanette-pelizzon: If the answer to https://github.com/TIP-Global-Health/eheza-app/issues/372#issuecomment-1216925234 is yes, it affects the Early Mastitis or Engorgement scenario as well. Currently selecting Infection results in Early Mastitis diagnoses.

![image](https://user-images.githubusercontent.com/3536805/187154598-da6797fc-4116-430e-88c6-19b1d9d3777f.png)
 


### Checked and approved:

1. Patients are diagnosed with Infection when under Examination -> GU Exam subactivity Perineal tear is not healing normally.
OR Vaginal examination -> Foul smelling lochia is selected.


Warning|Referral|Progress report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/187150653-29795f29-6df1-4de7-90b3-50b0bb32e2d2.png)|![image](https://user-images.githubusercontent.com/3536805/187150720-22c0c490-5fbd-486b-bfce-09fea52e495b.png)|![image](https://user-images.githubusercontent.com/3536805/187150881-d7d3ebf9-f5f1-4038-9f60-9b507a709b9f.png)
