### ISSUE TITLE
ANC PostPartum - Family Planning [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#373]
## Issue 

The family planning already exists elsewhere in the ANC module. We need to pull that over and add it as an activity to the post-partum encounter. 

Here is what the screen should look like: 

<img width="344" alt="Screen Shot 2022-07-25 at 7 52 08 PM" src="https://user-images.githubusercontent.com/77505464/180912917-6d5cefc9-6abe-43df-beb3-a655d24159df.png">

There is no next steps logic associated with this activity but, I believe, we do track the answers on the back end for reporting purposes. 

## To Do: 
- Style screen per design 
- Save info in backend (if we are already doing that for the other places this activity type exists. If not, then don't worry about it)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Screen for family planning displays correctly under Postpartum encounter.

![image](https://user-images.githubusercontent.com/3536805/187138590-74594837-6780-417e-83f2-a34f3d3c5981.png)
