### ISSUE TITLE
ANC PostPartum - Prior Treatment Review [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#374]
## Issue 

This activity checks in to see what supplements the mother received during/after labor. 

<img width="342" alt="Screen Shot 2022-07-25 at 8 03 52 PM" src="https://user-images.githubusercontent.com/77505464/180914267-2b846f87-9e39-45bb-8199-b7b5c0ea7f76.png">

## To Do: 
- Style screen per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Treatment review screen looks like the design.
![image](https://user-images.githubusercontent.com/3536805/186910040-51323df0-fcfe-49b0-a3c3-e658a82de154.png)
