### ISSUE TITLE
ANC PostPartum - Treatment Review - Next Steps [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#375]
## Issue 

<img width="342" alt="Screen Shot 2022-07-25 at 8 03 52 PM" src="https://user-images.githubusercontent.com/77505464/180914361-3df5d9f9-9274-4bb5-9a15-2102c0ec4efd.png">

If a patient answers no to Vitamin A, we will distribute 200,000 IU of Vitamin A in next steps. 

Pop Up | Medication Distribution 
--|--
<img width="326" alt="Screen Shot 2022-07-25 at 8 06 39 PM" src="https://user-images.githubusercontent.com/77505464/180914816-3ad16c9c-89bb-4734-9d95-1f2534d381bd.png"> | <img width="281" alt="Screen Shot 2022-07-25 at 8 08 48 PM" src="https://user-images.githubusercontent.com/77505464/180914819-936b10e1-aa1b-4adc-b81b-52026e202a04.png">

If the patient answers no to folic acid, nothing is done. 

## To Do: 
- Update logic 
- Style next steps screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

About that popup, if we really need it, we have same problem as at https://github.com/TIP-Global-Health/eheza-app/issues/359#issuecomment-1197011850. It needs to fit somehow inside that one popup we show on Next Steps.

**Comment by isapisa** [comment]
@jeanette-pelizzon

**Comment by anvmn** [comment]
@jeanette-pelizzon per our conversation yesterday, we'll show the popup immediatly after activity is saved.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. No popup displays after answering No to the question, nor after filling out all other activities.

2. Should administering Vitamin A be displayed in the progress report?
![image](https://user-images.githubusercontent.com/3536805/186913403-8504c271-c00c-48dd-81eb-2c0832aa4d4c.png)


### Checked and approved:

1. If no Vitamin A was administered, the Medication distribution panel shows instructions to give patient Vitamin A.
![image](https://user-images.githubusercontent.com/3536805/186912821-4f71f341-eecb-4eb8-aa4a-09d4887b5855.png)

**Comment by adamhstewart** [comment]
@adamhstewart please check @balagan73 's points and if OK move to acceptance.

**Comment by anvmn** [comment]
@adamhstewart 

> 1. No popup displays after answering No to the question, nor after filling out all other activities.

Fixed at #475.

> 2. Should administering Vitamin A be displayed in the progress report?

I'm no the one who defines the requirements, but as far as current requirements state, this is not needed.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Popup displays after answering No to the Vitamin A question.

![image](https://user-images.githubusercontent.com/3536805/192317002-3bdb3882-9b4a-412a-8706-5f145f73140f.png)
