### ISSUE TITLE
ANC PostPartum - Specialty Care - HIV [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#376]
## Issue 

If a patient was diagnosed with HIV during their pregnancy, the specialty care review activity will populate in the activity tray. 

This activity allows the nurses to check in with the patient to ensure they that they are set-up with continuous care now that their pregnancy is over. 

<img width="345" alt="Screen Shot 2022-08-17 at 8 21 03 AM" src="https://user-images.githubusercontent.com/77505464/185178767-25a56a37-3f02-46c9-8d5a-80b6531c33e2.png">

If they are not already enrolled in a program we will refer them to ARV services. 

## Related Issues 
- #368 
- #369 
- #370

## To Do 
- Style screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

There're gaps at requirements here, because HIV diagnosed patient may not have a treatment plan.
For example, if patient was referred to HIV program, they might have got treatmet but we do not know what it is.
Another case is where patient is supposed to be prescribed with medicine, was not (for whatever reason), as we provide this option.

**Comment by jeanette-pelizzon** [comment]
I think as a work around we have "Given medication by PMTCT" as the treatment plan if they were given medication by PMTCT that wasn't one that we list in outside care. 

In subs visit we ask in outside care if they were given two diff meds and they could answer that they were given none of those. Then in treatment review we ask about HIV medication again and if they were given medicine from PMTCT then we just keep moving. I think if they say they got the medication from PMTCT we just have that populate here as the treatment plan.

**Comment by jeanette-pelizzon** [comment]
@anvm updated the screen designs for specialty care review. I updated the main issue to reflect the changes. The flow stays the same, screen design changes. Hopefull this simplifies things!

**Comment by anvmn** [comment]
@jeanette-pelizzon  @adamhstewart 

Since there are 2 options for referrals, we'll have to make it multiple referral form, similar to what we're doing at https://github.com/TIP-Global-Health/eheza-app/pull/414.
This is complex develpment. We could save some time if we did not have the `Why not` part.

So, the question is whether or not that data is really needed.

**Comment by jeanette-pelizzon** [comment]
@anvmn got an answer for this. We really just need to ensure they are enrolled in a program and if not refer them to the appropriate program. The treatment plan stuff is not important (at this time). Updated main issue and design.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> If a patient was diagnosed with HIV during their pregnancy

We're talking here only of case where HIV dignosis was made during current pregnancy?
No need to send to ARV when patient is know to be positive, or got Discordant Partnership diagnosis?

**Comment by jeanette-pelizzon** [comment]
Got an answer. Refer all -  known positive, new positive, discordant- to ARV services. // @anvmn

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. When patient was diagnosed with HIV during pregnancy, in the postpartum encounter the Specialty care icon displays and makes sure they are enrolled in ARV services.

![image](https://user-images.githubusercontent.com/3536805/186857142-fee6979b-edfe-4ba6-8bd7-b3a39cfbd6a0.png)

If the answer is NO under the Specialty care, then patient is referred to ARV services.
![image](https://user-images.githubusercontent.com/3536805/186857579-1a490f37-c4bc-4ac5-aa84-46512f78db9e.png)
