### ISSUE TITLE
ANC Post Partum - Specialty Care Review -  Hypertension

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#377]
## Issue 

If a patient was diagnosed with a Hypertension related issue during their pregnancy, the specialty care review activity will populate in the activity tray. That means preeclampsia, eclampsia, or any sort of hypertension. 

This activity allows the nurses to check in with the patient to ensure they are set-up with continuous care now that their pregnancy is over. 

<img width="381" alt="Screen Shot 2022-08-17 at 8 21 36 AM" src="https://user-images.githubusercontent.com/77505464/185179100-c26667ce-77e6-4e9b-be3a-4f21099dcee4.png">

If they are not following a plan still we will refer them to NCD services. 

Note: hypertension (which is written in blue) should update with the appropriate hypertension-related diagnosis - eclampsia, preeclampsia, or hypertension

## Related Issues 
- #368 
- #369 
- #370

## To Do 
- Style screens per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

On all usecases where we diagnose Diabetes, patient is referred to hospital.
We never prescribe any medicational treatment. Maybe this issue should be only about Hypertension
(or Hypertension + Preeclampsia, since we treat it as well)?

**Comment by jeanette-pelizzon** [comment]
So this was created before we decided to not pull in the outside care treatment plans. We do want to make sure people with diabetes are being referred to NCD services post-partum though. I agree with you and think we can do this specialty care flow for HIV and Hypertension/Preeclampsia. However, if someone was diagnosed with diabetes or gestational diabetes during their pregnancy then we need to ensure we refer them to NCD services in next steps.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

No problem. Lets change issue description, and open a new issue for Diabetes Next Steps (if it was diagnosed during pregnancy).

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Similar to https://github.com/TIP-Global-Health/eheza-app/issues/376#issuecomment-1210258992, there may not be a treatment plan for patient.
There's an option where medicine is supposed to be prescribed, but was not (for whatever reason).
So, what do we then?

**Comment by jeanette-pelizzon** [comment]
If there is a way for us to never give them medicine then we should have "no medication distributed" as the treatment plan here

**Comment by jeanette-pelizzon** [comment]
> No problem. Lets change issue description, and open a new issue for Diabetes Next Steps (if it was diagnosed during pregnancy).

https://github.com/TIP-Global-Health/eheza-app/issues/369 @anvmn

**Comment by jeanette-pelizzon** [comment]
@anvmn updated the designs for the specialty care review screens. Updated the main issue images to reflect the changes. Essentially, we just took away the diagnosis aspect but still will ask if they are following a plan and if they are already enrolled in program or not. Hope this simplifies things!

**Comment by jeanette-pelizzon** [comment]
@anvmn got an answer for this. We really just need to ensure they are enrolled in a program and if not refer them to the appropriate program. The treatment plan stuff is not important (at this time). Updated main issue and design.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Based on https://github.com/TIP-Global-Health/eheza-app/issues/370#issuecomment-1194938716, I'd expect this issue to be not only about Hypertension, but Preeclampsia and Eclampsia as well.
If you agree, please update the requirements.
Also, during pregnancy, patient may be diagnosed with alll 3 diagnoses (for example, encounter 1 -> Hypertension, 2 -> Preeclampsia, 3 -> Eclampsia). What should  `You were diagnosed with  XXX during your pregnancy` header say in this case?

**Comment by jeanette-pelizzon** [comment]
Sorry, we've changed this flow so much that I think some things got lost. It should be for any hypertension related diagnosis. Updated main issue. 

Hypertension should just replace with whatever their diagnosis was.

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. Specialty care is populated with the respective diagnoses, and the question about enrollment in NCD services displays.


![image](https://user-images.githubusercontent.com/3536805/187186045-9a4eaa6c-9aa4-436d-bfac-74415918ca3e.png)
![image](https://user-images.githubusercontent.com/3536805/187186097-4586d264-c782-4b7a-8fa4-18c83f008b98.png)
![image](https://user-images.githubusercontent.com/3536805/187186143-cd00aff4-51fc-4aed-a631-95d371f00075.png)
![image](https://user-images.githubusercontent.com/3536805/187186179-c4efa0fb-6e2c-441c-912f-301d304dcfe5.png)
