### ISSUE TITLE
ANC - PostPartum - Access [2h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#378]
@jeanette-pelizzon 

From #352:

> Postpartum will replace the pregnancy outcome encounter in ANC. 

It's not very clear, because as far as I can tell, there's no `pregnancy outcome encounter` right now for the nurses.
We do have a postpartum encounter for CHW though. Here's is how it accessed.

![Selection_979](https://user-images.githubusercontent.com/17882245/180992068-ae4a163e-f9e7-4a66-98cd-69df0fb3f330.png)

Note that it's always available, even when there were no other encounters at current pregnancy.
It has 2 activities:

![Selection_978](https://user-images.githubusercontent.com/17882245/180992600-a5d8149d-7d40-48d8-ace8-da6deda89c78.png)

At Pregnancy Outcome activity, you can mark pregnancy as completed, and enter needed data.
However, you can also do so by pressing 'Record preganncy outcome' button.

So, if we mean to replace that button, I don't think it's the correct approach.
Consider the case where patient had a pregnancy few years ago, that was managed on the APP.
For some reason, that pregnancy was not concluded, and now, patient is pregnant again, and
wishes to start new pregnancy. This will not be possible, before previous pregnancy is concluded.
However, there's no meaning for PostPartum encounter here, because very long time has passed.

I suggest we maintain the access we have for CHW - add Postpartum encounter button, and keep the 
 'Record preganncy outcome' button:

![Selection_981](https://user-images.githubusercontent.com/17882245/180993758-d65c417a-c16e-4dce-827b-747449247c6e.png)

**Comment by jeanette-pelizzon** [comment]
So this is what we currently have: 

ANC @ CHW: 
- First 
- Subs 
- Postpartum (outcome + danger signs_ 
- Record Pregnancy outcome 

ANC @ Nurse: 
- First 
- Subs
- Record Pregnancy Outcome 


I believe in the original conversation re: postpartum we spoke about this replacing pregnancy outcome. Personally, I think the two buttons are confusing and maybe one should be time dependent (example: pregnancy outcome will appear 12 months after a pregnancy began) but it's up to the clinical team. @adamhstewart is going to speak to Wendy about this today and get us an answer

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

As per our conversation yesterday, we will implement the access we have for CHW  - add Postpartum encounter button, and keep the 'Record preganncy outcome' button.
If changes are needed, we can adjust latter.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. In the issue description @anvm writes that Postpartum encounter is 
>'always available', 

~~however, Postpartum encounter is not available if patient was previously diagnosed as pregnant. Is this OK?~~
After correctly syncing, this is no longer an issue.

### Checked and approved:

1. For CHW the Postpartum activity is always available.
Record pregnancy outcome is available when patient was diagnosed previously as pregnant.

Postpartum|Record pregnancy outcome
-|-
![image](https://user-images.githubusercontent.com/3536805/187136599-ab291b46-3a2d-436e-a966-01165dcc2d6a.png)|![image](https://user-images.githubusercontent.com/3536805/187136549-1fac091a-986c-424d-9e3c-49f9fde59f2e.png)

Postpartum after first antenatal encounter is finished.
![image](https://user-images.githubusercontent.com/3536805/187382096-1035ed7b-227e-48ee-8770-c43c3efc41bc.png)

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. For CHW both Postpartum and Record pregnancy outcome types of encounter are available. 
Postpartum is only available at first encounter, when patient is not pregnant, and the latter is only available when patient was diagnosed previously as pregnant.

Postpartum|Record pregnancy outcome
-|-
![image](https://user-images.githubusercontent.com/3536805/187136105-cec9bfb7-a26b-4b24-95c4-43b0b6a34482.png)|![image](https://user-images.githubusercontent.com/3536805/187136122-ece4f1b8-fd01-4ec3-8a31-e59588b99725.png)

**Comment by adamhstewart** [comment]
@balagan73  I'm not sure I understand this comment:

> For CHW the Postpartum activity is available without having a preceding antenatal encounter.
Record pregnancy outcome is available when patient was diagnosed previously as pregnant.

Under what condition is postpartum not available (and by that do you mean "grayed out")?

**Comment by balagan73** [comment]
@adamhstewart I think this was caused by some syncing problem, due to me not waiting patiently until it finished by itself. Will test it again.

**Comment by balagan73** [comment]
@adamhstewart  I have updated the previous report. Postpartum option is not greyed out when syncing is done correctly.
