### ISSUE TITLE
ANC - Progress Report: Add CHW Activity section [5h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#381]
## Issue

To accommodate the changes made in the ANC flow at the Health Center level and to better integrate CHW's and Nurses, we have made some changes to the ANC progress report. 

### **CHW Activity**
Shows the date and a label for what happened at the CHW encounter. These directly correlate to the activities in the CHW - ANC visit. If an activity was completed during an encounter, it should appear as a label in the progress report. 

Example:
<img width="629" alt="Screen Shot 2021-11-30 at 1 56 08 PM" src="https://user-images.githubusercontent.com/77505464/144110718-727d665e-5888-49c4-8b87-9f1bbce4091c.png">

All Labels for CHW ANC: 
<img width="702" alt="Screen Shot 2021-11-30 at 1 55 42 PM" src="https://user-images.githubusercontent.com/77505464/144110750-7ea07912-2204-4abe-97bb-b99f968792c1.png">

### Design

https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746

## To Do

- Add CHW activity section to progress report
- Logic for labels
- Style per design

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. CHW section displays on the progress report, all labels can be displayed.
![image](https://user-images.githubusercontent.com/3536805/183439109-4c354aa0-a6f5-44e0-beac-a0f85fbfa162.png)
