### ISSUE TITLE
ANC Subs - Gestational Diabetes + Diabetes - Logic Update [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#382]
## Issue 

The clinical team made an update to the logic and way we input results for gestational diabetes 

<img width="245" alt="Screen Shot 2022-07-28 at 2 33 47 PM" src="https://user-images.githubusercontent.com/77505464/181641622-991fd600-5345-4d7c-80db-745c5f09f969.png">

Note: GDM = Gestational Diabetes and the Type 2 diabetes we don't have the logic for that (it's the first time it's been mentioned) so don't worry about that part of the comment. **This is for Gestational diabetes and Diabetesin this issue.** 

## To Do: 
- adjust the results screen input to be in mg/dL per instructions above 
- adjust the diagnosis logic to match what is outlined above.

**Comment by jeanette-pelizzon** [comment]
Alright, updated the logic document. Highlighted changed cells in this image. These changes should apply to both gestational and normal diabetes logic. I will update the other issue where this was mentioned as well. 

<img width="929" alt="Screen Shot 2022-08-01 at 10 57 19 AM" src="https://user-images.githubusercontent.com/77505464/182212117-4493bda7-a454-47cd-b731-2ed4d66ba8d0.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Question about :

![Selection_1006](https://user-images.githubusercontent.com/17882245/182330159-10153905-2b98-4439-89b6-610893a1fc38.png)

At previous versions we had a definition what should happen if random blood sugar test was unable to run:

![Selection_963](https://user-images.githubusercontent.com/17882245/182330454-3b172714-9068-455f-b8dd-603348d4818e.png)

If unable to run - refer to hospital.
As I understood that, in case test was not run for any reason (Lack of reagents, for example), we diagnose Diabetes and send to hospital.

With recent change, that part was removed. So, in case we got urine glucose >= 2+ and test was unable to run, we should make no diagnosis, and no next steps?

**Comment by jeanette-pelizzon** [comment]
In unable to run random blood sugar, we should refer to the hospital. 

I updated the logic document.

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Logic master document says, if Glucose in urine is >=2, blood sugar test should be run. Currently there is no indication to do this after short/long dip results. If not done previously, patient is referred to hospital.


### Checked and approved:

1. Unit is updated to mg/dL

![image](https://user-images.githubusercontent.com/3536805/183419667-c8466083-782e-4359-83bd-5d8d5a728107.png)

2. Diabetes

EGA <= 20 weeks, Fasting, 127 mg/dL

Blood sugar|Warning|Referral
-|-|-
![image](https://user-images.githubusercontent.com/3536805/183420351-503a569f-006b-4856-884f-3bf75f5be204.png)|![image](https://user-images.githubusercontent.com/3536805/183420364-99e0c221-91b4-47ba-be0f-415f336c716b.png)|![image](https://user-images.githubusercontent.com/3536805/183420568-e40ed68b-5e0d-441e-9e4a-d2361c6b318e.png)

EGA <= 20 weeks, no fasting, 200 mg/dL

Blood sugar|Warning|Referral
-|-|-
![image](https://user-images.githubusercontent.com/3536805/183424794-92ccfb3f-133f-4691-b109-2d9c21421d19.png)|![image](https://user-images.githubusercontent.com/3536805/183424794-92ccfb3f-133f-4691-b109-2d9c21421d19.png)|![image](https://user-images.githubusercontent.com/3536805/183424772-051b45ed-f024-4eb9-a38f-84016c05a608.png)

EGA <= 20 weeks, 2 <= glucose in urine

Blood sugar|Warning|Referral
-|-|-
![image](https://user-images.githubusercontent.com/3536805/183426082-b0119806-e47a-4504-a35b-19f9f2432294.png)|![image](https://user-images.githubusercontent.com/3536805/183426102-cbeefed3-6294-4dd5-937a-697953a98ff4.png)|![image](https://user-images.githubusercontent.com/3536805/183426134-c22bead9-1c7f-4fc1-ab37-328932bbc771.png)

3. Gestational Diabetes

EGA >20 weeks, fasting, blood glucose > 126

Warning|Referral
-|-
![image](https://user-images.githubusercontent.com/3536805/183427840-352d2eb9-8d09-4970-b218-9135b3207bf7.png)|![image](https://user-images.githubusercontent.com/3536805/183427912-f47aced5-97f8-4516-b5c2-7d155b2cc6c7.png)

EGA >20 weeks, no fasting, blood glucose >=200

Warning|Referral
-|-
![image](https://user-images.githubusercontent.com/3536805/183428901-abb00485-7dd5-4ada-ad9e-64704056cd7e.png)|![image](https://user-images.githubusercontent.com/3536805/183428917-2ce9390e-868f-49f1-81c8-e520e733ac8a.png)

EGA >20 weeks, 2 <= glucose in urine

Warning|Referral
-|-
![image](https://user-images.githubusercontent.com/3536805/183429909-a696a8f1-ee55-4e0f-afbf-b6c5851e7f32.png)|![image](https://user-images.githubusercontent.com/3536805/183429970-998990fe-f4b5-4ca8-a7a0-16f3b5268912.png)
