### ISSUE TITLE
ANC Subs - Translations for ANC Subsequent at Health Center

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#384]
## Issue
Adding translations for ANC Subsequent feature

## Tasks
- List texts that need translations for the team to add translations
- Add translations in the app

**Comment by adamhstewart** [comment]
@Diama1 Looks like the associated PR here needs some changes, can you finish those off for release?

**Comment by Diama1** [comment]
> @Diama1 Looks like the associated PR here needs some changes, can you finish those off for release?

Sure, I have finished them I am waiting for review
