### ISSUE TITLE
ANC - Outside Care - Preclampsia [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#387]
## Issue 

We need to add a screen for preeclampsia in outside care. The screen should only appear if they select preeclampsia in the initial outside care screen (the same as the other outside care There is no next steps logic associated with these inputs but are used for data gathering. 

<img width="292" alt="Screen Shot 2022-08-02 at 8 56 24 PM" src="https://user-images.githubusercontent.com/77505464/182521022-6858c4e1-b84a-45fc-8233-ff646e7dfe2c.png">

## To Do: 
- Style screen per design 
- Add screen into Outside Care

**Comment by anvmn** [comment]
@balagan73 please test on Nutrition env

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Typo in  Amlodipine dosage

![image](https://user-images.githubusercontent.com/3536805/183391237-0c248447-cf81-4a8d-932d-21a862d96e63.png)

2. Shouldn't the medication administered in outside care be noted on the report page? Currently it doesn't display.
![image](https://user-images.githubusercontent.com/3536805/183391770-51a935ef-8854-45ab-bb2f-81f069216758.png)


### Checked and approved:

1. Question about medicine displays when Mild to moderate preeclampsia is selected.
![image](https://user-images.githubusercontent.com/3536805/183392022-a43b713d-e68e-432c-9834-e648a0e711fb.png)

**Comment by adamhstewart** [comment]
@anvmn please fix typo and and check question about medication.

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. Typo is fixed:
![image](https://user-images.githubusercontent.com/3536805/192308044-746545e3-9b73-48bb-ab52-c9ae3ef3c99c.png)

2. Medication is displayed on the Progress report.
![image](https://user-images.githubusercontent.com/3536805/192309289-88094047-0761-4c9c-9d39-6bc6a998a7f9.png)
