### ISSUE TITLE
Referrals - New Option added [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#390]
## Issue 

Currently on the referral screens we ask a boolean question "Have your referred the patient to the hospital/ANC Services/ Mental Health Specialist/ ETC" If they answer no, a "Why not"" questions appears with various options. Wendy requested that we ADD the option "Not Indicated" to this list. This way we can track how many times we are suggesting to refer a patient elsewhere when we don't really need to. 

## To Do: 
Add "Not Indicated" as an option for "why not" in referral screens across E-Heza
Affected encounter types:

- Group
- Nutrition
- Acute Illness
- Antenatal
- Well Child

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Is this something that we need only for NCD,  or for ANC as well, or for all modules where we refere patients?

**Comment by jeanette-pelizzon** [comment]
All modules where we refer patients @anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 

No problem. If I understand the ussage of this correctly, I don't think that label fits.
Maybe something like 'Unnecessary referral' would decribe this better?

**Comment by jeanette-pelizzon** [comment]
Let's keep the wording as "not indicated" as that's what the medical team asked for. This seems to be a common medical term. This was we can track on the back end when we are referring out and it is not called for and we can adjust the app in the future.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

### Checked and approved:

1. 'Not indicated' option is available if patient is not referred to hospital/specialist.

Postpartum|ANC ARV
-|-
![image](https://user-images.githubusercontent.com/3536805/186855909-e540024a-d72a-43b3-b4fa-396a9e9937e6.png)|![image](https://user-images.githubusercontent.com/3536805/186654951-79877d50-7b62-462f-bb78-9c5913d4fa32.png)
