### ISSUE TITLE
Random Blood Sugar - Update to Fasting Question [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#392]
## Issue 

The term "fasting" is not used in Rwanda so we need to rephrase the fasting question on the random blood sugar test to be more appropriate. 

The team has decided to change this question to "Was this test performed before a meal" 

This should be changed across all Random Blood Sugar tests in E-Heza. 

## To Do 
- Update the question across e-eheza

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. The question is updated as requested.
![image](https://user-images.githubusercontent.com/3536805/186660933-336cac4b-0d93-4859-864e-63e003d3bd4b.png)
