### ISSUE TITLE
NCD - Encounter Type - Infrastructure [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#395]
## Issue 
We are creating a new individual encounter type called NCD. We need to create the infrastructure to have this show up for all patients. 

## To Do 

- Create infrastructure for new encounter type

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Question: 

1. This encounter shows up under Clinical -> Individual encounter, but not from the Patient record. Is it OK? 

Individual encounter|Patient record
-|-
![image](https://user-images.githubusercontent.com/3536805/193303659-df49f01e-23aa-4d7c-b242-a78994ab77cf.png)|![image](https://user-images.githubusercontent.com/3536805/193303751-80200e8c-0654-470c-9392-b7899373e30c.png)
