### ISSUE TITLE
NCD - Encounter Infrastructure [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#396]
## Issue

The NCD module will have 6 main activities and then a next steps section that appears once all main activities are completed. 

- Danger Signs 
- Symptom Review
- Medical History 
- Examination 
- Labs 
- Family Planning

Because of the Labs section, this encounter will also need to appear in case management. 

## To Do: 
- Build out the infrastructure for these activity types for the NCD encounter type

**Comment by anvmn** [comment]
@jeanette-pelizzon 

I think Family Planning activit is missing

**Comment by jeanette-pelizzon** [comment]
Sorry, FP was added in at a later date. Updated issue above.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. The 6 activities exist under NCD encounter.

![image](https://user-images.githubusercontent.com/3536805/193301118-79d65604-766d-4406-8552-ef1950a5478c.png)
