### ISSUE TITLE
NCD - Danger Signs [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#397]
## Issues 

Danger signs is the first activity in the NCD module. It is a checklist of symptoms and at this point in time there is no logic associated with these symptoms but that is likely to change in the future. 

Activity Tray | Screen One 
--|-- 
<img width="378" alt="Screen Shot 2022-08-11 at 8 21 32 AM" src="https://user-images.githubusercontent.com/77505464/184169600-ac6a36e1-8ec1-4f9f-8e21-a3268ed239fd.png"> | <img width="378" alt="Screen Shot 2022-08-11 at 8 21 43 AM" src="https://user-images.githubusercontent.com/77505464/184169611-8e028c14-2c31-4fc6-b8c7-b13eaf3ab017.png">

## To Do: 
- Style Screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Screen displays with the same options as on the design.
![image](https://user-images.githubusercontent.com/3536805/193305077-4f1db6a2-8134-4734-9b2a-d9b1462f3e50.png)
