### ISSUE TITLE
NCD - Symptom Review [18h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#398]
## Issue 
Symptom review is the second activity in the NCD encounter. There are three sections of checkboxes and at this point in time there is no logic associated with these symptoms but this is likely to change in the future. 

Activity Tray | Screen One 
--|-- 
<img width="340" alt="Screen Shot 2022-08-11 at 8 28 28 AM" src="https://user-images.githubusercontent.com/77505464/184171090-8fdced31-7675-4976-abb0-c0860d57fc0d.png"> | <img width="294" alt="Screen Shot 2022-08-11 at 8 28 38 AM" src="https://user-images.githubusercontent.com/77505464/184171099-55508da9-15ce-420b-aacb-1857813fe9d8.png">

## To Do: 
- Style screen per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Questions display as on the design. (Display error is only on screenshot).
![image](https://user-images.githubusercontent.com/3536805/193294259-54777e76-26d8-4a84-933d-6eab5e0633ec.png)
