### ISSUE TITLE
NCD - Medical History - Infrastructure [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#399]
## Issue 

The medical history activity has 5 sub-activities. 

 co-morbidities | medication history | social history | family history | outside care 
--|--|--|--|--
<img width="99" alt="Screen Shot 2022-08-11 at 8 43 50 AM" src="https://user-images.githubusercontent.com/77505464/184174703-73df86c3-0f54-45e3-8be4-da0e42e0431d.png"> | <img width="87" alt="Screen Shot 2022-08-11 at 8 40 52 AM" src="https://user-images.githubusercontent.com/77505464/184173595-50e159e5-ea10-462e-9111-6e19b5cd951e.png"> | <img width="112" alt="Screen Shot 2022-08-11 at 8 41 38 AM" src="https://user-images.githubusercontent.com/77505464/184173750-d856ef7b-6411-4283-85ec-e3aed1366ae7.png"> | <img width="120" alt="Screen Shot 2022-08-11 at 8 42 27 AM" src="https://user-images.githubusercontent.com/77505464/184173933-db8622de-79ce-4d38-ac04-cdde7c6b5318.png"> | <img width="122" alt="Screen Shot 2022-08-11 at 8 39 55 AM" src="https://user-images.githubusercontent.com/77505464/184174730-5406070a-7082-4279-a8f8-1095d3a20645.png">

## To Do: 
- Create activity infrastructure

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. The five sub-activities exists under Medical history.

![image](https://user-images.githubusercontent.com/3536805/193522480-b35b001a-dd9b-4577-a48a-3ffca52afba0.png)
