### ISSUE TITLE
NCD- Medical History - Co-Morbidities [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#400]
## Issue 

Co-Morbidities is the first sub-activity under medical history. This sub-activity is important as some non-communicable diseases will affect others and the medical staff needs to know if a patient has any of them. 

In the current state, only hypertension, pregnancy related hypertension and diabetes will affect logic later on. However, this will likely change in the future. 

<img width="294" alt="Screen Shot 2022-08-11 at 9 13 20 AM" src="https://user-images.githubusercontent.com/77505464/184180417-71533261-7365-4f6c-89ce-48145b580412.png">

## To Do
- style screen per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Panel is styled per design.

![image](https://user-images.githubusercontent.com/3536805/193308117-c00ed9f2-d2e3-4da3-a77b-200490b8f4e5.png)
