### ISSUE TITLE
NCD- Medical History - Medication History   [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#401]
## Issue 

Medical staff needs to know what medication a patient has previously taken or is currently taken. At this point in time, we are not doing anything with these answers but using this as data collection. 

<img width="293" alt="Screen Shot 2022-08-11 at 9 13 15 AM" src="https://user-images.githubusercontent.com/77505464/184180264-429d454a-32ab-4a6d-8bae-74df4982a892.png">

## To Do: 
- style screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. The second and third question is wrong.
![image](https://user-images.githubusercontent.com/3536805/193523521-7583d885-59f7-4499-903f-f8fc176d54a7.png)


### Checked and approved:

1. Except from the second and third question the displayed options are correct.

**Comment by adamhstewart** [comment]
@anvmn please check the questions vs the design.

**Comment by anvmn** [comment]
@adamhstewart Fixed and depoyed to Nutrition env for retesting
