### ISSUE TITLE
NCD - Medical History - Family History [6.5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#403]
## Issue 

The medical team needs to know family history as it can affect the patient's health or make them pre-disposed to other conditions. At this time, we are not building out any logic associated with this screen but that will likely change in the future. You will see that I noted conditional questions on the screenshot. 

<img width="252" alt="Screen Shot 2022-08-11 at 3 22 39 PM" src="https://user-images.githubusercontent.com/77505464/184252538-1cb8f386-902c-401a-80d0-ea0f222a5adc.png">

## To Do 
- Style screens per design.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Panel looks as on the design, conditionals show if yes is selected.

At start|Selecting yes
-|-
![image](https://user-images.githubusercontent.com/3536805/193308653-9f5b7186-659d-491d-802c-af5853e02762.png)|![image](https://user-images.githubusercontent.com/3536805/193309037-7eedcbd3-fb7c-4c58-a1cb-4d7ed6faa68b.png)
