### ISSUE TITLE
NCD - Logic - Hypertension - Stage One [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#404]
## Issue 

When a patient comes into an NCD encounter, we know that they have been referred for an existing issue. In the NCD encounter, we determine how bad their diagnosis is and distribute medication to help alleviate the issue. 

Hypertension is one of the major issues tackled by the NCD encounter. There are several stages of Hypertension. For the purposes of these issues, I have broken them into one stage type per issue. 

**[The logic for NCD's can be found here.](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=211600820)** 

In **Stage One Hypertension (without complications)**, we provide health education at the first visit and then will distribute medication at the second visit. This is the only stage of hypertension where the next steps change depending on the visit number. 

The goal of giving a patient this medication is to get their numbers to systolic of <140 and diastolic of <90. If a patient has a systolic <100 we can bump them down a stage level. 

Stage One First Visit | Stage One Subsequent Visits 
--|-- 
<img width="311" alt="Screen Shot 2022-08-11 at 9 29 44 AM" src="https://user-images.githubusercontent.com/77505464/184183217-f675779b-3187-40b4-b6de-e31dd20e24b6.png"> | <img width="262" alt="Screen Shot 2022-08-11 at 2 31 30 PM" src="https://user-images.githubusercontent.com/77505464/184245887-f88c2f97-e257-4138-8261-e292ea87fac6.png">

## To Do 
- Create logic on the back end 
- Style screen per design

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. Typo, council should be counsel.
![image](https://user-images.githubusercontent.com/3536805/193538785-e2b65ac1-b3e5-403d-b17a-675ff1e26c80.png)

2. Diagnosis is not indicated on the progress report.
![image](https://user-images.githubusercontent.com/3536805/193574731-da3c3a7f-be28-4ac1-81ed-e8a5cb5c4dd6.png)

3. Typo in dosage, it should be 12.5 mg
![image](https://user-images.githubusercontent.com/3536805/193575967-9b4661ad-bc53-4b97-8829-489e5232f6f7.png)

4. At third visit patient has 139/89 BP, but still diagnosed with Stage one hypertension.

Measurement|Next steps
-|-
![image](https://user-images.githubusercontent.com/3536805/193576986-0a0e1eb2-794f-4303-93eb-6d9f270b0733.png)|![image](https://user-images.githubusercontent.com/3536805/193576968-a289b49a-ac5c-4ef2-8667-ac60a7fa0125.png)

### Checked and approved:

1. Health education displays at first encounter (image at Found issues point 1), and Medication distribution displays at second encounter.
![image](https://user-images.githubusercontent.com/3536805/193575600-8d744542-1dcf-4519-8ad0-ac775190de05.png)

**Comment by jeanette-pelizzon** [comment]
1. fix typo in council -> counsel @Diama1 
2. progress report is a known issue
3. fix typo in dosage outline in point 3 above @Diama1 
4. This is correct. Once diagnosed with hypertension a patient is never cured they can just get it down to stage one and maintain it with medication.

**Comment by adamhstewart** [comment]
@Diama1 please fix points 1 and 3

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for retesting (points 1 - 3)
