### ISSUE TITLE
NCD - Logic - Hypertension Stage One Complications [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#405]
## Issue 

When a patient comes into an NCD encounter, we know that they have been referred for an existing issue. In the NCD encounter, we determine how bad their diagnosis is and distribute medication to help alleviate the issue.

Hypertension is one of the major issues tackled by the NCD encounter. There are several stages of Hypertension. For the purposes of these issues, I have broken them into one stage type per issue.

[The logic for NCD's can be found here.](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=211600820)

**Stage One Hypertension** can also be presented with renal complications or with diabetes which changes things. 

The goal of giving a patient this medication is to get their numbers to systolic of <140 and diastolic of <90. If a patient has a systolic <100 we can bump them down a stage level. 

Renal Complications | Diabetes | Referral 
--|--|--
<img width="261" alt="Screen Shot 2022-08-11 at 2 35 12 PM" src="https://user-images.githubusercontent.com/77505464/184246501-f1d1732a-6e42-4a4a-b37c-e81a830be14c.png"> | <img width="265" alt="Screen Shot 2022-08-11 at 2 35 57 PM" src="https://user-images.githubusercontent.com/77505464/184246571-888b67d9-4fd5-49d7-bea1-7fad7cff542e.png"> | <img width="241" alt="Screen Shot 2022-08-11 at 9 51 37 AM" src="https://user-images.githubusercontent.com/77505464/184190058-d464682a-20a3-44ed-8ba6-db78da8b1a89.png">

NOTE: there should NOT be a blue underling in the diabetes image. I can't get it to go away though. 

## To Do: 
- implement logic 
- style screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. When patient has Renal complications, the wording of the Methyldopa medication is missing the '1 tablet' part. Is this a problem?
![image](https://user-images.githubusercontent.com/3536805/193532160-1a4f56f7-692d-4f59-9735-76f2632724c7.png)

2. The 'Have you administered the medication to the patient?' question doesn't display, but this might not be needed. See image above.

3. Diagnosis is not displayed on progress report.
![image](https://user-images.githubusercontent.com/3536805/193548486-46cbfe11-c03e-43fd-aa65-bf7134a12f58.png)

4. Patient is not diagnosed as Stage One with diabetes (only with Diabetes, but even that is not displayed on progress report). 
Medical history - Diabetes, plus current BP measurements 140/90, plus short dip glucose = 2.
![image](https://user-images.githubusercontent.com/3536805/193549128-1b685728-145d-4d02-9793-2910f148c8e7.png)

### Checked and approved:

If diagnosis is Stage one hypertension with Renal complications, referral correctly happens.
![image](https://user-images.githubusercontent.com/3536805/193532769-8e7d5b8a-ef3f-4ba3-8bcd-5aafdba282db.png)|

**Comment by jeanette-pelizzon** [comment]
1. update methyldopa per design @Diama1 
2. have you administered to the patient question should appear per design @Diama1 
3. progress report not populating is a known issue 
4. Seems like this patient should have stage 1 with diabetes - needs the proper next steps to appear and proper diagnosis to appear on progress report @anvmn

**Comment by adamhstewart** [comment]
@anvmn assigning all aspect to you because of point 4.

**Comment by anvmn** [comment]
@adamhstewart @jeanette-pelizzon 

> 1, When patient has Renal complications, the wording of the Methyldopa medication is missing the '1 tablet' part. Is this a problem?

Methyldopa recommended treatement dosage helper is the same one we use at Prenatal.
There we have:

![Selection_1168](https://user-images.githubusercontent.com/17882245/196399154-0dd68182-5f0b-4b26-83cf-9dd9d0837ac5.png)

I don't see why we need to say `1 tablet` at NCD and not say it at `Prenatal`.
So, we need a common presentation, since it's exactly same medication.

> 2. The 'Have you administered the medication to the patient?' question doesn't display, but this might not be needed.

This is not required, since we have `No Treatment Administered` option:

![Selection_1169](https://user-images.githubusercontent.com/17882245/196399856-6234ae3d-d2c7-4e6c-b1d8-8f2190303a4f.png)

> 3. Diagnosis is not displayed on progress report.

Known issue, will be treated separately.

> 4. Patient is not diagnosed as Stage One with diabetes (only with Diabetes, but even that is not displayed on progress report).

When we distribute medication, we state the reason for that medication.
Diabetes medication does not depend on hypertension in any way.
Therefore, the reason to give that medication is Daibetes and nothing else.

Had there been Hypertension diagnosed, it would have been treated with different set of medication, and we'd show the diagnosis there.

Note: When we have Hypertension, at medication distribution, we do mention Renal complications if there are any. though it does not affect medication.

**Comment by jeanette-pelizzon** [comment]
1. Methyldopa - @anvmn we are trying to clean up the medication wording across the entire app as we move forward. The convention that I have given the team more recently is "Name of Medicine (XX mg): take X tablet by mouth X times a day for X many days." Tablet can be switched out with other form i.e: drops, sachet, etc. We haven't been able to go back through all medication distro's in the app to make them the same so some of the newer modules or work will be different than past work. If it is easy to switch all methyldopa medication instances to read in the same format we should do it, otherwise we will have to hold off until we can properly audit the app. 

2. I cannot remember when we decided to add a no treatment administered option. I also do not know why we ask the have you administered the treatment to the patient (that is a holdover from before I was here). @adamhstewart do you know the reasoning? If we don't need the question we should take it away. It seems that the feedback we've gotten is that there are a lot of questions/modules feel long so if we can take it away we should, right?

4. Anatoly's explanation makes sense here. It should be good to go. If we get feedback that it needs to be presented in a different way we can adjust.

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

> I cannot remember when we decided to add a no treatment administered option.

This option exists on any medication distribution input where we show several options for recommended treatment. It's there to allow nurse to report that there was no treatment.

Note that this behavior is different from regular medication distribution, where we give direct instruction on medication and dosage, and then ask if it was administered, and if not, we ask for a reason.

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for retesting

**Comment by adamhstewart** [comment]
@jeanette-pelizzon can you confirm this woks according to logic

**Comment by adamhstewart** [comment]
@jeanette-pelizzon ^^

**Comment by jeanette-pelizzon** [comment]
NEW Problem: 
-Patient diagnosed with stage 3 hypertension but I marked everything as normal EXCEPT that she had a previous history of hypertension. I only ran the creatine lab but had not yet put in any results. All other labs I said I did not complete. 
<img width="638" alt="Screen Shot 2023-01-14 at 3 25 22 PM" src="https://user-images.githubusercontent.com/77505464/212501429-abf63789-ed14-4681-813e-a99ceae8dd37.png">
<img width="623" alt="Screen Shot 2023-01-14 at 3 24 53 PM" src="https://user-images.githubusercontent.com/77505464/212501431-f983b191-d793-4adc-9826-48fa58878ba9.png">

// @anvmn @adamhstewart

**Comment by jeanette-pelizzon** [comment]
I ran it again on Mpano Chantal and it worked. When I put in the lanb results it bumped her from stage one hypertension to stage one hypertension with renal complications @adamhstewart 

I can't get it to replicate the issue in my previous comment. Tried on Irumva Clarisse as well. Leaving comment there just in case something wonky is actually wrong.
