### ISSUE TITLE
NCD - Logic - Stage Two Hypertension [4.5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#406]
## Issue

When a patient comes into an NCD encounter, we know that they have been referred for an existing issue. In the NCD encounter, we determine how bad their diagnosis is and distribute medication to help alleviate the issue.

Hypertension is one of the major issues tackled by the NCD encounter. There are several stages of Hypertension. For the purposes of these issues, I have broken them into one stage type per issue.

[The logic for NCD's can be found here.](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=211600820)

In **Hypertension Stage Two**, the nurse will select TWO medications to prescribe to the patient. 

The goal of giving a patient this medication is to get their numbers to systolic of <140 and diastolic of <90. If a patient has a systolic <100 we can bump them down a stage level. 

<img width="262" alt="Screen Shot 2022-08-11 at 2 36 33 PM" src="https://user-images.githubusercontent.com/77505464/184246692-c8625a0a-4f0f-4f7d-8f0e-a7639ae21ae6.png">

## To Do 
- implement logic 
- style screen per design

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:
1. The Progress report is empty.
![image](https://user-images.githubusercontent.com/3536805/193591716-d5e3e256-905f-4029-a508-49519f82f210.png)

2. It is possible to select more than 2 medications. Is this a problem?
![image](https://user-images.githubusercontent.com/3536805/193591813-8ec5f32a-d392-4050-9c0f-99a1343eee9b.png)


### Checked and approved:

1. Diagnosis is correct, displayed Medication distribution panel is also correct except the typo in Atenlol dosage noted elsewhere.
![image](https://user-images.githubusercontent.com/3536805/193590484-ce226fd6-1e47-4509-81c7-b76406ec49cf.png)

**Comment by jeanette-pelizzon** [comment]
1. progress report is a known issue
2. @anvmn and @adamhstewart  I'll let you decide here. If we want to limit them to selecting two I think it would be helpful to avoid mistakes but unsure what the lift to make that happen would be.

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

Technically speaking, we either allow multiselect or single select.
We have this behavior at several other places I believe, and the responsibility for proper selection is on nurses.

**Comment by anvmn** [comment]
@adamhstewart 

Progress report issue is fixed and deployed to Nutrition env,
This can be retested.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

### QA Review

### Found issues and questions:

1. Patient gets diagnosed with stage 3 hypertension above 160 systolic BP.

Entered data|Progress report|Medical distribution
-|-|-
![image](https://user-images.githubusercontent.com/3536805/199475073-4c527cf3-2b71-49d3-be89-6af18fc6e7aa.png)|![image](https://user-images.githubusercontent.com/3536805/199475191-70004813-7ee1-4d27-a34e-b8624551ed97.png)|![image](https://user-images.githubusercontent.com/3536805/199475296-cc438f12-e8a7-4bc8-a7c5-be5cbf8de86e.png)
