### ISSUE TITLE
NCD - Logic - Hypertension Stage Three [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#408]
## Issue 

When a patient comes into an NCD encounter, we know that they have been referred for an existing issue. In the NCD encounter, we determine how bad their diagnosis is and distribute medication to help alleviate the issue.

Hypertension is one of the major issues tackled by the NCD encounter. There are several stages of Hypertension. For the purposes of these issues, I have broken them into one stage type per issue.

[The logic for NCD's can be found here.](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=211600820)

In **Stage Three Hypertension,** you will choose two different medications from the list to distribute to the patient and refer them to the hospital. 

The goal of giving a patient this medication is to get their numbers to systolic of <140 and diastolic of <90. If a patient has a systolic <100 we can bump them down a stage level. 

Medication Distribution | Referral 
--|-- 
<img width="262" alt="Screen Shot 2022-08-11 at 2 41 33 PM" src="https://user-images.githubusercontent.com/77505464/184247343-aa13d5d7-57a3-4bef-ac77-14bad8c76235.png"> | <img width="259" alt="Screen Shot 2022-08-15 at 3 39 10 PM" src="https://user-images.githubusercontent.com/77505464/184732754-91ec1c6a-2ece-414f-96c7-78a5a30ba3be.png">

## To Do 
- Implement Logic 
- Style Screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Progress report is empty.
![image](https://user-images.githubusercontent.com/3536805/193599359-271af2de-fa6f-4775-981e-c083bc11ea26.png)


### Checked and approved:

1. Diagnosis and Referral to hospital displays correctly.

Medical distribution|Referral
-|-
![image](https://user-images.githubusercontent.com/3536805/193599135-1c92fa9e-0191-42b4-80ea-8c4d5c3a1bbf.png)|![image](https://user-images.githubusercontent.com/3536805/193599311-812d1e04-db90-432f-bfe8-a2bc3e1adce0.png)

**Comment by jeanette-pelizzon** [comment]
Progress report being empty is a known issue so going to move this to acceptance as it is being addressed elsewhere
