### ISSUE TITLE
NCD - Logic - Hypertension in Pregnancy [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#409]
## Issue 
When a patient comes into an NCD encounter, we know that they have been referred for an existing issue. In the NCD encounter, we determine how bad their diagnosis is and distribute medication to help alleviate the issue.

Hypertension is one of the major issues tackled by the NCD encounter. There are several stages of Hypertension. For the purposes of these issues, I have broken them into one stage type per issue.

**[The logic for NCD's can be found here.]**(https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=211600820)

In Hypertension with Pregnancy, we will prescribe a pregnancy safe medication and refer to ANC Services. 

Medication Distribution | Referral 
--|-- 
<img width="258" alt="Screen Shot 2022-08-11 at 10 05 07 AM" src="https://user-images.githubusercontent.com/77505464/184192343-df04f96a-1807-4f34-b8a2-08cfc52e8be2.png"> |<img width="258" alt="Screen Shot 2022-08-11 at 10 05 12 AM" src="https://user-images.githubusercontent.com/77505464/184192346-1fe1cdc8-18f0-4125-afbc-3be516589cbe.png">

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. Patient has positive pregnancy test, has hypertension with 140/90 BP, but no pregnancy is displayed on the diagnosis.

Pregnancy|Diagnosis
-|-
![image](https://user-images.githubusercontent.com/3536805/193584687-7c033b06-6052-40f9-a225-3386c81aa35b.png)|![image](https://user-images.githubusercontent.com/3536805/193584735-eeecb07e-2ac8-4168-9a94-daca8c963ff4.png)

2. Typo: indefinite article should be matched to word start. 'an ANC'
![image](https://user-images.githubusercontent.com/3536805/193585170-1ccddd25-4d51-440c-8b8b-9090e1bb8d58.png)

3. Progress report is empty.
![image](https://user-images.githubusercontent.com/3536805/193585429-64151af7-fb89-4b42-a943-dcf8f5937976.png)

### Checked and approved:

1. When patient has 160/90 BP and is pregnant, medication distribution displays correctly.
![image](https://user-images.githubusercontent.com/3536805/193586621-b978aef6-d304-4572-9156-e121a6892884.png)

**Comment by jeanette-pelizzon** [comment]
1. patient should have hypertension with pregnancy per[ logic doc](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=211600820)
2. Change "a ANC" to "an ANC"  @Diama1 
3. Progress report being empty is a known issue appearing in several of the QA's @anvmn

**Comment by adamhstewart** [comment]
@anvmn ^^

**Comment by anvmn** [comment]
@adamhstewart @jeanette-pelizzon 

> 1. Patient has positive pregnancy test, has hypertension with 140/90 BP, but no pregnancy is displayed on the diagnosis.

Header text on Ediucation form comes to show why we provide education.
It's same education, no matter if patient is pregnant or not.
However, when distributing medication, there's different medication set for pregnant patients, 
and therefore, we do say that patient is pregnant.

> 2. Typo: indefinite article should be matched to word start. 'an ANC'

Fixed at [02f82a4](https://github.com/TIP-Global-Health/eheza-app/pull/508/commits/02f82a4609492924f6ec6a3038a8677b8dca3861)

> 3. Progress report is empty.

Known issue, will be treated separately.

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for retesting

**Comment by adamhstewart** [comment]
@anvmn The team found this issue: 

> When the patient has stage one hypertension and is pregnant in the first encounter, it doesn’t give the prescription of  Methyldopa as it is described in the issue. we only see the Health Education of Stage one Hypertension

and this:

> When the vitals Systolic is 160 diastolic is 90 which give the client hypertension. We don’t get the next step option.


https://docs.google.com/document/d/1CE7I0HrRsZ0ViiPCylZWkMFwTpT__SAIdt-yIW9lPcw/edit?usp=sharing
