### ISSUE TITLE
NCD - Logic - Diabetes [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#410]
## Issue 
When a patient comes into an NCD encounter, we know that they have been referred for an existing issue. In the NCD encounter, we determine how bad their diagnosis is and distribute medication to help alleviate the issue.

Diabetes is one of the major issues tackled by the NCD encounter. We will be prescribing medication for diabetic patients in next steps. The ultimate goal is to get a patient to numbers that are within a normal range which is fasting glucose of < 126, non-fasting glucose of < 200, urine dip (glucose) < 2.  We have decided to present nurses will all the available treatment options and allow them to use their best judgement in choosing a treatment option. 

I have created three different screens based on what criteria we are diagnosing them on. Having the levels would be helpful for the nurse so they can have that information in front of them when they make the decision on medication. If this is technically difficult to do and will add a lot of hours then just use the no results versions for all. 

Fasting | Non Fasting | Urine Dip Glucose | No Results
--|--|--|--
<img width="236" alt="Screen Shot 2022-08-15 at 1 57 08 PM" src="https://user-images.githubusercontent.com/77505464/184717178-7d5c9085-f3d0-4705-9144-3721b204d48b.png"> | <img width="239" alt="Screen Shot 2022-08-15 at 1 57 14 PM" src="https://user-images.githubusercontent.com/77505464/184717183-c474610c-fc2d-483f-a921-4d159bf5abd1.png"> | <img width="234" alt="Screen Shot 2022-08-15 at 1 57 22 PM" src="https://user-images.githubusercontent.com/77505464/184717185-13a9b778-dad4-4c0d-a3b3-10ebc4b1d8a7.png"> | <img width="236" alt="Screen Shot 2022-08-15 at 1 57 30 PM" src="https://user-images.githubusercontent.com/77505464/184717186-d9cda85d-003a-4e25-a210-f7a4c08ea3b4.png">

## To Do: 
- implement logic 
- style screens per design

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. Patient has a urine dip glucose level 2, diagnosed to have Diabetes or has Diabetes co-morbidities, but is not referred to hospital. In case of urine dip glucose level diagnosis the tiagnosis doesn't display on progress report.

Diagnoses, with no referral.|Progress report
-|-
![image](https://user-images.githubusercontent.com/3536805/193544010-3f083fcc-d8a2-412d-8428-bc93bb4432c1.png)|![image](https://user-images.githubusercontent.com/3536805/193544605-3c0d788e-6897-4dcc-95fd-9770ec578e90.png)

2. Patient was diagnosed with diabetes. At next encounter the patient is diagnosed again with diabetes without having a new test, encounter cannot be ended. 
![image](https://user-images.githubusercontent.com/3536805/193573295-62684e84-886a-42e6-a04e-949fe2012c6e.png)

### Checked and approved:

1. Fasting and non-fasting diagnosis works correctly, as pointed out in https://github.com/TIP-Global-Health/eheza-app/issues/410

2. Urine dip-stick diagnosis works correctly, as pointed out in https://github.com/TIP-Global-Health/eheza-app/issues/419#issuecomment-1265127289

3. When patients have Diabetes as Co-morbidities, they are diagnosed correctly.

Previous diagnoses|Diagnoses|Progress report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/193582451-f6a4662c-8e4f-4507-8377-0e5ba6a4d2f4.png)|![image](https://user-images.githubusercontent.com/3536805/193582464-6cb4aea9-eac7-4f65-8e76-eb8e361a0295.png)|![image](https://user-images.githubusercontent.com/3536805/193582478-14953483-05a0-488a-ac73-9b98d442e135.png)

**Comment by anvmn** [comment]
@balagan73 
The problem is only the missing entry at progress report?

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. Patient was diagnosed with diabetes. At next encounter the patient is diagnosed again with diabetes without having a new test, encounter cannot be ended. 
![image](https://user-images.githubusercontent.com/3536805/193573295-62684e84-886a-42e6-a04e-949fe2012c6e.png)

**Comment by anvmn** [comment]
@balagan73 
Looks like next steps are not completed.
This is the reason you can't complete the encounter.

**Comment by balagan73** [comment]
@anvmn The next steps were completed and saved, but did not disappear. 
In my previous comment the problem was also the missing referral. I will just merge my two comments into one, as I have planned.

**Comment by jeanette-pelizzon** [comment]
1. Patient with diabetes is only referred to the hospital if they have diabetes + hypertension. I am seeing where the confusion is coming from on the MAster Logic doc because there was an error in the progress report wording. I have updated that just now. It seems that E-Heza is behaving correctly in distributing medicine and not referring to the hospital. 

We need to update the progress report wording to "Diabetes treated with MEDICATION NAME on XX/XX/XXXX" 

2. I am not sure what's happening there but it seems like @anvmn does. 

Moving this back to To Do so that we can update progress report wording. Thank you! 

@anvmn

**Comment by anvmn** [comment]
@adamhstewart 

> 2. Patient was diagnosed with diabetes. At next encounter the patient is diagnosed again with diabetes without having a new test, encounter cannot be ended.

Fixed at [06d7934](https://github.com/TIP-Global-Health/eheza-app/pull/508/commits/06d7934c0cb2e807ceb88d7c56c5c9c9bdee05ce)

**Comment by anvmn** [comment]
@adamhstewart Fixed and depoyed to Nutrition env for retesting. Point 1 implemented as well.

**Comment by adamhstewart** [comment]
@jeanette-pelizzon can you double check this one (if you haven't already)

**Comment by adamhstewart** [comment]
@jeanette-pelizzon ^^

**Comment by jeanette-pelizzon** [comment]
I can't test. I can do the first encounter and it is saying the patient is diabetic but it won't let me enter into a new NCD encounter for her immediately. // @adamhstewart 

Otherwise, patient was just given meds for diabetes and not referred to hospital.
