### ISSUE TITLE
NCD - Medical History - Outside Care [9h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#411]
## Issue 

As in ANC, we are implementing an outside care sub-activity in the NCD encounter. At this time, the answers to these questions will not influence any logic but will be used for information gathering. 

Main Sub Activity Screen 
<img width="252" alt="Screen Shot 2022-08-15 at 10 02 28 AM" src="https://user-images.githubusercontent.com/77505464/184681278-d983ca99-2bd4-4db9-99c4-225b4387f819.png">

Follow Up Question Screens
Hypertension | Anemia | HIV | Malaria | Syphilis
--|--|--|--|--
<img width="274" alt="*Hypertension" src="https://user-images.githubusercontent.com/77505464/184197225-4a507672-458a-4e30-a918-c37729de37d5.png"> | <img width="260" alt="*Anemia" src="https://user-images.githubusercontent.com/77505464/184197250-d4fc26b1-3945-497d-bdf1-4dd65c4ffda8.png"> | <img width="270" alt="*HIV" src="https://user-images.githubusercontent.com/77505464/184197283-64cab74f-b53b-4c43-a025-11f759f4eef8.png"> | <img width="265" alt="*malaria" src="https://user-images.githubusercontent.com/77505464/184197318-6f907d74-de38-4ae0-90c2-56c6929d5c68.png"> | <img width="266" alt="*syph" src="https://user-images.githubusercontent.com/77505464/184197370-9e6ac3be-507c-4212-88c1-6afcd73b26e4.png">

## To Do 
- style screens per design

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. There is a typo in the dosage of amplodipine:
![image](https://user-images.githubusercontent.com/3536805/193525859-49349d00-1bc5-492f-b5cc-b1106252b977.png)



### Checked and approved:

1. The conditional display of options works as designed, and the Were you given medicine question only displays if one of the 5 diagnoses concerned is selected.

![image](https://user-images.githubusercontent.com/3536805/193524686-6f928221-c84e-4578-8a41-0e2044da22df.png)

2. Except from the above mentioned typo in the dosage all the questions and options regarding the given medication are correct. See image in Found issues section.

**Comment by jeanette-pelizzon** [comment]
Amlodipine is spelled correctly. Moving to acceptance.
