### ISSUE TITLE
NCD - Medication Not Distributed - New Option [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#412]
## Issue 
There was a request to add in the option "no medication prescribed today" as a reason as to why medication was not distributed. 

<img width="492" alt="Screen Shot 2022-08-11 at 3 06 34 PM" src="https://user-images.githubusercontent.com/77505464/184250869-3f0e0e42-b5d5-4e9f-9afa-fc02716b00d2.png">

## To Do 
- Add in option

**Comment by anvmn** [comment]
@jeanette-pelizzon Is this for NCD only, or globally?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> option "no medication prescribed today" as a reason as to why medication was not distributed

This sounds strange to me.
Nurse is asked if she prescribed medication (today), answeres no, and when asked why not, says because  "no medication prescribed today".

**Comment by jeanette-pelizzon** [comment]
- just for NCD 
- the option was requested by the team or wendy (i can't remember who) so we should include it.

// @anvmn

**Comment by jeanette-pelizzon** [comment]
@anvmn update from wendy - we no longer need to do this. I will close this issue.
