### ISSUE TITLE
ANC - Multiple referral options [12h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#413]
At current state. we can refer to single facility, while there can be 3 different option:

- Hospital (or HC for CHW)
- Mental health specialist
- HIV program

We want to allow reffering to multiple facilities. Each option with it's follow up questions.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app/

### QA Review

### Found issues and questions.

1. Doing postpartum encounter, patient has 185/120 blood pressure. This is not indicated in the Progress report, and no referral occurs for high blood pressure. It is not included in the postpartum part of the Logic Master excel sheet. Is this OK? 

Vitals|Referral|Progress report
-|-|-
![image](https://user-images.githubusercontent.com/3536805/186626921-d665361a-c170-48fc-b165-d4dc189086ea.png)|![image](https://user-images.githubusercontent.com/3536805/186625947-52da07e5-ba44-4c09-b237-7aa051abf770.png)|![image](https://user-images.githubusercontent.com/3536805/186625688-d8172902-6e31-4037-8032-edb89a8bb4ae.png)

2. When patient is referred to mental health specialist, it is not indicated in the progress report. Or is it just the EPDS line under obstetrical diagnosis?:
![image](https://user-images.githubusercontent.com/3536805/186629900-af07aa53-4341-442a-b0d5-c10dee840b58.png)

3. Typo in Doxycycline prescription for Gonorrhea: 
![image](https://user-images.githubusercontent.com/3536805/186633615-7e79bda3-9e04-4e84-9545-7dcd31488240.png)

4. Typo in question about hc having ARV services program.
![image](https://user-images.githubusercontent.com/3536805/186638165-65be782b-2b02-4b4f-81ac-09cb81a768b9.png)


### Checked and approved:

1.  When patient has Urinary incontinence and Suicide risk, and HC has no mental health specialist, the patient is referred only to hospital.
![image](https://user-images.githubusercontent.com/3536805/186629183-357d37ac-2875-4d63-bada-39deb2270099.png)

2. When there is a mental health specialist at the HC, patients are referred to both hospital and mental health specialist, if they hove other health problems too.
![image](https://user-images.githubusercontent.com/3536805/186629609-a9017b8d-f054-4ffb-a586-a2dac72342c6.png)

3. When patients were diagnosed with hypertension and HIV in previous encounter, they are referred to ARV and NCD services too.
![image](https://user-images.githubusercontent.com/3536805/186641139-ec1dd7e2-e51d-4d3a-ada9-acfbd8665968.png)

**Comment by adamhstewart** [comment]
@adamhstewart please check @balagan73 's points and if OK move to acceptance.

**Comment by anvmn** [comment]
@adamhstewart 

> 1. Doing postpartum encounter, patient has 185/120 blood pressure. This is not indicated in the Progress report, and no referral occurs for high blood pressure. It is not included in the postpartum part of the Logic Master excel sheet. Is this OK?

Yes, it's ok, because at Postpartum we do not diagnose any type of Hypertension.

> 2. When patient is referred to mental health specialist, it is not indicated in the progress report. Or is it just the EPDS line under obstetrical diagnosis?:

It's per requirements:

![Selection_1096](https://user-images.githubusercontent.com/17882245/190892834-48418a29-490c-47e0-a858-5273d6f16e94.png)


Point 3 and 4 are typos, fixed at #475.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

### QA Review

### Checked and approved:

1. Typo on HIV panel is fixed.
![image](https://user-images.githubusercontent.com/3536805/191670430-70242cf8-94b7-464b-9965-d7762eb6c61e.png)

2. Typo on gonorrhea medication distribution panel is fixed.
![image](https://user-images.githubusercontent.com/3536805/191671079-3f12f1e3-dfa4-4b0a-bb00-8f4ab608d3fe.png)
