### ISSUE TITLE
NCD - Examination- Infrastructure [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#415]
## Issue 

Unlike other places that the Examination activity appears, in NCD this will only have two sub-activities -> Vitals and Core Exam. Results from the vitals section are used to diagnose hypertension so there is logic attached to those. There have been no changes to the vitals or core exam screens. 

Main Screen | Vitals | Core Exam 
--|--|-- 
<img width="342" alt="Screen Shot 2022-08-15 at 2 14 22 PM" src="https://user-images.githubusercontent.com/77505464/184719764-f6df835a-7650-4478-a696-1295c5dda6e3.png"> | <img width="226" alt="Screen Shot 2022-08-15 at 2 14 30 PM" src="https://user-images.githubusercontent.com/77505464/184719769-06880498-1724-4fac-9960-bbda9dcdef23.png"> |<img width="192" alt="Screen Shot 2022-08-15 at 2 14 41 PM" src="https://user-images.githubusercontent.com/77505464/184719771-e1aaf0a6-cc13-437b-ae2c-e8bef4c696a9.png">

## To Do: 

- Create Examination activity 
- Style sub-activity screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues:

1. Typo in Pale conjunctiva
![image](https://user-images.githubusercontent.com/3536805/193307266-41c80ad5-4af4-430f-8390-5478bc269a2e.png)


### Checked and approved:

1. Except the above mentioned typo the panels display with the same options as on the design.

Vitals
![image](https://user-images.githubusercontent.com/3536805/193306651-119b8552-2f40-4b11-9ca6-303098fbdcf6.png)

**Comment by jeanette-pelizzon** [comment]
@Diama1 can you please update the typo that was found during QA - thank you!

**Comment by Diama1** [comment]
> @Diama1 can you please update the typo that was found during QA - thank you!

Sure!

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for retesting
