### ISSUE TITLE
NCD - Labs - Infrastructure [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#416]
## Issue 

We will have several labs activities in the NCD Module. SVG's can be found in Figma in the components file. These labs all require the lab orders (the labs activity in the encounter) AND the lab results screens in the appropriate place. 

- Random Blood Sugar 
<img width="119" alt="Screen Shot 2022-08-15 at 2 20 00 PM" src="https://user-images.githubusercontent.com/77505464/184720539-48067db1-bc6a-44e7-a666-2c05896e0966.png">

- Creatinine (New)  
<img width="98" alt="Screen Shot 2022-08-15 at 2 20 03 PM" src="https://user-images.githubusercontent.com/77505464/184720606-d8007c76-0763-419f-9f51-47db576712f6.png">

- Urine Dipstick 
<img width="109" alt="Screen Shot 2022-08-15 at 2 20 09 PM" src="https://user-images.githubusercontent.com/77505464/184720626-241d7575-32e3-414e-bd44-a3a4f808d991.png">

- HIV 
<img width="90" alt="Screen Shot 2022-08-15 at 2 20 12 PM" src="https://user-images.githubusercontent.com/77505464/184720640-cb7ab8ab-e6f5-4d36-bd9d-e41da50b5780.png">

- Pregnancy 
<img width="119" alt="Screen Shot 2022-08-15 at 2 20 16 PM" src="https://user-images.githubusercontent.com/77505464/184720657-cc9a8035-216d-4a08-b914-13c48a13b7d5.png">

- Liver Function (New) 
<img width="94" alt="Screen Shot 2022-08-15 at 2 20 27 PM" src="https://user-images.githubusercontent.com/77505464/184720675-80169c89-02bf-4988-bb26-6a3ff1f4f381.png">

## To Do
- Create infrastructure for Labs activities

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. The choices under Laboratory are the same as listed here.
![image](https://user-images.githubusercontent.com/3536805/193310074-0819fb27-67f1-4864-8c70-4c7f16cc91d9.png)
