### ISSUE TITLE
NCD - Labs - Random Blood Sugar [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#417]
## Issue 

NCD labs will include Random Blood Sugar tests. The results from this test will be used to diagnose diabetes. 

**Lab Order**
<img width="295" alt="Screen Shot 2022-08-15 at 2 23 36 PM" src="https://user-images.githubusercontent.com/77505464/184721138-1cde0386-f2f7-490f-803d-4f90ea182cab.png">

**Lab Results**
<img width="216" alt="Screen Shot 2022-08-15 at 2 25 14 PM" src="https://user-images.githubusercontent.com/77505464/184721211-42c2e3ea-c421-46cd-892d-2d6e0ae98857.png">

## To Do 
- Style screens per design 
- Create required back end logic (if needed)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Patient was fasting, blood level of 127, diagnoses displays correctly but not indicated on progress report. Same when patient was not fasting.
![image](https://user-images.githubusercontent.com/3536805/193559937-fc124aa9-77ae-4256-a2fa-30ed413d70d9.png)

2. On progress report Normal range is 74-110, but we diagnose above 126. Is this OK?
![image](https://user-images.githubusercontent.com/3536805/193560015-0c84bd6e-e231-4102-8f45-cf0d1876eb10.png)

3. As I remember the word fasting is not used in Rwanda and 'before meal' should be used.

Fasting|Non-fasting
-|-
![image](https://user-images.githubusercontent.com/3536805/193560219-cf28f193-a9ae-4c1b-81c1-916906efd909.png)|![image](https://user-images.githubusercontent.com/3536805/193561134-3a22ba18-a4da-4b85-9551-090bb26953d3.png)

4. When measurement is taken after meal, on the progress report the before meal normal range is indicated, and the measurement is marked with red even if it is far from the diagnosable limit.
![image](https://user-images.githubusercontent.com/3536805/193561840-bc4eab57-0300-4100-9eaf-332915f31396.png)

### Checked and approved:

1. The limits specified for diagnoses work correctly. See the images with found issues point 3.

**Comment by jeanette-pelizzon** [comment]
1. unsure why its not appearing on the progress report
2. this is accurate - the normal ranges are 74 -110 and the patient had 126 which is well above the normal range and therefore abnormal and an issue. 
3. @Diama1 can you confirm if this wording is okay in a medical situation please?
4. I believe that the normal range encompasses both. 

@anvmn

**Comment by jeanette-pelizzon** [comment]
3. The team thinks that the results should be "diabetes with before a meal glucose levels (fasting) ....." and "Diabetes with after meal glucose (non-fasting) levels of...."

**Comment by adamhstewart** [comment]
@jeanette-pelizzon regarding:

point 3: I don't think we can go with that wording as it is grammatically incorrect in English. Could we propose: `Diabetes, observed levels before a meal (fasting)` and `Diabetes, observed levels after a meal (non-fasting)`

point 4: Is that definitive?

**Comment by jeanette-pelizzon** [comment]
3. That works for me. 
4. I double checked with Wendy. These numbers are NOT for gestational diabetes but can be used for any other: 
-  Fasting: 74 mg/dL - 126 mg/dL  = Normal
- Non-Fasting: 74 mg/dL  - 200 mg/dL  = Normal

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

> Fasting: 74 mg/dL - 126 mg/dL = Normal
Non-Fasting: 74 mg/dL - 200 mg/dL = Normal

There can not be 2 normal ranges.
If you want to redefine it somehow, please open a separate issue.
Note that this is relevant for Antenatal labs as well.

**Comment by jeanette-pelizzon** [comment]
Since we ask if the test is fasting or not in the flow can't each one have a separate range? Essentially they are two different tests at that point

**Comment by adamhstewart** [comment]
@anvmn decision for RBS:
-  record the measurement and whether it was taken fasting or non fasting, 
- dynamically indicate if it's out of range depending on the type of test (on the progress report), 
- Plot it on the graph as is (no conversion) but with some sort of point indicator (label) that it is fasting or non fasting

**Comment by adamhstewart** [comment]
@jeanette-pelizzon can you adapt the design to show the label (something like F and NF) that would occur on the graph along with a legend if you think it is necessary?

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

This is how I made it look.
![Selection_1415](https://user-images.githubusercontent.com/17882245/207961158-4a9ffd6f-f5ef-48af-8d17-ed6b7c8f503b.png)

 Tell me if you want to change it.

**Comment by anvmn** [comment]
@LudmilaGoichman 

The testing here is for this problem: https://github.com/TIP-Global-Health/eheza-app/issues/417#issuecomment-1284301539

Requirements are defined here: https://github.com/TIP-Global-Health/eheza-app/issues/417#issuecomment-1351953413

Note that this is for ANC and NCD.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- Nutrition env

### Found Issues/Questions:
1. NCD. All values less than 80 (not including) are not displayed on the graph.
2. I asked Adam and he said to add a notation next to the range in the lab results.
<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210259347-e336b2cd-819e-4268-9626-2f2b99996243.png">
And I think also in Lab History screen:
<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210261605-56fc4a38-f52f-4c60-8ffe-b1957f9f53d0.png">
3. NCD. When a result is entered on the activity screen, the activity doesn't move to the Completed tab and the encounter cannot be closed.
<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210259723-9ca67281-e098-4594-8eee-a3144f42e68b.png">
4. A completed record of NCD Lab Results in Case management doesn't disappear until the screen is refreshed.
<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210260116-e5a00a53-ed9e-4840-9cd6-9d6f2f9a624b.png">
5. Lab results from an NCD encounter of the same adult woman do not appear in the ANC lab history and vice versa. This is okay? Example:

1 NCD Encounter | ANC Encounter | 2 NCD Encounter | 2 NCD Encounter - lab history|
---|---|---|---
<img width="366" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210267107-6e1bead1-215f-4081-a6b8-650f1e495e22.png">|<img width="366" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210267219-d3fb7c06-b6ba-4b79-908a-64c5f4f51ae3.png">|<img width="366" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210267302-19819a94-e08a-4881-94d0-a33f25abdcf0.png">|<img width="366" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210267362-4f3607bd-5bca-4854-81ed-4d49cb7e10b1.png">

### Checked and Approved:
1. ANC and NCD. Normal values for fasting and non-fasting ranges appear in black, and abnormal values appear in red on the Lab Results screen.
Examples:

NCD:

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210263549-98f9c7a4-be0e-4332-8847-d62a89c52566.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210263618-75079077-c885-4330-a181-6a229bdebd0b.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210263763-a6f47596-304a-4489-9f73-7e220b88ccdb.png">
---|---|---

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210263724-69b78b1e-da78-40a4-a469-d1d29d862bf6.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210263909-2f682cd1-8311-483f-9c24-6af4f558e5fd.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210263964-e9a96cc3-908e-4da7-a427-83322ce982c6.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210263991-9eba1716-4696-448f-b2ae-350bb6144e15.png">
---|---|---|---

Lab history:
<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210262964-d5a5236e-b7c3-4443-97ae-3e2beb724b20.png">

ANC:

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210264104-65541def-1738-405b-a0ec-0fb23c191a0a.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210264153-0cb2690f-825e-4d30-a894-789ef2fbd1b5.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210264187-2dfdb219-3f3d-4811-ab0c-eab3acf5a0c3.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210264222-514e6eb3-25e4-435d-a659-d68a47e4b50b.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210264277-459a1498-107c-436e-b02e-985960e51ff8.png">
---|---|---|---|---

2. NCD. Fasting non-fasting ranges are marked on the graph:
<img width="366" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210265083-a523dc47-5841-4e77-b401-88e56780c3cd.png">

**Comment by anvmn** [comment]
@LudmilaGoichman 

Points 1, 2 and 4 fixed at https://github.com/TIP-Global-Health/eheza-app/pull/581.

> 3. NCD. When a result is entered on the activity screen, the activity doesn't move to the Completed tab and the encounter cannot be closed.

Can't reproduce this. Tried locally, and on Nutrituion env.
Also, tried to access the patient at the screenshot (Bs4), but it's a 5 years old child, and we allow
NCD encounters starting age of 12. So, I don't really understand how you managed to work with child at all.
Anyway, please repeat the test with valid patient, and if problem reproduces, send me patient name.

> 5. Lab results from an NCD encounter of the same adult woman do not appear in the ANC lab history and vice versa. This is okay?

These are 2 different types of encounters, and each shows only the its own results.

**Comment by LudmilaGoichman** [comment]
@anvmn 

> Can't reproduce this. Tried locally, and on Nutrituion env.
> Anyway, please repeat the test with valid patient, and if problem reproduces, send me patient name.

Patient Bs03.1 (nutrition env.). In fact, this is due to the fact that the last HBA1C activity (in the Laboratory) cannot be saved (and this doesn't depend on a Random Blood Sugar test). This activity can only be saved if the answer to the first question is "no". (video below)

> but it's a 5 years old child, and we allow
NCD encounters starting age of 12. So, I don't really understand how you managed to work with child at all.

I registered a new participant after selecting encounter type "Noncommunicable Diseases" . And there are no age restrictions and 2 questions that don't usually appear together - Marital Status and Mode delivery were shown. This can also be seen in the video.
And the list shows some young people:

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210380206-71d0bf9d-b696-4567-a208-457345a34dc8.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210380004-e5c46c9f-3835-4a14-a064-8cd7cc394fa1.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210380136-1017dc5a-6834-407d-ae62-0b6c04ea88ac.png">
---|---|---

And I have additional question: Is this ok that the Pregnancy test is shown for males?

<img width="360" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210381035-638e14d0-79de-4008-b4c4-b53efd45a7bb.png">

https://user-images.githubusercontent.com/35059802/210368966-426e25be-470d-4c28-b8d1-a52a67fef57f.mp4

**Comment by anvmn** [comment]
@LudmilaGoichman 

>  In fact, this is due to the fact that the last HBA1C activity (in the Laboratory) cannot be saved  

Please mention this at HBA1C activity issue.
Fixed at #581.

> I registered a new participant after selecting encounter type "Noncommunicable Diseases" . And there are no age restrictions 

This is a bug. Age should be restricted to 12 years or older. Fixed at #581.

> Is this ok that the Pregnancy test is shown for males?

No, it should be only for women of child bearing age.
Note that in our case it's 13 to 45, so if you have a 12 years old girld, the test should not appear.

**Comment by LudmilaGoichman** [comment]
@anvmn 

> Please mention this at HBA1C activity issue.

I will add this bug to the relevant issue

>>Is this ok that the Pregnancy test is shown for males?

>No, it should be only for women of child bearing age.
Note that in our case it's 13 to 45, so if you have a 12 years old girld, the test should not appear.

Should I add this bug ^^ to some issue? or it will be fixed here?

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env

### Question:
1. Are the following fields relevant to participants after the age of 12? (an adult may not know how he was born (mode of delivery - mandatory field) and could already forget the Child HMIS number.)

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211198258-564f835d-32b6-4af0-a9e4-da9a3c7a573f.png">

### Checked and Approved:
1. The registration a new participant after selecting encounter type "Noncommunicable Diseases" has age restrictions:
<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211198061-da782a5b-812c-403b-9e41-08af56ac241e.png">

2. The list of participants doesn't show persons under the age of 12
3. Other bugs will be retested in the relevant issues

**Comment by anvmn** [comment]
@LudmilaGoichman 

> Are the following fields relevant to participants after the age of 12? (an adult may not know how he was born (mode of delivery - mandatory field) and could already forget the Child HMIS number.)

Indeed, this is not ok. I've deployed a fix.
Please update APP version and retets.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- nutrition env

### Checked and Approved:

The fields "Mode of Delivery" and "Children' HMIS number" have been removed from the participant's registration form for the NCD encounter

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211278858-86cfb710-bf82-4ddf-924d-e4d517962aac.png">
