### ISSUE TITLE
NCD - Labs - Creatinine [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#418]
## Issue 

NCD introduces a new type of lab called Creatinine. One lab is pulled but there are three results inputs (similar to urine dipstick). These results will eventually diagnose and help monitor chronic kidney disease. At this point in time, it helps us see if someone has hypertension with renal complications so there is logic associated with these results. See the [Logic Master](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=211600820) for more information. 

**Lab Order**
<img width="298" alt="Screen Shot 2022-08-15 at 2 26 49 PM" src="https://user-images.githubusercontent.com/77505464/184721727-6004fc5a-bcf7-46f7-838e-7fff7a8b019f.png">

**Lab Results**
<img width="248" alt="Screen Shot 2022-08-15 at 2 27 01 PM" src="https://user-images.githubusercontent.com/77505464/184721740-c0b8ca78-30f7-4e62-9cc4-87483badd43f.png">

## To Do 
- Style screens per design 
- update any logic (if needed)

**Comment by jeanette-pelizzon** [comment]
@anvmn changes had to be made to the lab results input screen for creatinine. Urea + Nirtogen results are a combo result called BUN. Updated in figma. 

<img width="256" alt="Screen Shot 2022-09-08 at 10 59 23 AM" src="https://user-images.githubusercontent.com/77505464/189194463-5e489def-dafd-4e7c-b21b-ccafc0eff300.png">

**Comment by anvmn** [comment]
@jeanette-pelizzon ^^ requires separate issue, since this issue was implemented and merged.
I opened #477.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. BUN result is available.
![image](https://user-images.githubusercontent.com/3536805/193529794-6c6bf24a-1b67-4ffc-aa05-73a392574f83.png)
