### ISSUE TITLE
NCD - Labs - Urine Dipstick [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#419]
## Issue 

NCD labs will feature the usual Urine Dipstick lab. They will be able to choose if they run the short or the long dip when they order the lab and the results screen will show the appropriate inputs. There is logic associated with the glucose results in these lab results. 

**Labs Order**
<img width="282" alt="Screen Shot 2022-08-15 at 2 46 21 PM" src="https://user-images.githubusercontent.com/77505464/184724015-2c754658-1c71-400d-9b9f-920740ec97f2.png">

**Lab Results - Long**
<img width="198" alt="Screen Shot 2022-08-15 at 2 47 00 PM" src="https://user-images.githubusercontent.com/77505464/184724073-7d247983-6db6-4d54-9181-b0a86c66abe0.png">

**Lab Results - Short**
<img width="198" alt="Screen Shot 2022-08-15 at 2 47 06 PM" src="https://user-images.githubusercontent.com/77505464/184724098-16f6ad0e-e1e8-4e4c-a476-eed7631dedf0.png">

## To Do: 
- Style screens per design
- Adjust necessary logic (if needed)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Grammar. I think either the 'a' or the plural 's' should be dropped.
![image](https://user-images.githubusercontent.com/3536805/193535599-ac856bcc-da45-4cd4-b6ff-4ab6f7540220.png)

2. The results of the NCD encounter are displayed in the Antenatal progress report. Is this OK? I can find the hypertension diagnoses, but not the Diabetes.
![image](https://user-images.githubusercontent.com/3536805/193537562-6da679e0-8927-4bb8-ab7b-3e08e34926d0.png)

3. Results are still pending, but they display as abnormal in progress report. I selected Long dipstick, but both short and long dipstick displays.

Short dipstick|Results pending
-|-
![image](https://user-images.githubusercontent.com/3536805/193541240-496fe941-075a-47fe-8d80-85eba1e422ef.png)|![image](https://user-images.githubusercontent.com/3536805/193541286-0583e447-afca-46ed-a9e6-4c42dc9fe276.png)

4. The Specific gravity test results are missing from Long dip test results, but I think that was removed in another issue. See image below in point 1. 

### Checked and approved:

1. Panels and questions display as designed.

![image](https://user-images.githubusercontent.com/3536805/193539025-853e03a5-a1ad-455f-ae2d-db0991b5ebe1.png)

Long dip|Short dip
-|-
![image](https://user-images.githubusercontent.com/3536805/193542608-44ee97fe-afe6-4ce4-84a7-c9f57a30dddf.png)|![image](https://user-images.githubusercontent.com/3536805/193546595-83b40a6a-0ff4-485d-ab77-a1b3258fd48d.png)

2. Diagnosis works correctly according to fasting/non-fasting glucose levels.

**Comment by jeanette-pelizzon** [comment]
1. Change to " Patient has diabetes with Urine Dip glucose levels of # " 
2. Progress report heading should read NCD Progress report 
3. Only the dipstick that was selected should appear with answers. This is the same as ANC so it should mimic whatever happens in the progress report there.

@Diama1 can you please update these - thank you! 

@anvmn tagging your for the lab results issue so we can make sure that's not happening across the board for the urine dipstick.

**Comment by anvmn** [comment]
@adamhstewart 

> 1. Spelling

Fixed and deployed to Nutrition env.


> 2. The results of the NCD encounter are displayed in the Antenatal progress report. Is this OK? I can find the hypertension diagnoses, but not the Diabetes.

Have hard time believing in this, because Antenatal and NCD are 2 different modules, and each of the reports loads its own set of data.
Please retest.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

>> 3 . Results are still pending, but they display as abnormal in progress report. I selected Long dipstick, but both short and long dipstick displays.

> Only the dipstick that was selected should appear with answers. This is the same as ANC so it should mimic whatever happens in the progress report there.

1. Behavior is identical to ANC.
2. Short test presents 3 measurements. Long test presents 10, including the 3 from short test. At report, for each of measurements, we present all results - short test shows results of 3 measurements (both from short and long), and long results shows those 3 from short and long + other 7 which exist only at long test. Therefore, when long test is done, at progress report, we expect to see results both at short and long sections, which explains current behavior.
3. Abnormal value at dip stick for pendng results - at ANC, definition was: Normal, if all results are Normal when pressing -> arrow. Abnormal otherwise. This is the logic we apply for pending - not all are normal, therefore, abnormal. If it needs to change, please open separate issue with new requirements.

//cc @adamhstewart

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for retesting (points 1 and 2)

**Comment by jeanette-pelizzon** [comment]
@anvmn Thanks for the clarification. I wasn't aware about the long and short showing when you ran long but that makes sense to me. Seems like everything is functioning as it should then!
