### ISSUE TITLE
NCD - Labs - Pregnancy [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#420]
## Issue 

We need to test women of child bearing age for pregnancy in NCD as it creates other complications and will be handled by other services.

Notes: 
- this test only populates for women of child bearing age as we have previously defined in the app 
- only the first questions should populate - if answer is yes, record and move on. If answer is no, then the rest of the question will populate. 

**Lab Order**
<img width="272" alt="Screen Shot 2022-08-15 at 2 53 27 PM" src="https://user-images.githubusercontent.com/77505464/184724849-11c206d2-0215-44d3-b513-1bb7edad2b43.png">

**Lab Results**
<img width="293" alt="Screen Shot 2022-08-15 at 3 05 32 PM" src="https://user-images.githubusercontent.com/77505464/184726396-e891042f-0e28-4531-ad64-bc10e3ac17c5.png">

## To Do
- Style screens per design 
- create the logic for it to only appear for certain patients 
- adjust any other necessary logic

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Isn't pregnancy an RDT test, similar to HIV?

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. The Register a new participant under NCD encounter is not working.
![image](https://user-images.githubusercontent.com/3536805/193557817-ab2eaf5b-1d4f-4e7f-bf65-2f538157f47e.png)


### Checked and approved:

1. Questions regarding pregnancy are populated per the conditions.

Test performed|Not performed
-|-
![image](https://user-images.githubusercontent.com/3536805/193527536-9272d66e-4b82-41f8-96cb-57847b40feab.png)|![image](https://user-images.githubusercontent.com/3536805/193527624-15164499-3d82-4a14-9fbb-7c7b854df5e9.png)

2. Pregnancy is correctly displayed on progress report if result is positive.
![image](https://user-images.githubusercontent.com/3536805/193539437-8387897a-c8a4-4944-819b-fd50eb602c5b.png)

3. Pregnancy test is not displaying for girls under age of 13 or women above 45.

Too young|Too old
-|-
![image](https://user-images.githubusercontent.com/3536805/193557613-8ea68b4c-d5e4-4ca0-b231-3d198b4ca4ec.png)|![image](https://user-images.githubusercontent.com/3536805/193558178-383dfb96-2deb-4e4d-bb41-c483eb56dcab.png)

**Comment by jeanette-pelizzon** [comment]
@anvmn Seems like something is weird with adding a new participant. Moving this back to To Do for QA followup

**Comment by anvmn** [comment]
@adamhstewart Fixed and depoyed to Nutrition env for retesting

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app/#individual-participants/ncd

### QA Review

### Checked and approved:

1. The register a new participant link under NCD encounter is correctly working, I have created a new patient.
![image](https://user-images.githubusercontent.com/3536805/199459743-e528d444-dd9c-4f8e-9822-0b9ccacc80ec.png)
