### ISSUE TITLE
NCD - Labs - Liver Function [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#421]
## Issue

We are introducing liver function tests in the NCD encounter. At this point, we do not have any logic associated with these results but that may change in the future. 

**Lab Order**
<img width="336" alt="Screen Shot 2022-08-15 at 3 08 06 PM" src="https://user-images.githubusercontent.com/77505464/184728404-861ec19d-f55b-49d9-9d53-1edb0017fe1b.png">

**Lab Results**
<img width="230" alt="Screen Shot 2022-08-15 at 3 07 57 PM" src="https://user-images.githubusercontent.com/77505464/184728450-b6591970-302c-476d-8935-04dfafd8b924.png">

## To Do
- Style screens per design 
- adjust any necessary logic

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. Liver function tests are available under Laboratory
![image](https://user-images.githubusercontent.com/3536805/193520468-78090f26-99ea-490a-9780-ce137f5202fe.png)
