### ISSUE TITLE
NCD - Family Planning [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#422]
## Issue 

We are adding in the family planning activity for women of child bearing age in the NCD encounter. This is the same activity that appears elsewhere in E-heza and no changes have been made to it. There is no logic associated with this activity at this time. 

<img width="366" alt="Screen Shot 2022-08-15 at 3 22 02 PM" src="https://user-images.githubusercontent.com/77505464/184729518-fa71c139-fa92-4b4a-80cf-d3beef284ff4.png">
<img width="368" alt="Screen Shot 2022-08-15 at 3 22 06 PM" src="https://user-images.githubusercontent.com/77505464/184729526-74f26594-dee2-40ec-977c-856bebce2cc0.png">

## To Do 
- create necessary infrastructure 
- style screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. UI displays with the same options as on the design.

![image](https://user-images.githubusercontent.com/3536805/193305966-05da9479-ebd9-4303-a206-bcff6ac0cd94.png)
