### ISSUE TITLE
NCD - Next Steps - Infrastructure [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#423]
## Issue 

Similar to the ANC module, in NCD we will have labs drawn, the patient will (theoretically) wait for their results to come back later that day and then have next steps associated with those labs then. We are bringing over the exact same flow from ANC with the exception of needing to re-do vitals. The vitals do NOT need to be rechecked in NCD. 

Here is a rough overview of the flow:
Main encounter -> any next steps that can be diagnosed already -> case management -> enter lab results -> next steps diagnosed from lab results

## To Do:
- Create infrastructure 
- Create Logic

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. After finishing the QA for almost all the NCD issues, I haven't encountered any problems with the Next steps infrastructure, it works correctly.
