### ISSUE TITLE
ANC - Progress Report Wording [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#424]
## Issue 

We need a way to show that a diagnosis was previously diagnosed but just input into E-heza at a later date. 

For example, a syphilies lab was ordered on March 1 but we didn't get the result into e-heza until April 13 at the patients next visit. We will then have in the progress report "Syphilis previously diagnosed on XX/XX/XXX."

**Comment by anvmn** [comment]
@jeanette-pelizzon 

I made text a little bit more detailed - `[Diagnosis] diagnosed on XX/XX/XXXX as a result of entering lab results from past encounter.`

//cc @balagan73

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

### QA Review

### Checked and approved:

1. Text on the progress report is shown as @anvmn suggested.
![image](https://user-images.githubusercontent.com/3536805/191305777-dc23efde-7433-429c-a5d4-2782d0d26943.png)
