### ISSUE TITLE
NCD - Activities Infrastructure [16h] 

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#437]
There are 20 activities. For each we need to:

- Create CT on backend
- Expose with Restful
- Prepare infrastructure on client

**Comment by balagan73** [comment]
@anvmn Where do I find the list of Activities/CTs?

**Comment by anvmn** [comment]
@balagan73 This issue is infrastructure for activities that will be tested at dedicated issues.
It's enough to verify thoses issues. 
This one does not require QA.
