### ISSUE TITLE
NCD - Infrastructure - 2 Part Encounter

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#438]
## Issue

NCD is a 2-part encounter, similar to ANC. There will be labs drawn in the first part of the encounter and certain diagnoses will not be able to be given until lab results are back in. 

NCD Encounter Activites -> next steps where anything can be diagnosed already is diagnosed -> patient waits for lab results -> lab results are put in via case mgmt -> next steps where any remaining diagnoses are made

Case Management | Second Part of Encounter | Second Next Steps 
--|--|--
<img width="367" alt="Screen Shot 2022-08-24 at 4 25 32 PM" src="https://user-images.githubusercontent.com/77505464/186540794-93e7357f-37a4-43ae-b69e-870c0b1ff462.png"> | <img width="326" alt="Screen Shot 2022-08-24 at 4 25 42 PM" src="https://user-images.githubusercontent.com/77505464/186540796-49bb485c-4373-44f8-bd03-fb4640939192.png"> |<img width="269" alt="Screen Shot 2022-08-24 at 4 25 51 PM" src="https://user-images.githubusercontent.com/77505464/186540798-eecc888a-6afd-4493-a2c8-2df988ad2ef3.png">

## To Do: 

- Set up the encounter infrastructure to be the 2 parts

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. I have finished the QA of many issues where lab results were entered in case managements. No problem was encountered with the 2 part encounter infrastructure.
