### ISSUE TITLE
NCD - Labs - HIV [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#455]
## Issue 
We will be running an HIV RDT in the NCD encounter. This HIV lab will be exactly like the HIV RDT flow that we run in ANC. Quick video [here.](https://www.loom.com/share/eb514489750749c99ccdde4375d5b371)

## To Do: 
- Build out HIV lab sub-activity

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Questions are populated per the flow displayed in the video.

Test not performed|Positive|Negative
-|-|-
![image](https://user-images.githubusercontent.com/3536805/193529081-ef3ffebe-5035-494b-b074-5f0fa7ff7e42.png)|![image](https://user-images.githubusercontent.com/3536805/193529146-c09f2d5c-0954-4bf8-972f-fc7ad93a658e.png)|![image](https://user-images.githubusercontent.com/3536805/193529175-5a26ad0b-8d86-4c07-94c9-02203d0a2470.png)
