### ISSUE TITLE
NCDA - Standard Pediatric Visit [7h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#462]
## Issue 

We are adding in an activity to the Standard Pediatric Visit called "Questionnaire." This activity has 14 yes/no boolean questions. The answers will be mapped to the NCDA child scorecard. It will be the last activity before next steps in the SPV encounter. 

The Questionnaire activity will use the history icon. 
<img width="375" alt="Screen Shot 2022-09-13 at 1 21 18 PM" src="https://user-images.githubusercontent.com/77505464/190003993-29ca77d2-3da8-4f66-a432-4892ac2c2fee.png">

The activity itself is just a list of boolean questions. None of the answers from this affect next steps, they will only map to the NCDA scorecard. 
<img width="247" alt="Screen Shot 2022-09-15 at 8 54 42 AM" src="https://user-images.githubusercontent.com/77505464/190450655-734de3b3-49cb-4393-9e2d-7bddefe8a2d3.png">

## To Do: 
- create Questionnaire activity in the SPV encounter
- style screen per design
- any necessary backend logic

**Comment by jeanette-pelizzon** [comment]
Note: updated image in main issue, wording was changed. Please double check with Adam or Jeanette for final wording on the "meal frequency" question as this is still outstanding with the team.

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for QA

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. There are only 12 questions for children under 6 months (Meal frequency shouldn't display), but that should leave us with 13 questions. The image in issue description also has 13 questions, but text says 14. Is that OK?
![image](https://user-images.githubusercontent.com/3536805/201327617-efa08edc-b4d1-4daa-9d69-4dab8281b59c.png)

### Checked and approved:
1. Questions appear as NCDA activity with the history icon.
![image](https://user-images.githubusercontent.com/3536805/201327197-c72ede1c-f3f9-402e-a2c3-951f10ccc837.png)

**Comment by adamhstewart** [comment]
> There are only 12 questions for children under 6 months (Meal frequency shouldn't display), but that should leave us with 13 questions. The image in issue description also has 13 questions, but text says 14. Is that OK?


All questions are accounted for.
