### ISSUE TITLE
NCDA - Individual Nutrition Encounter [7h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#463]
## Issue 

We are adding in an activity to the Nutrition Encounter at the Healthcenter (FBF) called "Questionnaire." This activity will appear in both the individual and group encounter. This issue specifically deals with the individual encounter.

The Questionnaire activity has 14 yes/no boolean questions. The answers will be mapped to the NCDA child scorecard. It will be the last activity a nurse completes with a patient. 

<img width="203" alt="Screen Shot 2022-09-15 at 8 50 57 AM" src="https://user-images.githubusercontent.com/77505464/190450011-7c3042b6-e678-4fe1-adcc-fdf54d671618.png">

## To Do: 
- Add in the Questionnaire to the individual nutrition encounter at the health center 
- style screen per design 
- update any back end logic

**Comment by jeanette-pelizzon** [comment]
Note: updated image in main issue, wording was changed. Please double check with Adam or Jeanette for final wording on the "meal frequency" question as this is still outstanding with the team.

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for QA

**Comment by balagan73** [comment]
### QA Review

### Checked and approved

1. NCDA card displays with 13 questions for individual nutrition encounter.

1|2
-|-
![image](https://user-images.githubusercontent.com/3536805/201330041-e6096964-e8c2-4c96-86e8-913dd3b718a4.png)|![image](https://user-images.githubusercontent.com/3536805/201330172-dce9595b-d796-4c65-8fea-cf77fbeb1db6.png)
