### ISSUE TITLE
NCD - Progress Report - Patient Information [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#466]
## Issue 
The patient information pane will be the same as it is on acute illness progress reports. 

It should include: 

- patient photo 
- LAST NAME First Name 
- Age: 
- Date of Birth: 
- Gender 
- Village 
<img width="777" alt="Screen Shot 2022-09-14 at 3 32 54 PM" src="https://user-images.githubusercontent.com/77505464/190274631-4562d192-03ce-4195-869e-e8d42c21db17.png">

## To Do: 
- Style pane on the progress report per design

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. Patient information on the progress report contains correct information and is styled correctly.
![image](https://user-images.githubusercontent.com/3536805/193599767-d6ac4821-07e4-4a08-b79f-948198f4b94a.png)
