### ISSUE TITLE
NCD - Progress Report - Risk Factors [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#467]
## Issue 

The risk factors pane will list the following, all of which pull from questions asked in the encounter:  

- smokes cigarettes 
- adds salt to diet 
- family history of hypertension 
- family history of heart problems 
- family history of diabetes 

This was the list that I was given to include. Anything not on this list we can assume should not be included. 
See meta issue for full progress report design 

<img width="735" alt="Screen Shot 2022-09-14 at 3 40 23 PM" src="https://user-images.githubusercontent.com/77505464/190275502-bf6015a6-ad00-41f4-8676-66a0ebb94c47.png">

## To Do: 
- style screen pane per design 
- update back end to pull correct information

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Risk factors display the items requested.
![image](https://user-images.githubusercontent.com/3536805/193519998-ea4442de-7bda-4f5c-a90f-1df4d0d143e8.png)
