### ISSUE TITLE
NCD - Progress Report - Acute Illness [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#468]
## Issue 

The acute illness pane on the progress report should be exactly like the acute illness progress report. It should have any current acute illnesses and then the option to view past acute illnesses. 

<img width="561" alt="Screen Shot 2022-09-14 at 3 56 33 PM" src="https://user-images.githubusercontent.com/77505464/190277277-d1de5b66-d346-480d-85aa-765030642539.png">

## To Do: 
- pull over the acute illness pane design and logic from the acute illness progress report.

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for QA

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. The title of the section on the NCD progress report is called Active Diagnosis, not Acute Illness. Is that a problem?
![image](https://user-images.githubusercontent.com/3536805/202146531-620f4266-6859-459f-81a3-fcbe77cc6c02.png)

### Checked and approved:

1. Progress reports look the same for NCD and Acute illness encounters.

Acute illness history pane in NCD encounter|Acute illness encounter
-|-
![image](https://user-images.githubusercontent.com/3536805/202146732-b6bb5c21-a941-4786-bf01-6a98bc50702b.png)|![image](https://user-images.githubusercontent.com/3536805/202146971-75048cbc-0654-4876-91f6-4e6c620b7585.png)

**Comment by adamhstewart** [comment]
> The title of the section on the NCD progress report is called Active Diagnosis, not Acute Illness. Is that a problem?

@jeanette-pelizzon seems this is correct as is, can you clarify?

**Comment by jeanette-pelizzon** [comment]
It is correct in the screenshot. Moving to Acceptance Testing. 

// @adamhstewart
