### ISSUE TITLE
NCD - Progress Report - Medical Diagnosis [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#469]
## Issue 

The medical diagnosis pane will populate with answers from the co-morbidities sub-acitvity. If they check yes to one of those it should map to the medical diagnosis pane. 

Then it will also list the diagnosis from this visit - any hypertension or diabetes diagnosis that we confirm during this encounter and what medication we gave out to treat it. 

You can view t[his loom](https://www.loom.com/share/e7d067216a014d9699fda52cfde6d24e) around the 2:00 mark if you need more info. 

<img width="403" alt="Screen Shot 2022-09-14 at 4 00 50 PM" src="https://user-images.githubusercontent.com/77505464/190277760-0754b7da-cd36-46b3-9a7a-eea26ccdff1e.png">

## To Do: 
- create logic for this pane 
- style pane per design 
-

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. Selecting the co-morbidities display their counterpart under progress report.

Co-morbiditites|Progress report
-|-
![image](https://user-images.githubusercontent.com/3536805/193589213-943a00eb-ef62-4169-a6d0-9de727d9a44f.png)|![image](https://user-images.githubusercontent.com/3536805/193589107-f9007a08-41fe-4446-8374-03b069fb054e.png)
