### ISSUE TITLE
NCD - Progress Report - Patient Progress [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#470]
## Issue 

The patient progress section of the progress report contains 2 graphs - blood pressure and blood glucose 

**Blood Pressure**
Blood pressure is taken at each visit and should be mapped on a graph. Systolic and Diastolic should be separate dots on the graph. Style the graph per the image below. The y axis of the graph should start at 60 and move up in increments of 20. The x axis of the graph will have a notch for each time the patient is seen in an NCD encounter. To keep the graph uncluttered, let's only show the past 12 data points (essentially a years worth of data).

<img width="672" alt="Screen Shot 2022-09-14 at 4 05 53 PM" src="https://user-images.githubusercontent.com/77505464/190278220-397639c3-afb5-4ee0-9dc3-a189234b2f6f.png">

**Blood Glucose**
Blood glucose is taken at every visit and should be mapped on a graph. The y-axis of the graph shows the glucose level starting at 60 and moving up in increments of 30. Style the graph per the image below. The x axis of the graph will have a notch for each time the patient is seen in an NCD encounter. To keep the graph uncluttered, let's only show the past 12 data points (essentially a years worth of data). 

<img width="672" alt="Screen Shot 2022-09-14 at 4 07 24 PM" src="https://user-images.githubusercontent.com/77505464/190278488-861ed4bc-71c6-4c94-96ce-1ded148780eb.png">

## To Do 
- create graphs and logic associated 
- style graphs per design

**Comment by jeanette-pelizzon** [comment]
QUESTION: can a nurse go into the back end and see dates further in the past than that?

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for QA

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. The Y axis of the glucose graph is increasing in increments of 20, not 30.
![image](https://user-images.githubusercontent.com/3536805/199476179-198cbaab-18d4-4f79-ba11-f039b663209b.png)


### Checked and approved:

1. Apart from the above problem the graphs are displaying correctly.
![image](https://user-images.githubusercontent.com/3536805/199476460-4fd8c752-d1b5-4559-940c-6a88ab4e2fb1.png)

**Comment by adamhstewart** [comment]
> The Y axis of the glucose graph is increasing in increments of 20, not 30.

@anvmn was this a choice or an oversight?

**Comment by adamhstewart** [comment]
@anvmn ^^

**Comment by anvmn** [comment]
@adamhstewart
Oversight. Can make it 30 if needed.

**Comment by jeanette-pelizzon** [comment]
Per conversation on 1/16, making increments in 30 to match design

**Comment by anvmn** [comment]
@adamhstewart Fixed. Ready for QA.

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn 

- nutrition env
- tablet

### Not Fixed Issue:
 The y-axis of the glucose level graph doesn't move up in increments of 30.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220143350-23cdbcca-5f59-47c9-ac16-47d22b694d08.png">

**Comment by adamhstewart** [comment]
@anvmn I'm also seeing increments of 20 - was this not deployed or do we need some sort of refresh?

**Comment by adamhstewart** [comment]
@anvmn the team found this issue:

> When the patient has stage one hypertension and is pregnant in the first encounter, it doesn’t give the prescription of  Methyldopa as it is described in the issue. we only see the Health Education of Stage one Hypertension

**Comment by anvmn** [comment]
@adamhstewart This did not get deployed with previous release.
Will be on next one.

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn

- nutrition env
- tablet

### Checked and Approved:
The y-axis of the glucose level graph moves up in increments of 30.
<img width="357" alt="image" src="https://user-images.githubusercontent.com/35059802/236677341-4068d940-c54f-4866-a934-175c231009d6.png">
