### ISSUE TITLE
NCD - Progress Report - Labs [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#471]
## Issue 

The NCD progress report will have a labs section. The workflow of the design will be the exact same as ANC - the only change is in what tests are appearing on the report. The two new tests we have added are Liver Function and Creatinine. I have included a screenshot of what their screens should look like below. 

**Lab Results** | **Liver Function** | **Creatinine** 
--|--|--
![Lab Result Pop Out](https://user-images.githubusercontent.com/77505464/187319286-d5a02e59-71c7-4626-8ef5-6cbd761b1487.jpg) | ![Liver Function](https://user-images.githubusercontent.com/77505464/187319295-87b86fa7-9554-44f8-a9d0-ee40ffa2a66c.jpg) | <img width="431" alt="Screen Shot 2022-08-30 at 11 33 00 AM" src="https://user-images.githubusercontent.com/77505464/187515966-d2343973-9e94-41f4-921d-232edaaf44e3.png">

## Issue 
- Create Labs flow in the NCD progress report
- update what tests appear so they are specific to NCD (outlined in screenshot above) 
- create Liver Function and Creatinine screens (new tests) 
- Style screens per design

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. On the Lab results page there is no Liver function test name, but ALT and ALS. Is this OK?
![image](https://user-images.githubusercontent.com/3536805/193533650-b596fc62-4781-417b-bc0e-396dcf183de4.png)

2. On the Lab results page there is an ALS entry, but when I click on it, it displays AST test history. As AST result is entered, I suppose the ALS on the Progress report should be also AST.
![image](https://user-images.githubusercontent.com/3536805/193533784-e99ebdb6-06d6-4723-85e0-ff4c162fde28.png)


### Checked and approved:

1. Liver function and Creatinine screens exist.

Liver function|Creatinine
-|-
![image](https://user-images.githubusercontent.com/3536805/193518152-8c973288-230b-4de3-9a4c-796e5a281c7c.png)|![image](https://user-images.githubusercontent.com/3536805/193518161-da0e9edc-91b4-434f-b4e0-aa58c1df4077.png)

Lab results|Test history
-|-
![image](https://user-images.githubusercontent.com/3536805/193518596-7491adda-d8d5-432b-a2b8-5237dbd48dbc.png)|![image](https://user-images.githubusercontent.com/3536805/193533008-d09cbdf0-d18a-4c42-a252-6a82ddff308b.png)

**Comment by adamhstewart** [comment]
@anvmn please check points 1 and 2

**Comment by anvmn** [comment]
@adamhstewart 

> 1. On the Lab results page there is no Liver function test name, but ALT and ALS. Is this OK?

The thing here is that one test got 2 measurements.
We have 2 approaches for this:
1. Urine dipstick test (that got multiple measurements) consist of extra level.
2. Blood group that consist of 2 measurements - blood grooup and rhesus.

Since we have only 2 measurement at Liver function test, I selected second option.
We switch to the alternative - will require ~2h.

> 2. On the Lab results page there is an ALS entry, but when I click on it, it displays AST test history. As AST result is entered, I suppose the ALS on the Progress report should be also AST.

Correct. Fixed at [7231074](https://github.com/TIP-Global-Health/eheza-app/pull/508/commits/72310743b46a4bbf77d9707c4eb1499bd0e9fc98).

**Comment by jeanette-pelizzon** [comment]
ALT + ALS = Liver Function Labs. They can appear on the lab report separately. If we get feedback that the lab results section is too long we can combine them (like Urine Dip) but I like them showing separately because it = less clicks for user. It is my understanding that blood group and rhesus aren't really looked at often for diagnosis so they can stay hidden until needed - the only come into play during labor/delivery.

**Comment by jeanette-pelizzon** [comment]
@anvmn if you feel strongly they should be grouped then that we can group them. Up to you.
