### ISSUE TITLE
NCD - Labs - Creatinine test - replace Urea + Nirtogen with BUN  [2h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#477]
Changes had to be made to the lab results input screen for creatinine. Urea + Nirtogen results are a combo result called BUN. Updated in figma. 

<img width="256" alt="Screen Shot 2022-09-08 at 10 59 23 AM" src="https://user-images.githubusercontent.com/77505464/189194463-5e489def-dafd-4e7c-b21b-ccafc0eff300.png">

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Creatinine Lab results are updated with BUN result.
![image](https://user-images.githubusercontent.com/3536805/193517795-e5632f11-ad37-4ae1-81ea-9c34eea3dcab.png)
