### ISSUE TITLE
Pathway from First to Second Phase of ANC encounter [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#479]
## Issue
- If an encounter is finished (no vitals recheck or test results), at the end of the first phase the nurse should be presented with the progress report and the button to close the encounter
- If there are vitals recheck or tests, progress report is not shown at the end of the first phase, but will be shown later in the second phase only after all required activities are completed.

## Task
- Adapt workflow accordingly

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for QA (a bit late for that, as it's on live already, but nevertheless...)
