### ISSUE TITLE
Improve installation instructions/process [3h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#486]
## Issue

The installation instructions could use a little fine tuning and abstraction for cross platform (non-linux) use. Also, it seems that the frontend installation might be broken.

- The instructions should geared toward a developer that is interested in a quick setup via either Gitpod or local DDEV
- Any infrastructure related information, deployment information specific to a particular installation should be moved top the bottom in favor of a quick start up. (i.e backend install, frontend install, initiate sync, and go...)
- command line instructions should be clear about directory context (i.e. if you need to be in `/client` be sure there's a `cd client` instruction.
- Installation should work across platforms

## Tasks
- Update instructions for clarity using above guidelines.
- Test across platforms to ensure success.

**Comment by AronNovak** [comment]
@adamhstewart Would you spend time with GitPod? It just got removed from the Starter Kit: https://github.com/Gizra/drupal-starter/pull/298

**Comment by adamhstewart** [comment]
@AronNovak I think there's some benefit here, but is it a significant burden to maintain?

**Comment by adamhstewart** [comment]
@AronNovak during post-start I get this error on MacOS:

```
> node-sass@4.13.1 install /var/www/html/client/node_modules/node-sass
> node scripts/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/client/node_modules/node-sass/scripts/install.js:7:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm WARN gulp-jshint@2.1.0 requires a peer of jshint@2.x but none was installed.
npm WARN generated-elm@0.1.0 No repository field.
npm WARN generated-elm@0.1.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /mnt/ddev-global-cache/npm/eheza-app-web/_logs/2022-09-22T12_24_19_296Z-debug.log
```

**Comment by AronNovak** [comment]
@adamhstewart Got it, let's try to keep GitPod then.

**Comment by AronNovak** [comment]
![image](https://user-images.githubusercontent.com/114076/191908707-9faccdb5-8c49-4f89-b64f-e3e6fd6b89b8.png)
GitPod is broken at the moment

**Comment by AronNovak** [comment]
@adamhstewart @isapisa 

What about extending the scope a bit?
I don't have access to a Mac and ScaleWay.com has a lengthy personal verification before I can order one in the cloud.

But just spotted:
https://circleci.com/docs/using-macos - CircleCI could continuously keep an eye on if we are compatible with Mac or not.
But it would require to double the TB, as it's a new territory for me.

**Comment by adamhstewart** [comment]
@AronNovak we can expand the time box for this ^^

**Comment by AronNovak** [comment]
@adamhstewart Let's treat it as done and handle Mac compatibility separately.
