### ISSUE TITLE
NCDA - Logic [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#496]
## Issue 

The NCDA questionnaire activities/subactivities only need to appear for children 1 day old to 24 months (2 years) old. We do not collect data after a child is 24 months. 

## Issue 
- Create logic for questionnaire activity/subactivity

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for QA

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Child is under 2 years, NCDA questionnaire displays. Above 2 years there is no questionnaire.

Under 2 years|2 years + 1 day
-|-
![image](https://user-images.githubusercontent.com/3536805/201317028-d8674db7-3999-4c42-b385-9e06196e8d55.png)|![image](https://user-images.githubusercontent.com/3536805/201325433-4f0b55a9-57c8-42c7-b4be-2300f5d0e3bf.png)
