### ISSUE TITLE
NCD - Typos Medication History 

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#498]
## Issue 

What is appearing in the nutrition environment is different than what is in the design. 

Nutrition | Design 
--|--
<img width="515" alt="Screen Shot 2022-10-11 at 3 45 06 PM" src="https://user-images.githubusercontent.com/77505464/195212144-945cfba2-dca1-420c-9d2b-52c62a29fc2c.png"> | ![Medical History 22](https://user-images.githubusercontent.com/77505464/195212041-800674dd-08f5-487b-9fdf-967b46e10b0c.jpg)

## To Do: 

- Style Screens per Design

**Comment by anvmn** [comment]
@jeanette-pelizzon I think this was one of the findings made when testing NCD.
Putting this issue on hold, till I can confirm this.

//cc @adamhstewart

**Comment by adamhstewart** [comment]
@jeanette-pelizzon are these issues covered in other QA followups?

**Comment by anvmn** [comment]
@adamhstewart see https://github.com/TIP-Global-Health/eheza-app/issues/401#issuecomment-1265048138

**Comment by jeanette-pelizzon** [comment]
> @jeanette-pelizzon are these issues covered in other QA followups?

Yes, tackled in #401. I will close this issue.
