### ISSUE TITLE
NCD - Design Descrepency  [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#499]
## Issue 

NCD Labs 

Name/title of the Lab should be in Nunito - Bold - 24px and the questions are in Nunito - Semi-Bold - 24px. Right now it looks like the name/title of the lab is smaller than the questions.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

This is how it looks with title and question at 24px:

![Selection_1172](https://user-images.githubusercontent.com/17882245/196413236-12c4aa17-ab80-45c3-a114-4f750b090c61.png)


I believe that we better have title at 24px and question at 22px:

![Selection_1173](https://user-images.githubusercontent.com/17882245/196413224-4a3dbe8e-2fe4-4c08-b244-a9ae163e12d2.png)

Tell me if you disagree.

**Comment by jeanette-pelizzon** [comment]
Mine looked different. I should have grabbed a screenshot because the title was much smaller but it seems you have set up correctly. Will things look different in nutrition environment if I have to do inspector -> tablet view?

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for QA

**Comment by adamhstewart** [comment]
@jeanette-pelizzon please double check
