### ISSUE TITLE
NCDA - Food Groups Question [6h] 

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#500]
## Issue 

We are adding a help box for one of the questions on the NCDA questionnaire to ensure that nurses are properly documenting the answer. 

**Add the little question mark as shown here.** The red box is only there to show where the question is and is not a part of the design: 
![Group Encounter Activity](https://user-images.githubusercontent.com/77505464/195218045-2e0576f3-3a4f-4d9b-99d4-7812b1982c10.png)

**Pop- Up with more information:** 
Pop up should look like other help pop-ups that already exist. I couldn't find any easily to mimic this so just did a rough outline of one so you have the text. 
![Group Encounter Activity-1](https://user-images.githubusercontent.com/77505464/195218043-eecde73a-9c60-499e-afee-4f793d32523f.png)

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Add the little question mark as shown here

Can we get this as an SVG icon?

**Comment by jeanette-pelizzon** [comment]
Sent via slack. Let me know if you need it a different way.

**Comment by anvmn** [comment]
@adamhstewart Depoyed to Nutrition env for QA

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Eggs appear in two food groups.
![image](https://user-images.githubusercontent.com/3536805/201321938-8f00703b-a026-4735-b603-baee5b4459d5.png)
2. I think cereals are not legumes, I myself would put that in the staples (grain) category). Also, I don't see nuts here, and maybe little children are not fed nuts, but right now answering these questions I would select Fruits and vegetables for nuts, but I think they belong to a different nutritional category.

### Checked and approved:

1. The question mark icon and the popup displays as requested.
![image](https://user-images.githubusercontent.com/3536805/201321525-19739779-f0af-4dd7-b57c-336f15b23aa4.png)

**Comment by adamhstewart** [comment]
@jeanette-pelizzon can you clarify the wording form the point above?

**Comment by jeanette-pelizzon** [comment]
@adamhstewart This was the exact wording given by Valens. I believe he pulled it from somewhere. I think it is okay? We can clarify with him if needed.
