### ISSUE TITLE
NCD - Design Discrepency - Physical Exam [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#505]
## Issue 

What is appearing in the Nutrition Environment is different than appears in design. We need the Physical exam activity to be accurate in order to pull in the information we need to diagnose. 
 

This is what appears in the nutrition environment: 
<img width="498" alt="Screen Shot 2022-10-12 at 8 20 22 AM" src="https://user-images.githubusercontent.com/77505464/195383670-9d7d659e-e396-4ad8-a0ae-d97360f612c9.png">

This is what it should look like. 
![Physical Exam - Vitals 1](https://user-images.githubusercontent.com/77505464/195383742-cd3f5730-cdb6-4676-a251-d7a6927a7874.jpg)

[Figma is here.](https://www.figma.com/file/uDLvcOC9dAqoWyluzJnuuS/NCD's?node-id=411%3A9422)

**Comment by anvmn** [comment]
@jeanette-pelizzon

I suppose that that patient of yours is child?
If so, please note that per requirements, we do not take BP till age of 12 years.

**Comment by jeanette-pelizzon** [comment]
Sorry, was rushing. I'll double check that we don't need NCD to do younger than 12 but ignore this for now.

**Comment by adamhstewart** [comment]
@jeanette-pelizzon have you double checked - can we close this one?

**Comment by jeanette-pelizzon** [comment]
Per conversation with Wendy on 10/17, children will not be using the NCD module. We do not need to change anything to accommodate for children.
