### ISSUE TITLE
NCDA - Child Scorecard - Where + Who [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#513]
## Issue 

~~This issue may need to be broken down further.~~

**Where does the NCDA Child Scorecard Appear:** 
We are presenting the NCDA Childscorecard for an individual child at the end of any FBF encounter of Standard Pediatric Visit ~~after the progress report is shown. The button at the bottom of the progress report that usually ends the encounter will then take them to the NCDA Scorecard and the encounter can be ended from there. The scorecard should also appear in the patient record.~~ at Progress report.
Progress report will consist of 2 tabs - the report itself and NCDA scoreboard.

- See #514 changes to patient record.  
 
**What patients does this appear for**: This is for all children ~~2 years of age and younger~~.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Is there a Figma flowchart to demonstrate this?

**Comment by anvmn** [comment]
@LudmilaGoichman 

This issue is about places for presentation of NCDA scorebaord.
Bottom line is that we show it in tabs at:
- Patient record
- All SPV reports (group and individual Nutrition + SPV encounter).

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- nutrition env

### Question:
1. The description only mentions the FBF encounter, but the ECD Scorecard is also shown in the following encounters. Is this correct?

PMTCT group nutrition encounter:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204994-3669b596-08da-4524-a170-d6381b642b22.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211205008-bf69a802-c9ea-44b0-b07f-19aec66b5913.png">
---|---

Group nutrition encounter (CHW):

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211205139-daa51baa-9ae7-4ada-9880-0ab24fd15fcc.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211205162-726baf04-dcbb-4cd6-a16b-eff8b048523c.png">
---|---


### Checked and Approved:
ECD Scorecard is displayed for children in the next encounters:
1. Participant directory:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204776-1a2bbe87-9243-4769-a88e-2e6edcafe714.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204805-cebc8976-c904-45ec-8460-22271242c682.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204830-53392745-78a0-4930-ac0d-66dee202bb9b.png">
---|---|---


2. Individual child nutrition encounter:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204861-9ff40a77-6fcd-4ba5-b992-e9c926230058.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204871-57c8450b-3c36-4baa-91f1-e524d87d65fc.png">
---|---

3. Standard pediatric visit encounter:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204886-921266e1-0f4b-4086-824c-84058740551e.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204898-0beafa17-11e2-4f49-8324-b050e546cd27.png">
---|---

4. FBF group nutrition encounter:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204937-87402dbb-a836-4213-84bf-af7c9d3050e7.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204965-b1bdf373-8dfc-4b63-b9bf-dab152a580a3.png">
---|---

5. PMTCT group nutrition encounter:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204994-3669b596-08da-4524-a170-d6381b642b22.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211205008-bf69a802-c9ea-44b0-b07f-19aec66b5913.png">
---|---

6. Newborn exam encounter (CHW):

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211205049-b6515865-389c-4583-bba4-c9ba17c2a357.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211205068-eb6b901e-fa6f-49e5-b474-c2275406b7b5.png">
---|---

7. Individual child nutrition encounter (CHW):

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211205096-3e921d76-5598-4aff-a650-4212f3619184.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211205115-5f2b91e2-d68d-49d3-9b66-d61d350b0724.png">
---|---

8. Group nutrition encounter (CHW):

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211205139-daa51baa-9ae7-4ada-9880-0ab24fd15fcc.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211205162-726baf04-dcbb-4cd6-a16b-eff8b048523c.png">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

It's ok to have it at all group and CHW as well.
