### ISSUE TITLE
Patient Record - Add NCDA [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#514]
## Issue 

We have to make some changes to the way pediatric records are shown in the patient record section. Previously, pediatric patients just had one report card so there were no options at the top as there are for adults. Now that we are introducing the NCDA scorecard there are two options of reports for pediatric patients. 

To accommodate the new report, we are updating the pediatric screen to mimic those of adults. They will have two options: Standard Pediatric Report and NCDA Scorecard. They will still be able to enter into pediatric encounters from either of these

This is what it should look like for the Standard Pediatric Report Option. We are just adding in the selection bar at the type. Nothing has changed on the report itself. The button on the bottom goes to start encounter (same as it is currently in patient record) 
![Patient REcord - Antenatal Care-1](https://user-images.githubusercontent.com/77505464/197043859-3ff93a1a-4c28-42a2-a56a-6a8a4ad6256f.jpg)

![Child - Start Encounter](https://user-images.githubusercontent.com/77505464/197044050-75352a9c-ff0e-4896-a94d-c0a469806bee.jpg)

This is what it will look like for NCDA scorecard. The scorecard is the same as appears in encounters. We are just adding the selection bar at the top. It will also have the start encounter button at the bottom same as SPV record.

![Patient Record - NCDA](https://user-images.githubusercontent.com/77505464/197044247-d4cc9cd4-4d50-46e9-adfd-b33e6ba1ced6.jpg)

![Child - Start Encounter](https://user-images.githubusercontent.com/77505464/197044285-ab793a9a-6920-4c62-96a7-3cc534d51097.jpg)

## To Do: 
- Make adjustments to pediatric patient record - add in the selection bar, add in the NCDA scorecard.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Weight for height chart is missing from the Standard pediatric report.

Standard pediatric report
![image](https://user-images.githubusercontent.com/3536805/207001202-4713805d-6d78-4828-823e-68d332980f4d.png)

2. The Early childhood development section is horizontally wider than the screen, but it's not possible to scroll with the mouse or with the scrollbar (arrows on keyboard work, but on mobile devices they are not available.)

![image](https://user-images.githubusercontent.com/3536805/206999695-35c58dec-29ba-4e98-b421-f0bfbdc13450.png)

### Checked and approved:

1. The two tabs display on the page, available encounter types match the ones in description.

Pediatric report|NCDA Scorecard
-|-
![image](https://user-images.githubusercontent.com/3536805/207000906-8ebfb703-2237-4fcc-8f54-3bb5ce604938.png)|![image](https://user-images.githubusercontent.com/3536805/207000926-1b4d583a-41b8-40e7-898a-896ae994971e.png)

Encounters:
![image](https://user-images.githubusercontent.com/3536805/207000184-3bc20062-9ec9-4d56-b8b5-68cd911c5f27.png)

**Comment by adamhstewart** [comment]
problems found found not related to this issue
