### ISSUE TITLE
[META] NCDA - Scorecard Where to Pull Info [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#515]
## Issue 

The NCDA Scorecard pulls data from various encounters and parts of E-Heza. Some of the data is being pulled from the new questionnaire activity so that needs to be developed first. 

We are checking the data monthly from the first month of pregnancy until the child is 2 years of age (24 months). The scorecard will be updated everytime a child is seen during a Standard Pediatric Visit, FBF (Nutrition), or an acute illness visit. There may be a time when a child has multiple visit types in a month. The scorecard should update accordingly. Example: patient has an FBF visit at 2 months and 3 days old so the scorecard will update with the information it can obtain from an FBF visit. At 2 months and 15 days old, the patient goes in for a Standard Pediatric Visit. The scorecard will then update the missing information with the information it has gathered from that visit. If information overlaps, the scorecard should update with the most recent information. 

[Here is a spreadsheet](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1194481634) that Theo put together and I added onto. It shows where to pull the data from and then when it should be marked as a red x, a green check, or a dash. Work off of the Master Sheet tab as I don't know what the other tabs are for. 

If there are questions on the spreadsheet please put them all in one comment here and I can get answers from the team as this is the spreadsheet only information I have. 

## Related Issues

#517 
#518
#519
#520 
#521
#525 
#526

**Comment by anvmn** [comment]
@jeanette-pelizzon 

This is a META issue.
Please open a separate issue for each pane of the report, where we'll discuss the requirements.
From what I see, some of these rows involve complex logic requiring substantial effort, which we'll have to estimate

**Comment by anvmn** [comment]
@jeanette-pelizzon 

At the spreadsheet, for many rows, source data is NCDA Questionnaire.
As you know, we have an option to have it filled from multiple sources.
Also, each source allows filling it more than once.

Therefore, per:

>  If information overlaps, the scorecard should update with the most recent information.

Presented data will be from last Questionnaire that was filled.


//cc @adamhstewart

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
