### ISSUE TITLE
NCDA - Scorecard Design [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#516]
## Issue 

The NCDA Child Scorecard will appear at the end of Standard Pediatric Visits, FBF visits, and in the Patient Record. Currently, healthcare workers in Rwanda are using a paper version of the scorecard. The digital version I have created is a digital replica of the paper version as requested by NCDA and the local team. Implementing the digital version will help NCDA (a govt body) better track pediatric data across Rwanda. 

Here is the design for the scorecard. 
[Acute Illness Ongoing.pdf](https://github.com/TIP-Global-Health/eheza-app/files/9834630/Acute.Illness.Ongoing.pdf)

## Issue 
- Style screen per design 
- See issue #515 for associated "logic"

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. Born underweight, Burn defect, Ubudehe, Father or Chief of Family's name and ID information is missing.
![image](https://user-images.githubusercontent.com/3536805/207003799-8f382a60-87fa-4153-ac0c-1f782e240ff0.png)

2. 6 months is abbreviated as 6 mo. It is per the PDF, but I think we could just add those 5 missing letters.
![image](https://user-images.githubusercontent.com/3536805/207004918-3a37507e-f951-4eea-8a67-222e6ce1beba.png)

3. 'Level of stuning' should be 'Level of stunting'
![image](https://user-images.githubusercontent.com/3536805/207006419-4a20089d-cb6e-462a-884e-bd0e4967c617.png)

**Comment by adamhstewart** [comment]
@anvmn Can you check the missing information in point 1 and fix the spelling in point 3?

**Comment by anvmn** [comment]
@adamhstewart 

> Born underweight, Burn defect, Ubudehe, Father or Chief of Family's name and ID information is missing.

The logic in code hides fields in case we have no info for them.
So, for listed fileds there's no info for that particular child, so, we don't show them.

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn 

- nutrition env
- tablet

### Questions/Not Fixed Issues:
1. I also think there is a typo in the word "stuning".

<img width="175" alt="image" src="https://user-images.githubusercontent.com/35059802/220169509-9a1a6946-739c-4564-8a87-dab870eddbe6.png">

2. This question/bug isn't related to this issue. the data collected during the Newborn Exam encounter (CHW) isn't reflected in the progress report (the data was synced). Is it okay on this env?

<img width="99" alt="image" src="https://user-images.githubusercontent.com/35059802/220170624-75bbbf65-2b54-499d-85c3-cb278bf6ed7e.png">


### Checked and Approved:
1. All required data is displayed (if any)

<img width="183" alt="image" src="https://user-images.githubusercontent.com/35059802/220167881-18d3e5fe-ec77-4897-a84e-cca77fb77a6e.png">

4. "mo" is used in most places in the application. It can be "month-old" and not "months"

<img width="176" alt="image" src="https://user-images.githubusercontent.com/35059802/220168244-b84ed72c-d0a4-4af3-8989-998268e5e9a9.png">

**Comment by adamhstewart** [comment]
@anvmn can you fix (1) the typographical issue; (2) investigate @LudmilaGoichman 's other question.

**Comment by anvmn** [comment]
@adamhstewart 

> @anvmn can you fix (1) the typographical issue; (2) investigate @LudmilaGoichman 's other question.

Point 1 fixed.
Point 2 - styling issue. Fixed.
