### ISSUE TITLE
NCDA Scorecard - Data Pulling - Universal Intervention Section

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#518]
## Issue 

**Immunization**

_What module is the data being pulled from_: Standard Pediatric Visit 

_Green Checkmark on scorecard_: if the child is up to date on their vaccines @adamhstewart how can we define up to date OR should this be if they received a vaccine that month? 

_Red X on scorecard:_ not up to date or no vaccines given (dependent on @adamhstewart answer)

_Dash on scorecard_: no data recorded - a missed appointment  

**Vitamin A**

Note: Under 6 months of age, this will be a dash for all children as they do not get vitamin A until 6 months.

 _What module is the data being pulled from_: Standard Pediatric Visit 

_Green Checkmark on scorecard_: eligible and received

_Red X on scorecard:_ eligible and did NOT receive

_Dash on scorecard_: not eligible or N/A 

_*they only receive Vit A every 6 months*_

**Deworming**

Note: Under 12 months of age, this will be a dash for all children as they do not get dewormer until 12 months.

_What module is the data being pulled from_: Standard Pediatric Visit 

_Green Checkmark on scorecard_: eligible and received

_Red X on scorecard:_ eligible and did NOT receive

_Dash on scorecard_: not eligible or N/A 

_*they only receive this every 6 months*_

**Did you receive and use Ongera-MNP?**

_What module is the data being pulled from_: New questionnaire

_Green Checkmark on scorecard_: yes to the question on the questionnaire activity 

_Red X on scorecard:_  no to the question on the questionnaire activity

_Dash on scorecard_: no data recorded - a missed appointment 

**ECD services provided to parents and child**

_What module is the data being pulled from_: Standard Pediatric Visit 

_Green Checkmark on scorecard_: if child is on track for ECD

_Red X on scorecard:_  If a child is behind on ECD 

_Dash on scorecard_: no data recorded - a missed appointment 

<img width="799" alt="Screen Shot 2022-10-24 at 1 14 25 PM" src="https://user-images.githubusercontent.com/77505464/197620075-48558b3b-6618-4b79-abeb-ce97aa373f90.png">

## Related Issues/Docs: 
- Meta Issue: #515 
- [Reference document](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1194481634)t. Use the master tab. 
- [Figma ](https://www.figma.com/file/bP3qdRVzCW6bUrmjS0hIco/Nutrition-%40-HC?node-id=316%3A188)

**Comment by jeanette-pelizzon** [comment]
@adamhstewart for ECD - we only track at specific months. I would say we should mark green if we have them listed as on track on Eheza even if it isn't a month that is an ECD tracking point. Thoughts?

**Comment by jeanette-pelizzon** [comment]
updated the master sheet for this and the main issue here for vitamin a and the dewormer. They only get it every 6 months - it seems like sometimes this is a national campaign and maybe sometimes not? @adamhstewart

**Comment by balagan73** [comment]
### QA Review

### Checked and approved:

1. Marks correctly appear.

Child under 6 month|Between 6 and 12 months.
-|-
![image](https://user-images.githubusercontent.com/3536805/207082676-c1053e6e-c20f-4b2b-b6dc-6d10da9d3faa.png)|![image](https://user-images.githubusercontent.com/3536805/207038950-3ef651b8-f195-4398-9ad1-146c66572a5c.png)

2. Deworming properly displays for child above 12 months.
![image](https://user-images.githubusercontent.com/3536805/207331565-077a612b-6f70-4fcc-96e9-0cdf509963de.png)
