### ISSUE TITLE
NCDA - Data Pulling - Nutrition Behavior 

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#519]
## Issue 

**Breastfed baby for 6 months without interruption**

_What module is the data being pulled from_: New Questionnaire (this question appears for the first 6 months months of life then switches to the complementary feeding question)

_Green Checkmark on scorecard_: yes to the questionnaire 

_Red X on scorecard:_ no to the questionnaire

_Dash on scorecard_: no data recorded - a missed appointment  

**Appropriate complementary feeding (6-24 mo)**

_What module is the data being pulled from_:  New Questionnaire (this question appears for the after the first 6months months of life - it switches out the breastfeeding question)

_Green Checkmark on scorecard_: yes to the questionnaire 

_Red X on scorecard:_ no to the questionnaire

_Dash on scorecard_: no data recorded - a missed appointment  

**Does the child have a diverse diet?**

_What module is the data being pulled from_:  New Questionnaire  - Question reads as "Does the child receive food items from the 5 food groups?"

_Green Checkmark on scorecard_: yes to the questionnaire 

_Red X on scorecard:_ no to the questionnaire

_Dash on scorecard_: no data recorded - a missed appointment 

**Number of times a child eats a day**

_What Module is the data being pulled from:_ New questionnaire - it is an age dependent question - 1. From 6 up to 9 months: Feed your young child complementary foods 2 to 3 times a day 
2. From 9 up to 12 months: Feed your young child complementary foods 3 to 4 times a day 
3.  From 12 up to 24 months: Feed your young child complementary foods at least 5 times a day

_Green Checkmark on scorecard_: yes to the questionnaire 

_Red X on scorecard:_ no to the questionnaire

_Dash on scorecard_: no data recorded - a missed appointment 

<img width="563" alt="Screen Shot 2022-10-24 at 1 39 33 PM" src="https://user-images.githubusercontent.com/77505464/197625555-d0b82153-b67e-438e-9afe-cc95d369e710.png">

## Related Issues/Docs: 
- Meta Issue: #515 
- [Reference document](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1194481634)t. Use the master tab. 
- [Figma ](https://www.figma.com/file/bP3qdRVzCW6bUrmjS0hIco/Nutrition-%40-HC?node-id=316%3A188)

**Comment by anvmn** [comment]
@jeanette-pelizzon  

![Selection_1230](https://user-images.githubusercontent.com/17882245/199598225-d9269081-e0f9-46a3-a089-e6d3653a35e9.png)

> this question appears for the first 6 months months of life then switches to the complementary feeding question

This is not something we have implemented.
I'm not aware of any such requirements. Were there any?

**Comment by jeanette-pelizzon** [comment]
@anvmn sorry got that feedback after I made original issues. Just created #534 to cover the gap. That should be the last change before we QA with the team.

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions

1. Per https://github.com/TIP-Global-Health/eheza-app/issues/534 the question about 6 months of breastfeeding should appear when child is 6-7 months old. Is there a mandatory check at that point? Asking it, because for the review I did my first encounter when child was 10 months old, and as this question did not appear, we have all dashes on the progress report for this, even though the child might have been breastfeed correctly without interruption.

### Checked and approved:

1. Marks display correctly for child above 6 months.

All no|All yes
-|-
![image](https://user-images.githubusercontent.com/3536805/207040173-edfa9464-e0d3-4d8e-8cbe-615f4edcfdd8.png)|![image](https://user-images.githubusercontent.com/3536805/207041872-771433e6-1729-4e01-bddd-2a43cedc1688.png)

2. Breastfeeding displays correctly for child between 6-7 months
![image](https://user-images.githubusercontent.com/3536805/207344035-c15c0cf1-fe22-4530-870a-14be87c58c77.png)

**Comment by adamhstewart** [comment]
@jeanette-pelizzon I'm not suer about this question:

> the question about 6 months of breastfeeding should appear when child is 6-7 months old. Is there a mandatory check at that point? Asking it, because for the review I did my first encounter when child was 10 months old, and as this question did not appear, we have all dashes on the progress report for this, even though the child might have been breastfeed correctly without interruption.

Can you clarify?

**Comment by jeanette-pelizzon** [comment]
@adamhstewart it's my understanding that the questions are asked in real time so whatever is happening at that point in time. We aren't tracking data retroactively - at least that was never outline as something we would need to do. If we need to track retro data, we need to go back through all the questions and see how we can do that across the board and if we trust the accuracy of that.

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn Did I understand correctly that the first issue in https://github.com/TIP-Global-Health/eheza-app/issues/519#issuecomment-1346352176 should not be retested?

**Comment by anvmn** [comment]
@LudmilaGoichman correct
