### ISSUE TITLE
ANC @ Health Center - Add "Labs" to Main Activity Tray [2h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#52]
## Issue 

We are adding a "Labs" activity to ANC @ Health Centers. The icon for "Labs" needs to be added to the main activity tray (before `Photo`).

<img width="297" alt="Screen Shot 2021-11-02 at 3 48 30 PM" src="https://user-images.githubusercontent.com/77505464/139942141-c367334d-b985-4fdd-87a4-b724c95c2e06.png">

### Design

The icon can be found in the Design Assets tab in Figma [here.](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=1%3A1249) 

## To Do

- Add icon to activity tray

**Comment by anvmn** [comment]
@isapisa 

Being implemented at https://github.com/TIP-Global-Health/eheza-app/pull/16

**Comment by LudmilaGoichman** [comment]
@isapisa @anvmn 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet

### Question:
The photo activity appears on the main activity tray only after the completion of the first activity ('Pregnancy Dating'). Is it correct?

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145410115-bcb1bfc9-fe65-4780-b983-f11b9b4f8909.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145410177-81720c53-9870-4aff-a47c-ac37807301e8.png">
---|---

### Checked and Approved:
Laboratory activity has been added to the main activity tray (before `Photo`).
<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145409680-8c3b8fa7-bf08-4a7e-8fa5-f78e49dfc674.png">

**Comment by isapisa** [comment]
> The photo activity appears on the main activity tray only after the completion of the first activity ('Pregnancy Dating'). Is it correct

@LudmilaGoichman we should show that on the tray

@Diama1 assigning you for a follow-up

**Comment by anvmn** [comment]
@isapisa

I don't think change is required here.
The reason for this functionality is a conditional logic we have for displaying photo activity.
So, until we know the lmp date, we can not decide if to show it or not.

**Comment by isapisa** [comment]
@anvmn right, now that you wrote that, it rings a bell. Thanks!
