### ISSUE TITLE
NCDA Child Scorecard - Data Pulling - Targeted Interventions

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#520]
## Issue

**FBF**

_What module is the data being pulled from_:  Nutrition

_Green Checkmark on scorecard:_ received FBF 

_Red X on scorecard:_ did not receive FBF

_Dash on scorecard:_ missed apt at this tracking age 

**Treatment for Acute Malnutrition** 

_What module is the data being pulled from_:  Nutrition

_Green Checkmark on scorecard:_  Was diagnosed with malnutrition and was given treatment 

_Red X on scorecard:_ was diagnosed with malnutrition and was NOT given treatment 

_Dash on scorecard:_ was NOT diagnosed with malnutrition or missed an appt

**Treatment for Diarrhea (ORS + Zinc)** 

_What module is the data being pulled from_:  Acute Illness

_Green Checkmark on scorecard:_  Was diagnosed with diarrhea and was given treatment

_Red X on scorecard:_ was diagnosed with diarrhea and was NOT given treatment 

_Dash on scorecard:_ was NOT diagnosed with diarrhea or missed an appt

**Provide Support to a Child with a Disability**

_What module is the data being pulled from_:  New Questionnaire

_Green Checkmark on scorecard:_  Yes to the questionnaire questions

_Red X on scorecard:_ No to the questionnaire questions

_Dash on scorecard:_ missed apt at this tracking age 

**Receipt of conditional cash transfer e.g. NSDS, VUP**

_What module is the data being pulled from_:  New Questionnaire

_Green Checkmark on scorecard:_  Yes to the questionnaire questions

_Red X on scorecard:_ No to the questionnaire questions

_Dash on scorecard:_ missed apt at this tracking age 

**Receipt of conditional food items including small livestock**

_What module is the data being pulled from_:  New Questionnaire

_Green Checkmark on scorecard:_  Yes to the questionnaire questions

_Red X on scorecard:_ No to the questionnaire questions

_Dash on scorecard:_ missed apt at this tracking age 

<img width="563" alt="Screen Shot 2022-10-24 at 1 45 02 PM" src="https://user-images.githubusercontent.com/77505464/197628306-ee14b0e8-64ce-4329-a7e1-675ac8634279.png">

## Related Issues/Docs: 
- Meta Issue: #515 
- [Reference document](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1194481634)t. Use the master tab. 
- [Figma ](https://www.figma.com/file/bP3qdRVzCW6bUrmjS0hIco/Nutrition-%40-HC?node-id=316%3A188)

**Comment by jeanette-pelizzon** [comment]
@anvm I have asked the team to clarify something for the malnutrition and the diarrhea questions - will report back

**Comment by jeanette-pelizzon** [comment]
FYI: Received clarification on the definitions and updated the spreadsheet and the main issue here.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Treatment for Acute Malnutrition
Green Checkmark on scorecard: Was diagnosed with malnutrition **and was given treatment**
Red X on scorecard: was diagnosed with malnutrition and **was NOT given treatment**

Note that we have following logic for nutrition assessment: If any assessment comes up, we refer patient to Health ceneter. So, there's no special treatment for malnutrition.
Therefore, implementation will be:

Green Checkmark on scorecard: Was diagnosed with malnutrition **and was referred**
Red X on scorecard: was diagnosed with malnutrition and **was NOT referred**

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Treatment for Diarrhea (ORS + Zinc)
Green Checkmark on scorecard: Was diagnosed with diarrhea and was given treatment
Red X on scorecard: was diagnosed with diarrhea and was NOT given treatment

Note that there's not such thing as 'diagnosed with diarrhea'.
ORS + Zinc are medications that suggested when patient is diagnosed with Gastrointestinal Infection without Complications. This diagnosis is made when 'non bloody diarrhea' dymptom is present, however, that diagnosis is low at hierarchy. This means that there can be 'non bloody diarrhea' symptom present, but other indicators will lead to another diagnosis.

Another thing here is the definition of `was / was not given treatment`.
ORS and Zinc are separate medications, and it's possible to inidcate that one was given and other was not:

![Peek 2022-11-09 12-30](https://user-images.githubusercontent.com/17882245/200806932-5b3f71b6-655d-4f88-bcd4-1f4b30e024f6.gif)

When implementing this, I'll consider treatement as given if any of these medications was perscribed.
Tell me if this needs to change.

**Comment by jeanette-pelizzon** [comment]
> Green Checkmark on scorecard: Was diagnosed with malnutrition **and was referred**
> Red X on scorecard: was diagnosed with malnutrition and **was NOT referred**

@anvmn this makes sense to me. Good to go!

**Comment by jeanette-pelizzon** [comment]
> When implementing this, I'll consider treatement as given if any of these medications was perscribed.

Discussed in our meeting on 11/14, this makes sense. If they get either treatment then its a green mark. If not, it's an x mark.

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. Child had GI infection without complications (diagnosed during CHW encounter), was prescribed Zinc, but it is not reflected on the charts (during encounter with nurse):
 
Diagnosis|Chart
-|-
![image](https://user-images.githubusercontent.com/3536805/207325663-3fbfbe56-9839-498e-ac08-03228f609da7.png)|![image](https://user-images.githubusercontent.com/3536805/207325818-b4bc76c9-dbaa-4a59-98ed-6230e0c7128d.png)

### Checked and approved:

1. Checkmarks appear correctly (FBF and ORS&Zinc is not tested here) 
![image](https://user-images.githubusercontent.com/3536805/207036496-e8aa21e2-8deb-4aeb-804f-ff604bd1441a.png)

2. FBF displays correctly.
![image](https://user-images.githubusercontent.com/3536805/207333917-e4df1460-0b87-45d6-909a-d993e9ba713b.png)

**Comment by adamhstewart** [comment]
@anvmn please check issue 1 above ^^

**Comment by anvmn** [comment]
@adamhstewart 

The problem here is with Child age.
The one that is tested is 3 years old, and the illnees is recorded when child is 3 years old.
However, NCDA presents data till child is 2 years old.

**Comment by jeanette-pelizzon** [comment]
@adamhstewart do we need to change something here? I don't think we did. They should always have access to the reports but we don't need to track data after age 2.

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn 

- nutrition env
- tablet

### Question/Not Fixed Issue:
Children with GI infection without complications (diagnosed during CHW encounter), Zinc was prescribed:
1. Child 23 month 19 days age

CHW encounter (the data was synced):

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220158761-d65914b2-6b32-4851-b5c8-e6ba5c24be3e.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220158969-8269c432-917f-4894-b8f5-40d953c0f50e.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220159045-6361cfac-ecee-4044-9ea7-539c8519e2b7.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220159261-055dc264-dcc8-4341-8a76-d1e0891c8992.png">
---|---|---|----

Nurse (the data was synced). There is green checkmark

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220159570-5f8ae816-a2fd-4efb-aa06-df2fa4cc5a7b.png">


2. Child 2 years old:

CHW encounter (the data was synced):

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220157042-99b3948a-9035-42a4-b09a-89f3460cda4e.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220157204-925cc76b-db49-4138-98fc-839387255533.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220157369-8b4f025e-959e-4db0-812f-6e5b6a110ca0.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220157475-a7f4754e-2e9e-4cab-82d4-54da883c90c0.png">
---|---|---|---

Nurse (the data was synced). There is no green checkmark although the column for 2 years/24 months is present

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220158036-ebd18538-ea50-4819-96df-aa565c4e3b1c.png">
