### ISSUE TITLE
NCDA Child Scorecard - Data Pulling - Infrastructure + Environment + Wash

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#521]
## Issue

**Household has Toilets**

_What module is the data being pulled from_:  New Questionnaire

_Green Checkmark on scorecard:_  Yes to the questionnaire questions

_Red X on scorecard:_ No to the questionnaire questions

_Dash on scorecard:_ missed apt at this tracking age 

**Household has clean water**

_What module is the data being pulled from_:  New Questionnaire

_Green Checkmark on scorecard:_  Yes to the questionnaire questions

_Red X on scorecard:_ No to the questionnaire questions

_Dash on scorecard:_ missed apt at this tracking age 

**Household has handwashing facility**

_What module is the data being pulled from_:  New Questionnaire

_Green Checkmark on scorecard:_  Yes to the questionnaire questions

_Red X on scorecard:_ No to the questionnaire questions

_Dash on scorecard:_ missed apt at this tracking age 

**Insecticide Treated Bed Nets**

_What module is the data being pulled from_:  ANC

_Green Checkmark on scorecard:_  Yes to the bed net question in the malaria prevention activity

_Red X on scorecard:_ Noto the bed net question in the malaria prevention activity

_Dash on scorecard:_ missed apt at this tracking age 

**Household has kitchen garden**

_What module is the data being pulled from_:  New Questionnaire

_Green Checkmark on scorecard:_  Yes to the questionnaire questions

_Red X on scorecard:_ No to the questionnaire questions

_Dash on scorecard:_ missed apt at this tracking age 

**Insecticide treated bed nets**
_Note: this is included in issues #517 since it refers to pregnancy / we typically ask this question in ANC_ 

<img width="565" alt="Screen Shot 2022-10-24 at 2 05 37 PM" src="https://user-images.githubusercontent.com/77505464/197629336-76fc9a2e-c7c7-42bf-b98c-20658017c7c8.png">

## Related Issues/Docs: 
- Meta Issue: #515 
- [Reference document](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1194481634)t. Use the master tab. 
- [Figma ](https://www.figma.com/file/bP3qdRVzCW6bUrmjS0hIco/Nutrition-%40-HC?node-id=316%3A188)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Questions display and are marked correctly.
![image](https://user-images.githubusercontent.com/3536805/207035514-61052db7-363d-4d8e-8990-f5189ed1c36b.png)
