### ISSUE TITLE
NCDA - Data Pulling - Child Identification [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#525]
**Child Name** 

_What module is the data being pulled from_:  Demographics
 
**Date of Birth (DOB)**

_What module is the data being pulled from_:  Demographics

**Sex**

_What module is the data being pulled from_:  Demographics

**born underweight? **

_What module is the data being pulled from_:  New Questionnaire 
_Answer_: yes or no question 

**birth defect? **

_What module is the data being pulled from_:  New Questionnaire 
_Answer_: yes or no question 

**Mothers Name**

_What module is the data being pulled from_:  Demographics

**Father or Chief of the Familys Name**

_What module is the data being pulled from_:  Demographics

**Ubudehe**

_What module is the data being pulled from_:  Demographics

**ID for the Mother**

_What module is the data being pulled from_:  Demographics

**ID for the Father**

_What module is the data being pulled from_:  Demographics

<img width="571" alt="Screen Shot 2022-10-25 at 11 06 10 AM" src="https://user-images.githubusercontent.com/77505464/197848873-c61a89f7-f1d3-4eca-b1c7-0c2fa7175ff4.png">

## Related Issues/Docs: 
- Meta Issue: #515 
- [Reference document](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1194481634)t. Use the master tab. 
- [Figma ](https://www.figma.com/file/bP3qdRVzCW6bUrmjS0hIco/Nutrition-%40-HC?node-id=316%3A188)

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

Here's what we'll have to do to present required info:

- **Mother and Father deatils**:
When patien is created, we do not record any details of parents (for child) / children (for adult).
Only place we make this assicuation is at Group encounter, where we register participant to a groups (FBF / PMTCT / ...).
Adult that participates is group encounter with child can be either parent or caregiver.
So the logic we'll need to apply here: 
  1. Child participates in group with parent, and that parent is Female => Mother.
  2. Child participates in group with parent, and that parent is Male => Father.

- **Info from Questionnaire**:
Questionnaire can be filled at 3 different modules, multiple time at each.
Displayed info will be taken from most recent Questionnaire.

**Comment by anvmn** [comment]
###  Tasks:

1. Fetch data: 
 - Child
 - Person relationships (from Group encounter)
 - Mother and/or Father
 - Measurements from SPV, Nutrition and Group enconters (to get NCDA measuemenrts).

2. Present and style per design

Estimation: **6h**

**Comment by balagan73** [comment]
### QA Review

### Checked and approved

1. Data are displaying correctly on the patient record.
![image](https://user-images.githubusercontent.com/3536805/207318390-231d0e55-9abd-44d1-806e-9735da1b10d0.png)
