### ISSUE TITLE
NCDA - Data Pulling - Fill in the Blanks 

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#526]
This part of the scorecard has different inputs: 
Green C = Cyatsi (which means green in English) 
Yellow H= Hondo (which means yellow in English) 
Red T = Tuku + Ibipimo (which means red+measurements in English) 

**Level of Stunting using Child Length Mat** 
_What module is the data being pulled from:_ Height for Age Graph 

**Edema** 
If they have Edema as a symptom, it is a red 
If they do not have it, it is a green. 
There is no yellow. 

**MUAC** 
If they have a muac score that is in green, then they get the green
If they have a muac score that is in yellow, then they get yellow on this chart.  
If they have a muaz score that is in the red, then they get the red 
If it is not taken, make a dash.

**Weight**
_What module is the data being pulled from:_ Weight for Age Graph

<img width="945" alt="Screen Shot 2022-10-25 at 11 34 27 AM" src="https://user-images.githubusercontent.com/77505464/197854143-2534ad23-730a-4b53-b0b0-e92b5bcb2eaf.png">

## Related Issues/Docs: 
- Meta Issue: #515 
- [Reference document](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1194481634)t. Use the master tab. 
- [Figma ](https://www.figma.com/file/bP3qdRVzCW6bUrmjS0hIco/Nutrition-%40-HC?node-id=316%3A188)

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions.

1. It seems Edema is marked green, even if it is a symptom.
![image](https://user-images.githubusercontent.com/3536805/207051015-02e2a06b-bae2-4e08-8daa-97421b73025a.png)

Severe|Moderate|Normal
-|-|-
![image](https://user-images.githubusercontent.com/3536805/207050934-7dde15cc-13f7-4180-a934-beb95e735432.png)|![image](https://user-images.githubusercontent.com/3536805/207052526-25ea08ff-38fa-49e5-8b8f-e90128c3ab60.png)|![image](https://user-images.githubusercontent.com/3536805/207052994-89cfc188-c6ea-49b8-92f3-895924eaf6d0.png)

When I mark Severe edema under danger signs, then I am sent to register an acute illness. After registering Edema as acute illness and coming back to the progress report of the patient, Edema is still green:
![image](https://user-images.githubusercontent.com/3536805/207085020-c12dfc84-dd13-442c-ab1b-b14963149808.png)

### Checked and approved:

1. Other markings are correct, see images above.

**Comment by adamhstewart** [comment]
@anvmn pls check edema per above ^^

**Comment by anvmn** [comment]
@adamhstewart 

The logic is simple - at Nutrition activity, if Edema is checked, we show red T. If not, green C.
There's not such thing as sever / moderate Edema at Nutrition activity.
No info is pulled here from Acute Illness.

![Peek 2023-01-09 22-38](https://user-images.githubusercontent.com/17882245/211404078-3d851f47-61c0-4b23-9792-4df4ec66a63c.gif)
