### ISSUE TITLE
ANC @ Health Center - Labs - HIV [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#53]
## Issue 

The HIV RDT is performed in the first antenatal visit at the health center and at an EGA of 38 weeks. There are 4 inputs needed on the screen. 

Were you able to perform this test? If yes, you then move on to validate if it was done today. If no, you select from a series of checkboxes why not. Check box options shown here | If yes, then the question "Did you perform this test today?" appears. If yes, today's date auto-populates in the Test Date section. If no, then a date input appears and is shown here:  | Since this is a Rapid Test, results will be ready immediately. The nurse will then select the result: 
--|--|--
<img width="465" alt="Screen Shot 2021-11-03 at 12 02 35 PM" src="https://user-images.githubusercontent.com/77505464/140097219-093e3376-44a0-4fbb-90ad-ff899c31dfbd.png"> | <img width="499" alt="Screen Shot 2021-11-03 at 12 04 39 PM" src="https://user-images.githubusercontent.com/77505464/140097671-fd8d2043-0477-4922-a9d1-f87908cbf1ae.png"> | Positive / Negative / Indeterminate 

*Note: we do not have the information on what happens as the next steps based on these results yet. We will build that out at a later time. 

### Design
Please refer to [ANC Labs - Full Prototype](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A42717) in Figma for proper flow. 

**Screen 1** | **Screen 2** | **Screen 3**  | **Screen 4** | **Screen 5** 
--|--|--|--|--
<img width="250" alt="Screen Shot 2021-11-03 at 11 59 04 AM" src="https://user-images.githubusercontent.com/77505464/140098304-a38a17d2-0f18-4e33-96f1-b829bba06c0b.png"> | <img width="226" alt="Screen Shot 2021-11-03 at 3 07 12 PM" src="https://user-images.githubusercontent.com/77505464/140176537-8673c69f-0741-4887-a75b-5a5e2ad8508d.png"> | <img width="253" alt="Screen Shot 2021-11-03 at 11 59 26 AM" src="https://user-images.githubusercontent.com/77505464/140098418-3a0b7b09-4ab1-4676-bae3-af9282bd4176.png"> | <img width="254" alt="Screen Shot 2021-11-03 at 11 59 36 AM" src="https://user-images.githubusercontent.com/77505464/140098453-0317d800-70aa-409d-9856-058559ca0c42.png"> | <img width="250" alt="Screen Shot 2021-11-03 at 11 59 42 AM" src="https://user-images.githubusercontent.com/77505464/140098494-c4e6c486-b173-456b-9444-d10af1cef2fe.png">
 
_Please note the top of the screen should read "Labs" or "Lab Results" which is appropriate for the screen. Noticed after I made all the issues that the title of the screens were off._

## To Do

- Create sub-activity
- Create logic for date input and calendar
- Style per design

**Comment by LudmilaGoichman** [comment]
@anvmn @isapisa 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet

### Question:
Screens in the application contain `:` that don't exist in the design. Is this okay? //the question is relevant to all Lab sub-activities

| app | design |
---|---
<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714096-7a05b6d3-57b3-4614-848a-c69c7e856a56.png">|![140098494-c4e6c486-b173-456b-9444-d10af1cef2fe_png__500×922_](https://user-images.githubusercontent.com/35059802/145714114-42d3658f-f1ae-4332-9329-3292f7d4cf76.png)


### Checked and Approved:
1. the activity has been created and styled per design:

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713617-4f8269af-6a30-4bab-a65a-0593c4a4a67c.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713680-bc127e0a-90c0-43ff-8686-bf8c561eef49.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713688-a1f324da-65b3-426d-9a1d-bac4d4ef596f.png">
---|---|---|

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713708-c6282229-1ace-476a-a145-564a78055c97.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713720-abed07f6-339f-47cb-8bac-88307f190312.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713731-e819ce59-ed64-4501-9e39-00b059549c37.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713792-f7574ae7-8cd2-49fc-af92-01712d674cca.png">
---|---|---|---|

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713758-9c346808-22ff-45bc-a343-e92a1db7e67e.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713766-fc616910-79f4-4eb2-990d-595ee40ef7f0.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713774-d4728844-2d40-4134-988e-b8a46f8055e3.png">
---|---|---|

2. logic for date input and calendar has been created ^^

3. The title of the sub-activity is "Laboratory".
<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713629-77c4b7a7-1d67-4463-a9fd-cbee1e4aba77.png">

**Comment by isapisa** [comment]
> Screens in the application contain `:` that don't exist in the design. Is this okay? //the question is relevant to all Lab sub-activities

@anvmn is this to align with other modules or oversight? Not a big deal, in my opinion, just checking

**Comment by jeanette-pelizzon** [comment]
Based on feedback from the team, we are making changes to the HIV lab flow in ANC. We are adding in an additional question "Is this patient known to be HIV positive?" If yes, then the user will click save and it will update the progress report accordingly in the backend and they will move to the next test. If no, then the questions that we already have programmed will appear. I have updated the design in Figma [here. ](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=6668%3A47492) Quick clickthrough can be found [here](https://www.figma.com/proto/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=6272%3A42250&scaling=scale-down&page-id=5862%3A38746&starting-point-node-id=6668%3A47492&show-proto-sidebar=1).

Quick explainer video [here. ](https://www.loom.com/share/631854e111854ea2b246caf452b2084d)

// @anvmn @adamhstewart

**Comment by anvmn** [comment]
@jeanette-pelizzon

This issue has been completed, tested already.
At this stage, any changes require a separate issue.
