### ISSUE TITLE
Mac compatibility [6h]

### ISSUE THREAD

**Issue by AronNovak** [TIP-Global-Health/eheza-app#531]
The installation should be smooth on Mac.

Todo:
 - [x] Test-drive DDEV-based install on an Intel-based Mac, fixes if any issue comes up
 - [x] Test-drive DDEV-based install on an Apple Silicon-based Mac, fixes if any issue comes up

**Comment by AronNovak** [comment]
^^ @adamhstewart Can/shall we spend the time on this? We discussed with Nora, I can have an Intel-based Mac soon, and in the coming month, we can arrange Apple Silicon-powered device as well.

**Comment by AronNovak** [comment]
@adamhstewart Thanks to @nora-novak , I could accomplish point 1). On an Intel-based Mac, it works like a charm.
![20221129_134630](https://user-images.githubusercontent.com/114076/204550761-db3c3b29-56c9-4159-908e-dc8364f8f916.jpg)
![20221129_141748](https://user-images.githubusercontent.com/114076/204550770-1d9209d8-b5ec-4763-a383-33b2c0a616fd.jpg)
![20221129_141859](https://user-images.githubusercontent.com/114076/204550775-7b9f2259-d3c3-4dab-9d65-72f2b8ebf2a1.jpg)
![20221129_142449](https://user-images.githubusercontent.com/114076/204550780-39e94f2d-1c17-4892-beeb-56c98ccccecc.jpg)

**Comment by AronNovak** [comment]
The next round will be for a Apple silicon powered device.

**Comment by adamhstewart** [comment]
> The next round will be for a Apple silicon powered device.

Let me know if you need some help with that - I have an M2 that I can test with.

**Comment by adamhstewart** [comment]
@AronNovak I took the install (off the main branch) for a spin on an M2 Mac.

Important note: I did destroy the ddev containers (`ddev delete`) - I only updated my main branch re-copied both config files and ran `ddev restart` and then `ddev gulp`

### Backend installation

Mostly fine with the exception of this warning:

```
npm WARN prefer global node-gyp@3.8.0 should be installed with -g

> node-sass@4.13.1 install /var/www/html/client/node_modules/node-sass
> node scripts/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/client/node_modules/glob/glob.js:45:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm WARN gulp-jshint@2.1.0 requires a peer of jshint@2.x but none was installed.
npm WARN generated-elm@0.1.0 No repository field.
npm WARN generated-elm@0.1.0 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.13.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /mnt/ddev-global-cache/npm/eheza-app-web/_logs/2022-11-29T14_54_24_841Z-debug.log
```

### Frontend

That warning manifests itself as an error on install:

```
*[main][~/Workspace/eheza-app]$ ddev gulp
{ Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/client/node_modules/glob/glob.js:45:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3) code: 'MODULE_NOT_FOUND' }
Failed to run gulp : exit status 1
```

**Comment by AronNovak** [comment]
Possibly related GitHub issue:
https://github.com/nodejs/node/issues/3922#issuecomment-187876491

**Comment by AronNovak** [comment]
@adamhstewart Can you confirm what node version is active?
```
ddev ssh
node --version
```

It should be `v9.0.0`

Also do you think we could have a remote session using TeamViewer using that Mac mini, so I can debug this error? Otherwise it's very hard to proceed.

**Comment by adamhstewart** [comment]
@AronNovak 

```
*[main][~/Workspace/eheza-app]$ ddev ssh
adamhstewart@eheza-app-web:/var/www/html/server/www$ node --version
v8.0.0
```


From earlier in the `ddev restart` process:

```
Container ddev-router  Started 
Ensuring write permissions for eheza-app 
Existing settings.php file includes settings.ddev.php 
Ensuring write permissions for eheza-app 
v8.0.0 is already installed.
Now using node v8.0.0 (npm v5.0.0)
Now using node v8.0.0 (npm v5.0.0)
/mnt/ddev-global-cache/nvm_dir/eheza-app-web/versions/node/v8.0.0/bin/bower -> /mnt/ddev-global-cache/nvm_dir/eheza-app-web/versions/node/v8.0.0/lib/node_modules/bower/bin/bower
updated 1 package in 3.912s
```

looks like it's relying on a previously installed node version. Maybe destroying the containers will help.

**Comment by adamhstewart** [comment]
@AronNovak `ddev delete` didn't work as I still git node 8.0.0 - what did ultimately work (to get the proper node version) was to blow away the .ddev directory and start over. Yet still after this the same node error persists.

I'll reach out via private channels to schedule a teamviewer session.
