### ISSUE TITLE
NCDA - Food Group Question - Change [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#534]
## Issue 

There has been an update to the question that reads "Appropriate complementary feeding (6-24 months)?".

Changes: 
-  Equal to or Under 6 months old -> question should read "Breastfed baby for 6 months without interruption" 
- 7 months and over -> question should read ""Appropriate complementary feeding (6-24 months)?" 

Up until 6 months the scorecard will populate with dashes. If not too much other work, we should have this question appear once a child is 6 months old as that is when it become relevant.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> Up until 6 months the scorecard will populate with dashes. If not too much other work, we should have this question appear once a child is 6 months old as that is when it become relevant.

So, if we want to fulfill this, the requirements are:

-  Under 6 months old - no question
- 6 months old, untill 7 months old -> question should read "Breastfed baby for 6 months without interruption"
- 7 months and over -> question should read ""Appropriate complementary feeding (6-24 months)?"

Correct?

**Comment by jeanette-pelizzon** [comment]
Yes. Based on our conversation today, we are going to do it this way. We will get feedback from the team in QA if this needs to be different as it wasn't specified other than this way.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Question displays correctly

Above 7 month|Between 6-7 months|Under 6 month
-|-|-
![image](https://user-images.githubusercontent.com/3536805/207039360-a89bab6a-6946-4ab8-b89b-9a2f8804c296.png)|![image](https://user-images.githubusercontent.com/3536805/207342461-0dcddb8e-bba6-4ea1-8ef4-3ed147b03781.png)|![image](https://user-images.githubusercontent.com/3536805/207082115-7ed6f654-e849-41c0-ad47-be962430ffcc.png)
