### ISSUE TITLE
[META] NCD - Subs Visit 

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#538]
## Issue 
The subsequent visit for NCD is comprised of largely the same activities as the first encounter. The following activities are being carried over in the same order and with no changes: 
- Danger Signs 
- Symptom Review 
- Physical Exam
- Family Planning 
- Next Steps

Changes will be happening to:
- Medical History - which is switching to only outside care (see specific issue)
- Labs - not all labs will be run every visit ( see #535) 

## To Do: 
- Create subsequent visit infrastructure 
- Pull over the activities that are not changing

**Comment by anvmn** [comment]
There was no real need for this issue, as vast majority of infrastructure was in place alredy.
Making this a META issue.
