### ISSUE TITLE
NCD - Subs Visit - Outside Care [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#539]
## Issue 
In the first encounter, we have an activity called "Medical History" with a sub-activity called "Outside Care." In the subsequent encounter, we are getting rid of all but one of the Medical History sub-activities. Even though there are other places in the app that we keep one sub-activity in the drawer, it has been requested that we get rid of the Medical History activity and bump up the Outside Care sub-activity to be a full activity. Outside care is replacing Medical History in the main activity tray and will appear in the same position. 

Nothing within the activity is changing. 

This is what the main activity screen will look like:

![Main Activity Tray 12](https://user-images.githubusercontent.com/77505464/200433270-7be15e14-8cd5-4f07-ab4b-503704733aa0.jpg)

This is what the activity will look like:

![Subs Vis](https://user-images.githubusercontent.com/77505464/200435575-e3fa73b8-ac8c-4606-9f8f-3d9cbc91891b.jpg)

## Issue 
- Create Outside Care main activity

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env.

### Questions/Found Issues:
1. Did I understand correctly that the Outside Care sub-activity should become the main activity only in subsequent encounters?
The following confused me:

<img width="283" alt="NCD_-_Subs_Visit_-_Outside_Care__6h__·_Issue__539_·_TIP-Global-Health_eheza-app" src="https://user-images.githubusercontent.com/35059802/210831239-979ca89d-3096-4014-bf7d-50da98a5aaea.png">

2. According to the example in the description: 1. should be "If yes, what?" 2. should be "None of these"

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210835130-ba81c4c7-10ef-40e8-b314-0234f057dbde.png">

3. According to the example in the description, the last question is "Were you given medicine?" shouldn't be conditional. But in the application it's conditional. The question only appears if at least one of the diagnoses from the first image is selected and doesn't appear if the diagnoses from the second image (or "Other") are selected:

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210837182-231270c0-330e-4842-a11d-baa80a93e284.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210837330-3ec53c9c-f306-485e-994a-a0beecb76727.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210837456-73fca8d6-8c3c-4734-aa1d-7453a989e728.png">
---|---|---

### Checked and Approved:
1. The Medical History activity (and sub-activity) doesn't appear in the subsequent encounters.
2. The Outside Care is the main activity in the subsequent encounters. 

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210832415-55ca77d7-753f-44c2-b8b3-b06bda50bec7.png">

5. The Outside Care activity looks as expected except the points in the Questions/Found Issues section:

- the second conditional question:

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210833187-4c99e474-ad36-4618-9782-fea129799754.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210833258-a9215a7f-6bd7-4b78-8c29-535a980b718b.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210833324-aa9cbc51-6e22-4594-89e2-2905370ac358.png">
---|---|---

- the third conditional question:

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210833872-1e450231-0726-4ccf-bcbd-0167b02e9406.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210834000-318fe0cf-4b41-4122-ab70-dc436f0838ca.png">
---|---

- the last question:

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210834211-0a9ce208-222c-4206-a04c-c877bc653bff.png">

**Comment by anvmn** [comment]
@LudmilaGoichman 

The designs are not 100% accurate. For context, we follow here same design and logic we got at ANC Outside care activity.

1 =>  Yes, only in subsequent encounter.
2 => Per ANC activity.
3 => Same logic as at ANC activity - some dignoses can be treated with medication. Others can not. There's no point in asking if medication was given, if diagnosis is not rtreated with medication.
So, question will show up only if there's at least one diagnosis that can be medicated.
