### ISSUE TITLE
ANC @ Health Center - Labs - Malaria [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#54]
## Issue

The Malaria RDT (Rapid Test) is performed at every ANC visit. There are 4 inputs needed on the screen.

Were you able to perform this test? If yes, you then move on to validate if it was done today. If no, you select from a series of checkboxes why not. Check box options shown here: | If yes, then the question "Did you perform this test today?" appears. If yes, today's date auto-populates in the Test Date section. If no, then a date input appears and is shown here:
--|--
<img width="465" alt="Screen Shot 2021-11-03 at 12 02 35 PM" src="https://user-images.githubusercontent.com/77505464/140177506-b60f0e8a-75d2-4557-9be1-bed8476abba1.png"> | <img width="499" alt="Screen Shot 2021-11-03 at 12 04 39 PM" src="https://user-images.githubusercontent.com/77505464/140177531-5e117b54-21e7-4393-a1c7-0f2ee873b5a4.png">

Since this is a Rapid Test, results will be ready immediately. Nurse will then select the result:
- Positive
- Negative
- Indeterminate

_Note: we do not have the information on what happens as the next steps based on these results yet. We will build that out at a later time._

### Design
Please refer to [ANC Labs - Full Prototype](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) in Figma for proper flow.

**Screen One** | **Screen Two** | ** Screen Three** | **Screen Four** | **Screen Five**
--|--|--|--|--
<img width="257" alt="Screen Shot 2021-11-03 at 3 13 14 PM" src="https://user-images.githubusercontent.com/77505464/140177269-e492bae9-5b50-4dc8-826e-59bce4b961db.png"> | <img width="261" alt="Screen Shot 2021-11-03 at 3 13 21 PM" src="https://user-images.githubusercontent.com/77505464/140177313-eae0e464-c708-4f3e-8903-f6a75eda26fb.png"> | <img width="258" alt="Screen Shot 2021-11-03 at 3 13 26 PM" src="https://user-images.githubusercontent.com/77505464/140177346-d7956ab1-30cf-4c9e-94d9-9b19f0fdb949.png"> | <img width="257" alt="Screen Shot 2021-11-03 at 3 13 32 PM" src="https://user-images.githubusercontent.com/77505464/140177375-073885a7-fb2b-4b66-b742-cd51cb02e375.png"> | <img width="257" alt="Screen Shot 2021-11-03 at 3 13 37 PM" src="https://user-images.githubusercontent.com/77505464/140177398-0fb103e1-7516-4dfe-9efa-024b3e8bd3db.png">

## To Do

- Create activity
- Logic for date input and questions
- Style per design

**Comment by LudmilaGoichman** [comment]
@anvmn @isapisa 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet


### Checked and Approved:
1. the activity has been created and styled per design:

<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714602-ac5000bd-86e9-4579-a4d5-22b2e4b62178.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714633-5d2e1ae6-30a1-47ed-a84c-4145c03bf0e0.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714645-2ec890b0-2ad2-4d23-a120-8e848e21590b.png">
---|---|---|

<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714664-15ffc1b8-c3f1-4948-a192-be5acf4afd92.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714682-ea6625cc-1ebb-4ad9-b1b2-c308e0b57695.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714700-7cdf5c85-83d7-426d-9685-083f9bfbc96f.png">
---|---|---|

<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714731-1fb3b579-e124-486a-83c4-35a727caa22f.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714742-293adfc3-6ac1-4fa9-9a37-e0e07ccc0d8f.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714763-aff31d60-f921-4cf5-88e9-f84da260f2e2.png">
---|---|---|

2. logic for date input and calendar has been created ^^

3. The title of the sub-activity is "Laboratory".

<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714615-4f6aea7b-cbfe-43f8-81f4-8a65953f2261.png">
