### ISSUE TITLE
Newborn Exam - Changes to History Activity [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#542]
## Issue 

We are making changes to the Newborn Exam as some issues were brought to light while working on NCDA. 

We are making a few changes: 

(1) We are adding: 
- Birth weight 
- birth length (has conditional follow up questions)
- apgars (has conditional follow up questions)
- birth defect (has conditional follow up questions)

(2)The activity name is changing to "Birth History" from "History"

Here is the updated design: 

![Birth](https://user-images.githubusercontent.com/77505464/202285027-54d7a903-6c3e-486c-b04e-4d7f502af370.jpg)

## To Do: 
- design screen per design 
- update title of the activity

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> birth defect (has conditional follow up questions)

I don't see any conditional questions on the design.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> We are making changes to the Newborn Exam as some issues were brought to light while working on NCDA.

I see this issue got NCDA label, but I don't see any requirement for pulling data from this (changed) activity to be used for NCDA logic.
Am I missing something?

**Comment by jeanette-pelizzon** [comment]
> @jeanette-pelizzon
> 
> > birth defect (has conditional follow up questions)
> 
> I don't see any conditional questions on the design.

Sorry was waiting for information from the medical team. Updated design and the main issue.

**Comment by jeanette-pelizzon** [comment]
> I see this issue got NCDA label, but I don't see any requirement for pulling data from this (changed) activity to be used for NCDA logic.
> Am I missing something?

If a child is under 2500 grams then they are underweight and that will be referenced on NCDA scorecard. See #543

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> > I see this issue got NCDA label, but I don't see any requirement for pulling data from this (changed) activity to be used for NCDA logic.
> > Am I missing something?
> 
> If a child is under 2500 grams then they are underweight and that will be referenced on NCDA scorecard. See #543.

Per #545, we have that input at NCDA questionnaire, when it asked once.
So, why do we need to referrence the oinput from Newborn exam?

**Comment by jeanette-pelizzon** [comment]
You're correct, right now we do not need to reference it from the newborn exam. Sorry, this was discussed in a meeting but we are holding off on pulling from the newborn exam since that's only done at the CHW level now and not all districts use CHWs with eheza or something like that. So for now we will keep it on the questionnaire with the numerical input and pull the data for the NCDA questionnaire from there. Sorry for the confusion!

**Comment by jeanette-pelizzon** [comment]
Okay sorry, I double checked with @adamhstewart and we DO need to pull the information from the newborn exam. So if the information is filled out in the newborn exam - NCDA will know that and automatically pull it. If the information does not exist in the newborn exam, then we need to ask the question on the questionnaire.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Ok, I see. This will require additional effort.
There's another question that we ask at Newborn Exam - about birth defects.
I suppose it should it behave the same way?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Similar to all other inputs, shouldn't we ask if birth weight is available, before asking what it was?

**Comment by jeanette-pelizzon** [comment]
> There's another question that we ask at Newborn Exam - about birth defects.
> I suppose it should it behave the same way?

@anvmn yes they should both behave the same way. Again, sorry for the confusion!

**Comment by jeanette-pelizzon** [comment]
> Similar to all other inputs, shouldn't we ask if birth weight is available, before asking what it was?

It seems that mothers are given a yellow card that has all the birth information about their baby so they will be able to provide birth weight to the healthcare worker. @anvmn

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> > Similar to all other inputs, shouldn't we ask if birth weight is available, before asking what it was?
> 
> It seems that mothers are given a yellow card that has all the birth information about their baby so they will be able to provide birth weight to the healthcare worker. @anvmn

What if mother does not have that card for some reason?
Asking, because we need this info for NCDA, and if incorrect value is entered, it will show on the scoreboard.

**Comment by jeanette-pelizzon** [comment]
It is my understanding that the yellow cards are VERY important and what is used currently to track everything about their childs health so I think it would be very, very rare that they don't have one but differing to @adamhstewart here. I think we can assume that 99% of them will have the card.

**Comment by balagan73** [comment]
### QA Review

### Found issues and questions:

1. Not related to this issue, but when registering new patient some dropdown list is so long, that doesn't fit on the screen, and I couldn't even use the scrollbar to go further down.
![image](https://user-images.githubusercontent.com/3536805/207321399-8853123b-707d-428f-855f-fd11fa777c86.png)


### Checked and approved:

1. History is changed to Birth history
![image](https://user-images.githubusercontent.com/3536805/207321081-0d7a95b2-786d-4855-a634-5ef4ecc076ad.png)

2. Apgar conditional questions display if Yes is answered.
![image](https://user-images.githubusercontent.com/3536805/207321995-317875b6-2a2c-4b0b-82a1-74154d4eb5d5.png)

3. Birth length conditional question displays if Yes is answered.
![image](https://user-images.githubusercontent.com/3536805/207322103-7dda2537-0336-425e-a935-bc39bf66aab2.png)

4. Birth weight and birth defect questions are displayed.
![image](https://user-images.githubusercontent.com/3536805/207322365-d119b955-c0aa-4a93-901d-03b08a3cea3f.png)

**Comment by jeanette-pelizzon** [comment]
1. I believe this is how this has always functioned. Maybe just a random error. adding @anvmn for clarification.

**Comment by anvmn** [comment]
@jeanette-pelizzon
Real case scenario is usage of tablet, where selector is different.
So, this is non issue.
