### ISSUE TITLE
NCDA - Changes to Questionnaire Layout [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#544]
## Issue 

Complete issue #545 first. 

It has been requested that we change the way the questionnaire is laid out. 

The questionnaire will now be split into three "pages". 

Page 1 | Page 2 | Page 3
--|--|--
![1 1](https://user-images.githubusercontent.com/77505464/202286375-4049ff4e-06b4-44dd-990f-d2cc38192dc1.jpg) | ![1 1-1](https://user-images.githubusercontent.com/77505464/201778730-7a1dbce3-1ec0-4c40-b4f4-48f1fd688c06.jpg) | ![1 1-2](https://user-images.githubusercontent.com/77505464/201778734-4cded43f-c4d9-4f2e-8142-71171d806cc3.jpg)

#3 To Do: 
- Break questionnaire into pages as shown in the design.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Checked and approved:

1. Questions are split to 3 pages as requested.

Page 1|Page 2|Page 3
-|-|-
![image](https://user-images.githubusercontent.com/3536805/207030115-e27d3366-f367-40a7-9f54-58eabdbf7c6e.png)|![image](https://user-images.githubusercontent.com/3536805/207030510-8e17d5b7-56d9-4cb9-a404-fd4c1e7c1f13.png)|![image](https://user-images.githubusercontent.com/3536805/207030723-c487f643-162f-403e-a5ed-d7c7fa0f2252.png)
