### ISSUE TITLE
NCDA - Adding Questions to Questionnaire [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#545]
## Issue 

We are adding the following questions to the questionnaire. 

- **Did the mother receive regular prenatal and post-partum visits?** -> this question only needs to be answered once. Once answered it can disappear. It should continue to appear until answered. 

- **Did the mother receive iron supplements during pregnancy?** -> this question only needs to be answered once. Once answered it can disappear. It should continue to appear until answered. 

- **Did the mother receive insecticide-treated bednets during pregnancy?** -> this question only needs to be answered once. Once answered it can disappear. It should continue to appear until answered. 
- **What was the childs birthweight?** -> this question only needs to be answered once. Once answered it can disappear. It should continue to appear until answered. The answer here should be a numerical input. Anything BELOW 2500 grams is underweight and the RED notification should appear next to it. see #543 

- **Was the child born with a birth defect?** -> this question only needs to be answered once. Once answered it can disappear. It should continue to appear until answered. 

## To Do: 
- Add new questions to the questionnaire

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Weren't there also questions that were supposed to be removed from questionnaire?

**Comment by jeanette-pelizzon** [comment]
No, I don't believe so.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> No, I don't believe so.

What about this one?

![Selection_1289](https://user-images.githubusercontent.com/17882245/202285343-39722157-70bf-4934-812a-792d75a388b0.png)

**Comment by jeanette-pelizzon** [comment]
It's not being removed. It's being changed to a numerical input. I was going to make a separate issue for that - can I include it here?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Well, this is a Yes/No question that needs to be deleted, and numerical input is added.
I think #543 is an issue for new numerical input for NCDA.
For Newborn Exam, we have it described at #542.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions

1. I think an apostrophe is missing here after child, so it should be child's, or sentence should be rephrased to ... birthweight of the child.
![image](https://user-images.githubusercontent.com/3536805/207028456-ddb69736-950d-41e1-bd71-7bab1c28458e.png)

### Checked and approved:

1. Questions appear as requested.
![image](https://user-images.githubusercontent.com/3536805/207028702-015610f3-4b00-48aa-87f5-b5a78af1642f.png)

2. The birthweight of the child is correctly marked with red if it is under 2500 grams.

Under 2500 grams|From 2500 grams
-|-
![image](https://user-images.githubusercontent.com/3536805/207028995-a83b220b-5f7f-482f-862f-3d60b2fd58dd.png)|![image](https://user-images.githubusercontent.com/3536805/207029069-eb729325-b262-45bd-9062-731057263357.png)

**Comment by jeanette-pelizzon** [comment]
Okay, @Diama1 can you update with the apostrophe suggestion made above please?

**Comment by Diama1** [comment]
> Okay, @Diama1 can you update with the apostrophe suggestion made above please?

I combined the correction with the translations.
