### ISSUE TITLE
Labs - Random Blood Sugar - Changes to Flow [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#547]
## Issue 

A request has been made to change the way the Random Blood Sugar lab functions across E-Heza. It was recently discovered that the Random Blood Sugar test is done at the point of care at some health centers and at the lab at other health centers (or it is sent to the lab if the nurses are very busy). 

To accommodate for this, we have had to change the flow of the Random Blood Sugar Lab. 

(1) We have added in a second question that asks "Where was this test performed?" with the point of care or lab as the options. 
<img width="286" alt="Screen Shot 2022-11-14 at 4 40 54 PM" src="https://user-images.githubusercontent.com/77505464/201798061-969254ed-fade-4574-932e-d1ff63fd8312.png">

(2) If done at the lab, nothing changes about the flow for this lab. Results will be input in the second half of the encounter as they normally are. 

(3) If done at point of care, a results input will populate at the bottom of the screen and the result will be logged immediately. This is the same way the HIV and Malaria RDTs work.  Here is how that screen will look: 
<img width="286" alt="Screen Shot 2022-11-14 at 4 40 30 PM" src="https://user-images.githubusercontent.com/77505464/201798013-68603ba9-ec56-4072-8b91-471fe22de67e.png">

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- Nutrition env.

### Questions:
1. The second question only appears when the answer to the first question is "yes". Is this okay?

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210384053-c309f811-8d02-48de-92b7-3b53999c65af.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210384567-f74e86f4-0455-4b78-a4a5-6aea4fedff78.png">
---|---

2. The question has been changed from "Where **was** this test performed?" (see in the description) to "Where **is** this test performed?" Is this okay?

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210384974-72a6c265-f4e7-4433-93c4-a59e332dfea7.png">

3. In the example in the description, the marked text in the following image looks like bold, but not in the application. Is this okay?

| from description | from application |
---|---
<img width="323" alt="201798013-68603ba9-ec56-4072-8b91-471fe22de67e_png__572×1228_" src="https://user-images.githubusercontent.com/35059802/210387123-a88b6425-ceb4-4d81-ae60-06bc06710632.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210386999-dec8f8a3-d8fa-4240-8265-add9ee71eb60.png">


### Checked and Approved:
1.  The second question that asks "Where was this test performed?" with the point of care or lab as the options has been added. But it only appears when the answer to the first question is "yes"

First question | Answer "no" | Answer "yes" |
---|---|---
<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210384053-c309f811-8d02-48de-92b7-3b53999c65af.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210384128-d52b5881-6877-4a13-af59-968c55145e1f.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210384264-761016ae-ebb2-4748-b1b4-32f731940564.png">

2. If done at the lab, nothing changes about the flow for this lab. Results will be input in the second half of the encounter.

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210385488-2f5ead52-515e-49a4-8b0d-9a50870ee203.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210385580-56602118-a711-4590-a4e2-54aed537f202.png">
---|---

3. If done at point of care, a results input will populate at the bottom of the screen and the result will be logged immediately. 

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210385870-3b6031b7-d245-4248-9357-fb3f47dab3b0.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210385970-0c4adc7d-d7fe-4437-9a3f-ea8f75dbe33c.png">
---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1, The second question only appears when the answer to the first question is "yes". Is this okay?

Yes, it's ok, because if test was not run, there's no point in asking where it was not run.

> 2. The question has been changed from "Where was this test performed?" (see in the description) to "Where is this test performed?" Is this okay?

Not, it should be `was`.

> 3. In the example in the description, the marked text in the following image looks like bold, but not in the application. Is this okay?

Yes, ok, because we got common styling for all forms.

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon 

- nutrition env

### Checked and Approved:
1. The question "Where was this test performed?" has been fixed:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211203313-9ea9011a-0d86-461b-81eb-5dd5cfbad0ab.png">
