### ISSUE TITLE
ANC @ Health Center - Labs - Syphilis - RPR [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#55]
## Issue 

The lab for Syphilis-RPR is run on the first ANC Antenatal visit and at 38 weeks EGA. There are three inputs. There is NO results input for this test. 

Were you able to perform this test? If yes, you then move on to validate if it was done today. If no, you select from a series of checkboxes why not. Check box options shown here | If yes, then the question "Did you perform this test today?" appears. If yes, today's date auto-populates in the Test Date section. If no, then a date input appears and the results input will populate directly on this screen. The date input is shown:
--|--
<img width="465" alt="Screen Shot 2021-11-03 at 12 02 35 PM" src="https://user-images.githubusercontent.com/77505464/140181062-cce4667b-f82a-4cec-b767-a0599a4f9fee.png"> | <img width="499" alt="Screen Shot 2021-11-03 at 12 04 39 PM" src="https://user-images.githubusercontent.com/77505464/140181310-9e02e952-1606-4587-9504-5e55d658a69c.png">

### Design

Please refer to [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5394%3A34119) in Figma for design. 

**Screen One** | **Screen Two** | **Screen Three**
--|--|--
<img width="217" alt="Screen Shot 2021-11-03 at 3 48 26 PM" src="https://user-images.githubusercontent.com/77505464/140182203-b6424410-0bec-4a78-9555-f269e8c99d11.png">  | <img width="233" alt="Screen Shot 2021-11-03 at 3 48 30 PM" src="https://user-images.githubusercontent.com/77505464/140182231-62dbf428-4c72-40fa-914a-22607d24bfaf.png"> | <img width="219" alt="Screen Shot 2021-11-03 at 3 48 36 PM" src="https://user-images.githubusercontent.com/77505464/140182256-983d0b61-4e44-49ba-81ae-cac89607b178.png">

### Note 
Syphilis - RPR results are sent to the lab and results are given later that same day. Results input is on a separate screen and flow. You can see the issue for the Syphilis-RPR results screen [here](https://github.com/Gizra/ihangane/issues/2826). 

### To Do

- Create activity
- Logic for questions and date/calendar entry
- Style per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

For some reason, icon got a hidden part that affects the height, and as a result, position on screen:

![Selection_380](https://user-images.githubusercontent.com/17882245/144236662-60cca5c7-68b8-48d9-bec2-a6568da9013d.png)

Can you please fix this?

**Comment by jeanette-pelizzon** [comment]
Fixed

**Comment by LudmilaGoichman** [comment]
@anvmn @isapisa 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet

### Checked and Approved:
1. the activity has been created and styled per design:

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713309-1922aace-fecc-408d-b62f-43cbbcffe266.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713335-bd807618-8e2d-48f9-b873-9c8b212e031f.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713356-5482d846-2089-4258-aa7a-831deacd3d2e.png">
---|---|---|

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713371-930ceee1-c179-4eec-922a-52f49deae25f.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713392-97ec433b-8df3-4af4-8065-162861f803fd.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713402-f227459b-6c11-419d-8e3d-4982555a7076.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713409-039101d4-3388-431e-aa70-38b41771ce55.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713415-93ddf482-8b01-44cc-80bb-76ef7068083e.png">
---|---|---|---|---

2. logic for questions and date/calendar entry has been created ^^

3. The title of the sub-activity is "Laboratory".
<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713317-160399eb-3e04-418e-88a0-0bd5d6e31229.png">
