### ISSUE TITLE
NCD- Progress Report - HBA1c Graph [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#551]
## Issue

There was a request to add a graph to the NCD progress report to track HBA1c results over time. This will go below the graphs that are already existing in the NCD lab section. 

Here is a close-up of the graph: 

<img width="601" alt="Screen Shot 2022-11-16 at 12 35 01 PM" src="https://user-images.githubusercontent.com/77505464/202289777-493f0258-812e-4c49-a9d8-3085d15b0a34.png">

Here is what the whole screen will look like: 
![NCD Progress Report](https://user-images.githubusercontent.com/77505464/202289869-5f39948a-5d9e-45e3-964b-7bdf13fbf0cc.jpg)

**Comment by LudmilaGoichman** [comment]
@jeanette-pelizzon @anvmn 
I tested it in https://github.com/TIP-Global-Health/eheza-app/issues/546. Point 3 under "Checked and Approved"
