### ISSUE TITLE
ANC @ Health Center - Labs - Syphilis-RPR Results [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#56]
## Issue

Related: https://github.com/Gizra/ihangane/issues/2825

### Overview 
During an ANC encounter, a patient sees a nurse who collects the appropriate samples for each test and then sends them to the lab (unless it is a rapid test). The samples are then processed by the lab and results are returned later that day. The patient will return to see the nurse after several hours and receive the results of the labs. Nurses will navigate from their Case Management screen to each patient awaiting lab results. The sub-activities will be all the tests that have been run but they do not yet have results for. The nurse will select the test she has results for and input them. She will do this for all tests she has results for. When she hits save that result will appear in the Progress Report for that patient. 

**Syphilis - RPR Specific** 

The possible results of a Syphilis - RPR test are: 
- Negative 
- Positive 
- Indeterminate 

**Screen One** | **Screen Two** | **Screen Three**
--|--|--
<img width="285" alt="Screen Shot 2021-11-03 at 3 58 42 PM" src="https://user-images.githubusercontent.com/77505464/140183697-e442b3d2-15de-4ea9-bac3-3d33ea018813.png"> | <img width="283" alt="Screen Shot 2021-11-03 at 3 58 47 PM" src="https://user-images.githubusercontent.com/77505464/140183732-0835f60b-28aa-4c19-8770-63c1e52ca2f1.png"> | <img width="283" alt="Screen Shot 2021-11-03 at 3 58 56 PM" src="https://user-images.githubusercontent.com/77505464/140183774-82298524-ce6d-4234-9a57-6bdd432942cf.png">

### Design
https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A43429

### To Do

- Create activity (`Syphilis Results`?)
- Style per design

**Comment by anvmn** [comment]
@LudmilaGoichman
Please test on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@isapisa @anvmn 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet

### Question:
The activity is called "Laboratory". Maybe it should be called "Laboratory Results"?

### Checked and Approved
1. sub-activity has been created

The flow:

the first encounter | case management | new sub-activity | possible results | the result field is mandatory | report |
---|---|---|---|---|---
<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148062901-ef0d0022-ddf0-4748-9b04-8285af85af83.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148063038-a2dc59b9-85e2-4161-bd0d-104678402ee5.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148063147-03b30222-f1f0-455a-81c7-a22fa0eb6af4.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148063229-72b5d56b-475a-458f-bd14-5a69880b2d8f.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148063318-bb87f27b-4193-44f4-9127-1bbd68f5e705.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148063523-76273199-3362-4798-9323-abbaa963cfd6.png">

**Comment by isapisa** [comment]
@LudmilaGoichman `Laboratory` is fine
