### ISSUE TITLE
NCD Progress report - Lipid Panel lab [6h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#565]
## Tasks:
1. The results can be entered in 2 different units of measurement (mmol/L or mg/dL).
For convinient data analysis, we want to store the results only at mg/dL.
Therefore, if results are entered in mmol/L, we convert using following formulas:

Total Cholesterol, HDL cholesterol and LDL cholesterol:
`1 mmol/L =  38.67 mg/dL`

Triglycerides:
`1 mmol/L =  88.57 mg/dL`

2. Presentation on progress report:

We use md/dL as unit of presentation. 
Normal ranges:

![Selection_1407](https://user-images.githubusercontent.com/17882245/207547945-c0a97732-8b4e-470e-b6f4-c7b128726720.png)

Lpid panel comes up with results as abnormal/normal as an overview. These should show up abnormal if any of the individual subtests are abnormal which would then tell the nurse to click through to view the results. 

<img width="442" alt="Screen Shot 2022-12-12 at 10 46 44 AM" src="https://user-images.githubusercontent.com/77505464/207129132-b42bb79b-4b76-4865-8525-a33c649db339.png">

Once they click into results this is what it will look like: 
<img width="399" alt="Screen Shot 2022-12-12 at 10 51 02 AM" src="https://user-images.githubusercontent.com/77505464/207129621-143d65bb-c23e-4b77-9b91-1482b66dfc83.png">

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env.

### Found Issues/Questions:
1. The calculations aren't correct for Total Cholesterol, HDL cholesterol and LDL cholesterol.
 Examples:

>Total Cholesterol, HDL cholesterol and LDL cholesterol:
>1 mmol/L =  38.67 mg/dL

TC   = 8 mmol/L =  8 * 38.67 mg/dL = 309.36 mg/dL
LDL = 3 mmol/L =  3 * 38.67 mg/dL = 116.01 mg/dL
HDL = 1 mmol/L =  38.67 mg/dL 

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210788476-065535fb-c797-4fbb-82c3-3e69e7de6266.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210804331-924d4e61-1f9e-4457-8987-3ce6a29e7ad9.png">
---|---|

Then I entered 1 into all fields, and the results are:

<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210804581-1be9ca54-7ea9-434e-87c1-eb15341d13a9.png">|<img width="362" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210804780-28da54f3-524d-4808-96da-64adf47a3c17.png">
---|---|

3. Values in mmol/L aren't displayed in the report, as shown in the last screen in the description. Neither in the first encounter nor in the subsequent encounter. But maybe it shouldn't show up in the report? Examples:

- First encounter

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210787506-5c9c18ad-e0d7-4238-a460-1969240eeb01.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210788731-e7e30fdf-6ae9-404f-aa51-0c8c351b3a08.png">
---|---

- Subsequent encounter (not all screens, just examples):

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210792073-b24a17c6-5b1a-4964-8001-25bd9d97c018.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210793192-425f6632-ed07-40cf-bccd-0b8f2eb6428e.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210793806-ec131738-01cb-47ad-9f01-1f91f628493e.png">
---|---|---

### Checked and Approved:
1. Lpid panel comes up with results as abnormal/normal as an overview. 
2. Individual subtest results are shown after clicking on the main line of the test

First encounter:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210788476-065535fb-c797-4fbb-82c3-3e69e7de6266.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210788559-47e0bbd7-6315-4fe6-bee6-3c9d406d865d.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210788656-4b8f0647-04c6-41b1-952f-a567c9abecc0.png">
---|---|---

Subsequent (after the year) encounter:

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210792115-ea10cd22-19a6-4a60-8abf-e96412dcf9bb.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210792844-cdafeb2e-dec3-4492-87b6-cd751b194e97.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210793079-adde8bf1-3391-48b4-a03e-4cb735f9e2a6.png">
---|---|---

<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210793391-8579aa0b-34ee-4dfb-a787-c3a096542cb4.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210793483-fcdd5d0d-2d86-48b1-befc-9ce5c9b35ea6.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210793573-accc214b-6c5f-4ef3-ba27-3846a01cc118.png">|<img width="364" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/210793669-c11e6f94-5772-42c4-b92b-138b3afefb84.png">
---|---|---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

> 1. The calculations aren't correct for Total Cholesterol, HDL cholesterol and LDL cholesterol.

Indeed wrong conversion ration was set. Fixed at #581.

> 3. Values in mmol/L aren't displayed in the report, as shown in the last screen in the description. Neither in the first encounter nor in the subsequent encounter. But maybe it shouldn't show up in the report? 

The decision was to convert mmol/L into mg/dL , so only mg/dL is displayed in the report.

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env

### Checked and Approved:
1. The calculations are correct for Total Cholesterol, HDL cholesterol and LDL cholesterol.

>Total Cholesterol, HDL cholesterol and LDL cholesterol:
>1 mmol/L =  38.67 mg/dL

TC   = 0.5 mmol/L =  0.5 * 38.67 mg/dL = 19.335 mg/dL
LDL = 1.5 mmol/L =  1.5 * 38.67 mg/dL = 58,005 mg/dL
HDL = 2.99 mmol/L =  2.99 * 38.67 mg/dL = 115,6233 mg/dL

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211200174-95deaf29-3145-48fd-bd99-26522be0fcc6.png"><img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211200197-08c35213-5180-40b3-b3f1-d7b84c0c25dc.png">
---|---

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211200137-08542fd4-6947-4756-acd3-5da6ba9998db.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211200153-ce2d5c17-fb09-4dcf-918a-77140db06baf.png">
---|---
