### ISSUE TITLE
ANC @ Health Center - Labs - Hepatitis B [5h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#57]
## Issue

The lab for Hepatitis B is run on the first ANC Antenatal visit and at 34 weeks EGA. There are three inputs. There is NO results input for this test in this flow. See note below.

Were you able to perform this test? If yes, you then move on to validate if it was done today. If no, you select from a series of checkboxes why not. Check box options shown here | If yes, then the question "Did you perform this test today?" appears. If yes, today's date auto-populates in the Test Date section. If no, then a date input appears and the results input will populate directly on this screen (shown in the flow below).
--|--
<img width="465" alt="*No checkboxes" src="https://user-images.githubusercontent.com/77505464/140184604-4df19232-544e-4a07-b67e-2c006b3d20f1.png"> | <img width="499" alt="*Date Input" src="https://user-images.githubusercontent.com/77505464/140184626-c836b093-ad25-421e-a51c-25e85a022435.png">

### Design

https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=6006%3A49826

<img width="432" alt="Screenshot 2021-11-26 at 10 08 01" src="https://user-images.githubusercontent.com/34378755/143555759-51fe23c0-52ab-460d-b03e-36ac29c44a67.png">

### Note 

Hepatitis B results are sent to the lab and results are given later that same day. Results input is on a separate screen and flow. You can see the issue for the Hepatitis B Results screen [here](https://github.com/Gizra/ihangane/issues/2828). 

## To Do

- Create activity incl. logic for questions/calendar input
- Style per design

**Comment by LudmilaGoichman** [comment]
@anvmn @isapisa 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet

### Checked and Approved:
1. the activity has been created and styled per design:

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145712952-2fa52c0a-f38b-4d8e-b49b-97b192771f23.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145712979-d7f31116-77e1-404b-b33f-be7336872a78.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145712991-9ec884c3-bcae-44d7-943a-7236d59885b8.png">
---|---|---|

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713004-b388664d-fd16-4c65-986e-afbace8be4c2.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713019-fb52ddf0-49de-4cd5-89d4-ddedccf1e08c.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713033-13b3a807-2f6e-46f9-95f5-09ca6a046e40.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713054-8a57028a-0334-45b8-847f-8fedb9d318c7.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145713084-d4dccf8f-2253-4015-9bdd-e224ffedfa26.png">
---|---|---|---|---

2. logic for questions and date/calendar entry has been created ^^

3.  The title of the sub-activity is "Laboratory".
<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145712961-2d483704-c6c3-47af-9ae3-6a1cc262cae9.png">

**Comment by jeanette-pelizzon** [comment]
Based on feedback from the team, we are making changes to the HIV lab flow in ANC. We are adding in an additional question "Is this patient known to be HIV positive?" If yes, then the user will click save and it will update the progress report accordingly in the backend and they will move to the next test. If no, then the questions that we already have programmed will appear. I have updated the design in Figma [here](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=6675%3A47924). Quick clickthrough can be found [here.](https://www.figma.com/proto/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A42717&scaling=scale-down&page-id=5862%3A38746&starting-point-node-id=5862%3A42660&show-proto-sidebar=1)

Quick explainer video [here](https://www.loom.com/share/840e8ae0305e44619e275ecb36794f5e).

// @anvmn @adamhstewart

**Comment by anvmn** [comment]
@jeanette-pelizzon

This issue has been completed, tested already.
At this stage, any changes require a separate issue.
