### ISSUE TITLE
Rename NCDA Scorecard to ECD Child Scorecard

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#570]
## Issue

The stakeholders in the NCDA program requested the name of activity and report title be change to ECD Child Scorecard

### Report Title
<img width="746" alt="E-Heza_System" src="https://user-images.githubusercontent.com/688507/208722663-dc6a13cc-2247-4cdd-8f3e-053ebe2bd35c.png">

### Activity
<img width="1067" alt="E-Heza_System" src="https://user-images.githubusercontent.com/688507/208723161-247c55f2-ed7f-43a6-a62c-f22c180bd17b.png">

## Tasks
- Change the name in all locations

## Note
- @Diama1 You had given instruction to change the name to ECD Child Scorecard, but since the C in ECD stands for Child, should it simply by ECD Scorecard?
- @anvmn please advise which branch to make this on so it can be easily and quickly deployed to the nutrition environment.

**Comment by anvmn** [comment]
@adamhstewart 

>  please advise which branch to make this on so it can be easily and quickly deployed to the nutrition environment.

`feature-ncda`

**Comment by Diama1** [comment]
> * @Diama1 You had given instruction to change the name to ECD Child Scorecard, but since the C in ECD stands for Child, should it simply by ECD Scorecard?

@adamhstewart  That’s right we can go with that **ECD Scorecard**

**Comment by anvmn** [comment]
@LudmilaGoichman 

Please verify on Nutrition env

**Comment by LudmilaGoichman** [comment]
@anvmn @jeanette-pelizzon

nutrition env

### Checked and Approved:

NCDA Scorecard has been renamed ECD Scorecard. It was tested at the following locations/meetings:

1. Participant directory
2. Individual child nutrition encounter
3. Standard pediatric visit encounter
4. FBF group nutrition encounter
5. PMTCT group nutrition encounter
6. Newborn exam encounter (CHW)
7. Individual child nutrition encounter (CHW)
8. Group nutrition encounter (CHW)

Example:

<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204886-921266e1-0f4b-4086-824c-84058740551e.png">|<img width="365" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/211204898-0beafa17-11e2-4f49-8324-b050e546cd27.png">
---|---
