### ISSUE TITLE
Dropdown list doesn't fit on the screen [1h]

### ISSUE THREAD

**Issue by isapisa** [TIP-Global-Health/eheza-app#572]
### Issue

> 1. Not related to this issue, but when registering new patient some dropdown list is so long, that doesn't fit on the screen, and I couldn't even use the scrollbar to go further down.
>![image](https://user-images.githubusercontent.com/3536805/207321399-8853123b-707d-428f-855f-fd11fa777c86.png)

_Originally posted by @balagan73 in https://github.com/TIP-Global-Health/eheza-app/issues/542#issuecomment-1348486860_
      

### To Do

- Fix

**Comment by adamhstewart** [comment]
@isapisa @balagan73 This works as expected on a tablet device where touch scrolling is available..
