### ISSUE TITLE
ANC @ Health Center - Labs - Hepatitis B Results [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#58]
## Issue 
**Overview**
During an ANC encounter, a patient sees a nurse who collects the appropriate samples for each test and then sends them to the lab (unless it is a rapid test). The samples are then processed by the lab and results are returned later that day. The patient will return to see the nurse after several hours and receive the results of the labs. Nurses will navigate from their Case Management screen to each patient awaiting lab results. The sub-activities will be all the tests that have been run but they do not yet have results for. The nurse will select the test she has results for and input them. She will do this for all tests she has results for. When she hits save that result will appear in the Progress Report for that patient.

**Hepatitis B Specific** 

The possible results of a Hepatitis B test are:

- Negative
- Positive
- Indeterminate

Screen One | Screen Two | Screen Three 
--|--|--
<img width="278" alt="Screen Shot 2021-11-03 at 4 20 49 PM" src="https://user-images.githubusercontent.com/77505464/140186732-98abfdce-17b0-4600-a35b-6622f23286ea.png"> | <img width="267" alt="Screen Shot 2021-11-03 at 4 20 54 PM" src="https://user-images.githubusercontent.com/77505464/140186747-227d2da2-0165-4028-9e90-8de172227920.png"> | <img width="264" alt="Screen Shot 2021-11-03 at 4 20 57 PM" src="https://user-images.githubusercontent.com/77505464/140186775-76910681-bbe6-4ef8-ad9d-a1f1a5114153.png">

### Note 

You can see the Labs input screen issue for Hep B [here.](https://github.com/Gizra/ihangane/issues/2827) 

## To Do

- Create activity (Hep B Results?)
- Style per design

**Comment by anvmn** [comment]
@LudmilaGoichman
Please test on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@isapisa @anvmn 

- Nutrition Environment
- tablet

### Checked and Approved
 sub-activity has been created

The flow:

the first encounter | case management | new sub-activity | possible results | the result field is mandatory | report |
---|---|---|---|---|---
<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148064095-202d0f7d-3661-4c51-99b7-b55efb2734b1.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148064173-fea84345-8798-4f37-ab56-3db94315091e.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148064232-e2342214-52b7-4d33-972d-64642637744e.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148064260-94aac5c1-4387-4f35-af30-dee4642691ba.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148064294-c3d14da9-8a5b-4647-ade3-0ecbb6f3b05a.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148064404-86971209-6703-4d75-b63c-d4ca7412b8a6.png">
