### ISSUE TITLE
Allow calendar to input dates beyond current limits [3h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#589]
## Issue 
In ANC, currently the calendar is restricted to allow only dates from the previous 6 months (or less)

## Task
- Remove the restriction to allow any date to be selected.

**Comment by anvmn** [comment]
@adamhstewart 

This update implies following changes to form:

![Selection_1493](https://user-images.githubusercontent.com/17882245/212864335-cdb987d1-2b39-45b6-baed-9a6e0afed346.png)

**Comment by Diama1** [comment]
> @adamhstewart
> 
> This updates implies following changes to form:
> 
> ![Selection_1493](https://user-images.githubusercontent.com/17882245/212864335-cdb987d1-2b39-45b6-baed-9a6e0afed346.png)

Thank you @anvmn let me change the range

**Comment by Diama1** [comment]
> @adamhstewart
> 
> This update implies following changes to form:
> 
> ![Selection_1493](https://user-images.githubusercontent.com/17882245/212864335-cdb987d1-2b39-45b6-baed-9a6e0afed346.png)

@anvmn does this mean the first input field should be removed?

**Comment by anvmn** [comment]
@Diama1 

> @anvmn does this mean the first input field should be removed?

Yes, that is what big red X indicates.

**Comment by adamhstewart** [comment]
@anvmn @Diama1 Rather we should make the list input item "Within 6 months or more"

**Comment by anvmn** [comment]
@adamhstewart why do you need that input? It's extra clicks for nothing.

**Comment by adamhstewart** [comment]
@anvmn we don't store it?

**Comment by anvmn** [comment]
@adamhstewart no

**Comment by adamhstewart** [comment]
@Diama1 status here?

**Comment by Diama1** [comment]
> @Diama1 status here?

ready for review
