### ISSUE TITLE
ANC @ Health Centers - Labs - Blood Group + Rhesus [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#59]
## Issue 
The labs for Blood Group + Rhesus are only run on the first ANC Antenatal visit. There are three inputs. There are NO results input for this test in this flow. See note below.

Were you able to perform this test? If yes, you then move on to validate if it was done today. If no, you select from a series of checkboxes why not. Check box options shown here: | If yes, then the question "Did you perform this test today?" appears. If yes, today's date auto-populates in the Test Date section. If no, then a date input appears and the results input will populate directly on this screen. Date input is shown here:
--|-- 
<img width="465" alt="*No checkboxes" src="https://user-images.githubusercontent.com/77505464/140190803-00e511b4-c5ac-4151-a5b1-3079a0b0fe3e.png"> | <img width="499" alt="*Date Input" src="https://user-images.githubusercontent.com/77505464/140190902-cb91ebb5-8856-4ff6-a852-d9079ae4801f.png">

### Design
Please refer to [ANC Labs - Full Prototyp](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746)e in Figma for design.

Screen One | Screen Two | Screen Three 
--|--|--
<img width="312" alt="Screen Shot 2021-11-03 at 4 54 27 PM" src="https://user-images.githubusercontent.com/77505464/140191246-440ab677-8807-437d-8365-0220b255217e.png"> | <img width="309" alt="Screen Shot 2021-11-03 at 4 54 33 PM" src="https://user-images.githubusercontent.com/77505464/140191267-549deba5-f036-495b-9ced-623a56514680.png"> | <img width="319" alt="Screen Shot 2021-11-03 at 4 54 46 PM" src="https://user-images.githubusercontent.com/77505464/140191286-cc316d6e-e8cc-47c5-9a8e-2827194fa14c.png">

### Note 
Blood Group + Rhesus results are sent to the lab and results are given later that same day. Results input is on a separate screen and flow. You can see the issue for the results screen [here](https://github.com/Gizra/ihangane/issues/2830).

## To Do

- Create activity
- Style per design

**Comment by LudmilaGoichman** [comment]
@anvmn @isapisa 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet


### Checked and Approved:
1. the activity has been created and styled per design:

<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714344-d56ed3e6-999a-4c55-b3b7-2341b45ba9a6.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714376-1bdeeb1d-318c-4587-9087-14c417dcb295.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714387-739b7ed3-6f28-411b-8632-23154ccc2061.png">
---|---|---|

<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714397-41041336-27a2-4085-aca5-ee141c368612.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714417-07c506d4-a122-4e91-bbf1-80d8348c3276.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714426-fb17aa7a-e6e2-465c-b329-f2871be7ff0c.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714444-3ef0a52c-84d8-4d77-b609-0fab72fd8fca.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714459-df448775-25af-43fc-89da-071747f38578.png">
---|---|---|---|---

2. logic for date input and calendar has been created ^^

3. The title of the sub-activity is "Laboratory".

<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145714362-62d22fb0-a088-477c-a7d0-a467c34bd0bb.png">
