### ISSUE TITLE
RM - New Home Screen [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#591]
## Issue 
 
Since we are adding another activity type to the home screen, there has been a request to change the format of the home screen to icons - rather than the text buttons we have now. 

This is how the new home screen will look with the new Resilience Messaging addition: 

<img width="383" alt="Screen Shot 2023-01-13 at 11 17 48 AM" src="https://user-images.githubusercontent.com/77505464/212400849-aa2bef70-cc20-43e0-bcac-2a78bfe7fba1.png">

The new icons can be found [here.](https://www.figma.com/file/Z5IoKolLaRe1NGuRe6MozG/Resilience-Messaging?node-id=539%3A1880&t=1bcjKvjchg0yqYLK-0)

## To Do: 
- restructure home screen per design

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

- nutrition env
- tablet

### Checked and Approved:
the new home screen with the new Resilience Messaging addition looks like this:

For Nurse:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220345521-b5b07ce0-f24f-4a24-992c-6785450d8a38.png">

For CHW:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220345602-d823908b-dc5d-4a38-96f0-8e79d4912551.png">
