### ISSUE TITLE
RM - Messaging Cadence (4h)

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#592]
## Issue 

The program is designed so that HCW's will receive three messages a week - Monday (Day 1), Wednesday (Day 2), and Thursday (Day 3). 

In the [spreadsheet](https://docs.google.com/spreadsheets/d/13NyXM8WyhUMCmXi7yUzxlGKJjicakpfN3q8YcHMVADM/edit#gid=419344799) (Tab= DEVELOPMENT MASTER). You will see which week of the program the message should be sent, and what day it should be sent on.  

There are a few exceptions: 
- Introduction Messages: The first four will be sent Week 1, Day 1. The second four will be sent Week 1, Day 2.  This is the only time four messages will be sent in a day. There is some programmatic reason they are broken up this way. 
- Daily Messages: located at the bottom of the spread sheet are actually going to be in-app pop ups and have their own unique cadence depending on the month of the program the user is in. 

## To Do: 
- Schedule messages appropriately

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> The program is designed so that HCW's will receive three messages a week - Monday (Day 1), Wednesday (Day 2), and Thursday (Day 3).

Since we decided that program start date is the date when kick off survey is completed, this definition does not hold.
Please redefine, taking into account that program can start on any day of the week.

**Comment by jeanette-pelizzon** [comment]
@anvmn let's do 1 message every 2 days per our conversation on 1/23

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> @anvmn let's do 1 message every 2 days per our conversation on 1/23

Checked this option, but if we do that, the 'end of period' messages get really off.
If I make periods 2d, 2d, 3d, 2d, 2d, 3d ... End of first month message is on day 30, and second month message is on day 56. Should we try to adjust it more?

**Comment by jeanette-pelizzon** [comment]
> If I make periods 2d, 2d, 3d, 2d, 2d, 3d ... End of first month message is on day 30, and second month message is on day 56.

This sounds like it should work. I want to keep it simple so if it follows a similar cadence and some of the "end of month" messages are off I think it's okay. It's more like they are done with a certain period of the program.  Honestly, what ever you think will be the best here, I trust! 

// @anvmn
