### ISSUE TITLE
RM - Kick Off Survey [14h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#595]
## Issue 
Before entering into the messaging center/wellness module for the first time, the HCW will be presented with a [kick-off survey.](https://docs.google.com/spreadsheets/d/13NyXM8WyhUMCmXi7yUzxlGKJjicakpfN3q8YcHMVADM/edit#gid=419344799) This is a 6 question survey to collect some demographic information about the HCW who will be participating in the program. 

Once they complete and hit save on the survey, they will be taken to the messaging center. 

<img width="226" alt="Screen Shot 2023-01-13 at 2 13 23 PM" src="https://user-images.githubusercontent.com/77505464/212428976-e07189e5-0267-4e86-b35d-089bedd90318.png">

## To Do: 
- Style survey per design 
- Create any related infrastructure.

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

So, task here are:
1. Identify first access to model and route accirdingly [2h]
2. Style the form with inputs [4h]
3. Store recorded data on backend. This involves editing existing nurses, and syncing this change to backend - something we don't have right now and needs to be developed [8h].

Estimation - 14 hours in total.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

 - **Role**: Currently, HCW is either a Nurse or CHW. What are those other options?
 - **Age**: Why not birth date?
 - **Education**: We got 'no schooling' option. Don't we need it here?
 - **Marital status**: Religious?

**Comment by jeanette-pelizzon** [comment]
Role - Those were the list items they gave me so I think we should include them?
Age - This was the question they gave me but we can do birthdate instead, I am okay with that. 
Education - Again, they gave me these options but I believe we should include the "no schooling" option 
Marital Status - No idea, maybe they are a nun or a priest? Again, an option that was outlined to me. 

// @adamhstewart

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

- nutrition env
- tablet

### Question/Found Issue:
1. I can't find the Kick Off Survey for **newly created** HCWs. It doesn't appear when open the Wellbeing module in the first time. I created a new nurse and CHW. When they logged into the app for the first time, the first message displayed was "drink water" and then "unread messages". The Wellbeing module opens with the introduction messages (4) when clicking the "read" button in the "unread messages" pop up or opening the module manually. When all messages are "read", the survey also doesn't appear:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220397659-5a9afea0-d548-45e0-9db4-d72fbae74dda.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220397783-29205886-6ea7-4198-93ab-db5068171b00.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220397918-8596bc52-c01a-4a58-a61f-0c1fead02d5a.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220398461-48c7ebc2-b732-40b1-9cd8-e955f92bc02b.png">
---|---|---|---

2. the Kick Off Survey is displayed for HCWs that were created in the past (before this feature?). But I'm not sure that the flow works as expected. The current flow:
      a. First login - there are no any pop ups. Only the Wellbeing module icon has red counter "4"
      b. When a HCW opens the Wellbeing module manually, the Kick Off Survey appears:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/35059802/220581693-a497b9a0-b040-4dd4-a0a8-dfec5252926e.png">

      c. After answering and saving the survey, the screen with messages is displayed:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/35059802/220581987-bfd83e0d-8458-4755-8cd7-2087bc3ada77.png">

      d. When a HCW closes the module, the "drink water" pop up appears:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/35059802/220582420-33e5860a-1b31-4ea3-b326-2023f6cd1fe3.png">

      e.1. If a HCW closes the module without reading the messages, then after closing the "drink water" pop up, the "unread messages" pop up appears:
      
<img width="369" alt="image" src="https://user-images.githubusercontent.com/35059802/220582782-99ecf28f-aacb-403c-89f3-ff14af0ea5e0.png">

      e.2. If a HCW closes the module when all messages are read, then after closing the "drink water" pop up, the screen looks like this:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/35059802/220585440-ca80bb9c-456a-4d4d-a3e6-c1455aa5d552.png">


4. Is it okay that HCWs can be 10 years old?

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220574520-6b513e31-4d37-4f95-a31c-dc5e359e7f59.png">

5. The order of answer options in questions "What is your role?" and "What is your marital status?" is different from the example in the issues description. Is it okay?

6. The Nurse CT contains more answer options in the "What is your highest level of schooling?" than in the survey. Is it okay?

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/35059802/220579725-c7ef729d-3152-4fb4-b298-b33564b80914.png">

### Checked and Approved:
1. The Kick Off Survey appears only for HCWs that were created in the past when they open the Wellbeing module manually:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220571090-458a6986-94e1-45bb-93e5-eed2c72250c6.png">

2. The Kick Off Survey contains all required questions and answer options:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220574146-8776cf82-03b4-47ea-93a2-17e0f9f4201a.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220574276-073a84ff-4c1f-42ae-af17-d999ef8e66b4.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220574782-b2e32d82-f27c-4530-ae50-8d2045fdf4b0.png">|
---|---|---


<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220575156-ecf91299-66b7-4d80-aa24-6460de0fbafd.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220575213-e85fd08a-ed44-49e8-838c-21418b3313e2.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220575544-f713721f-56bc-46b1-87d3-762f217dfd32.png">
---|---|---

3. After answering the Kick Off Survey, the screen with messages is displayed:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/35059802/220580206-80c86b9b-c265-4247-9ac9-4149bed3f80e.png">


4. The answers are saved in background:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220577338-d358fe37-0b22-4659-b100-8a83dfd5777d.png">|<img width="641" alt="image" src="https://user-images.githubusercontent.com/35059802/220577519-768f2ac3-2841-4031-8d31-62f7345edcd3.png">
---|---
