### ISSUE TITLE
RM - Monthly Survey (4h)

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#596]
## Issue

At the end of every month of the program, the HCW will be presented with a [monthly survey](https://www.figma.com/file/Z5IoKolLaRe1NGuRe6MozG/Resilience-Messaging?node-id=507%3A1505&t=1bcjKvjchg0yqYLK-0) to complete. They will need to fill out this survey before then enter into the messaging center that day. This is consistent with the way the first kick-off survey works. 

The survey will appear on: 
- Week 9, Day 1 
- Week 5, Day 2
(See #592 for more info on messaging cadence) 

<img width="310" alt="Screen Shot 2023-01-13 at 2 11 22 PM" src="https://user-images.githubusercontent.com/77505464/212428706-37f6cc61-3053-4330-a258-265ec2a156f9.png">

## To Do: 
- Style Survey per Design 
- Create any necessary infrastructure

**Comment by anvmn** [comment]
@jeanette-pelizzon @adamhstewart 

Estimation covers for creation and styling, and missing content related issues (creating, storing, syncing...)

**Comment by anvmn** [comment]
@jeanette-pelizzon 

When saying 'monthly' we need to keep in mind the mode in which APP is being used by HCW.
That is, APP may be not opened every day, and it's perfectly acceptable not to be used for a couple of weeks.
Moreover, even if APP is used, we can't force HCW to get into messaging center and take the survey.

So, we can't guarantee that survey will be performed on a certain day of certain week.
It'd make sence to present the servey 1 month after program began, and next survey will be presented 1 months after previous survey was completed.
This is what I'll implement. Tell me if this needs to be changed.

Now, as for estimation, above decision logic will require ~2h.
Creating CT for the survey, storing and syncing it, styling the form is another ~8h.
Please make estimation 10h in total.

**Comment by jeanette-pelizzon** [comment]
@anvmn Agree with you on the timing of the survey. You will also see on the spreadsheet where the "end of month" is in terms of messages - we can send the survey then which aligns with what you are saying I think.

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

- Nutrition env
- tablet

### Questions/Found Issues:
1. The `Every Three Months Survey` didn't appear for nurse and for CHW. Example (nurse):

<img width="848" alt="image" src="https://user-images.githubusercontent.com/35059802/221427084-1a0ee198-1bb5-4944-b9f2-e8f0565ce59f.png">|<img width="1169" alt="image" src="https://user-images.githubusercontent.com/35059802/221427151-c2dab187-a0a7-4fde-aa97-a28d13bf28ae.png">|
---|---

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/35059802/221427219-35946eb3-325b-4cd2-8931-b3bdd2572915.png">|<img width="1063" alt="image" src="https://user-images.githubusercontent.com/35059802/221427186-3a8321fa-e80c-463d-8a40-3f19cd584af4.png">|<img width="1063" alt="image" src="https://user-images.githubusercontent.com/35059802/221427268-22a69c67-452b-4418-9bf5-97bd5306dedc.png">|<img width="1063" alt="image" src="https://user-images.githubusercontent.com/35059802/221427295-ad1977f9-5f13-4172-a578-dbc1192d6d97.png">
---|---|---|---|

### Checked and Approved:
1. The first `Monthly survey` appears one month (31 days) after the `Kick off survey` (for nurse and CHW).
2. The following `Monthly surveys` appear every month  (for nurse and CHW).
3. On other days the `Monthly survey` doesn't appear.
4. The node of the "Resilience Survey" content type with answers is created for each `Monthly Survey`.
5. The `Monthly Survey` screen styled per design.
6. Only one answer can be selected for each question.

Example (CHW):

<img width="837" alt="image" src="https://user-images.githubusercontent.com/35059802/221428114-1cbba446-4e86-44f4-b386-bcab80f50000.png">|<img width="307" alt="image" src="https://user-images.githubusercontent.com/35059802/221428310-b7f5d13b-7c7a-4291-9cb2-617262015ba0.png">|<img width="1105" alt="image" src="https://user-images.githubusercontent.com/35059802/221428453-16291bb7-106f-4054-b0e0-d79e835165a5.png">
---|---|---

<img width="981" alt="image" src="https://user-images.githubusercontent.com/35059802/221428493-fdaec0f7-d389-48dd-b56c-469604b82e0c.png">|<img width="981" alt="image" src="https://user-images.githubusercontent.com/35059802/221428500-81310bfe-f4a3-4bb5-839d-040729b8ae95.png">|<img width="981" alt="image" src="https://user-images.githubusercontent.com/35059802/221428524-505dc134-003a-4a70-8f31-e26a016b1a13.png">|<img width="981" alt="image" src="https://user-images.githubusercontent.com/35059802/221428542-376c3b4b-eb9e-443c-8a4d-0b0b805377c3.png">
---|---|---|---

**Comment by anvmn** [comment]
@LudmilaGoichman 

Every 3 month survey is not part of this development. See https://github.com/TIP-Global-Health/eheza-app/issues/597.

**Comment by LudmilaGoichman** [comment]
@anvmn Sorry I just saw this in Figma and thought it must be
