### ISSUE TITLE
RM - FUTURE ISSUE - 3 Month Survey 

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#597]
## Issue 

THIS ISSUE DOES NOT NEED TO BE ADDRESSED RIGHT NOW. 

Every three months the user will complete a multi-page survey. It should appear at the X Week, X Day. It will appear before they can fully enter the messaging center - behaving consistently with the other surveys. 

[Here is the figma link.](https://www.figma.com/file/Z5IoKolLaRe1NGuRe6MozG/Resilience-Messaging?node-id=507%3A1507&t=1bcjKvjchg0yqYLK-0)

**Comment by anvmn** [comment]
@adamhstewart is this till relevant or can be closed?

**Comment by anvmn** [comment]
Not relevant anymore
