### ISSUE TITLE
RM - Pop Up - New Message [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#598]
## Issue 

Whenever a HCW has a new message or is being reminded about a message, a pop-up will appear on the home screen. This pop-up will only appear when a user navigates to the home screen and will NOT appear in the middle of modules.

<img width="378" alt="Screen Shot 2023-01-13 at 2 28 19 PM" src="https://user-images.githubusercontent.com/77505464/212430883-5b3d528e-054f-4abb-9b8e-7ff31223d801.png">

The pop up will feature the HCW's name and how many unread messages they have waiting in the messaging center. 

## To Do: 
- Style per design 
- Ensure pop up pulls in HCW name 
- Ensure pop-up updates with the number of unread messages

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

- nutrition env
- tablet

### Question (not checked requirement):
1. @anvmn Is it possible to check the next requirement without performing encounters within the one hour?

> ...and will NOT appear in the middle of modules.

### Checked and Approved:
1. The pop up is styled per design
3. The pop up shows the HCW name:

 | Nurse | CHW |
---|---|
| <img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220372195-9f6293b0-fd48-4f09-8077-472c2e941ebc.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220372505-bb85006a-eb27-494b-a3b1-f5223b1fc34e.png">

4. The pop-up updates with the number of unread messages

4 unread messages | one was read | 3 unread messages |
---|---|---
<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220377967-8910981e-7433-4bc2-a530-73034d8f5615.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220379224-46bc7f2c-e144-4393-a036-756e9f46f611.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220379370-8247df76-c533-4902-b660-2b530942be5c.png">
