### ISSUE TITLE
RM - Pop Up - Drink Water [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#599]
## Issue 

During Month One of the program, the HCW will receive a daily pop-up that reminds them to drink water. Originally, the team wanted this to appear at 10am CAT each day. If that is too difficult to do then we just need it to appear sometime during the day. If there are technical questions or limitations please refer those to @adamhstewart. 

- [Copy Found Here ](https://docs.google.com/spreadsheets/d/13NyXM8WyhUMCmXi7yUzxlGKJjicakpfN3q8YcHMVADM/edit#gid=419344799)

- [Figma Found Here](https://www.figma.com/file/Z5IoKolLaRe1NGuRe6MozG/Resilience-Messaging?node-id=548%3A1857&t=1bcjKvjchg0yqYLK-0)

Reminder: Pop-up should ONLY appear on the home screen and should not interrupt a module. It should only appear when a HCW navigates back to the homescreen at some point during their day. 

<img width="437" alt="Screen Shot 2023-01-13 at 2 39 37 PM" src="https://user-images.githubusercontent.com/77505464/212432103-1c2c03a1-158a-41b0-b02c-93f75155099a.png">

## To Do: 
- Style per Design 
- Ensure pop up appears 1x a day.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Bottom actions seem to be wrong. I think it shold be single button with label 'OK' or 'Close'.

**Comment by jeanette-pelizzon** [comment]
@anvm good catch - this was from a previous version of the message - I am fine with OK and Close being the bottom buttons.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

There will be one button. Implemented the 'Ok':

![Selection_1509](https://user-images.githubusercontent.com/17882245/214127426-d8a8ac9c-fb05-403a-94bc-ff59e05e73f6.png)

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn 

- nutrition env
- tablet

### Question:
@anvmn How can I check that after the first month the popup won't appear (other than waiting for a month)?

### Checked and Approved:
1. The pop-up is styled per design. The text is correct.
2. The pop up appears 1x a day. (checked 2 days)
3. Clicking the "OK" button closes the popup

<img width="940" alt="image" src="https://user-images.githubusercontent.com/35059802/220604952-fce1d74f-6622-4ac9-9f8e-712ee58cd52f.png">
