### ISSUE TITLE
ANC @ Health Center - Labs - Blood Group + Rhesus Results [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#60]
## Issue 

**Overview**
During an ANC encounter, a patient sees a nurse who collects the appropriate samples for each test and then sends them to the lab (unless it is a rapid test). The samples are then processed by the lab and results are returned later that day. The patient will return to see the nurse after several hours and receive the results of the labs. Nurses will navigate from their Case Management screen to each patient awaiting lab results. The sub-activities will be all the tests that have been run but they do not yet have results for. The nurse will select the test she has results for and input them. She will do this for all tests she has results for. When she hits save that result will appear in the Progress Report for that patient.

The possible results for each are:

Blood Group Specific  | Rhesus Specific
--|-- 
A | Negative 
B | Positive
AB
O

### Design

https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A43429

Screen One | Screen Two | Screen Three | Screen Four 
--|--|--|--
<img width="247" alt="Screen Shot 2021-11-03 at 5 00 03 PM" src="https://user-images.githubusercontent.com/77505464/140191983-4ff696fa-b726-4bc4-afd5-14074804825d.png"> | <img width="246" alt="Screen Shot 2021-11-03 at 5 00 09 PM" src="https://user-images.githubusercontent.com/77505464/140192009-b2223109-b61b-4af7-956f-2e71e628001d.png"> | <img width="245" alt="Screen Shot 2021-11-03 at 5 00 14 PM" src="https://user-images.githubusercontent.com/77505464/140192018-6eefcc11-030f-4134-9631-0212a8c92e90.png"> | <img width="243" alt="Screen Shot 2021-11-03 at 5 00 19 PM" src="https://user-images.githubusercontent.com/77505464/140192031-aacf43a3-9fd9-48a8-b5ef-1b2a03ad29ba.png">

### Note 

You can see the Labs input screen issue for Blood Group + Rhesus [here.](https://github.com/Gizra/ihangane/issues/2829)

## To Do

- Create activity (Blood Group Results)
- Style per design

**Comment by anvmn** [comment]
@LudmilaGoichman
Please test on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@isapisa @anvmn 

- Nutrition Environment
- tablet

### Checked and Approved
 sub-activity has been created

The flow:

the first encounter | case management | new sub-activity | 
---|---|---|
<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148064699-070c671b-ce3e-411e-852b-57b86f3d711b.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148064765-33fe139c-976a-47aa-b16f-af9e4402bc3e.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148064823-79fe7171-e492-4d11-9787-951a43878210.png">

possible results for group| possible results for rhesus | the results fields are mandatory | report |
---|---|---|---|
<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148065025-c5815812-a3ce-45eb-92c9-2b6ab805c6e5.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148065066-c2bf7586-801d-4a56-834a-f328a40530b3.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148065120-47296f50-c09e-4b45-9cbc-5237b2e47b22.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148065326-38e50a9f-2273-4d56-885f-1efcd63a321b.png">
