### ISSUE TITLE
RM - Pop Up - Take a Break [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#600]
## Issue 

During Month Two of the program, HCW's will receive an hourly pop-up reminding them to take a break. The daily drink water pop-up will stop appearing. 

This pop-up should appear hourly. 

- [Copy Found Here ](https://docs.google.com/spreadsheets/d/13NyXM8WyhUMCmXi7yUzxlGKJjicakpfN3q8YcHMVADM/edit#gid=419344799)

- F[igma Found Here](https://www.figma.com/file/Z5IoKolLaRe1NGuRe6MozG/Resilience-Messaging?node-id=548%3A1947&t=1bcjKvjchg0yqYLK-0)

Reminder: Pop-up should ONLY appear on the home screen and should not interrupt a module. It should only appear when a HCW navigates back to the homescreen at some point during their day. 

<img width="332" alt="Screen Shot 2023-01-13 at 2 51 26 PM" src="https://user-images.githubusercontent.com/77505464/212433491-86e3d9c2-f82d-4723-ae81-964b46e1fcdf.png">

## To Do: 
- Make sure the drink water pop-up stops appearing after month one 
- Style the "take a break" pop-up per design 
- Schedule it to appear hourly.

**Comment by jeanette-pelizzon** [comment]
@adamhstewart I think that this happening hourly is going to be really frustrating. Can we move it to daily?

**Comment by anvmn** [comment]
@jeanette-pelizzon 

Bottom actions seem to be wrong. I think it shold be single button with label 'OK' or 'Close'.

**Comment by jeanette-pelizzon** [comment]
Okay to change to your version.

**Comment by LudmilaGoichman** [comment]
@adamhstewart 
Anatoly wrote that this feature is disabled in the code. So, I shouldn't be checking these issues? Or does this feature need to be re-enabled? Issues of this feature are assigned to me ...
