### ISSUE TITLE
RM - Message Structure [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#604]
## Issue 

Each message has a uniform structure.  

- Icon - Icons are unique to the category of the message
- Category - next to the icon 
- Message Title - unique to each message, outlined in [this spreadsheet](https://docs.google.com/spreadsheets/d/13NyXM8WyhUMCmXi7yUzxlGKJjicakpfN3q8YcHMVADM/edit#gid=419344799)
- Message Content - unique to each message, outlined in this spreadsheet 

<img width="488" alt="Screen Shot 2023-01-13 at 3 35 34 PM" src="https://user-images.githubusercontent.com/77505464/212437502-c501fa7a-e90b-473f-b5dc-1eb7f77bd973.png">

Note: in the collapsed version the character limit before an ellipsis is 241 characters.
Supporting Documents: 
-[ Figma ](https://www.figma.com/file/Z5IoKolLaRe1NGuRe6MozG/Resilience-Messaging?node-id=416%3A555&t=1bcjKvjchg0yqYLK-0)
- [Message Category Icons ](https://www.figma.com/file/Z5IoKolLaRe1NGuRe6MozG/Resilience-Messaging?node-id=539%3A2000&t=1bcjKvjchg0yqYLK-0)

**Comment by Diama1** [comment]
@jeanette-pelizzon about the connecting icons do we use all the three or we choose one?
![Screenshot from 2023-02-06 11-55-49](https://user-images.githubusercontent.com/32199791/216941258-831c845c-cf59-4bfb-8066-454659433bb5.png)

**Comment by anvmn** [comment]
@Diama1 

Yes, we use all, per color of message header:

![Selection_1563](https://user-images.githubusercontent.com/17882245/216943142-78edc8c4-f39b-4d9b-b74e-c694f616b61e.png)
