### ISSUE TITLE
RM - Favorites + Favoriting [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#605]
## Issue 

When a user swipes left on a message, they will have the option to favorite a message. This will add the message to the favorite category. As a note, the message will still appear in it's normal category as well and will be purple. So the message will appear in two places. 

<img width="170" alt="Screen Shot 2023-01-13 at 3 39 37 PM" src="https://user-images.githubusercontent.com/77505464/212437840-a37e1f81-1b6a-456a-bdbe-34d097351866.png">
 
[This video overview will be most helpful to understand how this functions.](https://www.loom.com/share/39f362bb5d094ab792288c5aa268105c)

**Comment by anvmn** [comment]
@jeanette-pelizzon 
Is there an option to 'unfavorite' a message?

**Comment by anvmn** [comment]
Messages menu question:

Per figma, we have it only at 'Unread' tab':

![Selection_1551](https://user-images.githubusercontent.com/17882245/215354785-ad6fa1fb-506f-4d7f-9f78-e1860b16569c.png)

- Is this really, the case, or, should it be available at all tabs?
- When at Unread tab, why do we have the 'Unread' option?
- If not only at Unread, what options should there be, per tab?

**Comment by adamhstewart** [comment]
@anvmn 
- To me it makes sense to have this at every tab, on every message.
- "Read/Unread" and "Favorite/Un-Favorite" should be toggles based on the current status of the message.
- "Remind me" can be static.

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn 

- nutrition env
- tablet

### Questions/Found Issues:
1. Is the following flow correct?
     a. mark one of the messages as "favorite"
     b. tap twice on the message in the original tab - the message will disappear from the original tab
     c. mark the "favorite" message in the Favorite tab as "unfavorite" - the message will also disappear from the Favorite tab

3. The counter of unread messages doesn't changes when some message marked as "favorite". Is it okay?

<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220628587-93cfbcfd-7b67-49c7-99f7-95a78cf47d54.png">|<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220628706-445fedf1-f346-4203-aa40-494b30035d0e.png">
---|---

### Checked and Approved:
1. The massage's menu includes the "favorite" item:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220622254-b6c60083-40b1-4f7e-897d-a6c4fd72464e.png">

2. When clicking the "favorite" item, the message copys to the "Favorite" tab and her heading becomes violet. And the original message stays in the original tab with the red heading.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220625430-191ef680-abb0-4f20-94a5-cf8b62a08792.png">|<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220626688-2372c1d0-1081-4323-84b0-bbfe888f8493.png">
---|---

4. The "favorite" menu item changes to the "unfavorite" item for the "favorite" message in both tabs: 

<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220627115-700868f8-50c3-4da8-8ab6-600bccb10275.png">|<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220627252-7aa30791-eb22-4b62-822b-7e9713acfea6.png">
---|---

5. If to click the "unfavorite" menu item in any tab, the message disappears from the "Favorite" tab, but stays in the original tab and the "unfavorite" menu item replaced with the "favorite" menu item

<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220627831-1bc82378-d41d-40ea-a5f9-bfbdaf532cae.png">|<img width="367" alt="image" src="https://user-images.githubusercontent.com/35059802/220627986-baac5438-a7ec-42e7-b1e2-7a74831c3364.png">
---|---
