### ISSUE TITLE
ANC @ Health Center - Labs - Hemoglobin [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#61]
## Issue 

The Hemoglobin labs are run at every ANC visit. There are three inputs. There is NO results input for this test in this flow. See note below.

Were you able to perform this test? If yes, you then move on to validate if it was done today. If no, you select from a series of checkboxes why not. Check box options shown here | If yes, then the question "Did you perform this test today?" appears. If yes, today's date auto-populates in the Test Date section. If no, then a date input appears and the results input will populate directly on this screen. Date input is shown here:
--|--
<img width="465" alt="*No checkboxes" src="https://user-images.githubusercontent.com/77505464/140388433-44a48951-2c53-446d-99ab-a627216ecdda.png"> | <img width="499" alt="*Date Input" src="https://user-images.githubusercontent.com/77505464/140388484-338c39a9-99d8-43fd-860c-f7e2e7402712.png">

### Design
Please refer to [ANC Labs - Full Prototype](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) in Figma for design.

Screen One | Screen Two | Screen Three
--|--|--
<img width="189" alt="Screen Shot 2021-11-04 at 1 20 37 PM" src="https://user-images.githubusercontent.com/77505464/140388607-76c36a77-4be6-4b3c-b213-2c6a6a070168.png"> | <img width="192" alt="Screen Shot 2021-11-04 at 1 20 41 PM" src="https://user-images.githubusercontent.com/77505464/140388628-9970cad1-b891-4401-b80d-1225ca993138.png"> | <img width="186" alt="Screen Shot 2021-11-04 at 1 20 45 PM" src="https://user-images.githubusercontent.com/77505464/140388674-d4d44260-ed16-4cb5-b647-dce8d14345e0.png">

### Notes
- Hemoglobin results are sent to the lab and results are given later that same day. Results input is on a separate screen and flow. You can see the issue for the results screen [here.](https://github.com/Gizra/ihangane/issues/2834)
- Please note the top of the screen should read "Labs" or "Lab Results" which is appropriate for the screen. Noticed after I made all the issues that the title of the screens were off.

## To Do

- Create activity
- style per design

**Comment by LudmilaGoichman** [comment]
@anvmn @isapisa 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet

### Questions:
1. The title of the sub-activity is "Laboratory". Is this okay? //this question is relevant to all Lab sub-activities

> the top of the screen should read "Labs" or "Lab Results" which is appropriate for the screen.

<img width="363" alt="Hemoglobin1_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145708104-c882d986-0baf-455c-88ca-d08fe1348255.png">

2. `HemoglobinTest` is shown in the design screen. Is this typo in the design?

design | app |
---|---
![E-Heza_2021_–_Figma](https://user-images.githubusercontent.com/35059802/145708281-67dc5769-7268-4c46-895b-d91703a3484d.png)

3. The test name (`Hemoglobin` in this case) is missing in the last note. //this question is relevant to all Lab sub-activities

design | app |
---|---
![E-Heza_2021_–_Figma](https://user-images.githubusercontent.com/35059802/145708324-9097302b-d97c-4a26-9a99-db16cf4f47a9.png)|<img width="365" alt="Hemoglobin1_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145708342-ddae635b-9c8c-431f-bfee-a7f272d690c0.png">


### Checked and Approved:
1. the activity has been created and styled per design:

<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145707960-38e0de2c-023e-43b7-9ae2-42dea562cc58.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145707964-7817a291-dec8-4500-9c31-2fa51be70b28.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145707977-29154667-d54a-4cb6-ae0b-85222c96d013.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145707981-6c48b1de-8e05-42f1-8557-c9f5e4bfc9c4.png">
---|---|---|---

<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145707995-79deef5c-d9e8-46c2-8d6e-9e67bf75dafc.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145708008-30ee5d96-e4d3-438d-91be-d405ffb387ad.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145708023-c232649b-b9bb-4fd1-8298-5f63210c0e44.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145708031-c7653726-d747-44cb-94c0-b76c64a9c88b.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145708046-06db125b-6f13-42cb-9d05-f2e75307495f.png">
---|---|---|---|---

2. logic for questions and date/calendar entry has been created ^^

3.  The title of the sub-activity is "Laboratory".

<img width="363" alt="Hemoglobin1_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145708113-b1b57b01-da02-4099-9815-6388ff9d4823.png">

**Comment by isapisa** [comment]
> 1. The title of the sub-activity is "Laboratory". Is this okay? //this question is relevant to all Lab sub-activities

@LudmilaGoichman yes, this aligns with what we have already in other modules.



> 2\. `HemoglobinTest` is shown in the design screen. Is this typo in the design?

Yes. Fixed it.





> 3\. The test name (`Hemoglobin` in this case) is missing in the last note. //this question is relevant to all Lab sub-activities

this is fine
