### ISSUE TITLE
ANC - Update - LMP [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#616]
## Issue 

In both the CHW and HC ANC first encounters, we ask "Is patient sure of LMP date?" with a Y/N boolean. We are adding logic so if the user selects "No" a follow-up question will appear. This question will ask "What is the reason the patient is unsure?" with three checkboxes: irregular menses, on family planning method, can't remember dates. 

Then see issue #617 for how this will map to the progress report.  
<img width="279" alt="Screen Shot 2023-01-24 at 12 26 02 PM" src="https://user-images.githubusercontent.com/77505464/214401186-cb8440c5-d4f6-4ac1-993a-469b4c634954.png">

## Figma 
-[ Design can be found here ](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=1623%3A38952&t=nmJuG2XH9xswpuoA-0).

## To Do 
- Update logic 
- Add question 
- Style per design

**Comment by jeanette-pelizzon** [comment]
Note: added to ANC sub milestone as the normal ANC milestone is on the old github.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

> with three checkboxes: irregular menses, on family planning method, can't remember dates.

Should we allow multiple options to be selected, or only one of them?

**Comment by anvmn** [comment]
> @jeanette-pelizzon
> 
> > with three checkboxes: irregular menses, on family planning method, can't remember dates.
> 
> Should we allow multiple options to be selected, or only one of them?

Per progress report issue #617, it's single selection.
Implemented as single selection.

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

- nutrition env
- tablet

### Question:
Why does `menses` start with a capital letter when all other options only the first word starts with a capital letter?

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220112525-c1f65249-0cd8-4dd0-8f5d-bcc17acc197f.png">

### Checked and Approved:
The question "What is the reason the patient is unsure?" with three checkboxes: irregular menses, on family planning method, can't remember dates has been added as conditional question. Only one option can be selected:

Nurse:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220112285-1a496554-3f35-40b6-8390-9c75a86a50a1.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220112400-81b84046-4d20-4369-86f2-3d9967b0ff31.png">
---|---

CHW:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220117087-c5825f4a-97dc-44f1-93a3-a3cea6c512a6.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220117218-179641ee-4a73-4b22-aceb-4de9c0f41bd8.png">
---|---

**Comment by adamhstewart** [comment]
@LudmilaGoichman good catch

@Diama1 can you fix the capitalization mistake?

> Why does menses start with a capital letter when all other options only the first word starts with a capital letter?

**Comment by Diama1** [comment]
> @LudmilaGoichman good catch
> 
> @Diama1 can you fix the capitalization mistake?
> 
> > Why does menses start with a capital letter when all other options only the first word starts with a capital letter?

I can add it to the LMP calendar issue
