### ISSUE TITLE
ANC - LMP - Progress Report [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#617]
## Issue 

In Issue #616  we added in a follow-up question to get more information as to why a patient did not remember their LMP. 

Now we need to map that information to the progress report. 

- It will go under Obstetrical History 
- It will read: "Uncertain dating due to ___(insert reason selected)__"

<img width="401" alt="Screen Shot 2023-01-24 at 12 33 39 PM" src="https://user-images.githubusercontent.com/77505464/214403312-f3b12e49-27e2-417c-bb87-914f2c7e7004.png">

## Figma 
- design can be found [here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=463%3A25002&t=nmJuG2XH9xswpuoA-0)

## To Do 
- Update logic for progress report
- Style per design

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn 

- nutrition env
- tablet

### Checked and Approved:
The answer to "What is the reason the patient is unsure?" (about LMP date) is displayed in the progress report under Obstetrical History

Nurse:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220115167-27c9d172-0482-4c05-a317-f7fe5024fe20.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220115297-d5c2d908-6796-4843-bcb8-4f0bc1f3f8bb.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220115412-db337bce-0e5f-47ec-ba34-381717f8ce62.png">
---|---|---

CHW:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220117610-30a808b2-035e-4713-8964-507b3d5c4e71.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220117711-dccdbe84-2535-4a0d-8a79-044058708772.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220117851-2863f173-d30e-427b-9719-a09d5b9d8c9b.png">
---|---|---
