### ISSUE TITLE
ANC - LMP - Next Steps [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#618]
## Issue 

When a patient is unsure of their LMP (see #616 and #617) we need to refer them for an ultrasound. 

<img width="229" alt="Screen Shot 2023-01-24 at 12 42 52 PM" src="https://user-images.githubusercontent.com/77505464/214406478-08ae542a-6eed-40ec-bb50-7f58e8a47f26.png">

## Figma 
- You can see the design [here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=1625%3A39047&t=nmJuG2XH9xswpuoA-0)

## To Do: 
- create ultrasound referral screen 
- add in logic to make it a next step if answered no on LMP confidence question

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn 

- nutrition env
- tablet

### Question:
There is no referral a patient for an ultrasound if a patient is unsure of their LMP in a CHW encounter:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220123169-7058807b-37d9-47a2-9f43-47f67d8db6a6.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220123284-f1fee6fa-f62d-481f-816b-59f5fc33a3e3.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220123384-731fc249-6c62-490b-9770-c4bfa6ece9f5.png">
---|---|---

### Checked and Approved:
1. There is referral a patient for an ultrasound if a patient is unsure of their LMP (for any reason) in a nurse encounter:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220123501-1b326e88-645c-4ec7-8b26-b581ee0590fc.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220123726-32499a13-b5b2-475c-85fc-362958f8a0e4.png">
---|---

2. When the patient also needs to be referred to a hospital, it looks like this:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220124167-42d6d50c-964e-4ebb-93c8-30a9eedf6648.png">
