### ISSUE TITLE
ANC - C-Section - Follow-Up Questions [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#619]
## Issue 

In the Obstetric History sub-activity, we currently ask the number of c-sections a patient has had with a series of follow-up questions. 

These are the changes we are making: 
- We are hiding the follow up questions: "c-section in previous delivery?" and "reason for c-section"
- If a patient answers 0 (zero) to the number of c-sections the follow-up questions will remain hidden. 
- If a patient answers 1 or above, the follow-up questions will appear. 

## Figma 
- You can see the screen design [here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A29320&t=nmJuG2XH9xswpuoA-0) for reference 
- I don't think we need a figma flow to show this but let me know if you do 

## To Do: 
- update logic for screen to make follow-up questions conditional 
- If this question appears at the CHW level, please update there as well

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

- nutrition env
- tablet

### Checked and Approved:
1. If a patient answers 0 (zero) to the number of c-sections the questions "c-section in previous delivery?" and "reason for c-section" remain hidden.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220137451-ccf31385-7d14-48c3-a2c8-2a1014a13c55.png">


2. If a patient answers 1 or above, the questions "c-section in previous delivery?" and "reason for c-section" appear.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220137603-08c54ee6-95bb-479d-90df-f56a35c9be17.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220137758-3dad8fbf-792e-4a04-ab75-bd8798abdac2.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220137912-43ded1dc-cb6b-47f7-b1ee-a37dca8a3c38.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220138065-396cbec4-3929-45cd-9032-c161f9ce69ad.png">
---|---|---|---

3. This question (the number of c-sections) doesn't exist for CHW
