### ISSUE TITLE
ANC @ Health Center - Labs - Hemoglobin Results [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#62]
## Issue
**Overview**
During an ANC encounter, a patient sees a nurse who collects the appropriate samples for each test and then sends them to the lab (unless it is a rapid test). The samples are then processed by the lab and results are returned later that day. The patient will return to see the nurse after several hours and receive the results of the labs. Nurses will navigate from their Case Management screen to each patient awaiting lab results. The sub-activities will be all the tests that have been run but they do not yet have results for. The nurse will select the test she has results for and input them. She will do this for all tests she has results for. When she hits save that result will appear in the Progress Report for that patient.

**Hemoglobin Specific** 
The results of a Hemoglobin test are given in numerical values with decimals (example: 00.00). See screens below for example. 

Screen One | Screen Two 
--|--
<img width="124" alt="Screen Shot 2021-11-04 at 1 27 39 PM" src="https://user-images.githubusercontent.com/77505464/140389399-b944448d-dfb1-4c60-91dd-ffc8071e9dc3.png"> | <img width="120" alt="Screen Shot 2021-11-04 at 1 27 42 PM" src="https://user-images.githubusercontent.com/77505464/140389428-3dd573c6-5be8-4860-8c4a-0862b19e2796.png">

### Note 
You can see the labs input screen issue [here. ](https://github.com/Gizra/ihangane/issues/2833)

## To Do
- Create activity (Hemoglobin Results)
- Style per design

**Comment by anvmn** [comment]
@LudmilaGoichman
Please test on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@isapisa @anvmn 

- Nutrition Environment
- tablet

### Questions:
>The results of a Hemoglobin test are given in numerical values with decimals (example: 00.00). See screens below for example.

1. Should the maximum value (or number of digits before decimal point) be limited?
2. Should the number of digits after decimal point be limited?

<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148066919-592c074f-31c5-4f48-b1a4-d177df7eea03.png">

3. Is it okay that the test result that has not yet been received is already appearing in the historical report?

<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148070127-47e82a46-74bc-4c26-befc-c6da0cc6c27d.png">

4. Is it correct that the date of analysis is when the analysis was checked in the laboratory and not when the analysis (measurements) was taken?

<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148070618-76ba8353-6913-4f64-b31a-7f9b1b61f136.png">|![Prenatal_Hemoglobin_Test_-_Gatera_Marcelline_-_2021-12-04___E-Heza_System](https://user-images.githubusercontent.com/35059802/148070767-d5615a0a-5178-4be4-bf81-db32aaac6e60.png)
---|---

### Checked and Approved
 sub-activity has been created

The flow:

 first encounter | case management | new sub-activity | only numbers can be entered | the result field is mandatory | report |
---|---|---|---|---|---
<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148066415-6409de6b-6aeb-4625-a5cf-4261af549669.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148066467-f7e95b36-74a2-4ef2-a546-d77474003bb1.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148066523-6608c6eb-ea6d-4b20-b11c-72c57df01445.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148066600-25febb77-7798-4f26-9df2-77fe65f606c1.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148066866-4844d532-ddee-4a32-83fc-50fd3aecb28a.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148066320-68f822f9-42c0-47d6-b5df-6f5dfa26cef8.png">

second encounter | report before getting result | historical result | the test result | report |
---|---|---|---|---|
<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148067288-6137896f-c82f-4f1e-ada0-39259f6f72c3.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148067425-48bbb704-f504-439b-99c4-d3ed521f89a1.png">|<img width="363" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148067526-6726e5a8-1dc1-48da-aff7-f4dc7688448e.png">|<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148071106-65df125c-1e9e-46af-ae09-24a04dfca865.png">|<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148071408-5e05611f-e5db-4f88-ab55-7908607aa73b.png">

**Comment by isapisa** [comment]
> * Should the maximum value (or number of digits before decimal point) be limited?

No

> * Should the number of digits after decimal point be limited?

Should probably limit to 1 decimal. @jeanette-pelizzon ?



> 3\. Is it okay that the test result that has not yet been received is already appearing in the historical report?

yes



> 4\. Is it correct that the date of analysis is when the analysis was checked in the laboratory and not when the analysis (measurements) was taken?

should be the test date. @anvmn Can you explain the difference please?

**Comment by adamhstewart** [comment]
@anvmn Only issue 4 should be corrected - display date should be the date the test was recorded as taken.

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn This is relevant for all tests:

> Only issue 4 should be corrected - display date should be the date the test was recorded as taken.

**Comment by anvmn** [comment]
@adamhstewart 

> @anvmn Only issue 4 should be corrected - display date should be the date the test was recorded as taken.

I believe that this is how it behaves now.

![Selection_441](https://user-images.githubusercontent.com/17882245/148112953-04614603-4788-40f5-898f-112bcfe6a7a5.png)

Date measuremed is when measurement was taken.
Execution date is when test was executed, which is what is shown on pregress report.

//cc @LudmilaGoichman

**Comment by adamhstewart** [comment]
@anvmn  got it - this is correct then, thanks!
