### ISSUE TITLE
ANC - C-Section - Reasons [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#620]
## Issue 

On [this screen](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A29320&t=nmJuG2XH9xswpuoA-0), we are updating the check box list for reasons for c-section. 

Changes: 
- Take away "none" as an option
- Add in "previous c-section" as an option 
- Keep all others the same 

## To Do: 
- updated check box list
- let jeanette know if you need an updated design for this

**Comment by LudmilaGoichman** [comment]
@adamhstewart @anvmn 

- nutrition env
- tablet

### Checked and Approved:
Options in Reason for C-section question were updated: the "none" option has been removed and the "previous c-section"  option has been added

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/220139322-80ac7035-9847-4281-ba8f-3267b586ec11.png">
