### ISSUE TITLE
RM - Messages Infrastructure [12h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#621]
### Tasks:

- Create Messages CT
- Expose with restful
- Client side infrastructure to allow storage and sync
- Organise messages in data structuresd (by nurse)
- Allow fetching messages for Nurse from IndexedDB

**Comment by LudmilaGoichman** [comment]
@anvmn 

- nutrition env

### Question:


A don't know how to check the following requirements. Could you please explain me?

>Expose with restful
Client side infrastructure to allow storage and sync
Allow fetching messages for Nurse from IndexedDB

### Checked and Approved:
1. The Resilience Message CT has been created
2. The messages are organised in data structures (by nurse)

![image](https://user-images.githubusercontent.com/35059802/220888679-24650883-5adf-499f-95b2-fa52cdcac44c.png)|<img width="1173" alt="image" src="https://user-images.githubusercontent.com/35059802/220888843-ffd035d2-d68e-4654-b0f4-8add60347648.png">
---|---
