### ISSUE TITLE
ANC - Partner Information - Remove Lab Questions [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#623]
## Issue

In history, under the partner information sub activity, we need to remove the last two questions - "did partner receive HIV test this pregnancy" and the test result. These will be moved to another place. See issue #624. 

<img width="229" alt="Screen Shot 2023-01-24 at 12 42 52 PM" src="https://user-images.githubusercontent.com/77505464/214429253-e53fe6e6-f41f-4981-aa5e-d67cb4fcb32b.png">

## Figma 
-[ See figma here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=1627%3A39287&t=nmJuG2XH9xswpuoA-0)

## To Do: 
- Remove last two questions 
- view issue #624 for more info.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

- Screenshot seem to be wrong
- Figma link does not point to specific screen, but ANC main page

**Comment by LudmilaGoichman** [comment]
@jeanette-pelizzon @anvmn 

- nutrition env

### Checked and Approved:
In history, under the partner information sub activity, the last two questions - "did partner receive HIV test this pregnancy" and the test result have been removed

<img width="359" alt="image" src="https://user-images.githubusercontent.com/35059802/219101174-820608ec-7922-4178-aad9-5ce43009dab0.png">|<img width="359" alt="image" src="https://user-images.githubusercontent.com/35059802/219101245-7a28b749-9da7-4ef1-a87c-01f99c9060c9.png">
---|---
