### ISSUE TITLE
ANC - Partner HIV Lab - New [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#624]
## Issue

Based on feedback from HCW's on the ground, we need to add a sub-activity called "Partner HIV" under the ANC lab section.

- This is where the two questions deleted in #623 are being moved 
- This is a rapid test so it is done at point of care and there is no need to input results later. 
- This change does not affect next steps or logic. 
- If there are alerts or anything mapping to the progress report from the Partner Information sub-activity then those should still exist. 
- The lab should be the first one in the list but can be completed at any time (as any other lab functions) 

<img width="229" alt="Screen Shot 2023-01-24 at 12 42 52 PM" src="https://user-images.githubusercontent.com/77505464/214430693-0afeac93-4e6d-40bd-99d0-43da78578975.png">

## Issue 
- Style screen per design 
- carry over any logic associated with these from their previous location

**Comment by anvmn** [comment]
@jeanette-pelizzon 

- wrong screenshot
- do we have Figma design for this?

**Comment by anvmn** [comment]
> @jeanette-pelizzon
> 
> * wrong screenshot
> * do we have Figma design for this?

Made it similar to HIC test, but without Knows as positive option.
Here's how it looks:

![Peek 2023-02-05 23-18](https://user-images.githubusercontent.com/17882245/216947544-4a9e71a9-2272-415c-9c70-bfccd8209645.gif)

**Comment by LudmilaGoichman** [comment]
@jeanette-pelizzon @anvmn 

- nutrition env

### Question:
This lab only appears in the sequence encounter if the test wasn't performed in the first encounter, or if the result is Indeterminate. Is it correct?

### Checked and Approved:
1. New sub-activity (lab)has been created
2. The lab is the first one in the list 
3. This sub-activity only appears in the sequence encounter if the test wasn't performed in the first encounter, or if the result is Indeterminate
4. The results are saved in background

<img width="929" alt="image" src="https://user-images.githubusercontent.com/35059802/219114129-b14743f3-9fe2-4cb0-9ea7-0834c0c54069.png">

5. The screens are styled per design:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219114500-b0e27007-8118-4abe-89f3-9a1f6f29591c.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219114848-1dca80ff-0795-45c6-baab-4b497b212f32.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219115136-ce875b55-1c7d-4d46-b5c4-42380ee6cf5b.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219115272-653ed575-c014-4d0b-9c62-1f733291379a.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219114957-fde58378-b640-4b43-84eb-61a0f5107f07.png">
---|---|---|---|---
