### ISSUE TITLE
ANC - Partner HIV Lab - Progress Report 

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#625]
## Issue 

The result of the HIV partner lab should appear on the progress report in the lab section. It will be one line item (no arrow to more). Normal range is Negative. If positive or undetermined it will appear red. 

## To Do 
- Create Progress report entry for this 
- Let jeanette know if you need a design for this but it should be straightforward

**Comment by anvmn** [comment]
@jeanette-pelizzon 

No need for design, but I need the text to be displayed.

**Comment by anvmn** [comment]
> @jeanette-pelizzon
> 
> No need for design, but I need the text to be displayed.

This is how I made it:

![Selection_1564](https://user-images.githubusercontent.com/17882245/216945584-eeed334d-551c-4fd3-8dee-6d8a168ee23b.png)

**Comment by LudmilaGoichman** [comment]
@jeanette-pelizzon @anvmn 

- nutrition env
- tablet

### Questions:
1. > It will be one line item (no arrow to more). Normal range is Negative. 

The lab appears in the subsequent encounter if the test result was indeterminate in the first encounter, so the arrow and lab history are present. It's OK? Or is the indeterminate result not supposed to appear in the lab history and therefore the arrow and the lab history will not appear (will always show only the last result without the arrow)?

<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219950366-3a129ec6-3534-4dbe-b65e-862c5051af25.png">

2. About the question `Is the patient partner HIV positive?` in `HIV` lab. How should the nurse select an answer if the test result is indeterminate or has not yet been completed? There are only `Yes` and `No` answers

<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219950559-d7b2fffb-5d80-493a-b613-f06a683aa3d7.png">


### Checked and Approved:
1. The result of the HIV partner lab appears on the progress report in the lab section. Normal range is Negative. If positive or undetermined it appears red.

the Indeterminate result from the first encounter | the Indeterminate result from the second encounter | all results |
---|---|---
<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219949248-59324d54-6fae-4a92-a5cf-1c4ab945f07a.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219949813-464f29f4-c545-4ba4-8aca-82d0e897a47c.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219949844-bfa90628-9a71-4719-8d4a-9a93c62865a0.png">

 | the Positive result from the second encounter | all results | the Negative result from the second encounter | all results |
---|---|---|---
<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219949933-3d847a04-62b2-4bc4-b6e7-697ca794feaf.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219949968-3b54bf00-0c84-452e-b019-ba54965bf926.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219949982-9fa0ff6d-68ff-4a0c-b4ef-c6a10a736557.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219949998-5f9ffc4a-acbe-49d2-803d-1dd9c80002c2.png">
