### ISSUE TITLE
ANC - Breast Exam - New Question [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#627]
## Issue 

Based on feedback from HCW's we are adding a new conditional question to the breast exam. If discharge is selected in the first question, the conditional question will appear. 

![Selection_1557](https://user-images.githubusercontent.com/17882245/216355698-dbc2d84f-18b9-4299-abc1-01e900898400.png)

## Figma 
- [Design is here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=127%3A28744&t=nmJuG2XH9xswpuoA-0)

## To Do 
- Create new conditional question 
- style screen per design

**Comment by anvmn** [comment]
@jeanette-pelizzon 

wrong screenshot

**Comment by anvmn** [comment]
> @jeanette-pelizzon
wrong screenshot

Fixed by myself

**Comment by LudmilaGoichman** [comment]
@jeanette-pelizzon @anvmn 

- nutrition env

### Question:
1. The question is different from the one in the description. Is it okay?

![image](https://user-images.githubusercontent.com/35059802/219091773-68e48153-b78b-4c83-9bcc-d191e76ba304.png)

### Checked and Approved:
1. new conditional question has been added.
- in the first encounter:

conditional question doesn't appear:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/219090734-56e72b85-ea70-4682-8278-bb667197aeda.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/219090889-7f785402-fc38-44ed-a1e0-475b9ca6be62.png">|<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/219091018-2fab0dc9-f5fd-4fba-b7dd-0bb110b00606.png">
---|---|---

conditional question appears:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/35059802/219091434-00911258-f9b4-4616-a2c8-2164fa0e94da.png">

- in the subsequent encounter:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/35059802/219092251-cab7f5b7-63b4-496c-8d64-00df35c5fd01.png">|<img width="359" alt="image" src="https://user-images.githubusercontent.com/35059802/219092442-bbf57e19-191f-46fc-b6c4-66277f5b63d1.png">
---|---

2. the data is saved in backend

<img width="747" alt="image" src="https://user-images.githubusercontent.com/35059802/219092094-f42ce2bd-ec5b-42bc-a0ab-ecca5f6cb143.png">
