### ISSUE TITLE
ANC - Labs - Malaria [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#631]
## Issue 
We need to create a new pathway if Malaria RDT was not completed. Apparently, the supplies to run an RDT are sometimes out of stock and they need a different way to diagnose malaria. 

If RDT was not completed the following conditional questions should appear: 
 - check list of why not 
 - Was a blood smear performed 
 - If yes to the blood smear question, then What was the result.
 
<img width="244" alt="Screen Shot 2023-01-25 at 8 37 37 AM" src="https://user-images.githubusercontent.com/77505464/214623347-8b8c2efa-2da1-4894-bb37-bd2675846671.png">

## Figma
- You can see Figma design[ here](https://www.figma.com/file/0rIDfLlgZ3KHSt0VAOP2za/ANC-%7C-Health-Center?node-id=1640%3A39869&t=RIqn4CFdJGu3M2Io-0)

## Note 
- This will need to update to the progress report. I'll make a separate issue for that. 
- The options for results may change - waiting to hear back from the team. 

## To Do
- update the conditional questions for if no RDT was performed.

**Comment by anvmn** [comment]
@jeanette-pelizzon 

You say `different way to diagnose Malaria`. Does this mean that answers to follow up question should somehow result in Malaria Diagnosis?

**Comment by adamhstewart** [comment]
@anvmn any non-negative result on the blood smear (+, ++, +++) all result in a malaria diagnosis (same as a positive RDT)

**Comment by LudmilaGoichman** [comment]
@jeanette-pelizzon @anvmn 

- nutrition env
- tablet

### Question:
Conditional questions appear not when the second question is answered No, but when the first question is answered No. I think this is correct, but I want to make sure

<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219956862-1164c8b7-f41b-4c96-95c5-2982ebd6c3a8.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219957071-456f5e26-4324-474a-b0fc-657af0306d7a.png">
---|---

### Checked and Approved:
 the conditional questions have been updated

<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219956817-8147f862-845c-4173-b7fb-a0a3b2a68dc8.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219956906-cc3f79a2-30e7-46ed-888f-73c12d0b3e06.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219956937-7be8e48a-54b7-451a-8efd-8fd4342f9a20.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219956963-643d798f-69aa-475d-8ab3-b9619dcd1fed.png">|<img width="365" alt="image" src="https://user-images.githubusercontent.com/35059802/219956989-e380277f-9700-481d-b8d3-50d85d5fff92.png">
---|---|---|---|---

**Comment by adamhstewart** [comment]
> Conditional questions appear not when the second question is answered No, but when the first question is answered No. I think this is correct, but I want to make sure

looks correct,
