### ISSUE TITLE
Error on gulp after DDEV v1.21.4 upgrade [1h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#637]
Seems like the problem is due to nvm-defined node version is not being picked up.

![Selection_1549](https://user-images.githubusercontent.com/17882245/215352287-f3062cdf-d461-4351-b218-b97807554fcb.png)

**Comment by anvmn** [comment]
A workaround for this is to `ddev ssh` and then `gulp`.

**Comment by anvmn** [comment]
Found something similar reported on DDEV Github: https://github.com/drud/ddev/issues/4499

**Comment by anvmn** [comment]
Solution from https://github.com/drud/ddev/issues/4499#issuecomment-1366781127, to add `exec-host` to post-start hook, with PATH export doesn't work.

**Comment by anvmn** [comment]
[9358a3d](https://github.com/TIP-Global-Health/eheza-app/pull/638/commits/9358a3d2dd620028dc7c1165c47cd1d1c921f5f9) fixed this, but not sure it's the best approach.
@AronNovak what do you think?

**Comment by AronNovak** [comment]
@anvmn It's more or less okay, ddev's nvm handling is not so stable across releases, tweaks like this are unfortunately needed from time to time.

**Comment by rfay** [comment]
Oddly, no changes in nvm handling for some time. But it is in fact *hard*.

**Comment by rfay** [comment]
But, of course...

* https://github.com/drud/ddev/issues/4499#issuecomment-1419989916
