### ISSUE TITLE
ANC @ Health Center - Labs - Urine Dipstick Results [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#64]
## Issue 

**Overview**
During an ANC encounter, a patient sees a nurse who collects the appropriate samples for each test and then sends them to the lab (unless it is a rapid test). The samples are then processed by the lab and results are returned later that day. The patient will return to see the nurse after several hours and receive the results of the labs. Nurses will navigate from their Case Management screen to each patient awaiting lab results. The sub-activities will be all the tests that have been run but they do not yet have results for. The nurse will select the test she has results for and input them. She will do this for all tests she has results for. When she hits save that result will appear in the Progress Report for that patient.

### Short Dip Specific

There are three sub-tests in this version the urine dipstick. Possible results:

Protein | Ph | Glucose
--|--|--
Negative | 5.0 | 0
30 | 6.0 | +1
100 | 6.5 | +2
300 |7.0 | +3
2000 | 7.5 | +4
||8.0
||8.5

Screen One | Screen Two | Screen Three | Screen Four 
--|--|--|--
<img width="187" alt="Screen Shot 2021-11-04 at 2 31 21 PM" src="https://user-images.githubusercontent.com/77505464/140399188-11c6a451-a301-4a58-8eed-e19381af1071.png"> | <img width="188" alt="Screen Shot 2021-11-04 at 2 31 25 PM" src="https://user-images.githubusercontent.com/77505464/140399216-e94e6274-d39c-467e-9294-ff2d48e77005.png"> | <img width="182" alt="Screen Shot 2021-11-04 at 2 31 30 PM" src="https://user-images.githubusercontent.com/77505464/140399234-2baf951a-4233-4ea1-b01e-e064b84a537e.png"> | <img width="186" alt="Screen Shot 2021-11-04 at 2 31 36 PM" src="https://user-images.githubusercontent.com/77505464/140399247-21abec31-6149-40d0-8bc8-d31c4ce2a666.png"> | <img width="186" alt="Screen Shot 2021-11-04 at 2 31 36 PM" src="https://user-images.githubusercontent.com/77505464/140399317-deee0b71-648f-42b7-9867-db04ca963944.png">

Screen Five | Screen Six | Screen Seven 
--|--|--
<img width="184" alt="Screen Shot 2021-11-04 at 2 31 41 PM" src="https://user-images.githubusercontent.com/77505464/140399385-28ada128-797f-4aa3-8f47-6d88291ba08a.png"> | <img width="186" alt="Screen Shot 2021-11-04 at 2 31 46 PM" src="https://user-images.githubusercontent.com/77505464/140399410-ce8fb032-b099-40d4-b7f1-8f149db80e5c.png"> | <img width="190" alt="Screen Shot 2021-11-04 at 2 31 50 PM" src="https://user-images.githubusercontent.com/77505464/140399430-4c667966-46e2-4a96-9673-058585c48b40.png">

### Long Dipstick
There are ten sub-tests in this version the urine dipstick. See the info for the first 3 above.

Leukocytes | Nitrite | Urobilinogen | Haemoglobin | Specific Gravity | Ketone | Bilirubin
--|--|--|--|--|--|--
Negative | Negative | 0.2 | Negative | 1.000 | Negative | Negative
Small (+) | + | 1 | Non-Hemolyzed Trace | 1.005 | 5 | Small (+)
Medium (++) | ++ | 2 |  Non-Hemolyzed Moderate | 1.010 | 10 | Medium (++)
Large (+++) | | 4 | Hemolyzed Trace | 1.015 | 15 | Large (+++)
||| 8 | Small | 1.020 | 40
|||| Moderate | 1.025 | 80
|||| Large | 1.030 | 100

Example of screen: 
<img width="198" alt="Screen Shot 2021-11-04 at 2 36 54 PM" src="https://user-images.githubusercontent.com/77505464/140400797-0a1ad09a-d834-4fcd-888c-d3bbfaffdf47.png">

### Note 
- You can see the Labs input screen issue for Urine Dipstick [here.](https://github.com/Gizra/ihangane/issues/2835)
- Please note the top of the screen should read "Labs" or "Lab Results" which is appropriate for the screen. Noticed after I made all the issues that the title of the screens were off.

## To Do

- Extend activity
- Logic for displaying short vs long dipstick results
- Style per design

**Comment by anvmn** [comment]
@LudmilaGoichman
Please test on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@jeanette-pelizzon  @anvmn 

- Nutrition Environment
- tablet

### Questions/Found Issues:
1.This test is called "pH" (lowercase first letter) in the design. Should it be fixed?

Short Dipstick| Long Dipstick | Design |
---|---|---
<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148073379-743fbd4e-2b8d-4a4f-b303-25bb0b33f82e.png">|<img width="361" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148093959-a46e5f18-72e5-46ca-82bd-23647d926a19.png">|![140399188-11c6a451-a301-4a58-8eed-e19381af1071_png__374×694_](https://user-images.githubusercontent.com/35059802/148073494-1bfdfbd7-2c33-4353-9572-08724e84eb33.png)

2. Typo. It should be `Small` (Leukocytes):

<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148094653-41142be5-f475-4a65-b83f-04167e82b90d.png">

3. Values `Small`, `Medium` and `Large` (Leukocytes ) should have `+`/`++`/`+++` in parentheses:

<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148095158-2fe45896-c948-4bc7-9712-f51b9b125eb8.png">

4. `Non-Hemolyzed` (Haemoglobin) should be with `-`:

<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148095622-63fb5d06-ef5d-4795-b3b5-da80725df3f6.png">

5. Values `Small`, `Medium` and `Large` (Bilirubin) should have `+`/`++`/`+++` in parentheses:

<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148096167-5543aa3b-6c6d-4cab-84d7-3c5cb3e1dd69.png">

6. Only 3 tests results are displayed in the report for `Long Dipstick` analysis: Protein, pH and Glucose (as for `Short Dipstick`). Leukocytes, Nitrite, Urobilinogen, Haemoglobin, Specific Gravity, Ketone and Bilirubin test results are not shown. Is this correct?

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148099878-ebeaefcb-cf1b-4cb1-b5cc-b6c6e45e4010.png">

### Checked and Approved
 sub-activity has been created

The flow:

 first encounter (**Short Dipstick**) | case management | new sub-activity | possible results for protein | 
-- | -- | --|---|
<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148072101-17815e76-d986-4819-a763-d41fa5ffd045.png">|<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148072217-c041691c-301f-455a-b6c1-3744ec71d6a8.png">|<img width="368" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148072360-50f7757c-88c1-4400-8312-316716f8396e.png">|<img width="363" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148073729-de5af674-5d37-45c4-82ea-b02910da7551.png">

possible results for pH | possible results for Glucose | the results fields are mandatory | report |
-- | -- | --|---|
<img width="363" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148073821-b1bf1fc2-910d-4fff-9094-1eb2174971c1.png">|<img width="363" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148073854-308e76ef-2310-4c7b-a62d-e25dae413ffe.png">|<img width="363" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148073893-bca463ea-629a-4a4d-bffe-18b5942aa30e.png">|<img width="363" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148073993-0114eb4d-dc18-4f0f-a801-14adb4930815.png">


second encounter (**Long Dipstick**) | report before test results | historical reports - Protein , pH and Glucose | new sub-activity |
---|---|---|---|
<img width="363" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148074381-a19c767a-ffff-4caf-b940-b170a4a96806.png">|<img width="363" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148074478-8939bf77-819d-40a0-8ae8-ac9b19eb4bde.png">|<img width="357" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148074661-50c3b716-50c1-4707-85cc-5689352d9041.png"><img width="357" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148074867-2e4e6c56-36aa-4764-9492-4e65266ac081.png"><img width="357" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148074908-a58aff16-b16a-4841-995a-42c6feaa7f50.png">|<img width="363" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148075138-641634bb-b558-471f-8c63-e32d621139f4.png"><img width="361" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/148075226-4317985c-227d-495d-a702-b89006719177.png">

 possible results - Protein | possible results - pH | possible results- Glucose | possible results - Leukocytes | possible results - Nitrite |
-- | -- | -- | -- | -- |
<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148094049-c1789e96-3ec8-4349-80c5-c0fc05edc737.png">|<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148094081-9ce5f078-b62c-441c-9afa-de7b9d00846d.png">|<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148094121-16786b0d-965d-4825-a2d0-181dcdb52be4.png">|<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148094278-eb8b6984-5788-492c-8106-5425ffa0e37d.png">|<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148095116-d768063c-37d3-46a4-b867-d965a7077db8.png">

 possible results - Urobilinogen | possible results - Haemoglobin | possible results- Specific Gravity | possible results - Ketone | possible results - Bilirubin |
-- | -- | -- | -- | -- |
<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148095319-83b768cb-d770-496d-b93a-8c81f472276a.png">|<img width="361" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148095453-45d170e4-ab71-49b6-9be8-de778d05a925.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148095896-3e59ada0-f53d-4c11-b5a3-9afe18699851.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148095961-69882d26-d40b-42e6-afb2-b39bd1819d27.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148096021-419a6865-fe73-4035-8b0b-6b67908bf9de.png">

**Only 3 tests results are displayed in report: Protein, pH and Glucose:**

 Report | historical report - Protein | historical report - pH | historical report - Glucose | 
-- | -- | -- | -- |
<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148096348-ec4f0230-8b4d-4813-b762-91a78c58dc15.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148096503-20e91131-21f9-47b7-80c2-0ace7120f4fe.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148096563-4333e46d-aebb-4b16-befb-76666a191aca.png">|<img width="364" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148096593-df2845b3-b464-40d7-8fee-515d392d93c4.png">|

**Comment by adamhstewart** [comment]
@anvmn Found issues 1-5 can be fixed. I'm not certain about issue 6 -we'll wait for @jeanette-pelizzon .

**Comment by jeanette-pelizzon** [comment]
Issue number 6 - that's a really good catch. I will have to add those in the progress report. I think that for urine dipstick section in the PR only the ones run should appear in the report. Thoughts?

// @adamhstewart

**Comment by jeanette-pelizzon** [comment]
updated design for and progress report labs section when a long urine dipstick is performed <img width="330" alt="Screen Shot 2022-01-05 at 5 36 17 PM" src="https://user-images.githubusercontent.com/77505464/148299410-74e16837-62f0-4214-958c-1a609bc2d678.png">

**Comment by anvmn** [comment]
@adamhstewart 

Points 1 - 6 fixed at #99

**Comment by anvmn** [comment]
@LudmilaGoichman 

All points fixed. Please retest on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@isapisa 

- Nutrition Environment
- tablet

### Found Issue:
1. "PH" should be changed to "pH" in Lab History of the report:

<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152185720-fdc0591c-2726-43d1-a387-3f207dc5a53f.png">


### Checked and Approved:
1. "PH" has been changed to "pH" 

Short Dipstick| Long Dipstick | in the Report |
---|---|---
<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152185893-3787ef42-ae29-48bf-bbca-7f4a9b00b0d8.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152184102-4b833a2c-7595-402f-845f-4db0daa631b2.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152185046-18339383-5ac5-434e-88c7-25c2236fc7c3.png">


2. Typo has been fixed to `Small` (Leukocytes):

<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152184212-739f04a5-baab-4301-8ac3-d55c661f2532.png">

3. `+`/`++`/`+++` in parentheses have been added to values `Small`, `Medium` and `Large` (Leukocytes ) 

<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152184402-de5acbfe-a1aa-40c2-a130-8ff597145ba7.png">

4. `-` has been added to `Non-Hemolyzed` (Haemoglobin):

<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152184524-f7bfa214-3ba2-4125-bacd-b9e4bcfada7b.png">


5. `+`/`++`/`+++` in parentheses have been added to values `Small`, `Medium` and `Large`  (Bilirubin) 

<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152184664-37147287-5d25-4d1b-a74a-ae9c9fd55ef5.png">

6. All tests results are displayed in the report for `Long Dipstick` analysis

<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152184977-3f454673-508b-4cd6-a4dc-c425866e83ab.png">

`Short Dipstick` analysis has been performed after `Long Dipstick` analysis:

before results | after results |
---|---
<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152185336-605ea4dc-15f3-4d51-ba99-aef37e0f179c.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152185997-eb8032c4-74b5-4a28-b531-02156c1d9333.png">
<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152185388-ec42f2c2-08d1-461b-bad4-8d85d696b9ed.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152186055-09d41619-d8b8-4181-98b7-94f95925ac99.png">
<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152185488-13747270-30cb-404e-aa5c-052333250ea7.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152186103-d3f821e2-7670-4d49-b594-f0a9f8bc8932.png">
<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152185799-25943870-2a14-435b-80a5-175c67934fb7.png">|<img width="363" alt="Screenshots_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/152186152-3ea98128-c3ed-465e-87bd-32e44a7b7bd7.png">

**Comment by jeanette-pelizzon** [comment]
@Diama1 can you please fix this issue that Ludmilla found? 

// @anvmn

**Comment by Diama1** [comment]
> @Diama1 can you please fix this issue that Ludmilla found?
> 
> // @anvmn

@jeanette-pelizzon sure
