### ISSUE TITLE
Stock Mgmt - Infrastructure [10h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#640]
## Issue 

Users will be able to enter into the stock mgmt feature through the home screen on the app. Since we have moved to icons on the homescreen when we did resilience messaging, there will be an icon and the words Stock Managment under it added to the end of the existing icons. 

For now, we will re-use the current FBF icon

<img width="131" alt="Screen Shot 2023-01-30 at 12 15 02 PM" src="https://user-images.githubusercontent.com/77505464/215585403-d6c0395b-d7a5-460c-b2b7-b91fe74bb504.png">

## Issue 
- Add icon to the homescreen

**Comment by anvmn** [comment]
@adamhstewart 
As we diescussed, we'll need to come up with requirements of privileges for access here.
Should we allow access to any nurse, or introduce new role?

As for infrastructure, we'll need to define (one ?) CT that will record stock update.
For totals, we'll need to add logic on backend for calculations, and transfer back to devices as part of HC statistics.

**Comment by anvmn** [comment]
@adamhstewart Another CT will be required for signature, which will be refferenced from Stock Update CT.

**Comment by adamhstewart** [comment]
> Should we allow access to any nurse, or introduce new role?

All nurses will handle stick management

**Comment by LudmilaGoichman** [comment]
@isapisa @adamhstewart 

@anvmn wrote to me that this feature is not ready for QA
