### ISSUE TITLE
Stock Mgmt - Main Dashboard [18h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#641]
## Issue
The main screen of stock mgmt is a dashboard so that users can easily see all the required information in a quick glance. 

At the top you have the current month highlights - Month to Date IN (MTD In - sum of everything received this month), Month to Date Out (MTD Out- sum of everything given out during visits or manually marked as out), Current Stock (what we are auto calculating as the amount of stock they currently have on hand).  You will see at the very top of the screen it has the month and year. This is how we have it in dashboards and are carrying that over here. If they click right or left it will change the "current month" shown. 

Next there are three buttons that take you to different screens - receive stock (#ISSUE NUMBER), View Current Month Details (#ISSUE NUMBER), Correct Entry (#Issue Number). 

Finally, you have the history. This shows the past 12 months highlighted information. 

<img width="359" alt="Screen Shot 2023-01-30 at 12 24 57 PM" src="https://user-images.githubusercontent.com/77505464/215587213-9c8525a0-cd11-499c-aee6-be1915eeca83.png">

## To Do: 
- Style Screen per design
- Set up autocalculations 
- set up history feature

Note: Let Adam know if the time estimation needs to be updated.

**Comment by anvmn** [comment]
@adamhstewart 


1. Since this screen goes year back, at the moment of launh, only thing we'll be able to fill in the History table is the 'Issued' column. 
2. We'll need to define a way to update starting stock, and when feature is launched implement for each HC.
