### ISSUE TITLE
Stock Mgmt - Current Month Details [10h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#642]
## Issue

When a user clicks on "View Current Month Details" from the main Stock Mgmt screen, they will be taken to a more detailed view of just the current month (which is selected at the top of the main screen). 

This screen shows the history for the current month - anything received, any entry corrections, and anything issues (@adamhstewart should we do this daily or weekly for this screen?) 

The format of this screen directly mimics the paper form they are currently using so we need to keep it the same. 

The download report button will allow them to download a version of this report if they need to turn it in to the Ministry of Health. This can be a normal spreadsheet and, I assume, can be done just on the backend in the same way they are currently getting reports. 

<img width="366" alt="Screen Shot 2023-01-30 at 12 40 20 PM" src="https://user-images.githubusercontent.com/77505464/215590046-e5cd5c55-a038-4881-8ea2-70d28b2da29c.png">

Note: 
- Balance should automatically calculate
- Months of Stock is calculated by the app. Months of stock = Total current stock(balance)/monthly consumption average.
- Monthly consumption average.= total consumption over last six month / 6

**Comment by anvmn** [comment]
@adamhstewart 

This table should view 3 different types of entries.
The design right now is adjusted only for 'Received stock'.
For issued stock and entry correction, for example, we don't have batch number with expirity date. For issued stock there's also no signature
Maybe we need to redefine some of table columns to better suit the needs.

Please update the design to show all 3 types of entries at the table.

**Comment by adamhstewart** [comment]
> For issued stock and entry correction, for example, we don't have batch number with expirity date. For issued stock there's also no signature
Maybe we need to redefine some of table columns to better suit the needs.

"Issued" stock is stock that has been distributed during FBF (sachet by sachet) this needs to be tabulated per month and displayed on this table. Rioght now there is no signature for individual distribution, but we may add it.

Re: "entry correction" - agreed, we should duplicate the inputs from received stock.

**Comment by anvmn** [comment]
@adamhstewart 

> "Issued" stock is stock that has been distributed during FBF (sachet by sachet) this needs to be tabulated per month and displayed on this table. Rioght now there is no signature for individual distribution, but we may add it.

Not sure I understand. Do you expect to see an entry for each distribution made to child/mother?
In any case. seems this requires some more thought and maybe additional issues with required modifications, so that we have needed info.
