### ISSUE TITLE
Stock Mgmt - Receive Stock [10h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#644]
- On hold until we get answers from team 

## Issue
When a user clicks "Receive Stock", they will be taken to a new screen where they can input all the necessary details.  

- Date - calendar will pop up 
- Where is the stock from - drop down (options in red on the screenshot)
- Expiration Date - Calendar will pop up 
- How much stock is being received - numerical input 
- Months of Stock - this should be automatically calculated (Months of stock=Total current stock(balance)/monthly consumption average) 
- Log In verification - make sure its the correct user - if no, they need to select the correct user OR @adamhstewart do we want them to log out and log in as the correct user - forces them to be diligent about who they are logged in as. 
- Signature 

<img width="628" alt="Screen Shot 2023-02-08 at 8 11 10 AM" src="https://user-images.githubusercontent.com/77505464/217585942-625b6a56-7135-41e7-af1e-21d9c86c4fa6.png">

**Comment by jeanette-pelizzon** [comment]
Main issue updated. @adamhstewart need your input on the user verification bit.

**Comment by anvmn** [comment]
@adamhstewart 

Is this still on hold?

Comments:

1. Log In verification should be first question. Also, need to define what happens if the answer is NO.
2. Please define formula for Months of Stock.

**Comment by jeanette-pelizzon** [comment]
**Updated Designs for Receiving Stock:** 

**The first screen** will verify the user -
<img width="308" alt="Screen Shot 2023-02-15 at 8 20 40 AM" src="https://user-images.githubusercontent.com/77505464/219088203-fa1c20ae-8236-4216-b1d5-6c3e9626b926.png">

**If answer is no**, this screen will appear and should take them back to the home screen.
<img width="350" alt="Screen Shot 2023-02-15 at 8 22 16 AM" src="https://user-images.githubusercontent.com/77505464/219088477-879e1ae0-7439-4fa6-9da0-2b38ea316212.png">

**If the answer is yes**, then they can proceed with the rest of the receive stock inputs. *NOTE*: we have added in a freeform field for users to input observations so that it matches with the form they use in real life. This is the first time we are having a free form input field. @adamhstewart do we need a character limit? Just remember kinyarwanda words are super long
<img width="290" alt="Screen Shot 2023-02-15 at 8 34 21 AM" src="https://user-images.githubusercontent.com/77505464/219092297-b5fe0eb6-25b2-4bc1-94cf-3dae5822734c.png">

**Comment by jeanette-pelizzon** [comment]
As a reminder these are the dropdown options for "where was this received from?"

- MOH (Ministry of Health)
- RBC (Rwanda Biomedical Center)
- UNICEF
- RWANDA MEDICAL SUPPLY (RMS)-Central level
- RWANDA MEDICAL SUPPLY (RMS)-District Level
- BUFMAR (Le Bureau des Formations Médicales agréées du Rwanda)


This is the formula we were given for months of stock: 

Months of Stock = Total Current Stock (Balance) / monthly consumption average

**Comment by anvmn** [comment]
@jeanette-pelizzon consumption average needs to be defined as well.

**Comment by adamhstewart** [comment]
conumption per month = total consumption over last six month / 6
