### ISSUE TITLE
Stock Mgmt - Correct Entry [8h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#654]
## Issue

As we are manually entering in data, we need a way for users to go in and correct any errors. We also need these to be tracked separately, rather than just updating the main entry. 

To do this, we have created the following screen: 
<img width="416" alt="Screen Shot 2023-02-07 at 3 08 49 PM" src="https://user-images.githubusercontent.com/77505464/217387822-3c179de8-6309-45a8-b5ff-2766f188a496.png">

We will log: 
- Date (can be in the past or the current day)
- How much stock was added on that date 
- How much stock was issued on that date 
- and a reason as to why the correction is needed. 

This will log as it's own line entry in the month details (for the month that = the date). Example: It's Feb 2 and I need to adjust an entry for Jan 30. That adjustment will appear on the Jan month details.

**Comment by anvmn** [comment]
@adamhstewart 

I believe following format will better suite our needs:

- Selection - stock added / deducted.
- Number input 
- Date
- Reason selection - should be dynamic, according to added/deducted selection.

Also, this should follow same pattern of Receive Stock:
1. Make sure person who's logged in, is the one performing the operation.
2. Signature.

**Comment by adamhstewart** [comment]
@anvmn agree to the above, except:

> How much stock was issued on that date

This should not be an adjustment... issued stock is only through FBF.

**Comment by anvmn** [comment]
@adamhstewart
should be an option to add to stock here, or not?
