### ISSUE TITLE
Health Center - Group Encounters

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#671]
## Issue 
We need to streamline the flow of the group encounter entry flow at the health center. Upon investigating, we just need to remove one screen in the design and change a button color -  but some other changes need to happen on the back end. 

1. remove the "attendance" screen 
<img width="1439" alt="Screen Shot 2023-03-12 at 8 45 36 PM" src="https://user-images.githubusercontent.com/77505464/224603668-de12c3a6-f715-4d79-b433-a85f9892c33d.png">

@anvmn since we are just bypassing this one screen and going directly to the next (shown below), I don't think you need a design but let me know if you do. 
<img width="444" alt="Screen Shot 2023-03-12 at 8 50 18 PM" src="https://user-images.githubusercontent.com/77505464/224604074-f01e5425-bb03-41e5-ad67-4cd486749a90.png">

2.  When a group encounter is selected it will start and end on the same day. Currently, it can span multiple days. The nurses will just have several encounters for a group now. This means that now if 10 children are seen on Monday the 5th and 17 seen on Tuesday the 6th but they are all the same type of group - they will be marked as being seen on the correct date. Why? - (1) this makes more sense in general to know exactly what date a child was seen (2) there is an issue with encounters not being closed properly or in a timely manner.

3. This may affect reporting. @adamhstewart is investigating that. 

4. Change the color of the "End Encounter" Button. We are changing it to the E-Heza green so that it contrasts more with the blue background - hopefully this stands out more to users so they remember to close the encounter. 
<img width="232" alt="Screen Shot 2023-03-12 at 9 01 08 PM" src="https://user-images.githubusercontent.com/77505464/224605323-477cfac2-2152-4ea5-b22f-28508a48427e.png">

**Comment by jeanette-pelizzon** [comment]
Some additional notes: 
- We are getting rid of end date 
- they need to open a new encounter each day, even if it's in the same group 
- only need to see encountered within the last month that are still open 
- report should be looking at children this month

**Comment by anvmn** [comment]
@LudmilaGoichman please test on QA env

**Comment by LudmilaGoichman** [comment]
@anvmn @adamhstewart 

- https://qa-ihangane.pantheonsite.io/app
- tablet

### Question:
1. Where can I check these requirements?

>- only need to see encountered within the last month that are still open
>- report should be looking at children this month

### Checked and Approved:
1. The screen with dates of group encounters has been removed
2. "End Encounter" button is green

Examples:

Nurse, PMTCT program:

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/586f13f8-4b9d-45a7-b6a3-445484f7d0da">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/73555c36-9d54-4b02-95d0-2096c543e81e">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/a3417524-7740-4be8-976d-d17119e8055c">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c5a2deb4-a2ca-4c5b-8adc-f1e2bf403f72">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/9e5936db-3a82-4de7-964c-0d07b4045825">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/27b35bf8-be66-4d12-8550-bdc1436b1ba6">
---|---|---|---|---|---

Nurse, FBF program:

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e101672e-850d-4fa6-b5c5-8d3b18afd0d4">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/adccca7f-4719-4fea-a18b-db742ebf9847">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7d01437a-4b81-4760-bc56-6f0311ce901e">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/0e88c8b3-0d2d-405f-a64d-1ad56284552a">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/f5dd3ffe-5f1c-4442-9071-e5eecad83cee">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/c4dc287c-468e-400a-ab77-397e9421c88b">
---|---|---|---|---|---

CHW

<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/d7b238f0-1cd9-4c04-b506-a98bb6b49aa2">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/8bc2e229-47e4-49de-87b4-3e211df2bbb3">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/740c98bc-bb8b-44aa-aceb-59c1ca9d4683">|<img width="355" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/41c1c92e-d9f6-4720-90b7-aaade631fd91">
---|---|---|---|

3.  a new encounter will be open each day, even if it's in the same group

<img width="766" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/78ee8b99-1cfe-473c-ae07-bc845a448209">

**Comment by isapisa** [comment]
> 1. Where can I check these requirements?
> 
> > * only need to see encountered within the last month that are still open
> > * report should be looking at children this month

@adamhstewart ^^
