### ISSUE TITLE
Resilience Messaging - Nested Entry [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#674]
## Issue 

There has been a request to nest the messaging feature within the wellbeing activity. There will be more wellbeing activities added in the future. The user will click into wellbeing and then have to click into messaging specifically. For now this will feel like extra clicks but will make more sense once the extra activities are added in the future. I have added the unread messaging alert to both the main wellbeing icon and the messaging button to ensure the user doesn't miss any messages. 

<img width="685" alt="Screen Shot 2023-03-19 at 7 16 26 PM" src="https://user-images.githubusercontent.com/77505464/226231840-f272aa85-d27e-43da-94f1-b300f8a928df.png">

## To Do: 
- Create a second screen with the button to enter into messaging

**Comment by Diama1** [comment]
@jeanette-pelizzon I would like to ask, When does the surveys come in after we click on wellbeing or the messaging?

**Comment by jeanette-pelizzon** [comment]
I will have to defer to @adamhstewart on this one. I think that the team wanted them separate in wellbeing but I am not sure anymore.

**Comment by Diama1** [comment]
@adamhstewart From the last meeting I had with the Hope team, they suggested that instead of putting the name messing on the button but we name it **Resilience Message** This is because wellBeing as a program will have different sub-programs
