### ISSUE TITLE
NCDA -  Aggregated Scorecard - Village - Infrastructure

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#675]
## Issue 

As part of the second phase of the NCDA project, we are building out aggregated scorecards. We already have individual child scorecards. We will build out two other versions - Cell/District/Sector and Village. 

This is the **village** scorecard. 

This is designed for desktop/laptop - per Neilsen Norman guidelines it's optimized to 1024 x 768.

Instead of having the child's age across the top it will have months of the year. We have added in a section about Demographics. The rest of the sections are the same as the individual child scorecard. 

The way these scorecards are measured is different than the individual. We will create separate tickets for that. This ticket is for infrastructure only. 

Link to [Figma](https://www.figma.com/file/l0bvoD2VyyFc146VVIYWOQ/NCDA?node-id=416-2469&t=EHHHAnwZ2JT4nCgH-0) since the image is kind of hard to see the details. 

![NCDA - Village](https://user-images.githubusercontent.com/77505464/232351029-c4a2425d-c6b0-484e-aceb-3e7b33b070a4.jpg)

**Comment by jeanette-pelizzon** [comment]
@adamhstewart updated per our most recent convos.

**Comment by Diama1** [comment]
@jeanette-pelizzon @adamhstewart Based on the conversion we had last time on scrum, on Low birth weight, we were asked to have 2 rows the one with the number of children that were born with Low birth weight and the one with number of children that were not born with low birth weight.

**Comment by anvmn** [comment]
Discussed this with @adamhstewart, and the decision is not to add another row.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
