### ISSUE TITLE
ANC @ Health Center - Add Malaria Prevention and Medication as Activities [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#68]
### Issue 
The activity "Patient Provisions" is being removed completely from ANC. "Malaria Prevention" and "Medication" are moving from sub-activities to activities in the main tray. 

<img width="610" alt="Screenshot 2021-11-26 at 10 16 22" src="https://user-images.githubusercontent.com/34378755/143556759-81ca8270-1f06-4fbe-a797-1c88755dbbb2.png">

**Malaria Prevention** should have the question that is currently under `Patient Provisions` > `Resources` sub-activity.
**Medication** should have the questions that are currently under `Patient Provisions` > `Medication` sub-activity.

The current logic for sub-sequent encounters should remain the same.

### Assets

https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=292%3A5188

### To Do

- Create medication activity
- Create Malaria Prevention activity
- Adjust to keep current logic for sub enc.
- Order in main activity tray per design

**Comment by anvmn** [comment]
@isapisa 

Being implemented at https://github.com/TIP-Global-Health/eheza-app/pull/16

**Comment by LudmilaGoichman** [comment]
@isapisa @anvmn 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet

### Found Issue/Question:
1. the Icon isn't displayed:
<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145425933-36f82628-ad25-476f-ab0a-751c8ca42858.png">

2. is the following statement correct? Question `Has the mother received iron and folic acid supplement?` appear in all encounters/subsequent encounters. If not, then we have an issue

### Checked and Approved:
1. medication activity has been created
2. Malaria Prevent has been created
3. The activity "Patient Provisions" was removed completely from ANC. "Malaria Prevention" and "Medication" have been moved from sub-activities to activities
4. activities main activity tray are ordered  per design

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145414605-8b55b383-1332-4d41-bb79-dbba8612840c.png">
ion activity has been created

5. Malaria Prevention has the question that was under Patient Provisions > Resources sub-activity.

<img width="365" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/145419171-1382d966-aea7-4b35-b5d8-0046d7dc0dcd.png">

6. Medication has the question that was under Patient Provisions > Medication sub-activity:

<img width="365" alt="Notification_Center" src="https://user-images.githubusercontent.com/35059802/145419090-16ca32f0-2a88-473c-b891-09790b64385a.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145424485-ee2ae946-0be7-40f2-920f-498e415ec2d8.png">
---|---

7. The logic for sub-sequent encounters for Malaria Prevention:

- if the answer is yes, then the activity with this question will not appear in the next encounter

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145432955-c708318d-1dc6-48cb-9f7a-7316327679a3.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145433079-1eb9adb3-eee0-4568-bcfc-1f65563c9912.png">


- if the answer is no, then the activity with this question will appear in the next encounter again

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145432715-c7c1bee5-8761-4827-94f3-2a2e8fe81652.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145432999-d7eeec06-9045-42f1-89b9-adfe3eb70284.png">
---|---

8. The logic for sub-sequent encounters for Medication:

- question `Has the mother received deworming pill?` appears starting EGA week 20

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145436436-f48ece47-79b6-421c-a996-bd323f7c340c.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145436503-6be8bd4f-a0b5-4c53-b691-1edfcee4c1c9.png">
---|---

- if the answer to `Has the mother received deworming pill?`question is yes, then this question will not appear in the next encounter
- if the answer to `Has the mother received deworming pill?`question is no, then this question will appear in the next encounter again
- question `Has the mother received iron and folic acid supplement?` appear in all encounters

Examples:

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145433662-cd306d85-8d75-482f-bd67-42190e5be9d2.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145434171-366ea5e6-732c-4aa7-80b0-e46acafabc5d.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145434218-c9aa46c1-c65d-4214-9518-3691baee4f7d.png">
---|---|---

<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145433797-002786a5-6ba3-4a90-93d6-c897460b0419.png">|<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/145434081-6b79a994-616c-4363-bcec-eb4251a80408.png">
---|---

**Comment by isapisa** [comment]
> is the following statement correct? Question Has the mother received iron and folic acid supplement? appear in all encounters/subsequent encounters. If not, then we have an issue

@LudmilaGoichman yes it is. It's the same logic as we have at CHW.

> the Icon isn't displayed:

@Diama1 assigning you to fix as a follow-up

**Comment by anvmn** [comment]
@isapisa 

> the Icon isn't displayed:

Fixed at https://github.com/TIP-Global-Health/eheza-app/pull/2/commits/4f9180bd8c2d3a8d2c5e2ee71b8cddabc8662457

**Comment by anvmn** [comment]
@LudmilaGoichman 
Please retest on Nutrition env.

**Comment by LudmilaGoichman** [comment]
@isapisa @anvmn 

- https://nutrition-ihangane.pantheonsite.io/app
- tablet

### Checked and Approved:
1. the Icon is displayed:
<img width="365" alt="Test2_-_Google_Drive" src="https://user-images.githubusercontent.com/35059802/148037834-39ef4246-4ac2-4b7a-a018-947961505799.png">
