### ISSUE TITLE
NCDA - Aggregated Scorecard - Demographics [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#687]
## Issue 

 **Children Under 2** 
- Any child seen that is under 24 months old 

**Number of Newborns in This Month** 
- number of children born within this month/year
- Only appears on district/sector/cell

**Low Birth Weight**
- Children born this month/year that had a birth weight in the red 
- Only appears on district/sector/cell

**Comment by anvmn** [comment]
Replced by #708 and #710. Closing.
