### ISSUE TITLE
NCDA - Aggregated Scorecard: Acute Malnutrition pane (data + presentation) [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#688]
![Selection_1857](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/540f04f3-3d95-431d-b1d8-2840c754f20e)

**Severe Acute Malnutrition**
- Number of children seen with severe acute malnutrition this month/year 

**Moderate Acute Malnutrition** 
- Number of children seen with moderate acute malnutrition this month/year

**Good Nutrition** 
 - Number of children seen without a nutrition issue this month/year

**Comment by anvmn** [comment]
@adamhstewart 

How do we define Severe/Moderate Acute Malnutrition, and Good Nutrition?

**Comment by anvmn** [comment]
**Definition**:

Malnutrition occurs when one of 4 Nutrition criterias is off.
Severity is determined by most severe of conditions.
So, if we got:
 - Stunting = Moderate
 - Underweigth = No
 - Wasting = Severe
 - MUAC = Moderate

Malnutrituin is SEVERE.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
