### ISSUE TITLE
Stock Mgmt - Translations for the Feature

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#691]
## Issue
Adding translations for Stock Management feature

## Tasks
- List texts that need translations for the team to add translations
- Add translations in the app

**Comment by anvmn** [comment]
@Diama1 is this done?

**Comment by Diama1** [comment]
> @Diama1 is this done?

@anvmn not yet, I can push the clinical team to give me the rest of the translation
