### ISSUE TITLE
NCDA - Toggle - %/#

### ISSUE THREAD

**Issue by jeanette-p** [TIP-Global-Health/eheza-app#693]
## Issue 
On the aggregated scorecards, the user needs the ability to toggle between a view that shows the inputs in percentages and a view that shows the inputs in numbers. This is a requirement for their reporting. 

![NCDA - District - Sector - Cell](https://user-images.githubusercontent.com/130944788/233879235-3f7340ee-0b9d-484d-9630-98addb7cbd05.jpg)

**Comment by anvmn** [comment]
@adamhstewart 

In order to implement this, we need a definition of the denominator for each row of each pane.
After we have it, we can estimate the effort.

**Comment by anvmn** [comment]
The decision is to use the 'Children under 2' as denominatior for all row.
May need to revise for some of the rows latter.

**Comment by anvmn** [comment]
@adamhstewart 


> The decision is to use the 'Children under 2' as denominatior for all row. May need to revise for some of the rows latter.

Applied this on all panes, besides Demographics.
On Demographics pane:
 - Children under 2 - numbers, no matter if # or % is selected.
 - Newborns - uses Children under 2 as denominator.
 - Low birth weight - uses Newborns as denominator.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
