### ISSUE TITLE
NCDA - Aggregated Scorecard - Dropdown

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#694]
## Issue 

The user needs a way to move between the district-sector-cell scorecard and the village scorecard. We are doing this via a dropdown in the top left corner. Drop down options are village and district-sector-cell. 

![NCDA - District - Sector - Cell](https://user-images.githubusercontent.com/77505464/233879561-6b05f52e-9ec2-452f-9e4f-0d8223666850.jpg)

**Comment by anvmn** [comment]
Not relevant for selected implementation. Closing.
