### ISSUE TITLE
Feature: Patient Record

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#71]
## Feature Description

This feature allows healthcare professionals to easily access patient progress reports and records without having to begin an encounter to do so. From the main patient screen, a healthcare professional will easily be able to select which progress report they would like to view, as well as the information for any related children to an adult. 

Progress reports supported: 
- Acute Illness 
- Antenatal 
- Standard Pediatric 
- Demographics

The feature also includes new screens to select a specific pregnancy or acute illness incident in the past. 

## Design Assets
- Patient Record - located at the top of [this figma page](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=470%3A5237)

## [Personas](https://tip-global-health.github.io/eheza-documentation/research_docs/personas-workflows/)
- Nurse
- CHW

### Nurse Story
As a Nurse at a Health Center seeing a variety of patients every day, I need a way to easily access a patients history so that I can be more aware of any past health issues that may continue to affect them, review historical data with the patient, and ensure proper care. 

### CHW Story
As a CHW I often refer my patients to health centers for further care. I need a way to easily access my patient's history so I can see what treatment was provided at the health center, test results, and general patient progress so I can better support them. 

## Tracked Issues (Updated): 
**General**
- #102
- #103 
- #72
- #92
- #88 
- #89 
- #77 
- #76 

**Acute Illness** 
- #73
- #93 
- #94 
- #95

**Antenatal** 
- #74 
- #96
- #98 
- #91

**Pediatric** 
- #75
- #97

**Comment by jeanette-pelizzon** [comment]
Quick video walkthrough can be found [here](https://www.loom.com/share/383f6a1aa4ba441d94e1ee3ca0126fde)

**Comment by isapisa** [comment]
@jeanette-pelizzon 

some immediate questions/comments that pop up:
- Is there is a differentiation between "closed" and "open" records on the individual reports page?
- https://github.com/TIP-Global-Health/eheza-app/issues/73 should be 4 issues:
  1. Listing children 
  1. Overview page (resolved, ongoing)
  1. Display individual report
  1. Begin an encounter (I see this is already a [separate issue](https://github.com/TIP-Global-Health/eheza-app/issues/76, so it can just be referenced). 
- Same applies to https://github.com/TIP-Global-Health/eheza-app/issues/74 and https://github.com/TIP-Global-Health/eheza-app/issues/75 ^^
- Logic for navigating back and forth can be 1 issue for all
- The antenatal progress report and the demographic reports have design changes. Those should be each 1 issue. The logic for displaying them as part of patient records is missing for https://github.com/TIP-Global-Health/eheza-app/issues/77
