### ISSUE TITLE
NCDA CHW Questionnaire - Nutrition Behavior [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#747]
## Issue

The nutrition behavior screen records information about the child's feeding and eating habits.

<img width="297" alt="NCDA_–_Figma" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/011955bd-a944-4889-b776-f5b9453712d4">

## Tasks
- Render the frontend page as design
- Implement the following logic:
    - the second question is age dependent and follows the same logic as https://github.com/TIP-Global-Health/eheza-app/issues/534

**Comment by Diama1** [comment]
@anvmn @adamhstewart 
|  Question       |     Counseling    |
|  ---------------     |   -------------------- |
|  Feed your young child complementary foods 3 to 4 times a day | Provide counseling on the consequences of not feeding the child complementary food at the appropriate times, as per the guidance. |
| Does the child receive food items from the 5 food groups? |  Provide counseling on how the mother can combine different food items based on the one they have in their area.|
| Appropriate complementary feeding (6-24 months) | Provide counseling on the importance of complementary feeding and using example show them some food item that can be easy to find in their area. |
| Breastfed baby for 6 months without interruption | Provide counseling on the importance of breastfeeding a baby for 6 months without interruption. |

**Comment by anvmn** [comment]
@adamhstewart 

Checked this against original NCDA implementtion, and the requirements here are not alligned.
Specially, after https://github.com/TIP-Global-Health/eheza-app/issues/757.

What we have at orginal NCDA:

- `Does the child receive food items from the 5 food groups` appears always.
- `Breastfed baby for 6 months without interruption` appears only when child is 6 to 7 months old.
- `Appropriate complementary feeding (6-24 months)` appears when child is 7 month old or more.
- `Feed your young child complementary foods 2 to 3 times a day` - 6 to 8 moinths old.
- `Feed your young child complementary foods 3 to 4 times a day` - 9 to 11 months old.
- `Feed your young child complementary foods at least 5 times a day` - 12 months and older.

Please advice how this should look for the new mode.

Also, note that with current implementation (of new mode), there are 0 questions for child younger than  6 months.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
