### ISSUE TITLE
NCDA CHW Questionnaire - Infrastructure & Environment [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#749]
## Issue

The infrastructure and environment screen records information about the child's home as it relates to health and nutrition.

<img width="291" alt="NCDA_–_Figma" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/ffaeedc6-ca2c-4b54-ba87-df6814c11873">

## Tasks
- render the frontend page as designed
- there is no conditional logic to this page.

**Comment by Diama1** [comment]
@adamhstewart as we discussed, on all the negatives (where the answer is no) there should be counseling

**Comment by Diama1** [comment]
@anvmn @adamhstewart 
|  Question       |     Counseling    |
|  ---------------     |   -------------------- |
|  Does the house have clean water? | Provide counseling on how to prepare clean water like boiling it and using water purifier. |
|Does the house have a handwashing facility? |  Provide counseling on the importance of handwashing facility, and tell them to buy it  and use it. If they don't have means advocate for them.|
| Does the household have toilets? | Provide counseling by telling them to build toilets. If they don't have means advocate for them. |
| Does the house have a kitchen garden?|Provide counseling on the importance  of eating fruits and vegetables from kitchen garden. And tell them to build one. If they don't have means advocate for them. |
| Is the mother using the insecticide-treated bednets ? | Provide counseling on the importance of using the insecticide-treated bednets and advise them to have one. |

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
