### ISSUE TITLE
NCDA Correct the condition on Nutrition Behavior

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#757]
## Issue
Children under 6 months will only have one question about breastfeeding(Because they haven't started solid food yet).
## TODO
- Correct the condition as per request

**Comment by anvmn** [comment]
@Diama1 @adamhstewart 

Don't know why this change was required, but the original logic was implemented similar to what we have at individual NCDA activities.
As I see it, it should be similar across all NCDA activities.
