### ISSUE TITLE
Patient Record - Demographic Report [3h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#77]
## Issue 

For adult female patients, demographic information is available. This is basically their general information. For the patient record, we have altered the design of the demographic report to be more in line with the other progress reports. There are no more floating backgrounds and greyed-out backgrounds. The overall feel is cleaner and more in line with other aspects of the app that have been developed over the last year. 

![ANC - Tasks](https://user-images.githubusercontent.com/77505464/147020725-2770d67d-1b27-4613-b5b4-5a77c3c5e119.jpg)

## Tasks: 
- update style per design

**Comment by jeanette-pelizzon** [comment]
@anvmn this is the issue for the demographic report styling

**Comment by adamhstewart** [comment]
@anvmn @jeanette-pelizzon should the demographic tab lose the menu context like this:

https://www.loom.com/share/ef3e4d2ab7b44f4bae60a4251c65f023

It seems the tab should stay, but I understand that all other tabs have a sort of "landing" page with limited information before loading the full report.

**Comment by adamhstewart** [comment]
@jeanette-pelizzon after further review and according to this [demo](https://www.loom.com/share/383f6a1aa4ba441d94e1ee3ca0126fde), the implementation is correct.
