### ISSUE TITLE
NCDA CHW Questionnaire - immunisation history

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#780]
~~Todo: Define the architecture using which CHW will have a way to update vactinations thate were performed.~~

**Tasks:**

1. Turn Child Scoreboard encounter into multiactivity encounter (Encounter page with activities + Activity page for each activity), with 2 activites - Child Scorecard (displayed always) and Vaccination History (optional).
2. If child is behind on vaccinations, and responds that there are vaccines to record, display Vaccination History activity. It will have up to 7 tasks (for each of vaccines child is behind on).
![Selection_2065](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/5677d1ef-c962-46cd-afa0-b12a7c75c22f)

3. Vaccination History task form will behave similar to vaccination form at SPV encounter. Only difference is that it will not present a question about giving a shot today.
4. Vaccination History activity is to be accounted for at logic that generates vaccination progress data structure for child.

**Comment by anvmn** [comment]
@adamhstewart ^^

**Comment by adamhstewart** [comment]
@anvmn please check child Adeo Emmy on the nutrition environment. We did an encounter with him and update his vaccin records to be up to date. The scorecard shows that he is behind and there are no vaccines shown in the progress report.

**Comment by anvmn** [comment]
@adamhstewart 

> @anvmn please check child Adeo Emmy on the nutrition environment. We did an encounter with him and update his vaccin records to be up to date. The scorecard shows that he is behind and there are no vaccines shown in the progress report.

Managed to reproduce the issue locally.
The problem here is that current implementation relies on existence of at least one SPV encounter.
If there's such an encounter, it's able t generate vaccination data from both sources - SPV and Child Scoreboard data.
However, if there're no SPV encounters, it assumes there were no vaccinations, which is not correct.

I'll modify the logic to take into account a scenario where there were no SPV encounters, but Child Scoreboard took place.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
