### ISSUE TITLE
NCDA CHW Questionnaire - changes at Universal Interventions task [3h]

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#783]
Per https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1875508788

**Tasks:**

- Behind on vaccinations input is not to be shown at HC:

![Selection_2076](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/369e3478-9ffd-4600-a8a7-237502349fb4)

- Replace the food supplementation input with Onegra-MNP question(s).
Note: At HC, do not ask the follow up question.

![Selection_2074](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/5162257c-44d0-412d-ac41-e6f1b452cfc0)

![Selection_2075](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/3a9f83e2-d21b-4f8c-a4c4-94810141f4ff)

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
