### ISSUE TITLE
NCDA CHW Questionnaire - changes at Targeted Interventions task [2h]

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#784]
Per https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1875508788

**Task**

- Add the FBF questions - **only for NCDA activity at Child Scoreboard encounter.**
![Screenshot from 2023-07-14 16-07-26](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/7af3d0cf-5ea6-4da9-9b8e-5a1a9ff9cd6a)

- Do not show following 2 questions at HC:

![Selection_2073](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/a3fb6eb1-0c23-47e4-a56c-fc934f0ed397)

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
