### ISSUE TITLE
NCDA Questionnaire - Nutrition Behavior questionnaire changes [5h]

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#785]
Tasks:

1. Task is to become optional - show for children that are 6 months old and above
2. All existing questions are to be replaced by new ones:

![Selection_2077](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/9faaa634-5d7c-44d8-bee8-03373673d116)

3. Breastfeeding question should not appear if was already answered previously.

**Comment by anvmn** [comment]
@adamhstewart 

Please provide design for helper tables we need to show for questions 3 and 4.
FYI, this is the helper we got for question 1:

![Peek 2023-07-17 15-14](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/4f3bd59d-044f-48d4-9624-de73b78ae731)

**Comment by adamhstewart** [comment]
@Diama1 We need tooltip text for both:

> Does the child receive appropriate complementary feeding?
> Does the child eats at the recommended times per day?

Needs to be provided today to be incorporated into release.

**Comment by Diama1** [comment]
@adamhstewart 

**Does the child receive appropriate complementary feeding?** this question doesn't have the tooltip text

**Does the child eats at the recommended times per day?**
Ask and check if the daily frequency of the complementary food is enough
- A child between 6 to 9 months, Feed him/her complementary foods 2- 3 times a day

- A child between 9 to 12 months, Feed him/her complementary foods 3- 4 times a day. 

- A child between 12 to 12 months, Feed him/her complementary foods at least 5 times a day.

**Comment by adamhstewart** [comment]
@Diama1 ok thanks. I guess I was confused because “complementary feeding” is in the helper text for the “times per day” question. 

Clear now.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
