### ISSUE TITLE
NCDA Questionnaire - Fix typo on Infrastructure & environment task

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#786]
**Task**
- Fix a typo on guidance "**Build**"
![Screenshot from 2023-07-14 17-04-52](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/07f8a5f9-cf3d-48cc-8a9e-bb005d1d201e)

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
