### ISSUE TITLE
NCDA CHW Questionnaire - changes at Antenatal Care task [1h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#788]
Per https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1875508788:

At HC we should not be showing follow up question for `Did the mother receive Iron, Folic Acid/MMS?`.

![Selection_2070](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/ac7ee4d2-a55d-450e-9a91-30f873056e13)

**Comment by adamhstewart** [comment]
@anvmn one follow-up change: we will remove any logic before the first question - that is, the CHW should always be sown the previous visits and be asked "Is this is correct?"

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
