### ISSUE TITLE
NCDA CHW Questionnaire - update scorecard mapping [8h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#790]
https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit#gid=1875508788, per `Mapping Logic` and `Map to Scorecard` columns.

**Comment by anvmn** [comment]
@adamhstewart 

![Selection_2079](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/98f40445-8741-4eec-a67e-6b3f8fe7c346)

Folic Acid question is asked only once.
If asked by CHW, we'll be able to map answers to greed/red indicators, as we'll have follow up question, if needed..
If asked by Nurse, we have only first question asked. So we'll know if mother received Folic Acid or not, but if she did, we don't really know if she took it. In this case, per current requirements, scorecard will show red indicators. 
Is this correct behavior?

**Comment by adamhstewart** [comment]
@anvmn yes, that is the correct behavior - only a positive indication of adherence from the CHW is a green checkmark.

This adherence question, though, should be asked every time, though. That possibly is not clear from the spreadsheet, so I'll make a note.

**Comment by anvmn** [comment]
@adamhstewart 

> yes, that is the correct behavior - only a positive indication of adherence from the CHW is a green checkmark.

I'm talking here not about situation of positive, but false negative. That is, presenting negative indicator, when we don't really know if supplement was consumed ot not.

> This adherence question, though, should be asked every time, though. That possibly is not clear from the spreadsheet, so I'll make a note.

Not really get why. It's mapped to Iron **during pregnancy** on scorecard, and if answer was given once, I don't see why it should be asked ever again (similar to number of ANC visits question).

**Comment by anvmn** [comment]
Maybe the solution could be making nurse question behave in similar matter as chw?

**Comment by adamhstewart** [comment]
> Not really get why. It's mapped to Iron during pregnancy on scorecard,

Because adherence is an ongoing issue - so it's not mapped during pregnancy, only by adherence.

> Maybe the solution could be making nurse question behave in similar matter as chw?

no, because at the nurse, we only want to know that they received it - at the CHW, we want to know that they received it and are taking it.

> That is, presenting negative indicator, when we don't really know if supplement was consumed ot not.

o I think the real clarification is that the Nurse encounter isn't mapped at all - as we really only want to know if it is consumed. So in the case you describe where we know the nurse gave it but there is no confirmation by the CHW (in any direction) it should be a dash (-).

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
