### ISSUE TITLE
NCDA: Update input and mapping logic for ANC enounters [8h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#796]
## Issue

Per request from NCDA we want to change the input and mapping logic of ANC encounters, so that a CHW or nurse can document missing (from E-Heza) ANC encounters in the month that they occurred and display the months in which encounters occurred on the scorecard.

Design update: https://www.figma.com/file/l0bvoD2VyyFc146VVIYWOQ/NCDA?type=design&node-id=627-3590&mode=design&t=lQbB0CSYoi667co3-0

For example, 
- if a mother had 4 visits in her pregnancy, this question would not be displayed, and the scorecard would have green checkmarks in the months in which they occurred.
- if a mother had 2 visits in her pregnancy, the nurse/CHW would be prompted to ask "Is this correct" and if "no" they would be able to add the month and year of each visit in order to complete the mapping.

<img width="456" alt="NCDA_–_Figma" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/8c61ccd6-b3ab-4653-8f74-75fc8e4e212c">

Instead of the current mapping method, we will show 
- green checkmarks in each of the months in which there was an encounter if there were 4 or more total encounters
- red checkmarks in each of the months in which there was an encounter if there were less than 4 encounters
- dashes in any month with no encounter

<img width="902" alt="NCDA_–_Figma" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/647d82fd-d59b-4712-bcef-f190470fd07e">

## Tasks
- Change the wording of the initial question and list the dates of the visits that are recorded in E-Heza
- Change the "How many visits" question to a date selector that will allow multiple values to be added (as many encounters that need to be added)
- Change the mapping logic to show the month in the pregnancy that the mother that the encounters occured.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
