### ISSUE TITLE
[META] Multisite support - adding Burundi as a localization [22h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#798]
For each new country that is being added, we'll have separate site on Pantheon.
The code will remain unified (`https://github.com/TIP-Global-Health/eheza-app/` repo), 
but we should be able to support bahavoural differences. This can be done using additional configuration at front-end Config file.

**Comment by anvmn** [comment]
**Issues:**

1. Add configuration for site determination.
This will alsol require new repo, similar to [ihangane-infra](https://github.com/Gizra/ihangane-infra/) with properly set `Config.Deploy.elm`.

2. Language: 
  - Extend langauges set with new language.
  - Update language switcher - language label + country flag.
  - Add new language to all translation sets at `Translate.elm`.
  - Add actual translations for all words and phrases.

3. Demographics hierarchy:
- Generate dictionaries for the hierarchy
- Based on site param, use coresponding set of dictionaries.

~~4. Update default content migration to have generic names and labels.~~

5. The `Ubudehe` field appears at multiple locationions. Breakdown bellow.

~~6. Update patients import logics per site specific fields on person content type.~~

7. Wording at `Translate.elm` (specific mentions of Rwanda):

![Selection_2097](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/5dc3509f-bba9-488a-a44f-200bf0d31e56)
![Selection_2098](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/043608e7-eb15-4321-bb04-2ce95404de79)
![Selection_2099](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/c899b9ca-f96f-4e92-a944-380bb7e6fa1e)


8. `CountryCodeRwanda` related logic at WhatsApp feature. For example:

![Selection_2092](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/83ed14db-406d-49a2-891d-2bbb9922ea1b)

**Comment by anvmn** [comment]
**Ubudehe breakdown:**

 - Person form (not marked as required on back-end, but it is required on create/edit form).
 - Nurse - field on content type, value is set during Resilience kick off survey.
 - Resilience kick off survey - ubudehe question for Nurse.
 - Mother Fbf - logic for distribution (ubudehe 1 or 2  receive Fbf, others do not).
 - Mother group activities - info at mother card:
![Selection_2250](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/bafdcbe2-5a5b-4c0e-a4c3-1304eb8360ca)

- Patient record - info at adult card:
![Selection_2251](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/f7c70092-fa5f-4420-8933-c9eacd61984f)

- Prenatal Demographics report - at family info:
![Selection_2252](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/1b2a5e98-b8e3-49c2-b010-6efbf6ebd55f)

- Child scorecard - at identification pane:
![Selection_2253](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/7c287892-0bd2-4fc1-8464-805015bcf782)

**Comment by anvmn** [comment]
@adamhstewart 

Opened a [follow up issue](https://github.com/TIP-Global-Health/eheza-app/issues/871) which lists remaining tasks we need to handle.

**Comment by balagan73** [comment]
## QA Review

### Found issues and Questions

1. Not sure about the Ubudehe system. Do we have Ubudehe in Burundi too?

### Checked and approved:

1. Language switcher and country flag is updated
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/25aaa7b0-23a4-4374-9ab3-dcc0bcd2f81d)

2. Text is localized
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/cf4b2d26-b88e-4737-af32-9815fd8009a0)

3. No Ubudehe, but Georgraphic informations display on registratoin form
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/28afdf14-95ce-4540-a30b-607a011aa32c)

4. No Ubudehe displays on patient record:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/272ea49a-81d4-4ff0-b371-7750cf68e4c7)


5. No Rwanda specific text displays
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/3abd82ed-3a88-4503-869e-b4445d22c16b)
