### ISSUE TITLE
NCDA - Tab for Viewing Child Scorecard during/after scorecard visit [8h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#810]
## Issue

There will be an additional "Child Scorecard" tab on the scorecard encounter screens to directly access the scorecard.

<img width="287" alt="Cursor_and_NCDA_–_Figma" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/fb75f809-cc34-42cd-9141-1169327b6a59">

## Tasks
- Create the new page and 
- render the scorecard on the page
- Add "end encounter" button on the page

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
