### ISSUE TITLE
NCDA Additional Question: Vitamin A [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#819]
## Issue 
New questions under Universal Intervention: 

Did the child receive Vitamin A in the last six months?

(If yes): Is the Vitamin A being consumed?

(If no, provide guidance)

Guidance: 
Provide counseling on the importance of Vitamin A advise them to go to the Health center to recieve it.

For mapping lgic and scorecard indicators see [NCDA Analysis](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit?usp=sharing&ouid=104843215453637480834&rtpof=true&sd=true) Line 7

## Tasks
- Create new questions and logic
- wire to backend
- map logic to child scorecard

**Comment by anvmn** [comment]
@adamhstewart 

Since child receives Vitamin A only after turning 6 monts old, it would make sense to not show this question before child got to that age.

**Comment by anvmn** [comment]
@adamhstewart 

Consider following scenario:

At NCDA activity, patient reported of receiving and taking Vitamin A on months 10 and 14.

Per the mappign at requirements:
![Selection_2151](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/369e9238-1be7-4bde-ad17-d0d2cc480663)

We get following entries:

![Selection_2152](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/ee10de14-3ebb-4a04-b7a0-576beed30cda)

Is this the desired result?

**Comment by Diama1** [comment]
### Translations
| Phrase | Translations |
| -----------| ------------------|
| Did the child receive Vitamin A in the last six months? |Mu mezi atandatu ashize, umwana yahawe ikinini cya vitamini A? |
| Is the Vitamin A being consumed | Vitamini yayifashe neza? |
| Provide counseling on the importance of Vitamin A and advise them not to miss it again. | Gira inama umubyeyi ku  kamaro ko gufata ikinini cya vitamini A unamugire inama yo kutongera gucikanwa.|

**Comment by adamhstewart** [comment]
@anvmn let’s than change the question to 

“Did the child receive Vitamin A in the last six months”
 And the logic to: a green check in every month the answer is yes to both questions.- a dash in every month prior to 6 mos of age (unless child has received and consumed Vitamin A) 
 
We do not need l’ogive to remove the question at any age.

**Comment by Diama1** [comment]
@adamhstewart What about the child who is younger than 6 months since they start taking the Vitamin at 6 months

**Comment by Diama1** [comment]
> @adamhstewart What about the child who is younger than 6 months since they start taking the Vitamin at 6 months

I think I got it in the comment

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
