### ISSUE TITLE
NCDA - Additional Question: Deworming [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#820]
## Issue 

Did the child receive deworming medication?

(If yes): Is the deworming medication being consumed?

(If no, provide guidance)

Guidance: 
Provide counseling on the importance of deworming medication and advise them to go to the Health Center to receive it.

For mapping logic and scorecard indicators, see [NCDA Analysis](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit?usp=sharing&ouid=104843215453637480834&rtpof=true&sd=true) Line 8

## Tasks
- Create new questions and logic
- wire to backend
- map logic to child scorecard

**Comment by anvmn** [comment]
@adamhstewart 

Since child receives Deworming only after turning 12 monts old, it would make sense to not show this question before child got to that age.

**Comment by Diama1** [comment]
### Translations
| Phrase | Translations |
| -----------| ------------------|
| Did the child receive deworming medication in the last six months? | Mu mezi atandatu ashize, umwana yahawe ikinini cy’inzoka? |
| Is the deworming medication being consumed? | Ikinini cy'inzoka yagifashe neza? |
| Provide counseling on the importance of deworming medication and advise them not to miss it again. | Gira inama umubyeyi ku  kamaro ko gufata ikinini cy'inzoka unamugire inama yo kutongera gucikanwa.|

**Comment by Diama1** [comment]
@adamhstewart While I was looking at the handbook from NCDA the question on deworming they ask if the child received deworming in the last 6 months same as on Vitamin A.

**Comment by adamhstewart** [comment]
@anvmn let’s than change the question to 

“Did the child receive deworming medication in the last six months”
 And the logic to: a green check in every month the answer is yes to both questions.- a dash in every month prior to 12 mos of age (unless child has received and consumed deworming medication) 
 
We do not need  to remove the question at any age.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
