### ISSUE TITLE
NCDA - Additional Question: ECD services provided to child [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#821]
## Issue

(Do you sing lullabies, poems, and read books to your child, or play games with your child?
(If no, provide guidance)

Guidance: 
Provide counseling on the importance of brain stimulatio activities for the development of the child.

For mapping logic and scorecard indicators, see [NCDA Analysis](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit?usp=sharing&ouid=104843215453637480834&rtpof=true&sd=true) Line 10

## Tasks
- Create new questions and logic
- wire to backend
- map logic to child scorecard

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
