### ISSUE TITLE
NCDA - Change ANC Date Dialog [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#822]
## Issue

In the case that the CHW needs to be asked to correct the ANC encounter record, we will show a dialogue consisting of a timeline of the pregnancy, divided by trimester, and the opportunity to indicate in which month of pregnancy visits have occurred.

<img width="320" alt="Cursor_and_NCDA_–_Figma" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/2dca63a5-e619-4104-a2c4-14968d09ac92">

Multiple selections should be possible, and previously indicated months should be "pre-checked" in the input.

## Tasks
- Create the dialog and input
- Wire in logic for pre-filled selected months
- Reconfigure mapping to the child scorecard based on ANC encounters and additional dates provided by CHW

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
