### ISSUE TITLE
NCDA - Remove the counseling part on the question "Is the mother or the child beneficiary of cash transfer"

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#823]
### Issue
On the question "Is the mother or the child beneficiary of cash transfer e.g. NSDS, VUP?" when the answer is **no they are not beneficiaries** there are should not be counseling.

### Todo
Remove the counseling on the answer no
![Screenshot from 2023-08-05 19-39-19](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/a22ecf84-106d-46ee-b82c-b406984d676a)

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
