### ISSUE TITLE
NCDA - Fix No counseling on FBF consumption sub-question

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#839]
### Issue
On the question if FBF is being consumed there is no counseling.
### ToDo
Add counseling on FBF sub-question
![Screenshot from 2023-08-12 19-07-36](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/275cfb41-9ca4-47c6-841e-e179e7a3b4ed)

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
