### ISSUE TITLE
Rollbar integration [21h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#842]
We want to have Rollbar reporting info of client side errors, to have better understanding of the problems and ability to debug client side issues.
The idea is that once we identify an error on client, we'll be able to send proper info through Rollbar.

**Comment by amitaibu** [comment]
## Serverless

See example [here](https://github.com/Gizra/circuit-bid/tree/master/serverless)

Quick overview of the app:

1. We're using ExpressJS to create a simple router that accepts only [`POST` requests](https://github.com/Gizra/circuit-bid/blob/d410258736aed2296b16e6a4f9c51144430d4c05/serverless/index.js#L21)
2. Doing a bunch of [validations](https://github.com/Gizra/circuit-bid/blob/d410258736aed2296b16e6a4f9c51144430d4c05/serverless/index.js#L30-L34)
3. Loading the correct API public/ private key based on the `env`.
4. Send the message to the other service. On the [example](https://github.com/Gizra/circuit-bid/blob/d410258736aed2296b16e6a4f9c51144430d4c05/serverless/index.js#L115) it's Pusher, but in this case it will be rollbar, using their [own SDK](https://docs.rollbar.com/docs/nodejs)
5. Finally, [result with `200`](https://github.com/Gizra/circuit-bid/blob/d410258736aed2296b16e6a4f9c51144430d4c05/serverless/index.js#L117) to the client side.

## Elm

What I imagine is that upon Sync, if there's a [decoder error](https://github.com/TIP-Global-Health/eheza-app/blob/main/client/src/elm/SyncManager/Decoder.elm) we would send a message to the serverless. Client side could be smart enough not to send the exact same error twice.

Deciding which decoder error and what error to send, is likely the chalenging part. Let's start with one use case example. Maybe  the one where there are no matcing `shard_changes` to a measurement change?

It can be a valuable feature to help with proactive and quicker troubleshooting. @anvmn what do you think about this estimation?

- Serverless code - 5h
- Deploy serverless - 2h
- Call serverless on `SyncManager.Update` - 4h
- Hook into the Sync process - 8h
- IndexDB to prevent sending the same message twice - 4h

cc @adamhstewart

**Comment by anvmn** [comment]
@amitaibu 

This looks fine to me. I'd add that the events we'd want to notify about are not limited to the Sync process.
For example, the probelm that we get when content is written into `shards` table, but not found at `shardChanges` table happens when we save content which translates to issuing POST request to JS layer that works with IndexedDB.

The `prevent sending the same message twice` part is tricky, as we'll have define the definition of 'same error', and it will have to be expended, as we add more events. Also, querying and writing into IndexedDB is complex, development wise. 
So, I would include this as a follow up, after we have the core developed and functioning.

In any case, we're talking here about ~20h estimation.
If @adamhstewart approves and makes this a priority, I can start the work.

**Comment by amitaibu** [comment]
> The prevent sending the same message twice part is tricky

I imagine a new indexDB table with md5_errors. So when you have the JSON you want to send, you then JSON.Stringfy and md5 it. If it exists in the DB, you don't send it.

**Comment by amitaibu** [comment]
But sure, can be a follow up.

**Comment by AronNovak** [comment]
@amitaibu 
What's the benefit of wrapping Rollbar with a serverless function?
How I see that anyways we need a credential to store on the client side, to authenticate - either to serverless or Rollbar.
In both cases, someone can misuse it and flood our channel.
In both cases, Elm can filter out duplicated messages.

Or if we keep serverless wide-open, we will have nothing in our hands if someone starts to flood or misuse. With Rollbar, they provide out-of-the-box revoking tokens, block IPs, etc.

**Comment by AronNovak** [comment]
https://docs.rollbar.com/docs/preventing-client-side-access-token-abuse - if this is the main concern, with serverless, basically we put this responsibility in our shoulders, but it does not solve it.

**Comment by amitaibu** [comment]
@AronNovak Fair enough, we can skip the serverless part.
(On Circuit we had ot use serverless, as it had to do with sending messages via Pusher)

**Comment by anvmn** [comment]
@amitaibu @adamhstewart 
As we're in process of adding second site for Burundi, wonder if we should have central Rollbar account for all sites, or an account per site.
Per [Rollbar pricing](https://rollbar.com/pricing/), free plan is limited to 5K error events monthly. With ~350 active devices we got now, don't think this will be enough.

**Comment by amitaibu** [comment]
I'd go with a single Rollbar for TIP. It can be a paid account.

**Comment by anvmn** [comment]
Deployed to live
