### ISSUE TITLE
RM - Add Summation of score and interpretation on the Monthly survey [3h]

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#855]
### Issue
To score the Monthly survey by making the summation of each question.
- The highest score is 20points  (4 questions times 5(5th response option))
- The lowest score is 4points  (4 questions times 1 (1st response option))
**Interpretation** 
- Low resilient copers 4-13 points 
- Medium resilient copers 14-16 points 
- High resilient copers 17-20 points
### Todo
- Add the score on  each question.
- Make summation of each score.
- Add the popup with score and interpretation.
![Screenshot from 2023-08-30 10-29-40](https://github.com/TIP-Global-Health/eheza-app/assets/32199791/7f979d38-21c0-45c6-97d7-be4f6cb449ff)

**Comment by anvmn** [comment]
Deployed to live
