### ISSUE TITLE
Investigate "Failed to execute 'objectStore' on 'IDBTransaction': The transaction has finished." error

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#883]
Rollbar entry: https://app.rollbar.com/a/tipglobalhealth/fix/item/Site-Rwanda/11

**Comment by anvmn** [comment]
It may be an indication to issue we have when change does not appear at shardChanges table.
That table update is written withing `db.transaction`,  and the error indicates that transaction has ended before it has completed store operations.
If this is true, we may expect  ASM Village Kabare October 20th 2021 device to have sync issue, next time it uploads content.

**Comment by anvmn** [comment]
ChatGPT analysis:

In IndexedDB, transactions have a limited lifespan, and they can only perform database operations while they are active. Once a transaction is finished or has been explicitly aborted, you cannot use it to perform additional operations on the database. In your code, it appears that you are trying to perform an IndexedDB operation within a promise chain that is nested inside another promise chain, and there might be a timing issue causing the transaction to become inactive.

While promise chaining can be useful for managing asynchronous operations, excessive nesting can make the code harder to maintain and debug. Consider refactoring your code to use async/await, which can make it more readable and easier to manage.

**Comment by anvmn** [comment]
@adamhstewart @amitaibu 

Previous idea suggested that this type of error may be an indication to issue we have when change did not appear at `shardChanges` table.
That table update is written into withing db.transaction, and the error indicates that transaction has ended before it has completed store operations.

However, with additional data that we got, and more deep analysis, it seems not to be the case.
Currently, we got 4 variations of the error. All of them seem to be the result of failures during `bulkAdd` operation that occurs during sync, when device fetches data (500 changes) and stores them at IndexedDB.
First 2 items (11 and 14) simply point out to `bulkAdd`:

![Selection_2317](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/c87a47a6-5ee6-44e8-80ab-bbf44aa447e2)

![Selection_2316](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/92d6871b-3921-4221-8825-4b4b2fa46560)

Other 2 are items 16 and 18:

**Item 16** occurs at [line 566](https://github.com/TIP-Global-Health/eheza-app/blob/main/client/src/js/app.js#L556) of `app.js`, which executes `sendSyncedDataToIndexDb` port, which stores fetched changes using `table.bulkPut()`:

![Selection_2318](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/afb1a979-1039-444d-be35-9bfe5962aa06)

**Item 18** is actually another type of error thrown during problem that occurs for item 16.
It's at `app.js` line 1427, where we try to fetch Rollbar items from DB, and send them:

![Selection_2321](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/9004a825-4b01-4b9f-bfcc-c03e4889b09d)

![Selection_2320](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/b1760298-1de8-41b2-b2d4-4244ed97fee9)

So, conclusion is that until today, we did not see a report that could be an indication for missing data at `shardChanges` table, while it seems that I found first such failure at a device that had Rollbar notifications enabled when the content was recorded (on September 23) - https://github.com/Gizra/ihangane/issues/3076.

**Comment by amitaibu** [comment]
Really happy to see how Rollbar gives us better insights into those issues 👍
