### ISSUE TITLE
Upgrade Dexie [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#884]
## Issue
Upgrade Dexie.js as an approach to potentially solve issues such as #883.

## Tasks
- Investigate the issues resolved in Dexie repo as they relate to the sync issues we have seen
- Investigate upgrade path and potential trouble spots.
- Upgrade the software to the latest stable release
- Propose a QA Plan

**Comment by anvmn** [comment]
@adamhstewart 

> Investigate the issues resolved in Dexie repo as they relate to the sync issues we have seen

Looked through all official releases. At https://github.com/dexie/Dexie.js/releases/tag/v3.2.1, we got "reopen IndexedDB connection in case it was unexpectedly closed, and redo the operation" which may help. Also, we have some improvements at area of bulk updates, which can be useful.

> Investigate upgrade path and potential trouble spots.

Dexie got no dependencies, so there's no upgrade path. I also tested locally, verifying that Dexie upgrade does not affect the IndexedDB on the device. So we can upgrade from 2.0.4 to 3.2.4.

![Selection_2312](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/9779499b-cdf6-4f01-afad-fcd83d98357d)

> Upgrade the software to the latest stable release
 
#885 updates the version, but actual upgrade is performed during client installation.
So, when we wish to deploy new version, we'll have to perform local upgrade of Dexie using bower, and then deploy new products.

> Propose a QA Plan

- Verify Dexie upgrade does not affect IndexedDB (**done**)
- Sync large HC and verify both version of Dexie produce same entries at IndexedDB (**done**)
- Use new version of Dexie for a while on test environments, so enough content is recorded and stored at IndexedDB.
- 
Notes:
- Testing envs should have Rollbar notifications enabled.
- NCDA feature is a candidate to be tested using new Dexie.

**Comment by anvmn** [comment]
Deployed to live
