### ISSUE TITLE
NCDA: Change Question "Receipt of conditional food items" [.5h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#886]
## issue 

The question: Receipt of conditional food items including small livestock?  
Should be changed to: Receipt of other support (e.g., food items or small livestock)?

## Tasks
- Change the text of the question

**Comment by anvmn** [comment]
@Diama1 

This question requires Kinyarwanda and Kirundi translations.
You can add it at #891, or branch out from `develop` in case #891 gets merged.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
