### ISSUE TITLE
NCDA: Change text of conditional questions regarding consumption [.5h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#887]
## Issue

The conditional question after “Did the child receive Ongera-MNP” should be changed from "Is the food supplementation being consumed?" to "Is Ongera-MNP being consumed”

The conditional question after “Did the child receive FBF?
” should be changed from "Is the food supplementation being consumed?" to "Is FBF being consumed”

## Task
- Change the text of both questions.

**Comment by anvmn** [comment]
@Diama1 

These questions require Kinyarwanda and Kirundi translations.
You can add them at #891, or branch out from `develop` in case #891 gets merged.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
