### ISSUE TITLE
NCDA: Vitamin A - Add option for for "Not Applicable" [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#888]
## Issue

We need an option to respond "Not applicable" to the question "Did the child receive Vitamin A in the last six months?" in the case that the CHW determines that Vitamin A treatment is not applicable.

This response will result in a dash on the scorecard.

## Task
- Add the "Not applicable" option
- map the response to the score card

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
