### ISSUE TITLE
Multisite support - site dependant default content (migration) [3h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#892]
###  Support site dependant:

- Health centers
- Villages
- Patients

**Comment by balagan73** [comment]
https://qa-vhw.pantheonsite.io/app

## QA Review

### Checked and approved:

1. Burundi specific health centers exist
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/b192db3a-7186-4cb3-882e-76537813a63a)

2. Burundi specific patients exist
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/cb88c06c-03f8-4536-ab58-394a39a443b9)
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/c80511ed-f56c-441a-82e0-775370016a20)
