### ISSUE TITLE
Multisite support - allow features configuration [6h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#899]
Since diferent site may need different set of features, or, feature is launched  at sites on different dates, we need a mechanism that allows turning features on/off.
The idea is that flags will be configured on backend, and devices will be notified of features configuration as part of sync process.

**Comment by balagan73** [comment]
## QA Review

### Found issues and questions

1. Devices get the updates via sync, but changes are not reflected on the sync UI. Not sure if that was in scope.

### Checked and approved

1. After setting variables and syncing the behavior of the app changed

terminus remote:drush vhw.qa vset hedley_admin_feature_report_to_whatsapp_enabled 1
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/f35ce9f8-1fc8-4352-b31c-556f7de270cf)

terminus remote:drush vhw.qa vset hedley_admin_feature_report_to_whatsapp_enabled 0
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/1afddf31-6848-4f59-8c76-7e4fa1577dba)
