### ISSUE TITLE
Revisions to NCDA Nutrition Measurements [12h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#904]
## Issue
- followups to #889 

## Tasks
- Make the "Nutrition measurement" icon a step within the other scorecard "Pillars" (last step)
- measurement fields should all be on the same page (use ANC measurements as a guide - for visual looks and feel only)
- Changes to fields:
    - Height should be changed "Level of stunting using child length mat": A select list with the following options:
        - Green / Cyatsi 
        - Yellow / Hondo
        - Red / Tuku 
    - Nutrition signs should be changed to: "Does the child show signs of Edema?" with radio yes/no options
    - There should be an additional field at the top of the page: "Unable to take measurements, skip this step." with a check box that then allows the step to be completed.
- Order of fields:
    - Level of stunting using child length mat
    - Weight
    - MUAC
    - Does the child show signs of Edema?
- Mapping
     - Length: if the question is answered map the corresponding color, if the question was not answered and there is a nutrition visit from that month, use the existing mapping from the length measurement.
    - Weight: use original mapping 
    - MUAC: use original mapping
    - Edema:  if the question is answered map  red for yes or green for no, if the question was not answered and there is a nutrition visit from that month, use the existing mapping from the nutrition signs measurement.

Visual Sample from ANC:

<img width="948" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/beaaa5f4-908d-49f8-b556-746b08d12497">

**Comment by anvmn** [comment]
@adamhstewart 

> Make the "Nutrition measurement" icon a step within the other scorecard "Pillars" (last step)

Note that we show 'Is child being treated for Malnutrition' based on entered MUAC value.
If this Nutrition measurements step is last, and MUAC indicates malnutrition, the question may not be answered.
So, we either make this step before the step of malnutrition question, or, move the question to appear bellow the MUAC measurement.

> Height should be changed "Level of stunting using child length mat": A select list with the following options

Thinking about it, our standard on forms for selection between options is checkboxes.
That would also allow more flexebility when styling individual option (if we want to set different colors for example). Is select list a must here?

> There should be an additional field at the top of the page: "Unable to take measurements, skip this step." with a check box that then allows the step to be completed.

So, we have one field for all measurements? Shouldn't we allow skipping each measurement individually?
For example, case where CHW can take height and MUAC, but not weight?

**Comment by anvmn** [comment]
@adamhstewart also, I suppose this issue replaces https://github.com/TIP-Global-Health/eheza-app/issues/889? If so, we need to add the 'Is child being treated for Malnutrition' question requirement here.

**Comment by adamhstewart** [comment]
> Thinking about it, our standard on forms for selection between options is checkboxes.
> That would also allow more flexebility when styling individual option (if we want to set different colors for example). Is select list a must here?

@anvmn this would be fine to keep the standard

**Comment by adamhstewart** [comment]
> Note that we show 'Is child being treated for Malnutrition' based on entered MUAC value.

@anvmn Decision: 
- Move "Nutrition measurements" to the 4th position immediately after "nutrition behavior" and before "targeted interventions"
- The question "Is child being treated for Malnutrition?" should only appear (under "targeted interventions") if MUAC indicates acute malnutrition. The questions should be preceded by the phrase, "According to nutrition measurements, this child has acute malnutrition."

> So, we have one field for all measurements? Shouldn't we allow skipping each measurement individually?

Decision: Add the option to each question individually.

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
