### ISSUE TITLE
NCDA: Highlight Acute Malnutrition mesurement [1h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#907]
## Issue
Under targeted interventions - if the child has acute malnutirtion output the message in red.

<img width="815" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/55fb6393-ec34-494b-b158-aad7de61e93b">

## Tasks
- Change the font color to red in the text identified above

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
