### ISSUE TITLE
NCDA: Show abnormal ranges for MUAC measurement [3h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#908]
## Issue
Show the Green/Yellow/Red indicator for the MUAC measurement as appears on a normal nutrition encounter.

<img width="835" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/bef3eda0-636a-456e-9b2e-2b244fe0355f">

## Task

- Add the inline indicator

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
