### ISSUE TITLE
NCDA: Remove conditional logic for Edema question [1h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#909]
## Issue
Under nutrition measurement, there should be no conditional logic for the "edema" question (i.e. it should always be shown)

<img width="843" alt="Cursor_and_E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/57e35ad6-ec5c-4e1b-8cd3-70fd568d41cc">

## Task
- Remove the conditional logic

**Comment by anvmn** [comment]
@adamhstewart 

This issue is not assigned for a reason?

**Comment by adamhstewart** [comment]
@anvmn no ^^

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
