### ISSUE TITLE
Patient Record - ANC Progress Report Design Changes [4h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#91]
## Issue [Updated]

To keep all the progress report consistent in look and feel some minor design changes have been made to the ANC progress report. These changes should be made across all ANC progress reports in the app. 

Changes include: 
- Updated the heading section to be consistent with other progress reports
- Compressed the floating boxes to touching 
- Moved photos to the bottom ( #101 ) 

See photos for comparison 

Old Progress Report | New Progress Report 
--|--
![Short Dipstick Report](https://user-images.githubusercontent.com/77505464/148450943-ae533560-b324-48eb-a913-5d4bfa357695.jpg) | ![Anetnatal Progress Report](https://user-images.githubusercontent.com/77505464/149020385-0a9b838a-1d8a-4d6d-a291-b5bf57bb48c5.jpg)

## Tasks: 

- Style per design
    - update heading style
    - remove padding around floating boxes so they fill the width of screen 
    - remove padding between floating boxes so they touch

**Comment by isapisa** [comment]
@jeanette-pelizzon the patient header information for Patient Record is different to individual progress reports within modules:

Patient Record | AI Report example
--|--
<img width="777" alt="Screenshot 2022-01-07 at 10 36 05" src="https://user-images.githubusercontent.com/34378755/148523906-68d3a17f-a616-497d-bdb6-4ba36819b3d8.png"> | <img width="491" alt="Screenshot 2022-01-07 at 10 36 34" src="https://user-images.githubusercontent.com/34378755/148523954-5337a9ca-1c90-4a2e-b735-f80270dd60db.png">

Worth making sure that the patient header for individual ANC reports within the module is also adapted accordingly.

**Comment by jeanette-pelizzon** [comment]
@isapisa we made some changes to the overall flow of the patient record so the heading issue is resolved by that. No changes are being made to the ANC progress report heading at all now. Just removing padding and ensuring the photos are moved to the bottom.

**Comment by adamhstewart** [comment]
@anvmn 

- The header doesn't match the new design
![Selection_999(171)](https://user-images.githubusercontent.com/688507/156377514-16538d56-ef1b-41de-b57f-7c1f0bc1dd77.png)

- Not really related to this issue (but not sure where to put it) - when you click "more" for a completed pregnancy, you get to the labs results page, not the progress report. see video:
https://www.loom.com/share/ef2f65fb37a1448592ac179646cc89b3

**Comment by anvmn** [comment]
@adamhstewart 

>  The header doesn't match the new design


 This is what is what we have at Figma:

![Selection_570](https://user-images.githubusercontent.com/17882245/157403175-1fee152a-7c0f-444e-b103-7a6aa91604b6.png)

This is what we have implemnented:

![Selection_569](https://user-images.githubusercontent.com/17882245/157403211-92cbb677-b66a-4f07-800c-d80dfa568dec.png)

Are these the mismatches you found?
![Selection_569](https://user-images.githubusercontent.com/17882245/157403651-3367a427-75b4-46b1-954c-a70f5c540fe8.png)

**Comment by anvmn** [comment]
@adamhstewart 

> Not really related to this issue (but not sure where to put it) - when you click "more" for a completed pregnancy, you get to the labs results page, not the progress report

Fixed at https://github.com/TIP-Global-Health/eheza-app/pull/180

**Comment by anvmn** [comment]
As per @adamhstewart, https://github.com/TIP-Global-Health/eheza-app/issues/91#issuecomment-1062675597 changes are not required. Moving to QA.
