### ISSUE TITLE
NCDA: Remove consumption questions for Deworming and Vitamin A [3h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#910]
## Issue
Under Universal interventions, remove the 2 conditional "consumption" questions for Vitamin A and Deworming:

<img width="797" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/1924c80f-e22a-4967-8040-5eef5ceb2686">

The mapping to the scorecard should change to reflect the answer to the original question

## Tasks
- Remove the logic and the questions
- Change the mapping to the scorecard

**Comment by anvmn** [comment]
NCDA is on live for few months. Closing.
