### ISSUE TITLE
Regionalization - Burundi: Unit of measurement for MUAC [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#916]
## Issue 

In Burundi MUAC measurements are taken in mm rather than cm. This is true in case of both children and pregnant women

## Task
- Allow input to be taken in mm (also indicate mm on the interface) and store the value in cm
- Show previous measurements in mm

Note: as far as I can see, MUAC is not displayed in raw numbers on the progress report or on the child scorecard.

**Comment by balagan73** [comment]
https://qa-vhw.pantheonsite.io/app

## QA Review

### Found issues and questions:

1. Previous measurements are shown in mm, but the amount is invalid. Not sure about real data in the DB, but it seems existing data on QA should be converted to mm.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/d57029d4-f6b6-4726-ad7b-b664914674a6)


### Checked and approved:

1. MUAC is entered in mm
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/21f8e9b5-ae11-4568-b801-d5c84ea60009)

**Comment by adamhstewart** [comment]
@anvmn see above - past measurement needs to be calculated in mm
