### ISSUE TITLE
Regionalization - Burundi: Change Order - First Name/Last Name [3h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#917]
## Issue

In Burundi it is more common for the last name to appear first on a form (before the first name)

## Tasks

- Change the name order on the registration form only so that Last Name appears before first name

Note @Diama1 can you please check that we shouldn't be using different terms for the name also (such as Family name or surname, and Private name)?

**Comment by balagan73** [comment]
https://qa-vhw.pantheonsite.io/app

## QA Review

### Checked and approved:

1. Name order is reversed on the registration form

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/570d8608-747e-411e-b964-7f21088e65de)
