### ISSUE TITLE
Patient Record - Header [3h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#92]
## Issue 

For patient records, we want to present the user with any and all relevant information associated with a patient. 

We are presenting: 

- photo of patient 
- age 
- date of birth 
- ubudehe 
- level of education 
- Baby # and Name of Child (if applicable) 
  - sort by oldest child

![Selection_457](https://user-images.githubusercontent.com/17882245/150671894-9a35217f-309b-4d06-a97d-96d602f2e646.png)

## Tasks

- Change header containing patient information
- Style per design

**Comment by isapisa** [comment]
@jeanette-pelizzon see also https://github.com/TIP-Global-Health/eheza-app/issues/91#issuecomment-1007265697
