### ISSUE TITLE
Regionalization - Burundi Immunization Calendar [12h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#920]
## Issue

Adapt immunization schedule for Burundi:

BCG/HepBo/Polio: at birth
Polio1, Pentavale1, Rotavirus1, PCV13(Pneumonia):6 weeks
Polio2, Pentavale2, Rotavirus2, PCV13(Pneumonia):10 weeks
Polio3, Pentavalent 3, PCV13(Pneumonia) and IPV:14 weeks
Vitamin A Every 6 months: During campaign
Measle/Rubeola and mosquito net:9 months
VitA and albendazole: 12 months
DTC4, MR, vitA, Albendazole and mosquito net: 18 months 
VitA and Albendazole every 6 months until 59 months

NO HPV immunization

## Task
- Adapt schedule

# Immunisations:

Age | Immunisation | Notes
--|--|--
Birth |BCG Bacilius Calmette - Guérin (BCG)
|| Oral Polio Vaccine
6 Weeks (1.5 months) |Oral Polio Vaccine
||Pentavale
||Pneumococcal Vaccine (PCV 13)
||Rotavirus (Rotarix)
10 Weeks (2.5 months) |Oral Polio Vaccine
||Pentavale
||Pneumococcal Vaccine (PCV 13)
||Rotavirus (Rotarix)
14 Weeks (3.5 months) |Oral Polio Vaccine
||Pentavale
||Pneumococcal Vaccine (PCV 13)
||Inactivated Polio Vaccine (IPV)
36 Weeks (9 Months) |Measles - Rubella (MR)
18 Months (1.5 years) |Measles - Rubella (MR)
||DTP (4-th dose)

Vaccine | Dose | Interval
--|--|--
BCG Bacilius Calmette - Guérin (BCG) | 1 | 
Oral Polio Vaccine | 4 | 28 days min
Pentavale | 3 | 28 days min
Pneumococcal Vaccine (PCV 13) | 3 | 28 days min
Rotavirus (Rotarix) | 2 | 28 days min
Inactivated Polio Vaccine (IPV) | 1 |
Measles - Rubella (MR) | 2 | 9 months
DTP (4-th dose) |  1 |

**Comment by anvmn** [comment]
@adamhstewart 

This issue mixes different subjects together.
It should be divided into 3 - Immunization, Medication and Resources (mosquito net).

**Immunization**:
 - we need a table, similar to https://github.com/Gizra/ihangane/wiki/Module---Pediatric-Visit#immunisation, where we'd use same terminilogy.
 - What is Pentavale? Is this new type of vaccine. If so, we need a separate issue to create infrastructure for it.
 - I don't see DTP and IPV immunisations.
 - What is DTC4?

**Medication**:
- we need a table, similar to https://github.com/Gizra/ihangane/wiki/Module---Pediatric-Visit#medication.
- `Vitamin A Every 6 months: During campaign`  - what campaign?

**Resources**:
As far as I can tell, so far, mosquito net is mentioned only at Prenatal module, as Malaria prevention sign. If there's a need to have it as part of SPV, the requirements need to be defined.

**Comment by anvmn** [comment]
@adamhstewart 

> BCG/HepBo/Polio: at birth

Currently, at birth we suggest BCG and Polio.
We don't have HepBo as a vaccine. What is it? Do we need to introduce it as new vaccine type?

**Comment by adamhstewart** [comment]
> We don't have HepBo as a vaccine
igonre HepBo

**Comment by balagan73** [comment]
https://qa-vhw.pantheonsite.io/app/

## QA Review

### Found issues and questions:

1. DTP (4th dose) is missing. Also reported for issue https://github.com/TIP-Global-Health/eheza-app/issues/926

2. I think the indefinite article is not needed before fever. text should say 'causes fever'.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/b9c08e21-d3e8-4979-929b-a94a7e87183f)

###  Checked and approved:

1. Schedules of vaccinations are correct.

BCG
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/2c162d17-0e0b-4890-9bf6-6bd1c18bd5bc)

OPV
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/b605b769-2244-4d00-b7b9-b318a485ec42)

Pentavalent
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/8c1ffb46-d393-458b-83fa-e9acdcf7e7cf)

PCV-13 
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/84f284c2-e798-4936-bb18-30636e71292d)

Rotarix
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/0b3320aa-2517-4736-804a-47f6751ef88a)

IPV
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/0052b1ea-c9e6-4863-a4f2-376df580e8d8)

Measles-Rubella
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/713922b4-ec39-4191-ac66-cca81319a887)
