### ISSUE TITLE
Regionalization - Burundi - Change Description of salt in food for NCD Social History

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#922]
## Issue

Rephrase the question “Do you add salt to your food?” to "Do you add salt to your food after it is served?"
<img width="1020" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/57e1dc94-1921-4106-8198-8995a8bd6ede">

## Task
- Change the phrase for Burundi

cc @Diama1 please provide Kurundi translation

**Comment by balagan73** [comment]
https://qa-vhw.pantheonsite.io/app/

## QA Review

### Checked and approved:

1. Question is rephrased per request
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/c003b320-042c-4a13-9510-c7820553d174)
