### ISSUE TITLE
Localization - Burundi - DTP - HepB - Hib is called Pentavalent, extra dose of DTP [8h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#926]
## Issue
Following #920 

In Burundi context, the combo vaccine for DTP - HepB - Hib is named Pentavalent

In addition there is an extra (4th dose of DTP only) at 18 months

## Tasks
- Rename the combo vaccine in Burundi context (keep the icon)
- Add new vaccine called DTP for one dose at 18 months. It should only appear after 3 doses of Pentavalent and with a minimum 28 day interval from the last Pentavalent dose.

**Comment by anvmn** [comment]
@adamhstewart 

> In Burundi context, the combo vaccine for DTP - HepB - Hib is named Pentavalent

Ok, that makes sence. These are the details for Pentavalent (5 diseases):

![Selection_2393](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/b872693a-5c03-4eda-9a39-648e1021f76d)

Looking at current implementation however, seems that `Hib` disease is missing:

![Selection_2394](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/1ecb08fb-6a9a-4190-b73e-85837a4007f6)

Why is that? Should we fix it?

> In addition there is an extra (4th dose of DTP only) at 18 months

I suppose that DTC4 from #920 is the (4th dose of DTP only).
This is new type of vaccine we'll have to introduce. I suppose it handles 3 diseases - Diptheria, Tetanus, Pertusis. I'll addapt the forms accordingly.
Note that we need to add it for 2 types of encounters - Child Scorecard and SPV.
So, only the activities infra will require ~6h. In total, I suppose it will at least require 12h.

**Comment by adamhstewart** [comment]
> Why is that? Should we fix it?

I'll ask - but let's not deal with that here.

> I suppose that DTC4 from https://github.com/TIP-Global-Health/eheza-app/issues/920 is the (4th dose of DTP only).

Yes, it's a Typo - it should be DTP (the 4 is for the fourth dose , as DTP is included in Pentavalent).

> So, only the activities infra will require ~6h. In total, I suppose it will at least require 12h.

OK to bump

**Comment by balagan73** [comment]
https://qa-vhw.pantheonsite.io/app/

## QA Review

### Found issues:

1. Typo in Diphteria
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/7537061e-3218-4af0-9362-65dbd7fcddf0)

2. For a baby over 18 months, the option to enter the 4th DTP vaccine doesn't display, even though the required 28 days has been spent.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/d4fbd71f-67c6-49c2-b90c-20e0a723937e)
The status on the Overview page shows correctly the 4th DTP dose is missing:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/6690a8b4-f725-48cc-9117-f9d68f1d1576)


### Checked and approved:

1. Pentavalent displays correctly for Burundi. See image above.
2. DTP - HepB - Hib displays correctly for other environment
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/2ddf3739-9c1d-4b77-8ea6-e2d8a5b9d751)
