### ISSUE TITLE
Regionalization - Burundi SPV Medication [6h]

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#928]
Age | Type of medication | Dose | Interval
--|--|--|--
6 Months | Vitamin A | 100,000 IU 
1 Year | Albendazole | 200 mg
|| Vitamin A | 200,000 IU
18 Months (1.5 Years) | Albendazole | 200 mg
|| Vitamin A | 200,000 IU
2 years - <6 years | Albendazole | 400 mg | 6 months
|| Vitamin A | 200,000 IU | 6 months
6-12 years | Albendazole | 400 mg | 6 months

**Comment by balagan73** [comment]
https://qa-vhw.pantheonsite.io/app

## QA Review

### Checked and approved

6 month:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/7435b16e-9cdf-4c61-b23e-b0fa16bf3f5c)![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/f3d2107e-9da4-4d24-b022-d68fdc739555)

1 year:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/cdb296c9-9057-41ca-844a-641ce30a7e25)
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/20422ffc-d914-48c3-85e0-3c6964c537c7)

18 month:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/cbd004c3-0046-4800-85db-8bc7c2a27690)
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/b14e767e-ecc5-498e-b4ef-25912d7373c5)


2 - 6 years
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/bfa9ca1e-6655-4cd4-bbae-481a3aa1dfa1)
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/643b882a-34dd-4d0b-8f18-d122a84613a8)


6-12 years

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/b31fc77d-0d79-45d6-90f4-ad626489f5aa)
