### ISSUE TITLE
Adaptation of NewBorn Exam on Entry Screen [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#930]
## Issue
Change to Well Child Visit

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app/

## QA Review

### Found issues:
 - None
 
### Checked and approved:

- Encounter type is called 'Well child visit' for CHW.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/4b87e5bd-fbba-46f5-8706-b33415e423dc)

Encounter options:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/188db457-23a0-4bca-8db9-8e9702cd7b51)
