### ISSUE TITLE
Adapt existing activities from HC SPV -> CHW Well Child [8h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#931]
## Issue
- show birth history until 2 mos (or completed)
- Remove child schorecard
- remove medication
- remove ECD

**Comment by anvmn** [comment]
@adamhstewart 

At Nutrition assessment activity we have following tasks:
- Newborn exam:  Head Circumference, Nutrition, Weight
- SPV: Height, MUAC (from age of 6 months), Head Circumference, Nutrition, Weight

At SPV for CHW, I suppose we should have MUAC (from age of 6 months), Head Circumference, Nutrition, Weight. Do we need Height there?

**Comment by adamhstewart** [comment]
@anvmn yes, we need height there ^^

**Comment by anvmn** [comment]
@adamhstewart 

> @anvmn yes, we need height there ^^

Checked behavior of Nutrition Assessment encounter, and for CHW, Height activity is optional.
Updated code for Nutrition Assessment Height task to be optional.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Found issues:
- None

### Checked and approved:
- Child Scorecard is removed
- Medication Removed
- ECD Removed
- Height under Nutrition assessment is optional
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/9e393d43-b18e-49db-a30b-0a6620a6d159)

Birth history displays for child under 2 months.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/9daaa01d-277a-4f24-acd1-42a45e3a5642)
