### ISSUE TITLE
Change immunization for CHW to update record only [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#932]
## Issue 
CHW should only be able to update the vaccine record, they do not administer doses on the day of the encounter.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app/

## QA Review

### Found issues:
- None

### Checked and approved:
- CHW can only update vaccination record
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/21bf304f-e374-4b6a-9454-b155754263ae)
