### ISSUE TITLE
Add Home Visit to CHW Well Child [12h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#933]
## Issues
- Create the content types
- Build the activity on the front end

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Found issues:
- None

### Checked and approved:
- Home visit option is available under Well Child visit for CHW
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e5b58dc6-c6e5-44f2-8ea1-f79f782bd5e6)

Home visit screen:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/622ca81e-b20b-4123-9e6f-8769284a00d5)
