### ISSUE TITLE
CHW Well Child - Next Steps 

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#934]
TBD

**Comment by anvmn** [comment]
@adamhstewart 

Issue with requirements for nurse -  https://github.com/Gizra/ihangane/issues/2608.
Issue with requirements for CHW -  https://github.com/Gizra/ihangane/issues/2670.

**Comment by anvmn** [comment]
@adamhstewart 

This is what I see from code:

There are 5 next step tasks:

- Contributing Factors
- Health Education
- Referal (to HC for CHW (Newborn Exam), to Program for nurse (SPV))
- Follow up
- Next visit 

**First four** are displayed:
1. For nurse and CHW (Newborn Exam), when there's nutrition diagnosis.
2. For CHW (Newborn Exam), Health Education and Referal will also be displayed if any of given at birth vaccines (BCG and OPV) was not administered.

**Next visit**  is displayed only for nurses, and in case next visit is required (as it's possible that child has completed all vaccinations, ECD and medications).

How should we adjust this at SPV for CHW?

**Comment by adamhstewart** [comment]
@anvmn 
> How should we adjust this at SPV for CHW?

- Contributing factors as HC
- Health Education as HC
- Referral should be to health center if there is a nutrition diagnosis OR if they are behind in any of their vaccinations (not just the birth vaccinations).
- Next visit page should be same as HC, but add language "at health center" to avoid confusion.

**Comment by anvmn** [comment]
@adamhstewart 

> Next visit page should be same as HC, but add language "at health center" to avoid confusion.

Like this:

![Selection_2442](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/f4c0169f-dcf5-4012-8915-a81c8287eac7)

**Comment by anvmn** [comment]
@adamhstewart 

> Health Education as HC

At newborn exam both Referal and Health Education were dependant on immunization.
At SPV for CHW, Health Education is omited?

**Comment by adamhstewart** [comment]
@anvmn I had actually meant like this:
<img width="563" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/7783dd1b-7ef8-441c-b8d2-d613a4f4c17c">

But I think on the icon label is good as well.

> At SPV for CHW, Health Education is omited?

It should also be dependent on immunization if the patient is behind.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Found issues and questions
- None

### Checked and approved
- Next visit is shown to be at the HC
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/c71f4493-a6e8-4295-9d89-b2944c9e9640)

- Health education when patient is behind schedule
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/02383549-b3de-488c-8388-346c38e98981)

- When patient immunisation is up to date
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/0172d340-5d55-471b-a09b-1628e02db11b)

- The 5 next steps can be displayed
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/9754a63b-b05d-4355-b965-ba3e20869a42)
