### ISSUE TITLE
QA NCDA Child Scorecard [16h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#942]
## Issue

NCDA (National Childhood Development Agency) Child scorecard is a module that has activities both for CHW (Community level) and Nurses (Health Center level). 

For Health centers, activites are included under "child scorecard" subactivities in: Standard pediatric visits, Group nutrition visits (FBF and PMTCT), and Individual nutrition.

For CHWs, the module is contained in a single activity called "Child Scorecard" that can be accessed under Individual Encounters.

Each of the modules (for HCs and CHWs feed data into the "Child ScoreCard" which can be viewed next to the progress report for any child 2 years old and under.

Much of this module has already been QA-ed but there have been many [changes](https://github.com/TIP-Global-Health/eheza-app/issues?q=is%3Aissue+is%3Aopen+label%3ANCDA), so a review based on the [analysis sheet](https://docs.google.com/spreadsheets/d/1sAYhkh15V2CZcu9OC7pN1yJ3NPShU3q3/edit?usp=sharing&ouid=104843215453637480834&rtpof=true&sd=true) is required

## Tasks
- Compare questions in HC-level activity to the questions on the analysis sheet (Column B)
- Compare questions in CHW-level activities to the questions on the analysis sheet (Column A)
- Assure that proper guidance is given in the case of certain conditional answers (Column C)
- Confirm that mapping logic to the child scorecard is correct according to the analysis sheet (Columns D-H)

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review - Antenatal care

### Found issues and questions:

1. The text for no ANC visit differs from the one in the Analysis sheet, but it is more logical, as an unborn child cannot actually have a visit, only the mother, so I think it's OK.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/8b4d1624-b070-4650-a62d-18d6f201276c)

### Checked and approved:

1. With 4 ANC encounter dates the guidance texts is not displayed.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/a1cf9feb-7fbc-4345-af19-e3c71e33afab)

2. When Iron was not taken per recommendations, the guidance displays.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e4cc065c-2d96-493f-ada8-b210ff4ee535)
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/79d2d4a0-875e-4c2a-8aeb-2e8446f1caaa)

3. Mapping logic is correct.

Missing ANC encounters and no iron taken
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/3a4349bf-f79f-478f-a8b0-eeb0373dea7e)
At least 4 ANC encounter and iron taken
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/bfbbf508-9433-4f0b-84aa-bdeaf1365cb6)

**Comment by balagan73** [comment]
## QA Review - Universal Interventions

### Found issues and questions:

1. The green immunization checkmarks do not display after entering vaccination dates.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/94eebc54-2340-4d87-8607-9a174a02651b)

2. I think the 'the' should be omitted just like in other guidance texts 
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/b2375d50-a58a-4f0b-a206-93e75e050bc4)

3. It should be **child's** vaccine record
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/f3e1f52e-53f7-437b-bece-bed06a8bf617)

4. Should be Provide, as in other guidance texts
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/37bc4353-f8c9-49eb-9dd9-c09d15f4b150)

### Checked and approved:

1. Texts and guidance texts display correctly, see above images.

2. Mapping logic is mostly correct.

'No' answers
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/5fc69f55-ad49-4a92-acc4-ce36439c2539)
'Yes' answers (vaccination records are not updated yet.)
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/826d92bc-1883-49a6-bffd-ab8f25f21662)

**Comment by balagan73** [comment]
## QA Review - Nutrition behavior

### Found issues and questions:

1. I think the first questions should be 'Did the child receive food items...", 
2. I think the guidance text should say 'based on the ones they have in their area'.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e2213b3d-349e-48f5-8223-5ae53e2d3094)

### Checked and approved:

1. Questions and guidance texts display correctly, see above images.

2. Mapping logic is correct.
'No' answers:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/a9973a11-6386-466a-ae83-68d14caa42b8)
'Yes' answers:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e1c1e89a-89fe-4d73-a49a-6d866f3b5692)

**Comment by balagan73** [comment]
## QA Review - Targeted interventions

### Found issues and questions

1. The question 'Please check MUAC. Does the child have acute malnutrition?' is missing. The mapping logic says:

> maped from the most recent of:
> - CHW answer to second question
> - HC diagniosis and referral

What is this second question?

2. Guidance text should day 'Provide counseling...'
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/36787710-89cc-4807-98b7-0c7a28de6da9)

3. 'Receipt of conditional food items including small livestock' is phrased differently than the text on the Analysis sheet.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/67fded1b-8295-452b-ad56-cb7d088a245e)

### Checked and approved:

1. Questions and guidance texts display correctly.
2. Mapping logic is  correct, although the result for treatment of acute malnutrition cannot be changed, because question is missing.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/23c98387-7a04-4578-9212-b3dc1e03ca39)
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/9d3f8a55-cd0c-4bfb-a36f-c0dd6c5be17c)

**Comment by balagan73** [comment]
## QA Review - Infrastructure & environment

### Found issues and questions:
None

### Checked and approved:

1. Questions and guidance texts display correctly.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/cc544995-bab8-45ff-b629-a1e91e9a4049)

2. Mapping logic is correct.

No answers:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/244d68af-93f0-4092-9603-d79c08a622af)

Yes answers:
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/890b1b40-181b-49b9-9c80-2106c05c575b)

**Comment by balagan73** [comment]
### QA Review - HC login

## Checked and approved

1. Questions for Health Center login display correctly.

**Comment by adamhstewart** [comment]
@balagan73 

> The green immunization checkmarks do not display after entering vaccination dates.

Can you describe how you tested? This checkmark is received not just if a child received vaccination but if the child is "on track" with vaccinations overall.

> The question 'Please check MUAC. Does the child have acute malnutrition?' is missing. The mapping logic says:

This has been changed according to https://github.com/TIP-Global-Health/eheza-app/issues/904

Also: did you check each of the HC cases? I only see one note there.

@anvmn 
- Under Universal Interventions, please check the immunization record (point 1, per @balagan73's explanation above) and fix the grammatical issues that @balagan73 has suggested (points 2, 3 and 4).
- Under Nutrition behavior, please fix the grammatical issues (points 1 and 2)
- under Targeted interventions, please fix grammatical issues (points 2 and 3)

**Comment by anvmn** [comment]
@adamhstewart 

> Under Universal Interventions, please check the immunization record (point 1, per @balagan73's explanation above) and fix the grammatical issues that @balagan73 has suggested (points 2, 3 and 4).

Waiting for @balagan73 explanation. In addition, I need to know the patient that was tested, so I can check the reason for suspected incorrect result.
Gramar fixd.

> Under Nutrition behavior, please fix the grammatical issues (points 1 and 2)

Fixed

> Targeted interventions, please fix grammatical issues (points 2 and 3)

Point 2 fixed. Point 3 **shall remain as is**, per #886.

**Comment by balagan73** [comment]
@adamhstewart @anvmn 
Regarding the immunization:
After filling out the Child scorecard for the baby I have just created yesterday, the Vaccination history activity was available, and I have filled that. Today going back to the same patient (Baby Newborn), the Vaccination history was available, as I have entered that vaccination data is not up to date. 
Here entering a new Rotarix vaccination date the immunization checkmarks got updated.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/c5b4e2d6-2fd9-4a9c-a040-f590270b33b5)
I wonder if it is normal adding one vaccination date resulting in 7 checkboxes turning green.

I have checked all the HC cases and compared the questions with the ones on the analysis sheet. They were correct.

**Comment by balagan73** [comment]
Further checking the immunization, I have noticed some weird things:

BCG and Rotarix vaccination date was given, but BCG and Rotarix activity was not marked as finished.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/1757a5b4-45dd-490b-abcd-a301a35d78f5)
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/1c5b069d-6d27-4cc8-820a-0654eda95b26)

After refreshing the app, Rotarix was marked as finished, and I could enter the BCG vaccination date again:
After entering the same date as before, BCG activity was marked finished. (Update: I think I was forgetting to click Save on the individual tabs)

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/8becd789-69e5-40a5-9add-d5100c4b8f08)

Although all the vaccinations were entered, third month is still not marked with checkbox. (Baby name is 'Baby Another')
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/26cb7346-3e39-4129-b942-cc60e3591312)

**Comment by anvmn** [comment]
@balagan73 

You're correct. It's not enough to set date. You also need to press Save button on the bottom of the form. So, my guess is similar to yours, that you did not press Save.
