### ISSUE TITLE
Add Followup notification for Immunization Case Managemengt - CHW [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#943]
## Issue 

Allow a CHW to indicate that there should be a follow-up created for the next time a patient is supposed to receive vaccination.

<img width="1031" alt="Cursor_and_E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/cd36a9eb-d415-4a4c-bcc2-a9917c5b9990">

## Task
- Create the checkbox boolean field on the form

**Comment by anvmn** [comment]
@adamhstewart 

Note that Next Visit is a Next Steps task.
Currently, Next Visit is not displayed for CHW. I suppose that will change after https://github.com/TIP-Global-Health/eheza-app/issues/934#issuecomment-1807798825 is answered.

Also, it's not clear to me why CHW should indicate anything with checkbox. Don't we want the case management always?

**Comment by adamhstewart** [comment]
> Don't we want the case management always?

confirmed we will automate this when the encounter is ended.

**Comment by balagan73** [comment]
This will be checked under https://github.com/TIP-Global-Health/eheza-app/issues/945
