### ISSUE TITLE
Create an Immunization Followup Content Type [8h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#944]
## Issue
A content type to hold the follow-up date that a child should be rechecked for immunization by a CHW.

In this case, the follow-up option should be a date that is equal to the date in the SPV that indicates when a child's next immunization visit.  should have been

## Tasks
- Create the content type
- Create infrastructure to sync with frontend app.

**Comment by anvmn** [comment]
@adamhstewart 

We have Next visit content type, so I'd first consider expanding it for our needs.

**Comment by adamhstewart** [comment]
> We have Next visit content type, so I'd first consider expanding it for our needs.

sure, if it makes most sense.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Found issues:
- None

### Checked and approved
- Date of next immunization visit is stored and displayed:

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/4d192d0e-2e6a-4be9-873b-853c4702dce5)
