### ISSUE TITLE
Display Immunization Followups in Casemanagment for CHW [8h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#945]
## Issue
<img width="656" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/100327dd-502c-43eb-b994-dea5d89e20a9">

## Tasks
- Create new section for Immunization
- Show followups that are past the date for the immunization visit
    - for first 30 days past the visit date, the tags should read "this month"
    - for after 30 days past the visit date, the tag should read "past due"
    - Text should read "Check for immunization."
    - link to a new CHW SPV encounter

**Comment by anvmn** [comment]
@adamhstewart 

This issue is missing the 'reminder resolution' part.
For example, starting new SPV for CHW encounter, should resolve reminders from previous encounters.
Also, maybe same should be done if nurse runs standard SPV?

**Comment by adamhstewart** [comment]
> This issue is missing the 'reminder resolution' part.

It should only be resolved if:
- the patient visits the HC AND receives the required vaccines; OR
- the patient receives follow up from the CHW AND the required vaccines are recorded.

**Comment by anvmn** [comment]
@adamhstewart 

> > This issue is missing the 'reminder resolution' part.
> 
> It should only be resolved if:
> 
> * the patient visits the HC AND receives the required vaccines; OR
> * the patient receives follow up from the CHW AND the required vaccines are recorded.

In both cases, SPV encounter is started, where Next Visit activity is mandatory (in case future vaccinations are required).
So, each such encounter creates new 'follow up', which means we can resolve all previous ones.
Does that make sense?

**Comment by adamhstewart** [comment]
@anvmn ^^ above makes sense, yes.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app/

## QA Review

### Found issues and questions:

1 When a patient is behind with immunization, 
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/2d65271e-aea1-4ebf-bbdf-411edb37c062)

souldn't it be indicated under case management as Past due similar to other follow ups? I am not sure how this is checked. I have adjusted the date back on the Well Child followup, but maybe this way some cron task were skipped or something. I need help, how to test it. @anvmn @adamhstewart 
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/14aa11de-0ce5-42d7-9f9b-8f8ddec28de0)


UPDATE: Even after editing the Well child next visit CT and syncing the app, the follow-up doesn't display under case management immunization.

2. Not related to this issue, but Diphtheria is misspelled throughout the app as Diptheria.

**Comment by anvmn** [comment]
@balagan73 

The entry is generated based on Well Child Next Visit content type, that is created during SPV encounter (both for nurses and CHWs). It's part of Next Steps activity.
After you generated that content and adjust immunisation date, you should be able to see the entry.

**Comment by adamhstewart** [comment]
@anvmn I'm having the same issue that @balagan73 points out. After a well child visit, I don;'t see a follow up for a patient that is past due in immunization.

**Comment by anvmn** [comment]
@adamhstewart 

> @balagan73

> The entry is generated based on Well Child Next Visit content type, that is created during SPV encounter (both for nurses and CHWs). It's part of Next Steps activity.
After you generated that content and adjust immunisation date, you should be able to see the entry.****

Did you adjust the date on Well Child Next Visit node?

**Comment by adamhstewart** [comment]
@anvmn no. How should I adjust it? To the previous day?

**Comment by anvmn** [comment]
@adamhstewart 

There are 2 dates on node. You should be adjusting immunisation date.
Date should be set to past date, according to what you plan to test. The requirements are:
![Selection_104](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/5ab67afe-8663-44a8-951b-12a43c40644d)

Also, make sure to sync the device, so that changes on backend are synced to the device.

**Comment by adamhstewart** [comment]
@anvmn as discussed, this should be adjusted to show follow-ups for patients that have visited the CHW or HC but are still behind in their vaccination and are eligible to receive one.

**Comment by anvmn** [comment]
@adamhstewart 

> @anvmn as discussed, this should be adjusted to show follow-ups for patients that have visited the CHW or HC but are still behind in their vaccination and are eligible to receive one.

Changes implemented and deployed to Nutrition env

**Comment by adamhstewart** [comment]
@anvmn on testing :

Performed a well child encounter:
<img width="797" alt="Well_Child_Encounter_-_Individual_Participant_-_baby_test_-_2023-11-14_-_2024-01-08___E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/14cf2bae-4b6c-40e7-af4f-b0146ddad0bc">

Made sure IZ were past due after encounter:
<img width="968" alt="E-Heza_System_and_tpp-app_—_adamhstewart_Adams-MacBook-Pro_—___space_tpp-app_—_-zsh_—_126×35" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/7cd150bf-4948-4257-9516-b929b372214a">

edit: I refreshed the screen at this step - originally there were no followups but after refreshing the page there is one. How do we make the followup appear without a page refresh: 

<img width="692" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/32f59348-2744-420e-a6d9-4c7b7258e41c">

**Comment by adamhstewart** [comment]
@anvmn same issue when the followup is cleared - requires a screen refresh to make it disappear.

**Comment by anvmn** [comment]
@adamhstewart 

> @anvmn same issue when the followup is cleared - requires a screen refresh to make it disappear.

Applied a fix on Nutrition env. Please check.

**Comment by adamhstewart** [comment]
@anvmn 

> Applied a fix on Nutrition env. Please check.

Looks good.
