### ISSUE TITLE
Allow nurses to skip Child scorecard activity with "opt in" acknowledgement [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#953]
## Issue 
Nurses at a health center should be able to skip the child scorecard activity in both individual (nutrition and SPV) encounters and group encounters (nutrition). The user should be provided with a popup notification that the encounter can be skipped.

<img width="341" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/4508044e-8218-4429-8cde-b688ddb2098f">

## Tasks
- Add a popup when entering child scorecard encounter "The Child Scorecard activity requires entering information on the pillars of child nutrition. Would you like to proceed? Yes, Proceed/No, Skip"
- Always make the activity optional - i.e. even if the user proceeds, they do not need to complete it (Currently, SPV requires completion)
- Coverage for ALL instances of child scorecard in Health Center setting.

**Comment by adamhstewart** [comment]
@anvmn is this deployed somewhere for testing?

**Comment by anvmn** [comment]
@adamhstewart 

PR was merged on Nov 28, and our last deploy to Nutrition env was on Nov 27.
So, the answer is no.

**Comment by adamhstewart** [comment]
@anvmn lets please deploy for testing then.

**Comment by anvmn** [comment]
@adamhstewart deployed to Nutrition env

**Comment by adamhstewart** [comment]
@anvmn This is great; however, we need to adapt this to group settings as well, using the same process. When a nurse clicks the Scorecard activity, the popup appears and if confirmed will remove the activities from the todo screen (for all patients).
