### ISSUE TITLE
HC Dashboard - Overview page [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#957]
## Issue 
<img width="332" alt="Notification_Center" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/16ddd2a3-ff87-4d55-806f-39532f6dbf0e">

This page is a menu only (not data) that leads to each of the pages for the subsections

## Task

- Creat and wire the page

**Comment by adamhstewart** [comment]
@balagan73 These issues can be checked on the CHW environment (https://chw-ihangane.pantheonsite.io/app/#dashboard/main) using a CHW account (e.g. PIN: 2929).

**Comment by balagan73** [comment]
@adamhstewart Are you sure I should use a CHW account? As I see there are 2 issues for the CHW dashboard, all other are for HC dashboard. https://github.com/TIP-Global-Health/eheza-app/issues/958 This issue even has comparison to CHW.

**Comment by balagan73** [comment]
https://chw-ihangane.pantheonsite.io/app/

## QA Review

### Checked and approved

1. Overview page has all the required sections.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/7068924d-9758-41d1-922b-f3565585026f)
