### ISSUE TITLE
HC Dashboard - Acute Illness Overview [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#958]
## Issue
![Overview](https://github.com/TIP-Global-Health/eheza-app/assets/688507/7839f50d-2a73-460d-b89f-68366362fb15)

### Comparison to CHW
Total # of Assessments - AI Encounters at the Health Center level  
HC Level Cases - ~Cases with an active follow-up at the HC AND have had a HC encounter~ Number of cases with a diagnoses from a HC Encounter (referred or not)
Hospital Referrals - number of referrals to Hospital from HC only
~Diagnosis Undetermined - same~ DO NOT CREATE
~Fever of Unknown Origin - same~ DO NOT CREAT
Graph - Fever diagnosis from diagnoses made at the HC

## Tasks
- Create the page
- wire the data

**Comment by anvmn** [comment]
@adamhstewart 

> Hospital Referrals - different - number of referrals to Hospital from HC

Checked the code. We do not differentiate between referral to hospital, or health center.
This means that currently, at CHW dashboard we count both referrals to HC and hospital.
If we need this separation, we'll need a non trivial development that will divide acute illness data into 2 - data from CHWs and data from Nurses. Estimation for this is 8h.

**Comment by adamhstewart** [comment]
@anvmn updated the requirements regarding the segmentation of data. We will need to do this at the CHW level as well (new issues will be created)

In the meantime, I am providing a more detailed definition of each data point to be clear of the segmentation.

**Comment by adamhstewart** [comment]
@anvmn made a small change above in original description:

HC Level Cases - ~Cases with an active follow-up at the HC AND have had a HC encounter~ Number of cases with a diagnoses from a HC Encounter (referred or not)

**Comment by balagan73** [comment]
## QA Review

### Found issues and questions

1. Covid cases created by a nurse (fever, cough, no covid test) don't show up in the overview as causes of fever, neither on the Covid tab. The Total number of cases is increased, so data is clearly synced.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/dbfcd3ca-9df7-407e-bb26-b5950be96bc2)
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/92e08b33-b815-47ed-a523-60d78e7001ed)
