### ISSUE TITLE
HC Dashboard - Acute Illness - Covid [3h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#959]
## Issue
![COVID](https://github.com/TIP-Global-Health/eheza-app/assets/688507/4dd72646-b594-44a7-8a8a-b3f4b0e7b31b)

### Comparison to CHW
- Hospital Referrals - different - number of referrals to Hospital from HC for Covid
- Currently Under Care - same

## Tasks
- Create the page
- wire the data

**Comment by anvmn** [comment]
@adamhstewart 

> Hospital Referrals - different - number of referrals to Hospital from HC for Covid

This requires definition.
Both Nurse and CHW can refer patient to hospital, and as far as I can tell, CHW got several paths for it. Maybe nurse as well.

**Comment by adamhstewart** [comment]
Putting on hold because we may not do Covid

**Comment by adamhstewart** [comment]
@anvmn remove the two unused data cards.
