### ISSUE TITLE
HC Dashboard - Acute Illness - Malaria [3h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#960]
## Issue
![Malaria](https://github.com/TIP-Global-Health/eheza-app/assets/688507/e67f69eb-fac2-4691-a090-ff7dab1e144e)

### Comparison to CHW
- Diagnosed Cases - Number of malaria diagnoses made at the HC only
- Hospital Referrals - Number of referrals to Hospital for malaria from HC only

## Tasks
- Create the page
- wire the data

**Comment by balagan73** [comment]
https://chw-ihangane.pantheonsite.io/app

## QA Review

### Found issues and questions:

- None

### Checked and approved

1. Only malaria cases created at the HC level are displayed.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/c041f2bf-1c44-496f-a583-d71721d90821)
