### ISSUE TITLE
HC Dashboard - Acute Illness - Gastro [3h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#961]
## Issue
![Gastro](https://github.com/TIP-Global-Health/eheza-app/assets/688507/934c2e6f-6601-427c-bfb1-24f41ae64596)

### Comparison to CHW
- diagnosed cases - Number of gastro diagnoses made at the HC only
- Hospital Referrals - Number of referrals to Hospital for gastro from HC only

## Tasks
- Create the page
- wire the data

**Comment by adamhstewart** [comment]
@anvmn definitions updated per https://github.com/TIP-Global-Health/eheza-app/issues/959#issuecomment-1832753019

**Comment by balagan73** [comment]
https://chw-ihangane.pantheonsite.io/app

## QA Review

### Found issues and questions

- None

### Checked and approved

1. Only gastro accute illnesses created by nurse display

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/1ef0916a-8786-4f6c-bc02-fb1fd088c39f)
