### ISSUE TITLE
HC Dashboard - Move Nutrition Section under new menu [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#962]
## Issue 
The existing nutrition section should be placed under nutrition in the new dashboard menu

<img width="552" alt="Cursor_and_Dashboard___Progress_Reports___Etc_–_Figma" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/60a372b0-295d-4b00-872a-21b62de729ca">

## Tasks
- move page

**Comment by balagan73** [comment]
https://chw-ihangane.pantheonsite.io/app/

## QA Review

### Found issues and questions

1. Not clear how the '% of Good nutrition' works. As @anvmn writes in the https://github.com/TIP-Global-Health/eheza-app/issues/982#issuecomment-1875863378 comment

> % Good Nutrition - percent of good nutrition encounters (group + individuals) from total encounters performed during selected month.

Some indication on the card about how to interpret this value would be helpful.

Before|After
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/26e91cca-7f3c-482d-8de8-42495fcfa576)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/083c7ff9-03f7-4350-a8aa-b5259e3b7149)

Adding one more data point lowered the good nutrition value to 60%
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/5235c58d-6380-4939-8534-ebc34d34c12e)

2. Numbers and months on the graph do not correlate to the horizontal and vertical lines. For example there are 10 vertical lines, and 12 months.


![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/aecec432-f36a-4d63-b628-fe43ad6b5bdf)


### Checked and approved

1. The Nutrition section displays as Child nutrition in the HC dashboard menu.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/61da6e93-ac2c-48eb-ac57-b9437a3ab4f8)
