### ISSUE TITLE
Health Center Dashboard - ANC [10h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#966]
## Issue

<img width="411" alt="Notification_Center" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/f78652cd-57a6-4e8e-8cdf-958d853eba20">

### Section 1

ANC Newly Identified Pregnancies | Number of new pregancies that were recorded at the health center only
Currently Pregnant Women | Number of women who are currently pregnant AND who have had an encounter at the HC
Within 4 months of due date | Number of women who are currently pregnant AND who have had an encounter at the HC
Health Center deliveries | Number of deliveries made by the HC ~(as reported only by a HC nurse)~
Hospital referrals | Number of referrals to Hospital for ANC from HC only
Number of women with 4 visits or more (include CHW and HC visit) | Number of women who have had 4 ANC visits or more(in any contect) AND who have had an encounter at the HC

### Section 2
High-Risk Pregnancies | Number of New High Risk Pregnancies in current month (in one or more of the below categories)
Syphilis | Number of new syphilis cases diagnosed at the HC in the current Month
Preeclampsia | Number of new preeclampsia cases diagnosed at the HC in the current Month
Eclampsia | Number of new eclampsia cases diagnosed at the HC in the current Month
Severe Anemia (<7gm/dl) | Number of new severe anemia cases diagnosed at the HC in the current Month
Gestational Diabetes | Number of new gestational diabetes cases diagnosed at the HC in the current Month
Malnutrition using MUAC (MUAC < 21 cm) for ANC new registration | Number of new malnutrition cases diagnosed through MUAC measurement at the HC in the current Month

## Tasks
- Create the page
- wire the data

**Comment by anvmn** [comment]
@adamhstewart 

### Section 1:

> ANC Newly Identified Pregnancies | Number of new pregnancies that were recorded at the health center only

This is not clear. What's the definition of 'pregnancy recorded at the health center only`?

> Health Center deliveries | Number of deliveries made by the HC (as reported only by a HC nurse)

The delivery location is recorded at postpartum encounter, and set either to facility or home:

![Selection_028](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/017e8110-fce0-47eb-a33a-1d2b7a45e5a0)

Please clarify the requirements.

**Comment by adamhstewart** [comment]
New pregnancy recorded at the health center is a pregnancy that is first recognized in eheza (ie first ANC encounter) that occurred at the health center. 

HC deliveries should include all reported health center deliveries from postpartum encounters that happened at the HC only

**Comment by anvmn** [comment]
@adamhstewart 

> HC deliveries should include all reported health center deliveries from postpartum encounters that happened at the HC only

Actually, as I checked now, it's a little bit more complex.
Pregnancy outcome is recorded on participant node, and this can be done from 2 locations:

![Selection_038](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/f6bfbd1b-80ef-4699-9ff4-17800d5b20f8)

If we record from postpartum, we have no problem. We see the encounter created, and can tell  if it was a nurse or chw.
The other one is a problem - participant node is edited with delivery location, but nothing else is recorded. We don't record info for nurse/chw that performed the action.
So, we have no way of telling where it was recorded.

**Comment by adamhstewart** [comment]
> If we record from postpartum, we have no problem. We see the encounter created, and can tell if it was a nurse or chw.
The other one is a problem -

@anvmn - we will adjust this data point to"Number of deliveries made by the HC" (regardless of where it was input) - changing the original description

**Comment by anvmn** [comment]
@adamhstewart 

At section 2, definition for Danger signs is missing.
Can you please add it?

**Comment by anvmn** [comment]
@adamhstewart 

> > If we record from postpartum, we have no problem. We see the encounter created, and can tell if it was a nurse or chw.
> > The other one is a problem -
> 
> @anvmn - we will adjust this data point to"Number of deliveries made by the HC" (regardless of where it was input) - changing the original description

Does that translate to "Number of deliveries made at facility"?
As per: 

![Selection_028](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/017e8110-fce0-47eb-a33a-1d2b7a45e5a0)

**Comment by anvmn** [comment]
@adamhstewart 

> Hospital referrals | Number of referrals to Hospital for ANC from HC only

Not sure I understand what `referrals to Hospital for ANC from HC only` means. 
Can you clarify please?

**Comment by adamhstewart** [comment]
> At section 2, definition for Danger signs is missing.

Any one of these conditions from the "Danger signs" subactivity:
<img width="1054" alt="Cursor_and_E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/9a87359a-fd17-45cd-b434-fbb1f7d2d57d">

> Does that translate to "Number of deliveries made at facility"?

Correct.

> Not sure I understand what referrals to Hospital for ANC from HC only means.

Patients who have been referred to the hospital as the result of an ANC encounter at the HC level.

**Comment by anvmn** [comment]
@adamhstewart 

Re danger signs, should the definition  be:

![Selection_044](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/a6c019a1-64e4-4be2-a879-bb0f24f9fa93)

?

**Comment by adamhstewart** [comment]
@anvmn yes - correct.

**Comment by balagan73** [comment]
## QA Review

### Found issues and questions

1. I have recorded patients with HIV. Known HIV, and also test was positive. The HIV data doesn't show up in the dashboard.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/f68734fc-8f88-44c0-ad8d-bf460e65f35c)

2. Referred the patient to the hospital, but data doesn't show.

Warning|Dashboard
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/e8cd9656-007c-4e36-b5fc-268fe125a27f)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/4f678f40-e70f-4eb5-a114-d713418350e9)

3. Syphilis doesn't show up

Next steps|Dashboard
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/9c8dca77-8841-4120-9c09-15f546f9d9be)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/950999a5-6952-4c5d-9f72-35c3caad28f6)

4. See point 3 here. There are 5 newly identified pregnancies, with 3 total number of high risk pregnancies.  I have added 1 more pregnancy, newly identified pregnancies were raised to 6, total number of high risk pregnancies were raised from 3 to 5. See image at checked and approved.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/9d8776cc-6f16-4838-9d68-3c05b1d410f0)


### Checked and approved

1. Except the above mentioned problems the numbers are displayed correctly

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/d532d93d-7d08-41c0-8ed5-864e35facecf)
