### ISSUE TITLE
HC Daschboard - NCD - Hypertension [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#968]
## Issue 
![Hypertension](https://github.com/TIP-Global-Health/eheza-app/assets/688507/cadf3726-c3b7-4f67-bf63-4bb22cb2ba9b)

Data | Definition
--|--
Chronic Hypertension Cases | Number of chronic hypertension cases (individuals patients seen) under care at the HC
Hypertension - New cases | Number of new cases of hypertension diagnosed at the HC  in the current Month

## Tasks
- Create the page
- wire the data

**Comment by anvmn** [comment]
@adamhstewart 

There are 5 cards but only 2 got definition. Should there be only 2 cards on the page?

> Number of chronic hypertension cases (individuals patients seen) under care at the HC

This is not clear. At NCD we have stage 1, 2 and 3 for hypertension. Chronic / Gestational are diagnosed at ANC. So, what do we consider as chronic?
Also, what does `under care at the HC` means?

> Number of new cases of hypertension diagnosed at the HC in the current Month

Can we define 'New case' as first hypertension diagnosis (of any stage) for patient?
Also, NCD encounter allows to record diagnoses that were made at other facilities before first NCD visit or in between visits. For example:

![Selection_065](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/72045662-ca0b-41ae-860c-c493632de4a4)

Should these be somehow accounted for?

**Comment by adamhstewart** [comment]
> There are 5 cards but only 2 got definition. Should there be only 2 cards on the page?

only two cards on this page.

Chronic Hypertension is any level hypertension - "under care" means has had an NCD encounter.

> Can we define 'New case' as first hypertension diagnosis (of any stage) for patient?

First diagnosis of hypertension (any stage) DO NOT include previously diagnosed cases.

**Comment by balagan73** [comment]
## QA Review

### Found issues and questions

- None

### Checked and approved

1. Hypertension entered at an NCD encounter shows up correctly.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/0ed8d7c5-d7ea-41f1-b6e7-5f146b2d24b3)
