### ISSUE TITLE
HC Dashboard - NCD - HIV [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#969]
## Issue 
![HIV](https://github.com/TIP-Global-Health/eheza-app/assets/688507/af4b7755-c886-4f93-9c0c-dff69d1060dc)

Data | Definition
-- | --
Total Cases | Number of individual patients with HIV seen at the HC in NCD context
Managed by PMTCT at HC | Number of individual patients (mothers) with HIV who are also in a PMTCT group
Managed by HC | remove

## Tasks
- Create the page
- wire the data

**Comment by anvmn** [comment]
@adamhstewart 

> Number of individual patients with HIV seen at the HC in NCD context

How do we define patient with HIV?
There's an HIV test patient should take once, where we ask if patient is known as positive for HIV, and if not, we record test result.
Also, NCD encounter allows to record diagnoses that were made at other facilities before first NCD visit or in between visits (see https://github.com/TIP-Global-Health/eheza-app/issues/968#issuecomment-1853589588).
So, what should be the overall definition?

> Number of individual patients (mothers) with HIV who are also in a PMTCT group

When patient tests positive for HIV, there are certain conditions at which we refer patient to HIV program (I suppose that this is the PMTCT group).
However, we have no knowledge is patient attends the group.
So, what should be the conditions for this counter?

**Comment by adamhstewart** [comment]
> There's an HIV test patient should take once, where we ask if patient is known as positive for HIV, and if not, we record test result.
> Also, NCD encounter allows to record diagnoses that were made at other facilities before first NCD visit or in between visits (see https://github.com/TIP-Global-Health/eheza-app/issues/968#issuecomment-1853589588).

A yes to a previous diagnosis OR a positive test result. 

> However, we have no knowledge is patient attends the group.
> So, what should be the conditions for this counter?

By their participation in a PMTCT group

**Comment by adamhstewart** [comment]
> A yes to a previous diagnosis OR a positive test result.


@anvmn reversal of previous decision DON NOT include previously diagnosed at another facility.

**Comment by balagan73** [comment]
## QA Review

### Found issues and questions

1. How do I refer a patient to PMTCT group during NCD encounter? 
^^@anvmn  

### Checked and approved

1. NCD encounter HIV cases show up correctly.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/7d665e8b-73a9-4fb5-a6ee-25c83d843b31)
