### ISSUE TITLE
HC Dashboard - NCD - Diabetes [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#970]
## Issue 
![Diabetes](https://github.com/TIP-Global-Health/eheza-app/assets/688507/ee866ee4-b822-4369-a101-d67d2b5914cb)

Data | Definition
-- | --
Total Diabetic cases | Number of individual patients with diabetes seen at the HC in NCD context
Diabetes New cases | Number of new cases of diabetes seen at the HC in NCD context
Gestational Diabetes | Number of individual patients with gestational diabetes seen at the HC in ~NCD~ ANC context

## Tasks
- Create the page
- wire the data

**Comment by anvmn** [comment]
@adamhstewart 

> Number of individual patients with diabetes seen at the HC in NCD context

Should we count only the cases diagnosed at NCD encounter, or also account for diagnoses that were made at other facilities before first NCD visit or in between visits (see https://github.com/TIP-Global-Health/eheza-app/issues/968#issuecomment-1853589588).

> Number of new cases of diabetes seen at the HC in NCD context

Can we define 'New case' as first diabetes diagnosis for patient at NCD?
Also, what about diagnoses from other facilities?

> Number of individual patients with gestational diabetes seen at the HC in NCD context

'Gestational' is concept from ANC. At NCD we have no distinction.
So, what should the definition be?

**Comment by adamhstewart** [comment]
> Should we count only the cases diagnosed at NCD encounter, or also account for diagnoses that were made at other facilities before first NCD visit or in between visits

BOTH but they must have an NCD encounter which acknowledges one or the other.

> Can we define 'New case' as first diabetes diagnosis for patient at NCD?
Also, what about diagnoses from other facilities?

New case  should be any new case in the NCD context whether it was diagnosed at the encounter or recorded as previously diagnosed.

**Comment by adamhstewart** [comment]
> New case should be any new case in the NCD context whether it was diagnosed at the encounter or recorded as previously diagnosed.

@anvmn reversal of the previous statement - new cases should ONLY count new diagnosis NOT previously;y diagnosed an another facility

**Comment by adamhstewart** [comment]
> 'Gestational' is concept from ANC. At NCD we have no distinction. So, what should the definition be?

@anvmn edited the description.

**Comment by balagan73** [comment]
## QA Review

### Found issues and questions

### Checked and approved

1. Diabetes entered during NCD encounter are showing up correctly.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/48bd3771-0467-48ba-b924-af6c3acf031b)
