### ISSUE TITLE
Changes to CHW Dashboards ANC [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#971]
## Issue

Some of the data shown in CHW Dashboards needs to be segregated to show only patients that have been seen by the CHW

Data | Definition
-- | --
New Case Followed | NEW ANC Participants At the CHW level
Currently Pregnant | Number of women who are currently pregnant AND who have had an encounter at the CHW
Within 4 month of due date | Number of women who are within four months of due date AND who have had an encounter at the CHW
With Danger Signs | Number of women who are currently pregnant AND have danger signs AND who have had an encounter at the CHW

## Task
- update the definitions

**Comment by anvmn** [comment]
@adamhstewart 

Just to make sure we're on the same track, CHW is shown the data of a village they have selected. Therefore all data presented is only of residents of that specific village.

**Comment by anvmn** [comment]
@adamhstewart 

> Number of women who are currently pregnant AND have danger signs AND who have had an encounter at the CHW

So far, we were counting active pregnancies that `got an encounter at
selected month, where danger signs where recorded`.
Is that what you mean by `have danger signs`?

**Comment by adamhstewart** [comment]
> Just to make sure we're on the same track, CHW is shown the data of a village they have selected. Therefore all data presented is only of residents of that specific village.

This is correct but also, where indicated, we are only tracking patients/cases who have CHW-level encounters (and not patients from the village who have had only HC encounters)

> So far, we were counting active pregnancies that got an encounter at selected month, where danger signs where recorded.
> Is that what you mean by have danger signs?

No - danger signs should be considered a permanent condition until it is "cleared" That is if a patient had a danger sign last month and has not been seen, she would still be counted. If she had a danger sign last month, but this month she had an encounter and she has no danger signs, then she is not counted.

**Comment by anvmn** [comment]
@adamhstewart 

Re danger signs, should the definition  be:

![Selection_044](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/a6c019a1-64e4-4be2-a879-bb0f24f9fa93)

?

**Comment by adamhstewart** [comment]
@anvmn no, this issue is about changes to the CHW dashboard. I'm using the "HC Dashboard" label because all of this work is being done within this effort

**Comment by anvmn** [comment]
@adamhstewart  

> @anvmn no, this issue is about changes to the CHW dashboard. I'm using the "HC Dashboard" label because all of this work is being done within this effort

Right, added the comment at wrong issue.
Moved to https://github.com/TIP-Global-Health/eheza-app/issues/966#issuecomment-1854387147.

**Comment by balagan73** [comment]
https://chw-ihangane.pantheonsite.io/app/#dashboard/

## QA Review

### Found issues and questions

- Just experimented with a twin delivery. I had to start a new antenatal encounter again to add the twin sibling, thus it resulted in 2 pregnancies for the twins. Not sure if it is a problem.

### Checked and approved

All numbers show up properly. 
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/136e59a6-f968-461f-8989-b0d893b520a9)
