### ISSUE TITLE
Changes to CHW Dasboards - Acute Illness [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#972]
## Issue

Some of the data shown in CHW Dashboards needs to be segregated to show only patients that have been seen by the CHW

Data | Definition
-- | --
Total # of Assessments | Number of AI Encounters at the CHW level
Community Level Cases | Number of cases with a diagnoses from a CHW Encounter
HC Referrals | Number of referrals to HC from CHW only
Diagnoses undetermined | Number of undetermoned diagnoses from a CHW
Fevers of unkown origin | Number of fevers of unknown origin from a CHW
Graph | Adjusted to CHW Diagnoses only
Malaria |  
Diagnosed Cases | Number of cases diagnosed by CHW
Gastro |  
Diagnosed Cases | Number of cases diagnosed by CHW

## Task
- update the definitions

**Comment by balagan73** [comment]
https://chw-ihangane.pantheonsite.io/app/#dashboard/acute-illness

## QA Review

### Found issues and questions

1. Overview shows 0 number of assessments, which should be all right, as I did not enter any illness. Nevertheless the people under care in the Covid19 pane shows 16 patients.

Overview|Covid19
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/93b7ad0b-0f8a-4573-9eb1-818451f50ae1)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/42596e09-200e-444d-aa11-2303c952d5c7)


2. In the Malaria tab Resolved cases/currently in care shows 0:10, when all data is 0.
The Gastro pane shows 0:0 with all data being 0.

Malaria|Gastro
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/f467d562-e883-414b-bb5d-c7d6448219d2)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/390c9265-45d2-432d-b6c7-c96591ae8bc9)

3. Not related to this issue, but the Contact Exposure activity in the Exposure/Travel history displays !!!! characters.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/6170362d-6011-4a39-99b3-1b28d784d85a)


### Checked and approved


1. Besides the questions above, the data shows up as expected.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/7527d4fb-b4ae-4982-adbd-aafda2a2bd00)
