### ISSUE TITLE
Patient Record - Antenatal - Overview Screen [12h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#98]
## Issue 

Adult patients will have an overview screen on their patient record that mimics case management. At the top, there will be a tab for each of the potential report types that the patient has. For example, an adult female patient will have tabs for Acute Illness, Antenatal, and Demographics.

Below the tab for Antenatal Care will be a list of all the patient's past and ongoing antenatal progress reports. 

These are organized into 4 columns:

- Pregnancy Start - What is the date that this pregnancy was opened in e-eheza, should be the first time seeing a CHW or Nurse for this pregnancy. 
- Status - label with open (white text on the TIP red) for a current pregnancy OR concluded (white text on the tip teal) for a pregnancy that has a recorded outcome
- Pregnancy Conclusion- what date was this pregnancy concluded either when the child was born or we closed the pregnancy for another reason 
- See more - arrow buttons (reference the navigation issue for more info - Patient Record - Navigation  #88)

<img width="590" alt="Screen Shot 2022-01-07 at 2 19 40 PM" src="https://user-images.githubusercontent.com/77505464/148595821-38e30685-bb3c-4ef7-8189-a495b4c8be68.png">

## Design 
Designs for all patient record screens can be found in Figma [here](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=470%3A5237) (under dashboards / case mgmt / progress reports)

## Tasks 
- Create overview screen 
- Style per design
- Logic for open vs concluded

**Comment by anvmn** [comment]
@jeanette-pelizzon @isapisa 

This issue is very much underestimated:

1. This is a first time we need present summary of all pregnancies, so there's a need fot not only display, but also fetch required data.
2. So far, antenatal report was accessed only from encounter page. Extending this to additional origin is not a trivial task.
3. As we did with Acute Illness progress report, there're may be adjustments needed to display completed preganancy report.

**Comment by adamhstewart** [comment]
@anvmn according to the design suggestion the "open" label should be teal, in fact it is red:

![image](https://user-images.githubusercontent.com/688507/156373562-ffd4fa7a-3d2c-42d8-b772-0aa5bbd9df0d.png)

Likewise "concluded" is teal and should be red.

![image](https://user-images.githubusercontent.com/688507/156373857-463755b6-3dc8-494d-82e3-3d53045d7473.png)

**Comment by adamhstewart** [comment]
@anvmn can you also make a note about how "conclusion" is stored here? What about pregnancies that are not manually concluded.

**Comment by anvmn** [comment]
@adamhstewart 

There's inconsistency in the design. At AI, we have ONGOING as red:
![Selection_567](https://user-images.githubusercontent.com/17882245/157401308-3de5e687-6e10-466d-9237-e7815b4e3a0b.png)

Also, at progress report:
![Selection_568](https://user-images.githubusercontent.com/17882245/157401394-53d2f1f8-62b1-4a5e-b249-7167c0711c5c.png)

I don't think Antenatal is special in any way.

//cc @jeanette-pelizzon

**Comment by anvmn** [comment]
@adamhstewart 

> can you also make a note about how "conclusion" is stored here? What about pregnancies that are not manually concluded.

Preganancies that are not concluded are considered open.
However, there's no option to start a new pregnancy before you close previous instance.

**Comment by jeanette-pelizzon** [comment]
@adamhstewart i've made things that are alerts or need attention to in red to draw attention. Resolved things or things that are good now are in teal. So teal means "we're good here" and red means "hey check this out asap"

**Comment by anvmn** [comment]
@adamhstewart we had discussed this few weeks ago, and concluded there's no problem.
Moving this to QA column.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/

### QA Review

### Found issues and questions:

1. Issue description says about Pregnancy start:
"What is the date that this pregnancy was opened in e-eheza, should be the first time seeing a CHW or Nurse for this pregnancy."
The Pregnancy date doesn't reflect when the pregnancy was opened in e-heza, but when it actually started. I think that's OK. If not, I recommend also changing the column name to Pregnancy opened or something more descriptive.

### Checked and approved:

![1-patient-record](https://user-images.githubusercontent.com/3536805/177961561-9c424afe-c09e-4204-be94-54ddd7975136.png)

1. Status column has labels with red background for Open, and with teal background for Concluded pregnancies.

2. Other columns contain correct information.

**Comment by jeanette-pelizzon** [comment]
> Issue description says about Pregnancy start:
"What is the date that this pregnancy was opened in e-eheza, should be the first time seeing a CHW or Nurse for this pregnancy."
The Pregnancy date doesn't reflect when the pregnancy was opened in e-heza, but when it actually started. I think that's OK. If not, I recommend also changing the column name to Pregnancy opened or something more descriptive.


The issue description is confusing. That's my fault. It should be the date the pregnancy actually started with the patient so it seems to be operating correctly. I will move to acceptance testing. Thanks!
