### ISSUE TITLE
HC Dashboard - Well child - Overview [8h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#981]
## Issue 

![Overview](https://github.com/TIP-Global-Health/eheza-app/assets/688507/52174659-22f6-4817-9c9d-0f3e0dd9a84b)

Number of children seen - Number of children seen for SPV at the HC level
% ECD on track / behind (pie chart) - % of children who have been seen at at an SPV who are currently on track/behind
% on Track for Vax v Not. on Track (pie chart) - % of children who have been seen at at an SPV who are currently on track/behind

## Task
- Create the page (and charts)
- wire the data

**Comment by anvmn** [comment]
@adamhstewart 

For all points - can you please define time period?

> Number of children seen - Number of children seen for SPV at the HC level

- Can we define this as number of children that had at least one SPV encounter during time period?
- We'll soon have SPV for CHW. Should we include only for nurses or both nurses and CHWs.

> % ECD on track / behind (pie chart) - % of children who have been seen at at an SPV who are currently on track/behind
% on Track for Vax v Not. on Track (pie chart) - % of children who have been seen at at an SPV who are currently on track/behind

- On track - all encounters indicate on track over time period?
- Off track - one or more encounters indicate on track over time period?
- What is the yellow part?

> % on Track for Vax v Not. on Track (pie chart) - % of children who have been seen at at an SPV who are currently on track/behind

Do we show immunisation data from SPV only? There's similar data at Child Scorecard encounter.

**Comment by adamhstewart** [comment]
> For all points - can you please define time period?

month

> Can we define this as number of children that had at least one SPV encounter during time period?

Correct

> We'll soon have SPV for CHW. Should we include only for nurses or both nurses and CHWs.

For HC encounters only

> On track - all encounters indicate on track over time period?
> Off track - one or more encounters indicate on track over time period?
> What is the yellow part?

In the second question, I think you meant "off track" in which case that and the first statement are correct. The yellow can be ignored, there is no "middle".

> Do we show immunisation data from SPV only? There's similar data at Child Scorecard encounter.

From any immunization activity (or update).

**Comment by balagan73** [comment]
## QA Review

### Found issues and questions

1. Not strictly related to this issue, but under the danger signs activity if I save the form with data, that triggers an acute illness warning, 
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/985d664a-ef0c-4f6e-af4e-26129d5625f7)
and then I cancel and go back to the form, it is not possible to unselect all the checkboxes, only by clicking the 'None of these'  option on the bottom. But afterwards, the baby is still diagnosed with danger signs.

https://github.com/TIP-Global-Health/eheza-app/assets/3536805/5de2b8f5-1cef-4c10-99f6-7cedeb461818

Vitals|Symptom review
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/2aa3f3b7-b855-4d93-b5ae-c0956e9f358c)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/2252ce63-48b4-4b0d-9808-5b3ad5747829)

### Checked and approved

1. SPV encounters at the HC level show up correctly on the Overview page.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/3b34efc8-db50-45ff-9bad-26355093de25)
