### ISSUE TITLE
HC Dashboard - Well child - Nutrition [8h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#982]
## Issue
![Nutrition](https://github.com/TIP-Global-Health/eheza-app/assets/688507/0cbd15a7-963c-4452-8616-ce688f61bfd9)

| Percentage Good Nutrition | Patients with good nutrition (absence of malnutrition) over the total population (5 and under) - should match Nutrition dashboards
| Total encounters complete | Nutrition encounters at the HC - should match nutrition dashboard
| Total beneficiares wasting | # of children who have moderate or acute wasting 
| Incidence of Wasting | # of children who are new wasting cases in this month
| Stunting | # of children who have moderate or acute stunting
| Micro/Macrocephaly | # of Children who have either micro or macrocephaly
| Diagnosed Malnourished | # children who are diagnosed with malnutrition

## Tasks
- Create the page (and charts)
- wire the data

**Comment by anvmn** [comment]
@adamhstewart 

For the context, info of what is presented on Nutrition dashboard:
- Data is for current year. We also collect data for past year, to be able to calculate % diff.
- Data is divided by group type (fbf, pmtct, ...) and individual.
- Individual is only Nutrition encounters. No SPV encounters data included.. No separation between nurse and CHW encounters.

Questions for all cards:

1. What data needs to be included? Is it similar to Nutrition dashboard (no SPV)?
2. What is time period? Should it be same as Nutrition dashboard (current year). What is time period if we scroll back? Note that we allow going back 6 months, so there is an option we'll slide into previous year (on Jan 2024, going back one month brings us to 2023).

> | Percentage Good Nutrition | Patients with good nutrition (absence of malnutrition) over the total population (5 and under) - should match Nutrition dashboards
 
- What patients are we looking at? Would it be correct to define as a patient that had at least one encounter during defined time period?
- Should we present complete data - CHW + nurse, or only nurse?

> | Total encounters complete | Nutrition encounters at the HC - should match nutrition dashboard

What do we define by encounters at HC? Nutrition dashboard includes both nurse and CHW encounters.

> | Total beneficiares wasting | # of children who have moderate or acute wasting
| Stunting | # of children who have moderate or acute stunting
| Micro/Macrocephaly | # of Children who have either micro or macrocephaly
| Diagnosed Malnourished | # children who are diagnosed with malnutrition

Do we define this as # of children that had at least one diagnosis for this over the time period?

> | Incidence of Wasting | # of children who are new wasting cases in this month

Do we define this as # of children that had first diagnosis for this in current month over the time period?

**Comment by adamhstewart** [comment]
> What data needs to be included? Is it similar to Nutrition dashboard (no SPV)? 

It should include any time that nutrition is measured and evaluated (so including also SPV)

> What is time period? What patients are we looking at? Would it be correct to define as a patient that had at least one encounter during defined time period?

The time period is for the month and should include any patients that have had an encounter in that month.

> Should we present complete data - CHW + nurse, or only nurse? 

This dashboard should be based on Nurse encounters only.

> What do we define by encounters at HC? Nutrition dashboard includes both nurse and CHW encounters.

This dashboard should be based on Nurse encounters only.

> Do we define this as # of children that had at least one diagnosis for this over the time period?

Diagnosed malnutrition = prevalence (the number of currently malnourished children who were diagnosed either this month or a previous month but whose condition is not improved to good nutrition)

> Do we define this as # of children that had first diagnosis for this in current month over the time period?

Yes Incidence is new diagnoses in the defined time period (current month).

**Comment by anvmn** [comment]
@adamhstewart 

This is how I understand the requirements. Please confirm / correct:

- % Good Nutrition - percent of good nutrition encounters (group + individuals)  from total encounters performed during selected month.
- Total encounters complete  - Total Nutrition encounters (group + individuals) performed during selected month.
- Total beneficiaries wasting - # of children who had moderate or acute wasting diagnosed at encounter during selected month or previously, and did not have an encounter afterwards that indicated that condition was resolved.
- Incidence of Wasting - # of children who are had firs diagnosis of wasting during selected month
- Stunting - # of children who had moderate or acute stunting diagnosed at encounter during selected month or previously, and did not have an encounter afterwards that indicated that condition was resolved.
- Micro/Macrocephaly - # of Children who had either micro or macrocephaly diagnosed at encounter during selected month or previously, and did not have an encounter afterwards that indicated that condition was resolved.
- Diagnosed Malnourished - # children who had malnutrition diagnosed at encounter during selected month or previously, and did not have an encounter afterwards that indicated that condition was resolved.

**Comment by balagan73** [comment]
@adamhstewart @anvmn As one PR is still open, are you sure I should already do the QA?

**Comment by anvmn** [comment]
@balagan73 no problem proceeding with QA.
The comments at PR do not require changes.

**Comment by balagan73** [comment]
https://chw-ihangane.pantheonsite.io/

## QA Review

### Found issues and questions

1. Not clear how the '% of Good nutrition' works. As @anvmn writes in the https://github.com/TIP-Global-Health/eheza-app/issues/982#issuecomment-1875863378 comment

> % Good Nutrition - percent of good nutrition encounters (group + individuals) from total encounters performed during selected month.

Some indication on the card about how to interpret this value would be helpful.

Before|After
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/26e91cca-7f3c-482d-8de8-42495fcfa576)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/083c7ff9-03f7-4350-a8aa-b5259e3b7149)

Adding one more data point lowered the good nutrition value to 60%
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/5235c58d-6380-4939-8534-ebc34d34c12e)

2. Numbers and months on the graph do not correlate to the horizontal and vertical lines. For example there are 10 vertical lines, and 12 months.


![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/aecec432-f36a-4d63-b628-fe43ad6b5bdf)



### Checked and approved

**Comment by anvmn** [comment]
@balagan73 you're checking the wrong page.
See issue description.

**Comment by balagan73** [comment]
## QA Review

### Found issues and questions

1. How do I enter head circumference data? I don't see an option during Nutrition encounter.

### Checked and approved

1. Displayed data is correct.

![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/15933346-51d9-4187-a9f7-28ec2f6d8737)

**Comment by balagan73** [comment]
@anvmn I have added the findings of https://github.com/TIP-Global-Health/eheza-app/issues/982#issuecomment-1886601641 to the https://github.com/TIP-Global-Health/eheza-app/issues/962 issue. Even if that issue is about only adjusting the menu, it is more related to that.

**Comment by anvmn** [comment]
@balagan73 

> How do I enter head circumference data? I don't see an option during Nutrition encounter.

It only appears at SPV (Well Child) encounter.

> @anvmn I have added the findings of [#982 (comment)](https://github.com/TIP-Global-Health/eheza-app/issues/982#issuecomment-1886601641) to the #962 issue. Even if that issue is about only adjusting the menu, it is more related to that.

Well, this is something that exists for years,, and there are no changes there. Only page location.
