### ISSUE TITLE
Cut release 1.5.2 [2h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#984]
## Issue 

Cut release for the following issues:
- #953 
- #954 
- #978 

## Tasks
- Create the release and add text to notes:

This release fixes a bug in the pregnancy dating calendar and provides two new features related to child scorecard functionality and workflow.

The specific issues addressed in this release are:

- Fixes a bug where, in some cases, the pregnancy dating calculator opened to the wrong default date - it will now open to a default date based upon the question: When was the Patient's Last Menstrual Period?
- Allows a nurse at the Health Center to skip the Child Scorecard activity in nutrition encounters, standard pediatric encounters, and group encounters via a popup message that, when answered appropriately, will remove the subactivity from the activity tray.
- Allows a nurse at the Health Center to move back and forth easily between a Child Scorecard and the Patient Progress Report.

**Comment by anvmn** [comment]
@adamhstewart done

New release: https://github.com/TIP-Global-Health/eheza-app/releases/tag/v1.5.2
