### ISSUE TITLE
Reorganise Directory structure [8h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#985]
## Issue

reorganize directory structure to avoid large number of files per directory.

**Comment by anvmn** [comment]
Current state per Pantheon:

![Selection_095](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/d6c8ec3f-0bd2-4622-b940-a1c2d565c240)

**Comment by anvmn** [comment]
### For the context:

- Vast majority of files at `private` directory are photos.
- When device downloads content that contains a photo, it gets a link to `patient-photo` image style file, and stores it at `deferredPhotos` table at IndexedDb. After sync phase completes all steps, Download photos in background is activated and photos are fetched one by one.
- In case image style of photo does not exist, it will be created on fly as device tries to fetch it.
- Files for `patient-photo` image style are stored at `private/styles/patient-photo/private`, hence 278K files there.
- To the best of my knowledge, there's no retention at image style folder - if image style for photo was created, it remains until explicitly deleted.

**Comment by anvmn** [comment]
### Development:

#986 introduces:

1. A mechanism to relocate uploaded photo into dedicated storage folder `storage-MM-YYYY`, according to file creation date.
2. Drush script that moves files from `private` folder into dedicated storage folder.

**Comment by anvmn** [comment]
### Testing script (on multidev):

1. It takes about 1 minute to relocate 100 files. So, relocating 325K files should take around 55 hours.
2. Every now and then, experienced failures during script run. Script would get 'stuck' for few minutes, or fail to create storage folder, or would fail to move files. Script is written in a way that when rerun, it picks up from point of previous failure, but it will extend process execution. For example:

![Selection_096](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/35bb2a83-fead-41c0-93c9-f5b4bf56d229)

It is possible that multidev is not as stable as live envs, so on live we may experience less problems.

3. It seems that script run does not affect performance.
4. After 3 days, I'm still left with ~50K files that require relocation, so, after all is completed, will need to see that total files size was not affected.

**Comment by anvmn** [comment]
Process started on live:

![Selection_446](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/ab7e96a7-faaa-4716-a696-c7c8c551fdd4)

**Comment by anvmn** [comment]
After 24.5h run, 152K files handled:

![Selection_447](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/be2e0199-21d7-4697-8de8-5e4f64a967f4)

**Comment by anvmn** [comment]
8K left to process:

![Selection_449](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/6f63e36f-5751-4095-8cb1-29c5802119bc)

**Comment by anvmn** [comment]
Done:

![Selection_451](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/a2807267-d738-406f-a631-4bf87e73c07d)

**Comment by anvmn** [comment]
Pantheon error is gone. Closing...

![Selection_452](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/5754d83f-175d-444c-b1f4-1c61f45dc862)
