### ISSUE TITLE
Create Lab Technician user type [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#988]
## Issue
A pregnant woman comes to the lab and I look for her name in the Lab case management section. I see that labs were ordered for her (“ordered”). I open case management and enter all lab results that I performed or I document if labs were not performed. I complete the section and receive a review of lab results similar to the progress report (like IZs). I review and accept this. 

## Tasks
- Create a user (nurse) type that is a Lab Technician, this user type should be able to see only the case management section and the lab sections with in it.
- Create the entry screen for a lab tech - should contain only device status and case management.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app/#device

## QA Review

### Found issues

### Checked and approved

Nurse created with Lab Technician role. Entry screen contains only the Case management and Device Status activities. Under case management only the ANC Labs display. 

Entry screen|Case management
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/f07df5be-61df-4d2d-ac1b-3a3acb0bd38b)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/c589aac2-cdb8-40c2-b52c-13cf64a54988)
