### ISSUE TITLE
Allow Lab Tecnicians to enter labs for "paused" encounter [4h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#989]
## Issue

When a nurse indicates a test was able to be performed that day a case management followup should be created that indicates that the lab has been ordered. The lab technician should be able to click on the patient's name and open an encounter to enter the missing lab results.

<img width="757" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/c0b761ba-d36b-4d61-aa3d-cd041c3e2023">

## Tasks
- Allow lab tech to be able to access the second part of an ANC encounter for a patient who is awaiting lab results.
- Change the lab of the "pending" labs to "ordered"

**Comment by anvmn** [comment]
@adamhstewart 

Would it be correct to say that 'ordered' entries should be seen only by Lab Techs, and nurses should see an entry only when Lab tech has filled all of the results?

**Comment by adamhstewart** [comment]
> Would it be correct to say that 'ordered' entries should be seen only by Lab Techs, and nurses should see an entry only when Lab tech has filled all of the results?

No, because we don't want to break the existing workflow. The nurse should be able to see AND perform the operation.

**Comment by anvmn** [comment]
@adamhstewart 

> Change the lab of the "pending" labs to "ordered"

When we create an entry, it has expiration period of 35 days.
The entry says 'Pending' until 7 days before expiration.
After, it says 'Closing soon'.

So, for lab tech:
'Pending' => 'Ordered'
Closing soon' => ?

**Comment by adamhstewart** [comment]
@anvmn i think also “closing soon”

**Comment by balagan73** [comment]
## QA Review

### Found issues
- None
 
### Checked and approved:
1. Lab Technician sees Ordered items for paused encounters, where they need to enter lab results
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/7589ed99-b971-4ca2-be09-da7047ae9516)

2. When changing concluded date on the Lab results, Closing soon pill displays.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/2cc11a31-91b3-4478-9daf-ab2ba0140bf1)
