### ISSUE TITLE
Changes to Lab Results workflow for Lab Technicians [4h] 

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#990]
## Issue

Lab technicians perform the tests and enter the results, but they do not review the results with the patients. The lab tech should be given the opportunity to review the lab results that they entered on the Lab results report, before submitting them and closing the encounter.

<img width="905" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/b63f68bb-316d-46fb-ad6f-76328855fc18">

## Tasks
- When finished entering results, present the above review screen.
- remove the next steps sub activity.
- Remove the follow-up question for a positive syphilis result.

**Comment by balagan73** [comment]
https://nutrition-ihangane.pantheonsite.io/app

## QA Review

### Checked and approved

1. After entering the results, the two options to Submit and Edit the results are available
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/99912aa1-8929-4ec3-a841-f5762d1ac79e)
2. No follow up questions display for positive syphilis
3. No Next steps sub activity displays
