### ISSUE TITLE
Changes to Labs SubActivity workflow for Nurse [8h] 

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#992]
## Issue
At the moment, there are a series of questions for a nurse to determine if the test will be performed today and, if not, what day it was performed. This should be simplified to a single question which asks "Will this test be performed today?" On a "No" answer, the list of reasons (unaltered from original) should be displayed - on a "Yes" answer, the results should be queued for entry by the lab technician.

In addition to refining the date question, the nurse should be asked for each test, "Where was this test performed?" with the options "Point of Care" and "Lab" - if "Lab" is answered, the results should be queued for entry by the lab technician; if "Point of Care" is answered, the results should be entered on that screen (the behavior is already implemented for Random Blood Sugar).

Note: This logic should be implemented for ALL labs, including both those that were originally considered "Point of Care" by default (Like HIV and Malaria).

Also note: some labs (like random blood sugar) have extra questions for context - those should remain:

<img width="1073" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/3c3f111c-19be-4eda-bc00-b65600bd8cc6">

## Tasks
- Adjust the questions for determining if the lab should ordered for today.
- Allow each lab to be entered at point of care or by lab technician.

**Comment by anvmn** [comment]
@adamhstewart 

For the context, so far, we had 3 RDT and 7 non RDT labs.
Non RDT labs (from previous encounters), if not filled, could be completed at Labs History activity.
Per https://github.com/TIP-Global-Health/eheza-app/issues/258#issuecomment-1194496967, 4 of them had impact on next steps, and other 3 were for recording purposes only.

Since we make all labs universal, we have additional 3 labs to support - HIV, Partner HIV and Malaria.
What are the requirements for those activities, when it comes to filling them from Labs History?

**Comment by adamhstewart** [comment]
> What are the requirements for those activities, when it comes to filling them from Labs History?

Only that if taken at the lab rather than point of care, next steps for a positive diagnosis would occur in the nurse followup after the lab entry.

**Comment by anvmn** [comment]
@adamhstewart 

Here's a scenario:

Patient comes on 1/1: 
- Nurse fills Malaria lab to be taken at lab (initial phase of encounter).

Patient comes on 30/1:
- Malaria result was not entered. 
- At initial phase of encounter, only lab task is lab history (once completed, other task will appear).
- At lab history, there's an entry to complete Malaria test result.
- Nurse sets the result to positive.


What we have here is a result of test that was taken 30 days ago.
We can not apply standard diagnostics and next steps logic  here.

This is how we were dealing with this for 7 labs: 
- At 4 labs, when result showed illness, patient was referred to hospital.
- Remaining 3 labs - no action, no matter the result.

![Selection_153](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/a8ad7081-ed86-402f-89a8-e4af46c03c8f)

Now we have added 3 labs.
The question is what should be the actions if we see problematic result  (positive for Malaria / HIV).
Currently Partner HIV has no next steps, so it's not an issue.

**Comment by balagan73** [comment]
## QA Review

### Found issues and questions:
- None

### Checked and approved:

1.  Lab questions are updated for nurse:

Yes|No
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/feab238a-73e4-434a-bd90-488cd0fe2198)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/b047d316-118b-473b-a63c-71cc5f33c7f1)
