### ISSUE TITLE
Changes to Workflow for Nurse to Review results and Next Steps [6h]

### ISSUE THREAD

**Issue by adamhstewart** [TIP-Global-Health/eheza-app#993]
## Issue
After the lab Technician (or nurse) enters the lab results, the case management icon should change to "Ready for Review" to indicate that a nurse can now enter the encounter, review the labs, and continue with the next steps.

<img width="813" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/a8fe94f6-0fe7-48d9-aa34-d12caddb13b5">

Then: 
<img width="1302" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/4ec9f549-c246-445b-b964-49eb1ac87a15">

Followed by:
<img width="1180" alt="E-Heza_System" src="https://github.com/TIP-Global-Health/eheza-app/assets/688507/70bacbd8-bf6f-411a-8363-373e57a3b6d7">

NOTE: In some cases BP will need to be taken first before next steps appears.

## Tasks
- Change the logic and text for the case management "pill"
- Add lab review step before next steps
- Add a subactivity to Next Steps called "Treatment Review" (use same icon used in other modules to add followup questions for positive results. For example:
    - when Siphillus is positive we need to add the question "Please select one or more symptom that the patient is experiencing."
    - when HIV is positioned we need to ask the question "Does the Health center have an ARV program?"

**Comment by adamhstewart** [comment]
@anvmn I added this to the original issue:

- Add a subactivity to Next Steps called "Treatment Review" (use same icon used in other modules to add followup questions for positive results. For example:
    - when Siphillus is positive we need to add the question "Please select one or more symptom that the patient is experiencing."
    - when HIV is positioned we need to ask the question "Does the Health center have an ARV program?"

**Comment by balagan73** [comment]
## QA Review

### Found issues 

1. Maybe line height on the status pills could be smaller
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/865dc1ba-0a39-4102-8c1b-3a9e55e90ce2)

2. Grammar. Not related to this issue, but ARV should be preceeded by the indefinite article 'an'
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/59ef6179-3d32-4987-8148-3299de6abfc8)

### Checked and approved

1. Ready for Review status displays after Lab Technician enter lab results.
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/0e7aaa7c-8f93-473f-8196-a1fd9f292824)

3. Review & Accept option is available for Nurse
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/f563dd3c-cee2-4524-81e6-4d8bc9a02c36)

4. Review & Accept is followed by Next steps

1|2
-|-
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/5d475c15-9774-4674-a919-bd509e74fbb1)|![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/da6a35c8-1a10-4b6e-b2d7-b6ffb0187300)

5. HIV and Syphilis has Lab Results follow-ups
![image](https://github.com/TIP-Global-Health/eheza-app/assets/3536805/49efdce0-d49d-408c-a0f1-3007d703330b)

**Comment by adamhstewart** [comment]
- See if we can make pill one line
- Correct grammar

**Comment by anvmn** [comment]
@adamhstewart 

> * See if we can make pill one line

Only way to make it fit one line is making font smaller, and as I see this, it's smaller than acceptable, considering we run the app on mobile devices. Also, the translation may be longer that English, so it won't resolve the problem.

> * Correct grammar

Corrected grammar.
