### ISSUE TITLE
RM - Change the Schedule of Monthly Survey

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#996]
### Issue
Currently, the survey is conducted on a monthly basis. The proposal is to modify the survey timeline to occur at three key intervals: at the program baseline, at the 3-month mark, and at the conclusion of the program.

### To-Do
- Update the survey schedule.

**Comment by anvmn** [comment]
@adamhstewart 

Deployed to RM env (https://rm-ihangane.pantheonsite.io/)

**Comment by anvmn** [comment]
Deployed to live
