### ISSUE TITLE
RM -  Adoption Survey

### ISSUE THREAD

**Issue by Diama1** [TIP-Global-Health/eheza-app#997]
### Issue

HCWs are required to complete adoption surveys every 3 months as part of the program evaluation process. The survey is mandatory for accessing the messaging center on the designated days.

The adoption survey will be presented to HCWs at three specific stages:
1. At the baseline stage
2. At the 3-month mark in the program
3. At the end of the program ( after 6 months )

### To-Do
- Work on the design of the adoption survey.
- Style the survey as per design.

**Comment by anvmn** [comment]
@adamhstewart 

Deployed to RM env (https://rm-ihangane.pantheonsite.io/)

**Comment by anvmn** [comment]
Deployed to live
